### ISSUE TITLE
Support decimal values in stroke width field

### ISSUE THREAD

**Issue by Veethika** [uxbox/uxbox#1212]
## 🧩 Problem
For precise design works, being able to work with decimal values when it comes to strokes is crucial. Currently, the web app does not support decimal values for stroke width.
<img width="346" alt="Screen Shot 2021-09-14 at 11 01 30 AM" src="https://user-images.githubusercontent.com/35127763/133200414-d6259493-c69c-4cbb-9886-6a6b107a15af.png">

## ✨ Proposal
Allow decimal value inputs in the stroke width input field.

**Comment by elhombretecla** [comment]
Hi again @Veethika :)

We just created an enhancement to accomplish this as soon as we can.
[https://tree.taiga.io/project/penpot/issue/2035](https://tree.taiga.io/project/penpot/issue/2035)

Thank you so much!

**Comment by Veethika** [comment]
@elhombretecla Thank you so much for taking this up :)
