### ISSUE TITLE
Need : a shortcut for the "move" tool

### ISSUE THREAD

**Issue by maelomanontroppo** [uxbox/uxbox#1213]
**Description**
Each tool has its own shortcut : A for "Artboard", R for "Rectangle", E for "Ellipse" etc. 
I noticed Penpot doesn't have such a shortcut for the "Move" tool, wich happens to be the same at the "Select" tool (certainly a good choice).
I miss the shortcut because it's a common behaviour to switch between one of the tool and the move/select tool.

**Workflow description**
For exemple you draw many rectangle, then select to move one of them, then draw another rectangle and select artboard to make other features, then switch to select one of your component to copy it in the new artboard etc.
I made the description quite unreadeable on purpose to expose how fast and intuitive this behaviour is activated.

**A shortcut candidate**
The "V" key is probably the main "select/move" on design tools, as in many design apps.

**Comment by elhombretecla** [comment]
Hi @maelomanontroppo you're right, we just created an enhancement at Taiga for that.

[https://tree.taiga.io/project/penpot/issue/2037](https://tree.taiga.io/project/penpot/issue/2037)

Thanks for your feedback!

**Comment by maelomanontroppo** [comment]
My pleasure ;-)

**Comment by myfunnyandy** [comment]
Done (the shortctut is "V")
