### ISSUE TITLE
Unable to export artboards on self-hosted setup because of hardcoded Google Chrome path

### ISSUE THREAD

**Issue by Damillora** [uxbox/uxbox#1214]
**Describe the bug**
I was unable to export files (PNGs, PDFs) when running Penpot with the provided Docker images. 
I checked the logs, and it was a bit unclear at first, with the exporter's logs only showing that it's initializing browser pools, then request timeouts when I tried exporting.

After a look on the source code, I realized that Google Chrome's executable path [was hardcoded](https://github.com/penpot/penpot/blob/develop/exporter/src/app/browser.cljs#L106), which the exporter Docker container doesn't have. Symlinking `/usr/bin/google-chrome` to `/usr/bin/chromium` when building the Docker container fixes the problem and I was able to export once more.

**To Reproduce**
1.  Run a self-hosted instance, following the technical guide
2. Create a new design, then try exporting it.

**Expected behavior**
The export is successful. 

**Environment (please complete the following information):**
I'm running on a self-hosted instance. 

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Alpine Linux

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: Docker 20.10.8, Docker Compose 1.29.2
-   Image: latest

**Backend Stack Trace (if self-hosted)**

<details>

```
penpot-exporter_1         | [app.core] {:msg "initializing", :line 23}
penpot-exporter_1         | [app.browser] {:msg "initializing browser pool", :line 136}
penpot-exporter_1         | [app.http] {:msg "starting http server", :port 6061, :line 28}
penpot-exporter_1         | [app.http.impl] {:msg "Unexpected error", :error #object[TimeoutError TimeoutError: ResourceRequest timed out], :line 49}
penpot-exporter_1         | TimeoutError: ResourceRequest timed out
penpot-exporter_1         |     at ResourceRequest._fireTimeout (/opt/app/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
penpot-exporter_1         |     at Timeout.bound (/opt/app/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
penpot-exporter_1         |     at listOnTimeout (internal/timers.js:557:17)
penpot-exporter_1         |     at processTimers (internal/timers.js:500:7)
```

</details>

**Additional context**

**Comment by niwinz** [comment]
Clearly issue of the latest release, thanks for reporting it.
It will be fixed today probably.

**Comment by niwinz** [comment]
Should be fixed. Pull the latest image.

Additionally, please review the config.env changes, that may affect you. Some frontend options are converged into a single environment variable `PENPOT_FLAGS`. In this release it only affects frontend but the next release will unify it with backend.
