### ISSUE TITLE
line end style dropdown is not fully visible

### ISSUE THREAD

**Issue by OleksiySitka** [uxbox/uxbox#1216]
The dropdowns that select line end styles are going off the screen and last options are not visible and impossible to scroll to. Probably happens only on smaller screens (13'' MBP) and in cases when the browser window is not full screen. Also shadow options are displayed over this dropdowns.

**Steps to reproduce the behavior:**
1. Open Penpot (browser window should not be big, for example about 700px high)
2. Create a path object without closing it
3.  Add some fill color (optional, just reduces vertical space even more)
4.  In the Stroke options panel select either of the end style dropdowns
5.  **See that some options are off the screen it's impossible to scroll to see them**
6. Close the dropdown
7. Press "+" shadows panel and press 3 dots icon to open shadow options
8. **Open the end style dropdown again and see that shadow options panel is displayed over it**

**Expected behavior**
When the dropdown is open and off the screen user should be able to scroll to see all options. Other panels should not be displayed over dropdown.

**Screenshots**
<img width="287" alt="Screen Shot 2021-09-15 at 16 03 04" src="https://user-images.githubusercontent.com/2227457/133442553-3f956583-56a1-4004-87d0-7628c1cbdb87.png">
<img width="279" alt="Screen Shot 2021-09-15 at 16 02 36" src="https://user-images.githubusercontent.com/2227457/133442575-c5b32d93-820e-454c-a6c0-4b0c91b50429.png">

**Desktop:**
-   OS: macOS Mojave
-   Browser: Firefox 92.0 (64-bit)

**Environment:**
design.penpot.app

**Comment by elhombretecla** [comment]
Hi @AlexSleepy thanks for your feedback :)

We just created an issue at Taiga. You can track it progress here
[https://tree.taiga.io/project/penpot/issue/2039](https://tree.taiga.io/project/penpot/issue/2039)
