### ISSUE TITLE
Horizontal navigation using shift-scroll wheel

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#1217]
**Is your feature request related to a problem? Please describe.**
I want to navigate my canvas horizontally

**Describe the solution you'd like**
shift-scroll wheel

**Comment by elhombretecla** [comment]
Hi again @jsmorabito :)

Shift + scroll wheel is not working on your setup? Could you give us more info? Browser version, OS, Console errors, .... Thanks!!!

![horiz-scroll](https://user-images.githubusercontent.com/1045247/133456133-42e31a81-9fd3-4525-92df-6bc1c6862050.gif)

**Comment by jsmorabito** [comment]
- big sur 11.5.2
- Safari Version 15.0 (16612.1.28.1, 16612)

also tested on Brave Browser

no console errors

**Comment by elhombretecla** [comment]
Ok, we just created an issue at Taiga to manage this :)

[https://tree.taiga.io/project/penpot/issue/2040](https://tree.taiga.io/project/penpot/issue/2040)

**Comment by HafizKurniaAji** [comment]
I also experienced the same thing, can't scroll horizontally using `shift + vertical scroll wheel`.

My setup :
- MacOS Catalina 10.15.7
- Firefox 93.0b6 (64-bit)
- Google Chrome 93.0.4577.82 (x86_64)
