### ISSUE TITLE
Internal error when clicking on existing comment in comment list

### ISSUE THREAD

**Issue by mscofield0** [uxbox/uxbox#1219]
**Describe the bug**
When I click on a comment in the comment list, the site throws an Internal error. I can return to the project easily by clicking Retry though.

**To Reproduce**
1. Insert a comment
2. Go to comment list
3. Click on comment

**Expected behavior**
I wanted to see an option menu so I could delete the comment from the comment list

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser: Firefox
-   Version: 92.0

**Environment (please complete the following information):**
Using SAAS at https://design.penpot.app.

**Additional context**
My friend has no such issue and he's running the Brave browser.

**Comment by elhombretecla** [comment]
Hi @mscofield0 thanks you for your feedback :)

We just created an issue at Taiga to fix this bug as soon as we can.
You can track it here [https://tree.taiga.io/project/penpot/issue/2042](https://tree.taiga.io/project/penpot/issue/2042)
