### ISSUE TITLE
Letter spacing should permit scrubbing to negative values with arrow keys/scroll wheel

### ISSUE THREAD

**Issue by RomanHargrave** [uxbox/uxbox#1221]
**Is your feature request related to a problem? Please describe.**
There are situations where one might want to use negative letter spacing in a typography asset. This is possible right now by manual entry, but any use of the arrow keys or scroll wheel over the input will result in the value being reset to zero - which can be most frustrating and tedious to deal with. Additionally, the arrow keys and scroll wheel can only be used to input 0 or a positive number.

**Describe the solution you'd like**
There should not be a lower boundary for this input. The same could go for line spacing, for really odd folks.

**Comment by elhombretecla** [comment]
You are right :)

It's probably something we have to evaluate and develop for all input types

[https://tree.taiga.io/project/penpot/issue/2044](https://tree.taiga.io/project/penpot/issue/2044)
