### ISSUE TITLE
Exporting a page shows an error.

### ISSUE THREAD

**Issue by SedueRey** [uxbox/uxbox#1222]
I've tried to export two pages in two separated files but, at this moment, penpot always shows an error on Chrome.

Looking at the Network Panel on chrome the call https://design.penpot.app/export returns a 504 error and an empty response.

Request Payload:

```["^ ","~:page-id","~uf20f6171-178b-11ec-a2bf-b2702b3a67d1","~:file-id","~uf20f6170-178b-11ec-a2bf-b2702b3a67d1","~:object-id","~u0abbe8b1-178c-11ec-bc44-19cac726a52b","~:name","Certificados / Inicio","~:exports",[["^ ","~:type","~:png","~:suffix","","~:scale",1]]]```

**To Reproduce**
1.  Select an artboard
2.  Click on Export
3.  Select PNG, JPEG, SVG or PDF
4.  It returns an error: An unexpected error ocurred

**Expected behavior**
A file should be eligible to download

**Screenshots**
![image](https://user-images.githubusercontent.com/3238226/133768053-ee9676bb-e81e-4048-8d85-d0f71f42ffc7.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser (Chrome and Firefox)
-   Version 93.0.4577.82 (Build oficial) (64 bits) - Chrome, 92.0 64-bit Firefox

**Comment by elhombretecla** [comment]
The exporter it's already restarted. 

Please try now and sorry for the inconvenience :)

**Comment by SedueRey** [comment]
Working perfect.
Thank you very much!
