### ISSUE TITLE
"Show main component" won't scroll to target

### ISSUE THREAD

**Issue by maelomanontroppo** [uxbox/uxbox#1224]
**Describe the bug**
There is no scroll to the selected component in the library panel.

**To Reproduce**
1.  Right click on component in an artboard 
2.  Click on 'Show main component'
3.  Library opens in left panel
4. There is no animation nor somewhat similar to display the component. You have to scroll the entire list, eventually.

**Expected behavior**
The selected component should de positioned at the top of the scrollbar area

**Desktop:**
- OS: Windows
- Browser : Chrome
- Version Version 93.0.4577.82 (Build officiel) (64 bits)

**Environment :**
AAS (https://design.penpot.app)

**Comment by myfunnyandy** [comment]
Not exactly a bug as this functionality currently does not include scrolling to the asset, only opens the library where it is stored. We recon that is a bit too less for it to have sense so we are planning to make a couple of improvements on it, including the scrolling and the selection of the asset. You can see the user story at taiga, where we have added your request: https://tree.taiga.io/project/penpot/us/2053?no-milestone=1

**Comment by maelomanontroppo** [comment]
@myfunnyandy I will edit label to "enhancement" then.

**Comment by myfunnyandy** [comment]
Better, thanks! However, I uderstand why it seems like a bug.
