### ISSUE TITLE
Cannot change project name  

### ISSUE THREAD

**Issue by ghost** [uxbox/uxbox#1226]
**Describe the bug**
I build and run the penpot server with the default docker-compose configuration. After that I created a profile using the command from Getting Started > Configuration in the Docs and created a team. When I try to create a new project or rename some project that already exists I get Internal Error. 

**To Reproduce**
1.  Go to your team's Dashboard
2.  Click on Projects
3.  Click New Project at the top right of the screen. On the project's name input field type the desired name and press enter or click outside the input box
4.  The Internal Error appears and if you go back to the dashboard the new project has the default "New Project 1" name and not the one you typed

**Expected behavior**
The name should be the one that the user types on project's creation without any errors

**Screenshots**

No screeshots 

**Desktop (please complete the following information):**

-   OS: Ubuntu 20
-   Browser: Brave, Firefox
-   Version: Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit), 92.0 (64-bit)

**Environment (please complete the following information):**
Self hosted with docker compose (default config)z

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Ubuntu 20.04

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: docker-compose version 1.25.0, Docker version 20.10.8, build 3967b7d

**Frontend Stack Trace (if self-hosted)**
I don't get any errors in the docker logs

**Backend Stack Trace (if self-hosted)**
I don't get any errors in the docker logs

**Additional context**
I get the following error on the browsers console

```
hint: No protocol method IWithMeta.-with-meta defined for type object: [object Object] ui.cljs:329:6
Error: No protocol method IWithMeta.-with-meta defined for type object: [object Object]
    Kb core.cljs:324
    fc core.cljs:699
    Bd core.cljs:2093
    C projects.cljs:78
    p inline_edition.cljs:53
    React 11
    unstable_runWithPriority scheduler.production.min.js:19
    React 3

stack: Kb@http://localhost:9001/js/shared.1fe23ff73.js:1441:363
fc@http://localhost:9001/js/shared.1fe23ff73.js:1459:174
Bd@http://localhost:9001/js/shared.1fe23ff73.js:1545:263
pLb/C<@http://localhost:9001/js/main.1fe23ff73.js:3134:34
VKb/p<@http://localhost:9001/js/main.1fe23ff73.js:3097:543
Nb@http://localhost:9001/js/shared.1fe23ff73.js:971:235
rc@http://localhost:9001/js/shared.1fe23ff73.js:971:328
sc@http://localhost:9001/js/shared.1fe23ff73.js:971:387
Gb@http://localhost:9001/js/shared.1fe23ff73.js:995:257
Md@http://localhost:9001/js/shared.1fe23ff73.js:996:205
ld/<@http://localhost:9001/js/shared.1fe23ff73.js:1006:398
pi@http://localhost:9001/js/shared.1fe23ff73.js:1185:370
mb@http://localhost:9001/js/shared.1fe23ff73.js:970:70
ld@http://localhost:9001/js/shared.1fe23ff73.js:999:107
bb@http://localhost:9001/js/shared.1fe23ff73.js:986:36
Sa@http://localhost:9001/js/shared.1fe23ff73.js:985:94
shadow$provide[448]/f.unstable_runWithPriority@http://localhost:9001/js/shared.1fe23ff73.js:948:254
zd@http://localhost:9001/js/shared.1fe23ff73.js:1013:367
Ka@http://localhost:9001/js/shared.1fe23ff73.js:1185:222
Ia@http://localhost:9001/js/shared.1fe23ff73.js:984:393
```

**Comment by myfunnyandy** [comment]
Hi, we are already working on it and will fix it asap. You can follow the issue at Taiga: https://tree.taiga.io/project/penpot/issue/2049

**Comment by hirunatan** [comment]
This should be solved now. You can check it in the design.penpot.app site, and also if you update your docker image.
