### ISSUE TITLE
Add support for mutliple color-stops for gradients

### ISSUE THREAD

**Issue by Mai-Lapyst** [uxbox/uxbox#1227]
Currently, a gradient only allows two colors: one start and one stop color. It would be practical to allow more "stops" in gradients. Another solutions could be to allow multiple fills/strokes, but this would not really work with plain colors.

**Comment by myfunnyandy** [comment]
We have improvements planned for gradients but this is not yet prioritized. I will add your suggestion to the user story: https://tree.taiga.io/project/penpot/us/326?backlog-q=gradients&no-milestone=1

**Comment by myfunnyandy** [comment]
Closing this one as is a duplicated from https://github.com/penpot/penpot/issues/1504
