### ISSUE TITLE
Internal Error when naming or renaming a project (Blocking)

### ISSUE THREAD

**Issue by mlgarchery** [uxbox/uxbox#1228]
**Describe the bug**

I click on the New Project button on the top right corner, then type the name of my project, hit enter or click elsewhere and get an Internal Error. Refreshing the page shows the project has not been renamed. Same thing when I go on the project 3-dots and click on the Rename option. 
I have multiple teams and projects.

In the browser console, I have:
```
Internal error:
ui.cljs:329 hint: No protocol method IWithMeta.-with-meta defined for type object: [object Object]
```

**Desktop (please complete the following information):**

-   OS: ubuntu
-   Browser: brave

**Environment**
I am using penpot SAAS https://design.penpot.app

**Comment by myfunnyandy** [comment]
Hi, we are already working on it and will fix it asap. You can follow the issue at Taiga: https://tree.taiga.io/project/penpot/issue/2049

**Comment by mlgarchery** [comment]
Ok it's a duplicate of https://github.com/penpot/penpot/issues/1226, I can close mine
