### ISSUE TITLE
Typography asset does not list correct typeface after undo via history

### ISSUE THREAD

**Issue by RomanHargrave** [uxbox/uxbox#1230]
**Describe the bug**
If one changes the typeface of a typography asset, and then proceeds to undo the change, the asset will show the last selected typeface as opposed to the *effective* typeface. This persists between reloads, and project changes.

**To Reproduce**
1. Create and apply a typography asset
2. Observe that text objects using that asset reflect the stated typeface
3. Change the typeface
4. Observe that text objects reflect changes
5. Access history, and revert the typeface change
6. Observe that text objects reflect the original typeface
7. Observe that the typography asset typeface selection *does not* reflect the original and effective typeface.

**Expected behavior**
Typography assets reflect the current and effective typeface for that asset.

**Screenshots**
![Text showing incorrect typeface](https://i.imgur.com/oNToLTb.png)

In the above screenshot you will see that the selected text object has the 'Name' typography asset associated. The 'Name' asset indicates that [Goudy Bookletter 1911](https://www.theleagueofmoveabletype.com/goudy-bookletter-1911) is in use when *this could not be further from the truth*.

What is most frustrating about this is that I did not recall what typeface was in use originally, and had to use developer tools to retrieve it from the DOM.

**Desktop (please complete the following information):**

-   OS: Not applicable
-   Browser (e.g. chrome, safari): Chrome (embedded, nativefier) *and* Firefox
-   Version (e.g. 22): Not going to bother figuring out the equivalent chrome version, FF 91

**Environment (please complete the following information):**
SaaS 

**Additional context**

**Comment by myfunnyandy** [comment]
It seems that to rollback the typeface change you need to get to the history point where the typography style was applied. I've created the bug at Taiga and we will eventually fix it: https://tree.taiga.io/project/penpot/issue/2055
