### ISSUE TITLE
Penpot should avoid fractional object sizes and positions

### ISSUE THREAD

**Issue by RomanHargrave** [uxbox/uxbox#1232]
**Describe the bug**
Penpot aligns objects on a grid with 1-pixel intervals on both axes. Snapping and various other behaviors are defined in terms of the grid, if enabled. Pixels are the atomic unit of measure for conventional digital displays and, as such, shapes generally cannot be positioned on displays at the sub-pixel level without the use of trickery. To my knowledge, the only subpixel hack commonplace in general computing would be subpixel hinting, which applies only to the fine details of letterforms - which themselves must still be pixel-aligned for the purposes of positioning.

When tools, particularly the 'distribute' tools, are used in Penpot, objects may be assigned geometry that is not pixel aligned, e.g. a width or position of '100.465'. When this occurs, fractional geometry may then spread to other objects via alignment and snapping/guides. This can lead to frustration in trying to align objects and produce consistent appearance as movement will still be pixel aligned with fractional sizes and positions effectively introducing some level of error into pixel-aligned movements.

Further compounding this problem is that Penpot will not accept user-entered fractional geometry and will instead round entered values to the nearest pixel.

All of this makes it very difficult to produce visually appealing and pixel-perfect prototypes.

**To Reproduce**
The fastest way to discover this problem is by use of the 'distribute ... spacing' tools.

**Expected behavior**
Objects may not have fractional sizes or positions.

**Environment (please complete the following information):**
SaaS

**Comment by mlgarchery** [comment]
I agree. I had trouble aligning items. I found myself correcting to a int value some positions, but then I would stop using the distribute and spacing tools and check item position directly.

**Comment by 12people** [comment]
When distributing objects, Penpot could potentially ask whether to distribute unevenly or use fractional positioning.

This is what Sketch does:
![image](https://user-images.githubusercontent.com/7361228/133987840-b69cd30b-17ca-4eac-afe9-19dbdf201009.png)

**Comment by hirunatan** [comment]
Hi, @RomanHargrave. You are true, fractional pixels is a non-trivial issue. We are still investigating the best way of handling it, and giving the user more options is a reasonable approach.

You can track the progress of the idea here https://tree.taiga.io/project/penpot/us/1848.

**Comment by vanillajonathan** [comment]
Slightly related:
https://tree.taiga.io/project/penpot/issue/2290

**Comment by maciek134** [comment]
There are times when subpixel positioning is fine and even required, for example:

Icons imported as SVGs can have `rect`s in them - because of that they look uneven when scaled down, since the rects snap to the pixel grid. And the whole icon can't be aligned precisely.

Scaling "down" is common when designing for mobile devices, since they are usually high DPI (for example: Pixel 5, dimensions in Penpot: 393x851, real: 1080x2340).
