### ISSUE TITLE
Masked images not shown in view mode

### ISSUE THREAD

**Issue by Rechi86** [uxbox/uxbox#1238]
First of all thanks for this amazing tool. I hope this problem is not based on the wrong
usage, If you need any additional information, just let me know.

**Describe the bug**
When images which are part of masked group are not shown in view mode.
They seem to be there for a short time but when loading and then disappear.
If I put them out of the masked group, they are again visible as suspected.

See a screengrab of a simple use case, the working non-masked image and
the problematic masked image:
https://youtu.be/YmqZGhSilBM

Here a Link to the the preview of the project (in problematic masked state):
https://design.penpot.app/#/view/c407e7d0-1bd1-11ec-9c71-4a8af25a7bed?page-id=c407e7d1-1bd1-11ec-9c71-4a8af25a7bed&index=0&share-id=24243ec0-1bd2-11ec-9c71-4a8af25a7bed

**To Reproduce**
1. upload a new image
2. create a new mask
3. mask the image
4. test in view mode

**Expected behavior**
The overlapping region of image and mask should be visible in view mode.

**Screenshots**
See a full screenrecording of the bug:
https://youtu.be/YmqZGhSilBM

**Desktop (please complete the following information):**
-   OS: windows 10 64 bit
-   Browser: Chrome
-   Version 93.0.4577.82 (Offizieller Build) (64-Bit)

**Environment (please complete the following information):**
 SAAS (https://design.penpot.app)

**Comment by myfunnyandy** [comment]
Thanks for reporting this with such a detailed explanation and videos. We will fix this asap, you can follow the issue at Taiga: https://tree.taiga.io/project/penpot/issue/2085

**Comment by Rechi86** [comment]
Thanks for the fix. I can confirm that it's working fine!
