### ISSUE TITLE
Certain standard keyboard shortcuts missing

### ISSUE THREAD

**Issue by 12people** [uxbox/uxbox#1244]
**Is your feature request related to a problem? Please describe.**
As a Mac user, I find it annoying when I try a commonly used keyboard shortcut that's used in all competing software and find out it doesn't work in Penpot.

**Describe the solution you'd like**
Here are the missing shortcuts that I've come upon so far:
- Cmd + Shift + G to Ungroup. (In general, on macOS, it's standard behavior to add shift to a shortcut to get the opposite effect. For example, Cmd + Shift + Z to undo or Cmd + Shift + Tab to navigate through apps in reverse chronological order. Cmd + Shift + G is the logical counter to Cmd + G to group.)
- Cmd + 0 to zoom to 100%.
- Cmd + + to zoom in, Cmd + - to zoom out. (These commands are currently sent to the browser, which rescales the whole Penpot UI to be unusable.)
- While not standardized across competing software, it'd be nice to have shortcuts for hiding and for locking a layer too.

**Comment by claragvinola** [comment]
Hi 12people! thank you for your feedback. We have already done a meticulous analysis of the shortcuts of other tools, but we write down your suggestions :)

**Comment by myfunnyandy** [comment]
Except the proposal for hide and lock, that should be treated separately for not being standard, the rest have been implemented, sometimes with slight differences to not collide with browser shortcuts: https://help.penpot.app/user-guide/introduction/shortcuts/
