### ISSUE TITLE
Expand pages menu view

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#1252]
**Is your feature request related to a problem? Please describe.**
I have a lot of pages and that section of the UI is too compact to handle so many

**Describe the solution you'd like**
Drag and drop to expand the view area like figma

Penpot pages view:
![image](https://user-images.githubusercontent.com/46250921/135303491-ee7db0bc-ff14-4f67-8dd9-6beb8508fe0d.png)

Figma adjustable pages view:

https://user-images.githubusercontent.com/46250921/135303609-8748a328-2da9-4c67-84e7-9dde48861482.mov

**Comment by claragvinola** [comment]
Hi jsmorabito! we add it to our enhancement list right now!
thank you very much for the feedback!

**Comment by myfunnyandy** [comment]
Closing this one as it is already done
