### ISSUE TITLE
sharing link to prototype doesn't work

### ISSUE THREAD

**Issue by chovyprognos** [uxbox/uxbox#1254]
https://bit.ly/3uo8PHL

**Comment by claragvinola** [comment]
Hi chovyprognos! can you give us more info about the bug? your url isn't working but we can not reproduce it with another files!
Thank you!

**Comment by chovyprognos** [comment]
I just went to the share page from the Protoype page. 

Anthony Ettinger 
(408) 656-2473

**Comment by tryvin** [comment]
+1, neither in the https://penpot.app/ nor in the self-hosted instances, see video below.

https://user-images.githubusercontent.com/3874705/137345003-f858177d-ada4-4093-850e-83f3d3650113.mov

**Comment by tryvin** [comment]
No, actually got it, it's a UX issue, you need to click on `Get the link`, it doesn't load automatically when the popup opens.

**Comment by niwinz** [comment]
It is not a bug, it works as expected, you need to click "get link" to obtain the link.

**Comment by chovyprognos** [comment]
I did. 

Anthony Ettinger 
(408) 656-2473
