### ISSUE TITLE
Navigation between pages

### ISSUE THREAD

**Issue by Ali1Jamal** [uxbox/uxbox#1257]
Hello:
i'm have a question about Navigation between pages in run mode for example if i'm click this button its well jump to another layer to show it..
I am wondering  if it is supported or not because I'm didn't see it in the penpot

**Comment by claragvinola** [comment]
Hi Ali1Jamal! we are currently working on a feature to navigate between pages in view mode, and in the future maybe do it in the prototype. Stay tuned!
thank you for your feedback!

**Comment by niwinz** [comment]
This is already implemented. Sorry for late response.

**Comment by caiobribeiro** [comment]
Hi! First I just love Penpot, thanks!
I mainly use Penpot for diagramming, creating the assets for each kind of diagram that I need and making them libraries. Now I need to create a Data Flow Diagram, this is the last library I need/want to create before realizing publicly, the idea is to create a full set of libraries for software development.  DFD's must be navigateble between pages, however I can't find this functionality despite been already implemented, is there tutorial? PLZ and thanks for everything!
