### ISSUE TITLE
Create demo account is being displayed

### ISSUE THREAD

**Issue by tryvin** [uxbox/uxbox#1266]
**Describe the bug**
It doesn't matter if I use `PENPOT_ALLOW_DEMO_USERS` to `false` or remove the `enable-demo-users` from `PENPOT_FLAGS`, it will always show the "Create demo account" link.

**Expected behavior**
Don't show the create demo account link

**Desktop (please complete the following information):**

-   OS: OSX
-   Browser Chrome

**Environment (please complete the following information):**

Self-Hosted, Kubernetes, 1.8.2-alpha

**Comment by niwinz** [comment]
try the `disable-demo-users` flag

**Comment by niwinz** [comment]
demo users are enabled by default, so you need to explicitly disable it.

We are aware that the documentation is missing for this part. We will try to fix it for the next release.

**Comment by tryvin** [comment]
@niwinz that worked! I created a helm chart for Penpot: https://github.com/EightSystems/penpot-helm

Will try to add some README there to help.
