### ISSUE TITLE
Add Penpot icon so SimpleIcons

### ISSUE THREAD

**Issue by grivasgervilla** [uxbox/uxbox#1269]
Hi,

I think that it would be good that the Penpot icon to be on [simpleicons.org](simpleicons.org), I have open an issue to add it, maybe you can contribute the icon on that issue :). For example, I would use this icon to show that I use Penpot to develop some projects whose repositories are on GitHub.

The issue: https://github.com/simple-icons/simple-icons/issues/6664#issue-1019667068

**Comment by elhombretecla** [comment]
Hi @Griger Awesome idea!

We just comment on your issue at simpleicons adding the Penpot icon.
Thank you to give Penpot a try to develop your projects. Let us know if you need something else :)
