### ISSUE TITLE
zoom dropdown is cut-off to the right

### ISSUE THREAD

**Issue by rnarius** [uxbox/uxbox#1273]
**Describe the bug**

**To Reproduce**
1.  Open any file
2.  Click on the zoom widget in the upper right corner (displays the current zoom level, e.g. 100%)
3.  The resulting dropdown is cut-off to the right, which hides the screne

**Expected behavior**
Dropdown should be right aligned to the zoom widget button instead of left aligned.

**Screenshots**

Current alignment
![image](https://user-images.githubusercontent.com/2543323/136445741-021f9cef-15de-40ae-8426-09af1f7d40a1.png)

Expected alignment
![image](https://user-images.githubusercontent.com/2543323/136445707-b1966545-2aca-4e70-875a-653c53ef8c3e.png)

**Desktop (please complete the following information):**

-   OS: Fedora 34
-   Browser: Firefox 92.0.1

**Environment (please complete the following information):**
using SAAS (https://design.penpot.app)

**Comment by elhombretecla** [comment]
Hi @rnarius Thank you for your feedback

This is a [known bug](https://tree.taiga.io/project/penpot/issue/2041). We already fix it and will be deployed with the next release that will be available soon :)
