### ISSUE TITLE
Bug with changing font size with arrows

### ISSUE THREAD

**Issue by Igorgro** [uxbox/uxbox#1274]
**Describe the bug**
When changing font size of one text item using ↑↓ keyboard arrows, it cause changing of the size of another text item.

**To Reproduce**
1.  Create new artboard
2.  Create two text items (for example A and B)
3.  Select item A and then click on 'Font size' field
4.  Change the font size using keyboard arrows
5. Select item B and again click on 'Font size' field
6. Try to change the font size using keyboard arrows
7. The font size of item A resets to the current font size of item B and then nothing happens when pressing arrow keys

**Expected behavior**
The font size of any text item can be changed using keyboard arrows without any troubles.

**Screenshots**

https://user-images.githubusercontent.com/22894169/136626418-9afce8e3-c063-43f9-afb7-1c452510d842.mp4

**Desktop (please complete the following information):**

-   OS: Debian 11
-   Browser Firefox 78

**Environment (please complete the following information):**
Both SAAS (https://design.penpot.app) and self-hosted instance.

**Comment by myfunnyandy** [comment]
Thanks for taking your time to raise a such well detailed issue. We've added to Taiga and will manage if from there: https://tree.taiga.io/project/penpot/issue/2166
