### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by yarons** [uxbox/uxbox#1278]
Hi,
I would like to start a new Hebrew translation language code: `he`.

My Weblate profile is https://hosted.weblate.org/user/Yaron/

Thank you very much!

**Comment by hirunatan** [comment]
Thank you very much!

I've added you to the penpot project. You should now see it in your dashboard. You can start making translations and send them for us to review.

**Comment by yarons** [comment]
Hmmmm I can't join Hebrew since it's unavailable, can you please check it's on?

**Comment by hirunatan** [comment]
Sorry! You are true, the language was not available until now. I have enabled it, check if you see it now.

When you consider it to be complete, give us a signal and we will load it into Penpot. Thanks again!

**Comment by yarons** [comment]
Done, some of the original strings are a little vague and needs rephrasing but I managed somehow.

Thank you!
