### ISSUE TITLE
No assets in penpot container

### ISSUE THREAD

**Issue by Sebi2020** [uxbox/uxbox#1284]
**Describe the bug**
The penpot container (docker) does not contain any assets (rendering it unusable).

**To Reproduce**
1. download penpot docker-compose yml from repo (either taiga or penpot)
2. Create an account & login
3. Create a project and look at the assets page

**Expected behavior**
Prexisting assets

**Desktop (please complete the following information):**

-   OS: (e.g. iOS): Linux
-   Browser (e.g. chrome, safari): Firefox
-   Version (e.g. 22) (of penpot?!?!? or browser or os?) 1.0.0 alpha

**Comment by elhombretecla** [comment]
Hi @Sebi2020 thanks for your feedback :)

There is no option on creating a new user with assets in Penpot docker container. The way to add assets to a user is by downloading [Penpot libraries and templates](https://penpot.app/libraries-templates.html). To use them you just have to download and import them into your Penpot projects.

We hope that these files will be useful in your designs and prototypes.

**Comment by niwinz** [comment]
> The penpot container (docker) does not contain any assets (rendering it unusable).

What you mean with "unusable"?

**Comment by Sebi2020** [comment]
I simply wasn't aware, that assets have to be downloaded separately. Thank you for your response.
