### ISSUE TITLE
SVG export is invisible when exporting text with a gradient

### ISSUE THREAD

**Issue by infi** [uxbox/uxbox#1298]
**Describe the bug**
SVG export appears to incorrectly come out invisible when attempting to export text that has a gradient applied to it.

**To Reproduce**
1. Create a text node. The content, typeface and font weight do not seem to be important here.
3. Add a gradient to the text node. A linear gradient works. The colors do not seem to be important here, but make sure both colors have their alpha set to 100%.
3. Export the text node as SVG by itself.
4. Observe the exported SVG.

**Expected behavior**
The SVG exports like it looks in the viewport.

**Actual behavior**
The text appears to be invisible in the export, both when viewed in a browser and dedicated image viewer.

**Screenshots**
![image](https://user-images.githubusercontent.com/45950794/138554937-e099718f-9425-45c6-8d43-78ddd73e8693.png)

The same piece of text exported as PNG and SVG, viewed in a file manager:
![image](https://user-images.githubusercontent.com/45950794/138554897-c19b55d4-ffef-4554-a95a-ef2d68c936bc.png)

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser: Google Chrome
-   Version: dev 97.0.4676.0

**Smartphone (please complete the following information):**

\-

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Frontend Stack Trace (if self-hosted)**

\-

</details>

**Backend Stack Trace (if self-hosted)**

\-

**Additional context**
The typeface used for testing is Inter, with font weight 900. I also have the font installed on my system.

**Comment by elhombretecla** [comment]
Hi @infi thank you so much for your report.

We will fix this bug as soon as we can. You can track this issue at Taiga

[https://tree.taiga.io/project/penpot/issue/2200](https://tree.taiga.io/project/penpot/issue/2200)
