### ISSUE TITLE
Traditional Chinese (Taiwan) translation

### ISSUE THREAD

**Issue by 5idereal** [uxbox/uxbox#1299]
Hi,
I'd like to contribute to Traditional Chinese (Taiwan) translation.

My Weblate username is [SiderealArt](https://hosted.weblate.org/user/siderealart/). Thanks!

**Comment by hirunatan** [comment]
Thanks a lot for your offering!

Unfortunately, Weblate has not registered the Taiwan variant of Traditional Chinese language. These are the languages that the tool allows us:

![image](https://user-images.githubusercontent.com/1483050/138669923-61a51de3-eacb-490b-baf8-c951a35455ed.png)

If you want, we could ask Weblate to add it (they have a form to ask for it). If you write a small request text, justifying the need for this, we can send it to Weblate team.

**Comment by 5idereal** [comment]
Chinese (Traditional) (zh_Hant) is fine for me. Only Taiwan, Macau, and Hong Kong uses Traditional Chinese, it should not cause any confusion.

**Comment by hirunatan** [comment]
Ok then. Done! You now can see the new language in weblate. Thanks again!

**Comment by 5idereal** [comment]
@hirunatan Sorry to bother you again, but it appears that I don't have the permission to save or even suggest translation.
![image](https://user-images.githubusercontent.com/30827929/139148413-4b9951b8-1005-421e-a11f-4581e1d938a8.png)

**Comment by hirunatan** [comment]
Sorry, I think that I didn't fully add you. Try again now.

**Comment by 5idereal** [comment]
It's working properly now. Thanks for the help!

**Comment by hirunatan** [comment]
Thanks to you for the contribution!
