### ISSUE TITLE
Can't click items in menu-bar when in comments-mode.

### ISSUE THREAD

**Issue by roadbearstudios** [uxbox/uxbox#1303]
When in comments-mode on a shared prototype it is not possible to click items in the top-menu bar, because on click the comment-box appears. 

1.  Create a prototype with comments
2.  Share the prototype when in comments mode (so &section=comments is in the url)
3.  Log out of penpot or open the shared link in another browser and try to change 
4.  Try to change something in the top-menu bar, Comments or zoomlevel.

**Expected behavior**
It should be possible to change menu-items when in comments-mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/11589004/139258485-023c2a81-00ff-4cfb-b00a-022ac1488fc7.png)

-   OS: Linux
-   Browser: Firefox
-   Version: 93.0

Also confirmed on Linux / Vivaldi and MacOS / Safari

**Environment**
Self-hosted instance (docker). This is after upgrading to alpha 1.9.0, as far as I know this worked in alpha 1.8.0.
-   OS Version: (Debian)

**Comment by elhombretecla** [comment]
Hi @roadbearstudios thanks for your feedback :)

We just create this issue at Taiga to manage this bug as soon as we can.

[https://tree.taiga.io/project/penpot/issue/2222](https://tree.taiga.io/project/penpot/issue/2222)
