### ISSUE TITLE
Exported text does not match the same text in the editor

### ISSUE THREAD

**Issue by zhartus** [uxbox/uxbox#1305]
**Describe the bug**
Long text blocks in the export results differ from what is seen in the editor. 

**To Reproduce**
1. Create new Artboard.
2. Create a long canvas of text with many line breaks, but also many paragraphs. The more lines in the text, the better you can see the problem.  In the example in the screenshot, I took Shakespeare's text and reduced the block width to create line breaks. I am using Roboto font in example, but the same problem persists with other fonts. 
3. Export your artboard to png or any other format.
4. Compare the position of the bottom lines of text in the editor and in the result of the export. They are different. 

**Expected behavior**
Obviously, the appearance of the text in the editor and in the export result must match.

**Screenshots**

![image](https://user-images.githubusercontent.com/17202099/139341636-a3685097-28a1-4643-b528-24fb7c8619a2.png)

Update: the same problem even with short text (here the problem is obviously caused because the line breaks differently in the editor and in the export ):

![image](https://user-images.githubusercontent.com/17202099/139431827-b3a081dc-bfc9-493d-b107-44d9a99f07a3.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 93.0 (64-bit)

**Environment:**
https://design.penpot.app/

**Additional context**
It is noteworthy that sometimes the text in the export can be longer, and sometimes on the contrary - shorter than as a result of the export. Also, the text may differ from the usual appearance when editing it (see screenshot), but this does not always happen. I tried changing fonts and languages, but the problem still persists.

**Comment by myfunnyandy** [comment]
Hi, I've was able to reproduce the issue. We will track this on taiga and hopefully will it fix it soon: https://tree.taiga.io/project/penpot/issue/2223

Thanks!

**Comment by zhartus** [comment]
@myfunnyandy Thank you!

**Comment by niwinz** [comment]
This is already solved in the https://github.com/penpot/penpot/pull/1326 PR :P

**Comment by jsmorabito** [comment]
reproduced a related issue: the stars in this image are an emoji and they are flipped horizontally on export

this image is on the canvas:
![image](https://user-images.githubusercontent.com/46250921/140553047-c91a1d57-e186-47aa-bdc2-e1b2256eeebd.png)

this image is the export:
![image](https://user-images.githubusercontent.com/46250921/140553075-e3746732-4ef2-4320-af1d-483eee24fd20.png)

**Comment by hirunatan** [comment]
This should be fixed now. Please check it, thanks!

**Comment by jsmorabito** [comment]
> This should be fixed now. Please check it, thanks!

confirmed working for text but not emojis

Artboard:
![image](https://user-images.githubusercontent.com/46250921/141815502-f96812b7-69f6-4002-a677-deb1e88a8bdd.png)

Export (sparkles emoji mirrored, chair emoji not rendered):
![Artboard-1-4](https://user-images.githubusercontent.com/46250921/141815529-6a283789-6405-4f58-88c0-8cd7d8f1727e.png)

**Comment by hirunatan** [comment]
@jsmorabito could you please a new issue for this? I think this is a different problem. And please explain how are you typing the emojis and in what platform and browser. Thanks.

**Comment by jsmorabito** [comment]
> @jsmorabito could you please a new issue for this? I think this is a different problem. And please explain how are you typing the emojis and in what platform and browser. Thanks.

https://github.com/penpot/penpot/issues/1348
