### ISSUE TITLE
Deploying to non SSL, non localhost breaks authentication

### ISSUE THREAD

**Issue by d-franklin** [uxbox/uxbox#1310]
**Describe the bug**
When using docker to deploy to a non local, non SSL url authenticate breaks because the returned cookie has the 'secure' flag enabled.

See https://github.com/penpot/penpot/blob/a7241d4128e9fb8e0ddc2390f8ff48a02ca178e7/backend/src/app/http/session.clj#L61

**To Reproduce**
1.  Install Penpot locally via docker.
2.  In browser, open developer console and select 'Network' tab.
3.  Access Penpot via computers LAN IP Address (for example: 192.168.1.10).
4.  Login to Penpot (this will fail), but you can see via the network tab that the login request succeeded, but because the 'Secure' flag on the cookie is set, the browser will refuse the cookie.

While the above is solved by accessing Penpot via locahost, this does not solve the use case where Penpot is deploy to a server on a LAN.

**Expected behavior**
Either allow secure flag to be disabled via config.env (allowing for Penpot to be access via an insecure channel) OR update the documentation to specify that ONLY localhost and secure URLs will work.

**Screenshots**
![Developer Console, Network Panel](https://user-images.githubusercontent.com/12947514/139577462-f9a2578b-fab6-44d3-bb93-cf4538ffde79.png)

**Comment by niwinz** [comment]
You are right, we will need to improve this. Thanks for the report.

**Comment by niwinz** [comment]
Additionaly, but not related: the copy-and-paste will not work if you run without https.

**Comment by d-franklin** [comment]
> Additionaly, but not related: the copy-and-paste will not work if you run without https.

I haven't experienced this issue running localhost non-https.

**Comment by niwinz** [comment]
yes, the same rule applies, localhost is the exception to the rule. anything except localhost running on non-https environment will have problems also with clipboard. This is something that we can't fix, is the browser limitation.

**Comment by d-franklin** [comment]
> yes, the same rule applies, localhost is the exception to the rule. anything except localhost running on non-https environment will have problems also with clipboard. This is something that we can't fix, is the browser limitation.

Forgot about localhost :)

**Comment by d-franklin** [comment]
> This is something that we can't fix, is the browser limitation.

I'm not sure what your referring to with the above statement, are you talking about running non-localhost, non-https being broken as the thing you cant fix?

**Comment by niwinz** [comment]
We will fix, the login issue on non-localhost & non-https environments. In fact, the fix is already landed on `develop` branch.
The problem of Clipboard on non-localhost & non-https can't be fixed. it is a browser (clipboard api spec) security limitation.

**Comment by d-franklin** [comment]
Ok thank you for the update

**Comment by chris-aeviator** [comment]
receiving this on a  non-localhost, non-https machine

`Looks like you are not authenticated or session expired.` when trying to login - is this the same issue?

these 3 are commited directly in a row when the error shows

![image](https://user-images.githubusercontent.com/11522213/148121247-1f7aafe7-f7df-46bc-b571-a1f15b02f42b.png)

## Update
Penpot is usable when using an SSL tunnel to tunnel [remotehost]:9000 to localhost:5000 and I can successfully login

**Comment by 2018yuli** [comment]
on a non-localhost, non-https machine
set
`PENPOT_PUBLIC_URI= LAN IP Address (for example: 192.168.1.10)`
`PENPOT_FLAGS="enable-demo-users disable-secure-session-cookies enable-insecure-registration"`
 at `config.env` then restart  container `penpot-penpot-backend-1`
It works for me!
