### ISSUE TITLE
Input fields are hard to access if the label is as long as the box

### ISSUE THREAD

**Issue by benthillerkus** [uxbox/uxbox#1311]
**Describe the bug**

Clicking on the label within an input field does not focus the input field. This is problematic, when the label is longer than the box itself.

**To Reproduce**

1.  Switch the language to German
2. Open any project and select any component
3. Add a shadow effect

**Expected behavior**

The entire box, including the parts where the label is should be clickable.

**Screenshots**

![2021-11-01_17-29-32](https://user-images.githubusercontent.com/29630575/139706929-c76b6640-2af4-4062-9e43-6fe7f344046e.gif)

**Desktop:**

-   OS: Windows 10
-   Browser: Chome

**Environment:**

SAAS

**Comment by myfunnyandy** [comment]
Hi, I've was able to reproduce the issue. We will track this on taiga and hopefully will it fix it soon: https://tree.taiga.io/project/penpot/issue/2224

Thanks!

**Comment by Alotor** [comment]
Thank you for the report @benthillerkus we'll need to put an ellipsis for long texts like so:

![image](https://user-images.githubusercontent.com/3418223/140052806-37868fbb-533f-4d1b-a5fa-58edaa95d946.png)

Maybe you could suggest a more concise translation for these fields?

**Comment by benthillerkus** [comment]
> Maybe you could suggest a more concise translation for these fields?

"Unschärfe" would be a bit shorter than "Weichzeichnen" and means roughly the same.
According to Wikipedia the blurry part of a shadow is the "Penumbra", and the completely solid part is the "Umbra", so that might work too instead of "Weichzeichnen" and "Streuung".

If these are still too long, the shortest would be to call the blur just "Z", I guess.

**Comment by hirunatan** [comment]
We have released the fix of adding an ellipsis to the text when they are too long. And we'll change the word  "Weichzeichnen" for "Unschärfe" in the next release.
