### ISSUE TITLE
The inside stroke option doesn't work

### ISSUE THREAD

**Issue by mlgarchery** [uxbox/uxbox#1321]
**Describe the bug**
Inside stroke seems broken. It seems to do a center stroke of double the expected size.

**To Reproduce**
1.  Create a square
2.  Add a stroke with 1px
3.  Change to 'Inline' stroke

**Expected behavior**
Stroke should be inside the square

**Screenshots**
![penpot_bug](https://user-images.githubusercontent.com/16239564/140188179-f3e14998-a127-466d-946c-e0abbc074fe7.PNG)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Opera

**Environment (please complete the following information):**
SAAS

**Comment by niwinz** [comment]
Should be fixed.

**Comment by niwinz** [comment]
Thanks for reporting the issue :heart:
