### ISSUE TITLE
Alternative storage options for local usage

### ISSUE THREAD

**Issue by bedax** [uxbox/uxbox#1323]
Penpot seems excellent, but one thing that seems less simple than it could be is the installation process. Is it possible for penpot to have the option to use, for example, IndexedDB or other alternative storage engines, particularly for when using it locally. That way it seems penpot could basically be distributed as a .html file, not requiring docker, etc.

**Comment by niwinz** [comment]
It is in our roadmap research in this area; but right now, backend does many things that we can't do easily 100% on browser.
Example: when you upload a bitmap image when it should be stored? The users will want probably use large images, but browser has very low limits on the current storage.

Making penpot 100% browser (without backend) is a good challenge, and we have it in our radar but right now is not in our immediate todo list. 
There are also many requests for desktop application (that is very different thing from offline usage, but probably many users assumes both).

**Comment by bedax** [comment]
Hm, yeah I expect that abstracting away the storage layer likely won't be that easy. Perhaps the File API might be of use for large file support? Personally though, I would be willing to accept low file size limits when using it locally, but either way I'm glad to hear it's on your roadmap! Good luck with it!

**Comment by niwinz** [comment]
On the end this enter in a bunch of stuff that is related to PWA, desktop, offline usage and etc... that will be treated in a future when we start approach it. It is already tracked internally, so I close this issue.
