### ISSUE TITLE
Re-exporting shape ignores recent changes to text item content

### ISSUE THREAD

**Issue by diacritica** [uxbox/uxbox#1332]
**Describe the bug**
Rapid succession of text changes in a shape doesn't reflect on export outcome

**To Reproduce**
1.  Create an artboard with a text inside
2.  Export shape as PNG
3.  Change the text content
4.  Export shape again as PNG. You will see a duplicate, like no changes had been made to the text content

**Expected behavior**
Any change, as long as it gives you the SAVED status top right should immediately allow for updated re-exports

**Screenshots**
See video here: https://drive.google.com/file/d/19jtMrIBcfxYXvZ_V2-0IlRPH2ra6yOep/view?usp=sharing

**Desktop (please complete the following information):**

-   OS:GNU/Linux (Linux Mint)
-   Browser: Chrome 
-   Version  95.0.4638.54 (Official Build) (64-bit)

**Environment (please complete the following information):**
I'm using SaaS

**Comment by niwinz** [comment]
I'm unable to reproduce the issue.

After looking the video many times I have noticed that there are no feedback on "saving" before "saved" on the second text modification. This clearly means that the backend will not have the latest changes on the second export.
