### ISSUE TITLE
Internal Error when opening a shared prototype on mobile

### ISSUE THREAD

**Issue by mlgarchery** [uxbox/uxbox#1335]
**Describe the bug**
Can't see a shared prototype on mobile, I get an Internal error.

**Expected behaviour**
If viewing a prototype on mobile is not supported yet, a message telling so should be displayed.

**Smartphone (please complete the following information):**

-   iPhone SE 2020
-   Browser: Brave

**Environment (please complete the following information):**
SAAS

**Comment by hirunatan** [comment]
Hello. It should work. When you open a shared prototype in mobile, normally you can see it without problems. Another issue is that the viewer panel is not fully responsive yet, we have this in our roadmap. But there should not be any error.

Can you view the same link in a desktop browser? Or make another prototype, simpler, and try to view it with the mobile?

If not, could you please send us the prototype link to info@penpot.app for we to examine it?

Thanks for using penpot.

**Comment by niwinz** [comment]
After thinking a bit, I think I know the possible cause, I will look on it.
