### ISSUE TITLE
Can't use Solid style of Font Awesome

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#1338]
**Describe the bug**
When I import both Solid and Regular styles of Font Awesome 5 Desktop, it only detects Regular for both.

**To Reproduce**
1.  Download [FA-5.15.14 Desktop](https://use.fontawesome.com/releases/v5.15.4/fontawesome-free-5.15.4-desktop.zip) (same with the Web version)
2.  Import in Penpot
3.  The file is `Solid`, but Penpot detects it as `Regular`

**Expected behavior**
When I import the `Solid` style, I get it.

**Screenshots**
When importing
![image](https://user-images.githubusercontent.com/62602652/141485657-93b846dc-3682-4d16-9480-1f63520f1096.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Chrome
-   Version 95

**Environment (please complete the following information):**
SAAS

**Additional context**
I'm using FA 5.15.2 in Adobe Xd, and I've tried to use this version first. Then I tried 5.15.4 when I figured it doesn't work properly.
Then I can say the files work properly.
I've also tried with the web files (.ttf), with the same result.

Note: it's my first time with Penpot, I'm testing it to see if it fits our needs to replace Xd.

**Comment by niwinz** [comment]
Should be fixed in the next release. The solid fonts now matches as "Black" and you should be able to import both fonts in the same family.
