### ISSUE TITLE
Use without an account

### ISSUE THREAD

**Issue by vanillajonathan** [uxbox/uxbox#1341]
**Is your feature request related to a problem? Please describe.**
I cannot evaluate Penpot without an account. I am curious, but I might not be interested, first I want to see how it works and try it out before I create an account. When I mention Penpot to other people, they cannot try it without an account.

**Describe the solution you'd like**
I would like to be able to anonymously use Penpot without an account.

**Comment by hirunatan** [comment]
Hello. An account is necessary, for penpot to have a place to store your files and your user settings. You can create an account and easily remove it later, if you want.

Or if you have privacy concerns, and don't want to share your personal data, you can set up your own instance of Penpot, in your computer, as explained in the manual: https://help.penpot.app/technical-guide/getting-started/

**Comment by vanillajonathan** [comment]
I think it could store my user settings in `LocalStorage` and the files either it doesn't need to store them, or could store them with some File API too.

If I go on Canva, for example at https://www.canva.com/design/play?template=MADOPrIEz-k&category=tADWs5EeV14
then I can use the app and see how it works without having to sign up for an account.

**Comment by hirunatan** [comment]
Ok, perhaps it would be possible. But changing the storage used by Penpot is not a trivial issue. We have done some research and have a few ideas, but this still needs a lot of development. See this issue for a related question: https://github.com/penpot/penpot/issues/1323

**Comment by vanillajonathan** [comment]
It would also be okay that not all functionality is available without an account.
Example without an account you can draw and export, but if you want to upload files or save files then you need an account.

**Comment by hirunatan** [comment]
Ok. With the current architecture used in Penpot this is not an easy task (the diagramas themselves need to be stored somewhere). But It may be an interesting option for when we deal with the storagge issue. Thanks for the suggestion.

**Comment by vanillajonathan** [comment]
@niwinz Please close with a comment when closing an issue.

I still think it should be possible to use Penpot without an account, and I think this issue should remain open.

**Comment by niwinz** [comment]
You are right, sorry for not leave a comment.
In this case this issue is already covered in many issues and discussions open about offline usage so this is not to be forgotten

**Comment by tzwel** [comment]
This is a complete deal breaker for me

**Comment by 4e576rt8uh9ij9okp** [comment]
> Ok. With the current architecture used in Penpot this is not an easy task (the diagramas themselves need to be stored somewhere). But It may be an interesting option for when we deal with the storagge issue. Thanks for the suggestion.

Sorry for reviving this but I don't see how this is even a good argument. I have installed PenPot on my computer, this computer has TB of storage. The only reason why there is an account, is so you get peoples data.
