### ISSUE TITLE
Comments sidebar does not remain open when navigating between comments on different pages

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#1350]
**Describe the bug**
After clicking a comment in the comments panel thats on a different page than you are on, you are taken to the page where the comment is located, but the comments panel is not open, the comments are not shown on the page, and your viewport is not fixed on the area of the comment that was clicked on. 

**To Reproduce**
1.  Navigate to a page
2.  open comments panel
3.  click on a comment that is located on another page
4.  page you are taken to does not have comments panel open, nor does it take you to the comments location or show any comments on the canvas

**Expected behavior**
I expect that when I click on the comment in the comments panel on Page A, that when I'm navigated to Page B, the comments panel is open, all of the comments are visible on the canvas, and my viewport is centered on the area of the comment that I had clicked on

**Screenshots**

https://user-images.githubusercontent.com/46250921/142459210-29c5a39d-bec0-4045-9c3d-b1dd9e955e7d.mov

Towards the end of the video I click `c` to make the comments appear because they do not appear on their own

**Desktop (please complete the following information):**

tested on both safari and brave browser

**Comment by elhombretecla** [comment]
Hi @jsmorabito thanks for your feedback! You're on fire! :)

We will fix this bug as soon as we can. Yo can track it here
[https://tree.taiga.io/project/penpot/issue/2285](https://tree.taiga.io/project/penpot/issue/2285)

**Comment by jsmorabito** [comment]
@elhombretecla I'd also like to bring up this issue again as a reminder https://github.com/penpot/penpot/issues/1196

I stopped using comments because of the frustration caused by the lack of these properties. Without these properties (moving comments after creation, comments moving with the content they are placed on) it is costly for the user to move designs because they must then create the same comments in new locations. I don't think this situation is necessary and providing these enhancements would make commenting in Penpot much more user friendly!
