### ISSUE TITLE
is it necessary to provide an Ant design library?

### ISSUE THREAD

**Issue by zslucky** [uxbox/uxbox#1351]
Great project and thanks for your hard working.

As there are a large of users use ant design components, is it necessary to provide an Ant design library?

**Comment by elhombretecla** [comment]
Hi @zslucky thanks for your suggestion :)

Create new libraries and templates for Penpot is one of our priorities so we will review this one. I take this opportunity to remind you that you can contribute your own designs and libraries in [this repository](https://github.com/penpot/penpot-files).

**Comment by zslucky** [comment]
thanks @elhombretecla, glad to hear that, but I'm not designer, I don't know how to contribute it. 😢

**Comment by emengweb** [comment]
If could support .sketch format, that would be easy to provide these Design system stuff :)

**Comment by hirunatan** [comment]
@emengweb being able to import from other design tools formats is one of our priorities. But this is a quite complex issue, we'll do it when we can.

However, this is also a function that may be contributed by the community. We already have a .penpot file format, that is basically a zip file containing a .svg file per page, and some metadata for capabilities that cannot be expressed in plain svg (like interactions). It should be possible, for example, that any person that knows .sketch internal format could write a converted from it to the .penpot open format.

**Comment by elhombretecla** [comment]
Hi again @zslucky  😄 

A Lite version of the Ant Design library in Penpot is [available here](https://github.com/penpot/penpot-files/raw/main/Ant-Design-UI-Kit%20Lite.penpot)
Hope you find it helpful and fit your needs!

**Comment by zslucky** [comment]
@elhombretecla thanks, you are hero!
