### ISSUE TITLE
There is no way to delete teams or members?

### ISSUE THREAD

**Issue by zhartus** [uxbox/uxbox#1353]
**Describe the bug**
Owner can create teams and add members to them, but there is no ability to delete useless team or remove members. Member of team can leave it themselves, but owner or admins of team have no ability to remove any member.

**To Reproduce**
1.  Go to teams list or members list.
2. Try to delete team or remove some member.

**Expected behavior**
Obviously, the owner of a team should be able to delete both individual members and the entire team. 

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Firefox
-   94.0

**Environment:**
https://design.penpot.app

**Comment by myfunnyandy** [comment]
We are currently working on fixing this, we hope to deploy the solution soon.

**Comment by zhartus** [comment]
@myfunnyandy 
Great, thank you!
