### ISSUE TITLE
IMPORT ERROR when importing PenPot Design System

### ISSUE THREAD

**Issue by bartenra** [uxbox/uxbox#1362]
**Describe the bug**

**To Reproduce**
1.  Go to https://penpot.app/libraries-templates.html
2.  Download PenPot Design System
3.  Go to shared libraries
4.  Drag and drop downloaded file

**Expected behavior**
PenPot Design System imported

**Screenshots**
![image](https://user-images.githubusercontent.com/77667589/143418219-4d944208-7242-49b4-b4f1-b9d3ff8b7e12.png)

![image](https://user-images.githubusercontent.com/77667589/143417830-bcfb13ca-29e3-4c04-991a-fd289f8c3280.png)

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser Firefox
-   Version 94

**Environment (please complete the following information):**
SAAS

**Additional context**
![image](https://user-images.githubusercontent.com/77667589/143418024-d751914d-14f1-43ba-ac01-760edf17be48.png)

I don't know where else to import Penpot Design System. Inside the editor I see "No Shared Libraries Available":

![image](https://user-images.githubusercontent.com/77667589/143418111-f62914e4-a5b7-450d-bfd2-b16b7bdbf757.png)

**Comment by Alotor** [comment]
Thanks for reporting this. There is a bug in the shared-libraries screen but you can still import the library inside a project (or drafts) and the library will be displayed.

We'll fix it by the next release.

Thanks!

**Comment by shangkegit** [comment]
I had a similar problem, but I got a error prompt "There was a problem importing the file. The file wasn't imported" when I imported any template file
![2022-04-22 22-08-50屏幕截图](https://user-images.githubusercontent.com/21140738/164731624-2c69e054-b481-414e-a578-123d5a846b37.png)
