### ISSUE TITLE
support minio as custem s3 storage request

### ISSUE THREAD

**Issue by emengweb** [uxbox/uxbox#1369]
**Is your feature request related to a problem? Please describe.**
Some of people use minio as S3 type storage for self, they are same as aws S3.
Minio can be more scaleable and can be custem, pure self host.

**Describe the solution you'd like**
Support S3 storage Custem Server URL, REGION and urlType.

**Describe alternatives you've considered**
i use fs now, but not that scaleable.

**Additional context** 
Add minio in docker-compose.yml :)

**Comment by niwinz** [comment]
hi @emengweb 
thanks for the feedback

I think this issue https://github.com/penpot/penpot/issues/1267 already covers this, so I close this issue. Thanks.
