### ISSUE TITLE
Components Library Previews are cut off

### ISSUE THREAD

**Issue by candidexmedia** [uxbox/uxbox#1373]
**Describe the bug**
Hello! I'm working on contributing a template library that relies heavily on components. However, the preview of the components either looks incomplete, or is cut off. The components look fine, however, when you drag them in.

**To Reproduce**
1.  Save an object(s) as a component. Object(s) could be very long, containing clipping masks/boolean operations, etc.
2. Go to Library for assets
4.  See error

**Expected behavior**
I expect to see the component in its entirety and how it actually looks like in the preview, or at least be able to see the whole thing if I hover over the image.

**Screenshots**

![image](https://user-images.githubusercontent.com/95003834/143764113-c225f5a3-9fbd-4296-b16c-36a4d6197120.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Firefox
-   Version: SAAS version

**Comment by hirunatan** [comment]
@candidexmedia could you write to support@penpot.app and send us the url of your file, so we can examine it?

And please share another screenshot where we can see how do those components look when they are in the workspace? Thanks.

**Comment by candidexmedia** [comment]
@hirunatan Sounds good, I sent an email!
