### ISSUE TITLE
deploying with Docker it can not upload font files larger than ~5M

### ISSUE THREAD

**Issue by emengweb** [uxbox/uxbox#1383]
**Describe the bug**
When deploying with Docker, it is not allowed to upload font files larger than ~5M, such as: Source Han Sans CN, Microsoft YaHei, Alibaba PuHuiTi etc.

**Expected behavior**
Use Penpot.com try upload these font file everything is OK, may be is docker file limited the upload file size, maybe this can be set as variable in config.env ?

**Comment by niwinz** [comment]
There are already a option for it, but independently of this option, there is the nginx configuration that can't be set dinamically. We need to think in a good solution for it. Meanwhile we proceed with a workaround by increasing the nginx default upload size to a reasonable big value. It will be fixed for the next release for sure.

**Comment by emengweb** [comment]
Nice! :D

Andrey Antukh ***@***.***> 于 2021年12月1日周三 18:35写道：

**Comment by ttssttssttss** [comment]
still cannot upload font file with size bigger than 5M

**Comment by ttssttssttss** [comment]
just change "client_max_body_size"to bigger value could solve this problem in the front-end docker,
and I suggest put this value to be bigger than just 6M,as many font file larger than that.

**Comment by niwinz** [comment]
#1459 MR increases the default upload size on the docker images to 50M, we need to think about this on how make it configurable through the env variables.
