### ISSUE TITLE
Multiple color layers for one object (on fill and stroke)

### ISSUE THREAD

**Issue by ApolloOverflow** [uxbox/uxbox#1389]
## **Is your feature request related to a problem? Please describe.**
   For me, as for many other designers over the years of practice, the ability to add many layers of Fill color or many layers of Stroke color has become a familiar and integral function.
   This function is also in Adobe Illustrator (in which everyone used to design interfaces before). I think that's where this feature got into design apps like SketchApp, Figma, etc. and became familiar.
   So I was surprised that such a basic function was missing in Penpot. To be honest, this was the main reason why I did not practice more in the application, but left it "until better times" when this function appears.
   I have been following new releases and was hoping that one of them will feature this feature, but this has not happened yet.  So I finally decided to request it.

## **Describe the solution you'd like**
   Ability to add multiple layers of color in the Fill and Stroke parameters of an object.

## **Describe alternatives you've considered**
   This is a very handy feature in other apps. And the only alternative for it is to create multiple copies of the object, but with different fills and different transparency / blending mode.  This is more time consuming and unproductive than having multiple layers of color for one object.

**Comment by hirunatan** [comment]
Hello @ApolloOverflow. You are true, this is an important function. We have it planned, and it's very high into our backlog: https://tree.taiga.io/project/penpot/us/1394

You can track it to see when it's done. Thanks for your suggestions.

**Comment by myfunnyandy** [comment]
This one is already done.
