### ISSUE TITLE
Update properties of a component

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#1393]
**Is your feature request related to a problem? Please describe.**
When I create a component, I expect its properties to be independent.

For example here I've made a component of a text
![image](https://user-images.githubusercontent.com/62602652/144837436-c2ccee5c-a0d7-4036-bec4-0cd178da2037.png)

Then I reuse it.

![image](https://user-images.githubusercontent.com/62602652/144848344-f563e5c0-255e-4c4e-9a88-85d3a7112441.png)

If I edit the component via the first instance and update everything, the second one is updated. Fine.
![image](https://user-images.githubusercontent.com/62602652/144848461-bd1adee2-d011-4902-a12f-d17b778d825f.png)

But if I change the text or the font of the second one, and then change the component's color, the second one's color is not updated.
![image](https://user-images.githubusercontent.com/62602652/144848663-10dfdcf4-82ec-452f-81a6-063a8519a33d.png)

To get the changes, I have to update the second one manually, but then my changes of text or font are erased.

**Describe the solution you'd like**
I'd like that a property that has been changed in a component's instance is kept when another property of the component is updated.

**Describe alternatives you've considered**
Add a new option below "Cancel modifications" to "Update component" which updates only to not-modified properties from the component.

I hope I've been clear…

**Comment by EvaMarco** [comment]
Hello @NicolasLeboeuf, we are already aware of this problem and we are seeking the best way to solve it because it has a lot of implications. Thanks a lot for your colaboration.
