### ISSUE TITLE
Black space appears in view mode when accessed in full screen from mobile view in browser developer tools

### ISSUE THREAD

**Issue by shahrin014** [uxbox/uxbox#1397]
**Describe the bug**
When viewing on Chrome using the mobile responsive view in developer tools, there is a white space at the bottom of the screen.
This is somewhat similar to https://github.com/penpot/penpot/issues/1396, however I am logging a separate ticket because I think the issue might be different.

**To Reproduce**
1.  Run penpot from docker (not sure if this applies to penpot web)
2.  Open Chrome browser
3.  Access developer tools
4.  Change resolution to mobile (I used iPhone X)
5.  Go to view mode
6.  See white space at the bottom of the screen 
7. Go to full screen
8.  See black space at the bottom of the screen 

**Expected behavior**
The space should not be there.

**Screenshots**
Screenshot of artboard in workspace:
<img width="1904" alt="Screen Shot 2021-12-10 at 9 51 59" src="https://user-images.githubusercontent.com/17451563/145502143-519b69c1-9085-4da5-bc9e-4ff58a8c2a83.png">

Screenshot of issue:
![Screen Shot 2021-12-10 at 9 52 59](https://user-images.githubusercontent.com/17451563/145502003-32014529-d8af-43b4-8990-b40097535f76.png)

**Desktop (please complete the following information):**

-  Mac OSX
-  Chrome
-  Version 96.0.4664.93 (Official Build) (x86_64)

**Comment by shahrin014** [comment]
Just sharing some findings. If you override the CSS for viewer-section, and set height to 100vh, the issue seems resolved. However, I am not sure if this is the actual issue, of there is a better fix elsewhere.

![Screen Shot 2021-12-10 at 9 54 20](https://user-images.githubusercontent.com/17451563/145502249-8c0e3db1-d1c9-40e5-a769-74b54b82cb0c.png)

**Comment by EvaMarco** [comment]
Hello @shahrin014, as I told you in your last issue, we have opened a bug issue in taiga to manage both of your issues about white and black empty space, you can check it [here](https://tree.taiga.io/project/penpot/issue/2379). Thanks for your warning.

**Comment by pabloalba** [comment]
We can't reproduce it so I'm gonna close it. If it happens again, please tell us!
