### ISSUE TITLE
[Feature Request] View Only Mode for Workspace, Embeddable Workspace

### ISSUE THREAD

**Issue by candideu** [uxbox/uxbox#1398]
**Is your feature request related to a problem? Please describe.**
I would like to be able to invite people to view my workspace (not my prototypes) in a view-only mode without them having to sign-in. It would also be nice if we could embed this view-only workspace in other web pages.

Here is an example of a view-only workspace in Figma: https://www.figma.com/file/3l5flqotI1xyuec6d2CGe2/AM-Studio-by-Alice-Mollon/duplicate?node-id=3%3A19

Here is an example of Figma's share options in action:

https://user-images.githubusercontent.com/55474996/145532648-0e908007-6432-485d-ab2c-1f07b668d80a.mp4

**Comment by EvaMarco** [comment]
Hello @candideu, this idea it's already in our taiga. [Here](https://tree.taiga.io/project/penpot/us/1056?backlog-exclude_status=2076392,2076391,2076390&backlog-q=view%20mode&no-milestone=1) is a link to the issue. 
Thanks for your answer.
