### ISSUE TITLE
Text Formatting Issue: All text changes font weight if no section of text is highlighted/selected

### ISSUE THREAD

**Issue by candideu** [uxbox/uxbox#1400]
**Describe the bug**
If you change the weight of text without highlighting a particular passage, it changes the weight for _all_ the text.

Here is a video of the issue:

https://user-images.githubusercontent.com/55474996/145533461-3fa82fc8-e95a-4c6b-9c86-120de4577d1d.mp4

**To Reproduce**
1.  Create a text box and use a font with multiple weights.
2.  Type some things up
3.  Highlight/Select some text and make it bold.
4. Deselect, and change the font weight to something else.
4.  See error: all the text changes.

**Expected behavior**
Nothing happens when you change the weight and no text is selected/highlighted.

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser: Firefox 94.02

Using SAAS (https://design.penpot.app).

**Comment by EvaMarco** [comment]
Hello @candideu, we are going to study this case. I have opened a Taiga issue that you can check [here](https://tree.taiga.io/project/penpot/issue/2390).
Thanks for your help.
