### ISSUE TITLE
All export options not working (for me) on penpot.app

### ISSUE THREAD

**Issue by cparkerx** [uxbox/uxbox#1403]
**Describe the bug**
When I attempt to export an artboard from penpot.app (not self hosted) I get the message "an unexpected error occurred". I get this error no matter what format I choose (png, jpeg, svg, pdf). I have tried different penpot projects/artboards and different browsers and devices. I get this error on everything.

**To Reproduce**
1.  Go to export an artboard
2.  Click on any format and click export
3.  Wait, and after about a minute the error shows up
4.  See error in top right of browser window, and server error 500 in browser console

**Expected behavior**
I expect the export to succeed.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Chrome/Firefox
-   Version Latest version of both browsers

**Smartphone (please complete the following information):**

-   Device: iPhone Xr
-   OS: latest iOS version
-   Browser Firefox
-   Version latest version

**Environment (please complete the following information):**
using SAAS (https://design.penpot.app)

**Additional context**
I just found this project, and I love it! you all are doing great work. This is the only issue I have run into. Thank you.

**Comment by jdittrich** [comment]
I have the same problem on penpot.app  (Firefox)

**Comment by cparkerx** [comment]
I tried exporting again today, and the export options seem to be working.

**Comment by niwinz** [comment]
Yes, this is a known issue, for some reason on time to time the exporter process becomes unresponsive, and we need to research the underlying problem. For now, a simple restart fixes the problem hehe.

Thanks for notifying it here.
