### ISSUE TITLE
double click on component in file library to rename

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#1406]
I expected to be able to double click the component to rename it. would be a minor decrease in interaction cost over the current 1) right click 2) move mouse to rename 3) click rename 4) input field focused

![image](https://user-images.githubusercontent.com/46250921/145658120-903f5902-5ecd-4a11-8810-62649bd74829.png)

**Comment by EvaMarco** [comment]
Hello @jsmorabito, I have opened a Taiga issue to add your idea to our queue. If you want to check the state of it you can do it [here](https://tree.taiga.io/project/penpot/issue/2393).

Thanks for your interest.
