### ISSUE TITLE
Lock image ratio

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#1408]
**Is your feature request related to a problem? Please describe.**
When I import an image, its dimension ratio is not locked. Though I almost never want to deform my images.

**Describe the solution you'd like**
Automatically lock the image ratio when imported.

**Comment by girafic** [comment]
For me it's locked on https://penpot.app/ . It was already solved with the version 1.2.0 Alpha.

<img width="272" alt="grafik" src="https://user-images.githubusercontent.com/1187276/146163477-77bd09ef-53fc-47ff-a1d9-da903fea07b3.png">

**Comment by NicolasLeboeuf** [comment]
Ok then it needs a precision.

Indeed png and jpeg are locked, by not svg. I was working with Font Awesome svg icons.

**Comment by girafic** [comment]
> Ok then it needs a precision.
> 
> Indeed png and jpeg are locked, by not svg. I was working with Font Awesome svg icons.

Same behaviour you will see in Sketch or Figma for SVGs.

**Comment by EvaMarco** [comment]
Hello @NicolasLeboeuf.
We lock proportions of all non-vector images by default when importing because deformation makes the images lose information. This loss does not happen with SVGs because they are vectors. 

This is a common pattern between designing tools. Hope this helps.

**Comment by NicolasLeboeuf** [comment]
Ok I didn't know, fine.
