### ISSUE TITLE
Penpot stuck at the login page

### ISSUE THREAD

**Issue by Dzeykob** [uxbox/uxbox#1409]
Hi everyone.
The problem I'm describing is mostly my fault, but I've been trying to figure it out since Thursday.
After installing docker and penpot I am able to get to the login page, create a user in the console and "log in" using their credentials. The page changes to /#/dashboard for a split second when logging in, then goes back to /#/auth/login again. 
I see a welcome window with an introduction (as in the screenshot), but nothing else changes. 
I installed docker according to two different instructions, changed ports, checked on different devices - the problem is identical everywhere. 
Thanks for the help - I'm just learning.

![image](https://user-images.githubusercontent.com/96046335/145777277-adb6578f-f877-4d67-85bf-66fab5af5937.png)

EDIT
The only errors I found are from F12/webbrowser
![image](https://user-images.githubusercontent.com/96046335/145783501-f8616d13-38e4-42ef-bfd8-5d087390e688.png)
Im getting those errors after "successful login".

**Comment by niwinz** [comment]
Hi @Dzeykob , when you exposes it under different host than localhost there are different options that can affect the login. For the next release we try to improve the defaults for make it more easy to start on situations when you are serving it out of localhost.

In any case, without knowing the exact version you are running (you can see it on the devtools console) and configuration used, I don't know what can going wrong. Can you provide this information?
