### ISSUE TITLE
[Critical] Penpot down

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#1410]
**Describe the bug**
The tool can't be accessed anymore

**To Reproduce**
1.  Try to connect on design.penpot.app.
2. Blank page

**Expected behavior**
Tool loading

**Screenshots**
![image](https://user-images.githubusercontent.com/62602652/145824593-7a6625d8-53c2-4240-94d0-ce1c1c73d981.png)

**Environment (please complete the following information):**
SAAS

**Additional context**
On any browser, private browsing. Happens since a few minutes.

**Comment by elhombretecla** [comment]
Hi @NicolasLeboeuf please try again. We already fix the issue :)

**Comment by NicolasLeboeuf** [comment]
It's working :)
