### ISSUE TITLE
Design tab parameters not updating automatically on artboard switch

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#1411]
**Describe the bug**
When I switch my selection between artboards, the currently selected artboards settings are not automatically shown in the design tab

**To Reproduce**
1.  select artboard 1 
2.  select a second artboard with different settings
3.  observe that design tab shows the settings for artboard 1 while artboard 2 is selected

**Expected behavior**
Design tab to update automatically like it does when switching selection between objects

Tested on Safari and Brave browser

**Additional context**
pressing escape will put the design tab into a default state from which an artboard can be selected and its settings shown in the design tab

**Comment by EvaMarco** [comment]
Hello @jsmorabito, this is fixed in our pre-production code, we are going to deploy it very soon. Stay connected!. 

Thanks for the info by the way.

**Comment by jsmorabito** [comment]
ok, do you know if the following behavior is also fixed? let me know if not and i can make a separate issue. 

1. select object
2. switch selection to another object
3. observe previously selected object settings shown in design tab

I'm able to work around this by pressing escape or clicking outside of the object before selecting a new one which you can see in the video

https://user-images.githubusercontent.com/46250921/146989776-f3ba1b23-7b64-4547-9b1f-a885245885a4.mov

**Comment by EvaMarco** [comment]
Hello @jsmorabito,  this is also fixed!. 
Thanks for your interest.
