### ISSUE TITLE
Error when importing Penpot file with a linked library

### ISSUE THREAD

**Issue by garrett** [uxbox/uxbox#1412]
**Describe the bug**

I've exported a mockup that I'm working on. The export includes the library. However, importing does not work.

**To Reproduce**
1.  Download [attached ZIP file](https://github.com/penpot/penpot/files/7713183/Mockups.penpot.zip)
2.  Extract ZIP file
3.  Import Mockups.penpot file
4.  See error

**Expected behavior**
I expected to have both files import. Right now, only the library imports successfully. The error message doesn't say what the problem is (although I wouldn't be able to fix the problem most likely, as it's probably a bug in Penpot's importing and/or exporting).

**Screenshots**

![Screenshot 2021-12-14 at 17-25-54 Penpot Design Freedom for Teams](https://user-images.githubusercontent.com/10246/146038506-61559f31-301c-41f4-953e-e75778309218.png)

**Desktop (please complete the following information):**

-   OS: Linux, Fedora 35
-   Browser: Firefox 95

**Environment (please complete the following information):**

Using hosted version: https://design.penpot.app

**Other information**

[Mockups.penpot.zip](https://github.com/penpot/penpot/files/7713183/Mockups.penpot.zip)

(Compressed in a ZIP to share via GitHub)

**Comment by EvaMarco** [comment]
Hello @garrett: 
I have opened a taiga issue to manage your problem with that import. You can watch all info [here](https://tree.taiga.io/project/penpot/issue/2402).
Thanks for the information.

**Comment by Alotor** [comment]
@garrett looks like the original file had a problem that makes the import invalid. 

We have two problems: first how did we could generate an invalid shape in the export (a bug probably related to geometry transforms) and the second is how to "do our best" on the import so even if everything is not perfect you could potentialy get most of your design.

We're going to change the import problem so if we find a problem with any shape we still do the import but display a warning like... "The import finished but some shapes couldn't be imported". So at least the user can decide if the result is bad or good.

In the meantime if you want I can re-export your file so it doesn't have any more invalid shapes.

**Comment by Alotor** [comment]
@garrett I attach here the fixed export file. It has a missing shape that was causing the problem. But apart from that should be pretty much identical.

[Mockups_fix.penpot.zip](https://github.com/penpot/penpot/files/7814817/Mockups_fix.penpot.zip)

**Comment by garrett** [comment]
Awesome! Thanks! The fixed one works here.

![fixed import](https://user-images.githubusercontent.com/10246/148244926-9050abc4-95b8-4827-a94d-f38e6da519fa.png)

Thanks for working on this; I'm looking forward to the fixes!
