### ISSUE TITLE
Rotation option for gradients

### ISSUE THREAD

**Issue by nicosammito** [uxbox/uxbox#1413]
**Is your feature request related to a problem? Please describe.**
I wanted to rotate a gradient inside of a text but this isn't possible

**Describe the solution you'd like**
A rotation (360°) option for gradients not only in boxes but also in texts

**Comment by EvaMarco** [comment]
Hello @nicosammito.  
I've created a Taiga issue about this. You can check it [here](https://tree.taiga.io/project/penpot/issue/2394).
As you can see its priority is low right now because we have a lot of things to do, but I hope in the future we can do it. 
Thanks for your help.
