### ISSUE TITLE
Inside group elements selected not showing true size

### ISSUE THREAD

**Issue by APattjoshi** [uxbox/uxbox#1423]
Describe the bug
I made a group out of two elements, wanted to change the size of the elements individually inside the group but unable to see the true size of the element inside the group

To Reproduce

Create two shapes one is a background square box and next is an eclipse of smaller size above it
Group both the element
Double click to edit it
Went inside the group to change the size of the eclipse shape
The size shows the group size instead of the individual element size

Expected behavior
I want to double click and change the shape of the element after seeing its true size

Screenshots
<img width="1182" alt="re" src="https://user-images.githubusercontent.com/47391164/147478596-8278a774-374d-4868-953f-f60e106ede05.png">

Desktop (please complete the following information):

OS: (Windows 10)
Browser (chrome)
Version (88.0.4324.182 (Official Build) (64-bit)
Environment (please complete the following information):
Specify if using SAAS (https://design.penpot.app).

**Comment by myfunnyandy** [comment]
Hi, this is a known issue that we have already fixed but still not deployed (we plan to do it soon). Thanks for the report :)
