### ISSUE TITLE
Push 1.10.2-beta to Docker Hub & questions on the release process

### ISSUE THREAD

**Issue by saibotk** [uxbox/uxbox#1425]
Hello and thank you for this awesome piece of software!

Can you push the latest version to Docker Hub? It seems to be missing there, but the version is already released and tagged.

Also, it would be nice to have minor versions listed as real "releases" in GitHub's Releases tab for visibility.

And what is the current process of releasing a new version to Docker Hub? What would block an automated process using GH Actions or similar tools?

PS: Since the latest 1.10.2 release contains log4j updates, how is penpot affected by the recent security issues? Would that maybe also speak for a quick release to Docker Hub? And if it was vulnerable, I would like to suggest releasing a Security Advisory here on GitHub next time / now :)

Thank you very much :rocket:

**Comment by niwinz** [comment]
Hello @saibotk 
You are right that the docker images building can be automatized but right now, we didn't have time for it.

About the log4j2 issues, penpot does not logs anything from user input, so it should be safe. In any case we have updated the dependencies. Right now we preparing another  minor release and it will come with docker images updated (should be out today or tomorrow).

**Comment by saibotk** [comment]
Thank you very much for the quick response and your answers :)

**Comment by niwinz** [comment]
1.10.4-beta is on dockerhub ;)

**Comment by saibotk** [comment]
Nice 👍 thank you.

But would you also consider adding release notes on GitHub for patch releases?

**Comment by niwinz** [comment]
We will consider it for future releases :D
