### ISSUE TITLE
pressing [Shift+1] in an empty document causes internal error

### ISSUE THREAD

**Issue by ghost** [uxbox/uxbox#1435]
**Describe the bug**
pressing [Shift+1] in an empty document causes internal error

**To Reproduce**
1.  open new document
2. press [Shift+1]
3. see  "Internal Error"

**Expected behavior**
zoom set to default state, same as by creation of the document

**Screenshots**
firefox: internal error
![Internal Error_20220101105302](https://user-images.githubusercontent.com/59403389/147849049-fc9a8b5a-ce53-4a00-b809-3154ce8fa210.png)

chrome: infinite loop
![batman_20220101105628](https://user-images.githubusercontent.com/59403389/147849051-4acf2f18-1908-4cd2-ae9b-0f193f7a1212.png)

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser: Firefox (different for chrome)
-   Version: latest (web)

**Environment (please complete the following information):**
[x] using SAAS (https://design.penpot.app)

**Frontend Stack Trace (if self-hosted)**

<details>

```
12:02:21.715 Unexpected value Infinity Infinity -Infinity -Infinity parsing viewBox attribute. 2 react-dom.production.min.js:24:234
12:02:22.883
Unhandled Internal Error: d is null errors.cljs:159:7
12:02:22.883
TypeError: d is null
    r$ utils.cljs:51
    jYb actions.cljs:329
    React 11
    unstable_runWithPriority scheduler.production.min.js:19
    nb React
    x helpers.js:77
instrument.js:112:45
12:02:22.894
Unhandled Internal Error: d is null errors.cljs:159:7
12:02:22.895
TypeError: d is null
    r$ utils.cljs:51
    iYb actions.cljs:304
    VQa events.js:768
    SQa events.js:899
    b events.js:296
    x helpers.js:77
    _wrapEventTarget trycatch.js:139
    x instrument.js:479
    OQa events.js:261
    fM events.js:184
    PYb hooks.cljs:41
    vO alpha.cljs:200
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    c alpha.cljs:222
    Zg core.cljs:104
    Zg core.cljs:104
    $h core.cljs:52
    Kd core.cljs:30
    If core.cljs:35
    j core.cljs:871
    pc core.cljs:869
    j core.cljs:4536
    <anonymous> core.cljs:211
    RxJS 16
    next core.cljs:236
    j core.cljs:258
    g store.cljs:56
    mQb shortcuts.cljs:114
    b_a shortcuts.cljs:137
    J mousetrap.js:617
    _handleKey mousetrap.js:678
    handleKey mousetrap.js:1009
    G mousetrap.js:738
```

</details>

**Comment by myfunnyandy** [comment]
Hi, we've opened a bug at taiga to tackle this issue: https://tree.taiga.io/project/penpot/issue/2462

Thanks for the report.
