### ISSUE TITLE
Resizing Canvas Skews Shapes

### ISSUE THREAD

**Issue by nickian** [uxbox/uxbox#1440]
I'm running v 1.10.0-beta. Sometimes when I try to resize the canvas, the items on the canvas get skewed. If I do a "transform to path" on the shapes, they no longer get skewed on resize. Any idea what is going on here? An example gif below:

![2022-01-03 12-45-57-1-1](https://user-images.githubusercontent.com/590678/147975763-58aa3aa3-74af-491f-ae55-567edfc8c241.gif)
e

**Comment by myfunnyandy** [comment]
Hi, could you provide us a .penpot file where this happens so we can reproduce the issue?

Here we explain [how to export .penpot files](https://help.penpot.app/user-guide/import-export/), just in case you need it.

Thanks!

**Comment by myfunnyandy** [comment]
Here's the issue created on Taiga: https://github.com/penpot/penpot/issues/1440

**Comment by nickian** [comment]
Sure, here is a file that is doing this: https://cloud.creative.link/s/SRtjmDjZf4RkQTj/download

This is a file that was exported and imported into another installation. I only noticed this happening after that point. Maybe it's an import issue? I also noticed there are a bunch of 404 errors in the browser console when working on this file.

**Comment by Alotor** [comment]
@nickian Thanks for sharing the file with us. I've been able to reproduce your error with the file you sent us.
I hope we'll be able to deploy a fix for the next release.
