### ISSUE TITLE
Refused to display 'https://design.penpot.app/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by amira133** [uxbox/uxbox#1446]
**Describe the bug**

**To Reproduce**
first go to penpot.app and create a new project
then shared it via a link
then showing content of link in `IFrame` (https://design.penpot.app/#/view/187ac360-6343-11ec-bdf8-0d63a7779748?page-id=1d1dbe90-6343-11ec-bdf8-0d63a7779748&index=0&share-id=617cbe90-6e35-11ec-8da6-c2b142838c8b)
it show this error:
`Refused to display 'https://design.penpot.app/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Desktop (please complete the following information):**

-   OS: (e.g. iOS) = windows
-   Browser (e.g. chrome, safari) = any
-   Version (e.g. 22) = lastest

**Environment (please complete the following information):**
using https://design.penpot.app 

As you can see [here ](https://stackoverflow.com/questions/27358966/how-to-set-x-frame-options-on-iframe)you should probably add an option to set this feature to disable.
Of course, I encountered this problem on your main site and it may not be possible to fix it there.
But for self-host by adding an option to disable this feature, the problem is solved.

**Comment by niwinz** [comment]
I'm not clearly understand the problem here. This is not a bug, it explicitly enabled on the SAAS the `X-Frame-Options`.
On self-host it is not enabled by default.

**Comment by amira133** [comment]
Thanks
