### ISSUE TITLE
Can't log with a newly created user (localhost)

### ISSUE THREAD

**Issue by danielius-tvarijonas** [uxbox/uxbox#1447]
Hi,

I'm running a Penpot instance (the latest version) on a Raspberry Pi via Docker. Following the documentation, I've successfully created a new user (via the command in terminal) but when I try to log in, I get the following error message:

` 'Looks like you are not authenticated or session expired. Username or password seems to be wrong.'`

I tried creating another user, but it's still the same. In dev tools, there're no errors. Any ideas what could be the cause of it?
All containers are running normally.

Also, I tried to create a demo account but in the front-end a 'Create demo account' link is not clickable :(

**Comment by niwinz** [comment]
You probably need to activate the `disable-secure-session-cookies` flag because you probably don't using https and cookies are set with secure flag.

**Comment by danielius-tvarijonas** [comment]
> You probably need to activate the `disable-secure-session-cookies` flag because you probably don't using https and cookies are set with secure flag.

Thanks, it helped! I did add it to the config.env file and reinstalled it all from scratch. If I want to make changes to the config.env file after the container installation, where can I find the config.env file?

**Comment by niwinz** [comment]
I'm not cleary undestand your question. The config.env file is your personal file that you are using to configure the penpot instance.

**Comment by danielius-tvarijonas** [comment]
> I'm not cleary undestand your question. The config.env file is your personal file that you are using to configure the penpot instance.

Sorry, I barely know how to use docker and wasn't entirely sure how to set it up properly. So I have now installed it following this tutorial https://medevel.com/penpot/ and prior to running the installation command, I activated the flag you mentioned by adding it to the config.env file, and now it works fine, I'm able to create users and log in with no issues. I just have a question now, if I want to make any more changes in relation to other flags or in general, how do I make them so that they'd be applied to the Penpot's docker containers that are already installed and running?

**Comment by niwinz** [comment]
Ok, now I understand the question

You should just update this file, and **restart** the containers, restarting containers does not drops the previous data.

**Comment by danielius-tvarijonas** [comment]
> Ok, now I understand the question
> 
> You should just update this file, and **restart** the containers, restarting containers does not drops the previous data.

OK, so it will pick the changes up from the config.env file in original directory I've initiated the installation of containers from, right?

**Comment by niwinz** [comment]
yes

**Comment by danielius-tvarijonas** [comment]
> yes

Thank you!

**Comment by rastacalavera** [comment]
> You probably need to activate the `disable-secure-session-cookies` flag because you probably don't using https and cookies are set with secure flag.

update:
I see the flags should be in the config.env and I am guessing that each flag has to be on a new line (when on the same line, they are red in my text editor nano)
I have it setup like this
```
PENPOT_FLAGS="enable-insecure-registration"
PENPOT_FLAGS="disable-secure-session-cookies"
PENPOT_FLAGS="enable-demo-user"
``` 
I cleared the browser cookies but it still doesn't work
___
Where do you set this flag? I am having the same error. Running on local host http and not sure if that line gets put in the docker yaml or the config env file.

**Comment by danielius-tvarijonas** [comment]
> > You probably need to activate the `disable-secure-session-cookies` flag because you probably don't using https and cookies are set with secure flag.
> 
> update: I see the flags should be in the config.env and I am guessing that each flag has to be on a new line (when on the same line, they are red in my text editor nano) I have it setup like this
> 
> ```
> PENPOT_FLAGS="enable-insecure-registration"
> PENPOT_FLAGS="disable-secure-session-cookies"
> PENPOT_FLAGS="enable-demo-user"
> ```
> 
> I cleared the browser cookies but it still doesn't work
> 
> Where do you set this flag? I am having the same error. Running on local host http and not sure if that line gets put in the docker yaml or the config env file.

Add it to the config.env file, it should all be in the same line:

`PENPOT_FLAGS="enable-registration enable-demo-users disable-secure-session-cookies enable-insecure-registration"`.

Adding it after the installation of containers didn't work for me, so I did it from scratch, first modified the config.env file by adding that flag and then installed all containers again.

**Comment by rastacalavera** [comment]
Ah cool thanks for that. I've got it running now.

**Comment by hilltopmediadesign** [comment]
@john777555 Any tips on getting Penpot working on Raspberry Pi 4? I keep getting errors when attempting to using the default docker-compose. Looks like a platform error: standard_init_linux.go:219: exec user process caused: exec format error

Any help would be greatly appreciated.

**Comment by hilltopmediadesign** [comment]
@john777555 Scratch that. I was able to get it working. I needed to run an update on ubuntu server. All working.
