### ISSUE TITLE
federation: sync between multiple penpot servers

### ISSUE THREAD

**Issue by milahu** [uxbox/uxbox#1457]
currently, i backup my project to local `*.penpot` files

in the penpot interface, i want to click "add server",
to connect to my selfhosted penpot server,
so i always have a backup of my project

federation protocols: matrix chat, activitypub/mastodon, (nextcloud?)

challenge: conflict resolution (CRDT)
\+ user authentication across different servers
&rarr; [gun](https://github.com/amark/gun/wiki/awesome-gun)?

nice to have: preserve the full edit history,
similar to etherpad timeslider and revisions

**Comment by niwinz** [comment]
Hi @milahu 

I think we don't need CRDT's here in any case.
Interesting ideas, and we annotate them for the future. But being realistic, we cant approach on this on the near future and keeping open the issue for long time does not make sense. We annotate this on our internal ideas list and I close the issue right now.

Thanks!
