### ISSUE TITLE
duplicated object should appear below

### ISSUE THREAD

**Issue by milahu** [uxbox/uxbox#1458]
when i duplicate an object ...

actual:
the new object is created \*above\* the original

expected:
the new object is created \*below\* the original

use case:
i use "duplicate" to add new pages ("artboards")
so the new page should be appended, not prepended

**Comment by elhombretecla** [comment]
Hi @milahu

We understand that are different opinions based on different mental models. The one we follow is that each new object created appears on top of the selected object, regardless of the type of action (duplicate, paste, create). This model is also a pattern that occurs in almost all design tools and that makes it familiar to users.

Thanks a lot!
