### ISSUE TITLE
laggy text input for large documents

### ISSUE THREAD

**Issue by milahu** [uxbox/uxbox#1478]
### Reproduce

1\. create a "large" document with many pages (artboards) and lots of text
2\. insert text by typing each character

### Actual

the typed characters dont appear "live" but with a long delay/lag of multiple seconds (say, 5 seconds)

### Expected

the typed characters should appear "live"

### Solution

disable "off screen" rendering

pages (artboards) which are currently not visible (due to zoom level and pan position)
should be excluded from "live updates"

### Environment

https://design.penpot.app/

html source says

```js
window.penpotVersion = "1.10.3-beta-6102-gfdb1c5e1f";
```

**Comment by milahu** [comment]
could be cause by excessive debouncing of the keydown handler
-> [debounce or throttle](https://programmingwithmosh.com/javascript/javascript-throttle-and-debounce-patterns/)?

more general: react is slow, cos virtualdom is slow (not one bottleneck, but "death by a million cuts")
-> svelte, solidjs are faster for such micro updates (but their ecosystems are small)

call tree while sending keydown events

![penpot bug laggy text input javascript call tree](https://user-images.githubusercontent.com/12958815/149621064-dfb25ed8-d6ae-4da7-bfbf-ee650d794e37.png)

**Comment by niwinz** [comment]
We will research on it [taiga issue](https://tree.taiga.io/project/penpot/issue/2599)

We already have some kind of disabling off screen rendering, but sometimes it does not works, or at least look so.
Thanks for report.

**Comment by hollisticated-horse** [comment]
I'm getting similar issues with texts, though not on huge projects. 

If an text block **in a component** has text already and you replace it, it keeps the previous text on top of the current input:

![image](https://user-images.githubusercontent.com/76632257/152655651-79307231-4a16-4768-97fa-5851a91caa78.png)

Am on Firefox latest, Archlinux and design.penpot.app

**Comment by milahu** [comment]
@hollisticated-horse not similar, please make a separate issue

to reproduce

1. create text box, insert text
2. select all text with Ctrl+a
3. insert second text

actual: now there are two text boxes, directly overlapping
expected: should be only one text box, holding the second text

**Comment by hollisticated-horse** [comment]
Do you want me to remove the comment here @milahu  ?

**Comment by milahu** [comment]
that would be sweet

this comment will self-destroy in 3.. 2.. 1..

**Comment by niwinz** [comment]
This should be considered solved. Many improvements landed on this area in the latest versions.
Thanks for reporting.
