### ISSUE TITLE
svg stroke-width does not scale 

### ISSUE THREAD

**Issue by milahu** [uxbox/uxbox#1480]
when i resize svg graphics, the stroke-width stays constant

when i make the svg larger, the stroke-width is too small
when i make the svg smaller, the stroke-width is too large

example svg

```svg
<?xml version="1.0"?>
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">

<g id="dont-tumble-symbol" fill="none" stroke="black" stroke-width="5">
  <line x1="20" y1="20" x2="80" y2="80" />
  <line x1="80" y1="20" x2="20" y2="80" />
  <rect x="10" y="10" width="80" height="80" />
  <circle cx="50" cy="50" r="30" />
</g>

</svg>
```

### workaround: scale

manually set the viewBox size, so you dont have to scale in penpot

then, scale all coordinates with

```svg
<?xml version="1.0"?>
<!-- old: viewBox="0 0 100 100" -->
<svg viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">

<g transform="scale(0.5)">

<g id="dont-tumble-symbol" fill="none" stroke="black" stroke-width="5">
  <line x1="20" y1="20" x2="80" y2="80" />
  <line x1="80" y1="20" x2="20" y2="80" />
  <rect x="10" y="10" width="80" height="80" />
  <circle cx="50" cy="50" r="30" />
</g>

</g>

</svg>
```

### workaround: pattern

the stroke-width-scaling does work in svg patterns
but the problem with svg patterns is, they trigger a browser bug in chromium:
on printing or PDF export, the pattern becomes blurry

```svg
<?xml version="1.0"?>
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">

<defs>
  <pattern id="dont-tumble-symbol" width="100" height="100" patternUnits="userSpaceOnUse">
    <g fill="none" stroke="black" stroke-width="5">
      <line x1="20" y1="20" x2="80" y2="80" />
      <line x1="80" y1="20" x2="20" y2="80" />
      <rect x="10" y="10" width="80" height="80" />
      <circle cx="50" cy="50" r="30" />
    </g>
  </pattern>
</defs>

<rect x="0" y="0" width="100%" height="100%" fill="url(#dont-tumble-symbol)" />

</svg>
```

<details>
<summary>screenshots</summary>

screen:

![penpot bug svg stroke width scale-screen](https://user-images.githubusercontent.com/12958815/149626407-378ad53e-ce46-446e-9312-80302da19967.png)

PDF:

![penpot bug svg stroke width scale-print](https://user-images.githubusercontent.com/12958815/149626408-4499a3e8-605b-4dc2-9391-db6181e70781.png)

</details>

**Comment by elhombretecla** [comment]
Hi again @milahu :)

This is not a bug, is an enhancement. Your proposal is ok but, as a user, I might prefer to mantain the stroke by scalling only the object (think on a button with stroke, for example).

I will add this as an enhancement in Taiga (our project management tool) and prioritize it in our road map :)

[https://tree.taiga.io/project/penpot/issue/2548](https://tree.taiga.io/project/penpot/issue/2548)

**Comment by NicolasLeboeuf** [comment]
I add my 2 cents.

I disagree, as a user, I do want the strokes to be scaled, for a very simple reason: when I use SVG icons, depending on how they are created, the stroke must be scaled.

The Ionic icons, for instance, can not be scaled because of that. We were considering switching from FA icons to Ionic icons, but if I can not add them, that's an issue.

[Uploading Capture vidéo du 15-06-2023 16:37:34.webm…]()

**Comment by superalex** [comment]
Thanks!,

Penpot support both modes, if you press the key "k" it changes the scale mode:

https://github.com/penpot/penpot/assets/1579633/b9382b3f-66fc-4d17-9a52-bfa06961a22a

**Comment by NicolasLeboeuf** [comment]
Game changer :)
