### ISSUE TITLE
Export to SVG/PNG/JPEG doesn't work on design.penpot.app

### ISSUE THREAD

**Issue by schlichtanders** [uxbox/uxbox#1483]
this is the very same bug as described by the already closed ticket https://github.com/penpot/penpot/issues/1050
however it appears for me in the current design.penpot.app free web version

----------------

Background: I am completely new and tested out some functionality. The export functionality is quite crucial for ensuring a truly flexible svg tool, hence I tested it.

As a workaround it seems one can instead export the .penpot file from the project overview page. Unzipping it seems to give the underlying svg.

**Comment by elhombretecla** [comment]
Hi @schlichtanders thanks for your feedback :)

There are two ways of "export" files in Penpot at this moment.

1- Export the whole file as a .penpot file. This is quite useful to share or make file backups.
2- Export an element (artboard, gruop, shape,...) as a JPG, PNG, SVG or PDF. This option is located on the right sidebar at the workspace.

We are experiencing some issues with the PDF export option but SVG, PNG and JPG export are available.

![image](https://user-images.githubusercontent.com/1045247/149736951-fa6135fd-92c0-4a29-889c-a30cb9ac1c57.png)

**Comment by schlichtanders** [comment]
yes that is the export I am referring to
I admit I haven't tested png or jpeg, but I actually tested svg and pdf, both didn't work the time I created this issue.

I now tested SVG again and can confirm that it works.
Also PDF export works now.

Not sure what it was that it failed for me yesterday, but great it works
