### ISSUE TITLE
Ability to swap color themes

### ISSUE THREAD

**Issue by tbmatuka** [uxbox/uxbox#1486]
When working on a site with more than one color theme (usually light and dark), it would be useful to be able to design only one theme and swap color themes to see what the other themes look like.

There are 2 potentials solutions I can think of right now:
1. Add the ability to create an alias for a color group which would make the group's colors available under our new alias group. Switch the group the alias points to to change the theme. The possible problems I see with this approach are mostly related to missing colors and their handling.
2. Create a smarter alias with a fallback (default) theme. This alias would try to resolve the color in the group that is set as current theme and if it couldn't it would look in the default theme. Again, there would be a problem with missing colors when a designer adds a color to the additional theme but doesn't add it to the default one and switches back to it. In this case we would need a prompt that asks them if they really want to switch and show a list of colors that will be added from the current theme to the default one. This will make sure that the design never uses colors which exist in a specific theme but not in the default one. The colors that would be added could also be only those that are actually used and not all of the ones that are defined.

The UX steps to use it would look like this:
1. Prepare the colors. If they are not already grouped, group them into a group whose name doesn't matter, but let's use `light` for this example. Moving colors around keeps them linked at the moment, so this step doesn't require anything new.
2. Right click on the `light` group and click a new option called `Make this the default theme`. This option would have switch all references to the group colors to point to the theme alias instead.
3. Right clicking on another group (for example `dark`) would now offer an option called `Activate theme` which would override values from the default group. Any color that is missing in the `dark` group would fall back to the value from the default group.
4. Designed adds a color to the `dark` group and uses it in the design through the theme alias. This color would exist in `dark` but not in `light`.
4. Right clicking on the `dark` group would give an option called `Deactivate theme` which would bring us back to using only the default theme. Since we would have a color that is used and defined only in `dark`, we would get a prompt saying "There are colors in `dark` that need will be copied to `light`:" and it would give a list of colors with buttons to continue or cancel.
5. Right clicking on the `dark` group when it's not active would also give us an option called `Make this the default theme` which would have to copy all referenced colors from the old default to the new default with the same prompt as before.

This UX would work well for development as well, since it fits with how theme colors are already defined and generating code for color themes with a plugin or CI integration would be cool.

**Comment by elhombretecla** [comment]
Hi @tbmatuka thank you very much for your detailed feedback :)

We already have an User Story to approach this topic. UI themes will be an important part of Penpot in terms of design and accessibility.
Your proposal is going to be added to the User Story and will be revised once we start working on it.

[https://tree.taiga.io/project/penpot/us/2287](https://tree.taiga.io/project/penpot/us/2287)

**Comment by tbmatuka** [comment]
@elhombretecla I've been going through my issues and realized that the taiga issue you linked is for user themes, not designing them. Can you please take another look at the issue?

**Comment by elhombretecla** [comment]
I see. Thanks for notice this :)

We have created an enhancement in Taiga [https://tree.taiga.io/project/penpot/issue/4135](https://tree.taiga.io/project/penpot/issue/4135)
