### ISSUE TITLE
Grouped images don't resize appropriately. 

### ISSUE THREAD

**Issue by mrbracchi** [uxbox/uxbox#1497]
**Describe the bug**
I have a group created for a simple "window" shape. Gray background, black square border and two black rectangles that are horizontal and vertical. All shapes should be centered horizontally and vertically. When the group is selected and resized, not all elements honor the resizing behavior. Mostly, the gray background retains its shape but at other times some of the rectangles do not resize as well.
**To Reproduce**
I've included a file to show the behavior and screen shots as well.

**Expected behavior**
All grouped items should scale appropriately and resize correctly.
**Screenshots**
![Snag_93f590](https://user-images.githubusercontent.com/42683116/150188769-526d4b64-e725-44d1-9138-e5b32fd5a774.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Chrome 
-   Version 97.0.4692.71 (Official Build) (64-bit)

**Environment (please complete the following information):**
self-hosted instance running on docker. Host OS is Ubuntu based.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Zorin OS 16, 64 bit, Kernel 5.11.0-46

**Additional context**

**Comment by mrbracchi** [comment]
~~File can be found [here]()~~

**Comment by elhombretecla** [comment]
Hi @mrbracchi thank you so much for your detailed feedback :)

I'm testing your file and found a possible solution. It seems that you have changed the constraints of the inside lines of the window.

![image](https://user-images.githubusercontent.com/1045247/150192040-729086cf-4cef-493e-ad45-7c90b815be4b.png)

Please try again setting the constraints to "scale" and test if the problem is solved.

**Comment by mrbracchi** [comment]
Thank you for the reply! I spend a lot of time testing this tool today and will try as you suggest tomorrow or this evening. I am very impressed with what this software can offer and look forward to following its progression. Maybe down the road I can help contribute to your documentation. This is my public github account which isn't very active but I have another where I do a lot of documentation help. Am I correct that all contributions must be tied to a "real" person or could I use my alt account?

**Comment by mrbracchi** [comment]
> Hi @mrbracchi thank you so much for your detailed feedback :)
> 
> I'm testing your file and found a possible solution. It seems that you have changed the constraints of the inside lines of the window.
> 
> ![image](https://user-images.githubusercontent.com/1045247/150192040-729086cf-4cef-493e-ad45-7c90b815be4b.png)
> 
> Please try again setting the constraints to "scale" and test if the problem is solved.

Setting each item to scale in the group solved the issue I was experiencing. Thank you
