### ISSUE TITLE
Prototype view not accessible from iOS -IPv4 related?

### ISSUE THREAD

**Issue by EnidKapelsen** [uxbox/uxbox#1522]
**Users invited to see a prototype are not able to open the link on their iOS device**
Instead of the prototype users see „internal error. If problem persists please contact support.“
We assume that PenPot runs on iPv4. This would explain iOS blocking the connection. 

**To Reproduce**
1.  Chose a page 
2.  Click „Share Prototype“
3. Choose „Zuschauer“ (probably „View only“ in the English version? 
4.  Send to Person with iOS device.

**Expected behavior**
The recipient of the link will not be able to open the prototype. 

**Screenshots**
![C64EFBED-9246-400D-A904-24638FF1F393](https://user-images.githubusercontent.com/6633240/151657747-89e49edc-0b35-48cd-99de-b84d6a651ce9.jpeg)

**Smartphone (please complete the following information):**

-   Device: 5 different iPhones
-   OS: at least one of them: iOS 15.3
-   Browser  Safari and Chrome

Motivational Cat for you: 😻

**Comment by hirunatan** [comment]
This strange! I've created an issue in Taiga to track it as quickly as possible: https://tree.taiga.io/project/penpot/issue/2732

Thanks for your detailed report. Do you have any more info about what is the IPv4 condition that applies here?

And thanks for the cat, it will surely help us to work in this one sooner ;)

**Comment by superalex** [comment]
I think it's not related to IPv4, inspecting a bit the error says: "seems like the current browser does not support fullscreen api."

![1](https://user-images.githubusercontent.com/1579633/152377368-ddce645e-0581-4b28-8847-341f77b059d5.png)
