### ISSUE TITLE
Import SVG with images stored externally

### ISSUE THREAD

**Issue by der-On** [uxbox/uxbox#1531]
When I import / drag & drop a SVG onto the canvas that contains images stored outside the SVG file penpot aborts due to a validation error. The error tells me that the URL to the image could not be found.

Instead I would like penpot to import the SVG and the images but gracefully ignore unreachable URLs so I can replace those missing images in penpot myself.

An alternative would be to replace images with unreachable URLs with a placeholder image that displays e.g. a red "X" to indicate that there is a missing image.

**Comment by hirunatan** [comment]
It's interesting. I have opened a Taiga issue for tracking this. Thanks for the suggestion.

https://tree.taiga.io/project/penpot/issue/2731

**Comment by Alotor** [comment]
I'm going to make so the images that cannot be uploaded are just skipped.
