### ISSUE TITLE
Optimize PNG images

### ISSUE THREAD

**Issue by rhcarvalho** [uxbox/uxbox#1533]
**Is your feature request related to a problem? Please describe.**

PNG images can be losslessly compressed reducing bytes in disk and in transit.

**Describe the solution you'd like**

We can compress the images in the penpot repo using a tool like `zopflipng`. It could even be eventually automated with a GitHub Action/Workflow/etc to ensure new images are properly optimized.

**Describe alternatives you've considered**

There are other tools (e.g. `optipng`) out there, but `zopflipng` has been out for a long time, is stable and packaged for Linux distros and generates good results.

**Additional context**

References

- https://github.com/google/zopfli
- https://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/
- https://ariya.io/2016/06/using-zopfli-to-optimize-png-images

I can provide a PR with changes.

**Comment by rhcarvalho** [comment]
For what is worth, the gain to be had is going from 728 KB to 576 KB in total (79% of original).

In the meantime, I've noticed some images are also apparently not in use (were replaced with new images in past commits and the old images were never removed), so we could reduce disk / bandwidth usage even further by removing unused images -- but that might be a separate issue/concern.

<details><summary>Example</summary>
In d93fa72e48dabc7be7f5b16886ef0b2e20f796c5 

```diff
-    [:img {:src "images/pot.png" :border "0" :alt "Penpot"}]]
+    [:img {:src "images/login-on.jpg" :border "0" :alt "Penpot"}]]
```

A new file `frontend/resources/images/login-on.jpg` was created, but `frontend/resources/images/pot.png` remained and is apparently unused.
 
</details>

**Comment by hirunatan** [comment]
Thanks very much for the idea! Every optimization matters in a complex application like this.

If you want to provide a PR with the optimized pngs, and removing the ones that are not used, it will be very welcome.

About the automation, we prefer not to do it in a completely automatic way (this could cause imprevist strange effects, although unlikely). We prefer to have for example a script in `frontend/scripts` that does the job, and run it manually at some certain point, for example, before making a new release.

**Comment by hirunatan** [comment]
The zopfi compressor is lossless, but I've found that in corner cases it may cause some information loss:

https://github.com/google/zopfli/issues/113

It should be taken into account, for example by using the `--keepchunks=iCCP` flag in the command line, as explained there.
