### ISSUE TITLE
Aligning objects in container with odd side length causes invalid object sizes and positions

### ISSUE THREAD

**Issue by archer-321** [uxbox/uxbox#1544]
**Describe the bug**

When aligning objects using the resize action (and possibly other actions) in containers (e.g. artboards) that have odd side lengths, the objects' position and size can end up invalid, and the object outline and resize controls don't match the visible object.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an artboard with odd side lengths (I tried it with 603 px by 779 px, but all odd side lengths should work)
2. Create a rectangle and position it in the upper half of the artboard
3. Resize the rectangle so that it fills out the top part of the artboard
4. Create another rectangle and place it in the bottom half of the artboard
5. Resize the second rectangle so that it fills out the bottom half of the artboard
6. Check the object outline for the second rectangle; it doesn't match the visible (pixel-aligned) second rectangle

**Expected behaviour**

Like the visible rectangle, the outline and the actual position are pixel-aligned.

**Screenshots**

Here's a video: https://youtu.be/jySVQTCnSTU
Resizing the artboard to even side lengths in the part starting at 2:39 fixes the problem when re-aligning all inner objects.

**Desktop (please complete the following information):**

-   OS: GNU/Linux
-   Browser: Firefox Nightly
-   Version: Nightly 98.0a1 (2022-02-03), but I have experienced this with every version of Firefox

**Environment (please complete the following information):**

SAAS (https://design.penpot.app)

**Additional context**

Especially when creating quick pixel-perfect mockups, I rely on object aligning and snapping. This bug is currently my only reason to use other services.

This bug most likely relates to #1232.

**Comment by hirunatan** [comment]
Hello. Thanks for you well explained report.

This is a complicated issue, because there are conflicting interests, and our current implementation does not resolve every case well. We are investigating it, hope we'll reach a result soon.

https://tree.taiga.io/project/penpot/us/2552

**Comment by archer-321** [comment]
I tested this again in `1.13.0-beta` on `design.penpot.app`, and the problem disappeared. Even when disabling "Snap to Pixel", the outline works as expected.

I'll close this issue as the problem is fixed.
Thank you to everyone who made this feature possible! :tada:
