### ISSUE TITLE
Artboard invisible if locked

### ISSUE THREAD

**Issue by hollisticated-horse** [uxbox/uxbox#1549]
**Describe the bug**
When locking an artboard, it does not get loaded back if moved out of screen and back. The Art Board label is showing but there is no content, no box. I don't know if it's by design or a bug though.

**To Reproduce**
1.  Make a new project and Artboard
2.  Lock the artboard
3. Move anywhere until the artboard is outside the screen.
4.  Move the artboard back into view and it will be invisible except the title

**Expected behavior**
The artboard should be visible even if locked, and be hidden if toggled as hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/76632257/152654858-968d9abc-70d6-47ce-93e3-64403d17bc9c.png)

**Desktop (please complete the following information):**

-   OS: Archlinux
-   Browser (e.g. chrome, safari): **Firefox 96.0.3** archlinux
-   Version (e.g. 22): 1.11.0-beta

**Environment (please complete the following information):**
Using SAAS (https://design.penpot.app)

**Comment by hollisticated-horse** [comment]
Seems that locking an item inside a component in an artboard also makes everything except the artboard title invisible.

**Comment by EvaMarco** [comment]
Hello @hollisticated-horse:
Thanks for reporting this issue. I've created a ticket in Taiga, I hope we can fix it soon.
Here is a link to it https://tree.taiga.io/project/penpot/issue/2766.

**Comment by niwinz** [comment]
Should be fixed and deployed. Thanks for reporting.
