### ISSUE TITLE
texte input duplication

### ISSUE THREAD

**Issue by hollisticated-horse** [uxbox/uxbox#1551]
**Describe the bug**
If an text block in a component has text already and you replace it, it keeps the previous text on top of the current input while editing and clears up only after applying the modifications.

**To Reproduce**
1.  Make a text box in a component
2.  Input text a first time
3.  Edit the text and try to write something else.
4.  See both the original text and the new modification at the same time while editing. Gets updated properly after

**Expected behavior**
When editing a text box, the previous text should not stay on screen while I'm writing the new text.

**Screenshots**
![image](https://user-images.githubusercontent.com/76632257/152683978-dd587e47-589c-42b5-a6ab-4d139477dc58.png)

**Desktop (please complete the following information):**

-   OS: Archlinux
-   Browse: Firefox 
-   Version Beta version 1.11

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by EvaMarco** [comment]
Hello @hollisticated-horse :
I'm trying to reproduce this bug but  I was not able to, as you can see in this small gif.

![component-text](https://user-images.githubusercontent.com/48989967/152827086-542b3c11-c622-4f69-b128-4e17e8e2be27.gif)

Could you please give me a bit more information so we can reach the bottom of this?
Thanks¡

**Comment by niwinz** [comment]
Also, unable to reproduce.

**Comment by hollisticated-horse** [comment]
So far also unable to reproduce, but I'll keep my eyes open.
