### ISSUE TITLE
typographies keeps resetting

### ISSUE THREAD

**Issue by mjourdan** [uxbox/uxbox#1556]
**Describe the bug**
Typographies are reset to Source Sans Pro / 14 / Regular / 1.2

**To Reproduce**
- Save a typography, like Lato / 16 / 900 / 1.4
- Close the typography, click around
- Open again the typography for edition, notice its name remains but all its values have been reset

**Expected behavior**
Typography keeps the value I set

**Screenshots**
I expected to find my settings there:
![screenshot of the typographies panel](https://user-images.githubusercontent.com/5346620/152873860-60fefa79-a1ed-4cda-845e-960951dd7500.png)

**Desktop (please complete the following information):**

-   OS: Fedora 35
-   Browser: Firefox 96.0

**Environment (please complete the following information):**
Using SAAS

**Additional context**
I couldn't identify exactly how to reproduce, but did reproduce it many times. For some reasons, some of my typographies got reset while some stayed intact.

**Comment by EvaMarco** [comment]
Hello @mjourdan:

My coworkers and I have tried to reproduce this issue but we couldn't. We are going to keep an eye on this. If you identify a way to reproduce it just let us know, please, and we will open a ticket in our system. 

Thanks¡

**Comment by EvaMarco** [comment]
Hello again @mjourdan:

I spent some time figuring this out and at last, I was able to reproduce it. 
I've created a ticket in our taiga project, you can check it [here](https://tree.taiga.io/project/penpot/issue/2791).

Thanks for the clue.

**Comment by mjourdan** [comment]
Yesterday I launched screen recording and desperately tried to reproduce the bug, without success. I figured it's because I didn't use the + button, so I was about to give it another try tonight… The I saw it was already solved. Wow!

Thanks for the thorough investigations and quick fix @EvaMarco!
