### ISSUE TITLE
RTL support not working as it should

### ISSUE THREAD

**Issue by jifnawi** [uxbox/uxbox#1559]
**Describe the bug**
If I type in Arabic text, the text displays mirrored.

**To Reproduce**
1.  Create a text box
2.  Type in "اللغة العربية"
3.  Select RTL in the text alignment options
4.  See error

**Expected behavior**
The text should appear as "اللغة العربية", instead it appears as in screenshot.

**Screenshot**
![Screenshot 2022-02-08 at 13 48 51](https://user-images.githubusercontent.com/25263499/152981322-1707042f-774f-4a35-a409-41f62b9066ef.png)

**Desktop**
-   Browser: Firefox

**Comment by niwinz** [comment]
Hello @rayasharbain 

I'm unable to reproduce, tried both in forefox and chromium and works as expected. Which version of firefox you are using? 

I have tested it on FF v91.4.1 and Chromium v96

**Comment by jifnawi** [comment]
I'm using FF v96.0.3

**Comment by EvaMarco** [comment]
Hello @rayasharbain 
I have tried this in FF v96.0 and this is what I see.
![Captura de pantalla de 2022-02-08 13-19-57](https://user-images.githubusercontent.com/48989967/152987327-b01ea8fd-d3f8-4772-8a1e-44e2cf924e20.png)
Can you please me us a small video showing this issue?
Thanks in advance.

**Comment by jifnawi** [comment]
Okay I tried to replicate the issue now and it's working very well! Not sure what happened previously! Apologies for inconveniencing everyone 😅

**Comment by EvaMarco** [comment]
No problem @rayasharbain, we are here to help¡¡
