### ISSUE TITLE
Google OAuth not working with nginx proxy

### ISSUE THREAD

**Issue by wesguirra** [uxbox/uxbox#1563]
**Describe the bug**
The Google OAuth is not working when use this with nginx proxy

**To Reproduce**
1.  Spin up docker environment and configure google oauth
2.  Configure nginx site and proxy it to penpot app
4.  Try to login using google

**Expected behavior**
Login with google when have nginx proxy configured

**Environment (please complete the following information):**
Self hosted

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Ubuntu 20.04

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: (e.g. Docker version 18.03.0-ce, build 0520e24)
-   Image (e.g. alpine)

No stack-traces

**Additional context**
I will update here soon with nginx config.

**Comment by niwinz** [comment]
I don't think this is a bug, at least looks like some configuration issue (maybe I'm wrong). Our SAAS is behind 2 nginx... and has google auth enabled and works as expected. We can help you to configure it but we probably need more context. I think nginx config, the config.env relevant values.

**Comment by niwinz** [comment]
Close for inactivity
