### ISSUE TITLE
Penpot/Docker: hide gui elements, when disabling registration and/or demo account

### ISSUE THREAD

**Issue by JackHewson** [uxbox/uxbox#1575]
**Is your feature request related to a problem? Please describe.**
In config.env it is possible to disable user registration and/or demo access.
(see https://raw.githubusercontent.com/penpot/penpot/main/docker/images/config.env )

**Describe the solution you'd like**
When registration and/or demo-users is disabled like this, these elements should not be shown in GUI.
`PENPOT_FLAGS="disable-registration disable-demo-users"`

**Additional context**
These elements should be hidden, when settings the flags above.

![grafik](https://user-images.githubusercontent.com/36240327/153431559-52de8743-fd0e-460d-ae7d-0c312b1fed3e.png)

**Comment by EvaMarco** [comment]
Hello @JackHewson 
I'm going to open an enhancement ticket in our Taiga project about this issue. You can follow it [here](https://tree.taiga.io/project/penpot/issue/2861).

Thanks for your help.

**Comment by githubber** [comment]
I've been looking for some place to add basically the same comment. I've installed Penpot using Caprover, but I would like to turn off Registration. What are the env to do so? (Caprover has already told me to come here to ask...) Thank you!

**Comment by niwinz** [comment]
This will be solved in the next release.
