### ISSUE TITLE
Penpot/Docker: Login only possible, when deactivating cache in Development Tools

### ISSUE THREAD

**Issue by JackHewson** [uxbox/uxbox#1576]
**Describe the bug**
The login is only successful, when disabling the cache in (Firefox) Development Tools.

**To Reproduce**
1.  Go to Penpot login page
2.  Fill in the credentials
3.  Click on "Login"
4.  Error message appears: "Looks like you are not authenticated or session expired." 
5. Open Firefox Development Tools
6. Click on checkbox "Disable cache"
7. Reload Penpot login page
8. Fill in the credentials
9.  Click on "Login"
10. Login is successful

**Expected behavior**
Login should be possible without deactivating browsers cache.

**Desktop (please complete the following information):**

-   OS: Windows 10 
-   Browser: Firefox
-   Version: 97

**Environment (please complete the following information):**
1. Run penpot in a docker container as described at https://help.penpot.app/technical-guide/getting-started/#install-docker
2. `ProxyPass ` the penpot-frontend to https url (with a valid SSL cert)
3. Create user with `docker exec -ti penpot_penpot-backend_1 ./manage.sh create-profile`

FLAGS set on `config.env`:
`PENPOT_FLAGS="disable-registration disable-demo-users"`

**Comment by JackHewson** [comment]
I had an issue in my apache2 caching settings. Adapting them, Penpot works like a charm!

**Comment by niwinz** [comment]
Nice to know, and glat the issue has been solved.
