### ISSUE TITLE
Layer drag-and-drop doesn't work any-more

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#1578]
**Describe the bug**
Previously I could drag-and-drop layers to change their order. This doesn't work any-more.

**To Reproduce**
1.  Have three layers
2.  Click on a layer (see cursor change in drag-hand)
3.  Move cursor down to other layer
4.  See error

**Expected behavior**
See lines of where layer would end up - when letting go of the mouse click, drop the layer.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser: Versie 97.0.4692.71 (Officiële build) Built on Ubuntu , running on Ubuntu 18.04 (64-bits)
-   Version (e.g. 22)

**Environment (please complete the following information):**
Specify if using **SAAS (https://design.penpot.app)** or ~self-hosted instance~.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: (e.g. Ubuntu 16.04)

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: (e.g. Docker version 18.03.0-ce, build 0520e24)
-   Image (e.g. alpine)

**Frontend Stack Trace (if self-hosted)**

<details>

```

```

</details>

**Backend Stack Trace (if self-hosted)**

<details>

```

```

</details>

**Additional context**

It concerns the following file: https://design.penpot.app/#/workspace/9e19fed0-782c-11eb-8a88-eb0147e048f5/d1c45d80-3b12-11ec-a516-23056af0be2f?page-id=d1c45d81-3b12-11ec-a516-23056af0be2f&layout=layers

**Comment by keunes** [comment]
I just tested this in Chrome, there the issue doesn't seem to be present there.

**Comment by niwinz** [comment]
Unable to reproduce :(
Is this happens with a concrete shape/group? or is not deterministic?
Do you remember more details, like which steps you have done to cause the error... if you are using some shortcuts, etc.. all detail can help.

**Comment by keunes** [comment]
Hi @niwinz
Thanks for the quick reply. There's not much more to say, other than that it happens only in **Chrom*ium*** - Chrome and Firefox work as expected. It happens with new as well as old files, in no particular shape/group/element. Since I'm talking about mouse actions, I'm not sure how shortcuts might be involved.

Please note also that I am testing on Ubuntu 18.04 (64-bits) - haven't tested on other OSs. Do you have the same (test) set-up?

... Oh, I see now that actually I didn't specify the browser in my first post, sorry about that. So like I said: it's browser-specific.

Hope that helps.

**Comment by madalenapmelo-kp** [comment]
Hi @keunes,

Could you please confirm if you are still experiencing this issue and, if not, close the issue? Thank you in advance :)
