### ISSUE TITLE
Click-to-add and drag-and-drop component doesn't work any-more

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#1579]
**Describe the bug**
Previously, I was able to drag-and-drop or (IIRC) click to add a component to the active/viewed artboard. This doesn't seem to work any-more.

**To Reproduce**
1.  Grab a Graphic component
2.  Drag it to the artboard
3.  Let go of the click
4.  See error

**Expected behavior**
Component is placed on the artboard.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: (e.g. iOS)
-   Browser: Chromium Versie 97.0.4692.71 (Officiële build) Built on Ubuntu , running on Ubuntu 18.04 (64-bits)
-   Version (e.g. 22)

**Environment (please complete the following information):**
Specify if using **SAAS (https://design.penpot.app)** or ~self-hosted instance~.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: (e.g. Ubuntu 16.04)

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: (e.g. Docker version 18.03.0-ce, build 0520e24)
-   Image (e.g. alpine)

**Frontend Stack Trace (if self-hosted)**

<details>

```

```

</details>

**Backend Stack Trace (if self-hosted)**

<details>

```

```

</details>

**Additional context**
Issue is with this file: https://design.penpot.app/#/workspace/9e19fed0-782c-11eb-8a88-eb0147e048f5/d1c45d80-3b12-11ec-a516-23056af0be2f?page-id=d1c45d81-3b12-11ec-a516-23056af0be2f&layout=assets (same as #1578 - starting to wonder if there's something wrong with this file, which was created in earlier versions of penpot).

**Comment by keunes** [comment]
I just tested this in Chrome, there the issue doesn't seem to be present there.

**Comment by niwinz** [comment]
The same case, as previous, unable to reproduce. Any additional detail on your steps before the error will make it debug more easy. Including the shape/group names.

**Comment by cian0** [comment]
I can see that this happens on Android browsers, I am using Firefox/Brave browser/Chrome on my tablet and I can confirm that it doesn't work (both click to add components and drag and drop)

I used mouse / no mouse still doesn't work

**Comment by keunes** [comment]
Copying my reply from #1578 which is also valid here (forgot to paste it earlier):

> Hi @niwinz
> Thanks for the quick reply. There's not much more to say, other than that it happens only in Chromium - Chrome and Firefox work as expected. It happens with new as well as old files, in no particular shape/group/element. Since I'm talking about mouse actions, I'm not sure how shortcuts might be involved.
> 
> Please note also that I am testing on Ubuntu 18.04 (64-bits) - haven't tested on other OSs. Do you have the same (test) set-up?
> 
> ... Oh, I see now that actually I didn't specify the browser in my first post, sorry about that. So like I said: it's browser-specific.
> 
> Hope that helps.
