### ISSUE TITLE
Remember library display type (grid/list)

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#1582]
**Is your feature request related to a problem? Please describe.**
When switching between Layers and Assets, the display state (grid or list) of the Assets view is lost. This is annoying because when creating a set of components I switch back and forth a lot between layers and assets.

**Describe the solution you'd like**
Maintain the view when switching between panels (are layers and assets 'panels'?)

**Describe alternatives you've considered**
none :)

**Additional context**
I'm very happy with the introduction of the list view. Thanks for your continued work on Penpot <3

**Comment by pabloalba** [comment]
Hello @keunes 
I'm going to open an enhancement ticket in our Taiga project about this issue. You can follow it [here](https://tree.taiga.io/project/penpot/issue/2863).

We're glad that you like the list view :)

Thanks for your help.

**Comment by madalenapmelo-kp** [comment]
Hi @keunes,

I'm closing this issue as this was fixed by PR #3578 :slightly_smiling_face:
