### ISSUE TITLE
Group looks blurry when setting transparency

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#1584]
**Describe the bug**
When setting the 'Group layers' to a visibility that is not 100%, the group looks blurry (when editing - it is fine in the viewer).

**To Reproduce**
1. Set zoom level to 371%
1.  Select a group
2.  Set Group layers to 99% or lower
4.  See error

**Expected behavior**
Content remains as crispy as with 100% visibility.

**Screenshots**
![Schermafdruk van 2022-02-13 14-26-36](https://user-images.githubusercontent.com/11229646/153755417-be34f161-a3df-42f8-8e4d-8b2aefb3d5f4.png)
![Schermafdruk van 2022-02-13 14-26-44](https://user-images.githubusercontent.com/11229646/153755418-8eb37526-35ba-4bba-93d4-19d26a54963b.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser: Chrome 98

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by pabloalba** [comment]
Hello @keunes 
I'm going to open a bug ticket in our Taiga project about this issue. You can follow it [here](https://tree.taiga.io/project/penpot/issue/2864).

Thanks for your help.
