### ISSUE TITLE
Save button in update dialog not visible for bottom colours

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#1585]
**Describe the bug**
After adjusting a colour asset in the colour dialog, the changes I made weren't saved to the asset. I was just clicking outside the box, as I didn't see any save/close button so assumed changes would be saved automatically. But I just discovered that there is a save button, which is just not visible.

**To Reproduce**
1.  Go to a colour on the bottom of the asset list
2.  Click on edit
4.  See error

**Expected behavior**

**Screenshots**
![Schermafdruk van 2022-02-13 16-14-49](https://user-images.githubusercontent.com/11229646/153759978-b9db0db3-2626-4fff-916f-aab7bb216362.png)

**Desktop (please complete the following information):**

-   OS: (e.g. iOS) Ubuntu
-   Browser (e.g. chrome, safari) Chrome
-   Version (e.g. 22)

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by pabloalba** [comment]
Hello @keunes
I'm going to open a bug ticket in our Taiga project about this issue. You can follow it [here](https://tree.taiga.io/project/penpot/issue/2865).

Thanks for your help.

**Comment by keunes** [comment]
Seems closed in Taiga
