### ISSUE TITLE
Error in size input box

### ISSUE THREAD

**Issue by soultipsy** [uxbox/uxbox#1586]
**Describe the bug**
Normally, penpot will restrict the minimum length or width of the shape to 1px or more(Maybe it should be bound above zero and support decimals? For example, if I want to represent 1px width on ios 2X, I need a value of 0.5px on Penpot), but if I drag the value out of the input box, the value in the input box may be 0. When I recheck the shape size, the size and position will be NaN, and it will disappear on the canvas. But in the list that it's still there.

**To Reproduce**
1. New arbitrary shape, (size less than 100 * 100px easier to trigger) 
2. Select all the width values in the size input box on the right  
3. Use the mouse to drag the value into the length input box  
4. Width input box in the value becomes 0, (if it is 1, repeat Step 2-3)  
5. Click on the canvas, the graphics are not visible and can not be selected  
6. Select the graph in the left list, re-check the right list size data and position data, both become NaN values  

**Expected behavior**

NaN values should not appear (if possible, make the dimensions support decimals above 0 instead of integers as they are now)

**Screenshots**

https://user-images.githubusercontent.com/40300919/153791774-71dabf9c-181a-47c7-a009-22025c3b11dd.mp4

**Desktop (please complete the following information):**

-   OS:Windows10
-   Browser:Microsoft Edge
-   Version:98.0.1108.50

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by pabloalba** [comment]
Hello @soultipsy 
I'm going to open a bug ticket in our Taiga project about this issue. You can follow it [here](https://tree.taiga.io/project/penpot/issue/2866).

Thanks for your help.
