### ISSUE TITLE
Rounded corner implementation improvements

### ISSUE THREAD

**Issue by soultipsy** [uxbox/uxbox#1587]
**Is your feature request related to a problem? Please describe.**
Rounded rectangles should be constrained to the correct shape, and currently when the rectangle rounded value exceeds the short side value, the shape is displayed as an oval corner until the rectangle eventually becomes a full oval. This is inconsistent with the actual CSS code presentation style, where rounded corners are supposed to be positively rounded at all times and constrained by the length of the short side (perhaps the oval corners are a special design? But this is not the case in most design software, and it is also rare to see this element in actual interface design), and secondly, when I transpose the shape of the elliptical corners, his shape is wrong, and this phenomenon exists in Boolean operations (sorry, I can't describe it clearly, please see the video), I think this way of rounding corners should be improved. 

**Describe the solution you'd like**
The rounded display should always be positive rounded and confined to 1/2 of the length of the short edge, but should also accept a larger rounded value. For example, if you add a 100px rounded corner to a 10 × 20 rectangle, the rounded corner will appear as 10/2=5px. If you adjust the rectangle to 100 × 200, the rounded corner will appear as 100/2=50px because it is still less than the input value of 100px (see CSS). When converting a shape to a curve,  should use the actual size of the rounded corners displayed instead of entering a value to ensure a consistent display.

**Describe alternatives you've considered**
If oval rounded corners are an implementation or style, maybe add a full rounded/oval corner toggle switch?

**Additional context**
![image_2017](https://user-images.githubusercontent.com/40300919/153803661-d38705a6-999f-4a6f-9ee2-bb04a12e8ce0.png)
![image_2018](https://user-images.githubusercontent.com/40300919/153803664-fec3449e-02eb-43ad-bb76-b6bee386c869.png)
The CSS display is not the same as penpot.

https://user-images.githubusercontent.com/40300919/153803893-a57560cd-3700-451b-9d52-2dc63b3dcb59.mp4

https://user-images.githubusercontent.com/40300919/153803900-e4d282ed-e03e-429b-abd7-f15b710b4319.mp4

The video shows the ellipse Angle being broken when converted to curve/in booleans

**Comment by pabloalba** [comment]
Hello @soultipsy
I'm going to open a bug ticket in our Taiga project about this issue. You can follow it [here](https://tree.taiga.io/project/penpot/issue/2868).

Thanks for your help.
