### ISSUE TITLE
Incorrect position drift

### ISSUE THREAD

**Issue by soultipsy** [uxbox/uxbox#1588]
**Describe the bug**
After the graph has been rotated, the position will be slightly offset when resized through the input box on the right, even if the rotation is adjusted back to 0, this problem persists(Then the program is likely to crash, it is not clear whether there is any connection with this BUG).However, shapes that are not rotated/or resized by dragging and dropping directly in the view will not be offset.

**To Reproduce**
1. Create an arbitrary graph
2. Rotate it
3. Use the scroll wheel in the input box to adjust the size
4. The graph moves a tiny distance to the right
5. Try to restore the rotation amount of the graph to 0, the problem still exists

**Expected behavior**
When I adjust the size, the position does not shift.

**Screenshots**

https://user-images.githubusercontent.com/40300919/153809822-bfa256ca-6493-47b6-a03d-4c52e8f42f17.mp4

**Desktop (please complete the following information):**

-   OS: Windows10
-   Browser:Microsoft Edge
-   Version 98.0.1108.50

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by soultipsy** [comment]
> 
It should be added that the problem of position data offset caused by resizing after rotation only applies to rotation angles between 0 and 90 degrees. Because the shape and size is based on its own coordinates as the origin of the upper left corner change; The position information is dynamically calculated based on the coordinate of the drawing board. Therefore, when the rotation Angle is greater than 90 degrees, the change of the size of the graph itself will cause the change of the position measurement, but the position will still be offset when the shape is restored to 0 degree rotation after rotation。

**Comment by pabloalba** [comment]
Hello @soultipsy 
I'm going to open a bug ticket in our Taiga project about this issue. You can follow it [here](https://tree.taiga.io/project/penpot/issue/2867).

Thanks for your help.
