### ISSUE TITLE
Keep the same color theme for /workspace/ and /dashboard/

### ISSUE THREAD

**Issue by cristianson** [uxbox/uxbox#1590]
Switching between the `/workspace/` and `/dashboard/` pages can be a pain for the eyes (especially when using Penpot on a big screen). The reason is that the dashboard UI is mainly light-themed, whereas the workspace is dark (besides the canvas). Check images below 👇

Is it possible to have them both more consistent? Instead of creating a dedicated dark/light mode feature and designs, I guess we could simply change the color of some UI elements on the workspace page and make it lighter. Specifically the `Pages` nav on the left and the whole right nav

<img width="1440" alt="Screenshot 2022-02-14 at 20 33 56" src="https://user-images.githubusercontent.com/33906006/153925081-c95020ca-4dcd-4b30-8fed-a63eb10c760b.png">
<img width="1440" alt="Screenshot 2022-02-14 at 20 34 25" src="https://user-images.githubusercontent.com/33906006/153925153-b229f098-dd44-44a6-8d79-9ab5f3969ee9.png">

**Comment by pabloalba** [comment]
Hi @cristianson !

It's true that workspace and dashboard are very different, and we need to make them more consistent. We already have plenty of improvements planned for dark/light mode, and I hope it will be available soon. In the meantime, we will take your suggestions into consideration. 
Thanks!

**Comment by cristianson** [comment]
thanks for the reply @pabloalba!

Shall I leave this issue open then?

**Comment by superalex** [comment]
Yes @cristianson 

We have attached [your explanations at the [user story](https://tree.taiga.io/project/penpot/us/2287) where we will track this enhancement

Thanks!
