### ISSUE TITLE
Docker containers won't start and says "is up-to-date"

### ISSUE THREAD

**Issue by VladimirLevadnij** [uxbox/uxbox#1597]
Hello. I tried to start Penpot according to the instructions in "Getting Started" https://help.penpot.app/technical-guide/getting-started/

After executing the command `docker-compose -p penpot -f docker-compose.yaml up -d`

Gives me:

```
penpot_penpot-postgres_1 is up-to-date
penpot_penpot-redis_1 is up-to-date
penpot_penpot-exporter_1 is up-to-date
penpot_penpot-backend_1 is up-to-date
penpot_penpot-frontend_1 is up-to-date
```

Tell me, please, what can be done to start the containers and see the system at http://localhost:9001?

**Comment by niwinz** [comment]
Hello @VladimirLevadnij 

You will need to provide a little bit of context for me be able to help you. With the provided information, I don't know the host platform, no logs, no container state. Please provide more context information.

**Comment by VladimirLevadnij** [comment]
Thanks, I figured it out, everything started, but my browser had strong security settings and it blocked the new URL on localhost :-)
