### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by yarons** [uxbox/uxbox#1608]
https://github.com/penpot/penpot/blob/809d7ab7f4ea72cd457c201203712c71839295ae/frontend/translations/en.po#L2222

Not sure if it should be fit or fill.

**Comment by superalex** [comment]
Thank you very much for reporting @yarons 

I've just fixed this with [this commit](https://github.com/penpot/penpot/commit/88706534c26483eb74f1dbed0408bb49b8f4e8bb)
