### ISSUE TITLE
Generate Webpages using Elm

### ISSUE THREAD

**Issue by ModestMC** [uxbox/uxbox#1614]
As far as I can tell, this tool only generates out SVGs, though it allows for some really neat ways to mock up applications. WYSIWYG editors are super convenient when dealing with any kind of visual content.

I was reading through the docs and I saw that much of the configurable details related to how objects are created are the exact same inputs used in the Elm language to create webpages. While porting over more complicated stuff like animations is probably a way bigger can of worms, it might be very doable to map over the parameters used by penpot into a compilable Elm model.

As I understood Penpot, in its present form it cannot actually generate code. Depending how people use the platform, this might be a very interested feature to roll out an alpha of and see if there's interest among designers.

Hope this helps, love what you're doing, cheers!

**Comment by superalex** [comment]
Hi!,

I've opened [an ehnacement at Taiga](https://tree.taiga.io/project/penpot/issue/2928) to track it but it's still not prioritized. I hope we can start  working on it soon.

Thank you very much!

**Comment by JPustkuchen** [comment]
Slightly related: https://github.com/penpot/penpot/issues/2540
