### ISSUE TITLE
View mode (G V) button opens a blank window in Firefox

### ISSUE THREAD

**Issue by ghost** [uxbox/uxbox#1621]
**To Reproduce**

1.  Open the "Penpot Onboarding / Penpot UI Walkthrough" project
2.  Click on the 'play' icon near the top-right-hand corner of the page

![image](https://user-images.githubusercontent.com/81389922/154989820-81c87357-1aab-4100-89d8-f5d45c909977.png)

**Expected behavior**

The project should switch into view mode.

**Actual behavior**

A new tab containing blank content is opened.
 
**Screenshots**

(included inline above)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Debian Linux (bullseye)
- Browser & version (e.g. Chrome 89.0): Firefox 91.5.0esr (64-bit)

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): https://design.penpot.app

**Comment by ursacascadia** [comment]
Unable to reproduce on Firefox w/ Ubuntu Linux on empty project. Maybe an element in the example project causes it?

**Comment by superalex** [comment]
@jayaddison-collabora could you please [attach a .penpot](https://help.penpot.app/user-guide/import-export/) file where this problem is happening?

**Comment by ghost** [comment]
Thanks for taking a look @sirsnowy7 - and @superalex, yep - please find attached the .penpot file from the project.  I wasn't completely certain what export options to use and selected "Include shared library assets in file libraries".

![image](https://user-images.githubusercontent.com/81389922/155293492-488bfdca-56c0-47f3-9c8e-fb2230685fd1.png)

[Penpot - UI Walkthrough.tar.gz](https://github.com/penpot/penpot/files/8123200/Penpot.-.UI.Walkthrough.tar.gz)

**Comment by ursacascadia** [comment]
Still unable to reproduce from Firefox 97, Ubuntu Linux with example project

**Comment by superalex** [comment]
Hi again!,

We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/2954) to track this issue from here. Hopefully, it will be fixed soon. 

Thanks!.

**Comment by ghost** [comment]
An additional observation:

By adding a breakpoint on `mouse.click` events in Firefox, it's possible to pause the page scripts and step through the lines of code that are running.

![image](https://user-images.githubusercontent.com/81389922/155700947-67c40d05-321b-4ef7-8ae5-c7432c2cf00c.png)

After doing this and using the 'step' (F10) feature multiple times to gradually run the click-handler code, the page _does_ correctly load the preview view -- but it attempts to load it twice.  The URL that it attempts to open both times is:

https://design.penpot.app/#/view/48b92160-21cc-11ec-985f-f08c5eccf3df?page-id=eb3086b0-5f15-11eb-9ddd-c7d1d1ca3057&section=interactions

(the walkthrough only seems to contain a single slide / page, but that's a separate issue)

**Comment by ghost** [comment]
Closing this GitHub issue since the same item is tracked in Taiga.
