### ISSUE TITLE
Pressing Alt to see distance to other elements doesn't work anymore

### ISSUE THREAD

**Issue by LopsemPyier** [uxbox/uxbox#1644]
**To Reproduce**

1.  Go to a document
2.  Click on an element and press alt while hovering an other element

**Expected behavior**

Before, it was showing the distance between the elements. It was consistent with other design tools which was nice.

**Actual behavior**

Now, the mouse cursor is showing the cursor for duplicating element and is not showing distance.
 
**Screenshots**

To hard to take one.

**Desktop (please complete the following information):**
- OS : Arch Linux with Wayland
- Browser : Firefox Developer Edition 98.0b6

**Environment (please complete the following information):**
- Host : https://design.penpot.app

**Additional context:**

It work fine for a long time, I don't know if you intentionally change it but I prefer the way it was before and I did not see any way to get it back.

**Comment by LopsemPyier** [comment]
Sorry, I did not check on other browsers : 
 - Chromium 98 and Firefox 97 work fine
 - Firefox Nightly 99 doesn't work

I don't know if it's a *Beta/Nightly* thing or if it just doesn't work on Firefox 98 but I will stick to Firefox 97 for now.

Thanks for this wonderful tool, hope you can fix it quick

**Comment by claragvinola** [comment]
Hi! with the release of last week this problem should be fixed :)

**Comment by LopsemPyier** [comment]
Yes, I checked, thanks you
