### ISSUE TITLE
Chinese Translate

### ISSUE THREAD

**Issue by bingling-sama** [uxbox/uxbox#1657]
Hello, I want to become a translator for Chinese language.

I'm a Chinese native speaker.
And I found that there were a lot of mistakes and untranslated words in Penpot.
So I want to make contributes to Penpot.

My weblate username is bingling_sama

Thanks

**Comment by Alotor** [comment]
Hello @bingling-sama ,

We'll be very grateful to have you contributing to the translations.

I've tried to add your user but seems like it doesn't exist. Can you write us to `support@penpot.app` sending your username again? maybe Github is doing something to the text.

**Comment by bingling-sama** [comment]
Sorrrry, I just found that my weblate username is `bingling-sama`.
I mistake my nickname and my username, the difference between `-` & `_` is difficult to recognise with my shortsighted eyes.
~~It's my fault, not GitHub XD~~
Sorry again for my mistake.

**Comment by niwinz** [comment]
Sorry for the late response, I have added your user succesfully, thanks for the patience.
