### ISSUE TITLE
Missing documentation for demo user flags

### ISSUE THREAD

**Issue by dragetd** [uxbox/uxbox#1659]
The documentation claims, that there is only a 'enable-demo-users' flag. But according to my tests and #1266, demo-users are enabled by default and actually require the 'disable-demo-user' flag.

Wouldn't it be more sane to default to not allowing demo-users? This would be a more secure default. The documentation should be updated and reflect this.
It should also mention that there is an enable/disable counterpart of the variables.

**Comment by Alotor** [comment]
Hello @dragetd ,

Thanks for your feedback. We're talking internally to see what's the best default... on one hand we want to ease the trial of the platform for new users but you're right that activating demo users could be a potential security concern.

In the meantime I've created a bug to update the documentation with the user flags. 

https://tree.taiga.io/project/penpot/issue/2978

**Comment by johncadengo** [comment]
I used `disable-demo-users` and when I go to the homepage, it still has a link for "Create Demo Account"

When I press "Create Demo Account" it gives me "Unexpected Validation Error"

Is there a way to remove the link to even create a demo account?

![Screen Shot 2022-03-09 at 1 38 59 PM](https://user-images.githubusercontent.com/561587/157540640-2e8efa2c-827b-469e-a646-8d5d0019422a.png)
?

**Comment by dragetd** [comment]
For those who might have missed it: Demo users are disabled by default: https://github.com/penpot/penpot-docs/commit/832e5e17e23ec8d739c44cb61363643e218095c1

Thank you, I think this is a good default. :)
