### ISSUE TITLE
Delete artboards from the 'prototype' tab

### ISSUE THREAD

**Issue by lane-hogan** [uxbox/uxbox#1664]
**To Reproduce**

1.  Click on any component or artboard
2.  Click on the 'Prototype' tab
3.  Press 'A' and create a new artboard
4. Select the new artboard and press 'delete' key (or right-click and click 'delete')
5. Click back to 'Design' tab and repeat step 4

**Expected behavior**

The artboard should be deleted from the canvas even if I am in the 'prototype' tab.

**Actual behavior**

The artboard is not deleted until I navigate back to the 'Design' tab.

**Desktop:**
- Windows 11
- Microsoft Edge 98.0

**Environment (please complete the following information):**
- https://design.penpot.app

**Comment by Alotor** [comment]
@lanehogan1 thanks for the report. 

We're reviewing it internally because it's something we did on purpose but we're thinking about revisiting our decision.

**Comment by niwinz** [comment]
This is finally tracked on taiga: https://tree.taiga.io/project/penpot/issue/3059
And it is already closed, so the fix will land on the next release.
