### ISSUE TITLE
Can't select multiple items with Ctrl + Shift

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#1671]
**To Reproduce**

1.  Create 2 groups of elements (like a text inside a rectangle)
2.  Select the text of the first group
3.  Try to select the text of the second group with Ctrl + Shift

**Expected behavior**

The second text should be selected in the same selection.

**Actual behavior**

I can't click on the second text. Nothing happens.
 
**Screenshots**

Select first text
![image](https://user-images.githubusercontent.com/62602652/157491295-02f20a85-367a-445a-87ce-bb4092857053.png)
Try to select second text
![image](https://user-images.githubusercontent.com/62602652/157491403-3c765cdb-72c7-44e0-b84d-3d1d5cca9b00.png)

Organisation:
![image](https://user-images.githubusercontent.com/62602652/157491708-d5c35c54-a4c6-4d2b-9f5d-aa3c67e27fc6.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Win 10
- Browser & version (e.g. Chrome 89.0): Chrome 99

**Additional context:**

It was working like 2 weeks ago, you made a release in the meantime.

I can select multiple elements in the left panel tho.

**Comment by Alotor** [comment]
@NicolasLeboeuf thanks for the report. You're right it's a bug with the latest release. We'll try to solve it soon.

I've created an issue in our internal bug tracking system https://tree.taiga.io/project/penpot/issue/3017

**Comment by niwinz** [comment]
Should be fixed

**Comment by NicolasLeboeuf** [comment]
It is :)
