### ISSUE TITLE
More translations for Russian

### ISSUE THREAD

**Issue by vintprox** [uxbox/uxbox#1678]
Hello, world! I'd like to contribute several translation strings for `ru` locale.

At the moment, crucial sidebar strings are untouched, and from what I've noticed there are only partial translations for menus. So much work 😉

https://hosted.weblate.org/user/vintprox/

**Comment by vintprox** [comment]
I will close the issue once I'm ready to delegate.

**Comment by Alotor** [comment]
Thanks a lot!! I've added you to our weblate project. Let me know if you have any issues.

**Comment by vintprox** [comment]
50% ready.
