### ISSUE TITLE
Guide deletion by dragging on the ruler

### ISSUE THREAD

**Issue by vintprox** [uxbox/uxbox#1679]
## Problem

While you can delete a guide by dragging it away outside editing view, it remains on the ruler. It was kind of unexpected, because in many WYSIWYG editors the behavior is different.

## Expectation

Expecting guides to be deleted just by dragging on the ruler (**and** outside, as it is now).

**Comment by Alotor** [comment]
Hi, thanks for the report.

This is really a bug, It should be working as you expect.

I've open a ticket in our internal tracking tool https://tree.taiga.io/project/penpot/issue/3035
