### ISSUE TITLE
Faster access to renaming objects

### ISSUE THREAD

**Issue by vintprox** [uxbox/uxbox#1680]
## Problem

It's easy to miss this area for double-clicking:  
![image](https://user-images.githubusercontent.com/5708819/157737917-974e6a3f-875f-4cc9-93a3-57a029fcb855.png)

Also, the absence of keyboard shortcut for "Rename" is creating a massive dependency on the mouse input for seemingly simple quality-of-life operation.

## Expectation

Expected to have intuitively faster access to renaming objects:
- by double-clicking anywhere near by the name: preferably in range from the icon to the hover controls on the right;
- by selecting object and just pressing <kbd>F2</kbd>.

**Comment by Alotor** [comment]
Thanks for the feedback. I think you're right. We'll try to change it for the next release.

**Comment by vintprox** [comment]
> Thanks for the feedback. I think you're right. We'll try to change it for the next release.

Yeah, it's one simplistic fix (at least, for the first expectation). I'll drop a little piece of code, just in case:

```
.element-name {
  /* Span horizontally */
  flex-grow: 1;

  /* Stretch vertically */
  align-self: stretch;
  
  /* Center name vertically after stretching */
  display: flex;
  align-items: center;
}
```
