### ISSUE TITLE
Artboard Corner Radius

### ISSUE THREAD

**Issue by lane-hogan** [uxbox/uxbox#1683]
When designing screens for a mobile app I like to have round corners for my artboards. This is not possible unless I add a rectangle to fit the size of the artboard, change the background color of the artboard to match the canvas color, and add corner radius to the rectangle.

I think it would be much easier if there was a corner radius option like there is when you add a rectangle.

**Comment by Alotor** [comment]
I'm glad to inform you that this feature is already developed and will be available on the next release (1.13) :smile: 

We don't have a ETA yet but should be by the end of this month/beginning of the next.
