### ISSUE TITLE
Exporting to PDF does not manage image resized

### ISSUE THREAD

**Issue by vinyll** [uxbox/uxbox#1685]
**To Reproduce**

1.  Create a document in insert an image
2.  Size it down
3.  Export to PDF

That at least occured on Firefox 99

**Expected behavior**

The PDF should show the image as on the artboard.

**Actual behavior**

The size is larger than resized and cropped to the requested image size
 
**Screenshots**

Artboards from within the penpot app
<img width="780" alt="Screen Shot 2022-03-14 at 09 17 42" src="https://user-images.githubusercontent.com/145172/158132094-237c29d2-e6bc-43b5-88e3-167fc77dd829.png">

Exported PDF has stretched images instead
<img width="275" alt="Screen Shot 2022-03-14 at 09 18 01" src="https://user-images.githubusercontent.com/145172/158132258-e88b5a33-5bf3-4efd-91ce-20734ac707db.png">

**Comment by EsterLatorre** [comment]
Hi,
We've opened it as a bug in Taiga: https://tree.taiga.io/project/penpot/issue/3050. Hopefully, it will be fixed soon. 
Thanks for the report!

**Comment by niwinz** [comment]
The fix on this is already landed, and will be available on the next release.
