### ISSUE TITLE
Import SVG files

### ISSUE THREAD

**Issue by AskAkshith** [uxbox/uxbox#1688]
**To Reproduce**

1.  Go to penpot.app
2.  Click on import Penpot files.
3.  Select SVG file to import

**Expected behavior**

SVG file should be imported from local computer and should be available to use like other Penpot files.

**Actual behavior**

Importing SVG files didn't work. 
 
**Screenshots**

![Penpot Design Freedom for Teams](https://user-images.githubusercontent.com/41001858/158162834-2d91e965-691a-4515-9e5b-72ad5faa16c1.png)

**Desktop (please complete the following information):**
- Debian 11
-  Firefox 91.6.1esr

**Additional context:**

Any other context about the problem.
While we drag and drop SVG into art board, text in the file is not being uploaded. Also tried to copy/paste the design, but it is uploading as raster image which can't be edited, as also tried by copy/paste elements in design one by one, but all logos/images which are in SVG format are getting uploaded as raster images and text is not uploading.
Related issues for above problem 

- https://github.com/penpot/penpot/issues/1532 
- https://github.com/penpot/penpot/issues/546
- https://github.com/penpot/penpot/issues/826

**Comment by niwinz** [comment]
Hmm, I think you are using a wrong tool. A SVG file just a graphic media, penpot files, are a group or collection of them because penpot it not a just svg editor, is a design tool. If you want to import svg, just go to the workspace, choice the image tool or drag and drop the image into the workspace.

**Comment by niwinz** [comment]
> While we drag and drop SVG into art board, text in the file is not being uploaded. Also tried to copy/paste the design, but it is uploading as raster image which can't be edited, as also tried by copy/paste elements in design one by one, but all logos/images which are in SVG format are getting uploaded as raster images and text is not uploading.

The text in the svg, is a known bug and it will be probably fixed in the next release.

**Comment by AskAkshith** [comment]
> Hmm, I think you are using a wrong tool. A SVG file just a graphic media, penpot files, are a group or collection of them because penpot it not a just svg editor, is a design tool. If you want to import svg, just go to the workspace, choice the image tool or drag and drop the image into the workspace.

Tried to drag and drop, but it is getting uploaded as raster image, not vector image.

**Comment by vintprox** [comment]
> Tried to drag and drop, but it is getting uploaded as raster image, not vector image.

Does it seem blur/pixelated when you stretch it? I've seen instances of Penpot using some sort of raster cache for objects that temporarily leave viewport (optimization of sorts?) - but if I just hover on anything, it's vectorized again.

**Comment by niwinz** [comment]
Close for inactivity, unable to reproduce.

**Comment by AskAkshith** [comment]
> Does it seem blur/pixelated when you stretch it? I've seen instances of Penpot using some sort of raster cache for objects that temporarily leave viewport (optimization of sorts?) - but if I just hover on anything, it's vectorized again.

Output in raster image format, not in original SVG, which means it is blur, and we can't make any changes(like changing color).

**Comment by AskAkshith** [comment]
> Hmm, I think you are using a wrong tool. A SVG file just a graphic media, penpot files, are a group or collection of them because penpot it not a just svg editor, is a design tool. If you want to import svg, just go to the workspace, choice the image tool or drag and drop the image into the workspace.

I have tried to import it using file import option, that's where I got the above error. After that I tried to drag and drop from local system to art board, but text didn't appear along with logos and all, even logos appeared as raster images.

**Comment by anentropic** [comment]
> If you want to import svg, just go to the workspace, choice the image tool or drag and drop the image into the workspace.

New to Penpot... I was looking everywhere for the import menu 🤦‍♂️
