### ISSUE TITLE
Add Persian language

### ISSUE THREAD

**Issue by ahmaduxui** [uxbox/uxbox#1689]
I want to help in Persian translation, please add Persian language in Weblate

**Comment by myfunnyandy** [comment]
Hi, we'd love you to help us with Persian translations. We've already added the language at the languages list. Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

The only thing we need to grant you permissions to edit translations is your Weblate username, the moment you tell us we will add you to the project.

Thanks!

**Comment by myfunnyandy** [comment]
Hi again @Ahmadhosseinbor , we've seen some advances at the Persian language and we are willing to publish it so other users can set their interface with it. However, the translation progress is still at 21%, so we highly encourage you to keep up with the completion. Non translated texts will show up in english, which can be a bit confusing for the users.

Thank you for such awesome contribution!
