### ISSUE TITLE
docker command different then in getting started section

### ISSUE THREAD

**Issue by drBenway** [uxbox/uxbox#1695]
**To Reproduce**

0.  Launch Penpot from the docker compose file.
1.  Go to https://help.penpot.app/technical-guide/getting-started/#configuration
2.  Copy the docker command and paste it in your terminal
3.  I got No such container
4.  looking at the containers with "docker ps" gave me a list with "penpot_penpot-backend_1"
5.  so I guess the default settings is not all underscores as in the wiki

**Expected behavior**

the terminal command being the same as what is being created by docker compose file

**Actual behavior**

command fails as it cannot find the container
 

**Desktop (please complete the following information):**
- Ubuntu latest
-

**Environment (please complete the following information):**
- localhost

*If self-hosted:*
default docker compose file:

---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_data:
  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9001:80

    volumes:
      - penpot_assets_data:/opt/data

    env_file:
      - config.env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - penpot_assets_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - penpot_postgres_data:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:6
    restart: always
    networks:
      - penpot

**Comment by niwinz** [comment]
Everything depends on how you are starting your containers. if you use the v1 o v2 of compose.
This don't have easy fix. Just look first the container name, then use it.
