### ISSUE TITLE
Team management permission

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1709]
**Is your feature request related to a problem? Please describe.**
50/50

**Describe the solution you'd like**
Now we are using Figma. I can restrict other users from creating the Projects folders or view folder's content. I can make some users editor or viewers in certain project. I really need the same in Penpot.

**Comment by myfunnyandy** [comment]
Hi, we have planned big improvements on permissions management for teams. Those include the viewer role and fine-grain permissions for access and editing. Some of them are already on definition stage, meaning that we will develop them eventually but still can not provide an estimation about when. Stay tuned, we hope that soon you will be able to enjoy this upcoming features :)

**Comment by heyakyra** [comment]
@myfunnyandy But where can that feature be tracked if not here? 

Not having the ability to prevent destructive actions makes us weary of inviting team members who might accidentally delete one thing or another
