### ISSUE TITLE
Invite external users

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1710]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
We use LDAP authorisation. But the same time we need the option to invite external users to our prototypes.

**Comment by niwinz** [comment]
Hello @catcargos 

I'm not clearly understand this. What problem you have to invite external users?

As additional context: the next release already comes with many improvements to the invitation/members section.

**Comment by catcargos** [comment]
0. Penpot is on our server.
1. We use LDAP authorisation. So we have no Sing In button on the main screen.
2. External user has not registered in PenPot yet and he don't have our LDAP account.
3. We try to invite external user to our team.

**Comment by niwinz** [comment]
ok, thanks for the context, I gues you have the registration disabled?

the next release comes with the ability to invite external users having the registration disabled and many other improvements in this area.

**Comment by catcargos** [comment]
_I guess you have the registration disabled?_
Yes.
