### ISSUE TITLE
Paste SVG with transparent shapes 

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1720]
**To Reproduce**

1.  I have vector image in Figma. The vector have transparent shape (we need it to make free space around the shapes).
2. I copy svg code and try to paste it to Penpot.
3. Transparent shape is not pasted.

**Expected behavior**
I have all visible shapes in Penpot.

**Actual behavior**
Transparent shape is not pasted.
 
**Screenshots**

In Figma:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/102146431/159723731-6304145b-54c0-4e7b-8d4f-356d420df0c4.png">

In Penpot:
<img width="145" alt="image" src="https://user-images.githubusercontent.com/102146431/159723845-858ebea3-615d-4104-bc47-5283073491bc.png">

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser & version: Edge  99.0.1150.46

**Additional context:**

SVG Code:
![svg](https://user-images.githubusercontent.com/102146431/159724776-2e748e87-842b-42b6-82e9-68ffbe97ded0.svg)

**Comment by elhombretecla** [comment]
Hi @catcargos thanks for your detailed feedback

We will manage this issue from Taiga
[https://tree.taiga.io/project/penpot/issue/3134](https://tree.taiga.io/project/penpot/issue/3134)

**Comment by catcargos** [comment]
I guess it was fixed in 1.12.3? I've tried and the bag is here again...

**Comment by superalex** [comment]
Hello @catcargos I think the problem with this image is the default background of the page (different in Penpot and Figma), could you please confirm if changing it renders the image ok?

![1](https://user-images.githubusercontent.com/1579633/162674187-ffcf0726-9673-400e-baae-910ab07190a4.png)
![2](https://user-images.githubusercontent.com/1579633/162674198-9c25b729-da45-454b-a552-25ab5c3ed135.png)

**Comment by catcargos** [comment]
> Hello @catcargos I think the problem with this image is the default background of the page (different in Penpot and Figma), could you please confirm if changing it renders the image ok?
> 
> ![1](https://user-images.githubusercontent.com/1579633/162674187-ffcf0726-9673-400e-baae-910ab07190a4.png) ![2](https://user-images.githubusercontent.com/1579633/162674198-9c25b729-da45-454b-a552-25ab5c3ed135.png)

Nope. In the first screenshot I show the difference between selected objects in Figma and (imported from Figma) in Penpot.
<img width="211" alt="{77774E0F-C1B3-4243-880F-86A227C3C1D0}" src="https://user-images.githubusercontent.com/102146431/162678446-de59a605-ef15-4ef5-86d1-2d434421d288.png">

**Comment by catcargos** [comment]
Do you have all info about the issue? it's critical for my team :)

**Comment by superalex** [comment]
Sure!, there is a MR waiting to be merged (https://github.com/penpot/penpot/pull/1898) if everything goes right it will be deployed next week ;)
