### ISSUE TITLE
Penpot/Teams Admins

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1723]
**Is your feature request related to a problem? Please describe.**
Penpot is installed on a local server. There are few teams according to our company's sctructure. But every Penpot user can create new teams as he/she wish.

**Describe the solution you'd like**
- I need an option to select/delete Penpot admins that can add new teams, delete them. etc.
- I need an option to change team permission (select users that can add new projects into team, delete them etc).

**Comment by elhombretecla** [comment]
Hi @catcargos This and other advanced settings for teams management are in our roadmap. We will approach them in a close future :)

**Comment by niwinz** [comment]
Is tracked internally as separated features. I close this issue for now.
