### ISSUE TITLE
Import PNG images

### ISSUE THREAD

**Issue by leroya-bod** [uxbox/uxbox#1724]
When I import images into penpot? I've got this issue :
![image](https://user-images.githubusercontent.com/94043818/159897152-99096fa9-55f0-4beb-9356-f4be23df0bb0.png)

My penpot is on docker. My docker-compose and .env are the same on the git.
https://github.com/kaleidos-ventures/taiga-docker/blob/main/docker-compose.penpot.yml

In the navigator, i've got this :

Failed to load resource: the server responded with a status of 404 (Not Found)
(http://localhost:9001/assets/by-file-media-id/1ed22700-ab5d-11ec-84f0-3d3f4d5761cb)

Thank you in advance for the solution.

Anthony

**Comment by niwinz** [comment]
Ensure you have the storage configured correctly:

https://github.com/penpot/penpot/blob/develop/docker/images/config.env#L19

**Comment by leroya-bod** [comment]
It works.

Thank you for your help :D
