### ISSUE TITLE
Hotkeys for zoom

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1730]
**Is your feature request related to a problem? Please describe.**
There are some hotkeys in the same software. I need it in Penpot.

**Describe the solution you'd like**
The following hotkeys are urgently needed:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/102146431/160078668-48b3b9ad-6ee5-4ec6-8b24-0f0523eb413e.png">

**Comment by elhombretecla** [comment]
They exists already. Please check that this work for you :)
![Captura de pantalla de 2022-03-28 10-36-34](https://user-images.githubusercontent.com/1045247/160359661-4cdc8ec6-b85e-4573-907d-ef3ebfb06fd6.png)
![Captura de pantalla de 2022-03-28 10-39-23](https://user-images.githubusercontent.com/1045247/160359843-02a8282a-fb28-4f34-8fdd-6719274d4dfd.png)
All Penpot shortcuts are[ available here](https://help.penpot.app/user-guide/introduction/shortcuts/)

**Comment by catcargos** [comment]
But why shift? We use Ctrl+... in Figma

**Comment by myfunnyandy** [comment]
@catcargos Penpot is browser based and Ctrl+ would collide most browsers zoom shortcuts, which we care to keep for accesibility reasons as some users tweak the browser zoom to adapt sizes (specially font's) to their needs.
