### ISSUE TITLE
Snap to grid Issue

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1732]
**To Reproduce**

1. I have the componnet snapped to grid.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/102146431/160085258-cb3f71d3-b39d-4965-a6bf-2fdc8f5f04c8.png">
2. "Snap to grid" enabled.
3. I move the component by mouse.
4. The component is not snapped to grid.
<img width="475" alt="image" src="https://user-images.githubusercontent.com/102146431/160085488-0c335b9f-5be8-4ad5-97bf-c02e56ef1b79.png">
<img width="174" alt="image" src="https://user-images.githubusercontent.com/102146431/160085518-0e35016d-7ceb-4f49-9cc5-4f592d4d6e8e.png">

**Expected behavior**
The component is snapped to grid always if "Snap to Grid" option enabled.

**Comment by elhombretecla** [comment]
Hi agan @catcargos Thank you so much for your reporting. You're right. We know about this issue. It is already fixed and in QA process right now. So it will be ready for the next release :)
