### ISSUE TITLE
Shift and Alt+Shift hotkeys

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1733]
**Is your feature request related to a problem? Please describe.**
I missed the options to move (Shift + drag mouse) and dublicate (Alt + Shift + drag mouse) an object.

**Describe the solution you'd like**
In Penpot I can move an object by moving mouse with selected object. I urgent need the option to move an object with Shift button (_move object sctricty vertically or horizontally_).
The same for dublicate object (Alt+Shift).

**Comment by elhombretecla** [comment]
You can move fixing X or Y axis using drag + shift combination.
To duplicate elements you can use alt + drag shortcut :)

**Comment by catcargos** [comment]
But why it's so different from other tools?

**Comment by myfunnyandy** [comment]
Currently you can shift + drag to move through axis and alt + drag to duplicate elements (just like in most of the design tools). I'm not sure if these shortcuts worked that way when this issue was raised, but today they do so I'm closing the issue.
