### ISSUE TITLE
Object's size near the selected object

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1734]
**Is your feature request related to a problem? Please describe.**
Show selected object's size nearby.

**Describe the solution you'd like**
<img width="191" alt="image" src="https://user-images.githubusercontent.com/102146431/160095376-d8efb6cd-93bb-410b-b48a-a26f73fe9e28.png">

**Comment by elhombretecla** [comment]
You can hold "alt" key to show up the measures and distances info
![Captura de pantalla de 2022-03-28 10-54-24](https://user-images.githubusercontent.com/1045247/160362735-253f474d-2263-447a-aba0-b379f24cf641.png)
