### ISSUE TITLE
Update component from its instance

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1736]
**To Reproduce**
1. Add the component in assets.
2. Make two instances of the component on artboard.
3. Change an opacity in one instance. Update the component from this instance.
4. The changes is not published to first instance.

**Expected behavior**
All styles changes of the component publish to all instances.

**Actual behavior**
Changes of some properties is not published to all component's instances.

**Comment by elhombretecla** [comment]
Thanks! We are currently working on a components rework. This and other behaviours will be reviewed with this update in a close future.
