### ISSUE TITLE
Quick update of a used component

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1737]
**Is your feature request related to a problem? Please describe.**
I need the ability to quickly instantiate a used component in order to make changes to the component.

**Describe the solution you'd like**
Something like used in Figma.
<img width="298" alt="image" src="https://user-images.githubusercontent.com/102146431/160098260-99e18e21-5d17-49a4-ad4f-5fb0dcb2f634.png">

**Comment by elhombretecla** [comment]
This functionality is available in Penpot

![update-component](https://user-images.githubusercontent.com/1045247/160445516-d4d08106-68bc-4af5-958a-a4529f2147eb.jpg)

**Comment by catcargos** [comment]
Its not the same. Penpot does not have "Go to main component" to make a new instance of the component to edit it. In Petpot I might do: 1) find the component in a library, 2) make a new instance. Instead of a single command.

**Comment by niwinz** [comment]
because penpot does not have the concept of main component. There are no main component on workspace, the main component only lives on the assets libraries.

This is current behavior; but we already working in several proposals and improvements in this area that will enable this in future releases.

**Comment by catcargos** [comment]
I told this thing:
If I want to make global changes in component I might 1) find that component in a library, 2) make new "clear" instance, 3) make a changes, 4) Update the component with changes.
I want to make 1 and 2 actions quickly.

**Comment by elhombretecla** [comment]
Ok! Thanks for your suggestions. We note down :) As @niwinz said we are currently reworking and improving components. It will be part of our developing sprints very soon.
