### ISSUE TITLE
Penpot version information on Sign In Screen

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1742]
**Is your feature request related to a problem? Please describe.**
Penpot is installed on a local server. I want to see version number in Penpot UI.

**Describe the solution you'd like**
Maybe it should be on Sing In Screen

**Comment by niwinz** [comment]
You have a "hightlights" version of the changes in the profile section:
![image](https://user-images.githubusercontent.com/843689/160157919-a0c6c14b-c07a-40e1-99d0-14204cfafdd5.png)

**Comment by niwinz** [comment]
If you want to know the exact version you are running you can open the devtools (with F12) and see it there:

![image](https://user-images.githubusercontent.com/843689/160158121-739748bf-bf77-46ac-871a-c70331602ebd.png)

**Comment by catcargos** [comment]
It's 

> If you want to know the exact version you are running you can open the devtools (with F12) and see it there:
> 
> ![image](https://user-images.githubusercontent.com/843689/160158121-739748bf-bf77-46ac-871a-c70331602ebd.png)

Too hard. It should be better somewhere on Sing In Screen for example...

**Comment by niwinz** [comment]
You are right, that is is not the right place, we will discuse it internally and think how can improve it, thanks for the feedback.

**Comment by niwinz** [comment]
We have no decision for this, for now this can be categorized as non priority, so I close the issue.
In any case thank you very much for suggesting it.
