### ISSUE TITLE
Landing page picture advertising SVG is a PNG

### ISSUE THREAD

**Issue by textpain** [uxbox/uxbox#1758]
Hi, just stumbled upon Penpot, and it looks very promising.

However, in "Meant for designers & loved by everyone" block on your main landing page, you have the following block:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/14220138/160610127-44b356c8-6485-4dfc-86c8-871f565d28c1.png">

Its image is implemented as follows:
```HTML
<img src="images/open-standards.png" alt="With love and Open Standards" border="0">
```

We end up in a situation where we advertise SVG support and praising the SVG standard using a PNG image instead of an SVG one. This is kind of ironic, knowing that this image is clearly vector in its nature and probably was exported from a vector format to a raster one.

**Comment by niwinz** [comment]
hehe, you are right, we could have used svg for these image, but this is not the case right now.
And we don't go to change it until next landing rework.

Additionally: this bugs seems unrelated to penpot repository (the "bug" you found is on landing page, that is not part of this repository).
