### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#1769]
**Is your feature request related to a problem? Please describe.**
The light theme elements of Penpots UI are not comfortable at night, notably:

1) project selection page
2) canvas menus

**Describe the solution you'd like**
A dark mode toggle (following system theme would be a bonus - ie. when operating system automatically changes from light to dark mode, Penpot does the same.)

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/46250921/160957289-100ca006-9b86-49d1-9cd1-6b646362e026.png)

![image](https://user-images.githubusercontent.com/46250921/160956720-2a51ad0d-d6a6-4bd4-bdeb-962ded69875c.png)

**Comment by elhombretecla** [comment]
Hi @jsmorabito thanks for your feedback.

We are aware of the importance of dark mode and other UI themes. We already have this User Story ready to prioritize and develop.
This github issue is attached to it too.

[https://tree.taiga.io/project/penpot/us/2287?backlog-exclude_status=2076390,2076392,2076391&backlog-q=theme&no-milestone=1](https://tree.taiga.io/project/penpot/us/2287?backlog-exclude_status=2076390,2076392,2076391&backlog-q=theme&no-milestone=1)

**Comment by jsmorabito** [comment]
so excited! I'd searched taiga/github for "dark theme" and "dark mode" so I see why I didn't come across this ticket. Thanks for the response. Hope all is well ✨

**Comment by florian-lefebvre** [comment]
Hi I'm also interested in this. Are there any news?

**Comment by ghost** [comment]
~~Yeah, bit blinding when switching out from a project. I'll probably attempt building my own dark mode for this on Penpot Desktop(Unofficial).~~

I prefer to see an official one
.

**Comment by KaKi87** [comment]
Hi,
The release is not available on Docker.
Thanks
