### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by luwol03** [uxbox/uxbox#1775]
**To Reproduce**

1.  download docker-compose and env file
2.  change baseurl and add enable-insecure-registration to flags
![image](https://user-images.githubusercontent.com/60048565/161439772-3abd9358-7254-4cad-a752-9b4d43abe69c.png)
3.  register
4. click on the link in the email source which I see in the terminal in the container logs
5. complete registration
6. logout
7. try loggin in
8. see error

**Expected behavior**

User should get logged in

**Actual behavior**

An error shows up and the request to `https://myserver/api/rpc/mutation/login` returns a 400
 
**Screenshots**

![image](https://user-images.githubusercontent.com/60048565/161439729-e33a28f2-5198-44ad-9c3c-93126aae5eff.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows
- Browser & version (e.g. Chrome 89.0): Chrome 99

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): local instance

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04): Debian 10
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24): docker
- Image version (e.g. Alpine):

Docker commands or docker-compose file (if possible and if proceed.x):
see [gist](https://gist.github.com/luwol03/bdeaaefb360809ceee2efa124c7da5cb).

**Additional context:**

Could my reverse proxy setup be the problem? I created a self signed certificate that nginx proxy manager uses and enforces.

**Comment by niwinz** [comment]
I think you are using a wrong flags, yo are missing the `disable-secure-session-cookies` additionally to the `enable-insecure-register`

**Comment by luwol03** [comment]
I also tested with that flag with no success, but I will try again. Is my reverse proxy setup working like that? Or is that supposed to be different?

And why do I need to verify with that email link if I have enabled the insecure login?

**Comment by luwol03** [comment]
No, I also set the `disable-secure-session-cookies` and it doesn't helped. Do I need that because the way to the reverse proxy is transmitted over http?

I think I identified the problem after looking into the database. My database only contains `!` in the password column. How could that be caused?
![image](https://user-images.githubusercontent.com/60048565/161535732-6ded5341-6f29-49bc-893d-6f994824e1c2.png)

**Comment by niwinz** [comment]
Sorry, I have clearly missread the issue. This happens because the concrete profile does not have password set. This happens when you have used a oauth/oidc type auth flow for creating the profile. You need to proceed to use the same method to login again and set the password on profile section in order to be able to login also using password method.

**Comment by luwol03** [comment]
No, I havent used a OAuth provider. I created that account and I cannot login due to wrong credentials. Watch the video for my steps I did:

https://user-images.githubusercontent.com/60048565/161546106-2a17080a-0915-4c75-a7ee-b84d7f092f18.mp4

For my setup, I updated the linked [gist](https://gist.github.com/luwol03/bdeaaefb360809ceee2efa124c7da5cb)

**Comment by niwinz** [comment]
Very strange.

I can observe that the new report (this video) the error says: wrong credentials, that is different error from the first post: profile-without-password. They are not the 

The profile without password (with password set to `!`) are the result of using password-less flow.

I try to take time today or tomorrow for testing it myself, but right now we have this code running on production and it does not causes any problem... so I don't know what is really happening.

**Comment by overcride** [comment]
Hello,

I have the same behavior as @luwol03 . But I don't use a reverse proxy.

**Comment by luwol03** [comment]
ok. Very strange, that this runs without any issues in production. What images are they (and @overcride) using? Im using the latest with the following shas:
```
penpotapp/exporter                              latest            2d1c53f8b325   3 weeks ago     1.3GB
penpotapp/frontend                              latest            a92cc920a0ff   3 weeks ago     243MB
penpotapp/backend                               latest            467395a3d45c   3 weeks ago     868MB
```

But thank you very much for your quick response.

**Comment by overcride** [comment]
I use the same images.
![image](https://user-images.githubusercontent.com/11908418/161571058-9700cb21-ff5a-40ea-bb5e-b51f9b5e9843.png)

**Comment by niwinz** [comment]
Found and fixed the issue. Building and pushing new images right now, so in some instants it will be available on dockerhub.

**Comment by luwol03** [comment]
Thank you very much for that quick fix. Great Product.

**Comment by shangkegit** [comment]
I had a similar problem using penpot in local docker. When I first login with the registered account, I got an error "the username or password is incorrect".
I checked the network in chrome, the first request (http://192.168.56.1:29001/api/rpc/mutation/login) had a correct response. But the reponse for the second request (http://192.168.56.1:29001/api/rpc/query/profile) was incorrect, why the id is "~u00000000-0000-0000-0000-000000000000" and the fullname is "Anonymous User"

![2022-05-06 23-09-56屏幕截图](https://user-images.githubusercontent.com/21140738/167162457-3351166d-8e28-4893-a9d3-9df98dd10f0c.png)
![2022-05-06 23-09-39屏幕截图](https://user-images.githubusercontent.com/21140738/167162488-fb5652b4-4359-44ff-9bdd-2cd8da2ff3f8.png)

**Comment by jinnnyang** [comment]
> I had a similar problem using penpot in local docker. When I first login with the registered account, I got an error "the username or password is incorrect". I checked the network in chrome, the first request (http://192.168.56.1:29001/api/rpc/mutation/login) had a correct response. But the reponse for the second request (http://192.168.56.1:29001/api/rpc/query/profile) was incorrect, why the id is "~u00000000-0000-0000-0000-000000000000" and the fullname is "Anonymous User"
> 
> ![2022-05-06 23-09-56屏幕截图](https://user-images.githubusercontent.com/21140738/167162457-3351166d-8e28-4893-a9d3-9df98dd10f0c.png) ![2022-05-06 23-09-39屏幕截图](https://user-images.githubusercontent.com/21140738/167162488-fb5652b4-4359-44ff-9bdd-2cd8da2ff3f8.png)

I had the same problem. Now, I set `PENPOT_FLAGS="enable-registration disable-secure-session-cookies enable-insecure-registration"` to solve this ploblem in `config.env`. Hope that helps.

**Comment by niwinz** [comment]
This is a known issue, if you are serving penpot under different domain than `localhost` without HTTPS, you need to use the `disable-secure-session-cookies` flag. This is because the default flag is use secure cookies, but secure cookies only works on HTTPS or `localhost`.

**Comment by luwol03** [comment]
I think there was something misdocumented which was the real issue.

**Comment by shangkegit** [comment]
> > I had a similar problem using penpot in local docker. When I first login with the registered account, I got an error "the username or password is incorrect". I checked the network in chrome, the first request (http://192.168.56.1:29001/api/rpc/mutation/login) had a correct response. But the reponse for the second request (http://192.168.56.1:29001/api/rpc/query/profile) was incorrect, why the id is "~u00000000-0000-0000-0000-000000000000" and the fullname is "Anonymous User"
> > ![2022-05-06 23-09-56屏幕截图](https://user-images.githubusercontent.com/21140738/167162457-3351166d-8e28-4893-a9d3-9df98dd10f0c.png) ![2022-05-06 23-09-39屏幕截图](https://user-images.githubusercontent.com/21140738/167162488-fb5652b4-4359-44ff-9bdd-2cd8da2ff3f8.png)
> 
> I had the same problem. Now, I set `PENPOT_FLAGS="enable-registration disable-secure-session-cookies enable-insecure-registration"` to solve this ploblem in `config.env`. Hope that helps.

Yes, it works.I append "disable-secure-session-cookies" to the PENPOT_FLAGS. thanks

**Comment by shangkegit** [comment]
> This is a known issue, if you are serving penpot under different domain than `localhost` without HTTPS, you need to use the `disable-secure-session-cookies` flag. This is because the default flag is use secure cookies, but secure cookies only works on HTTPS or `localhost`.

got it, thanks

**Comment by shangkegit** [comment]
@jinnnyang 
>I had the same problem. Now, I set PENPOT_FLAGS="enable-registration disable-secure-session-cookies enable-insecure-registration" to solve this ploblem in config.env. Hope that helps.

Yes, I appended "disable-secure-session-cookies" to PENPOT_FLAGS and it works, thanks

**Comment by shangkegit** [comment]
@niwinz 
> This is a known issue, if you are serving penpot under different domain than `localhost` without HTTPS, you need to use the `disable-secure-session-cookies` flag. This is because the default flag is use secure cookies, but secure cookies only works on HTTPS or `localhost`.

Got it, thanks

**Comment by shangkegit** [comment]
@luwol03 
>I think there was something misdocumented which was the real issue.

Actrally,  I did not notice the annotation in the config.env file
![image](https://user-images.githubusercontent.com/21140738/187718812-8e49ab15-67be-45fc-be9c-2f2232ea0775.png)
