### ISSUE TITLE
Cannot login without verification.

### ISSUE THREAD

**Issue by luwol03** [uxbox/uxbox#1784]
**To Reproduce**

1. Set flags to `"enable-registration enable-insecure-registration"`
2.  Register new account
3.  Login
4.  See error, user or password is incorrect
5. Look at the database and notice that the `is_active` flag is not set

**Expected behavior**

From what I got in the docs:
> `enable-insecure-registration`: Enables the insecure process of profile regist**rio**n deactivating the email verification process (only for local or internal setups).

With this flag set, it should be possible to register without browsing through the logs and searching in the email content for the token.

(Btw. there is a typo in the docs, marked in the quote with bold)

**Actual behavior**

User needs to be verified by clicking on the link provided in the logs in the email content.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/60048565/161734430-857d2e00-ec3c-40ec-89cb-980ad10fce87.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows
- Browser & version (e.g. Chrome 89.0): Chrome 99

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): local instance

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04): Debian
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24): docker
- Image version (e.g. Alpine): Alpine

```
penpotapp/exporter                              latest            f565b83a2b5e   12 hours ago    1.3GB
penpotapp/frontend                              latest            89031c3fe44c   12 hours ago    243MB
penpotapp/backend                               latest            f47abd8f5516   12 hours ago    868MB
```

Configuration is still the same as yesterday in #1775 except the flags are as shown above.

**Comment by niwinz** [comment]
Hello @luwol03 
Yes, this is a known bug; I have noticed it yesterday, when a fixing the other one.
Will be fixed for the upcoming release.

**Comment by luwol03** [comment]
ok. Thank you.

**Comment by ItsNoted** [comment]
I was pulling my hair out trying to get logged in. Is this still an issue?

**Comment by MoeidHeidari** [comment]
After a closer inspection inside the code, it seems that they made a misspelling. 
 ```
;; If the `:enable-insecure-register` flag is set, we proceed
        ;; to sign in the user directly, without email verification.
        (true? is-active)
        (with-meta (profile/strip-private-attrs profile)
          {:transform-response ((:create session) (:id profile))
           ::audit/props (audit/profile->props profile)
           ::audit/profile-id (:id profile)})
```

it works with "enable-insecure-register" and not "enable-insecure-registration"

**Comment by niwinz** [comment]
Looks like solved.

Thanks for reporting.
