### ISSUE TITLE
Cannot join team

### ISSUE THREAD

**Issue by luwol03** [uxbox/uxbox#1785]
**To Reproduce**

1.  Create team
2.  Fish out the invitation link form logs
![image](https://user-images.githubusercontent.com/60048565/161740355-7551b57e-1511-4109-9c5d-0196ba31d031.png)
3. Open that link as the use which was invited

**Expected behavior**

User should join the team

**Actual behavior**

User gets logged out with an error
 
**Screenshots**
![image](https://user-images.githubusercontent.com/60048565/161740571-7a2e9bf8-8d74-469d-884a-b92bedc6f9cc.png)
![image](https://user-images.githubusercontent.com/60048565/161740590-41a10f88-6dbc-4007-bb6c-e71c02507bb1.png)
![image](https://user-images.githubusercontent.com/60048565/161741212-13653d70-06e3-498a-8886-11b47dd436c5.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows
- Browser & version (e.g. Chrome 89.0): Chrome 99

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): local instance

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04): Debian
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24): docker
- Image version (e.g. Alpine): Alpine

same setup as in #1784

**Comment by luwol03** [comment]
> I prove, it works 50/50
> (deleted comment)

I tested that like 10 times. Always the same problem. Are these tokens JWT token? Because if I try to decode mine, they result in an error.

**Comment by niwinz** [comment]
Yes they are JWT tokens, and the error happens becuase you are trying to copy it from the email encoded format without decoding. I was stugg with this same issue some time ago, but this is the main reason; the token is correct but the copy paste from mime encoded and padded content copies incorrect token. I recommend you configure a proper SMTP server or use something like this https://mailcatcher.me/

We are already using it in our development environment for test email sending:
https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml#L46
https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml#L172

In any case, I just have tested many invitation flows and they are working as expected.

**Comment by luwol03** [comment]
Mh, that doesn't looks like an ideal setup. What about just returning that token (link) to the user who requested the invitation if no smtp is configured, so that he can send that link by himself via email or something else? Or just simply log the tokens in the log instead of that crappy email content which is not relevant in logs.

**Comment by niwinz** [comment]
Adding the ability to copy the invitation link is a good idea. I have transmited it to our design/ux team.
Logging it to the console as is is an option, but I think it is not a solution  (same as email catcher I mean).

For now, I will take your suggestions in consideration for next release.

**Comment by niwinz** [comment]
![image](https://user-images.githubusercontent.com/843689/161921293-3e77d469-b092-442c-9ab5-668f28ce095a.png)

Logging improvements for invitations and emails.

**Comment by luwol03** [comment]
Thank you and sorry for those many issues, I hope you don't feel disturbed.

When can I expect this with the docker latest tag?
