### ISSUE TITLE
Italian l10n

### ISSUE THREAD

**Issue by xplosionmind** [uxbox/uxbox#1795]
Hello, I would like to propose myself as translator of Penpot in Italian.

**Comment by myfunnyandy** [comment]
Hi, we'd love you to help us with Italian translations. 

We've already added the language at the languages list so you can start translating it right away. Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/ 

The only thing we need to grant you permissions to edit translations is your Weblate username, the moment you tell us we will add you to the project.
Thanks!

**Comment by xplosionmind** [comment]
My username is `@tommi`. Thanks a lot!
