### ISSUE TITLE
Show Penpot website background color in Safari Tab bar

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#1803]
**Is your feature request related to a problem? Please describe.**
I would like safaris tab bar to inherit penpots background color so I can have complete dark mode for my late night design sessions 😁

**Describe the solution you'd like**
https://www.amitmerchant.com/get-your-website-ready-tab-bar-theming-of-safari-15/

**Additional context**
![image](https://user-images.githubusercontent.com/46250921/162580710-742cb18f-eb24-43aa-8139-545ef4261005.png)
![image](https://user-images.githubusercontent.com/46250921/162580724-0f1529ca-4a6e-4db7-9d79-1302ee97a2e9.png)

**Comment by hirunatan** [comment]
Thanks for your suggestion. Didn't know about this feature. If it's easy, we may do it.

I have created a Taiga issue to track it: https://tree.taiga.io/project/penpot/issue/3226
