### ISSUE TITLE
Can't change font-size when in text

### ISSUE THREAD

**Issue by mlgarchery** [uxbox/uxbox#1809]
**To Reproduce**

1.  Create a text box and start writing
2.  Then try to change font-size

**Expected behavior**

Font size changing.

**Actual behavior**

Font size is not changing. We have to select the text box to change it. 
 This induce a loss of time

**Comment by maartenverheul** [comment]
When you're editing a text, you have to select some or all of the characters to change the size of. This is made so you can have have characters of different sizes in one textbox.

Edit: Sorry, you know that already.

**Comment by EvaMarco** [comment]
Hello, @mlgarchery:
This is the behavior we are expecting. 
During the edition, you need to select which part of the text you want to update.
If you don't select anything, the text you type next will have the style you choose. This allows us to have several text styles in one sentence.
If you want to change all the text styles in a text box you can do it when you are not editing it or by selecting all rows in it.
Hope this helps¡
