### ISSUE TITLE
French translation on weblate

### ISSUE THREAD

**Issue by moeenio** [uxbox/uxbox#1817]
Hi, I would like to add missing French translations. My Weblate username is @locness3 \:)

**Comment by EvaMarco** [comment]
Hi @locness3, we'd love you to help us with French translations. We've already added you to the project and now you have permission to edit the translations. Tell us when you have finished for us to update it.
Thanks!

**Comment by alexpawlak** [comment]
Is it possible to help translate to french too? Thanks !

**Comment by moeenio** [comment]
Que faire à propos des accords en genre des adjectifs aux sujets, par exemple quand il faut confirmer une action? La plupart des chaînes utilisent actuellement "Êtes-vous sûr de...", cependant il s'agit du genre masculin, ce qui peut ne pas convenir à tout le monde...
Faudrait-il utiliser un point médian "êtes-vous sûr·e", ou plus simplement changer ces phrases en "Voulez-vous vraiment..."?

**Comment by alexpawlak** [comment]
hum bonne question ,c'est vrai qu'on pourrait pousser l'écriture inclusive :)

**Comment by niwinz** [comment]
Please, open an individual issue for each translation request, in order we able to track it properly.Thanks for the patience, but this issue was clearly missed from our internal issues review.
