### ISSUE TITLE
Internal Error when selecting vertices with shift pressed in a rounded rectangle

### ISSUE THREAD

**Issue by dfelinto** [uxbox/uxbox#1818]
I have a rounded corner rectangle that if I use shift to select its vertices I get an immediate Internal Error.

How to reproduce it:
1. Add a new rectangle
2. Change its corner radius (e.g., to 10).
3. Double-click to see the individual vertices.
4. Hold shift and drag over some of the corners (e.g., over the entire bottom-half of the rectangle).
5. Boom: Internal error

Shape right before the crash (after step 3):

![image](https://user-images.githubusercontent.com/843498/164043778-a230b862-5e22-469c-81b4-658170521bc9.png)

**Comment by EvaMarco** [comment]
Hello @dfelinto 
We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/3237) to track this issue from here. Hopefully, it will be fixed soon. 
Thanks for the report.
