### ISSUE TITLE
New translation: Polish

### ISSUE THREAD

**Issue by rnd0mized** [uxbox/uxbox#1830]
Hi,

As talked, I would love to translate Penpot into Polish. 
My weblate username: rnd 

Cheers!

**Comment by myfunnyandy** [comment]
Hi, nice to talk to you again!

We've already added you to the translation project and also the Polish language at the languages list. It always makes us really happy to add a new language! Now you just need [enter here](https://hosted.weblate.org/projects/penpot/frontend/pl/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
