### ISSUE TITLE
Guides clipping goes during import or export of a penpot file

### ISSUE THREAD

**Issue by navaneethon** [uxbox/uxbox#1838]
**To Reproduce**

1.  Add Guides to the art board
2.  Export the penpot file into our local hard disk
3.  Now import the saved penpot file to the penpot app
4. We can find that the guides clipping to the art board is missing

**Expected behavior**

The guides usually seems to be inside the art board while creating, but when we export and again import the penpot file, the guides comes out of the art board. 

**Actual behavior**

A clear and concise description of what happens instead; what the bug is.
 
**Screenshots**

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows 10
- Browser & version (e.g. Chrome 89.0): Chrome 100.0.4896

**Smartphone (please complete the following information):**
- Device & model (e.g. iPhone 6):
- OS & version (e.g. iOS 8.1):
- Browser & version (e.g. stock browser 22):

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): 

*If self-hosted:* Yes self-hosted
- OS Version (e.g. Ubuntu 16.04): Windows 10
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24): Docker 4.7.1
- Image version (e.g. Alpine):

Docker commands or docker-compose file (if possible and if proceed.x):
```

```

Frontend Stack Trace:
<details>

```

```

</details>

Backend Stack Trace:
<details>

```

```

</details>

**Additional context:**

Any other context about the problem.

**Comment by Alotor** [comment]
Thanks for the feedback. I was able to reproduce the issue. I've added it to our internal bug tracker and we hope to address it soon.
https://tree.taiga.io/project/penpot/issue/3259
