### ISSUE TITLE
Install on Synology ?

### ISSUE THREAD

**Issue by SmartHbdev** [uxbox/uxbox#1848]
Hello, is there a tuto on how to install on synology ?

I have found the backend and frontend in the docker list but something is probably missing.
The backend just stop after a short time. I don't have setup anything like ports. Just pressed next all the time.

**Comment by Alotor** [comment]
Hello, sorry but we don't know about this. But feel free to share with us if you make a tutorial.

You can find all our documentation in https://help.penpot.app/
