### ISSUE TITLE
Brazilian Portuguese translation on weblate

### ISSUE THREAD

**Issue by devadarta** [uxbox/uxbox#1862]
Hello, I would like add Brazilian Portuguese translation on WebSite.
My Weblate user is @devadarta

**Comment by pabloalba** [comment]
Hi! That's so cool!

We've already added you to the translation project. The Brazilian Portuguese language was already on the languages list, but it's only at 50%, so there is still a lot to do. Now you just need to enter [here](https://hosted.weblate.org/projects/penpot/frontend/pt_BR/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
