### ISSUE TITLE
Broken team invitation for non-registered users (on penpot.app)

### ISSUE THREAD

**Issue by valioDOTch** [uxbox/uxbox#1868]
**To Reproduce**

1.  Go to a team on penpot.app
2.  Click on the button to invite a user, add the email of someone who's not yet a user
3.  Select the corresponding role (it's certainly broken for role "Admin"; maybe "Editor" would have worked?)
4.  A mail will be sent to the corresponding email address with the invitation link. Click on the corresponding button.
5. The browser will open with the registration form. The user adds the missing fields and ends the registration process.

**Expected behavior**

At this point the team the user got invited to, should show up on the teams combo.

**Actual behavior**

The newly created user wasn't added to the team; the user won't see the corresponding team.
Clicking on the invite link again from the mail won't solve the problem, but shows the registration form again.

**Comment by valioDOTch** [comment]
I solved this case by sending a second invite to my colleague for that team.

As he was already registered on penpot.app, adding him worked.

**Comment by pabloalba** [comment]
Hi!

Thank you for your bug report. We were aware of this, and it will be resolved on the next release 1.13 (along with several enhancements on all the invitations system)

Best regards
