### ISSUE TITLE
PDF export not rendering text and messing image size

### ISSUE THREAD

**Issue by PetitMote** [uxbox/uxbox#1871]
**To Reproduce**

1.  Go to a project
2.  Click on export as pdf
3.  Enjoy

**Expected behavior**

The pdf should be ok and everything visible as in the navigator.

**Actual behavior**

Text is not rendered. It’s in there, since you can select it and copy-paste it elsewhere. But not visible. Also, images are badly rendered. Some of them are exported with a too little resolution.

Other exports are working fine.
 
**Screenshots**

![On the pdf](https://user-images.githubusercontent.com/81959473/167259612-00ea3cd2-a71b-47a8-b044-10f998d100cc.png)
On the pdf
![On the web app](https://user-images.githubusercontent.com/81959473/167259635-4f32de86-0d93-4dc3-82c7-b0e97cbb9c7f.png)
On the web app

**Desktop (please complete the following information):**
- OS (e.g. iOS): Archlinux
- Browser & version (e.g. Chrome 89.0): Tried with Firefox 100.0 and chromium 101.0.4951.54

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): design.penpot.app

**Additional context:**

Well, it’s my resume and I’m supposed to send it asap :grimacing:

**Comment by superalex** [comment]
Hello @PetitMote 

I think this can be related to two different issues:
- The texts: next release will include real SVG texts and will solve a lot of issues including some related to text rendering
- Image resolution: we had another issue related to this (https://tree.taiga.io/project/penpot/issue/3220) and we are working on it. I have one more question about it, as to include the images in a pdf they have to be resized, did you try if resizing them in an external tool to the real final size doesn't blur the images?

It would be really helpful if you could export the problematic .penpot file so we can reproduce the issue directly

Thanks,

**Comment by mlgarchery** [comment]
I have a problem that is related to PDF export badly rendering a text element. Here's the simple .penpot project (I renamed it in .zip for github to accept the file)
[template.zip](https://github.com/penpot/penpot/files/8717543/template.zip)

**Comment by superalex** [comment]
Thank you very much @mlgarchery 

Your problem is related to how we managed the texts. The next release (hopefully we will deploy it in a few hours) fully rebuilds the texts system and use real SVG to manage them and should solve your issue.

Regards,

**Comment by PetitMote** [comment]
Hi,

Sorry for the wait. It’s my resume, so I had to anonymize it before sending it, and I forgot, and here I am.

I removed a lot of elements, and strangely now some of the texts are ok. It seems to be some specific text styles. I don’t know if it’s because I modified them that they now work? But some are still not showing on the export. Images are still not ok (must be png against svg).

I don’t know if it’s important, my file was created on an older version of penpot (was working fine in november, I think).
[CV AURAN (copie).zip](https://github.com/penpot/penpot/files/8727139/CV.AURAN.copie.zip)

**Comment by superalex** [comment]
Hello @PetitMote 

I've tested your .penpot file with the new release and the result is much better:

[Fond.pdf](https://github.com/penpot/penpot/files/8727910/Fond.pdf)

I've also checked your problematic images, for example (I've added a red background to make the white visible):

![OR](https://user-images.githubusercontent.com/1579633/169263243-903e3587-7bef-4eec-a8b1-b1574e5a326d.png)

That image is 328x315 but you are resizing it to 31x30. If you do the same process out of penpot (I've used gimp) the result is blurry too so there is not too much we can do inside penpot

![MOD](https://user-images.githubusercontent.com/1579633/169263600-8a52ebb2-f0c1-40fa-8cb1-a4c414e31edb.png)

With such a resizing ratio you should try to generate a not blurry image out of penpot.

Regards,

**Comment by PetitMote** [comment]
Thanks, I’ll wait for the update!

What’s strange is I remember the images being ok before. I think there must have been a change between how penpot used to resize images and how it does it now. Maybe it’s because my file’s resolution is not correctly set.

There is still a difference between png and pdf renders:
![png](https://user-images.githubusercontent.com/81959473/169268795-6e24bfd6-1d9a-4607-9463-4f6848668a7e.png)
![pdf](https://user-images.githubusercontent.com/81959473/169268833-db5d1335-f6fd-4436-aa7c-8310e7e7444c.png)

Also, rendering as png at 4x the resolution is far better.
Maybe pdf exports are a bit harsh on the export resolution? (Well, maybe it’s simply because penpot isn’t designed for this use case 😬 and indeed, since the scale is pixel-based, it makes sense. Maybe I need more a way to upscale pdf renders)

**Comment by superalex** [comment]
I think this resizing thing have been working like this from the beggining. 

If you check my attached pdf (generated with the next release) the texts "Appears wrong" are rendered too.

Rendering at 4x will make the scaling much better because the final size of the image will be 124x120 (getting that size from 328x315 is "better" than 31x30).

**Comment by PetitMote** [comment]
Maybe they weren’t resized at all before, it used to work fine:
![image](https://user-images.githubusercontent.com/81959473/169349191-27becd49-cfd2-4237-b3b3-2d4c82379486.png)

I believe there is something to think about, here. Should images be scalable on pdf renders? Because that allows better control on the zoom level we want to allow.

**Comment by superalex** [comment]
Hmmmmm, 

Is that last screenshot from an exported PDF?, could you please attach it?

**Comment by PetitMote** [comment]
It’s indeed from an exported pdf, back from last year. I won’t be able to attach it as it contains all my personal information :/

But I exported the image from the pdf, and it seems to be 328*315px. (see below, but it’s white on transparent background, click on it)
![image](https://user-images.githubusercontent.com/81959473/169360349-1179864a-ee5a-4359-a172-7435534149a3.png)

**Comment by superalex** [comment]
Thank you very much @PetitMote, we will look into it ;)

**Comment by PetitMote** [comment]
Hi,
Just to confirm that text export is great now, thank you very much!

**Comment by superalex** [comment]
Great!!! :sparkle: :sparkle: :sparkle:
