### ISSUE TITLE
Export to PDF is broken again (text is not exported)

### ISSUE THREAD

**Issue by zhartus** [uxbox/uxbox#1876]
**To Reproduce**

1.  Create document with some text (with Roboto font in my case).
2.  Export document to pdf. (one page or full document, it doesn't matter).

**Expected behavior**

Regular export.

**Actual behavior**

Text doesn't export.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Browser & version: Firefox 99.0

**Environment (please complete the following information):**
- Host: https://design.penpot.app

**Additional context:**

Exported with a problem, even those documents that were previously exported normally. Have you again changed your export utility in recent months?

At the same time, the export to SVG is fine, but the text is converted to curves in this case.

**Comment by superalex** [comment]
Hello @zhartus 

Thank you very much for reporting this. We have fully rebuilt the export system and the text rendering too. We will publish a new release in the next days. I've checked and Robot exports should work properly under the new system too.

Regards,
