### ISSUE TITLE
Save and change Typography names error

### ISSUE THREAD

**Issue by LisonF** [uxbox/uxbox#1879]
**To Reproduce**

1.  Go to your file and create a text area with some random text
2.  Go to Conception tab, in text section
3. Click on the '+' sign next to the Text label

**Expected behavior**
Add the typographical characteristics to the file resources 

**Actual behavior**
Error message : "modification not saved" and "something wrong happened on backend"
 
**Screenshots**

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows 11
- Browser & version (e.g. Chrome 89.0): Firefox 100.0

Frontend Stack Trace:
<details>
INF [app.main] {:public-uri "https://design.penpot.app/", :version "1.12.4-beta-6707-ge0aeb3b5a", :message "Welcome to penpot"} [logging.cljc:318:16](https://design.penpot.app/js/app/common/logging.cljc)
[debug:fonts]: loading custom font custom-9dcf7fd1-cf8e-11ec-9692-ab41db0c4299 [fonts.cljs:187:4](https://design.penpot.app/js/app/main/fonts.cljs)
Ce site semble utiliser un effet de positionnement lié au défilement. Cet effet pourrait ne pas fonctionner correctement avec le défilement asynchrone. Consultez https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html pour obtenir davantage de détails ou discuter des outils et des fonctionnalités liés. [design.penpot.app](https://design.penpot.app/#/workspace/7b4f6240-c7b9-11ec-ab9e-75f6b8214121/259a5850-cd2c-11ec-ab9e-75f6b8214121?page-id=89da8741-c7b9-11ec-ab9e-75f6b8214121&layout=assets)
Internal Server Error: spec assert: ':app.common.spec.change/changes' [errors.cljs:150:5](https://design.penpot.app/js/app/main/errors.cljs)
{:ns "app.common.pages.changes",
 :name ":app.common.spec.change/changes",
 :type :assertion,
 :hint "spec assert: ':app.common.spec.change/changes'",
 :line 51, 
 :code :spec-validation}
errors.cljs:151:5
Internal Server Error: spec assert: ':app.common.spec.change/changes' errors.cljs:150:5
{:ns "app.common.pages.changes",
 :name ":app.common.spec.change/changes",
 :type :assertion,
 :hint "spec assert: ':app.common.spec.change/changes'",
 :line 51, 
 :code :spec-validation}
[errors.cljs:151:5](https://design.penpot.app/js/app/main/errors.cljs)

​
</details>

**Additional context:**

The same problem happens when trying to rename an existing typography in the library

**Comment by superalex** [comment]
Hello @LisonF 

I'm trying to reproduce the issue but I can't. Is this happening in https://design.penpot.app/ or in your own instance?. Could you also please attach some screenshots showing when the problem appears exactly?.

Thanks!

**Comment by LisonF** [comment]
Hello Alejandro, 

 

The bug happened in  <https://design.penpot.app/> https://design.penpot.app/ I attach a screenshot. I tried to modify the name of a typography (circled in blue, on the left) and then an error message was displayed saying “Saving Error” in red (into the blue square on the top right corner. Just before this saving error, another error message appeared saying “something wrong happened on the backend”. It occurred repeatedly, I could never change a typo name in this file.

 

I just tried to reproduce the behavior today in another file and everything was working just fine. So it might be related to a specific file ? 

 

Let me know if I can help in any other way. 

 

Cheers, 

 

Lison

 

De : Alejandro <> 
Envoyé : mercredi 11 mai 2022 13:47
À : penpot/penpot ***@***.***>
Cc : LisonF ***@***.***>; Mention ***@***.***>
Objet : Re: [penpot/penpot] Save and change Typography names error (Issue #1879)

 

Hello @LisonF <https://github.com/LisonF> 

I'm trying to reproduce the issue but I can't. Is this happening in https://design.penpot.app/ or in your own instance?. Could you also please attach some screenshots showing when the problem appears exactly?.

Thanks!

**Comment by superalex** [comment]
Hello LisonF, 

Sorry but the screenshot wasn't attached...

If it's happening in one file and not in others it can be related to that specific file, could you please include its url?

**Comment by LisonF** [comment]
Sorry for forgetting the file. Here it is. 

And here is the file url: https://design.penpot.app/#/workspace/7b4f6240-c7b9-11ec-ab9e-75f6b8214121/259a5850-cd2c-11ec-ab9e-75f6b8214121?page-id=89da8741-c7b9-11ec-ab9e-75f6b8214121

 

 

De : Alejandro <> 
Envoyé : mercredi 11 mai 2022 19:58
À : penpot/penpot ***@***.***>
Cc : LisonF ***@***.***>; Mention ***@***.***>
Objet : Re: [penpot/penpot] Save and change Typography names error (Issue #1879)

 

Hello LisonF,

Sorry but the screenshot wasn't attached...

If it's happening in one file and not in others it can be related to that specific file, could you please include its url?

**Comment by superalex** [comment]
Thank you very much @LisonF 

Sorry but still can't see your attached images, could you please upload them directly in the github issue and check they are rendered correctly?

**Comment by LisonF** [comment]
Hi, 
Here is the file : 
<img width="960" alt="PenPot bug report" src="https://user-images.githubusercontent.com/100200707/168759926-fa2003d5-a326-400a-a67e-3044cb333968.png">
Thank you for working on this !

**Comment by superalex** [comment]
Thank you very much!

**Comment by madalenapmelo-kp** [comment]
Hi @LisonF,

Could you please confirm if you are still experiencing this error as of the latest release?

Thanks!
