### ISSUE TITLE
Too Many Redirects on Nginx Reverse Proxy

### ISSUE THREAD

**Issue by nickian** [uxbox/uxbox#1882]
After updating my Docker images, I'm no longer able to access Penpot behind my nginx reverse proxy. I'm getting the "too many redirects" error now and there aren't any errors in the nginx error log. I can access Penpot with http://ip:9001, but not on my domain. Did something change with the configuration?

I don't see any examples listed anywhere for doing a reverse proxy in the documentation. This is the config I was using. Is there something wrong with this?:

```
server {
    listen 443 ssl;
    server_name mydomain.com www.mydomain.com;

    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    
    location / {
        proxy_pass http://localhost:9001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }

}

server {
    listen      80;
    server_name mydomain.com www.mydomain.com;
    return 301 https://$server_name$request_uri;
}
```

**Comment by nickian** [comment]
Oops! Nevermind. I resolved this. It turned out to be an issue with Cloudflare SSL settings, not Penpot.

**Comment by superalex** [comment]
Great!, 

Checking it was in my TODO list for today :)
