### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [uxbox/uxbox#1897]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@b1nslashsh) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by superalex** [comment]
Hello @JamieSlome 

Thank you very much for your recommendation, we will include that as soon as poosible, it will be great if you share it with us at support@penpot.app

Regards

**Comment by JamieSlome** [comment]
@superalex - of course 👍 

I'll get that sent over shortly. In the meantime, you can view the report directly here, if you prefer:
https://huntr.dev/bounties/5981a36a-d5b0-4cfb-982e-1b62fc4f1a0c/

It is currently private and only accessible to maintainers with repository write permissions 👍

**Comment by superalex** [comment]
Thank you very very much, we will review it as soon as possible
