### ISSUE TITLE
Self Hosted: Error 400 on image upload.

### ISSUE THREAD

**Issue by Verequies** [uxbox/uxbox#1917]
**To Reproduce**

Attempt to upload an image, or template such as the Plant example.

**Expected behavior**

Image or template uploads successfully.

**Actual behavior**

Image fails to upload, returning HTTP 400 and gives the following error in developer console.
```
/api/rpc/mutation/upload-file-media-object

{"~:type":"~:validation","~:hint":"Seems like you are uploading a file whose content does not match the extension.Expected: image/png. Got: ","~:code":"~:media-type-mismatch"}
```
 
**Desktop:**
- OS: Arch Linux
- Browser: Chrome Beta, Vivaldi Snapshot, Firefox, all browsers

**Environment & Additional context:**
Figured out how to build penpot without docker as I am unable to use docker on my server.
Built and tested staging branch commit https://github.com/penpot/penpot/commit/29010453e6d7499a1d17ca0bca0e1e5bea5497d6 .

Everything seems to work except uploading images which result in the above error.
I have matched everything I can to the docker configuration.
There is nothing apparent that is wrong with my NGINX configuration - I run many other services alongside penpot as well.
Have also tried recompiling and running with Java 11 and 16 instead of 18 to no avail. 

Uploading the same file on https://design.penpot.app works.
Analysing the request header/data confirms that they are identical except for hashes/IDs.

**penpot build script** (builds in current directory):
```bash
#!/bin/bash

# Setup variables
version="1.13.0-beta"
commit_hash="2901045"
babashka_version="0.8.2"
clj_kondo_version="2022.04.25"

# Setup Java Home
export PATH="/usr/lib/jvm/java-18-openjdk/bin:$PATH"

# Cleanup old files
rm -rf bin penpot.jar public src *.tar.gz*

# Create bin and src
mkdir -p {bin,src}

# Download the latest version of penpot
wget -O penpot-$version.tar.gz https://github.com/penpot/penpot/archive/$commit_hash.tar.gz
tar -xf penpot-$version.tar.gz --strip-components=1 -C src

# Patch backend to allow for redis sockets
sed -i 's/io.lettuce\/lettuce-core {:mvn\/version "6.1.6.RELEASE"}/io.lettuce\/lettuce-core {:mvn\/version "6.1.8.RELEASE"}\n  io.netty\/netty-transport-native-epoll$linux-x86_64 {:mvn\/version "4.1.77.Final"}\n/' src/backend/deps.edn

# Patch backend to allow setting the temporary asset directory
sed -i 's/"\/tmp\/penpot"/(cf\/get :tmp-directory)/' src/backend/src/app/main.clj

# Build backend
pushd src/backend
./scripts/build $version
popd
mv src/backend/target/dist/penpot.jar .

# Build exporter
pushd src/exporter
./scripts/build $version
cd target
yarn add pkg
yarn pkg -C GZip -t node18-linux-x64 -o penpot-exporter app.js
popd
mv src/exporter/target/penpot-exporter bin/penpot-exporter
chmod +x bin/penpot-exporter

# Patch frontend build to get commit hash from $2
sed -i 's/CURRENT_HASH=${CURRENT_HASH:-$(git rev-parse --short HEAD)};/CURRENT_HASH=$2/' src/frontend/scripts/build

# Build frontend
pushd src/frontend
./scripts/build $version $commit_hash
popd
mv src/frontend/target/dist public
mv src/docker/images/files/config.js public/js/config.js

# Clean up
rm penpot-$version.tar.gz
rm -r src

# Download babashka
wget -O - https://github.com/borkdude/babashka/releases/download/v$babashka_version/babashka-$babashka_version-linux-amd64-static.tar.gz | tar -zxf -
mv bb bin/bb
chmod +x bin/bb

# Download clj-kondo
wget -O - https://github.com/clj-kondo/clj-kondo/releases/download/v$clj_kondo_version/clj-kondo-$clj_kondo_version-linux-static-amd64.zip | zcat > bin/clj-kondo
chmod +x bin/clj-kondo
```

**penpot run script:**
```bash
#!/bin/bash

# Setup PATH
export PATH="/usr/lib/jvm/java-18-openjdk/bin:bin/:$PATH"

# Run penpot exporter
PENPOT_TENANT=pro \
PENPOT_PUBLIC_URI=redacted \
PENPOT_REDIS_URI=redacted \
penpot-exporter&

# Run penpot backend
PENPOT_TENANT=pro \
PENPOT_PUBLIC_URI=redacted \
PENPOT_HTTP_SERVER_HOST=redacted \
PENPOT_HTTP_SERVER_PORT=6060 \
PENPOT_SREPL_HOST=redacted \
PENPOT_SREPL_PORT=6062 \
PENPOT_DATABASE_URI=redacted \
PENPOT_DATABASE_USERNAME=redacted \
PENPOT_DATABASE_PASSWORD=redacted \
PENPOT_REDIS_URI=redacted \
PENPOT_ASSETS_STORAGE_BACKEND=redacted \
PENPOT_STORAGE_ASSETS_FS_DIRECTORY=redacted \
PENPOT_TMP_DIRECTORY=redacted \
PENPOT_SECRET_KEY=redacted \
PENPOT_TELEMETRY_ENABLED=false \
PENPOT_SMTP_ENABLED=true \
PENPOT_SMTP_DEFAULT_FROM=redacted \
PENPOT_SMTP_DEFAULT_REPLY_TO=redacted \
PENPOT_SMTP_HOST=redacted \
PENPOT_SMTP_PORT=redacted \
PENPOT_SMTP_USERNAME=redacted \
PENPOT_SMTP_PASSWORD=redacted \
PENPOT_SMTP_TLS=true \
PENPOT_SMTP_SSL=false \
PENPOT_LDAP_HOST=redacted \
PENPOT_LDAP_PORT=redacted \
PENPOT_LDAP_SSL=redacted \
PENPOT_LDAP_STARTTLS=redacted \
PENPOT_LDAP_BASE_DN=redacted \
PENPOT_LDAP_BIND_DN=redacted \
PENPOT_LDAP_BIND_PASSWORD=redacted \
PENPOT_LDAP_ATTRS_USERNAME=redacted \
PENPOT_LDAP_ATTRS_EMAIL=redacted \
PENPOT_LDAP_ATTRS_FULLNAME=redacted \
PENPOT_LDAP_ATTRS_PHOTO=redacted \
PENPOT_LOGIN_WITH_LDAP=true \
PENPOT_FLAGS="enable-backend-asserts enable-audit-log enable-transit-readable-response enable-login-with-ldap disable-login disable-registration disable-demo-users" \
java -Djava.io.tmpdir="redacted" -jar penpot.jar -m app.main
```

**Comment by superalex** [comment]
Hello @Verequies 

Be careful when using the staging branch, you should always use the **main** one. Could you please check if the problem is also happening in that branch?

Regards,

**Comment by Verequies** [comment]
Hey @superalex 

Yeah, I've tried compiling on main, develop and staging branches. As well as previous beta releases back to 1.11-beta.
Nothing made a difference. I have also just tested compiling the latest 1.13.0-beta release to no avail.

I have uploaded that 1.13.0-beta build [here](https://mega.nz/file/MERATRLI#7WHtaF4cNEA5ljnbcWliokd4cYU_ux9nJxO-sSjOqZw) for reference to test with. Should be able to edit the environment variables in the `run` script, then run that script and serve the public folder with NGINX.

**Comment by superalex** [comment]
Hello @Verequies 

I'm using your scripts to deploy locally Penpot in the same way. Could you also please include your nginx configuration?

**Comment by Verequies** [comment]
Hey @superalex 

Sure, I have a fairly complicated setup so I've stripped some stuff down and removed some sensitive information. Hopefully it should still work.

Main NGINX configuration (`/etc/nginx/nginx.conf`):
```
# User and Workers
user                    web;
worker_processes        4;

events {

        worker_connections      768;
        # multi_accept          on;

}

http {

        # Basic Settings

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 4096;
        server_tokens off;
        client_max_body_size 65M;
        disable_symlinks off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # Logs

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Gzip

        gzip on;
        gzip_disable "msie6";

        # Virtual Hosts

        include         /etc/nginx/sites-enabled/*;

        # Mappings

        map $http_upgrade $connection_upgrade {

                default upgrade;
                ''      close;

        }

}
```

Penpot Server Block (`/etc/nginx/sites-enabled/penpot`):
```
server {

        listen                  localhost:443 http2 ssl;

        ssl_certificate         /etc/cert/fullchain.pem;
        ssl_certificate_key     /etc/cert/privkey.pem;
        ssl_trusted_certificate /etc/cert/fullchain.pem;

        include                 /etc/nginx/ssl_params;

        server_name             penpot.example.com;

        root                    /home/penpot/public;

        index                   index.html;

        location /api {

                include                 /etc/nginx/proxy_params;
                proxy_pass              http://localhost:6060/api;

        }

        location /api/export {

                include                 /etc/nginx/proxy_params;
                proxy_pass              http://localhost:6061;

        }

        location /assets {

                include                 /etc/nginx/proxy_params;
                proxy_pass              http://localhost:6060/assets;

        }

        location /webhooks {

                include                 /etc/nginx/proxy_params;
                proxy_pass              http://localhost:6060/webhooks;

        }

        location /ws/notifications {

                include                 /etc/nginx/socket_params;
                proxy_pass              http://localhost:6060/ws/notifications;

        }

}
```
SSL/TLS Settings (`/etc/nginx/ssl_params`):
```
ssl_session_cache               shared:SSL:10m;
ssl_session_timeout             10m;
ssl_session_tickets             off;

ssl_protocols                   TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers       on;
ssl_ecdh_curve                  secp521r1:secp384r1;

#TLS v1.2
ssl_ciphers                     "ECDHE+ECDSA+CHACHA20:ECDHE+ECDSA+AESGCM:!AES128";

#TLS v1.3
ssl_conf_command                Ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384;

ssl_stapling                    on;
ssl_stapling_verify             on;

resolver                        1.1.1.1 1.0.0.1 valid=300s;
resolver_timeout                5s;

add_header                      Expect-CT "enforce, max-age=2592000, report-uri=\"https://report.example.com\"" always;
add_header                      Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
```

Proxy Settings (`/etc/nginx/proxy_params`):
```
proxy_connect_timeout           10s;
proxy_send_timeout              3600s;
proxy_read_timeout              3600s;
proxy_redirect                  off;
proxy_set_header                Host $host;
proxy_set_header                X-Real-IP $remote_addr;
proxy_set_header                X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header                X-Forwarded-Proto $scheme;
proxy_buffering                 on;
proxy_pass_request_headers      on;
```

Socket Proxy Settings (`/etc/nginx/socket_params`):
```
proxy_http_version              1.1;
proxy_set_header                Upgrade $http_upgrade;
proxy_set_header                Connection "upgrade";
proxy_connect_timeout           10s;
proxy_send_timeout              3600s;
proxy_read_timeout              3600s;
proxy_redirect                  off;
proxy_set_header                Host $host;
proxy_set_header                X-Real-IP $remote_addr;
proxy_set_header                X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header                X-Forwarded-Proto $scheme;
proxy_buffering                 on;
proxy_pass_request_headers      on;
```

**Comment by superalex** [comment]
I've used your scripts to mount it locally and can reproduce the issue with images. 

I suspect the problem is with nginx configuration because I've tried launching the backend from docker and the problem happens too.

**Comment by Verequies** [comment]
I'm not so sure it is an issue with the nginx configuration. The issue is very odd as I have apps like Nextcloud and GitLab running on my server, and have never faced an issue with transmitting data through nginx. 

Would you have any idea to what part of the configuration could cause the issue are you able to narrow it down with the docker images?

**Comment by superalex** [comment]
I'm not sure, I though the problem could be in the backend so I used your configuration for nginx, front and exporter) and launch the backend directly with https://github.com/penpot/penpot/blob/develop/backend/scripts/start-dev. As it was failing in the same way it made me suspect that it could be something related to nginx.

**Comment by Verequies** [comment]
Interesting, thanks for testing that. Are you able to test my backend configuration and exporter, but use the docker image for the frontend to see if that works?

I just tested copying the docker nginx.conf directly, modifying it to support SSL (required by my server) and then testing it. Same issue.

**Comment by Verequies** [comment]
Okay, so I've removed NGINX and my builds from the equation. Purely just testing from source.
Running the backend directly with that script you gave `start-dev` and with the frontend served with `yarn watch-main` in the frontend directory also shows the same error. There is definitely a bug in the code somewhere.

**Comment by superalex** [comment]
Hmmmmmmm, that's very strange I'll have to do some more tests on monday to see if I can find what's happening. Thanks!

**Comment by Verequies** [comment]
Is there any update on this issue? Without being able to upload images, my team and I are a bit limited.

**Comment by superalex** [comment]
Hello @Verequies 

I finally could serve penpot locally without docker. But I changed how I build the "artefacts", I used the "manage.sh" script from the repo:
- For frontend: "./manage.sh build-frontend-bundle", it will generate a bundle-frontend folder and it's the one I configure nginx to serve
- For backend: "./manage.sh build-backend-bundle", it will generate a bundle-backend folder with a run.sh script to laucnh. That's the one I used
- For exporter: "./manage.sh build-exporter-bundle", it will generate a bundle-exporter folder. In tha folder execute "yarn" and then "node app.js"

I hope it helps! ;)

**Comment by Verequies** [comment]
Hi @superalex 

Unfortunately the `manage.sh` script does not work for me as it uses Docker to build.
Did you get the error during upload with those bundles?
I'm happy to test if you are able to upload them.

**Comment by superalex** [comment]
You could use docker to build in another machine and then upload the bundles to the final machine :)

With the bundles generated using manage.sh I have no upload errores.

I have uploaded the bundles here:
- https://tmpfiles.org/298703/bundle-exporter.tgz
- https://tmpfiles.org/298704/bundle-frontend.tgz
- https://tmpfiles.org/298706/bundle-backend.tgz

(will be available only for twp hours)

**Comment by Verequies** [comment]
Thanks for uploading your build.
Unfortunately I still receive the same 400 Bad Request error when uploading an image file.
```
{"~:type":"~:validation","~:hint":"Seems like you are uploading a file whose content does not match the extension.Expected: image/png. Got: ","~:code":"~:media-type-mismatch"}
```

**Comment by superalex** [comment]
Are you sure you are using those bundles and none of the previous ones?. With these and nginx I'm able to upload images propery.

**Comment by Verequies** [comment]
I am 100% sure as I tested it on my server in a fresh folder and pointed my NGINX configuration to it. Same error as compiling and running directly from source. I retested on the latest main brand commit also.

**Comment by Verequies** [comment]
Are you able to export your NGINX configuration so I may test with that?

**Comment by superalex** [comment]
Sorry @Verequies I had to jump to another tasks from the project and couldn't check your issue. I'll write you again as soon as I can

**Comment by Verequies** [comment]
No worries, it would be great to get this issue sorted soon.

**Comment by superalex** [comment]
Hello @Verequies after a looooong investigation I think I found the reason that makes the upload work sometimes.

We are using im4java, a librarte to comunicate with imagemagick from java. After a lot of testing I've seen that this library is not working properly if the imagemagic version is 7 (it should work with the legacy version 6). 

Could you please check your imagemagick version?, something like "identify -version" should give you the info.

In my system I could install both versions and the use the IM4JAVA_TOOLPATH to point to the legacy one: http://im4java.sourceforge.net/docs/dev-guide.html

I hope it helps ;)

Regards,

**Comment by Verequies** [comment]
Hello @superalex 

Thank you for doing all that testing. I can confirm I am using ImageMagick version 7.1.0.37.
I will see if I can test with version 6, but is there a way we can make penpot work with the latest version, considering I have been using it since 2017?

**Comment by superalex** [comment]
We will have to make it work in the near future but it requires deep changes in that part of the code. Right now the only option is using the legacy version :(

**Comment by Verequies** [comment]
I would probably keep this issue open and rename the title to ImageMagick 7 support.
Also I tried your WIP pull request and it does fix the upload issue but the images do not appear properly, which is understandable as you said it required deep changes.
Will try ImageMagick 6 shortly.

**Comment by Verequies** [comment]
I have attempted to get it working with ImageMagick 6, but still receiving the error. I might be doing it wrong, but I'm using the latest ImageMagick 6.9.12-52 release. I did try changing my PATH environmental variable, and using the IM4JAVA_TOOLPATH to no avail.

May I ask what version you are using, and how you installed it? Would be great if I can get a link the binaries to test with.

**Comment by superalex** [comment]
I closed this one but I created another in Taiga called "replace im4java".

My PR is an initial exploration, next week I would like to discuss it with the rest of the team, I think we will probably have to replace im4java with other library

I'm using arch linux. I installed from here https://aur.archlinux.org/packages/libmagick6 and when finished pointed IM4JAVA_TOOLPATH to /home/superalex/programs/imagemagick6/src/binpkg/usr/bin

**Comment by Verequies** [comment]
Okay cool, so we are using the same versions. I did the same to be sure, and I don't get the wrong file extension error anymore. However I do get an invalid image error.
```
{"~:type":"~:validation","~:hint":"invalid image","~:code":"~:invalid-image"}
```
Any clue to why that may be?

**Comment by superalex** [comment]
Hello again @Verequies 

We have just merged this -> https://github.com/penpot/penpot/pull/1996 to develop (it will be included in the new release). That MR allows you to launch backend with the extra JAVA option "-J-Dim4java.useV7=true" to use imagemagick 7 :)

Regards,

**Comment by Verequies** [comment]
Hey @superalex,

I have tested the 'develop' branch of penpot which includes the merged changes. Using this build I am able to upload images without error but unfortunately the image appears blank on the canvas. In the developer console I receive these errors:
![image](https://user-images.githubusercontent.com/282071/173709782-f63a2d2a-7a72-49e0-9d7a-1fa82d38ff19.png)

Here is an image of what the selected image looks like on the canvas.
![image](https://user-images.githubusercontent.com/282071/173709848-c8476997-efbc-4387-bbba-97e67a2ca932.png)

I have made sure to use the "-Dim4java.useV7=true" option when running penpot.

**Comment by superalex** [comment]
It sounds like a nginx configuration problem, did you check the url that is using to draw the image and if it fits in any of your nginx rules?

**Comment by Verequies** [comment]
I am pretty sure NGINX is configured properly. It seems to be creating the file on disk, and inserting an entry into the database ```file_media_object``` table. What I did notice is that the URL that it searches by is say ```https://penpot.example.com/assets/by-file-media-id/900094a0-ec87-11ec-9661-0f5e09152b95```. However the ID in the URL is actually the primary key in the database, not the media_id ID - which is ```c7f074c0-9a7e-48eb-bc46-e297973973bb``` and correlates correctly to the file structure on disk. Perhaps the ID isn't being mapped properly here? I tried swapping the media_id for the one in the database as well, and that didn't work either.

**Comment by niwinz** [comment]
Ensure you have `resolver 8.8.8.8` on http directive on nginx.
You probably see the error on nginx error or access logs about this.
You also can use your own DNS service, the 8.8.8.8 is just an example

**Comment by niwinz** [comment]
On our docker we have:
![image](https://user-images.githubusercontent.com/843689/173794304-8c589506-2c0d-47a1-a04f-6827825a0f67.png)

**Comment by Verequies** [comment]
Thanks for the suggestion, as per my configuration above, I have my resolver set to 1.1.1.1 for CloudFlare as I use them as my DNS. I think a lot of my apps would be broken if that wasn't working, so I don't think that's the issue on why it can't find load the image. 

I use the resolver per server block under my SSL/TLS settings as some of my other sites do not run under CloudFlare and this allows me to change it for each site.

**Comment by niwinz** [comment]
> I am pretty sure NGINX is configured properly. It seems to be creating the file on disk, and inserting an entry into the database `file_media_object` table. What I did notice is that the URL that it searches by is say `https://penpot.example.com/assets/by-file-media-id/900094a0-ec87-11ec-9661-0f5e09152b95`. However the ID in the URL is actually the primary key in the database, not the media_id ID - which is `c7f074c0-9a7e-48eb-bc46-e297973973bb` and correlates correctly to the file structure on disk. Perhaps the ID isn't being mapped properly here? I tried swapping the media_id for the one in the database as well, and that didn't work either.

This is correct, this is how it works.

Right now I don't have any idea why it does not works and no image is displayed. For some reason the`/by-file-media-id/` returns 404... can you check if the `900094a0-ec87-11ec-9661-0f5e09152b95` exists in the `file_media_object` table?

**Comment by Verequies** [comment]
It does exist in the database as the primary key in the ```file_media_object``` table and correlates to the ```media_id``` ```c7f074c0-9a7e-48eb-bc46-e297973973bb```. That file also exists in the on disk file structure, to which permissions are correctly set for access.

**Comment by niwinz** [comment]
Can you look the nginx error/access log when you accesing the `.../by-file-media-id/...` url?

**Comment by Verequies** [comment]
Okay, so it seems to work now. It turns out I was missing a redirect for ```public/internal/assets/``` to where the data directory is actually located. I did have this symbolic link earlier but was probably removed when I was rebuilding penpot to test the ImageMagick 7 fixes.

Thanks a lot for getting this working :)

**Comment by msbt** [comment]
@Verequies nice work on that, is there any chance that your working script is available publicly somewhere?

**Comment by Verequies** [comment]
Hi @msbt,

You can update the version by modifying the version string and commit hash in the below build script.
Once built, you can run it with the run script.
Here are the contents of my scripts:

`build.sh`
```bash
#!/bin/bash

# Install fontforge and jre-openjdk via pacman
# Setup variables
version="1.17.0-beta"
commit_hash="e6b2c40"
babashka_version="0.8.2"
clj_kondo_version="2022.06.22"

# Setup Java Home
export PATH="/usr/lib/jvm/java-19-openjdk/bin:bin/:$PATH"

# Cleanup old files
rm -rf bin penpot.jar public src *.tar.gz*

# Create bin and src
mkdir -p {bin,src}

# Download babashka
wget -O - https://github.com/borkdude/babashka/releases/download/v$babashka_version/babashka-$babashka_version-linux-amd64-static.tar.gz | tar -zxf -
mv bb bin/bb
chmod +x bin/bb

# Download clj-kondo
wget -O - https://github.com/clj-kondo/clj-kondo/releases/download/v$clj_kondo_version/clj-kondo-$clj_kondo_version-linux-static-amd64.zip | zcat > bin/clj-kondo
chmod +x bin/clj-kondo

# Download and build sfnt2woff
git clone https://github.com/wget/sfnt2woff
cd sfnt2woff
make
mv sfnt2woff ../bin/sfnt2woff
mv woff2sfnt ../bin/woff2sfnt
cd ..
rm -rf sfnt2woff

# Download the latest version of penpot
wget -O penpot-$version.tar.gz https://github.com/penpot/penpot/archive/$commit_hash.tar.gz
tar -xf penpot-$version.tar.gz --strip-components=1 -C src

# Patch backend to allow for redis sockets
sed -i 's/io.lettuce\/lettuce-core {:mvn\/version "6.1.6.RELEASE"}/io.lettuce\/lettuce-core {:mvn\/version "6.1.8.RELEASE"}\n  io.netty\/netty-transport-native-epoll$linux-x86_64 {:mvn\/version "4.1.77.Final"}\n/' src/backend/deps.edn

# Patch backend to allow setting the temporary asset directory
sed -i 's/"\/tmp\/penpot"/(cf\/get :tmp-directory)/' src/backend/src/app/main.clj

# Build backend
pushd src/backend
./scripts/build $version
popd
mv src/backend/target/dist/penpot.jar .

# Build exporter
pushd src/exporter
./scripts/build $version
cd target
yarn add pkg
yarn pkg -C GZip -t node18-linux-x64 -o penpot-exporter app.js
popd
mv src/exporter/target/penpot-exporter bin/penpot-exporter
chmod +x bin/penpot-exporter

# Patch frontend build to get commit hash from $2
sed -i 's/CURRENT_HASH=${CURRENT_HASH:-$(git rev-parse --short HEAD)};/CURRENT_HASH=$2/' src/frontend/scripts/build

# Build frontend
pushd src/frontend
./scripts/build $version $commit_hash
popd
mv src/frontend/target/dist public
mv src/docker/images/files/config.js public/js/config.js

# Clean up
rm penpot-$version.tar.gz
rm -r src

# Apply frontend config
sed -i "s/\/\/var/var/" public/js/config.js 
sed -i "s/\"\"/\"enable-cors enable-backend-asserts enable-audit-log enable-transit-readable-response enable-login-with-ldap disable-login disable-registration disable-demo-users\"/" public/js/config.js

```

`manage.sh`
```bash
#!/bin/bash

# Setup PATH
export PATH="/usr/lib/jvm/java-19-openjdk/bin:bin/:$PATH"

# Run penpot backend
PENPOT_PUBLIC_URI=http://localhost:9001 \
PENPOT_TENANT=pro \
PENPOT_HTTP_SERVER_HOST=Server.example.com \
PENPOT_DATABASE_URI=postgresql://Server.example.com:5432/penpot \
PENPOT_DATABASE_USERNAME=DB_USER \
PENPOT_DATABASE_PASSWORD="DB_PASS" \
PENPOT_REDIS_URI=redis-socket:///run/redis/redis.sock \
PENPOT_ASSETS_STORAGE_BACKEND=assets-fs \
PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/var/www/example.com/penpot/data/assets \
PENPOT_TELEMETRY_ENABLED=false \
java -Djava.io.tmpdir="/var/www/example.com/penpot/tmp" -Dim4java.useV7=true -jar penpot.jar -m app.cli.manage

```

`run.sh`
```bash
#!/bin/bash

# Setup PATH
export PATH="/usr/lib/jvm/java-19-openjdk/bin:bin/:$PATH"

# Run penpot exporter
PENPOT_TENANT=pro \
PENPOT_PUBLIC_URI=https://penpot.example.com \
PENPOT_REDIS_URI=redis-socket:///run/redis/redis.sock \
penpot-exporter&

# Run penpot backend
PENPOT_TENANT=pro \
PENPOT_PUBLIC_URI=https://penpot.example.com \
PENPOT_HTTP_SERVER_HOST=Server.example.com \
PENPOT_HTTP_SERVER_PORT=6060 \
PENPOT_SREPL_HOST=Server.example.com \
PENPOT_SREPL_PORT=6062 \
PENPOT_DATABASE_URI=postgresql://Server.example.com:5432/ux \
PENPOT_DATABASE_USERNAME=DB_USER \
PENPOT_DATABASE_PASSWORD="DB_PASS" \
PENPOT_REDIS_URI=redis-socket:///run/redis/redis.sock \
PENPOT_REDIS_URI=redis://Server.example.com:6379 \
PENPOT_ASSETS_STORAGE_BACKEND=assets-fs \
PENPOT_STORAGE_ASSETS_FS_DIRECTORY="/var/www/example.com/penpot/data/assets" \
PENPOT_TMP_DIRECTORY=/var/www/example.com/penpot/tmp \
PENPOT_SECRET_KEY="SECRET_KEY" \
PENPOT_TELEMETRY_ENABLED=false \
PENPOT_SMTP_ENABLED=true \
PENPOT_SMTP_DEFAULT_FROM=no-reply@penpot.example.com \
PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@penpot.example.com \
PENPOT_SMTP_HOST=mail.example.com \
PENPOT_SMTP_PORT=587 \
PENPOT_SMTP_USERNAME="penpot@example.com" \
PENPOT_SMTP_PASSWORD="SMTP_PASS" \
PENPOT_SMTP_TLS=true \
PENPOT_SMTP_SSL=false \
PENPOT_LDAP_HOST=Server.example.com \
PENPOT_LDAP_PORT=389 \
PENPOT_LDAP_SSL=false \
PENPOT_LDAP_STARTTLS=true \
PENPOT_LDAP_BASE_DN=ou=users,ou=example.com,dc=example,dc=com \
PENPOT_LDAP_BIND_DN=uid=penpot,ou=services,ou=example.com,dc=example,dc=com \
PENPOT_LDAP_BIND_PASSWORD="LDAP_PASS" \
PENPOT_LDAP_ATTRS_USERNAME=uniqueIdentifier \
PENPOT_LDAP_ATTRS_EMAIL=mail \
PENPOT_LDAP_ATTRS_FULLNAME=cn \
PENPOT_LDAP_ATTRS_PHOTO=avatar \
PENPOT_LOGIN_WITH_LDAP=true \
PENPOT_FLAGS="enable-cors enable-backend-asserts enable-audit-log enable-transit-readable-response enable-login-with-ldap disable-login disable-registration disable-demo-users" \
java -Djava.io.tmpdir="/var/www/example.com/penpot/tmp" -Dim4java.useV7=true -jar penpot.jar -m app.main

```

**Comment by msbt** [comment]
@Verequies thanks, that part I got, I was just worried because you mentioned symlinked asset directories which might need some extra work that's not included in the scripts ;) I'll give it a go in a bit and see how far I'll come. Appreciate it!

**Comment by Verequies** [comment]
@msbt 

I have just used the alias keyword to link to the directory in my NGINX config.
Here is my Penpot section of my NGINX configuration.

```nginx
server {

        listen                  Server.example.com:443 http2 ssl;

        ssl_certificate         /etc/nginx/tls/fullchain.pem;
        ssl_certificate_key     /etc/nginx/tls/privkey.pem;
        ssl_trusted_certificate /etc/nginx/tls/fullchain.pem;

        include                 /etc/nginx/ssl_params;

        server_name             penpot.example.com;

        include                 /etc/nginx/protection_params;

        root                    /var/www/example.com/penpot/public;

        index                   index.html;

        access_log              /var/log/penpot-access.log combined;
        error_log               /var/log/penpot-error.log;

        location /api {

                include                 /etc/nginx/proxy_params;
                proxy_pass              http://Server.example.com:6060/api;

        }

        location /api/export {

                include                 /etc/nginx/proxy_params;
                proxy_pass              http://Server.example.com:6061;

        }

        location /assets {

                include                 /etc/nginx/proxy_params;
                proxy_pass              http://Server.example.com:6060/assets;

        }

        location /internal/assets {

                internal;
                alias                   /var/www/example.com/penpot/data/assets;

        }

        location /webhooks {

                include                 /etc/nginx/proxy_params;
                proxy_pass              http://Server.example.com:6060/webhooks;

        }

        location /ws/notifications {

                include                 /etc/nginx/socket_params;
                proxy_pass              http://Server.example.com:6060/ws/notifications;

        }

}
```

**Comment by msbt** [comment]
ok cool, thanks again!
