### ISSUE TITLE
Roboto Flex font

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1918]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It should be better to use ROBOTO FLEX font instead UI-font used in Penpot currently.
https://github.com/googlefonts/roboto-flex

Details: https://9to5google.com/2022/05/05/roboto-flex-font/

**Comment by superalex** [comment]
Thank you very much @catcargos 

I've just created the [Taiga enhancement](https://tree.taiga.io/project/penpot/issue/3422) to manage this. I hope we can start working on it soon.

Regards,

**Comment by pabloalba** [comment]
The font used by the Penpot UI was selected for it's legibility and aesthetics. Our designers have discussed this idea,  and we think that the current font is the right choice (for now). Thank you anyway for the suggestion!
