### ISSUE TITLE
The font cannot be set to the number 12

### ISSUE THREAD

**Issue by AlienHub** [uxbox/uxbox#1922]
**Expected behavior**

When the font is set to No. 10, the font becomes 10

**Actual behavior**

The smallest font can only be on the 12th

**Comment by superalex** [comment]
Sorry @AlienHub but I don't fully understand how to reproduce the issue, could you please detail the steps to reproduce it?

As you see in the attached gif I can set the text size to smaller values.

![Peek 2022-05-19 19-14](https://user-images.githubusercontent.com/1579633/169359177-604ca2c6-efd1-426d-8e09-ba2f80b3f219.gif)

**Comment by AlienHub** [comment]
https://user-images.githubusercontent.com/44266450/169451464-b68325d7-ec8c-4dc4-9285-c26837c65fbe.mov

**Comment by AlienHub** [comment]
> 2022-05-20.12.36.21.mov

@superalex This is in my local instance, but I also reproduced this problem on Penpot.app.I use the Mac Air M1 browser: chrome 101.0.4951.64

**Comment by superalex** [comment]
Thank you very much @AlienHub 

I think it's a configuration of your own chrome. Go to settings -> appearance -> customize fonts and  check the value of "Minimum font size" is configured correctly (probably it's set to 12px in your system).

![1](https://user-images.githubusercontent.com/1579633/169455760-f1d29cbc-d2a4-4561-8ba8-5b9a05512e0b.png)
