### ISSUE TITLE
Docker Version Not Updating

### ISSUE THREAD

**Issue by nickian** [uxbox/uxbox#1925]
The documentation says this will update me to the latest version:

```
docker-compose -f docker-compose.yaml pull
```

However, this is not working for me. I even tried:

```
cd penpot/docker/images
docker-compose -p penpot down
docker system prune -a
docker-compose -f docker-compose.yaml pull
docker-compose -p penpot -f docker-compose.yaml up -d
```

Still shows the same old version when I go to "Your Account" then "Release Notes." (Beta version 1.12) What am I doing wrong here?

Thanks.

**Comment by superalex** [comment]
Hello @nickian 

You are not doing anything wrong, the last published version in docker is that one, probably we will generate de 1.13 today ;)

**Comment by nickian** [comment]
Oh, got it. Haha, I didn't think that maybe the Docker build was a little behind the release. That makes sense. Thanks!

**Comment by superalex** [comment]
You are welcome! ;)
