### ISSUE TITLE
Erase guide line and lines magnetized

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#1930]
**Is your feature request related to a problem? Please describe.**
I don't use the penpot very often and there are several reasons and one of them I mention here.
I can't erase a guide line and guide lines don't have magnetized action.

**Describe the solution you'd like**
To delete the guide lines, a good solution would be to click on one, change the color to specify that it was selected and press the `delete`/`del` button to delete the line.
For magnetized lines, one solution is that when the line approaches some element, the line takes the same position as some point on that element. Just like figma or inkscape do.

**Describe alternatives you've considered**
Alternative solution for the deletion of the line would be the action similar to that of inkscape that can, with double click, appear an action screen where you can change the position or delete the line and another way would be the already mentioned, that of clicking on the line, it changes color and then the user clicks the delete button. 

**Additional context**

![Example of an inkscape function for the guide line option to erase and position the line. This action appears by double clicking on the line.](https://user-images.githubusercontent.com/47113005/169719558-9df21777-0fba-4971-aec7-121053393c57.png)
> Example of an inkscape function for the guide line option to erase and position the line. This action appears by double clicking on the line.

For the magnetic lines, I recommend looking at instagram and figma, both have the function. I couldn't record a video because I don't know how to do it on my notebook

**Comment by myfunnyandy** [comment]
Hi @allytiago,

Happy coincidence, just yesterday we published an update that includes the ability to delete guides whithout dragging them. Now if you press supr/del while hovering a guide deletes it.

About the guides magnetism, at Penpot is called "snap to guides". Make sure the option is activated to snap objects to the nearest guide.
![image](https://user-images.githubusercontent.com/708713/170000847-a8f8b58b-015c-4bb0-8d87-48d152dfe927.png)

**Comment by allytiago** [comment]
> 
It's enabled!
Before I created this issue I checked the option. Elements can be magnetically attracted to lines, but lines are not magnetically attracted to element nodes. I even did a test with an element of 135px width and height and when I went to position the line on the sides of the element, they didn't magnetize to be under the element's node, it stayed where the mouse left the line. I had to zoom in and look at the x & y position in the side panel to be able to get the line in the right place.

**Comment by allytiago** [comment]
> Oi@allytiago,
> 
> Feliz coincidência, ainda ontem publicamos uma atualização que inclui a capacidade de excluir guias sem arrastá-los. Agora, se você pressionar supr/del enquanto passa o mouse em um guia, o exclui.
> 
> Sobre o magnetismo dos guias, na Penpot é chamado de "snap to guides". Certifique-se de que a opção esteja ativada para encaixar objetos na guia mais próxima. ![imagem](https://user-images.githubusercontent.com/708713/170000847-a8f8b58b-015c-4bb0-8d87-48d152dfe927.png)

It's enabled!
Before I created this issue I checked the option. Elements can be magnetically attracted to lines, but lines are not magnetically attracted to element nodes. I even did a test with an element of 135px width and height and when I went to position the line on the sides of the element, they didn't magnetize to be under the element's node, it stayed where the mouse left the line. I had to zoom in and look at the x & y position in the side panel to be able to get the line in the right place.

**Comment by soutiagojose** [comment]
> Hi @allytiago,
> 
> Happy coincidence, just yesterday we published an update that includes the ability to delete guides whithout dragging them. Now if you press supr/del while hovering a guide deletes it.
> 
> About the guides magnetism, at Penpot is called "snap to guides". Make sure the option is activated to snap objects to the nearest guide. ![image](https://user-images.githubusercontent.com/708713/170000847-a8f8b58b-015c-4bb0-8d87-48d152dfe927.png)

It's enabled!
Before I created this issue I checked the option. Elements can be magnetically attracted to lines, but lines are not magnetically attracted to element nodes. I even did a test with an element of 135px width and height and when I went to position the line on the sides of the element, they didn't magnetize to be under the element's node, it stayed where the mouse left the line. I had to zoom in and look at the x & y position in the side panel to be able to get the line in the right place.

**Comment by soutiagojose** [comment]
> Hi @allytiago,
> 
> Happy coincidence, just yesterday we published an update that includes the ability to delete guides whithout dragging them. Now if you press supr/del while hovering a guide deletes it.
> 
> About the guides magnetism, at Penpot is called "snap to guides". Make sure the option is activated to snap objects to the nearest guide. ![image](https://user-images.githubusercontent.com/708713/170000847-a8f8b58b-015c-4bb0-8d87-48d152dfe927.png)

It's enabled!
The issue is that the line is not "sticking" to the element nodes in order to have a more precise position. The line is at the base of the "olhometro", which is commonly said here in Brazil for something that was made at the base of our eye, without it being able to have a defined precision.
