### ISSUE TITLE
Alt key not working

### ISSUE THREAD

**Issue by soultipsy** [uxbox/uxbox#1935]
**To Reproduce**

1. Hold alt and adjust the shape size
2. the shape will not be adjusted symmetrically, but fixed in the upper left corner
3. Give the shape a rotation angle, and the symmetric adjustment can be reused again 

**Expected behavior**

Symmetrical resizing when alt key is pressed

**Actual behavior**

Symmetric resizing is not effective
 
**Desktop (please complete the following information):**
- OS :Windows10
- Browser & version :Firefox 100.0.1

**Environment (please complete the following information):**
- SaaS (https://design.penpot.app)

**Comment by myfunnyandy** [comment]
Hi @soultipsy,

We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/3447) to track this issue from here. Hopefully, it will be fixed soon. 

Thanks for the report.
