### ISSUE TITLE
[ BUG ] SVGs are not using the correct colors, misaligned text, and imported artboards width and height set to 0.01

### ISSUE THREAD

**Issue by do-kevin** [uxbox/uxbox#1936]
Hi, was there an update today? Some of the text became misaligned and the SVGs are not showing the colors that were set for them on my artboards. I've tried changing the color back and forth, but that did not work.

##### ARTBOARD UNSELECTED :
![svg color bug](https://user-images.githubusercontent.com/40156784/169935040-106579fd-5a0b-47ff-90e9-4b181ff672e9.PNG)

##### SELECTED :
![select artboard](https://user-images.githubusercontent.com/40156784/169934995-e1626893-539d-4da3-bb0a-78c26daf1822.PNG) 

##### SVG not using color that was set:
![Capture 1](https://user-images.githubusercontent.com/40156784/169934968-1ba6b50c-0205-4001-bd0f-88fc0ba12e04.PNG)
![Capture 2](https://user-images.githubusercontent.com/40156784/169934978-46637aa2-0271-47af-a406-ad408cc1237d.PNG)
![Capture 3](https://user-images.githubusercontent.com/40156784/169934992-a1e9c8ec-1d3d-4e99-8497-627c70e962b0.PNG)

I had a day old Penpot file of this, so I decided to try importing it to see if it fixes the colors. The colors in the imported Penpot were being shown correctly, but I encountered **another issue where half of my artboards' width and height were set to 0.01**.

So far, what seems to work well is re-importing my SVG assets and the SVGs were able to change their fill color. However, that means I'll have to replace all of my SVGs in my artboards.

**Comment by superalex** [comment]
Hello @do-kevin 

Yesterday we did and update yes, and I think we probably introduced a bug when rendering external svgs. Could you please include here a .penpot problematic file so we can try to reproduce it? (if you are using design.penpot.app you can also include just the problematic url). We will try to fix this as soon as possible. Sorry for the inconvenience :(

**Comment by do-kevin** [comment]
> Hello @do-kevin
> 
> Yesterday we did and update yes, and I think we probably introduced a bug when rendering external svgs. Could you please include here a .penpot problematic file so we can try to reproduce it? (if you are using design.penpot.app you can also include just the problematic url). We will try to fix this as soon as possible. Sorry for the inconvenience :(

I would love to. But ah, this is work for a company. Where can I privately send you the Penpot links? I've got two Penpot links with the issues separated.

**Comment by superalex** [comment]
@do-kevin you can write to support@penpot.app with the info, thanks!

**Comment by do-kevin** [comment]
@superalex All righty, I've sent the email to support. Please let me know when the issues are resolved, so I can delete the links later. Thanks.

**Comment by jsmorabito** [comment]
I'm also experiencing svg color issues after the update, please let me know what I can share to help if anything is needed

**Comment by superalex** [comment]
Hello @do-kevin and @jsmorabito we've just deployed a new version to https://design.penpot.app solving all the issues @do-kevin detected (and some more). 

@jsmorabito if you detect something is still wrong just let us know and we will try to fix it as soon as possible ;)

Regards,

**Comment by jsmorabito** [comment]
I'm seeing faint lines on my svg which are not related to the stroke...I don't think:

On the canvas:
![image](https://user-images.githubusercontent.com/46250921/170831484-4b26d254-6660-4c21-ba4e-519fc8147cea.png)

![image](https://user-images.githubusercontent.com/46250921/170831513-90165453-3211-4a4e-8160-136d62c8702b.png)

Exported PNG:
![Artboard-1-3](https://user-images.githubusercontent.com/46250921/170831521-aefc6edc-4f9f-4310-9a73-8db9c0870023.png)


Am I doing something wrong? I don't expect those lines to appear there...

**Comment by superalex** [comment]
@jsmorabito could you plese include here an exported .penpot file we could use to reproduce the problem?

Thanks

**Comment by jsmorabito** [comment]
@superalex sent it to support@penpot.app 👍

**Comment by superalex** [comment]
Thanks @jsmorabito 

I'm not seeing those lines, what browser/version and operative system are you using?

![1](https://user-images.githubusercontent.com/1579633/171439950-48d8b042-f9aa-4dc7-ae4b-4cc2ab9eaeb7.png)


By the way, are you using https://design.penpot.app or your onw instance?

**Comment by jsmorabito** [comment]
I am using design.penpot.app on the latest versions of brave and safari on macOS Monterey 12.4

The lines appear in both browsers @superalex

**Comment by superalex** [comment]
@jsmorabito could you please check if it happens too in chrome?

**Comment by superalex** [comment]
@jsmorabito I think I found the problem, the SVG you pasted include a fill and a stroke with the value "currentColor":

![image](https://user-images.githubusercontent.com/1579633/171580133-ac19a25b-c0b0-4565-b635-daae22b3827a.png)

If you remove them the lines will disappear:

![1](https://user-images.githubusercontent.com/1579633/171580306-6053e395-8db4-47ad-9e7c-17784e2ca2cf.png)

**Comment by jsmorabito** [comment]
@superalex YES!! I was not aware of that menu item. Thank you so much 🙏

**Comment by superalex** [comment]
You are welcome @jsmorabito ! :D
