### ISSUE TITLE
Lithuanian Language on Weblate

### ISSUE THREAD

**Issue by vinkas** [uxbox/uxbox#1938]
Hello,

I would like to ask to add a Lithuanian language on projects Weblate. My user name is @dundzys.vincas

**Comment by myfunnyandy** [comment]
Hi @vinkas!

We've already added you to the translation project and also the Lithuanian language at the languages list. It always makes us really happy to add a new language! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/lt/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
