### ISSUE TITLE
Group paste

### ISSUE THREAD

**Issue by catcargos** [uxbox/uxbox#1946]
**To Reproduce**

I have two frames in Figma
![image](https://user-images.githubusercontent.com/102146431/170049710-19fdae82-5382-4b45-9922-13f5959e2410.png)

1.  Select two frames (groups) in Figma.
2.  Copy selected groups as SVG
3.  Paste it to Penpot.

**Expected behavior**
I have two separate groups of elements as in Figma

**Actual behavior**
I have one group of a paths.
![image](https://user-images.githubusercontent.com/102146431/170050256-5f5438fe-a1a1-4d72-b03d-ed8a4f657bfa.png)
 
**Screenshots**

In figma:
![image](https://user-images.githubusercontent.com/102146431/170050395-419b08dd-5fd9-4dd5-9224-bbd0117d7041.png)
![image](https://user-images.githubusercontent.com/102146431/170050504-fa5e87c9-d983-4840-8a87-173a3529ec19.png)

In Penpot:
![image](https://user-images.githubusercontent.com/102146431/170050611-6757edb5-e7b5-4cff-946f-b81532c26321.png)
![image](https://user-images.githubusercontent.com/102146431/170050660-1284f8bc-1a1f-410c-af25-427d1b133c61.png)

**Comment by EsterLatorre** [comment]
Hello Catcargos 
SVG doesn't contain all of the information for it to appear in separate groups, so it's normal behavior. It's in our roadmap to improve importation from Figma, so that will solve the issue.
Thanks for the report :)
