### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#1952]
**Is your feature request related to a problem? Please describe.**
Smartphones are getting bigger and more powerful screens and the vast majority of similar software, or if not all, do not have full support for mobile devices. Figma only has the preview, Gravit Designer has a limited version for touch and so far only photopea has its software friendly for mobile devices.

**Describe the solution you'd like**
I believe that if the penpot has a photopea-like responsive adaptation, it will be able to bring its potential to mobile devices. At first it doesn't have to be everything, it can be something that makes it possible to create posts for social media, or edit the posts, make quick adjustments to the components, colors, typography, fonts...

**Describe alternatives you've considered**
You can look at photopea.com, it's the friendliest software I know.

**Comment by EsterLatorre** [comment]
Hi allytiago, 
We already have improvements planned for mobile but they are not yet prioritized. We will take your suggestions into consideration once we start working on them. 
Thanks for your feedback!

**Comment by jdittrich** [comment]
I think it makes sense to have penpot working on tablets (or generally: touch displays) as the same UI could probably used with some tweaks. I assume a fully phone compatible UI woud need a lot of changes (compare e.g. mobile google docs with the web version) and might have limited use.

**Comment by soutiagojose** [comment]
> I think it makes sense to have penpot working on tablets (or generally: touch displays) as the same UI could probably used with some tweaks. I assume a fully phone compatible UI woud need a lot of changes (compare e.g. mobile google docs with the web version) and might have limited use. 

There is a web app similar to Photoshop, an alternative in this case, Photopea, it is a web app developed to work in the desktop browser, but it is highly responsive and you can edit or create something using it on a cell phone or tablet

**Comment by StefanFW** [comment]
in my opinion the feature with the smallest effort but with the most improvement is a responsive version of the view screen wich could be shared with others.

If I open such a link on a phone or tablet, part of the content is invisible and not scrollable.

**Comment by jdittrich** [comment]
@schnes4: Maybe create a separate issues for "responsive version of prototype view screen"? That probably makes it easier to scope for the developers/product manager

**Comment by Alotor** [comment]
A responsive version of the view screen is already in our backlog. We hope to do it soon but we basically are doing our best to prioritize functionality. But the accessibility is one of our focuses in medium term and this would be one of the firsts steps.

**Comment by niwinz** [comment]
This issue is very general and many different appraches are already tracked internally.

I close the issue for now because we dont want having it open with no clear objective or how to track this. Feel free to open more concrete enhacement if you want. In any case, thanks for suggesting and opening the discussion.
