### ISSUE TITLE
How do I translate the penpot?

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#1953]
**Is your feature request related to a problem? Please describe.**
I see that the Portuguese version of it is not complete and with some errors and I think it can be improved

**Describe the solution you'd like**
If there is any translation tool, I would like to contribute in my spare time by translating some words.

**Comment by myfunnyandy** [comment]
Hi @allytiago, 

We'd love you to help us with portuguese translations. The only thing we need to grant you permissions to edit translations is your [Weblate](https://weblate.org/) username. Once we have this we will add you to the project as soon as we can. Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thanks!

**Comment by allytiago** [comment]
My user is @allytiago in the weblate

**Comment by soutiagojose** [comment]
> Hi @allytiago,
> 
> We'd love you to help us with portuguese translations. The only thing we need to grant you permissions to edit translations is your [Weblate](https://weblate.org/) username. Once we have this we will add you to the project as soon as we can. Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/
> 
> Thanks!

My user is @allytiago in the weblate

**Comment by myfunnyandy** [comment]
Hi @allytiago, my apologies, I missed your reply and just read it. You've been already added to the weblate project, I hope you are still willing to contribute with the translations. Thanks!
