### ISSUE TITLE
TLS error while sendmail job

### ISSUE THREAD

**Issue by wafelmolt** [uxbox/uxbox#1959]
Context:
Having a SMTP server with starttls configured on port 587 with a self-signed certificate.

When penpot is trying to mailing my coworkers, the following error occurs :

> [2022-05-26 16:45:49.472] D app.worker - action="execute task" id="4458a520-dd13-11ec-bef6-ebeeee861e81" name="sendmail" retry="1"
> 
> [2022-05-26 16:45:49.506] E app.worker - hint="unhandled exception on task"
> 
> jakarta.mail.MessagingException: Could not convert socket to TLS
> 
> 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2140) ~[penpot.jar:?]
> 
> 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:734) ~[penpot.jar:?]
> 
> 	at jakarta.mail.Service.connect(Service.java:342) ~[penpot.jar:?]
> 
> 	at jakarta.mail.Service.connect(Service.java:222) ~[penpot.jar:?]
> 
> 	at jakarta.mail.Service.connect(Service.java:243) ~[penpot.jar:?]
> 
> 	at jakarta.mail.Transport.send0(Transport.java:228) ~[penpot.jar:?]
> 
> 	at jakarta.mail.Transport.send(Transport.java:150) ~[penpot.jar:?]
> 
> 	at app.util.emails$send_BANG_.invokeStatic(emails.clj:170) ~[penpot.jar:?]
> 
> 	at app.util.emails$send_BANG_.invoke(emails.clj:167) ~[penpot.jar:?]
> 
> 	at app.emails$fn__24894$fn__24896.invoke(emails.clj:170) ~[penpot.jar:?]
> 
> 	at app.worker$wrap_task_handler$fn__22516.invoke(worker.clj:519) ~[penpot.jar:?]
> 
> 	at app.worker$handle_task.invokeStatic(worker.clj:311) ~[penpot.jar:?]
> 
> 	at app.worker$handle_task.invoke(worker.clj:307) ~[penpot.jar:?]
> 
> 	at app.worker$run_task.invokeStatic(worker.clj:356) ~[penpot.jar:?]
> 
> 	at app.worker$run_task.invoke(worker.clj:348) ~[penpot.jar:?]
> 
> 	at clojure.core$partial$fn__5859.invoke(core.clj:2634) ~[penpot.jar:?]
> 
> 	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
> 
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
> 
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
> 
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
> 
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
> 
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
> 
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
> 
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
> 
> Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 
> 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
> 
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
> 
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
> 
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
> 
> 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
> 
> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
> 
> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
> 
> 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
> 
> 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1497) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1403) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
> 
> 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[penpot.jar:?]
> 
> 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[penpot.jar:?]
> 
> 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[penpot.jar:?]
> 
> 	... 23 more
> 
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439) ~[?:?]
> 
> 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
> 
> 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
> 
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[?:?]
> 
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
> 
> 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
> 
> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
> 
> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
> 
> 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
> 
> 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1497) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1403) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
> 
> 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[penpot.jar:?]
> 
> 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[penpot.jar:?]
> 
> 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[penpot.jar:?]
> 
> 	... 23 more
> 
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 
> 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:?]
> 
> 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:?]
> 
> 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
> 
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[?:?]
> 
> 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
> 
> 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
> 
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[?:?]
> 
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[?:?]
> 
> 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[?:?]
> 
> 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
> 
> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
> 
> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
> 
> 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
> 
> 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1497) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1403) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
> 
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
> 
> 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602) ~[penpot.jar:?]
> 
> 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:529) ~[penpot.jar:?]
> 
> 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:2135) ~[penpot.jar:?]
> 
> 	... 23 more

So, I assume there must be a way to get the CA certificate imported into the java trust store. What would it be?

**Comment by hirunatan** [comment]
@TurboGofre you are true. It seems that you need to install the certificate into the Java environment.

I'm not an expert, but think it can be done with the `keytool` command:

https://www.java67.com/2019/06/javaxnetsslsslhandshakeexception-PKIX-path-building-failed-ssl-certificate.html

If it does not work, here is a discussion of other ways:

https://stackoverflow.com/questions/6659360/how-to-solve-javax-net-ssl-sslhandshakeexception-error

**Comment by wafelmolt** [comment]
Hi @hirunatan.

I did try with keytool but the utility tell me that there is no existing keystore.
I guess or it is true, or I might be doing something wrong with the CLI.

I'll send here soon the keytool command I tried as I don't have access to my main computer now.

**Comment by wafelmolt** [comment]
@hirunatan Hello. I did use the keytool import command but without success because it is asking me to enter a password to access the truststore.

**Comment by wafelmolt** [comment]
@hirunatan Ok it seams the default password is "changeit". I've been able to import my CA cert and now it's working fine.

For those who would end up in the same situation :
You must use
keytool -import -alias "my.mail.server.example" -storepass changeit -noprompt -file /tmp/ca.crt -cacerts

With /tmp/ca.crt being the plain CA certificate of your mail server.

Thx @hirunatan
