### ISSUE TITLE
No images visible on frontend with s3 storage backend on elest.io

### ISSUE THREAD

**Issue by prononext** [uxbox/uxbox#1967]
Images are not shown when using s3 storage backend. Maybe someone has a clue if there is a special bucket policy or setting to get that working. My bucket is created as standard with no settings changed, after that the IAM user is created with the policy referenced below. 

**To Reproduce**
1.  Go to elest.io
2.  Click on create a new Penpot instance
3. on aws s3 create a new bucket
4. on aws IAM create a user with full permissions on that bucket
5.  change the config env and add (with your individual data from aws iam and s3)

`# AWS Credentials
AWS_ACCESS_KEY_ID=<you-access-key-id-here>
AWS_SECRET_ACCESS_KEY=<your-secret-access-key-here>

# Backend configuration
PENPOT_ASSETS_STORAGE_BACKEND=assets-s3
PENPOT_STORAGE_ASSETS_S3_REGION=<aws-region>
PENPOT_STORAGE_ASSETS_S3_BUCKET=<bucket-name>`

6. restart instance and login to frontend and open a new file. 
7. drag and drop a image to the file 

**Expected behavior**

image is shown on frontend inside the file you are editing and also uploaded to s3

**Actual behavior**

The dragged image is not shown on the penpot frontnend
Some data is added to s3 in unreadable format
 
**Screenshots**

![image](https://user-images.githubusercontent.com/24569958/171411586-34693c39-cb21-43c0-b02a-df78597f02b7.png)

**Desktop :**
- latest Chrome and Firefox 

**Environment :**
- elest.io Inatance
 - Ubuntu Server 22

**AWS-IAM-Bucket-Permission-Policy:**

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutAnalyticsConfiguration",
                "s3:GetObjectVersionTagging",
                "s3:CreateBucket",
                "s3:ReplicateObject",
                "s3:GetObjectAcl",
                "s3:GetBucketObjectLockConfiguration",
                "s3:DeleteBucketWebsite",
                "s3:GetIntelligentTieringConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:GetObjectVersionAcl",
                "s3:PutBucketAcl",
                "s3:PutObjectTagging",
                "s3:DeleteObject",
                "s3:DeleteObjectTagging",
                "s3:GetBucketPolicyStatus",
                "s3:GetObjectRetention",
                "s3:GetBucketWebsite",
                "s3:PutReplicationConfiguration",
                "s3:DeleteObjectVersionTagging",
                "s3:PutObjectLegalHold",
                "s3:GetObjectLegalHold",
                "s3:GetBucketNotification",
                "s3:PutBucketCORS",
                "s3:DeleteBucketPolicy",
                "s3:GetReplicationConfiguration",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:GetObject",
                "s3:PutBucketNotification",
                "s3:PutBucketLogging",
                "s3:PutObjectVersionAcl",
                "s3:GetAnalyticsConfiguration",
                "s3:PutBucketObjectLockConfiguration",
                "s3:GetObjectVersionForReplication",
                "s3:GetLifecycleConfiguration",
                "s3:GetInventoryConfiguration",
                "s3:GetBucketTagging",
                "s3:PutAccelerateConfiguration",
                "s3:DeleteObjectVersion",
                "s3:GetBucketLogging",
                "s3:ListBucketVersions",
                "s3:ReplicateTags",
                "s3:RestoreObject",
                "s3:ListBucket",
                "s3:GetAccelerateConfiguration",
                "s3:GetBucketPolicy",
                "s3:PutEncryptionConfiguration",
                "s3:GetEncryptionConfiguration",
                "s3:GetObjectVersionTorrent",
                "s3:AbortMultipartUpload",
                "s3:PutBucketTagging",
                "s3:GetBucketRequestPayment",
                "s3:DeleteBucketOwnershipControls",
                "s3:GetObjectTagging",
                "s3:GetMetricsConfiguration",
                "s3:GetBucketOwnershipControls",
                "s3:DeleteBucket",
                "s3:PutBucketVersioning",
                "s3:PutObjectAcl",
                "s3:GetBucketPublicAccessBlock",
                "s3:ListBucketMultipartUploads",
                "s3:PutBucketPublicAccessBlock",
                "s3:PutIntelligentTieringConfiguration",
                "s3:PutMetricsConfiguration",
                "s3:PutBucketOwnershipControls",
                "s3:PutObjectVersionTagging",
                "s3:GetBucketVersioning",
                "s3:GetBucketAcl",
                "s3:BypassGovernanceRetention",
                "s3:PutInventoryConfiguration",
                "s3:GetObjectTorrent",
                "s3:ObjectOwnerOverrideToBucketOwner",
                "s3:PutBucketWebsite",
                "s3:PutBucketRequestPayment",
                "s3:PutObjectRetention",
                "s3:GetBucketCORS",
                "s3:PutBucketPolicy",
                "s3:GetBucketLocation",
                "s3:ReplicateDelete",
                "s3:GetObjectVersion"
            ],
            "Resource": [
                "arn:aws:s3:::penpot-bucket/*",
                "arn:aws:s3:::penpot-bucket"
            ]
        }
    ]
}`

**Comment by myfunnyandy** [comment]
Hi @prononext, we are currently taking a look at this, it seems to be something related to the configuration.

 Is it still happening to you? It could have been alrady fixed by Elestio.

**Comment by prononext** [comment]
Hi, sadly nothing got fixed by elastio. Also repeating the described process did not change the behavior. 

Here is the config used: 

### **ENV:** 

SOFTWARE_PASSWORD=xxxxxxxxxxxxxxxx
SOFTWARE_VERSION_TAG=latest
PENPOT_PUBLIC_URI=http://penpot.example.com

PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
PENPOT_DATABASE_USERNAME=penpot
PENPOT_DATABASE_PASSWORD=penpot

PENPOT_REDIS_URI=redis://penpot-redis/0

AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxx

PENPOT_ASSETS_STORAGE_BACKEND=assets-s3
PENPOT_STORAGE_ASSETS_S3_REGION=eu-central-1
PENPOT_STORAGE_ASSETS_S3_BUCKET=xxxxxxxxxxxxxxxxxxxxxxxxxxx

PENPOT_TELEMETRY_ENABLED=false

PENPOT_SMTP_ENABLED=true
PENPOT_SMTP_DEFAULT_FROM=xxxxxxxxxxxxxx
PENPOT_SMTP_DEFAULT_REPLY_TO=xxxxxxxxxxxxxxxxxxxxx
PENPOT_SMTP_HOST=xxxxxxxxxxxxxxxxx
PENPOT_SMTP_PORT=587
PENPOT_SMTP_USERNAME=xxxxxxxxxxxxxxxxxxxx
PENPOT_SMTP_PASSWORD=xxxxxxxxxxxxxxxxxxxxxx
PENPOT_SMTP_TLS=true
PENPOT_SMTP_SSL=true

PENPOT_REGISTRATION_ENABLED=false


### **DOCKER-COMPOSE:**

version: "3.5"

networks:
  penpot:

services:
  penpot-frontend:
    image: "penpotapp/frontend:${SOFTWARE_VERSION_TAG}"
    container_name: penpot-frontend
    ports:
      - 172.17.0.1:8080:80

    volumes:
      - ./penpot_assets_data:/opt/data

    env_file:
      - .env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:${SOFTWARE_VERSION_TAG}"
    container_name: penpot-backend
    volumes:
      - ./penpot_assets_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - .env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:${SOFTWARE_VERSION_TAG}"
    container_name: penpot-exporter
    environment:

      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    container_name: penpot-postgres
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=${SOFTWARE_PASSWORD}

    volumes:
      - ./penpot_postgres_data:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:6
    container_name: penpot-redis
    restart: always
    networks:
      - penpot

**Comment by superalex** [comment]
hello @prononext 

Some ideas:
- I've seen there is no PENPOT_STORAGE_ASSETS_FS_DIRECTORY in your env file, could you please try including it too? (PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets)
- Did you check the logs tab a elest.io to see if there is some important info when you upload an image?

**Comment by prononext** [comment]
Just tried that and added: 

(PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets

to the ENV file, but nothing changed. 

When restarting the image after config update there are many logs like this, but they have been there before, without any config change: 

penpot-exporter    | WRN [app.redis] hint="connection closed"
penpot-exporter    | SEV [app.redis] hint="error on redis connection"
penpot-exporter    | Error: getaddrinfo EAI_AGAIN redis
penpot-exporter    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
penpot-exporter    | WRN [app.redis] hint="connection closed"
penpot-exporter    | SEV [app.redis] hint="error on redis connection"
penpot-exporter    | Error: getaddrinfo EAI_AGAIN redis
penpot-exporter    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
penpot-exporter    | WRN [app.redis] hint="connection closed"

**Comment by niwinz** [comment]
After analyzing the cause of this, I found the following issues:
- Our docker image does not correctly setups the resolver on nginx that causes the S3 image retrieval issue, so we need to fix it in our next version images.
- The connection closed error happens on restarting so it is correct to see it on the logs.
- the main env file used in elestio is not updated so we need to fix it.

This is just a follow-up message, we are already working on fixing it.

**Comment by niwinz** [comment]
Hello @prononext 

Some update here:
- The issue with our image is fixed, we pushed again the latest. In this case, you will need to pull the new image and restart. The pull can be done manually entering in the VM terminal and executing `docker-compose pull` and `docker-compose up -d`. Or probably using the **UPDATE** button on the elest.io admin UI.

- Additionally, the configuration that elest.io is using and setting up for all instances is a little bit outdated. You can ensure that you have the updated configuration comparing yours with the files that I leave attached to this issue. Mainly look on the YAML file the `penpot-exporter` section and the FLAGS stuff on the ENV file. (*We're going to contact with elestio for fix this*)

[elestio-sample.env.txt](https://github.com/penpot/penpot/files/8896991/elestio-sample.env.txt)
[elestio-sample.yml.txt](https://github.com/penpot/penpot/files/8896992/elestio-sample.yml.txt)

**Comment by niwinz** [comment]
I close this issue, if you still has problem with this, feel free to reopen it.
