### ISSUE TITLE
E-Mail Customization - Content and Design

### ISSUE THREAD

**Issue by prononext** [uxbox/uxbox#1968]
**It would be really nice to have the possibility to customize the emails which are being sent out from a Penpot instance besides from the sending and reply address.** 

- E-Mail HTML Version
- E-Mail TEXT Version

- E-Mail Footer
- E-Mail Header

Thank you very much for that beautiful software!

**Comment by elhombretecla** [comment]
Hi @prononext thank you so much for your words and feedback

We will review your suggestion and prioritize it
[https://tree.taiga.io/project/penpot/issue/3502](https://tree.taiga.io/project/penpot/issue/3502)
