### ISSUE TITLE
Multi selection not working inside a group in graphics assets

### ISSUE THREAD

**Issue by Klarr-Agency** [uxbox/uxbox#1977]
**To Reproduce**

1.  Select multiple elements in the graphics section
2.  Create a group
3.  Try to select more than one element inside that group

**Expected behavior**

I expect to select multiple elements when holding shift.

**Actual behavior**

When I click on another element when holding shift it keep saying "1 item selected"
 
**Screenshots**
![image](https://user-images.githubusercontent.com/87146097/171880347-859b4c7b-f085-4e29-bef0-a5ccc344692e.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): MacOS 10.14.2
- Browser & version (e.g. Chrome 89.0): Chrome  102.0.5005.61

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): https://design.penpot.app/

**Comment by myfunnyandy** [comment]
Hi!
We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/3532) to track this issue from here. Hopefully, it will be fixed soon. 
Thanks for the report.

**Comment by Klarr-Agency** [comment]
Thanks you! 😄
