### ISSUE TITLE
Cannot log into Penpot on fresh docker install.

### ISSUE THREAD

**Issue by piqueza** [uxbox/uxbox#1979]
**To Reproduce**

1.  Install penpot with docker, make no config changes to config.env
2.  Create user with: docker exec -ti penpot-penpot-backend-1 ./manage.sh create-profile
3.  Use details to log in, get message: "Username or password seems to be wrong."
4. Decide to enable smtp, and set that up. Rebuild docker image.
5. Create account via frontend, get token image to activate account.
6. Get same error message: Username or password seems to be wrong.

**Expected behavior**
Creating account should allow user to log into penpot.

**Actual behavior**
Penpot does not allow login, claims: Username or password seems to be wrong.

**Screenshots**
![image](https://user-images.githubusercontent.com/64781143/172133315-e95736d9-588e-4199-9e18-12fbf3b2e3fe.png)
(Note email address and other info redacted)

![image](https://user-images.githubusercontent.com/64781143/172133422-8c558784-b72c-4b16-aff2-b7199dab4e80.png)
(Note email address redacted)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows 11
- Browser & version (e.g. Chrome 89.0): Chrome Version 102.0.5005.63 (Official Build) (64-bit)

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): local instance, self hosted.

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04): Debian 10
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24): Docker Compose version v2.5.0
- 
**Additional context:**

Could be related to https://github.com/penpot/penpot/issues/1784 since the behavior is similar, but could not add extra comment since that issue is closed.

**Comment by superalex** [comment]
Hello @piqueza 

I've just tried this and it's working perfecly, did you try setting a password only with "normal" characters (just to test if there can be any enconding issues when you type the password)

**Comment by piqueza** [comment]
> Hello @piqueza
> 
> I've just tried this and it's working perfecly, did you try setting a password only with "normal" characters (just to test if there can be any enconding issues when you type the password)

Hey @superalex 

No special characters, all lowercase and no numbers. It's kinda my default way of doing things when working with new software precisely because my super special password could cause issues with brackets and whatnot in the password.

Can you give me an example config.env that I can compare with mine? Maybe there is another setting that is causing the issue, for instance I left it on localhost:9001 as I did not care to change the url yet. I log in on http://ipaddress:9001 though, so maybe that is the cause?

**Comment by superalex** [comment]
@piqueza I'm using as https://raw.githubusercontent.com/penpot/penpot/main/docker/images/config.env detailed at https://help.penpot.app/technical-guide/getting-started/#install-docker and I'm accessing using ipaddress:9001 too

**Comment by piqueza** [comment]
Thanks @superalex 

I tried a few changes on my side with no luck, and then put penpot behind an ssl proxy (nginx https > http://$ipaddress:9001 and now logins work.

It definitely seems to be an http/https problem which was discussed in the linked but now closed bug report in my original post.

I am willing to build another server from scratch tomorrow and follow exactly the steps in the technical guide if you want me to double check?

In fact, the moment I remove the https > http redirect it stops allowing me to log in. Could it be the secure cookies setting that needs to be changed?

Let me know if you want me to guinea pig a test install for you.

**Comment by prononext** [comment]
had the same problem, until today no solution found...

**Comment by superalex** [comment]
@piqueza @vintprox could you please show the config.env you are using?

**Comment by piqueza** [comment]
Gladly. I redacted hostnames and passwords only.

`root@penpot:~# cat config.env`
`# Should be set to the public domain where penpot is going to be served.`
`PENPOT_PUBLIC_URI=http://penpot.xxx.domain`
`PENPOT_TENANT=pro`

`# Temporal workaround because of bad builtin default`
`PENPOT_HTTP_SERVER_HOST=0.0.0.0`

`# Standard database connection parameters (only postgresql is supported):`
`PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot`
`PENPOT_DATABASE_USERNAME=penpot`
`PENPOT_DATABASE_PASSWORD=penpot`

`# Redis is used for the websockets notifications.`
`PENPOT_REDIS_URI=redis://penpot-redis/0`

`# By default, files uploaded by users are stored in local filesystem. But it`
`# can be configured to store in AWS S3 or completely in de the database.`
`# Storing in the database makes the backups more easy but will make access to`
`# media less performant.`
`PENPOT_ASSETS_STORAGE_BACKEND=assets-fs`
`PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets`

`# Telemetry. When enabled, a periodical process will send anonymous data about`
`# this instance. Telemetry data will enable us to learn on how the application`
`# is used, based on real scenarios. If you want to help us, please leave it`
`# enabled.`
`PENPOT_TELEMETRY_ENABLED=true`

`# Email sending configuration. By default, emails are printed in the console,`
`# but for production usage is recommended to setup a real SMTP provider. Emails`
`#are used to confirm user registrations.`
`PENPOT_SMTP_ENABLED=true`
`PENPOT_SMTP_DEFAULT_FROM=penpot@xxx.domain`
`PENPOT_SMTP_DEFAULT_REPLY_TO=penpot@xxx.domain`
`PENPOT_SMTP_HOST=smtp.xxx.domain`
`PENPOT_SMTP_PORT=25`
`PENPOT_SMTP_USERNAME=xxx.username.xxx`
`PENPOT_SMTP_PASSWORD=xxx.password.xxx`
`# PENPOT_SMTP_TLS=true`
`# PENPOT_SMTP_SSL=false`

`# Feature flags. Right now they are only affect frontend, but in`
`# future release they will affect to both backend and frontend.`
`PENPOT_FLAGS="enable-registration"`

`# Comma separated list of allowed domains to register. Empty to allow all.`
`# PENPOT_REGISTRATION_DOMAIN_WHITELIST=""`

`## Authentication providers`

`# Google`
`# PENPOT_GOOGLE_CLIENT_ID=`
`# PENPOT_GOOGLE_CLIENT_SECRET=`

`# GitHub`
`# PENPOT_GITHUB_CLIENT_ID=`
`# PENPOT_GITHUB_CLIENT_SECRET=`

`# GitLab`
`# PENPOT_GITLAB_BASE_URI=https://gitlab.com`
`# PENPOT_GITLAB_CLIENT_ID=`
`# PENPOT_GITLAB_CLIENT_SECRET=`

`# OpenID Connect (since 1.5.0)`
`# PENPOT_OIDC_BASE_URI=`
`# PENPOT_OIDC_CLIENT_ID=`
`# PENPOT_OIDC_CLIENT_SECRET=`

`# LDAP`
`# PENPOT_LDAP_HOST=ldap`
`# PENPOT_LDAP_PORT=10389`
`# PENPOT_LDAP_SSL=false`
`# PENPOT_LDAP_STARTTLS=false`
`# PENPOT_LDAP_BASE_DN=ou=people,dc=planetexpress,dc=com`
`# PENPOT_LDAP_BIND_DN=cn=admin,dc=planetexpress,dc=com`
`# PENPOT_LDAP_BIND_PASSWORD=GoodNewsEveryone`
`# PENPOT_LDAP_ATTRS_USERNAME=uid`
`# PENPOT_LDAP_ATTRS_EMAIL=mail`
`# PENPOT_LDAP_ATTRS_FULLNAME=cn`
`# PENPOT_LDAP_ATTRS_PHOTO=jpegPhoto`
`# PENPOT_LOGIN_WITH_LDAP=true`

**Comment by superalex** [comment]
@piqueza in your file I can read "ENPOT_PUBLIC_URI" is it an error copy pasting?

**Comment by piqueza** [comment]
> @piqueza in your file I can read "ENPOT_PUBLIC_URI" is it an error copy pasting?

@superalex yeah, I had to figure out how to properly format the code and probably accidentally deleted the P.

Updated the comment to correct it.

**Comment by superalex** [comment]
Ok @piqueza so your problem only happens if you are using http://penpot.xxx.domain (without https). In that case you should add disable-secure-session-cookies to PENPOT_FLAGS

```
PENPOT_FLAGS="enable-registration disable-secure-session-cookies"
```

**Comment by piqueza** [comment]
Ok thanks. I think it should be included in the install guide.

**Comment by superalex** [comment]
I totally agrre :)

**Comment by JonathanStrangeHelium** [comment]
> Hello @piqueza
> 
> I've just tried this and it's working perfecly, did you try setting a password only with "normal" characters (just to test if there can be any enconding issues when you type the password)

I've tried password like "123456".  had the same problem, until today no solution found...

**Comment by JonathanStrangeHelium** [comment]
![图片](https://user-images.githubusercontent.com/26567451/176855759-313ecbe9-4f21-483e-8afe-ce5df14aaa4e.png)
login response status is 200, 
But,
Actual behavior
Penpot does not allow login, claims: Username or password seems to be wrong.

**Comment by JonathanStrangeHelium** [comment]
> Ok @piqueza so your problem only happens if you are using http://penpot.xxx.domain (without https). In that case you should add disable-secure-session-cookies to PENPOT_FLAGS
> 
> ```
> PENPOT_FLAGS="enable-registration disable-secure-session-cookies"
> ```

thanks a lot

**Comment by piqueza** [comment]
> > Ok @piqueza so your problem only happens if you are using http://penpot.xxx.domain (without https). In that case you should add disable-secure-session-cookies to PENPOT_FLAGS
> > ```
> > PENPOT_FLAGS="enable-registration disable-secure-session-cookies"
> > ```
> 
> thanks a lot

I got it working by putting penpot behind an NGINX proxy with a letsencrypt SSL cert.

**Comment by IcedQuinn** [comment]
Just got bit by this today. The docker repo doesn't mention it in the .env file and the front-end doesn't give any indication there is an SSL problem. Setting the flags worked.

Sort of seems like the UI should be more specific about this error mode eh

**Comment by kenmlee** [comment]
I think there is a bug in entrypoint.sh script.

When I put next line in config.env:
`PENPOT_FLAGS="enable-registration disable-secure-session-cookies"`

After penpot-frontend container started, the file '/var/www/app/js/config.js' will be:
`var penpotFlags = ""enable-registration disable-secure-session-cookies"";`

**pay attention to the extra double quotes.**

So, I changed line in config.env to (from double-quotes to single-quotes):
`PENPOT_FLAGS='enable-registration disable-secure-session-cookies'`

After restart penpot-frontend, 'config.js' changed to:
`var penpotFlags = "'enable-registration disable-secure-session-cookies'"`

Maybe your case is different to my case. But it just work for me.

**Comment by niwinz** [comment]
Are you using docker-compose (v1) or `docker compose` (v2)
I guess you are using docker-compose (v1), and is not a bug in entrypoint.sh is a bug on how the legacy docker-compose v1 handles environment variables.

You have two options: switch to use `docker compose` v2 or update config.env and remove all `"` chars from configuration

**Comment by kenmlee** [comment]
> Are you using docker-compose (v1) or `docker compose` (v2) I guess you are using docker-compose (v1), and is not a bug in entrypoint.sh is a bug on how the legacy docker-compose v1 handles environment variables.
> 
> You have two options: switch to use `docker compose` v2 or update config.env and remove all `"` chars from configuration

I'm using 'podman pod' not docker.

Working on to run Penpot at my home server with podman and use 'podman generate kube' to generate a k8s yaml file to deploy on K8S.

And yes, removing double-quotes or with single-quotes both work for me.

**Comment by KvizadSaderah** [comment]
i'm so lost with this docker-compose file...
Can anyone share valid config for deploying it on domain like "example.com"?
Without any your's private data of course. 

30 mins of editing like a mom's hacker, and when i run it...

`ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yaml", line 2, column 1
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yaml", line 38, column 3`

**Comment by promachines** [comment]
Hi everyone 

I had some issues creating  a user on a fresh docker penpot installation. Running a command 
**docker exec -ti penpot_penpot-backend_1 ./manage.py create-profile** through a console, I've got some errors. Everything is detalied below with my configuration and docker compose files.

My server ip is 197.168.1.12 running on a ubuntu server and as you can see below flag disable-secure-session-cookies is activated.

My apologise, I don't know if I have to create a new post or not, but reading on github this one is more or less similar to my issue. Thanks you 

**CONSOLE**

root@dwu-server:/home/dwu/penpot# docker exec -ti penpot_penpot-backend_1 ./manage.py create-profile                         
Email: dxxxx@gmail.com                                                                                                               
Fullname: dwu                                                                                                                                 
Password:   xxxxxxx (with letters and numbers)                                                                                                                                 
Traceback (most recent call last):                                                                                                            
  File "/opt/penpot/backend/./manage.py", line 147, in <module>                                                                               
    create_profile(fullname, email, password)                                                                                                 
  File "/opt/penpot/backend/./manage.py", line 79, in create_profile                                                                          
    res = run_cmd(params)                                                                                                                     
  File "/opt/penpot/backend/./manage.py", line 62, in run_cmd                                                                                 
    res, failed = send_eval(expr)                                                                                                             
  File "/opt/penpot/backend/./manage.py", line 41, in send_eval                                                                               
    s.connect((host, port))                                                                                                                   
ConnectionRefusedError: [Errno 111] Connection refused 
 ****


**CONFIG.ENV**
```
 # Should be set to the public domain where penpot is going to be served.                                                                     
 #                                                                                                                                            
 # NOTE: If you are going to serve it under different domain than                                                                             
 #                                                                                                                                           
                                                                                                                                               
 PENPOT_PUBLIC_URI=http://192.168.1.12:9001/                                                                                                    
 PENPOT_TENANT=pro                                                                                                                             
                                                                                                                                               
 # Feature flags.                                                                                                                             
                                                                                                                                               
 # 'localhost' without HTTPS                                                                                                                   
 # PENPOT_FLAGS="enable-registration disable-secure-session-cookies"                                                                           
 PENPOT_FLAGS="disable-registration enable-login disable-secure-session-cookies"                                                                
                                                                                                                                               
 # PENPOT_FLAGS="enable-registration enable-login"                                                                                             
 # PENPOT_FLAGS="disable-registration disable-demo-users"                                                                                      
 # PENPOT_FLAGS="disable-registration enable-login"                                                                                            
                                                                                                                                               
                                                                                                                                               
 ## Temporal workaround because of bad builtin default                                                                                         
                                                                                                                                               
 PENPOT_HTTP_SERVER_HOST=0.0.0.0                                                                                                               
                                                                                                                                               
 # Standard database connection parameters (only postgresql is supported):                                                                    
                                                                                                                                               
 PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot                                                                                       
 PENPOT_DATABASE_USERNAME=penpot                                                                                                               
 PENPOT_DATABASE_PASSWORD=penpot                                                                                                               
                                                                                                                                               
 # Redis is used for the websockets notifications.                                                                                            
                                                                                                                                               
 PENPOT_REDIS_URI=redis://penpot-redis/0                                                                                                       
                                                                                                                                               
 # By default, files uploaded by users are stored in local                                                                                    
 # filesystem. But it can be configured to store in AWS S3.                                                                                   
                                                                                                                                               
 PENPOT_ASSETS_STORAGE_BACKEND=assets-fs                                                                                                       
 PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets                                                                                           
                                                                                                                                               
 # Telemetry. When enabled, a periodical process will send anonymous                                                                          
 # data about this instance. Telemetry data will enable us to learn on                                                                        
 # how the application is used, based on real scenarios. If you want                                                                          
 # to help us, please leave it enabled.                                                                                                       
                                                                                                                                               
 PENPOT_TELEMETRY_ENABLED=true                                                                                                                 
                                                                                                                                               
 # Email sending configuration. By default, emails are printed in the                                                                         
 # console, but for production usage is recommended to setup a real                                                                           
 # SMTP provider. Emails are used to confirm user registrations.                                                                              
                                                                                                                                               
 PENPOT_SMTP_ENABLED=false                                                                                                                     
 PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com                                                                                                 
 PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com                                                                                             
 # PENPOT_SMTP_HOST=                                                                                                                           
 # PENPOT_SMTP_PORT=                                                                                                                           
 # PENPOT_SMTP_USERNAME=                                                                                                                       
 # PENPOT_SMTP_PASSWORD=                                                                                                                       
 # PENPOT_SMTP_TLS=true                                                                                                                        
 # PENPOT_SMTP_SSL=false                                                                                                                       
                                                                                                                                               
 # Comma separated list of allowed domains to register. Empty to allow                                                                        
 # all.                                                                                                                                       
                                                                                                                                               
 # PENPOT_REGISTRATION_DOMAIN_WHITELIST=""                                                                                                     
                                                                                                                                               
 # Authentication providers                                                                                                                   
                                                                                                                                               
 # Google                                                                                                                                     
                                                                                                                                               
 # PENPOT_GOOGLE_CLIENT_ID=                                                                                                                    
 # PENPOT_GOOGLE_CLIENT_SECRET=                                                                                                                
                                                                                                                                               
 # GitHub                                                                                                                                     
                                                                                                                                               
 # PENPOT_GITHUB_CLIENT_ID=                                                                                                                    
 # PENPOT_GITHUB_CLIENT_SECRET=                                                                                                                
                                                                                                                                               
 # GitLab                                                                                                                                     
                                                                                                                                               
 # PENPOT_GITLAB_BASE_URI=https://gitlab.com/                                                                                                   
 # PENPOT_GITLAB_CLIENT_ID=                                                                                                                    
 # PENPOT_GITLAB_CLIENT_SECRET=                                                                                                                
                                                                                                                                               
 # OpenID Connect (since 1.5.0)                                                                                                               
                                                                                                                                               
 # PENPOT_OIDC_BASE_URI=                                                                                                                       
 # PENPOT_OIDC_CLIENT_ID=                                                                                                                      
 # PENPOT_OIDC_CLIENT_SECRET=                                                                                                                  
                                                                                                                                               
 # LDAP                                                                                                                                       
 #                                                                                                                                            
 # NOTE: to enable ldap, you will need to put 'enable-login-with-ldap'                                                                        
 # on the 'PENPOT_FLAGS' environment variable.                                                                                                
                                                                                                                                               
 # PENPOT_LDAP_HOST=ldap                                                                                                                       
 # PENPOT_LDAP_PORT=10389                                                                                                                      
 # PENPOT_LDAP_SSL=false                                                                                                                       
 # PENPOT_LDAP_STARTTLS=false                                                                                                                  
 # PENPOT_LDAP_BASE_DN=ou=people,dc=planetexpress,dc=com                                                                                       
 # PENPOT_LDAP_BIND_DN=cn=admin,dc=planetexpress,dc=com                                                                                        
 # PENPOT_LDAP_BIND_PASSWORD=GoodNewsEveryone                                                                                                  
 # PENPOT_LDAP_ATTRS_USERNAME=uid                                                                                                              
 # PENPOT_LDAP_ATTRS_EMAIL=mail                                                                                                                
 # PENPOT_LDAP_ATTRS_FULLNAME=cn

```

**DOCKER-COMPOSE.YAML**
```

version: "3.5"

services:

  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - ./penpot_assets_data:/opt/data
    env_file:
      - config.env
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: unless-stopped
    volumes:
      - ./penpot_assets_data:/opt/data
    depends_on:
      - penpot-postgres
      - penpot-redis
    env_file:
      - config.env
    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend/
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
    volumes:
      - ./penpot_postgres_data:/var/lib/postgresql/data
    networks:
      - penpot

  penpot-redis:
    image: redis:6
    restart: unless-stopped
    networks:
      - penpot

networks:
  penpot:
```

 Any advice is welcome, thanks again.

**Comment by shmolf** [comment]
I finally got mine working, but only if I register through the user interface.
Here's the lines I modified in my composer file, but you can update your `env` file as needed:
```yaml
services:
  penpot-frontend:
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-secure-session-cookies enable-insecure-register

  penpot-backend:
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies enable-insecure-register
```

**Comment by DriedMachine** [comment]
docker-compose.yaml，Replace the following line
PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server

PENPOT_FLAGS=enable-registration disable-secure-session-cookies

**Comment by Averyy** [comment]
> I finally got mine working, but only if I register through the user interface. Here's the lines I modified in my composer file, but you can update your `env` file as needed:
> 
> ```yaml
> services:
>   penpot-frontend:
>     environment:
>       - PENPOT_FLAGS=enable-registration enable-login-with-password disable-secure-session-cookies enable-insecure-register
> 
>   penpot-backend:
>     environment:
>       - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies enable-insecure-register
> ```

Thank you! This worked perfectly.

**Comment by phoscoder** [comment]
> I finally got mine working, but only if I register through the user interface. Here's the lines I modified in my composer file, but you can update your `env` file as needed:
> 
> ```yaml
> services:
>   penpot-frontend:
>     environment:
>       - PENPOT_FLAGS=enable-registration enable-login-with-password disable-secure-session-cookies enable-insecure-register
> 
>   penpot-backend:
>     environment:
>       - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies enable-insecure-register
> ```

This worked for me thank you very much

**Comment by vipulgote1999** [comment]
> I finally got mine working, but only if I register through the user interface. Here's the lines I modified in my composer file, but you can update your `env` file as needed:
> 
> ```yaml
> services:
>   penpot-frontend:
>     environment:
>       - PENPOT_FLAGS=enable-registration enable-login-with-password disable-secure-session-cookies enable-insecure-register
> 
>   penpot-backend:
>     environment:
>       - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies enable-insecure-register
> ```

Thanks a lot got my working with this after searching and testing so long...
