### ISSUE TITLE
Unable to log in with LDAP, says it's disabled

### ISSUE THREAD

**Issue by LXK-98** [uxbox/uxbox#1980]
**To Reproduce**

1. Enable LDAP in `config.env`
2. Add LDAP network for each container in `docker-compose.yml` (I'd assume only backend needs access but I tried it with all containers having access)
3. `dockercompose up -d`
4. Open Penpot in your browser and try logging in using your LDAP credentials

**Expected behavior**

Normal login should occur

**Actual behavior**

"LDAP  authentication is disabled." shows up as a notification in the top right.
 
**Screenshots**

![Screenshot from 2022-06-06 14-14-16](https://user-images.githubusercontent.com/52625640/172161003-dcd5af4b-d95c-4a4a-ae98-7851dab5222c.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04
- Browser & version: Firefox 101.0 (64-bit)

**Environment (please complete the following information):**
- Host: self-hosted

*If self-hosted:*
- OS Version : Ubuntu 22.04 Server (64-bit)
- Docker / Docker-compose version: Client: 20.10.16 Engine: 20.10.16 using both `docker compose` and `docker-compose`
- Image version (e.g. Alpine): latest (as of June 6 2022)

Docker commands or docker-compose file (if possible and if proceed.x):
LDAP config according to https://help.penpot.app/technical-guide/configuration/#ldap
with port, host, base DN, bind DN and password changed.
Tried with and without `PENPOT_LOGIN_WITH_LDAP=true` (which seems to be in the config.env but not in the web docs)

The network the osixia/openldap container runs on is added to every container in docker-compose.yml as well.

Frontend Stack Trace:

```
172.28.0.1 - - [06/Jun/2022:12:39:40 +0000] "POST /api/rpc/mutation/login-with-ldap HTTP/1.1" 400 115 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
```

Backend Stack Trace:
Nothing available using docker logs

**Additional context:**

same LDAP is being used with several other containers no issues, so I doubt the issue is with the LDAP itself.

**Comment by niwinz** [comment]
Have you tried the "enable-login-with-ldap" flag?

**Comment by LXK-98** [comment]
Yes, that is enabled just like in the web docs. The "log in with LDAP" button is visible as well.

**Comment by LXK-98** [comment]
Oh dear, I have to apologize. The issue was a rather dumb one on my side. I accidentally mistook a hyphen for an underscore in my ldap network name...
After changing that everything works just fine.
Still, I guess this leads me to a suggestion: Since the frontend said that LDAP was disabled I was assuming it was an issue on Penpot's side. Maybe for a case like this a message like "Cannot connect to LDAP" or something similar would be more helpful?
Either way, my deepest apologies for making a big fuss about nothing, I hope I didn't waste too much of your time. And thanks for trying to help!
