### ISSUE TITLE
Landscape-Portrait does not work with differently sized artboards (Internal Error: Assertion)

### ISSUE THREAD

**Issue by tz-reinberger** [uxbox/uxbox#1982]
**To Reproduce**
1. Go to your project on https://design.penpot.app
2. Make a few differently sized artboards
3. Select all of them
4. Click on the Landscape or Portrait Button

**Expected behavior**
The same happens as when you select the artboards individually and press the button.

**Actual behavior**
None of the artboards gets influenced, instead you get an "Internal Error: Assertion".
 
**Screenshots**
![Example canvas with error message](https://user-images.githubusercontent.com/107051323/172393425-8300b47b-7cec-46b4-ba8b-b8237ad2defe.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows 10, Build 21H2
- Browser & version (e.g. Chrome 89.0): Firefox 101.0

**Environment (please complete the following information):**
- https://design.penpot.app

**Comment by myfunnyandy** [comment]
Hi,

We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/3548) to track this issue from here. We will try to fix it soon. 

Thanks for reporting it!

**Comment by niwinz** [comment]
This should be fixed.

Thank you very much for reporting the issue.

**Comment by tz-reinberger** [comment]
Yes, it’s fixed as far as I can see.

Von: Andrey Antukh ***@***.***>
Gesendet: Donnerstag, 14. Juli 2022 12:23
An: penpot/penpot ***@***.***>
Cc: Benedikt Reinberger ***@***.***>; Author ***@***.***>
Betreff: Re: [penpot/penpot] Landscape-Portrait does not work with differently sized artboards (Internal Error: Assertion) (Issue #1982)


This should be fixed.

Thank you very much for reporting the issue.
