### ISSUE TITLE
Galician translation

### ISSUE THREAD

**Issue by ascarida** [uxbox/uxbox#1983]
Hi,

I would like to translate Penpot into Galician, please add Galician at the languages list.

My weblate username: ascarida

Saúdos!

**Comment by myfunnyandy** [comment]
Ola!

We've already added your username to the translation project and also the Galician language at the languages list.: https://hosted.weblate.org/projects/penpot/frontend/gl/. Also, here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Moitas grazas!
