### ISSUE TITLE
Help for French translation

### ISSUE THREAD

**Issue by alexpawlak** [uxbox/uxbox#1986]
Hello ! 
I would like to help on the french translation, could you add me? 
(same account as on github)

Thanks !

**Comment by myfunnyandy** [comment]
Hi @alexpawlak!

We've already added you to the translation project. We have a big french speaking community but the french transalations are only 62% completed, so we're happy that you want to help! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/fr/) and start translating.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
