### ISSUE TITLE
Reload / Refresh image assets in a design with new set of image sources (that have same filenames...?)

### ISSUE THREAD

**Issue by GetBitOutdoors** [uxbox/uxbox#1989]
I am used to working with Photoshop + Generator image exports. When I save a PS file, I get a fresh batch of exported images.
This allows a tight feedback loop from image editing in Photoshop, to compositing assets in another runtime (ex. HTML/CSS).
I would like to use PenPot to design an overall composition, while incrementally updating image assets (with photoshop or another process).

Is there any way to go about this?

(I don't even see a way to update an embedded image one by one. Is this possible?)

**Comment by myfunnyandy** [comment]
Hi @GetBitOutdoors, right now you can not update an embedded image at Penpot, but this capability is in our plans and will be available eventually.

About the exporting options, we recently released new capabilites for bulk exports that might suit your needs: https://help.penpot.app/user-guide/exporting/#export-multiple-elements

Let us know if this helps!
