### ISSUE TITLE
Importing SVG with lots of fonts  kills performance 

### ISSUE THREAD

**Issue by adambelis** [uxbox/uxbox#1990]
**To Reproduce**

1. open pen pot
2. import this file 
![font dialog](https://user-images.githubusercontent.com/50795097/173015404-dfb85913-328c-4439-b157-697cd3f5b4c2.svg)
3. observe  performance and missing fonts

**Expected behavior**

I would expect that I would see text objects and that performance would not be this bad.

I would also expect pen-pot recognize Inkscape layers should be fairly easy. Inkscape uses groups as a layer but also adds special labels to recognize them as layers .
![image](https://user-images.githubusercontent.com/50795097/173015920-de5804ec-8b9d-4d15-9ec0-051ef474c103.png)

**Actual behavior**

No fonts visible and freezes on selecting object 
 layer is recognized as groups
**Screenshots**

**Desktop (please complete the following information):**
win 10 chrome 102 [penpot](https://penpot.app/)

```

```

</details>

Backend Stack Trace:
<details>

```

```

</details>

**Additional context:**

Any other context about the problem.

**Comment by hirunatan** [comment]
Sorry. Currently only import SVG standard features. The inkscape particular extensions are not recognized. We have in our roadmap to be able to import from other applications formats, but cannot give you specific dates for now.

About performance, this is, instead, in our top priorities. We have made some advances, and you can expect more in the next releases.

**Comment by adambelis** [comment]
Ah sad to see that you don't want inkscape and penpot talk to each other
