### ISSUE TITLE
Coordinate spaces for groups in artboards are inconsistent

### ISSUE THREAD

**Issue by bleonard252** [uxbox/uxbox#2008]
**To Reproduce**

1. Set up an artboard away from origin somewhere.
2. Add or create a group inside the artboard.
3. Add or create a non-group object inside the artboard.
4. Compare the displayed positions of the two objects.

**Expected behavior**

The group's X and Y values are displayed relative to the artboard.

**Actual behavior**

The group's X and Y values are displayed based on the global coordinate system (relative to 0, 0).
 
**Screenshots**

![](https://i.ibb.co/ZKzHHHf/image.png)

![](https://i.ibb.co/fvjsfhg/image.png)

(The Common text is part of a group along with a hidden shape.)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Linux (Debian Bullseye/Sid)
- Browser & version (e.g. Chrome 89.0): Firefox 101.0.1

**Smartphone (please complete the following information):**
- Device & model (e.g. iPhone 6): N/A
- OS & version (e.g. iOS 8.1): N/A
- Browser & version (e.g. stock browser 22): N/A

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): https://design.penpot.app

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04): N/A
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24): N/A
- Image version (e.g. Alpine): N/A

Docker commands or docker-compose file (if possible and if proceed.x):
```
N/A
```

Frontend Stack Trace:
<details>

```
N/A
```

</details>

Backend Stack Trace:
<details>

```
N/A
```

</details>

**Additional context:**

None.

**Comment by hirunatan** [comment]
Thanks for reporting. I have created an issue in Taiga to track it. Hope it will be fixed soon.

https://tree.taiga.io/project/penpot/issue/3630

**Comment by elhombretecla** [comment]
This issue is fixed and will be solved with the next release :)
