### ISSUE TITLE
unexpected line with stroke cap

### ISSUE THREAD

**Issue by jsmorabito** [uxbox/uxbox#2011]
A line is appearing in between the cap and rest of the path in a logo I'm making. You can see it on the hands and feet of the character. The line appears in exported pngs as well. I do not expect a line to appear between the cap and the rest of the path.

**Screenshots**

![image](https://user-images.githubusercontent.com/46250921/174495422-b8ff510f-25f6-4d6e-a840-51f21c0dc88e.png)

![image](https://user-images.githubusercontent.com/46250921/174495437-6f998dec-a1b5-4e5b-9004-410da6f2f877.png)

appears on both safari and brave browsers on latest Mac OS

**Comment by superalex** [comment]
Hello @jsmorabito,

Some time ago you reported a similar issue here: https://github.com/penpot/penpot/issues/1936 

If it's an imported SVG, did you check if any of the elements has attributes producing that lines?

**Comment by jsmorabito** [comment]
@superalex the arms and legs are not part of the svg. they are paths (is that what theyre called?) i created the arms and legs with the pen tool.

![image](https://user-images.githubusercontent.com/46250921/174497018-75758230-ca64-410d-8ad4-2e030586362a.png)

**Comment by superalex** [comment]
Ok, could you please export a .penpot file just with the problematic logo?

**Comment by jsmorabito** [comment]
> 

sent to support email 🙏

**Comment by EvaMarco** [comment]
Hello @jsmorabito 
We received your message. We have opened an issue in our Taiga project to manage this issue. You can follow it up [here](https://tree.taiga.io/project/penpot/issue/3645).

Thanks for your help, hope this will be fixed soon.

**Comment by superalex** [comment]
Hello @jsmorabito could you please check if this is still happening in design.penpot.app I can't reproduce it now...
