### ISSUE TITLE
Make the openID button easy to find

### ISSUE THREAD

**Issue by GregLebreton** [uxbox/uxbox#2013]
Hi,
When you want to activate openID protocol connection, you need to uncomment a line in /var/www/app/js/config.js in the Frontend container.
You find nothing in the documentation about that and it would be nice for future openID implementers to know that.
It could be written somewhere in the Readme in a external authentification providers section for example.
Thanks!

**Comment by hirunatan** [comment]
This is strange. If you use the standard docker images, you should not need to manually change anything in this file. It's updated automatically by docker startups scripts, from the values in `config.env` file, as explained here https://help.penpot.app/technical-guide/getting-started/#start-penpot

If this does not work, perhaps it's a bug. What is the line you need to uncomment?

**Comment by GregLebreton** [comment]
The line uncommented is: "var penpotOIDCClientID = "penpot.our-org-domain.fr";"
I think it's a bug, cause the config.env was correctly filled.
I noticed the same behaviour for the penpotFlags (needed to uncomment "var penpotFlags = "disable-demo-users disable-login";" in order to make it efficient)

**Comment by niwinz** [comment]
If config.env is correctly filled, then the frontend container should reflect it. I have tested it recently. If you are using our docker images and our compose file, this is how it works and if you think you need to modify files inside the container, there are something working wrongly.

For try to understand and try to help, we need more information (config.env with values redacted), the docker-compose.yml file, etc.. All the context information is valuable.

**Comment by rbadsi** [comment]
I've encountered the same issue. The OpenID button doesn't show up.

[config.env.txt](https://github.com/penpot/penpot/files/9182284/config.env.txt)
[docker-compose.yml.txt](https://github.com/penpot/penpot/files/9182296/docker-compose.yml.txt)

```
# docker images | grep penpot
penpotapp/exporter   latest    54bc928ffcac   10 days ago    1.49GB
penpotapp/frontend   latest    815ab6eb9440   10 days ago    250MB
penpotapp/backend    latest    894fcd2696bd   10 days ago    869MB
```

There are no errors in the log:
```
# docker logs penpot_penpot-backend_1
...
[2022-07-25 14:55:17.687] D app.http.oauth - hint="initialize oidc provider", name="generic-oidc", opts={:scopes #{"profile" "email" "openid"}, :token-uri nil, :client-id "\"XXXXXXXX\"", :name "oidc", :roles nil, :roles-attr nil, :auth-uri nil, :base-uri "https://login.microsoftonline.com/XXXXXXXXX/v2.0/", :client-secret "\"UBU8*************************************", :user-uri nil}
[2022-07-25 14:55:17.687] D app.http.oauth - hint="trying to discover oidc provider configuration using BASE_URI"
[2022-07-25 14:55:17.691] D app.http.oauth - hint="discovered opts", additional-opts={:token-uri "https://login.microsoftonline.com/XXXXXXXXXXX/oauth2/v2.0/token", :auth-uri "https://login.microsoftonline.com/XXXXXXXXXXX/oauth2/v2.0/authorize", :user-uri "https://graph.microsoft.com/oidc/userinfo"}
[2022-07-25 14:55:17.692] I app.main - msg="welcome to penpot", version="1.14.2-beta-7535-g3e7b9805c"
```

Any help would be much appreciated!

**Comment by GregLebreton** [comment]
You need to access your Frontend container and edit the  /var/www/app/js/config.js to uncomment the openID protocol.
You can do: "docker exec -it frontend-container-name /bin/bash" to navigate inside the container and when the modification is done: "docker-compose stop" and "docker-compose start" to make penpot reload the config.

**Comment by rbadsi** [comment]
I checked the contents of /var/www/app/js/config.js. I didn't have to uncomment anything, the correct variable was already there, but some of the strings were double-quoted twice, e.g.:

`var penpotFlags = ""disable-registration enable-login"";`

The "OpenID Connect" button appeared after removing the quotation marks from all values in config.env. It seems that the script that generates config.js doesn't handle quoted values properly.

Thanks!

**Comment by niwinz** [comment]
Yep, we will check it for the next release. Looks that there are conditions where this is handled incorrectly, I do not figure when and why... I known some cases when the docker images are executed in docker swarm or similar environments, that does not handles the quotes in the same way as docker compose v2 does. I mean, we test to run this images on vanilla docker compose v2 and it handles correctly the quotes...
