### ISSUE TITLE
Cannot right-click on Typography assets

### ISSUE THREAD

**Issue by lane-hogan** [uxbox/uxbox#2022]
**To Reproduce**

1.  Go to a design file
2.  Click on 'Assets'
3.  Create a new typography and save it
4. Try to delete the new typography by right-clicking

**Expected behavior**

A right-click context menu should appear with options such as 'Rename, Edit, Delete, Group', similar to when you right-click a custom color asset or component asset.

**Actual behavior**

You are navigated to an error screen that asks to retry or report (see screenshot).
 
**Screenshots**
![image](https://user-images.githubusercontent.com/53493489/174890797-b4fbcbc4-a8b4-4642-bf2f-015a0cce6596.png)

Error in console:
![image](https://user-images.githubusercontent.com/53493489/174892047-142d11d9-3c18-40a1-ae0c-2794d30dbe6c.png)

**Desktop**
- OS: Windows 11
- Browser & version: Microsoft Edge Version 102.0.1245.44 64-bit

**Environment: **
- Host: https://design.penpot.app, installed as a PWA.

**Comment by EvaMarco** [comment]
Hello @lanehogan1 
Thanks for pointing out this bug¡
I've created an issue in our Taiga project, that you can check it [here](https://tree.taiga.io/project/penpot/issue/3638).
I hope it will be solved soon.

**Comment by Musiphilos** [comment]
Same here

**Comment by niwinz** [comment]
The fix is already landed on `main`, tomorrow we will bump a minor release with the fix.

**Comment by niwinz** [comment]
Should be fixed in the latest release (1.14.1)
