### ISSUE TITLE
Comment Errors on Shared Link 

### ISSUE THREAD

**Issue by prononext** [uxbox/uxbox#2032]
When sharing a link with comment functionality, the recipient cannot see any comments made, even if the "Show Comments" is activated. 

Also when creating the comments on the shared link they are not saved and a red error appears: 
"There was a error with the comment"

![image](https://user-images.githubusercontent.com/24569958/175399941-c3e91c1d-be84-4daf-8bd7-a025c0931c11.png)

How can it be fixed, are there any permission setting possibilities?

**Comment by EvaMarco** [comment]
Hello @prononext 
We are already working on allowing show comments in shared links. Stay tuned, we hope that soon you will be able to enjoy this upcoming feature/improvement. Just in case you are interested, you can see some details at the [user story](https://tree.taiga.io/project/penpot/us/3056).
Thanks!
