### ISSUE TITLE
Vector snapping is inaccurate/random

### ISSUE THREAD

**Issue by Yakehira** [uxbox/uxbox#2040]
**To Reproduce**

1. Create a Path and zoom in
2. Click on a Vector and Inspect the vector with debug tools to monitor, then move it, then release it
3. Take notice of the path data
4. Click on Vector and move it again and release
5. Notice how Vector lands on random sub pixel precision every time on Click and Release

**Expected behavior**

Vectors should properly snap on whole and half pixels not randomly in between.

See Video and look at how all over the place the locations are it snaps to.

**Desktop (please complete the following information):**
- Windows 11
- Edge 104

https://user-images.githubusercontent.com/773039/175787111-c3267b08-10ff-41c6-8235-84c73e3cb5c6.mp4

**Comment by Yakehira** [comment]
Looks like the issue is a result from getting the cursor position, depending on where I click on the dot the resulting snap distance is different.


Does it start here maybe?
https://github.com/penpot/penpot/blob/4d2de63374280814d5177ac64196d0dcdcfe00f7/frontend/src/app/main/data/workspace/path/streams.cljs#L51

https://user-images.githubusercontent.com/773039/175791770-355bb001-0fdd-4547-9061-fee4d4f9a610.mp4

**Comment by CathodeCube** [comment]
I require pixel accuracy for my use case, this is a deal breaker unfortunately :(

**Comment by madalenapmelo-kp** [comment]
Hi @Yakehira,

This issue should now be fixed, could you please confirm whether you are still experiencing it? If not, could you go ahead and close the issue?
