### ISSUE TITLE
Change the font of the UI in Persian and Arabic languages

### ISSUE THREAD

**Issue by ahmaduxui** [uxbox/uxbox#2048]
In Persian and Arabic languages, use legible and suitable Persian/Arabic font in Penpot UI

Persian/Arabic open source fonts:
[Estedad](https://github.com/aminabedi68/Estedad)
[Vazirmatn](https://github.com/rastikerdar/vazirmatn)

**Comment by Alotor** [comment]
Thanks for the suggestion. I've added this to the backlog.

We're definitely focusing more on accessibility in the near future so we'll try to address this.

https://tree.taiga.io/project/penpot/us/3687

**Comment by niwinz** [comment]
It is already merged, and will be available on the next release
