### ISSUE TITLE
Consider fontkit over OpenType.js

### ISSUE THREAD

**Issue by davelab6** [uxbox/uxbox#2049]
Font internals are accessed by OpenType.js but Fontkit js perhaps better written and more extensible.

**Comment by Alotor** [comment]
Thanks for your input. 

We don't really use OpenType a lot, just for basic stuff so we really prefer to have a more widely used library. We'll keep this in mind if we need more functionality in the future.

**Comment by VivaRado** [comment]
Stumbled on this while looking for letter to letter interpolation, figured it out with fontkit https://github.com/opentypejs/opentype.js/issues/400
