### ISSUE TITLE
Viewport-Actions interfere with the ability to Move a vector

### ISSUE THREAD

**Issue by Yakehira** [uxbox/uxbox#2050]
**To Reproduce**

1.  Draw a Line/Rect
2. Go Into Edit mode so the UI overlay shows
3. Drag a Point to the top anywhere on the horizontal, as the same height as the displayed UI
4. Try to drag it back down

**Expected behavior**

I should still be able to move the Vector.

**Actual behavior**

Not possible to move the Vector, Currently the UI is small but seemingly seems to take over the entire space.
![image](https://user-images.githubusercontent.com/773039/176034745-c74c0f3c-e09a-4c05-a9e1-e762c668bf70.png)

https://user-images.githubusercontent.com/773039/176034360-e225754b-6b93-4839-ae74-6e9ca234d95f.mp4

**Comment by Alotor** [comment]
Thanks for reporting the issue. I've added to our internal bug tracking and we'll resolve it soon.

https://tree.taiga.io/project/penpot/issue/3701
