### ISSUE TITLE
Typographies not grouping on design.penpot.app

### ISSUE THREAD

**Issue by knightknight** [uxbox/uxbox#2073]
**To Reproduce**

1.  Go to '[...](https://design.penpot.app/)'
2.  Create two text items under Typographies
3.  Ctrl + click each item
4. Right click > Group and add a name then Create

**Expected behavior**

Ctrl + click each text item then right-click to group.

**Actual behavior**

Not grouping for Typographies but is for others.
 
**Screenshots**

*No group created*
![No group created](https://user-images.githubusercontent.com/5765628/177310469-229c7651-7c5b-4a7b-b09b-f1c5a7d613f9.png)

*Group 'main' created for colors and 'energy' for graphics*
![Group 'main' created for colors and 'energy' for graphics](https://user-images.githubusercontent.com/5765628/177311662-3ea8cf37-61df-46fa-afc4-c6edb1272c2c.png)

**Desktop (please complete the following information):**
- Chrome Version 103.0.5060.66 (Official Build) (64-bit)

**Environment (please complete the following information):**
- https://design.penpot.app

*If self-hosted:*
- Docker 4.5.1 (74721)

**Comment by pabloalba** [comment]
Thanks for reporting the issue. We have already fixed it, and it will be released soon.

**Comment by niwinz** [comment]
The concrete issue is already fixed and released. We still have issues on drag and drop grouping, this is already tracked internally. So I close this issue.

Thanks you very much for reporting it.
