### ISSUE TITLE
Using the MacOS emoji picker crashes the app

### ISSUE THREAD

**Issue by kimadactyl** [uxbox/uxbox#2078]
**To Reproduce**

1.  Create a text area
2.  Open emoji picker with ctrl-command-space
3.  Pick an emoji
4. App crashes

**Expected behavior**

App not to crash when picking an emoji to insert

**Actual behavior**

After I click the emoji, the app crashes

**Screenshots**

<img width="1026" alt="Screenshot 2022-07-07 at 14 54 21" src="https://user-images.githubusercontent.com/511734/177791093-690ca69d-426d-4973-b3ca-fe08abb025e1.png">
<img width="954" alt="Screenshot 2022-07-07 at 14 54 32" src="https://user-images.githubusercontent.com/511734/177791104-3a1c9ac2-c14c-45da-b7e7-fbaaa56b9431.png">
<img width="1060" alt="Screenshot 2022-07-07 at 14 54 39" src="https://user-images.githubusercontent.com/511734/177791107-48022c1c-1f15-49c8-9c74-ba91eb9925f7.png">

**Desktop (please complete the following information):**
- OS (e.g. iOS): Mac OSX 12.4
- Browser & version (e.g. Chrome 89.0): Firefox 102.0 (64 bit)

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): penpot website

**Comment by pabloalba** [comment]
Thanks for reporting the issue. I've added to our internal bug tracking and we'll resolve it soon.

https://tree.taiga.io/project/penpot/issue/3844

**Comment by superalex** [comment]
Hello @kimadactyl 

This one should be fixed some time ago, feel free to reopen the issue if you finde something more.

Thanks!
