### ISSUE TITLE
Project Freezes when moving item out of group

### ISSUE THREAD

**Issue by Riximus** [uxbox/uxbox#2081]
**To Reproduce**

1.  Create a group with Text, Shapes whatever
2.  Select a Group Item
3.  Right-Click the board
4.  Move one Item out of the Group

**Expected behavior**

The item to get moved out of the group.

**Actual behavior**

The whole application freezes and doesn't react to anything.
 
**Screenshots**
The moment it froze.
![image](https://user-images.githubusercontent.com/62538759/177953555-552ca9ae-22b0-4794-a672-b58c858e52f3.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser & version: Chrome Version 103.0.5060.114 (Official Build) (64-bit)

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): design.penpot.app/#/workspace

Frontend Stack Trace:
<details>

```

```

</details>

Backend Stack Trace:
<details>

```

```

</details>

**Additional context:**

Any other context about the problem.

Edit: Reloading the page doesn't fix the problem. Multiple left-clicking on the page till the "Page Unresponsive" window pops up and click "Exit Page" to then refresh the page fixes it.

**Comment by pabloalba** [comment]
Hi @Riximus !

I can't reproduce this bug. Could you export the .penpot file and send it to support@penpot.app? If you can also send us the problematic url, we will try to fix this as soon as possible.

Thank you!

**Comment by pabloalba** [comment]
Thank you!

I've been able to reproduce the bug, and I've created a Taiga issue for it. You can follow the progress there.

https://tree.taiga.io/project/penpot/issue/3855

Thanks for reporting and for the additional info!

**Comment by myfunnyandy** [comment]
Fixed
