### ISSUE TITLE
Linear gradient issue on rotation to 180 degree

### ISSUE THREAD

**Issue by carstenheyer** [uxbox/uxbox#2082]
**To Reproduce**

1. Create a rectangle or ellipse
2. Change color to gradient
3. Rotate it to 180 degree

**Expected behavior**

The gradient should be rotated with the shape it belongs to. 

**Actual behavior**

The gradient is shown like there is no rotation done yet. 
 
**Screenshots**

![0degree](https://user-images.githubusercontent.com/88189340/178017038-8a6f4736-2bb1-49bb-9474-36903d5eef47.PNG)
![180degree](https://user-images.githubusercontent.com/88189340/178017044-39a9a187-7606-4476-9a79-e62c3fabf4fa.PNG)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows 10
- Browser & version (e.g. Chrome 89.0): Google Chrome Version 103.0.5060.114 (Official Build) (64-Bit)

**Additional context:**

Any other angle seems to work as intended.

**Comment by pabloalba** [comment]
Hello @carstenheyer 

Thanks for pointing out this bug!

I've created an issue in our Taiga project, you can check it [here](https://tree.taiga.io/project/penpot/issue/3832).
