### ISSUE TITLE
Editing any attribute of a text object removes it from the group

### ISSUE THREAD

**Issue by knightknight** [uxbox/uxbox#2098]
**To Reproduce**

1.  Go to Assets / File Library / Typographies
2.  Create two new text objects and group them
3.  Edit any attribute of that text object

**Expected behavior**

Text object to remain part of the group.

**Actual behavior**

Editing any attribute of that text object removes it from the group.
 
![text object removed from group](https://user-images.githubusercontent.com/5765628/178993046-6dad36a0-355b-4a65-b9c1-893ba490a589.gif)

**Desktop (please complete the following information):**
- OS (e.g. iOS):
- Browser & version (e.g. Chrome 89.0):

**Smartphone (please complete the following information):**
- Chrome Version 103.0.5060.114 (Official Build) (64-bit)

**Environment (please complete the following information):**
- https://design.penpot.app

*If self-hosted:*
- Docker not tested.

**Comment by pabloalba** [comment]
Hi!

This is resolved as part of https://tree.taiga.io/project/penpot/issue/3763

We will release the fix soon.

Thank you!
