### ISSUE TITLE
Custom fonts with apostrophes in their names don't work

### ISSUE THREAD

**Issue by rtwalz** [uxbox/uxbox#2101]
**To Reproduce**

1.  Upload a custom font, and include an apostrophe in its title, like `'`
2. Try using the font in the editor, and it won't work. For me, it just showed a browser default, Times Newe Roman.
3. Rename the font by getting rid of the apostrophe. It will now work.

**Desktop (please complete the following information):**
- OS: Chrome OS
- Browser & version: Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by EsterLatorre** [comment]
Hello @rtwalz 

Thanks for pointing out the bug!

I've created an issue in our Taiga project, you can check it [here](https://tree.taiga.io/project/penpot/issue/3918).

**Comment by EvaMarco** [comment]
Hello @rtwalz:

I've done some digging into this and as a result, I realize that quotes (simple or double) are not valid characters in a font family name. 
The only valid characters are:
- any alphabetical character (A to Z, or a to z),
- any decimal digit (0 to 9),
- a hyphen (-),
- an underscore (_),
- an escaped character (preceded by a backslash, \),
- a [Unicode](https://en.wikipedia.org/wiki/Unicode) character (in the format of a backslash, \, followed by one to six hexadecimal digits, representing its Unicode code point)

You can have more info on how to create a custom-ident for your fonts [here](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident)
You can also check the specification of a font family in SVG  text [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-family)

When the SVG does not recognize the font family it uses the default in your system.

Hope this helps.

**Comment by JakeQZ** [comment]
I just came across this looking for something else, and don't find that quotes are specifically disallowed in font family names.

> The only valid characters are:
> ...
> You can have more info on how to create a custom-ident for your fonts [here](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident)

This is for a &lt;custom-ident&gt;.  However, [the font family name can also be a &lt;string&gt;](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#values):

> The &lt;string&gt; [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [data type](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types) represents a sequence of characters. Strings are used in numerous CSS properties, such as [content](https://developer.mozilla.org/en-US/docs/Web/CSS/content), [font-family](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family), and [quotes](https://developer.mozilla.org/en-US/docs/Web/CSS/quotes).
> ...
> Importantly, certain characters which would otherwise be invalid can be escaped with a backslash. These include double quotes when used inside a double-quoted string, single quotes when used inside a single-quoted string... 

Edit: actually &lt;custom-ident&gt;s can also include quotes:

> * an [escaped character](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident#escaping_characters) (preceded by a backslash, \\)

So, basically, any character is allowed.
