### ISSUE TITLE
Support apple pencil in browser on iPad

### ISSUE THREAD

**Issue by ChristophSonnleitner** [uxbox/uxbox#2102]
**Is your feature request related to a problem? Please describe.**
When opening penpot (selfhosted) on my ipad (safari or other browsers) I have to pair a bluetooth-mouse to be able to work, since the apple pencil does not work with penpot (click actions work, but no dragging or drawing)

**Describe the solution you'd like**
It would be great if penpot would be able to recognize the apple pencil, so it can be used instead of a mouse.

**Comment by elhombretecla** [comment]
Hi @ChristophSonnleitner thanks for your suggestion :)

We are going to manage this enhancement on Taiga.
[https://tree.taiga.io/project/penpot/issue/3954](https://tree.taiga.io/project/penpot/issue/3954)
