### ISSUE TITLE
Clarify how to upload team avatar

### ISSUE THREAD

**Issue by andrewzhurov** [uxbox/uxbox#2103]
**Is your feature request related to a problem? Please describe.**
I've been taking a walk through Penpot interface and stumbled upon a button which I wasn't sure what it does.
![image](https://user-images.githubusercontent.com/13056889/179490141-4ba7cea8-d866-4062-8f0f-5a291233c3f6.png)
The icon on hover associated with 'log out' with me and I've seen 'leave team' on the previous page, so I assumed that it's another way to leave team, but wasn't 100% sure with it and decided to check out.
There is no text description so I'm again left to guess.
Clicknig on it proposed to select a file, which was a surprise, I thought maybe it's another way to upload a Penpot project, I've seen that action before. But it allowed to select only images, so it assumed it's an avatar upload and was finally right choosing an image and seeing team avatar change.

All-and-all, it frustrated me and I was hesitant to click it assuming it will drop me off team.
Perhaps this scenario may be encountered by other users and if they're not simply poking around but have a production system they may not want to take risk in figuring out what it does, leaving them with question "how do I upload a team avatar?".

**Describe the solution you'd like**
An icon that associates with avatar upload.
A text description of "Upload team avatar".

**Describe alternatives you've considered**
Have a contextual menu item.
![image](https://user-images.githubusercontent.com/13056889/179491536-06023e99-6e93-49bc-9a2f-c4296a05658d.png)

**Additional context**
An icon may be
![image](https://user-images.githubusercontent.com/13056889/179492896-b39517c4-1c56-4a62-8582-88fb9a8e5c59.png)
source: https://www.onlinewebfonts.com/icon/212908

**Comment by EsterLatorre** [comment]
Hello @andrewzhurov! 

That is certainly a bug, the icon is meant to be a different one, similar to the camera one you're proposing. I've created it as a bug in Taiga, it should be a quick fix. If you would like to have a look, find it [here](https://tree.taiga.io/project/penpot/issue/3919) :)

Thanks so much for pointing it out!

**Comment by azmy60** [comment]
Can I solve this issue?

**Comment by niwinz** [comment]
I think, yes, without contextual menu item I guess, because this is an separated enhacement.
