### ISSUE TITLE
Rectangle properties incorrectly inherited with 2-level nested components

### ISSUE THREAD

**Issue by extremegf** [uxbox/uxbox#2120]
**Steps to reproduce**
1.  Go to penpot and import attached project file.
     [wrong property inheritance.zip](https://github.com/penpot/penpot/files/9221385/wrong.property.inheritance.zip)
1.  Change color of the upper rectangle to some other shade of red.
1.  Click update main component.
1.  Observe that the lower pair of rectangles got black instead of your selected color.
1.  Click reset overrides on the rectangle pair. 
1.  Observe that they receive the correct color.

**Expected behavior**

The lower rectangles should inherit upper rectangle color, not the root color.

**Actual behavior**

Pair becomes black - that is the color of the root rectangle.
 
**Desktop (please complete the following information):**
- Ubuntu 20.04
- Chrome 103.0.5060.53

**Environment (please complete the following information):**
- https://design.penpot.app/

**Comment by elhombretecla** [comment]
Hi @extremegf we are currently working on a deep rework of the components functionality.

We will manage this issue in Taiga
[https://tree.taiga.io/project/penpot/issue/3957](https://tree.taiga.io/project/penpot/issue/3957)

**Comment by Freeplayg** [comment]
I tried the zip file mentioned but I couldn't get it to work, but I'm wondering if this would be the same issue?

https://user-images.githubusercontent.com/40742947/184227156-b18f44df-9d5a-42b4-bb54-3256c0b26d30.mp4

**Comment by hirunatan** [comment]
Hello @extremegf. We are reviewing issues and this one seems to be solved. I close the issue, but if you experience it again, feel free to reopen it and give more info.

**Comment by extremegf** [comment]
Thanks!
