### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by laminne** [uxbox/uxbox#2126]
Hello,

I want to become a tranlator for Japanese language.
My wablate account username is `@laminne`.

Thanks for the awesome works!

**Comment by YukiYuigishi** [comment]
Hello.

I'd like to participate in translating Penpot into Japanese too.
My Weblate account is `@YukiYuigishi`.

Thank you for the amazing software.

**Comment by myfunnyandy** [comment]
Hi @laminne and @YukiYuigishi,

We've already added both of you you to the translation project. Japanese is a new language at Penpot so you will need to add it first at the weblate project.

Here you can find information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your willing to contribute!

**Comment by laminne** [comment]
Hi @myfunnyandy ,

I tryed to add a new language(japanese) on
weblate, but the system said "permission denied".  


I think that I don't be translator on weblate.
Could you check my permissions?

**Comment by myfunnyandy** [comment]
@laminne I've just created the language so you can already start here: https://hosted.weblate.org/projects/penpot/frontend/jpn_JP/

It seems that you need an special permission to create a language, something that for the moment we rather leave to the Penpot team members. Sorry for the confusion!
