### ISSUE TITLE
Option to get a demo user work 

### ISSUE THREAD

**Issue by 100tomer** [uxbox/uxbox#2136]
**Is your feature request related to a problem? Please describe.**
Hi, I have an instance of penpot running in my home, and my friend accidentally did week of works in a demo account..
So far I wan't able to get the account in the DB is was marked as deleted

**Describe the solution you'd like**
Maybe an admin page where System admin will be able to log in any user even deleted demo users, this way I can go into this account and export the projects..

**Describe alternatives you've considered**
Currently I didn't find nay solution 

Thank you !

**Comment by niwinz** [comment]
The demo accounts are special ones that has been programed to be deleted after some time. There are no admin account or admin UI in penpot. But you as administrator can do it updating the `profile` table. Just assign `NULL` to the `deleted_at` property and `false` value to the `is_demo` attr.

```SQL
UPDATE profile SET is_demo=false, deleted_at=null WHERE email = 'email@email.com';
```

**Comment by 100tomer** [comment]
> The demo accounts are special ones that has been programed to be deleted after some time. There are no admin account or admin UI in penpot. But you as administrator can do it updating the `profile` table. Just assign `NULL` to the `deleted_at` property and `false` value to the `is_demo` attr.
> 
> ```sql
> UPDATE profile SET is_demo=false, deleted_at=null WHERE email = 'email@email.com';
> ```

Thank you, is it make sense that my DB no longer shows the old demo users after I removed the demo user login option ?

**Comment by niwinz** [comment]
I'm not clearly understand your question. What you mean "no longer shows"?

The demo button can be activated or deactivated, but this means nothing to the database state. All demo users already created should work independently of the button. If there are no demo users in the db, means the garbage collector passed and removed them. Demo users as they name indicates are just for do testing; they are really useful for development purposes and are not expected to be used by external users.  No real work should be done on demo users.

**Comment by 100tomer** [comment]
I meant that the demo accounts rows in the db does not exists anymore. 
Thank you for explaining how it might happened.
