### ISSUE TITLE
Text in SVG is invisible 

### ISSUE THREAD

**Issue by 100tomer** [uxbox/uxbox#2146]
**To Reproduce**

1. Get an SVG with text
2. drag and drop it to penpot

**Expected behavior**

See the svg as other programs, in Sketch or Figma the svg does work

**Actual behavior**

Only the text in the SVG is invisible, other shapes are fine
 

**Desktop (please complete the following information):**
- Mac OS
- Chrome 100

**Environment (please complete the following information):**
- https://design.penpot.app

**Comment by elhombretecla** [comment]
Hi @100tomer thank you so much for your feedback :)

Looks like we are experiencing some issues with SVG text elements. We will manage this issue on Taiga.
[https://tree.taiga.io/project/penpot/issue/3962](https://tree.taiga.io/project/penpot/issue/3962)
