### ISSUE TITLE
Create component from Artboard

### ISSUE THREAD

**Issue by jahirvidrio** [uxbox/uxbox#2163]
**Feature request:** Create components from Artboard like Figma

Currently creating components can only be from objects and groups, I whis I cloud create components from Artboard.
Failing this, I whish I could treat a Group like an Artboard: creste rouender borders, background color, border color, etc.

**Comment by myfunnyandy** [comment]
This is something that will be possible with the upcoming changes that we will probably release next week. You will be able to nest artboards and to create components from them and with them inside. [This is the user story](https://tree.taiga.io/project/penpot/us/2874?milestone=319982) just in case you're curious. Stay tunned!
