### ISSUE TITLE
Hosting the guilds and templates in the platform

### ISSUE THREAD

**Issue by 100tomer** [uxbox/uxbox#2164]
**Is your feature request related to a problem? Please describe.**
Hi, I have a really bad network at my workplace and that's why we have a penpot instance in our lan. The problems is that the templates and guilds are not accessible while there's not network..

**Describe the solution you'd like**
Hosting all the documentations and templates as part as penpot, this way it can work very well offline.

Thank you!

**Comment by myfunnyandy** [comment]
We are currently working on an in-app widget that will allow to download a selection of templates, we posted a [sneak peek at the Community](https://community.penpot.app/t/libraries-templates-module-at-the-dashboard-sneak-peek/352). Stay tunned to update your instance once is released, it will be ready soon :)

The documentation is [at GitHub](https://github.com/penpot/penpot-docs) so you could also set up the Help Center locally in your lan. 

I hope this helps!
