### ISSUE TITLE
Portuguese Brasilian Translate

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#2166]
**Is your feature request related to a problem? Please describe.**
I see that the Portuguese version of it is not complete and with some errors and I think it can be improved

**Describe the solution you'd like**
My weblate username is @allytiago and I will be able to help with some corrections in my spare time.

**Comment by myfunnyandy** [comment]
Hi @allytiago, I've just added you to the weblate project.

Just in case you need it, here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thanks :)
