### ISSUE TITLE
Fixed objects jitter while scrolling

### ISSUE THREAD

**Issue by ghost** [uxbox/uxbox#2167]
**To Reproduce**

1.  Turn on "Fix when scrolling" for some objects
2.  Start the prototype
3.  Start scrolling

**Expected behavior**

The object stays still and doesn't move or jitter at all

**Actual behavior**

The object jitters while scrolling. I also noticed that when the developer tools are open on the right, objects no longer stutter
 
**Screenshots**

https://user-images.githubusercontent.com/56515875/184787978-6b070ab0-1bed-42b6-9281-1b98cc19f6b1.mp4
(the bar at the top and the blue rectangle are the fixed objects)

**Desktop:**
- OS: KDE neon 5.25
- Browser & version: Firefox 103.0 64-bit

**Environment:**
- Host: design.penpot.app

**Comment by myfunnyandy** [comment]
Definitely a bug. I've added it to our issue tracker: https://tree.taiga.io/project/penpot/issue/3989. We will try to fix it soon. 

Thanks for reporting it!

**Comment by superalex** [comment]
Hi @logicalwillow 

This one should be fixed with the last release, could you please check if it's still happening?

**Comment by ghost** [comment]
I still see it happening, especially when using the scroll wheel instead of the scrollbar

**Comment by superalex** [comment]
Thanks @logicalwillow, now in my case it's only happening in firefox, could you please check if it jitters too on other browsers?

**Comment by ghost** [comment]
Sorry, I don't have access to any other browsers.
