### ISSUE TITLE
Extra text in German version for buttons logging via GitLab, GitHub, Google

### ISSUE THREAD

**Issue by staykova-sport-thieme** [uxbox/uxbox#2170]
1.  Go to https://design.penpot.app/#/auth/login - you have to be not logged in the app

**Expected behavior**

Visible lables in the buttons for logging in with GitLab, GitHub, Google when the browser language is set to German

**Actual behavior**

there is extra text here, the labels should be enough? not "Anmelden mit"/"Einloggen mit" which actually could be another issue as there are 2 different translations for this word somewhere else.

Browser - Chrome, Version 104.0.5112.79 (Official Build) (x86_64), on MacPro, 16inch

**Screenshots**
Comparison between German and English versions
<img width="250" alt="Screenshot 2022-08-17 at 09 00 06" src="https://user-images.githubusercontent.com/75254865/185055866-49512b7c-983e-4902-9d5f-8497c831022d.png"><img width="250" alt="Screenshot 2022-08-17 at 09 00 20" src="https://user-images.githubusercontent.com/75254865/185055871-47247e87-857f-4179-adaf-d046e6eeefc6.png">

**Comment by myfunnyandy** [comment]
Just checked that is also happening in other languages. I've opened [the issue at Taiga](https://tree.taiga.io/project/penpot/issue/3992) and we will fix those translations asap.

**Comment by myfunnyandy** [comment]
Fixed
