### ISSUE TITLE
Move between Artboards in view mode by "time"

### ISSUE THREAD

**Issue by 100tomer** [uxbox/uxbox#2179]
**Is your feature request related to a problem? Please describe.**
Hi, it will be great to have an option to moves between Artboards in View Mode automatically (something like setting a number of seconds till it moves to the next artboard)

**Describe the solution you'd like**
Having an option to set number of seconds till the view changing to the next artboard.

Thank you

**Comment by myfunnyandy** [comment]
@100tomer for that you can set an interaction with the trigger After delay. You'll need to set it individually for each artboard though. Take a look at the user guide: https://help.penpot.app/user-guide/prototyping/#prototyping-triggers
