### ISSUE TITLE
Accessibility: The best time to think about accessibility is when you start a project. 

### ISSUE THREAD

**Issue by mgifford** [uxbox/uxbox#2195]
The second best time is now. 

Figma is trying to retrofit a lot of stuff here:
   https://www.figma.com/blog/a-step-forward-in-our-accessibility-efforts/
   
Probably a tonne of work.  Usually best to start early. 

Here's a screenshot of errors provided by Microsoft's https://accessibilityinsights.io/

![Screen Shot from Accessibility Insights of Errors](https://user-images.githubusercontent.com/116832/186779412-1a537963-a9db-419b-a97b-01abb4d203f9.png)

It uses Deque's Axe (like so many other things). 

1.  Go to '...'

https://design.penpot.app/#/workspace/

2.  Click on '....'3. 

Run this accessibility engine (or axe DevTools or WAVE or whatever)

**Expected behavior**

There shouldn't be all these errors. 

**Actual behavior**

There are lots of errors: 
 
[FastPass_20220825_NewFile4Penpot.html.zip](https://github.com/penpot/penpot/files/9428569/FastPass_20220825_NewFile4Penpot.html.zip)

**Screenshots**

See above.

**Desktop (please complete the following information):**
Mac & Edge

**Comment by pabloalba** [comment]
Hi @mgifford !

You are absolutely correct. We really want that the accessibility will become one of our values at Penpot. We know that we are way behind, and we really want to improve, so thank you very much for your tips!

We have a lot of work to do and a lot to learn about accessibility, buy I can assure you that it's in our plans. Juan's post already reveals some of our work there: https://community.penpot.app/t/thoughts-on-penpot-s-user-interface/248

For now, I will add this as an [issue on Taiga](https://tree.taiga.io/project/penpot/issue/4011).

Thank you!

**Comment by EvaMarco** [comment]
Hi @mgifford!
As @pabloalba just told you, accessibility is very important to us, but we have to work much harder on it.
Because of this, we have closed the issue @pabloalba created and created two user stories instead.
We have started working on one of them.
You can check them out [here](https://tree.taiga.io/project/penpot/us/4178) and [here](https://tree.taiga.io/project/penpot/us/4163) .
