### ISSUE TITLE
No such directory exist

### ISSUE THREAD

**Issue by naxiwaynez10** [uxbox/uxbox#2196]
Please who also faced this issues installing the ### devenv just following the instruction [HERE](https://help.penpot.app/technical-guide/developer/devenv/) After running `./manage.sh run-devenv`

![image](https://user-images.githubusercontent.com/72284142/187013163-22deca45-07c9-42bf-ad08-beaa6dc6da1e.png)

This is the result for the `penpot-devenv-main` container. Every other containers works fine

**Comment by hirunatan** [comment]
Could yo please tell me what OS are you running?

Have you cloned the repository, and executed run-devenv in the cloned root?

Is there any other error message, previous to this last one? (Or could you send me the full log?) 

Thanks
