### ISSUE TITLE
Indonesian translation 

### ISSUE THREAD

**Issue by liimee** [uxbox/uxbox#2197]
hi, I'd like to help translate penpot to Indonesian :)

my weblate user is @liimee (https://hosted.weblate.org/user/liimee/)

**Comment by myfunnyandy** [comment]
Hi @liimee !

We've already added you to the translation project. Indonesian language is already added but still have little progress so any help will be more than welcome! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/id/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.
Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
