### ISSUE TITLE
Add More Shape in Toolbar

### ISSUE THREAD

**Issue by ahmaduxui** [uxbox/uxbox#2202]
Add Polygon, Star, Line and Arrow Tools in Penpot Toolbar

**Comment by hirunatan** [comment]
You can currently do all those things with the path tool: you can draw a line or a polyline, close it in a polygon and edit the line caps to have arrows.

To draw a star you need to do it by hand. We could add a predefined shape, but it's more versatile to use symbol libraries, with not only one or a few shapes, but a complete library of them.

**Comment by lukew3** [comment]
@hirunatan 
You mean like this?:
![Screenshot from 2022-09-17 19-39-59](https://user-images.githubusercontent.com/47042841/190879745-1b5c6df3-8914-409d-ac5d-7cc789772761.png)

Forcing designers to use the path tool for common shapes just adds an extra layer of difficulty to creating a good design. I can understand not adding every shape imaginable to the toolbar, but I think that at least arrows are necessary.

**Comment by mfgoes** [comment]
"closed this as completed" 
I'm guessing the reactions paint a different picture haha
