### ISSUE TITLE
Putting typography style into group doesn't work 

### ISSUE THREAD

**Issue by Rechi86** [uxbox/uxbox#2203]
See a video including audio here:
https://youtu.be/eS5HMxRFLA8

Expacted Behaviour:
Drag and Drop Functionality for adding Type Styles into existing groups.

Behaviour:
Currently Dropping a Type Style into a group doens't add it to the group. The
only way (I know of) is to ungroup and create a new group (including the newly to add
style). Maybe this is a misunderstanding, but like in the video demonstrated, this expected behavior works
for components.

- Windows 10
- Chrome Version 104.0.5112.102

**Environment:**
https://design.penpot.app

As always, thank you very much for your great work!

**Comment by hirunatan** [comment]
You are true. It's a bug. I've added it to Taiga, and we'll solve it as soon as possible.

https://tree.taiga.io/project/penpot/issue/4055
