### ISSUE TITLE
Text above an artboard scales/streches on resizing

### ISSUE THREAD

**Issue by girafic** [uxbox/uxbox#2207]
**To Reproduce**

1.  Create a new artboard
2.  Resize the arboard with your mouse
3.  Text (nam of an artboard) scales/streches on resizing

**Screenshots**

https://user-images.githubusercontent.com/1187276/187436162-5a27a68a-c8ad-4c1d-858a-1bb53329ff98.mp4

**Desktop (please complete the following information):**
- OS (e.g. iOS): macOS 12.5.1
- Browser & version (e.g. Chrome 89.0): Firefox 103.0.2

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance):  https://design.penpot.app

**Comment by Alotor** [comment]
Thanks for the report @girafic we'll solve this in the next release.
