### ISSUE TITLE
Close when clicking outside not working

### ISSUE THREAD

**Issue by notjl** [uxbox/uxbox#2215]
**To Reproduce**

1.  Open/Toggle Overlay
2. Tick 'Close when clicking outside'

**Expected behavior**

It is expected for it to return to the main board.

**Actual behavior**

It ignores the mouse clicking outside of the board.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/58279268/187839418-9c9a6cb5-36de-4d0f-bd52-c748db54106c.png)
![image](https://user-images.githubusercontent.com/58279268/187839647-fa44f7e6-c345-463a-8325-50fc1324bdb9.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows 11
- Browser & version (e.g. Chrome 89.0): Brave Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): https://design.penpot.app

**Comment by hirunatan** [comment]
Oops... this is a bug. I've created it at Taiga, and we'll fix it as soon as possible. Thanks for reporting.

https://tree.taiga.io/project/penpot/issue/4027
