### ISSUE TITLE
Wacom tablets not supported ?

### ISSUE THREAD

**Issue by gordielachance** [uxbox/uxbox#2216]
**To Reproduce**

1.  Select pencil tool
2.  Draw on canvas
3.  Not working

**Expected behavior**

Using tablets to draw instead of a mouse should work too.

**Actual behavior**

Only drawing with mouse works.
 

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser & version: Chrome 105 / Firefox 104

**Environment (please complete the following information):**
- Host : https://design.penpot.app
- Tablet: Intuos 4 (PTK-840)

**Comment by EvaMarco** [comment]
Hello @gordielachance:

We have tried two Wacom tablets, an old bamboo and a newer one, the new one without cable. 
In both options, the pencil tool worked for us.
Can you tell us more about your problem or the tablet?
Thanks

**Comment by gordielachance** [comment]
I confirm it does not work with my tablet, which is an Intuos 4 (PTK-840).
My tablet works fine anywhere else.

**Comment by EvaMarco** [comment]
Hello again @gordielachance:
We have tried penpot with several Wacom tablets, on windows and Linux OS, and on those tests, the "pencil" tool works fine.
Have you tried it on firefox?
When you said "works fine anywhere else" what do you mean? It works fine in other apps? In other browser applications? or do the rest of the tools work fine?

**Comment by gordielachance** [comment]
Hi again,
Just did test on Firefox 104.0.2 and it does not work either (as on Chrome 105.0)

Works fine anywhere else means in other apps (Blender, Photoshop, Krita, ...) and other browser apps (I got it working on https://www.tldraw.com/)

I noticed that the wacom works to select a tool like  _curve_(pencil) or _ellipse_, but does not "draws" on the canvas.  
The _path_ tool works as expected.


Thanks !

**Comment by EvaMarco** [comment]
Hello @gordielachance 
Thanks for all the information provided. 
I've created an issue in our Taiga project to fix it, you can check it [here](https://tree.taiga.io/project/penpot/issue/4123).

**Comment by Eliepse** [comment]
Hello !

I had the same issue, but disabling the "Windows Ink" on the wacom configuration app solved it.

**Comment by EvaMarco** [comment]
Thanks for the clue¡¡

**Comment by Alotor** [comment]
I've been able to reproduce the error with the "Windows Ink" activated. Will be solved for the next release
