### ISSUE TITLE
Redefine shortcut cmd+Q for macOS

### ISSUE THREAD

**Issue by girafic** [uxbox/uxbox#2219]
**Expected behavior**
The shortcut cmd+Q should clear undo in Penpot.

**Actual behavior**
In Apple's macOS, pressing cmd+Q exits the current program.
 
**Screenshots**
<img width="610" alt="grafik" src="https://user-images.githubusercontent.com/1187276/188083124-8ad40bb4-67e4-4c77-a0af-7061a93ec5d1.png">

**Desktop (please complete the following information):**
- OS (e.g. iOS): macOS 12.5.1
- Browser & version (e.g. Chrome 89.0): Firefox 104.0.1

**Comment by elhombretecla** [comment]
Agree @girafic thanks for notice us :)

We are thinking in "Cmd + option + Q". Do you have any shortcut proposals?

**Comment by EvaMarco** [comment]
Hello @girafic :
I've opened an issue on our taiga project to manage this as soon as possible. You can check it [here](https://tree.taiga.io/project/penpot/issue/4059).
If you have any suggestions as @elhombretecla said just let us know and I'll add it to the issue.
Thanks¡

**Comment by girafic** [comment]
@elhombretecla `cmd + option + Q` or `alt + z` if it's free.

**Comment by elhombretecla** [comment]
`alt + z`  it's free so let's go for it :)
