### ISSUE TITLE
Desktop 64-bit version please.

### ISSUE THREAD

**Issue by RobFosterNYC** [uxbox/uxbox#2220]
Would love to have a Windows 10 (64-bit) Desktop version.
Many times I have had my internet flake on me for many times.
It would be nice to have an application for desktop.

That would be great.

.

**Comment by EvaMarco** [comment]
Hello @RobFosterNYC
A desktop app is not in our main backlog right now, we are focusing on other areas at this moment. But we have talked about this issue for a while. You can get more information on our main page [here](https://help.penpot.app/faqs/#how-can-penpot-work-offline), and also be part of [this topic ](https://community.penpot.app/t/faq-how-can-i-make-penpot-work-offline/51)on our community.
Thank you for your interest.
