### ISSUE TITLE
Snap to grid/guide not working properly

### ISSUE THREAD

**Issue by Gonchonson** [uxbox/uxbox#2221]
I have snap to grid and guides enabled for my artboard with a 20px grid visible, but whenever I add a new element to the board the element is not snapping to anything.

**Comment by chihiros** [comment]
me too

**Comment by EvaMarco** [comment]
Hello @Gonchonson  and @chihiros:

Thanks for the info, I've created an issue about this in our Taiga project [here](https://tree.taiga.io/project/penpot/issue/4060).

**Comment by dick-jo** [comment]
I can also recreate this bug, notably the same issue occurs for column grids also.

**Steps to reproduce:**

1. Create a board of arbitrary size
2. Add a column grid (default 12)
3. Draw a rectangle of arbitrary size
4. Resize rectangle within column grid, no snapping occurs

I would emphasise the seriousness of this bug actually, just in case anyone mistakes this merely for a quality of life issue - this is actually a basic requirement for almost every use case.

**Comment by aharish** [comment]
Would like to corroborate the above replies, and also like to add that no snapping apart from "Dynamic alignment" seems to work. Reload of page with dynamic alignment disabled reenables the feature. In fact, every preference with regards to snapping is reset on page reload (all of them are enabled by default).

No errors in browser console.

Self-hosted Penpot instance, running Firefox 104.0.2 on Linux. Would also like to add that same case can be observed on Chrome Version 104.0.5112.79 (Official Build) (installed from AUR). Haven't checked on other browsers or operating systems.

**Comment by EvaMarco** [comment]
Hello @dick-jo  and  @aharish we are working on a hotfix right now. 
Thanks for the info.
