### ISSUE TITLE
enable-login-with-google doesn't show up 

### ISSUE THREAD

**Issue by siddjellali** [uxbox/uxbox#2231]
**To Reproduce**

1.  add flags "enable-login-with-google" in portainer.
2.  Click on 'Update the stack"
 
![image](https://user-images.githubusercontent.com/3965823/188512166-57ceee40-3310-492f-8deb-48386c46cc6b.png)

**Expected behavior**

Login with Google button Oauth;

**Actual behavior**

Button doesn't show up.

![image](https://user-images.githubusercontent.com/3965823/188512227-2c763056-3ec3-4506-83b8-675b98307b4d.png)

**Docker** 

```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:05:12 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:03:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

Frontend Stack Trace:
<details>

```
today at 23:05:3810.0.1.157 - - [05/Sep/2022:21:05:38 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
today at 23:05:3910.0.1.157 - - [05/Sep/2022:21:05:39 +0000] "GET /api/rpc/query/profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
```

</details>

Backend Stack Trace:
<details>

```
today at 22:53:40+ exec /usr/lib/jvm/openjdk/bin/java -jar penpot.jar -m app.main
today at 22:53:44[2022-09-05 20:53:44.872] I app.config - hint="flags initialized", flags="backend-api-doc,login-with-google,secure-session-cookies,login,backend-worker,registration"
today at 22:53:47WARNING: abs already refers to: #'clojure.core/abs in namespace: taoensso.encore, being replaced by: #'taoensso.encore/abs
**today at 22:53:50[2022-09-05 20:53:50.803] I app.auth.oidc - hint="provider initialized", provider=:google, client-id="10***************************ntent.com", client-secret="GOCSP******************************"**
today at 22:53:50[2022-09-05 20:53:50.805] I app.metrics - action="initialize metrics"
today at 22:53:50[2022-09-05 20:53:50.875] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=30
today at 22:53:51[2022-09-05 20:53:51.136] W app.setup - hint="using autogenerated secret-key, it will change on each restart and will invalidate all sessions on each restart, it is hightly recommeded setting up the PENPOT_SECRET_KEY environment variable"
today at 22:53:51[2022-09-05 20:53:51.196] I app.msgbus - hint="initialize msgbus", buffer-size=128, redis-uri="redis://penpot-redis/0"
today at 22:53:52[2022-09-05 20:53:52.286] I app.loggers.audit - hint="audit log collection disabled"
today at 22:53:52[2022-09-05 20:53:52.288] W app.loggers.audit - hint="audit log http handler disabled or db is read-only"
today at 22:53:52[2022-09-05 20:53:52.913] I app.http - hint="starting http server", port=6060, host="0.0.0.0", name="http"
today at 22:53:52[2022-09-05 20:53:52.953] I io.undertow - starting server: Undertow - 2.2.17.Final
today at 22:53:52[2022-09-05 20:53:52.967] I org.xnio - XNIO version 3.8.6.Final
today at 22:53:52[2022-09-05 20:53:52.981] I org.xnio.nio - XNIO NIO Implementation Version 3.8.6.Final
today at 22:53:53[2022-09-05 20:53:53.019] I org.jboss.threads - JBoss Threads version 3.1.0.Final
today at 22:53:53[2022-09-05 20:53:53.145] I app.loggers.zmq - msg="initializing ZMQ receiver", bind="tcp://localhost:45556"
today at 22:53:53[2022-09-05 20:53:53.156] I app.loggers.database - msg="initializing database error persistence"
today at 22:53:53[2022-09-05 20:53:53.169] I app.storage.tmp - hint="starting tempfile cleaner service"
today at 22:53:53[2022-09-05 20:53:53.206] I app.worker - hint="registry initialized", tasks=11
today at 22:53:53[2022-09-05 20:53:53.212] I app.worker - hint="cron initialized", tasks=8
today at 22:53:53[2022-09-05 20:53:53.264] I app.worker - hint="worker initialized", name="worker", queue="default"
today at 22:53:53[2022-09-05 20:53:53.267] I app.srepl - msg="initializing server repl", port=6062, host="127.0.0.1", name="main"
today at 22:53:53[2022-09-05 20:53:53.271] I app.main - msg="welcome to penpot", version="1.15.2-beta-7851-g2cb8e7b98"
```

</details>

**Comment by niwinz** [comment]
Looking the backend logs, looks like it works as expected.
Looking at the screenshot, you can see that the flags value is enclosed in double quotes (but if you compare it to other values, for example PENPOT_TENANT, there are no quotes there); I suspect that in the environment you are using to deploy this has the double quotes and the config.js file is generated incorrectly.
Try removing the quotes from the flags value and restarting the frontend container.

**Comment by siddjellali** [comment]
Thanks ! I have tried with double quote, single quote and no quote... Same behavior

**Comment by niwinz** [comment]
Are you sure that after the change, you have properly restarted/recreated the frontend container?
In any case, for make sure that the problem is related to the quotes, please can you open the `https://<your-domain-here>/js/config.js` and paste here or take a screenshot of the contents

**Comment by siddjellali** [comment]
Frontend configuration
var penpotFlags = "'enable-login-with-google'";

<img width="451" alt="Capture d’écran 2022-09-06 à 10 07 47" src="https://user-images.githubusercontent.com/3965823/188581563-1d7b2d4d-a069-47eb-929b-3aacd6e6ce28.png">


// Frontend configuration
var penpotFlags = "enable-login-with-google";

<img width="451" alt="Capture d’écran 2022-09-06 à 10 07 47" src="https://user-images.githubusercontent.com/3965823/188581884-c510d7d7-9673-46e3-bb0f-230eb615fe7c.png">


// Frontend configuration
var penpotFlags = ""enable-login-with-google"";

<img width="451" alt="Capture d’écran 2022-09-06 à 10 07 47" src="https://user-images.githubusercontent.com/3965823/188582236-7bad75af-e830-4cab-9410-aa9f2f44c8a8.png">

Do you experiment a different behavior ?

**Comment by niwinz** [comment]
![image](https://user-images.githubusercontent.com/843689/188583621-c8dfa5a4-905e-4195-8a85-88a5f7acc050.png)
This is how it should be, ensure you are not caching.

![image](https://user-images.githubusercontent.com/843689/188583875-6506cb8d-9cdb-4a85-b08e-9fed29af4027.png)
This is how it looks on out production isntance

**Comment by siddjellali** [comment]
Cache... You right !! Thanks a lot 

_Note: enable-login-with-cache should be documented ^^_

**Comment by niwinz** [comment]
yep, thanks, I have [documented it yesterday ](https://github.com/penpot/penpot-docs/pull/96), and the changes to the help center should be deployed today \o/
