### ISSUE TITLE
Translate in french : I want to participate on weblate ;)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [uxbox/uxbox#2239]
Hi,
What is the process to participate on weblate to translate in french ?

have a nice day.
Philippe

**Comment by PhilippeAccorsi** [comment]
I seen this doc https://help.penpot.app/contributing-guide/translations/

I want to translate or help to translate existing key without french translate.
My weblate name is same like github name.

**Comment by EvaMarco** [comment]
Hello @PhilippeAccorsi 
The only thing we need is your weblate username to add you as translator. 
Thanks¡¡¡¡

**Comment by PhilippeAccorsi** [comment]
My weblate username is `PhilippeAccorsi` :)

**Comment by EvaMarco** [comment]
Hello again¡¡¡ You can start translating when you want¡¡
Thanks for your collaboration.
