### ISSUE TITLE
Support Simplified Chinese

### ISSUE THREAD

**Issue by Jengro777** [uxbox/uxbox#2245]
It is hoped that penpot can support Simplified Chinese, so as to liberate the majority of Chinese designers from the predicament of relying on non-open source design tools.

**Comment by EvaMarco** [comment]
Hello @Avey777:
Thanks to the community translation to Simplified Chinese is at 88% of the total. You can check how it goes in our weblate dashboard [here](https://hosted.weblate.org/projects/penpot/frontend/).
