### ISSUE TITLE
Editing artboards like paths/shapes should be blocked

### ISSUE THREAD

**Issue by girafic** [uxbox/uxbox#2246]
**To Reproduce**

1. Create a new artboard
2. Select this artboard and tap on "Enter"-key
3. Select the "Draw nodes"-tool and draw a new path (for example, a triangle)
4. Tap "Enter"-key or "Esc"-key
5. Selection box of the artboard is now corrupted
 
**Screenshots**

https://user-images.githubusercontent.com/1187276/189296016-2551a5fd-6b5d-4bda-aea5-e2f9da69c9e8.mp4

**Desktop (please complete the following information):**
- OS (e.g. iOS): macOS 12.5.1 
- Browser & version (e.g. Chrome 89.0): Firefox 104.0.1

**Comment by EvaMarco** [comment]
Hello @girafic:
You are totally right, path editions should be banned for artboards. I have just opened an issue to fix this, you can check it [here](https://tree.taiga.io/project/penpot/issue/4105). I hope it will be fixed soon.
Thanks a lot¡
