### ISSUE TITLE
if email verification does not work

### ISSUE THREAD

**Issue by thefonso** [uxbox/uxbox#2250]
On first use of app. 

If you do not get an email verification... email....how do you reset and get the app to send you another?

(Why do I even need to login with an email if I'm the only one using the app on my computer?)

**Comment by superalex** [comment]
Hi @thefonso !

Thank you very much for reporting this one, I think it's related to this -> https://github.com/penpot/penpot/issues/2249 and to another issue we have detected (https://tree.taiga.io/project/penpot/issue/4106) that we will solve as soon as possible ;)
