### ISSUE TITLE
getting started docker command does not work

### ISSUE THREAD

**Issue by thefonso** [uxbox/uxbox#2251]
**To Reproduce**

1.  Go to 'https://github.com/penpot/penpot'
2.  Click on 'whale [Install docker](https://help.penpot.app/technical-guide/getting-started/)'
3.  Scroll down to 'START PENPOT'

**Expected behavior**

Docker compose installs configures and runs penpot

**Actual behavior**
This command: docker compose -p penpot -f docker-compose.yaml up -d

Produces this error: unknown shorthand flag: 'p' in -p
 
**Screenshots**

![](https://i.imgur.com/dCvPtLm.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Ubuntu 22.04
- Browser & version (e.g. Chrome 89.0): Firefox

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): local instance

**Additional context:**

Everything else is N/A since the code is not installable via the given command

**Comment by Alotor** [comment]
Hi @thefonso ,

I think the `-p` error is due to a version mismatch. It's working on version docker-compose 2.10.2 with docker 20.10.18.

Which docker-compose version do you have? And docker?

**Comment by rawzone** [comment]
missing the '-' between docker and compose in the docs.
Should be docker-compose <args>.

And -f is not needed if in same directory as the docker-compose file.

**Comment by niwinz** [comment]
You can use the `docker-compose` (v1) or `docker compose` (v2) 

if the second one does not works for you this means you don't hace the v2 installed.

**Comment by itsthejoker** [comment]
If anyone else hits this error, it's probably a fakeout on linux; you likely don't actually have the docker compose command installed because it's not included by default unless you're on mac or windows. Start here to install compose: https://docs.docker.com/compose/install/linux/
