### ISSUE TITLE
Internal error when resizing a svg

### ISSUE THREAD

**Issue by gbonaspetti** [uxbox/uxbox#2252]
**To Reproduce**

1.  Import svg on Ressources 
2.  Add to an Artboard
3.  Resize

**Expected behavior**

It resizes without error.

**Actual behavior**

Sometimes an internal error happens during resize.
 
**Screenshots**

![errorPenpot](https://user-images.githubusercontent.com/35422692/189669285-01e3ce5b-646b-4ecc-9506-eab2e6515c8e.gif)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Ubuntu 20.04.5 LTS
- Browser & version (e.g. Chrome 89.0): Google Chrome Version 105.0.5195.102 (Official Build) (64 bits)

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): local instance

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04):
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24):
- Image version (e.g. Alpine):

Docker commands or docker-compose file (if possible and if proceed.x), Frontend / Backend Stack Trace:
https://github.com/penpot/penpot/issues/2252#issuecomment-1243807321

**Additional context:**

I have an error on the console but it doesn't say a lot:

```
{:v nil}
    (anonymous) @ errors.cljs:54
```

The imported svg are Font Awesome icons. With a size of 500 bytes on average.

**Comment by PhilippeAccorsi** [comment]
We have check this kind of logs without any visible error:
- on the reverse proxy nginx  (reverse proxy is on another server than where penpot run)
  - `/var/log/nginx/penpot_access.log` (we just seen POST and other request without error)
  - `/var/log/nginx/penpot_error.log` (no error appear)
 
We use penpop with docker, and nothing visible in:
- `docker logs -f penpot_penpot-frontend_1` (just normal request)
- `docker logs -f penpot_penpot-backend_1` (nothing)
- `docker logs -f penpot_penpot-exporter_1` (nothing)
- `docker logs -f penpot_penpot-redis_1` (nothing)

We also check log in `/var/log/nginx/` of the container `penpot_penpot-frontend_1` without find anything.

**Comment by Alotor** [comment]
The error happens when you resize the SVG in a negative fashion (just like in the gif you're sharing). I've added it to our internal tracking and we hope to solve it for the next release.

@PhilippeAccorsi this a frontend bug that's why the errors won't show anyhing.

**Comment by Alotor** [comment]
https://tree.taiga.io/project/penpot/issue/4109
