### ISSUE TITLE
Unable to open the program after docker is installed

### ISSUE THREAD

**Issue by Carlos920** [uxbox/uxbox#2254]
Install according to the document

![image](https://user-images.githubusercontent.com/32257015/189839654-acc910e8-6a9b-49ca-9109-7e19ffeafc7b.png)
![image](https://user-images.githubusercontent.com/32257015/189839729-4916f176-c07e-47a2-9e94-0d44d54dad5b.png)

![image](https://user-images.githubusercontent.com/32257015/189839936-c3c129c6-16ab-4aff-8f63-b498a71ed58f.png)
![image](https://user-images.githubusercontent.com/32257015/189840006-0933af4e-75a3-4825-89fe-eb1cf8a51148.png)

 I don't know why nginx will report an error, I don't have nginx installed on my system

**Comment by niwinz** [comment]
Are you using docker compose for start the containers? If not, you will need to setup the correct network rules and correct environment variables in the system you are using for starting containers.
