### ISSUE TITLE
Overlay on Penpot in Chrome & Edge preventing access to UI elements

### ISSUE THREAD

**Issue by AnneKok** [uxbox/uxbox#2261]
**To Reproduce**

1. Go to penpot.app and sign up
2. In the verification email, click the button 'Verify email'

After this, it also happens when I log in from penpot.app (I am already logged in and redirected to the .../projects page) and when I refresh the browser tab. So any time I access the URL: https://design.penpot.app/#/dashboard/team/e7e40400-34f7-11ed-9e6a-c67f7655c7b3/projects 

**Expected behavior**

I see the Penpot UI and can use the app.

**Actual behavior**

I see a white page with only the Penpot-colored squiggles and no further content/UI elements.
Going into dev tools and removing an overlay div resolves the issue.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/7063684/190420456-d49d5db5-1e8e-4506-984c-fa81bca528c8.png)

Screen recording: 
https://user-images.githubusercontent.com/7063684/190420681-c46c9908-e6a4-4cdc-b624-8d62f4ce2ffc.mp4

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser & version: Chrome Version 104.0.5112.101 (Official Build) (64-bit), bug also occurs with Edge Version 105.0.1343.33 (Official build) (64-bit)

**Environment (please complete the following information):**
- Host: https://design.penpot.app

**Additional context:**

No active browser extensions (no adblockers etc) except for one, I tried again after the screen recording with the extension disabled, nothing changed.

**Comment by superalex** [comment]
Hello @AnneKok 

Could you please check if this is still happening?

Thanks!

**Comment by DJTwoTone** [comment]
I have the exact same behavior. I assumed it's because of the stupid number of tabs I have open, but I haven't tested that assumption... YET!

**Comment by superalex** [comment]
@DJTwoTone could you please check your browser network console to see if there are any requests blocked?

![1](https://user-images.githubusercontent.com/1579633/190985941-c0f173d1-51ae-4058-8076-d43d87725046.png)

**Comment by DJTwoTone** [comment]
@superalex Looks like forms.js isn't loading 
![penpot](https://user-images.githubusercontent.com/34737313/191002309-cd3ae299-68e0-45ec-ba48-262177a27db2.jpg)

**Comment by superalex** [comment]
Hmmmm, it sounds like your browser is blocking that request. Do you have any plugin installed that can be doing it?

Can you access https://sdk.arengu.com/forms.js directly?

**Comment by DJTwoTone** [comment]
@superalex I'll dig through it soon, see if I can figure out what is happening, and let you you know.

**Comment by superalex** [comment]
Thank you very much! :)

**Comment by DJTwoTone** [comment]
@superalex  It was my firewall. I'm using NordVPN with their Threat Protection option turned on. I turned off the Threat protection option, but it still didn't work. I turned off the firewall, and I'm in... Working both in Firefox and Chrome. I don't know if any of that helps, but...

**Comment by superalex** [comment]
Thank you very much!, it helps a lot, probably we should detect this kind of situations where needed javascript is blocked and inform the user. I hope we can include it in Penpot soon.

**Comment by DJTwoTone** [comment]
@superalex Just a heads up. I just turned my computer on for the day, and it is still working fine.

**Comment by superalex** [comment]
Great!, anyway yesterday we decided include this extra check in the next release :)

Thank you very much!

**Comment by AnneKok** [comment]
Hey, apologies for not replying, I didn't see your comments and forgot about this issue. I also use NordVPN so that may well have been the issue for me too. Thank you for troubleshooting @DJTwoTone. My feedback is way late but the issue is indeed fixed now and I can access Penpot!
