### ISSUE TITLE
Support for Portuguese - I want to help this amazing project

### ISSUE THREAD

**Issue by hugompfigueira** [uxbox/uxbox#2264]
Hello,

Thanks for bringing this nice project to life. I'm a Portuguese designer and I want to help you with the Portuguese translations.

My Weblate username is **hfigueira_1**

Thanks and happy coding!

**Comment by 00ff88** [comment]
@hugompfigueira 🇵🇹 
Contibution guide: https://help.penpot.app/contributing-guide/translations/
Weblate: https://hosted.weblate.org/projects/penpot/frontend/

Weblate username is 00ff88

**Comment by pabloalba** [comment]
Hi @hugompfigueira!

Thank you! I've just added you to Weblate.
