### ISSUE TITLE
Terms and Service Checkbox Not Styled Properly

### ISSUE THREAD

**Issue by lukew3** [uxbox/uxbox#2267]
**To Reproduce**

1. Use Dark Reader extension
2. Go to sign up page
3. Fill out details and click create account
4. Check box to agree to Terms Of Service
5. Observe check mark above box

Alternatively, this can be observed if you are not using the dark reader extension and follow the same steps, but just change the `background-color` of `.auth-content` to something darker.

**Expected behavior**

There should not be a checkmark visible above the checkbox

**Actual behavior**

There is a checkbox above the checkbox, being the same color as the background it is invisible to regular users, but improper.
 
**Screenshots**
![Screenshot from 2022-09-15 13-41-40](https://user-images.githubusercontent.com/47042841/190474583-3e67638d-5147-486d-add8-557d72108242.png)
![Screenshot from 2022-09-15 13-50-12](https://user-images.githubusercontent.com/47042841/190475078-85ca3dae-7228-45be-b79b-09596ded532b.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Ubuntu 20.04
- Browser & version (e.g. Chrome 89.0): Firefox 104.0

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): https://design.penpot.app

**Comment by lukew3** [comment]
I can attempt to patch this issue myself if you would like to assign me.

**Comment by myfunnyandy** [comment]
Hi @lukew3, I've just assigned you to the issue. It would be awesome to have a contribution like this one. Thanks for pointing out the bug and offering your help :)

**Comment by myfunnyandy** [comment]
Closing this as the register/login page was redesigned and the checkboxes are looking fine already.
