### ISSUE TITLE
Import React Components.

### ISSUE THREAD

**Issue by LucasNeuhausDev** [uxbox/uxbox#2269]
In my day job we often face the problem that our React based component library isn't in sync with our (currently) Figma based design library. 

We which we could import our React Components into penpot and use the imported components to design layouts.
Ideally, changes in the react codebase would automatically change the components inside penpot.

Currently, we are trying animas beta offering that syncs react storybook components with Figma. (Via Figma and storybook plugin)

**Comment by NurMarvin** [comment]
I think having this as a core feature wouldn't really make sense, as I feel it's simply too specific and I think it'd make more sense to have this a third-party plugin/extension once support for that has been added.

**Comment by nekwo** [comment]
I feel like such a feature would be good to iterate on especially if penpot can export react code

**Comment by TheHaymaker** [comment]
UXPin has this feature already - and it's not an insignificant feature.

**Comment by myfunnyandy** [comment]
At the Penpot team we've been thinking for a long time about importing components from frameworks like React or Storybook, but to be honest at the moment we don't have more than ideas. Surprisingly there where not even a user story at our backlog ([which I've just created](https://tree.taiga.io/project/penpot/us/4128), at least to add these requests at our roadmap).

This is clearly a topic that would be worth bringing to [the Community](https://community.penpot.app/), just in case anyone wants to continue this conversation in a maybe more appropiate place for open conversations.
