### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by florian-lefebvre** [uxbox/uxbox#2271]
**To Reproduce**

1.  Create file
2.  Create a text
3.  Select the font and search for "Space Grotesk"

**Expected behavior**

The "Space Grotesk" font should be available.

**Actual behavior**

It's not the case
 
**Screenshots**

![image](https://user-images.githubusercontent.com/69633530/190603207-3c1be16d-9d97-489b-a260-bc8341cd8bcf.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows 11
- Browser & version (e.g. Chrome 89.0): Brave Version 1.43.93  Chromium: 105.0.5195.127 (Official Build)  (64-bit)

**Environment (please complete the following information):**
- Host : https://design.penpot.app

**Additional context:**

I guess the issue is about outdated google fonts. Btw, we could even use [fontsource](https://github.com/fontsource/fontsource) instead.

**Comment by Manueljlin** [comment]
there's also some weights and variants missing in some fonts, for example noto sans only has four weights and the display variant is missing

**Comment by niwinz** [comment]
We don't use directly google fonts. The font list is cached and updated from time to time; this is the main reason why some fonts does not appear
