### ISSUE TITLE
Request to become a translator

### ISSUE THREAD

**Issue by swapnil-tc** [uxbox/uxbox#2280]
Hi,

I would like to first mention how glad I am to see an open source tool for designers. I stumbled here after a popular tool was acquired and I wish you all success. I would love to contribute to this project with the best of my abilities and I figured that translations would be a good place to start.

The languages I can translate to are:
- French [Certified Advanced Level]
- Hindi [Native Proficiency]
- Marathi [Native Proficiency]

Weblate ID: @swapnil.cx

Thanks

**Comment by Alotor** [comment]
Hi @swapnil-design I've added your user to the translators in weblate. 

Of those languages we only offer french right now. Would you be interested in starting an hindi translation?

**Comment by swapnil-tc** [comment]
I would love to!
