### ISSUE TITLE
Translation request (Portuguese-BR)

### ISSUE THREAD

**Issue by RuanAragao** [uxbox/uxbox#2281]
Hello,

I would like to contribute to the Portuguese-BR translation.

Weblate ID: @RuanAragao

Thanks!

**Comment by Xamanthas** [comment]
> Hello,
> 
> 
> 
> I would like to contribute to the Portuguese-BR translation.
> 
> 
> 
> Weblate ID: @RuanAragao
> 
> 
> 
> Thanks!

Hi Ruan,

Just visit this link (which is available on the main GitHub project page) to see the instructions on how to help with translations: 

https://help.penpot.app/contributing-guide/translations

**Comment by Alotor** [comment]
I've added you to the list of translators. Thanks for your collaboration.
