### ISSUE TITLE
Horizontal Ruler Disappearing when it touches top or bottom of a board

### ISSUE THREAD

**Issue by seongjaeryu** [uxbox/uxbox#2291]
- Environment: Macbook Air / Chrome Version 105.0.5195.102 (Official Build) (arm64)
- Bug: Horizontal Ruler Disappearing when it touches top or bottom of a board

**Comment by Waishnav** [comment]
Hey @seongjaeryu  actually, this behavior is occurring not only by touching the top and bottom parts of the board but also occurring when selecting/touching any part of the board.

**Comment by myfunnyandy** [comment]
We've added [the bug](https://tree.taiga.io/project/penpot/issue/4138) to our issue tracker. Thanks for reporting!

**Comment by superalex** [comment]
Hello!,

This one should have fixed some time ago, please feel free to reopen if you reproduce it.
