### ISSUE TITLE
Developer API for rendering + embedding

### ISSUE THREAD

**Issue by Explosion-Scratch** [uxbox/uxbox#2294]
Basically allow a dev API for embedding and rendering penpot things. This should allow serialization, deserialization, embedding the editor with some/all tools enabled, and just rendering it to PNG/svg or canvas.

**Comment by myfunnyandy** [comment]
We have already plans to allow to [embed the viewer](https://tree.taiga.io/project/penpot/us/3833?backlog-q=embe&no-milestone=1) and to create a [plugins system](https://tree.taiga.io/project/penpot/us/1129?backlog-q=api&no-milestone=1) providing an API. I've added your request at the embed story so it can be taken into consideration when the time comes.
