### ISSUE TITLE
Cannot login in MacOS Safari 16.1

### ISSUE THREAD

**Issue by uxandai** [uxbox/uxbox#2299]
**To Reproduce**

1.  Go to 'login'
2.  Enter valid credentials
3.  Login error (invalid password)

**Browser console:**
Failed to load resource: the server responded with a status of 400 (Bad Request) 
for /api/rpc/command/login-with-password

**Desktop:**
- MacOS Ventura
- Safari 16.1

**PenPot version:**
Docker - 1.15

**Comment by niwinz** [comment]
Hello @ppogorze 
I guess you are serving it under different domain than localhost. This is a known issue on browsers.

It is answered [here](https://github.com/penpot/penpot/issues/1775#issuecomment-1156374841)
You probably need to use the `disable-secure-session-cookies` flag

The flags are documented here: https://help.penpot.app/technical-guide/configuration/#other-flags
