### ISSUE TITLE
Content within an SVG that is designated as a fill bounces around as the filled object is moved.

### ISSUE THREAD

**Issue by dariusgarza** [uxbox/uxbox#2307]
**To Reproduce**

1. Drag an SVG onto the canvas that has a fill designated.
2. Move the SVG around the canvas

**Expected behavior**

The SVG fill should be stationary within the object that is being moved. 

**Actual behavior**

Content within an SVG that is designated as a fill bounces around as the filled object is moved around.
 
**Screenshots**

![SVG](https://media.giphy.com/media/mUpwBmIFwuw5Gvfqh0/giphy.gif)

**Desktop (please complete the following information):**
- MacOS 12.6
- Chrome 105.0.5195.125 (Official Build) (arm64)

**Comment by myfunnyandy** [comment]
We've added [the issue](https://tree.taiga.io/project/penpot/issue/4190) to our tracker, we hope to take a look at it soon.

**Comment by superalex** [comment]
Hello @dariusgarza 

I was trying to reproduce this issue, could you please attach an svg file example?

**Comment by myfunnyandy** [comment]
Hi @dariusgarza, we're closing the issue as we are not able to fix it without the SVG file. You can always reopen it in case you can send it to us and want us to take a look at it.
