### ISSUE TITLE
Scaling an imported SVG that was then grouped, causes erratic scaling behavior. 

### ISSUE THREAD

**Issue by dariusgarza** [uxbox/uxbox#2309]
**To Reproduce**

1. Import SVG
2. Scale with cursor, or scale numerically

**Expected behavior**

SVG layers within groups should smoothly scale with both the cursor and numerical methods. 

**Actual behavior**

Sometimes scaling an SVG group with the numerical fields in the properties panel is smooth and even, other times the SVG gets broken up. Scaling with the cursor seems to always break up the layers in an SVG group. 
 
**Screenshots**

![scaling](https://media.giphy.com/media/PT37Z4AleSm81FoJPl/giphy.gif)

**Desktop (please complete the following information):**
- macOS 12.6
- Chrome Version 105.0.5195.125 (Official Build) (arm64)

Frontend Stack Trace:
<details>

```
​ INF [app.main] message="Welcome to penpot", version="1.15.3-beta-7868-g2da6732ab", build-date="Wed, 07 Sep 2022 10:21:49 +0000", public-uri="https://design.penpot.app/"
​ INF [app.util.i18n] hint="locale changed", locale="en"
​ ">>>create-"
​ ">>>create-"
​ ">>>create-"
​ ">>>create-"
​ ">>>create-"
​ SEV [goog.net.WebSocket] The WebSocket disconnected unexpectedly: undefined
​ WebSocket connection to 'wss://design.penpot.app/ws/notifications?session-id=02b5ace0-3924-11ed-8d88-855b50b9559e' failed: 
h.open @ shared.2da6732ab.js:sourcemap:4728
​ SEV [goog.net.WebSocket] An error occurred: undefined
​ SEV [goog.net.WebSocket] The WebSocket disconnected unexpectedly: undefined
​ SEV [goog.net.WebSocket] The WebSocket disconnected unexpectedly: undefined
​ ">>>create-"
​ ">>>create-"
```

</details>

**Comment by myfunnyandy** [comment]
Hi @dariusgarza,

I've added the bug to our issue tracker: https://tree.taiga.io/project/penpot/issue/4189

Could you please send us a sample file where the issue can be reproduced to support@penpot.app?

Thanks!

**Comment by madalenapmelo-kp** [comment]
Hi @dariusgarza,

We have reviewed this issue but we have not been able to reproduce it. I have reached out to you to request access to the file where you experiencing this behaviour, but as I have not heard back from you I'm closing this issue.

If you are still experiencing this, please feel free send the file to support@penpot.app and reopen the issue!

Thank you!
