### ISSUE TITLE
Editor tab running out of memory when pasting svg code from XD

### ISSUE THREAD

**Issue by LauraWebdev** [uxbox/uxbox#2313]
**To Reproduce**

- Open the attached .xd file
- Copy the SVG code of the group "Jumbotron" (right click -> copy svg code)
- Go into a penpot document
- Paste

**Expected behavior**

The jumbotron appears in the document or the editor reports back, that it couldn't paste the code.

**Actual behavior**

The editor freezes up for a few seconds. After that, the browser stop the tab and displays an "Out of memory" error.

**Desktop (please complete the following information):**
- Windows latest
- Microsoft Edge 105.0.1343.42

**Environment (please complete the following information):**
- design.penpot.app

**XD file for testing**
https://drive.google.com/file/d/1AslkonnbeiqxWFb4RE6-1JSzG2BOb_Aq/view?usp=sharing

**Comment by LauraWebdev** [comment]
For additional information: The size of the clipboard after copying the svg code is 8.9mb big

**Comment by superalex** [comment]
Thanks @LauraWebdev 

Could you please upload somewhere the XD generated svg file?

**Comment by LauraWebdev** [comment]
I've pasted the code into this github gist: https://gist.github.com/LauraWebdev/6b92870f36d6272427e6370815c7e34b

Oddly enough, pasting the code into notepad++ and then pasting it doesn't crash the tab, though it does freeze up still (but displays some elements of the code). It is the exact same clipboard content.

**Comment by superalex** [comment]
Thanks again!,

We still must resolve some issues when importing complex svg's generated with other tools. I hope we can make your svg work soon.

**Comment by madalenapmelo-kp** [comment]
Hi @LauraWebdev,

Could you confirm if you are still experiencing this behavior?

**Comment by LauraWebdev** [comment]
@madalenapmelo-kp I can confirm that this has not happened in the 2.0 preview on my devices so far.
