### ISSUE TITLE
Recent colors don't work when adding a color asset

### ISSUE THREAD

**Issue by Lehvant** [uxbox/uxbox#2321]
**To Reproduce**

1.  Go to `Assets`
2.  Click on `Colors`
3.  Click the` + (plus)` icon button
4.  Click on a recent color you used

**Expected behavior**

Clicking a recent color used should prefill the color values

**Actual behavior**

Clicking a recent color does not do anything at all.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/48232326/191609962-f22fad6a-fade-472f-b770-8c0872637083.png)

**Desktop (please complete the following information):**
- Windows 10
- Using desktop app, but the browser I use is Brave [Version 1.43.93 Chromium: 105.0.5195.127](https://brave.com/latest/)

**Comment by myfunnyandy** [comment]
Hi,

We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/4186) to track this issue from here. We will try to fix it soon. 

Thanks for reporting it!

**Comment by Lehvant** [comment]
Thanks so much!
