### ISSUE TITLE
Add Portuguese (Portugal) translation

### ISSUE THREAD

**Issue by 00ff88** [uxbox/uxbox#2322]
Hi, my weblate user is **00ff88**.

**Comment by myfunnyandy** [comment]
Hi!

We've already added you to the translation project and also the Portuguese (Portugal) language at the languages list. It always makes us really happy to add a new language! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/pt_PT/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
