### ISSUE TITLE
Responsive prototyping

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#2330]
**Is your feature request related to a problem? Please describe.**
Create prototypes for websites and web apps that adapt to various screen resolutions for desktop and mobile devices. The UI elements on your screens will also adapt automatically.

**Describe the solution you'd like**
The prototyping tool could use flex display techniques for the responsive elements when necessary, using a layout responsiveness function, similar to Figma's auto layout, but adding other resolution options like percentage (%) as shown in the video below and a line break option in case the artboard is reduced and the space of the element group becomes larger than the size of the artboard, an example is the unofficial Figma auto layout plugin.

**Describe alternatives you've considered**

https://user-images.githubusercontent.com/47113005/192028986-fa922fc4-a205-4406-aac4-ff117df78b85.mp4

![6178ae16-7b41-47ff-af0c-6e56131d998e-cover.png](https://user-images.githubusercontent.com/47113005/192030482-9f35da10-011a-4bb6-861b-5ed1261cbc7e.png)
> https://www.figma.com/community/plugin/755300155155835622/AutoLayout

**Comment by LauraWebdev** [comment]
From what I've seen, they are currently working on auto-layout. There is a post on their community forums: https://community.penpot.app/t/what-are-penpot-plans-for-autolayout/112

**Comment by superalex** [comment]
Yes!, you can also track the current progress of auto-layout here -> https://tree.taiga.io/project/penpot/us/2262?milestone=326556 

I hope we can release a first version soon! :)
