### ISSUE TITLE
Confusing manual account creation script

### ISSUE THREAD

**Issue by oc013** [uxbox/uxbox#2331]
I ran into this issue while setting up the application using docker. Hopefully fixing this will resolve some of the headaches new users are experiencing.

As mentioned here https://help.penpot.app/technical-guide/getting-started/#configuration I ran the command 

```
docker exec -ti penpot-penpot-backend-1 ./manage.sh create-profile
```
And was given this output:
```
[2022-09-18 00:00:00.422] I app.config - hint="flags initialized", flags="backend-api-doc,login,backend-worker"
[2022-09-18 00:00:01.280] I app.metrics - action="initialize metrics"
Email:  [2022-09-18 00:00:01.323] I app.db - hint="initialize connection pool", name="main", uri="postgresql://penpot-postgres/penpot", read-only=false, with-credentials=true, min-size=0, max-size=30
```
I thought it was just hanging so I hit enter and was presented with a prompt, which of course does not result in a usable set of credentials.

```
Full Name:  
```

**Expected behavior**

`Email:` prompt should appear on its own line.  
Hitting enter on `Email:` prompt without any input should not proceed to the next prompt, but validate it is blank/not an email, show an error message and re-prompt.

**Actual behavior**
`Email:` prompt is munged in with the log lines making it easy to miss and lets you proceed without entering an email.

**Comment by LauraWebdev** [comment]
This has happened in my first setup as well and confused me just as you.

**Comment by niwinz** [comment]
Yep, this is clearly an issue, thanks for reporting. I think we need to rethink this a little bit, because the current approach is a little bit hacky in any way.
