### ISSUE TITLE
Issues with OpenID and keycloak

### ISSUE THREAD

**Issue by Sahnvour** [uxbox/uxbox#2332]
Hi,

I'm trying to set up a penpot instance using docker, an existing nginx reverse proxy, and keycloak as SSO.
Keycloak and nginx are known to work as I can use them for other services.

I've followed the install guide and read #810.
When I try to connect using OpenID, keycloak validates my ids but then I'm always redirected back to the penpot login page. On keycloak's admin console, I can see that the account has an open session so I know the authentication worked.
On subsequent login tries, keycloak recognizes my session as I'm not asked for ids again, but I still land on the login page.

My `config.env` modifications from the default looks like this
```conf
PENPOT_FLAGS="disable-registration enable-login-with-oidc"
# ...
PENPOT_OIDC_BASE_URI="https://<keycloak-url>/realms/<realm-name>/"
PENPOT_OIDC_CLIENT_ID="<client-name>"
PENPOT_OIDC_CLIENT_SECRET="<secret>"
PENPOT_OIDC_NAME_ATTR=username
# ...
VIRTUAL_HOST=<penpot-url>
LETSENCRYPT_HOST=<penpot-url>
VIRTUAL_PORT=80
```

At launch the backend says
```
I app.auth.oidc - hint="provider initialized", provider=:oidc, method="discover", client-id="<client-name>", client-secret="<secret>", scopes="profile,email,openid", auth-uri="https://<keycloak-url>/realms/<realm-name>/protocol/openid-connect/auth", user-uri="https://<keycloak-url>/realms/<realm-name>/protocol/openid-connect/userinfo", token-uri="https://<keycloak-url>/realms/<realm-name>/protocol/openid-connect/token", roles-attr=nil, roles=nil
```
which looks correct.

When logging in the following flow happens, as viewed by the reverse proxy
```
nginx.1     | <keycloak-url> - - [24/Sep/2022:12:56:28 +0000] "GET /realms/<realm-name>/protocol/openid-connect/auth?client_id=<client-name>&redirect_uri=https%3A//<penpot-url>/api/auth/oauth/oidc/callback&response_type=code&state=***&scope=profile+email+openid HTTP/2.0" 200 3856

# Connect button is clicked

nginx.1     | <keycloak-url>  - - [24/Sep/2022:12:56:40 +0000] "POST /realms/<realm-name>/login-actions/authenticate?session_code=***&execution=***&client_id=<client-name>&tab_id=*** HTTP/2.0" 302 0 
nginx.1     | <keycloak-url>  - - [24/Sep/2022:12:56:40 +0000] "POST /realms/<realm-name>/protocol/openid-connect/token HTTP/2.0" 200 3327 "-" "Java-http-client/18.0.1" 
nginx.1     | <keycloak-url>  - - [24/Sep/2022:12:56:40 +0000] "GET /realms/<realm-name>/protocol/openid-connect/userinfo HTTP/2.0" 200 131 "-" "Java-http-client/18.0.1" 
nginx.1     | <penpot-url>  - - [24/Sep/2022:12:56:40 +0000] "GET /api/auth/oauth/oidc/callback?state=***&session_state=*** HTTP/2.0" 302 0 
nginx.1     | <penpot-url> - - [24/Sep/2022:12:56:40 +0000] "GET / HTTP/2.0" 304 0 
nginx.1     | <penpot-url> - - [24/Sep/2022:12:56:41 +0000] "GET /api/rpc/query/profile HTTP/2.0" 200 68 
```

**Comment by Sahnvour** [comment]
It seems this is because I put `disable-registration` in the flags.
Apparently connecting via SSO requires this to be able to create and link a penpot account ; and penpot still identifies user mostly via email (for example to invite them to a team). Correct ?

**Comment by niwinz** [comment]
Yep, penpot identifies users via email right now.

In any case I'm not clearly understand the problem. 

About the `disable-registration` flag and the OIDC, it should work but for some reason does not work. I have this issue in my todo list but didn't get on it.

**Comment by niwinz** [comment]
Still unable to understand why you can't register new users through the OIDC path with `disable-registration` flag.
I have checked the code, in the `main` branch (1.15.x) and the `staging` (1.16.x) and the flag checking only happens on the `:prepare-register` RPC call. This call is only used on the standard, password based registration. OIDC module prepares the registration token itself without using this RPC call. I also have tested it and it works as expected. I can properly register new user.

https://user-images.githubusercontent.com/843689/192788764-8e7b14e1-3a2d-4fe9-8568-c8faf17b9eff.mp4

**Comment by niwinz** [comment]
I gess it will be fixed on the next version.

**Comment by Sahnvour** [comment]
Hi @niwinz, sorry for not answering earlier, for some reason my notifications were shut.

I tried again with the latest image (1.16-beta) and the problem persists.

With `enable-registration disable-login enable-login-with-oidc`:
I can connect with oidc as expected, but the frontend shows a registration page which I don't want.
![image](https://user-images.githubusercontent.com/1806407/199121859-2a593826-5411-4959-a961-a7a7a58d9ea6.png)

With `disable-registration disable-login enable-login-with-oidc`:
I can try to connect with oidc, _but_ the login will not complete because when this is the first login with a specific account, penpot needs to create it internally but it's forbidden by the configuration (my hypothesis).
![image](https://user-images.githubusercontent.com/1806407/199122077-ebecbeee-9e0e-4ae8-9183-3cba47b3666e.png)
Trying to login via oidc will get me back to the login page without effect.
**However**, if I use an account that succeeded to login previously (with the other configuration), it works without issue.

Hope this helps.
