### ISSUE TITLE
Penpot icon adjustment

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#2333]
I was looking at the Penpot icon, but necessarily the favicon that would be used if the app had pwa support with installation. I saw that there was little margin space and I decided to adjust it using the grid. I left the example below.!
![Board-3.png](https://user-images.githubusercontent.com/47113005/192111650-f0c22194-eb8f-4a8c-8d48-a2a859079885.png)

I changed the white background to a green color found within the site itself and which is even used a lot.

**Comment by Waishnav** [comment]
Yes, I do think the Penpot logo has a lot of elements, which makes it challenging to recognize as a brand.

Take a look at the screenshot below. 
![image](https://user-images.githubusercontent.com/86405648/192133635-ad93b0fe-8cdf-42d1-8ee4-9d927fd27261.png)

What do you think? If you look at the top-left corner of the logo, I believe boldness is lacking.
Boldness, in my opinion, will stand for the impression of a powerful brand and community.

Though I might be mistaken.

**Comment by soutiagojose** [comment]
> Yes, I do think the Penpot logo has a lot of elements, which makes it challenging to recognize as a brand.
> 
> Take a look at the screenshot below. 
> ![image](https://user-images.githubusercontent.com/86405648/192133635-ad93b0fe-8cdf-42d1-8ee4-9d927fd27261.png)
> 
> What do you think? If you look at the top-left corner of the logo, I believe boldness is lacking.
> Boldness, in my opinion, will stand for the impression of a powerful brand and community.
> 
> Though I might be mistaken. 

So, on this screen, Penpot tries to get very close to Figma, but what it lacks is the safety margins that it either doesn't have or isn't well-designed for the brand's identity.

**Comment by superalex** [comment]
Thank you very much for your suggestions!, we will consider them if we rethink the brand image.

For this kind of community discussions where there are a lot of opinions you can also use https://community.penpot.app/

Regards!,
