### ISSUE TITLE
Text function bug

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#2334]
**To Reproduce**

- Click on the function button "Text (T)" or press the letter "T" on the keyboard to enable the function of writing a text

**Expected behavior**

By clicking on the function button or typing the letter on the keyboard, the function will be automatically enabled to start typing the text and, as expected, have an automatic adjustment of width and height.

**Actual behavior**

When clicking on the function button or typing the letter "T" on the keyboard, the function automatically starts in the selection format, in this case, to start typing, first select the text box area and for the function to do what is expected, you have to double click to enable the option to type with auto width and auto height.

Note: I don't know why, but there are times when a single click already enables the function as expected, but there are times when it starts with the function of selecting the text area.
 
**Desktop (please complete the following information):**
- Zorin OS 15.6 Lite
- Chromium 105.0.5195.102

**Environment (please complete the following information):**
- Host: https://design.penpot.app

**Comment by superalex** [comment]
Hello @allytiago 

I've been trying to reproduce this but I think it's working as expected:
- If you have no selection then T enables the text function
- If you select a text shape without selecting its content (for example using the left sidebar) T selects the text
