### ISSUE TITLE
Shared library responsiveness in assets tab

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#2335]
**To Reproduce**

1. Open the file of your choice
2. Click on "Resources"
3. Click on "Libraries"

**Expected behavior**

When clicking on the "Libraries" option, the window that will open will adjust the device's screen so that there is no information cut.

**Actual behavior**

When the library window opens, part of it is cut, for example, the close button and the bottom part of the window, being able to hide shared libraries that are lower.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/47113005/192112729-95ff0c57-a2ab-41cb-ba56-38e93cba76ef.png)

**Desktop (please complete the following information):**
- Zorin OS 15.6 Lite
- Chromium 105.0.5195.102

**Environment (please complete the following information):**
- Host: https://design.penpot.app

**Additional context:**

The problem happens when the page is not in full screen (F11) in the browser

**Comment by superalex** [comment]
Thank you very much for reporting @allytiago 

What screen resolution are you using?

**Comment by soutiagojose** [comment]
> Thank you very much for reporting @allytiago 
> 
> What screen resolution are you using?

1280x800

**Comment by superalex** [comment]
Thanks!,

I've just created a bug report to track this -> https://tree.taiga.io/project/penpot/issue/4265

I hope we can fix it soon,

Regards,

**Comment by hirunatan** [comment]
Fixed! You will see it in the next Penpot release.
