### ISSUE TITLE
Ctrl+S does not save the file

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#2337]
**To Reproduce**

1.  Press Ctrl+S

**Expected behavior**

Save the file

**Actual behavior**

As penpot does not have this command registered, nor did it block it, the browser understands that it is to save the html of the page locally.
 
**Screenshots**

![image](https://user-images.githubusercontent.com/47113005/192113507-3d56c7f5-3cab-46e6-b770-356022634b73.png)

**Desktop (please complete the following information):**
- Zorin OS 15.6 Lite
- Chromium 105.0.5195.102

**Environment (please complete the following information):**
- Host: https://design.penpot.app

**Additional context:**

A solution would be that by clicking Ctrl+S, the file would be saved at that moment without waiting for the auto save, or acting like figma, which notifies that the file will be saved automatically.
Also reserve the command so that the browser does not try to download the page in case the designer uses the command by mistake, as he is used to using it in other software.

**Comment by LauraWebdev** [comment]
Related: https://github.com/penpot/penpot/issues/2314

**Comment by superalex** [comment]
Thanks @allytiago 

Closing this one, as @LauraWebdev said we were speaking about this in the related #2314 :)
