### ISSUE TITLE
Add title attribute to colorpicker libraries bullets

### ISSUE THREAD

**Issue by lukew3** [uxbox/uxbox#2338]
**Is your feature request related to a problem? Please describe.**
When using a pallet with many similar colors, it would be useful to show hints as to what that color is before clicking on it.

**Describe the solution you'd like**
When selecting the color for a fill/stroke, I'd like the title of the color to show when I hover over it. This could be done by simply adding a title attribute to the html with the value being the name of the color. ie:
```
<div class="color-bullet tooltip tooltip-right is-library-color" alt="max-vol-color">...</div>
```
would become
```
<div class="color-bullet tooltip tooltip-right is-library-color" alt="max-vol-color" title="max-vol-color">...</div>
```

**Describe alternatives you've considered**
A custom popup could be used, but title attribute is much simpler and built into browsers. Another possibility is making the bullets matrix into a scrollable list with the color titles to the right of the bullets.

**Additional context**
My color palette looks like this:
![Screenshot from 2022-09-24 18-41-38](https://user-images.githubusercontent.com/47042841/192121108-5eb3dbff-5138-4efc-a5d5-d4ba5d676ac7.png)
Since the colors are similar it is hard to tell between some of them. I'd like it if a title attribute was added to each color bullet so that on hover, the title will be shown like this:
![Screenshot from 2022-09-24 18-44-49](https://user-images.githubusercontent.com/47042841/192121178-019b10e4-1ed6-4aba-8d43-90c24041db43.png)

**Comment by lukew3** [comment]
It looks like there are hints on hover for most buttons on the design panel. Should use the same component as these to show hints.

**Comment by superalex** [comment]
Thank you very much @lukew3 

We have to do a big refactor of the penpot tooltips system -> https://tree.taiga.io/project/penpot/us/2782

I've just added your suggestion as a quick-win related to the accesibility user story we have in the current sprint https://tree.taiga.io/project/penpot/task/4218 so it will be included in the penpot core very soon :)

Regards!,
