### ISSUE TITLE
Drop-Down inconcistent UI

### ISSUE THREAD

**Issue by Waishnav** [uxbox/uxbox#2339]
It is not a major problem, basically, it's a UI-UX problem that looks not good IMO.

The drop-down menu in the top left corner looks inconsistent if you see the last option i.e "+ Create new team"

Previous UI             |  New UI
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/86405648/192142418-799504dc-c9c4-42ea-978b-46b9ea4ab425.png)  |  ![](https://user-images.githubusercontent.com/86405648/192142478-35d5b1b1-2658-4fd5-8f02-5ef46b2016cd.png)

**Comment by rakshit087** [comment]
Which one os the preferred one?

**Comment by LauraWebdev** [comment]
In what way is it inconsistent?

**Comment by rakshit087** [comment]
I think it's about the + button.
One is having a background while other is not.

**Comment by Waishnav** [comment]
@LauraWebdev IMO the alignment of the + icon should look like the div above it.

**Comment by elhombretecla** [comment]
Hi all :)

It is a pleasure to have this type of conversation about Penpot design issues with the users themselves.
@Waishnav We have been working for days on a deep dashboard UI review polishing this type of design elements giving an aesthetic coherence.

Here is what it looks like now. This and many other improvements will be available soon.

![image](https://user-images.githubusercontent.com/1045247/193193251-b97469df-e9dc-4754-87ef-23d96b9e384d.png)

**Comment by Waishnav** [comment]
Can I work on this issue and make the changes the design team wanted??

**Comment by elhombretecla** [comment]
@Waishnav These UI changes have been done yet by our team. Will be deployed soon :)
