### ISSUE TITLE
Hand tool

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#2341]
**Is your feature request related to a problem? Please describe.**
One thing I miss in penpot is the hand tool to move me around the file without accidentally moving any object.
At the moment the penpot has two navigation bars to be able to move within the file, but in my usability, they are very limited.
The bar to move left or right, up or down sometimes doesn't work and when I use it, I end up activating the selection function.
![image](https://user-images.githubusercontent.com/47113005/192149939-789ca7a0-6ec0-4caf-bade-c1f7a1a878b2.png)

**Describe the solution you'd like**
In figma and other browser-based software, the hand tool function is activated by pressing the letter "H".
In inkscape, Ctrl+ Left, Right, Up or Down arrow does something similar.

Another function also present in inkscape, uses the mouse scroll button. When the mouse cursor is on the sidebar top or bottom, the scroll button will move in the file from top to bottom or bottom to top, but when the cursor is on the scrollbar from left to right, the scroll button mouse scrolling will make it move left to right or right to left

**Additional context**
In Photopea, Ctrl+Scroll moves the file from left to right or right to left

**Comment by superalex** [comment]
Hello!,

You have different options to navigate the viewport :)

![image](https://user-images.githubusercontent.com/1579633/192445149-f6aea997-ed0a-4c58-bca0-4ab40bad504f.png)

Regards,

**Comment by jesperordrup** [comment]
still missing the handtool

**Comment by PatrikFomin** [comment]
If holding the middle mouse button down produces this "hand tool" while holding it down, why not just add a hand tool to the menu? (The functionality is already be there, just not exposed)
I am also for team "Hand tool button"

**Comment by kissgyorgy** [comment]
Even though I used this feature in a couple of months before, I forgot about it and spent a couple of minutes looking for the hand tool. I gave up and a Google search got me to this issue.

A Hand tool is a familiar concept for everyone who already worked with design tools, it makes sense to add it to the toolbar.
