### ISSUE TITLE
Typography's line-height in specific unit of measurement

### ISSUE THREAD

**Issue by ant0nioli** [uxbox/uxbox#2350]
Would be useful to have the possibility of specifying a font line-height in px or rems, to reproduce designs based on specific _vertical rhythm_.

![image](https://user-images.githubusercontent.com/1677823/192340778-e97771e4-1ee0-48ff-b354-ac9bc089013e.png)

Love this project. Thanks to the team!

**Comment by superalex** [comment]
Thank you very much @ant0nioli 

This one exists yet in our backlog https://tree.taiga.io/project/penpot/us/2328 I hope we can prioritize it and work on it soon :)

Regards,

**Comment by ant0nioli** [comment]
Great @superalex
Felicidades a todo el equipo, me encanta como trabajáis!
