### ISSUE TITLE
The Font line-height seems to be inconsistent

### ISSUE THREAD

**Issue by ant0nioli** [uxbox/uxbox#2351]
**To Reproduce**

Steps to reproduce the behavior
Create a Typography with:
- font-size: 16
- line-height: 1.5 (this should result in 24px)
Add a grid like this
- ![image](https://user-images.githubusercontent.com/1677823/192342113-60e99aca-8a5e-46bd-8b9d-86c98d21fefb.png)

**Expected behavior**
The lines should respect the grid
![image](https://user-images.githubusercontent.com/1677823/192342398-8e546e97-c612-4404-8944-1b967fd6d411.png)

**Actual behavior**
The lines does not respect the grid
![image](https://user-images.githubusercontent.com/1677823/192341959-5c710a79-bc8a-4ac8-947e-8ac7d5e841f5.png)

**Comment by superalex** [comment]
Thanks @ant0nioli 

It seems like a but, I've just created a bug on Taiga to track this -> https://tree.taiga.io/project/penpot/issue/4263

**Comment by superalex** [comment]
Hello @ant0nioli I've been working on this and it seems a chrome issue with the text-rendering: geometricprecision attribute for texts. You can check it here: https://codepen.io/alejandro-alonso-fern-ndez/pen/YzjqYRK

If you enable the "text-rendering: geometricprecision;" the problem with the height appears again. We are removing that attribute from the texts generated in penpot.

Thanks!

**Comment by ant0nioli** [comment]
Hello @superalex , actually I detected this issue using Firefox, never Chrome. So I'm not sure the issue can be closed.

Thanks!

**Comment by superalex** [comment]
Hello @ant0nioli,  could you please attach a exported .penpot file showing the issue?

Thanks!
