### ISSUE TITLE
Upload chinese font file never finished

### ISSUE THREAD

**Issue by Semonxue** [uxbox/uxbox#2353]
**To Reproduce**

1.  Go to 'Dashboard'
2.  Click on 'Font'
3.  Select a Chinese font file about 19M then click upload button
4. The uploading is not over for a long time.

**Expected behavior**

A Chinese font is uploaded.

**Actual behavior**

The uploading never finish.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/372518/192422519-1baca4d8-1212-4db4-be46-c790af7cfe4e.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): Mac OS 12.6
- Browser & version (e.g. Chrome 89.0): Chrome  105.0.5195.125

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): This appears in Saas and  latest docker version.

**Comment by Semonxue** [comment]
I attached the one of the font I tried as a attachment. It works well on a english font. Don't know if is the size matter. 
[bHEI00M.ttf.zip](https://github.com/penpot/penpot/files/9651179/bHEI00M.ttf.zip)

**Comment by superalex** [comment]
Hello @Semonxue 

Yesterday we deployed a fix for this one (it was related to the generation of woff2 format for big font files). I've just tried to upload your included font and it works :)

![1](https://user-images.githubusercontent.com/1579633/192441041-e2f40bb4-f7d6-4930-9c3a-4d61619e68d3.png)

**Comment by Semonxue** [comment]
> Hello @Semonxue
> 
> Yesterday we deployed a fix for this one (it was related to the generation of woff2 format for big font files). I've just tried to upload your included font and it works :)
> 
> ![1](https://user-images.githubusercontent.com/1579633/192441041-e2f40bb4-f7d6-4930-9c3a-4d61619e68d3.png)

Thanks. Great news.
