### ISSUE TITLE
Setup Commitlint to enhance the developer experience

### ISSUE THREAD

**Issue by KashishLakhara04** [uxbox/uxbox#2354]
### What needs to be done?

- Setup Commitlint and Configure commitlint to use conventional config ``@commitlint/config-conventional``
 ### How Commitlint helps?

- Commitlint helps your team adhere to a commit convention. By supporting npm-installed configurations it makes sharing of commit conventions easy.
### Resources

- Guide to [Commitlint setup](https://commitlint.js.org/#/guides-local-setup)
- Learn more about [Conventional Commit Message](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by niwinz** [comment]
Is commitlint allow custom guidelines? I mean, we use different identifiers for designate bugs, features, etc... and right now there are no relevant reason for change it. If commitlint supports custom guidelines, we will gladly accept a PR that improves the developer experience.
