### ISSUE TITLE
Support for OKHSL and/or related colour spaces

### ISSUE THREAD

**Issue by kj** [uxbox/uxbox#2355]
I would love to see support for perceptual colour spaces like OKHSL (my preference for ease of use, similarity in concept to HSL) which make it much easier to pick consistent colours. Some references:

https://bottosson.github.io/posts/colorpicker/
https://bottosson.github.io/posts/oklab/
https://bottosson.github.io/misc/colorpicker/
https://oklch.evilmartians.io/
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch
https://culorijs.org/color-spaces/

![20220927_19h17m26s_grim](https://user-images.githubusercontent.com/628170/192447707-ec23c349-8c15-404c-97c4-fb3977aa98cf.png)

**Comment by superalex** [comment]
Hi @kj !

Thank you very much for your feedback, we will consider it and prioritize it according to our roadmap :)

Regards,

**Comment by kj** [comment]
@superalex Where would I be able to watch out for this? Will it show up here?

https://tree.taiga.io/project/penpot/search?text=picker

**Comment by Nova38** [comment]
Hi is there any documentation on how to be able to use to use oklab and it's variants? Searching the whole repo only brought up this issue and it didn't seem to be available when I tried in the app

**Comment by Nova38** [comment]
Is there any plan to expand the design tokens to support them as it looks like penpot only implemented some of the color spaces that are in the design tokens specification according to the docs

https://help.penpot.app/user-guide/design-tokens/#design-tokens-available
```
RGB: rgb(255, 0, 0)
RGBA: rgba(255, 0, 0, 1)
ARGB: #80FFFF00 (also known as Hex8)
HSL: hsl(120, 50%, 50%)
HSLA: hsla(120, 50%, 50%, 1)
```

https://tr.designtokens.org/color/#supported-color-spaces

**Comment by wraybowling** [comment]
I fear that this is one of those features that was tossed out when the penpot team decided to abandon native browser rendering in favor of canvas. Meanwhile actual P3 color support and the need for modern designs to use it has only increased. There's a Figma plugin for an "advanced color picker" now but it's not native low level support. [Excitement for the new colorspace is picking up](https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl), but to understand it well you need a solid colorpicker. It'd be a big win if Penpot can be first.
