### ISSUE TITLE
Add expand appearance

### ISSUE THREAD

**Issue by ahelja** [uxbox/uxbox#2356]
**Describe the solution you'd like**
It would be nice to implement an adobe illustrator killer feature, "expand appearance", this feature would lead many graphics to use penpot (note this feature is not present in sketch, adobe XD or figma)

**Additional context**
The Illustrator expand appearance option changes shapes, texts, brush strokes, etc. into different vector objects with editing points

**Comment by superalex** [comment]
Thanks!,

I've just created an enhancement request to track this -> https://tree.taiga.io/project/penpot/issue/4264
