### ISSUE TITLE
Requesting to join Translation team at Weblate for Tamil

### ISSUE THREAD

**Issue by kbdharun** [uxbox/uxbox#2357]
I request to join the Translation team for Penpot at Weblate.

- My name: K.B.Dharun Krishna
- Language: Tamil (ta) 
- Translation type: New language
- Weblate profile: <https://hosted.weblate.org/user/kbdharunkrishna>.
- Weblate Username: kbdharunkrishna
- Reference: <https://help.penpot.app/contributing-guide/translation>.

**Comment by myfunnyandy** [comment]
Hi!

We've already added you to the translation project and also the Tamil language at the languages list. It always makes us really happy to add a new language! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/ta/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
