### ISSUE TITLE
Drag&Drop not working for objects within the layer hierarchy

### ISSUE THREAD

**Issue by mkuenzl** [uxbox/uxbox#2358]
**To Reproduce**

1.  Create a new project (or use existing one) 
2.  Create two boards in the same page
3.  Add an object to board_1 
4. Move object per Drag&Drop within the layer hierarchy from one board to the other

**Expected behavior**

The object should move from board_1 to board_2 within the hierarchy.

**Actual behavior**

The object does not move between the boards. It is only possible to move board_1 into board_2 within the hierarchy.
 
**Screenshots**

![BugReport-DragDrop-Feature-2022-09-27 at 09 52 17](https://user-images.githubusercontent.com/33060049/192469525-475e92ab-6fe4-404d-9433-fb14488a6118.png)

**Desktop (please complete the following information):**
- OS (e.g. iOS): macOS Monterey
- Browser & version (e.g. Chrome 89.0): Firefox (105.0.1), Chrome (105.0.5195.125 ARM), Opera (91.0.4516.20)

**Comment by myfunnyandy** [comment]
Hi, this is a [known bug](https://tree.taiga.io/project/penpot/issue/4209) and we will try to fix it ASAP.

**Comment by superalex** [comment]
Hi @mkuenzl 

He have just deployed a fix for this to https://design.penpot.app and it should be working again 

Thank you very much!
