### ISSUE TITLE
Requesting to join Translation team at Weblate for Croatian

### ISSUE THREAD

**Issue by zjuranko** [uxbox/uxbox#2359]
I request to join the Translation team for Penpot at Weblate.

My name: Zvonimir Juranko
Language: Croatian (HR)
Translation type: New language
Weblate profile: https://hosted.weblate.org/user/zjuranko/
Weblate Username: zjuranko

**Comment by myfunnyandy** [comment]
Hi @zjuranko!

You have already been added you to the translation project and also the Croatian language at the languages list, it is a new one. Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/hr/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much!
