### ISSUE TITLE
Middle button panning can drag guides

### ISSUE THREAD

**Issue by ant0nioli** [uxbox/uxbox#2369]
**To Reproduce**

- Place a vertical or horizontal guide
- Zoom in the work area, and start panning near the guide with the middle mouse button

**Expected behavior**
If you accidentally click the middle button on the guide to pan the view, the guide will be dragged.

**Actual behavior**
The middle button should not drag and drop the guides, should behave with the guides the same way it behaves with other elements.

**Comment by LauraWebdev** [comment]
In general, it would be neat to lock the guides somehow.

**Comment by superalex** [comment]
Thank you very much!,

I've just created a bug report on Taiga to track this -> https://tree.taiga.io/project/penpot/issue/4266

**Comment by superalex** [comment]
Sorry @LauraWebdev 

This one was solved some releases ago but we forgot to close it.

Thanks!
