### ISSUE TITLE
Export failing

### ISSUE THREAD

**Issue by LauraWebdev** [uxbox/uxbox#2373]
**To Reproduce**

1.  Open the penpot project
2.  Export as .penpot

**Expected behavior**

The workspace exports the penpot file or alternatively gives me any sort of error message.

**Actual behavior**

The pencil icon changes to a red cross.

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows latest
- Browser & version (e.g. Chrome 89.0): Microsoft Edge latest (Chromium)

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): design.penpot.app

**Additional context:**

The project has a large number of graphics (>7000 small svg's), so that might be the case.

**Comment by superalex** [comment]
Hi @LauraWebdev !

Could please indicate what's the file url?

**Comment by LauraWebdev** [comment]
Hey @superalex, it's this project: https://design.penpot.app/#/workspace/94d46040-3f3b-11ed-b414-cf2300df1f4f/9d309710-3f34-11ed-bf98-c67f7655c7b3?page-id=9d309711-3f34-11ed-bf98-c67f7655c7b3

**Comment by superalex** [comment]
Thanks!, just one more test, could you please check in the javascript browser console what kind of error are you receiving?

**Comment by LauraWebdev** [comment]
None, the console stays empty.

![image](https://user-images.githubusercontent.com/7365286/192830297-f390fca0-22ad-4675-8ec0-8cac73ccec2d.png)

![image](https://user-images.githubusercontent.com/7365286/192830336-8ad21208-0df5-47a7-9826-3567d5876f6a.png)

**Comment by superalex** [comment]
Sorry, I would like to see the network tab, something like this:
![1](https://user-images.githubusercontent.com/1579633/192830528-1f64de9f-d48c-487e-900d-b01dbf10e340.png)

**Comment by LauraWebdev** [comment]
![image](https://user-images.githubusercontent.com/7365286/192831074-d74a77ea-e100-46d3-ae62-b65a273a3eb9.png)

The reply has no body, potentially, exporting takes too long and times out? The network request sends back http 504 exactly one minute after initiation.

**Comment by superalex** [comment]
Yes, that's what it seems to be happening, thank you very much, let me see what we can do :D

**Comment by LauraWebdev** [comment]
Hoping for the best, wanted to export the project to create an MR in the penpot-files repo :D

**Comment by superalex** [comment]
<3 <3 <3

Thank you very much!

**Comment by superalex** [comment]
As a workaround I could manually export your file, if you want I can upload it here too :)

(the file just about 1MB but processing so many elements in the export process seems to be very time consuming now)

**Comment by LauraWebdev** [comment]
That would be lovely!

**Comment by superalex** [comment]
Sure! :)

[material-design-icons.penpot.zip](https://github.com/penpot/penpot/files/9667336/material-design-icons.penpot.zip)

**Comment by superalex** [comment]
I've created a bug on Taiga to manage this -> https://tree.taiga.io/project/penpot/issue/4252

**Comment by LauraWebdev** [comment]
![image](https://user-images.githubusercontent.com/7365286/196785611-b4ecb515-9629-481f-afba-ec17094b998c.png)

Looking great!
