### ISSUE TITLE
Custom font is failing to load for existing project

### ISSUE THREAD

**Issue by udany** [uxbox/uxbox#2374]
**To Reproduce**

1.  Create a document with a custom font
2.  Update the page
3.  The texts that used the custom font are now all buggy and wont render correctly

**Expected behavior**

Custom fonts should work

**Actual behavior**

They don't once you reopen the project
 
**Screenshots**

https://user-images.githubusercontent.com/6425637/192841458-b11e0e73-e113-4542-b2ab-28568927714a.mp4

**Desktop (please complete the following information):**
- OS: Windows
- Browser & version: Chrome 105

**Environment (please complete the following information):**
- Host: https://design.penpot.app

Frontend Stack Trace:

```
INF [app.util.i18n] hint="locale changed", locale="en"
2logging.cljc:325 WRN [app.main.fonts] msg="no implementation found for", backend=nil
/fonts/-normal-900.woff:1          Failed to load resource: the server responded with a status of 404 ()
/fonts/-normal-400.woff:1          Failed to load resource: the server responded with a status of 404 ()
fonts.cljs:187 [debug:fonts]: loading custom font custom-688b6801-2981-11ed-b087-9bb55d5a0d4e
Failed to decode downloaded font: <URL>
OTS parsing error: cmap: Failed to parse table
Cannot load fontcustom-688b6801-2981-11ed-b087-9bb55d5a0d4e DOMException: A network error occurred.
(anonymous)	@	text_svg_position.cljs:60
```

**Comment by superalex** [comment]
Hello @udany 

Could you please indicate the url of your file?

And more question, if you go to your custom fonts settings, that font appears?
![1](https://user-images.githubusercontent.com/1579633/192859447-7d576113-29f9-420a-a453-f1412f543207.png)

**Comment by udany** [comment]
> Could you please indicate the url of your file?

Hey @superalex, sorry for taking so long, you can see this happening [here](https://design.penpot.app/#/workspace/6beaee30-27f6-11ed-9977-c67f7655c7b3/75f26f70-296d-11ed-b8ab-cf2300df1f4f?page-id=75f26f71-296d-11ed-b8ab-cf2300df1f4f) (6beaee30-27f6-11ed-9977-c67f7655c7b3/75f26f70-296d-11ed-b8ab-cf2300df1f4f?page-id=75f26f71-296d-11ed-b8ab-cf2300df1f4f)

> And more question, if you go to your custom fonts settings, that font appears? !

Yes it does
![image](https://user-images.githubusercontent.com/6425637/194159474-94d2a4b7-d468-4c10-8086-8e46a08af889.png)

**Comment by udany** [comment]
I have also figured that it only happens when you load a project directly (i.e.: accessing the /workspace/ url directly), if you open it going through the dashboard beforehand it doesn't happen

**Comment by superalex** [comment]
Hello @udany 

Thank you very much for your help, finally I could reproduce the issue and fix it (https://tree.taiga.io/project/penpot/issue/4874). It should be working ok right now :)
