### ISSUE TITLE
Custom font upload has inconsistent description and fails silently for unsupported formats

### ISSUE THREAD

**Issue by ion-tichy** [uxbox/uxbox#2376]
**To Reproduce**

1.  Go to 'https://design.penpot.app/#/dashboard/team/<team_id>/fonts' and you will see the following:
![Screenshot 2022-09-29 at 01-54-16 Penpot Design Freedom for Teams](https://user-images.githubusercontent.com/840585/192908876-520661de-c539-4406-bd10-4da01ef71a64.png)

2.  When trying to upload a `.woff` fontfile, the upload will fail silently (--> an error message indicating incorrect file-format would be helpful!)

3. The [documentation](https://help.penpot.app/user-guide/custom-fonts/) indicates:
  ![Screenshot 2022-09-29 at 01-53-53 15· Custom fonts](https://user-images.githubusercontent.com/840585/192909014-f163c9b3-9673-4269-bb03-3c52df155dca.png)

So apparently, only `.ttf` and `.otf` files are being supported?

**Expected behavior**

The helptext in the app should match the documentation.  
Additionally, if one were to upload a font-file that has the wrong format or extension: display an error message instead of failing silently.

**Actual behavior**

When trying to upload a `.woff`, which is mentioned as a supported format, the upload fails silently.

**Desktop (please complete the following information):**
- OS: Win7
- Browser & version: Firefox 104.0.2

**Smartphone (please complete the following information):**
- Device & model (e.g. iPhone 6):
- OS & version (e.g. iOS 8.1):
- Browser & version (e.g. stock browser 22):

**Environment (please complete the following information):**
- Host: https://design.penpot.app

**Remarks**
Apart from the docstring inconsistency, my main gripe is just the missing verbosity when the upload is not supported/goes wrong.

**Comment by superalex** [comment]
Hello @ion-tichy 

I've just tried to upload a woff file and it worked, is it possible you are uploading an invalid file?, could you also include the problematic woff file?

**Comment by ion-tichy** [comment]
I inspected the problematic file and it was indeed not a valid woff, sorry for that.

Another try with a confirmed valid woff file worked.

Nevertheless, might be a good idea showing some kind of error message in case of invalid files.

Thanks for checking aswell!

**Comment by superalex** [comment]
I agree @ion-tichy 

I've just created a bug report here to track it -> https://tree.taiga.io/project/penpot/issue/4280

Regards,
