### ISSUE TITLE
New GitHub Issue Label Request: "good-first-issue"

### ISSUE THREAD

**Issue by austinatchley** [uxbox/uxbox#2377]
**Is your feature request related to a problem? Please describe.**
This is not related to a specific problem, it's more of a feature request for the project management of this repo. 

I found this project on Hacker News, as it looks like many others have recently. In open source projects I've been new to in the past, it has been helpful to be able to search the existing issues for a label like "good-first-issue" to find a good entry point to working on the project. I suspect with all the visibility this project is getting from Hacker News and TechCrunch, you could probably use such a "good-first-issue" label to draw new contributors in.

**Describe the solution you'd like**
New label for issues in this repo, using a name like "good-first-issue"

Someone who has deep knowledge of the backlog of issues in this repo could assign this label to several issues they feel it would fit for.

**Comment by superalex** [comment]
Thanks for your suggestion @austinatchley 

We use Taiga to manage the project, issues created here are filtered and created there too. We have the tag "beginner-friendly" for that purpose https://tree.taiga.io/project/penpot/issues?order_by=-priority&tags=beginner-friendly

Regards!,

**Comment by austinatchley** [comment]
That's great, thanks for pointing me in the right direction!
