### ISSUE TITLE
Ability to flatten text

### ISSUE THREAD

**Issue by harshzalavadiya** [uxbox/uxbox#2378]
**Is your feature request related to a problem? Please describe.**
Most times when you are shipping small designs which only contains 2-3 charactors as of now penpot has no way of converting it to text to shape (called flatten in figma)

**Describe the solution you'd like**
Ability to flatten text to shape at runtime/while exporting

**Describe alternatives you've considered**
sadly, as of now there's no way

**Additional context**
This is very useful when you are trying to export logos etc. into svg

![Recording 2022-09-29 at 15 01 11](https://user-images.githubusercontent.com/5774849/192996587-ff91f1ef-025f-4550-985d-6bd688fbed08.gif)

**Comment by superalex** [comment]
Thank you very much @harshzalavadiya 

This one existed as user story in our backlog https://tree.taiga.io/project/penpot/us/3180

I've just added your comments there
