### ISSUE TITLE
[Language Request] Ukrainian (uk-UA)

### ISSUE THREAD

**Issue by dector** [uxbox/uxbox#2383]
Please add **[new]** Ukrainian language to Weblate project.
User: https://hosted.weblate.org/user/dectorm/

**Comment by superalex** [comment]
Hi @dector !

You have already been added you to the translation project and also the Ukrainian language at the languages list, it is a new one. Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/ukr_UA/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much!

**Comment by maxuiux2** [comment]
Hi @superalex I wish to help with Ukrainian translation.
https://hosted.weblate.org/user/mmaks.step/
