### ISSUE TITLE
Able to replace image

### ISSUE THREAD

**Issue by quangson91** [uxbox/uxbox#2385]
Currently, I can upload png/jpeg to the Penpot.

After the image is uploaded, I found that there is no way to `replace` that image.
So it would be great if we can replace the uploaded image.

Eg usecase:

- Upload Image - `A`.
- Mask `A` with some special shape
- Put it in to the PhoneFrame -> get `RESULT`

-> Now, I would like to duplicate `RESULT`. Then I want to replace image `A` with another.

**Comment by superalex** [comment]
Thank you very much for suggestion @quangson91 

This is included in one of the next futures we would like to include (https://tree.taiga.io/project/penpot/us/2983?backlog-q=image&no-milestone=1). I've linked this enhancement there.

Regards!,
