### ISSUE TITLE
Penpot doesn't work with proxy_path and nginx

### ISSUE THREAD

**Issue by IvoPo** [uxbox/uxbox#2389]
**To Reproduce**

1.  Go to `config.env` and add `PENPOT_PUBLIC_URI=https://FQDN/penpot`
2.  add proxy location to nginx config
3.  open website and get 404s

**Expected behavior**

The proxy path of the URI should be replicated in the frontend webserver

**Actual behavior**

The /penpot is missing from all ressources and produces 404s
 

*self-hosted:*
- Docker / Docker-compose version 20.10.18 / 1.29.2
- Image version: latest

Frontend Stack Trace:
![image](https://user-images.githubusercontent.com/5849142/193278458-bfe0f4c9-47cd-4e28-b30c-060a1a1c44e0.png)

one of the Nginx location codes i tried:
```
    location /penpot {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header HTTPS on;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_redirect off;
        proxy_pass http://localhost:9001/;
```

**Comment by knowald** [comment]
Seems that relative/subpath routing has been mentioned as an untested thing in a [relevant issue](https://github.com/penpot/penpot/pull/2223)

I've been curious what the compose `PENPOT_PUBLIC_URI` env var is used for, can't find it used anywhere?
Looks like it should be forwarded to `global.penpotPublicURI` [here](ttps://github.com/penpot/penpot/blob/develop/frontend/src/app/config.cljs#L115) but it can't be configured currently if i understand correctly.

Trying to figure out here if the `public-uri` generated path is used for the CSS/JS files though?

**Comment by niwinz** [comment]
Penpot is not tested to work correctly on prefix path.

> Seems that relative/subpath routing has been mentioned as an untested thing in a [relevant issue](https://github.com/penpot/penpot/pull/2223)
> 
> I've been curious what the compose `PENPOT_PUBLIC_URI` env var is used for, can't find it used anywhere? Looks like it should be forwarded to `global.penpotPublicURI` here but it can't be configured currently if i understand correctly.
> 
> Trying to figure out here if the `public-uri` generated path is used for the CSS/JS files though?

The PENPOT_PUBLIC_URI env var is used as is in backend. Frontend can't read environment variables because it executes on the user browser. So the official frontend docker image reads the environement vars and build the js/config.js where the penpotPublicURI is set.
