### ISSUE TITLE
WARN[0000] The "PENPOT_FLAGS" variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by 403-html** [uxbox/uxbox#2391]
**To Reproduce**

1.  Download config.env & docker-compose.yaml as stated in docs
2. Make sure you've pruned volumes and images in docker with penpot if you had any
3. Change L13 to `PENPOT_FLAGS="$PENPOT_FLAGS disable-registration"` in config.env
4. Run `docker compose -p penpot -f docker-compose.yaml up -d`

**Expected behavior**

Flags should be taken into consideration, while building app. 

**Actual behavior**

Right after calling docker compose I get
```sh
WARN[0000] The "PENPOT_FLAGS" variable is not set. Defaulting to a blank string.
WARN[0000] The "PENPOT_FLAGS" variable is not set. Defaulting to a blank string.
WARN[0000] The "PENPOT_FLAGS" variable is not set. Defaulting to a blank string.
```
 
**Screenshots**

<img width="619" alt="image" src="https://user-images.githubusercontent.com/57900160/193316430-30be46c4-fb6d-4924-bc14-a316fbc3adb6.png">

*If self-hosted:*
- OS (e.g. iOS): MacOS 12.6
- Docker: `Docker version 20.10.18, build b40c2f6b5d` && `Docker Compose version 2.11.1`
- Image version (e.g. Alpine): current image from `https://raw.githubusercontent.com/penpot/penpot/main/docker/*` so I assume 1.15.0-beta?

**Comment by knowald** [comment]
This is your attempt to use the unexisting `$PENPOT_FLAGS` variable in the initial creation of it 😄

The example of including `$PENPOT_FLAGS` is meant to be used to append a new string to an existing string variable. 
```
// This assigns an initial value to the var
FOOBAR="foo bar"
// This creates a new string inserting the existing value into the new string
FOOBAR="$FOOBAR baz"
// The result is now $FOOBAR containing
// "foo bar baz"
````

If you've removed the initial value of the variable the warning is raised because it ends up as
`PENPOT_FLAGS = undefined + " disable-registration"`

The example in the documentation means to include the value `disable-registration` along your other flags.
```
// Either append the new string to the existing variable
PENPOT_FLAGS="disable-secure-session-cookies enable-login"
PENPOT_FLAGS="$PENPOT_FLAGS disable-registration"

// Or just add it to the variable initialization
PENPOT_FLAGS="disable-registration disable-secure-session-cookies enable-login"
```

**Comment by 403-html** [comment]
I... damn, didn't think of it, or forgot how it works... thanks!
