### ISSUE TITLE
Show color names instead of hex code in color palette drawer

### ISSUE THREAD

**Issue by schalkneethling** [uxbox/uxbox#2394]
**Is your feature request related to a problem? Please describe.**

When expanding the color palette drawer at the bottom of PenPot it shows the hex values even though the colors have "variable" names.

![color palette drawer showing a list of color swatches with hex values below each swatch](https://user-images.githubusercontent.com/10350960/193457303-ee0c19b7-7c45-479f-bfb7-902b925d3744.png)

![colors displayed in the assets panel showing color names and hex codes](https://user-images.githubusercontent.com/10350960/193457337-ed56e9cc-a499-4059-a65d-a884430869f6.png)

**Describe the solution you'd like**

It would be great if the palette drawer displayed the color name if available.

**Describe alternatives you've considered**

N/A

**Additional context**

Screenshots provided as part of the description.

**Comment by schalkneethling** [comment]
I would be happy to work on this if there is someone that can give me some direction. :+1:

**Comment by laaksonel** [comment]
What you are looking for is `frontend/src/app/main/ui/workspace/colorpalette.cljs` which is the color palette component on the bottom of the UI.

There's a child component called `palette-item`
```
(mf/defc palette-item
  {::mf/wrap [mf/memo]}
  [{:keys [color]}]
  (letfn [(select-color [event]
            (st/emit! (mdc/apply-color-from-palette color (kbd/alt? event))))]
    [:div.color-cell {:on-click select-color}
     [:& cb/color-bullet {:color color}]
     [:& cb/color-name {:color color}]]))
```
What you want to do is to replace `color-name` with the actual name. `color` parameter is a map which contains the name entry already, just use it instead of `color` which is the hex value.

**Comment by superalex** [comment]
Thank you very much @laaksonel ,

When selecting the "file library" color names are shown, I'm checking with the UI team if this is the desired behavior.


https://user-images.githubusercontent.com/1579633/193506330-81afd7c9-39c1-4686-8d3a-d2789a058c86.mp4



Regards!,

**Comment by schalkneethling** [comment]
> What you are looking for is `frontend/src/app/main/ui/workspace/colorpalette.cljs` which is the color palette component on the bottom of the UI.

Thank you so much for this info!

**Comment by schalkneethling** [comment]
> When selecting the "file library" color names are shown, I'm checking with the UI team if this is the desired behavior.

I completely missed this option. What one can do in the code is to check whether the name exists. If it does, show it. If not, show the color code as a fallback. Let me know what the UX folks think. Thanks!

**Comment by EsterLatorre** [comment]
UXUI gives the green light for this, thanks very much!

**Comment by schalkneethling** [comment]
> UXUI gives the green light for this, thanks very much!

Thanks so much for getting back to me, @EsterLatorre. I will have a look at the code @laaksonel mentioned and get a PR ready.

**Comment by schalkneethling** [comment]
@superalex are you all working on this or is this something I can dig into?

**Comment by superalex** [comment]
@schalkneethling feel free to dig into!, thank you very much! :)

**Comment by schalkneethling** [comment]
> @schalkneethling feel free to dig into!, thank you very much! :)

So, the place to start is here https://help.penpot.app/technical-guide/developer/devenv/ and more specifically here https://help.penpot.app/technical-guide/getting-started/#install-with-docker, correct?

**Comment by schalkneethling** [comment]
@superalex I was thinking of using Gitpod as I saw a `gitpod` directory in the repo. When trying to add it as a workspace, I ran into the following error:

```
#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 3.50kB done
#2 DONE 0.0s
Dockerfile:118
--------------------
 116 |         PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com \
 117 |         PENPOT_DATABASE_URI="postgresql://localhost/penpot"
 118 | >>>     PENPOT_REDIS_URI="redis://localhost/0"
 119 |     
 120 |     # TODO Retrieve OpenLDAP from rroemhild/docker-test-openldap
--------------------
error: failed to solve: dockerfile parse error on line 118: unknown instruction: PENPOT_REDIS_URI="redis://localhost/0"
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","command":"build","error":"exit status 1","file":"build.go:44","func":"func1","level":"error","message":"build failed","serviceContext":{"service":"bob","version":""},"severity":"ERROR","time":"2022-10-12T22:36:53Z"}
exit

headless task failed: exit status 1
```

**Comment by hirunatan** [comment]
@schalkneethling I'm afraid that we are not actively maintaining the gitpod docker files. I've seen there was a typo and fixed it. Also upgraded some package versions.

You can try it again and see if it works now.
