### ISSUE TITLE
Error importing 

### ISSUE THREAD

**Issue by an0o0nym** [uxbox/uxbox#2397]
**To Reproduce**

1.  Go to https://penpot.app/libraries-templates.html
2. Download Penpot Design System FIle
3. Import Penpot Design System .penpot file to your drafts/projects

**Expected behavior**

It should import Penpot Design System into my drafts/projects without error.

**Actual behavior**
It throws an error when  importing .penpot file fo Penpot Design System.

It stops for a second at screenshot 1. only to yield an error shown in screenshot 2. few seconds later. 

P.S.
This does not only happen for Penpot Design System File but also for other .penpot files from the link above.
 
**Screenshots**

1.
![image](https://user-images.githubusercontent.com/5521113/193465720-26e319bd-f831-4211-aeb4-71ed5b8ce4e2.png)

2.
![image](https://user-images.githubusercontent.com/5521113/193465279-44d98fc3-4627-4ec9-9b75-4dc06689b256.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Browser & version: Firefox 105.0.1

**Environment:**
- Host: https://design.penpot.app

**Additional context:**
Console logs from Firefox terminal:

```
SEV [app.worker.import] hint="NetworkError when attempting to fetch resource.", file-id=#uuid "fa8af910-2035-11ec-9b8d-be64608333b9" [logging.cljc:325:12](https://design.penpot.app/js/app/common/logging.cljc)
```

![image](https://user-images.githubusercontent.com/5521113/193465507-9be8d878-cc52-4a9c-9f8f-d65a84b460a4.png)

**Comment by laaksonel** [comment]
I could not reproduce this problem (not in main branch nor develop). I also run Ubuntu 20.04 & Firefox 105.0

![image](https://user-images.githubusercontent.com/5064947/193474842-c161ef26-cac6-4fe6-81d5-06fe982290ec.png)

**Comment by superalex** [comment]
I could upload it ok (using https://design.penpot.app)

![1](https://user-images.githubusercontent.com/1579633/193507373-85ad736b-c99a-4040-a114-b3251c3c6929.png)

If it's happening with other files too...could it be a problem of your network? did you try with a different one?

**Comment by an0o0nym** [comment]
If anyone hits the same problem. I believe it was uBlock Origin that cause this to fail.
