### ISSUE TITLE
Translation access request (German / Polish)

### ISSUE THREAD

**Issue by knowald** [uxbox/uxbox#2400]
Hello, i'd love to contribute to this project!
I can help out with my two native languages: German and Polish :)

https://hosted.weblate.org/user/knowald/

Thanks for this great work! ❤️

**Comment by superalex** [comment]
Hi @Vesther  !

You have already been added you to the translation project.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much!
