### ISSUE TITLE
Translation: Faroese

### ISSUE THREAD

**Issue by Turmz** [uxbox/uxbox#2408]
Hi Penpot,

Language: Faroese
Type: New language
Username: Turmz

I would like to be able to translate the project into Faroese (The language spoken in the Faroe Islands).

Thank you.

**Comment by EsterLatorre** [comment]
Hi Turmz, 
We'd love you to help us with Faroese translations. Your user now has permissions to edit translations in Weblate. Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/
Thanks a lot!
