### ISSUE TITLE
bug: SVG loses color information

### ISSUE THREAD

**Issue by schalkneethling** [uxbox/uxbox#2422]
### Steps To Reproduce

1. Drag an SVG that has some color information into the app.
2. The SVG asset loses the color information is shown in all black

### Expected behavior

SVG should retain color information.

### Actual behavior

See step 2 of the steps to reproduce.

### Screenshots or video

https://user-images.githubusercontent.com/10350960/194718308-d36ea5ae-5211-44f3-b905-a4bcd404da27.mp4

### Desktop (please complete the following information)

- OS: macOS
- Browser: Arc Version 0.71.0 (35084) Chromium Engine Version 106.0.5249.103

### Environment (please complete the following information)

design.penpot.app

**Comment by EsterLatorre** [comment]
Hi schalkneethling,

I've added your bug to the backlog in Taiga, and you can track its progress from here: https://tree.taiga.io/project/penpot/issue/4310 We will try to fix it soon. 

Thanks for your feedback!

**Comment by schalkneethling** [comment]
> Hi schalkneethling,
> 
> I've added your bug to the backlog in Taiga, and you can track its progress from here: https://tree.taiga.io/project/penpot/issue/4310 We will try to fix it soon.
> 
> Thanks for your feedback!

Hey @EsterLatorre,

I see this is closed. Not sure if it is because it was transferred to Taiga. I ran into the same problem again, and it seems that the problem is when an SVG was exported from Adobe Illsutrator. I have dragged in other SVG elements and it retained the color information. I then made a change to it in Illustrator when dragging it back into Penpot, the color information is lost.

**Comment by pabloalba** [comment]
Hi @schalkneethling.
Is this still happening to you? If it fails, can you send us some svgs that fails?

Thank you!

**Comment by thomasfrobieter** [comment]
Same here, guess its this weird cdata color definition:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Creator: CorelDRAW X8 -->
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="314.638mm" height="100.081mm" version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
viewBox="0 0 31464 10008"
 xmlns:xlink="http://www.w3.org/1999/xlink">
 <defs>
  <style type="text/css">
   <![CDATA[
    .fil0 {fill:#ff0000}
    .fil1 {fill:#00ff00}
    .fil2 {fill:black;fill-rule:nonzero}
   ]]>
  </style>
 </defs>
 <g id="Layer_x0020_1">
  <metadata id="CorelCorpID_0Corel-Layer"/>
  <g id="_1979675438144">
   <polygon class="fil0" points="11763,583 2834,2020 2834,7988 11763,9425 11763,7728 12260,7728 12260,10008 2338,8411 2338,1597 12260,0 12260,2324 11763,2324 "/>
   <polygon class="fil1" points="9425,2020 496,583 496,9425 9425,7988 9425,7716 9922,7716 9922,8411 0,10008 0,0 9922,1597 9922,2324 9425,2324 "/>
  </g>
 </g>
</svg>
```


Example attached!
![logo_penpot_issue](https://user-images.githubusercontent.com/4060313/214907121-742256e4-3e6b-44ce-952f-5edbdfeb1c63.svg)

EDIT: Confirmed, its caused by this seperate CSS color definition .. re-exported it with my regular settings and it works well.
