### ISSUE TITLE
bug: Export two or more boards at the same time fails

### ISSUE THREAD

**Issue by aitormendez** [uxbox/uxbox#2424]
## Select two or more boards

![Captura de pantalla 2022-10-09 a las 10 24 03](https://user-images.githubusercontent.com/2788577/194746107-22046887-75e6-4dcc-8d89-b225b6c900f3.png)

## Export it

![Captura de pantalla 2022-10-09 a las 10 17 30](https://user-images.githubusercontent.com/2788577/194746015-021acaf0-295e-4eb1-9304-228ae6ba0fcd.png)

You get an internal error

![Captura de pantalla 2022-10-09 a las 10 15 11](https://user-images.githubusercontent.com/2788577/194746198-c8e9ea45-d526-45f0-bc2f-75ec72b61789.png)

### Expected behavior

Expected export boards

### Actual behavior

Get internal error

### Desktop (please complete the following information)

Macos 11.6.8
Firefox developer edition 106.0b9 (64-bit)

### Environment (please complete the following information)

https://design.penpot.app/#/workspace/a8a61641-6553-11eb-868f-03f8ac143bbf/132a7e80-46cf-11ed-a794-c67f7655c7b3?page-id=132a7e81-46cf-11ed-a794-c67f7655c7b3

**Comment by EsterLatorre** [comment]
H Aitor,

Could you please send us the file so we can see what is causing the issue? I'm not experiencing the same issue so it must be something from that file in particular. (We don't have permissions to access the file from a link, but if you export it we will be able to see it from here)

Thanks!

**Comment by aitormendez** [comment]
Hola, Ester. Aquí está el archivo .penpot [FSG JPI.penpot.zip](https://github.com/penpot/penpot/files/9744282/FSG.JPI.penpot.zip)

Muchas gracias.

**Comment by niwinz** [comment]
I have tested it and I was unable to reproduce it. Can the issue be reproduced consistently? I mean if you repear it right now still happens? I guessing a possible temporal glitch/fail of the exporter backend because right now I can export the both boards withou t any problem.
