### ISSUE TITLE
bug: Text "…contact with support" on "internal error" page

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#2427]
### Steps To Reproduce

inital state: (no clue how one creates the internal error page)

The text is 

> Internal Error
> Something bad happened. Please retry the operation and if the problem persists, contact with support.

### Expected behavior

Should be "Contact support"

### Actual behavior

Should not be: "Contact with support"

### Additional context

A link to the support would be nice. Or something like "contact the admin of this instance" (which is probably closer to what one can do – neither kaleidos nor normal community instances have support teams)

**Comment by niwinz** [comment]
Thanks, looks very reasonable. I have reported it internally: https://tree.taiga.io/project/penpot/issue/4329

**Comment by niwinz** [comment]
https://github.com/penpot/penpot/pull/2430 the text issue is already merged for the next version
