### ISSUE TITLE
feature: Pasting board inside other board

### ISSUE THREAD

**Issue by lorearwe** [uxbox/uxbox#2436]
### Is your feature request related to a problem? Please describe.

I'm working on my first project on penpot, since I used to work in Figma, maybe I'm too used to using boards inside boards. Still I think this is unintended behaviour.

1. Start by having a bunch of boards and some items (although it also works with empty boards). 
![image](https://user-images.githubusercontent.com/58910829/195086514-d13b9eca-6604-4ef9-b82d-2c206b0a8161.png)
2. Copy board 3.
![image](https://user-images.githubusercontent.com/58910829/195087617-48c0d506-baa6-48a4-96ad-881f551a47a9.png)
3. Select board 2. 
![image](https://user-images.githubusercontent.com/58910829/195086654-43e73a0b-049a-4da3-b54f-1d77332a19ee.png)
4. Paste.
![image](https://user-images.githubusercontent.com/58910829/195086419-bc96b3da-1857-4c3e-bd25-4262294c59be.png)
Board 5 is created outside the selected board.

### Describe the solution you'd like.

The new board (Board 5) should be pasted inside Board 2. Ideally,  as if pasting in place a non-board element.

![image](https://user-images.githubusercontent.com/58910829/195087493-6cc08167-ce35-4a60-9fe4-7148a27e81af.png)
![image](https://user-images.githubusercontent.com/58910829/195087526-7450d568-ef69-4549-9f36-c9349c992944.png)

**Comment by superalex** [comment]
Thank you very much @lorearwe 

This one was solved some hours ago https://github.com/penpot/penpot/pull/2413 and will be deployed to production as soon as possible :)

Regards!,
