### ISSUE TITLE
feature: Change CTRL-S Functionaloty

### ISSUE THREAD

**Issue by nathan-a-macleod** [uxbox/uxbox#2438]
### Is your feature request related to a problem? Please describe.

This is just a small enhancement

### Describe the solution you'd like.

When you press CTRL-S currently it opens a page so you can download the webpage as an HTML file (which is the default behaviour). 
It would be much better if this did the same as it does in Figma, which is to either do nothing, or to save the actual file into your penpot account, rather than opening up the current dialogue box.

### Describe alternatives you've considered.

N/A

### Additional context

I'm fairly sure this can be done with a couple lines of javascript (basically cancelling the default behaviour of CTRL-S/CMD-S so it should be a very easy thing.

**Comment by LauraWebdev** [comment]
I agree and there have been multiple issues on this exact behaviour, but the team responded that they don't want to override browser shortcuts by their own shortcuts.
