### ISSUE TITLE
feature: Better documentation on data format

### ISSUE THREAD

**Issue by KlausSchaefers** [uxbox/uxbox#2439]
### Is your feature request related to a problem? Please describe.

Hi,

I am trying to support Penpot in the Luisa framework (https://luisa.cloud/). I was trying to reverse engineer the REST API, but for me the data structure is not clear. It´s quite different from the JSON Figma or Sketch produce...

I often see that there or some arrays like

["^ ", "~:y", 113, "~:hide-fill-on-export", false, "^O", 0, "^P",…]
I assume this is a list of key value pairs. But I would like to confirm this. Are there somewhere schema defined?

### Describe the solution you'd like.

I would like to be able to parse the REST service.

### Describe alternatives you've considered.

Getting some SVG oder JSON object based API.

**Comment by niwinz** [comment]
The api output uses transit format. On the end is a valid JSON using the most optimized data stuctures with cached prop names. You can use a library for correctly parsing it:  https://github.com/cognitect/transit-js.
Also you can use the `&transit_verbose=1` query parameter for more verbose/human readable transit format output
