### ISSUE TITLE
feature: Export multiple boards as single PDF

### ISSUE THREAD

**Issue by nimishavijay** [uxbox/uxbox#2444]
### Is your feature request related to a problem? Please describe.

I used Penpot to make a slide deck for a presentation (and it works great for that!), using one board for one slide. When I was done I wanted to get one nice PDF of all my boards, instead each board was exported individually as a separate PDF, compressed into a zip files, which I then had to extract and merge using another software.

### Describe the solution you'd like.

When multiple boards are selected and "Export" is clicked with the PDF option selected, it would be nice to be able to export them all as one PDF, with possibly the ability to reorder them as well.

It can look something like this
![image](https://user-images.githubusercontent.com/52440189/195583739-6eb6b321-3f36-4498-9925-a762e2431f7b.png)

Drop down would have "Export as single PDF" and "Export as multiple PDFs"  

### Additional context

This would vastly increase the use cases for Penpot, for eg. creating resumes, slide decks, any reports, etc.

**Comment by elhombretecla** [comment]
Hi @nimishavijay please let us know if the current "File -> Export artboards to PDF" at the file menu works for you.

![image](https://user-images.githubusercontent.com/1045247/196050500-4a0c3701-a864-4979-ae0c-d08a46670b41.png)

![image](https://user-images.githubusercontent.com/1045247/196050512-a015bd89-fd75-449a-965d-4c09602104fa.png)

**Comment by nimishavijay** [comment]
It does! I was not able to discover this feature as my current flow is:
1. select boards
2. go to "Export selection" in right sidebar
3. set to PDF
4. click export 
5. confirm in the modal

Perhaps integrating it into the existing export section in the right sidebar would help its discoverability

**Comment by elhombretecla** [comment]
Ok great. Good to know :)

Export options on the right sidebar are to manage exports at object level. Menu PDF export option is at file level.

Anyway we are going to track this behaviour in order to improve it in the future is its necessary.

Thanks!
