### ISSUE TITLE
bug: Strange cursor behavior after clicking viewport with text tool

### ISSUE THREAD

**Issue by cverdes** [uxbox/uxbox#2447]
### Steps To Reproduce

Select the text tool and click on the Viewport.

### Expected behavior

The cursor should appear on the left top corner of the text area rectangle as it is shown in the following image:
![image](https://user-images.githubusercontent.com/6440942/195641694-3d4d722c-1bc9-4d27-b0ef-878db162455d.png)

### Actual behavior

The cursor starts blinking to the left of the text area rectangle (to the left of where it was clicked) as shown in the following image:
![image](https://user-images.githubusercontent.com/6440942/195639822-197043b5-cfde-4c3f-88e5-2b2ab4b9528f.png)
The cursor is set to the correct position as soon as any key is pressed, as shown in this second image:
![image](https://user-images.githubusercontent.com/6440942/195640826-aa38334a-6bf7-45ea-8c17-ff8f1a3fabaf.png)

### Desktop (please complete the following information)

- Ubuntu 22.04
- Google Chrome Version 106.0.5249.103 (Official Build) (64-bit)

### Additional context

The bug happened when I first opened the file. After writing this issue, at the time of clicking in the viewport, the behavior changed and the guides are shown and the cursor blinks only once and stays off until a key is pressed.
![image](https://user-images.githubusercontent.com/6440942/195645115-89bad1f0-381d-4dbe-bc4f-a186a074b24b.png)

The bug appears again (it's quite random) with the guides as shown in the following image:
![image](https://user-images.githubusercontent.com/6440942/195646873-1a37189c-0f4f-4fe8-921d-7930a72c69c7.png)

**Comment by elhombretecla** [comment]
Thanks for your feedback :)

We will manage this issue [from Taiga](https://tree.taiga.io/project/penpot/issue/4363)
