### ISSUE TITLE
feature: Ctrl + `+` to zoom into Board/Canvas instead of browser's default zoom.

### ISSUE THREAD

**Issue by Waishnav** [uxbox/uxbox#2448]
### Is your feature request related to a problem? Please describe.

Comming from Figma, I'm planning to use penpot for my all design project, but got upset every time I use `ctrl +` shortcut.
In Figma it used to use to zoom into canvas/ frame, but here it behaves default zoom of the browser,

### Describe the solution you'd like.

`Ctrl +` should zoom into the board as this keyboard shortcut is universal for zoom.

### Additional context

I know that `shift +` keybinding is allotted for zooming into the board. But it doesn't seem universal. If it is possible to override the browser's default zoom behavior when pressing "Ctrl +," it would be really beneficial for all designers using Penpot.

**Comment by elhombretecla** [comment]
We just create this [Taiga enhancement](https://tree.taiga.io/project/penpot/issue/4362) to manage this as soon as we can :)
