### ISSUE TITLE
bug: callback from gitlab oauth leads to nginx bad gateway

### ISSUE THREAD

**Issue by bVdCreations** [uxbox/uxbox#2449]
### Steps To Reproduce

1. got to https://design.penpot.app/#/auth/login
2. click login with gitlab
3. gitlab redirect to https://design.penpot.app/api/auth/oauth/gitlab/callback?
4. nginx bad gateway

### Expected behavior

no bad gateway

### Actual behavior

nginx bad gateway on callback gitlab login

### Desktop (please complete the following information)

- OS linux
- chromium

**Comment by niwinz** [comment]
Is still happens or just a temporal issue? This can be caused because gitlab didn't responded on the authorization callback in a reasonable time. Right now it works for us.
