### ISSUE TITLE
bug: Pasting SVG content does not import the content at the right position

### ISSUE THREAD

**Issue by LauraWebdev** [uxbox/uxbox#2452]
### Steps To Reproduce

1. Copy SVG code, for example, from materialdesignicons.com
2. Paste it while being inside a folder/group

### Expected behavior

As with pasting objects that are already present in the board, the svg should be created within the current context (eg: folder/group)

### Actual behavior

The svg gets inserted at the very top of the board

### Screenshots or video

https://user-images.githubusercontent.com/7365286/195737326-ab32442e-dc16-40a6-bedf-0abce229f546.mov

### Desktop (please complete the following information)

- Mac OS latest
- Edge Chromium latest

### Environment (please complete the following information)

- design.penpot.app instance

### Additional context

In the video, I am pasting the raw svg via cmd+v. After some copies, I am copying the svg from the board and paste it once more. Only the last time, it gets inserted correctly

**Comment by elhombretecla** [comment]
Hi @LauraWebdev thank you for your feedback :)

I checked this issue and it happens with every item imported from outside Penpot (SVGs, Images, Texts,...) So we just created this[ issue in Taiga](https://tree.taiga.io/project/penpot/issue/4356) to fix it asap.
