### ISSUE TITLE
feature: Use Front End in  an electron project

### ISSUE THREAD

**Issue by khoshrou** [uxbox/uxbox#2462]
### Is your feature request related to a problem? Please describe.

using frontend and back end separately.

### Describe the solution you'd like.

I have an electron app, and I like to have a figma like design editor there. I see penpot is open source and I like to know if its possible to use penpot front end as user interface library in reactjs/electron project. If yes can you provide a sample?

**Comment by niwinz** [comment]
Hello @khoshrou 
There is a community effort on doing that: https://code.korbsstudio.com/KorbsStudio/Penpot-Desktop
