### ISSUE TITLE
docker installed , but i can't registe . the registe uri is 404

### ISSUE THREAD

**Issue by ivanmissu** [uxbox/uxbox#2463]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/8721615/196075115-9e6b2395-f492-4951-9acf-6d93c0c288f8.png">

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/8721615/196075046-f92d821f-9d2d-48e5-a59f-f1b771180354.png">

**Comment by niwinz** [comment]
Without more details on your config, we will be unable to help.
Backend logs and config.env sample probably will be a good starting point. Thanks

**Comment by ivanmissu** [comment]
> Without more details on your config, we will be unable to help. Backend logs and config.env sample probably will be a good starting point. Thanks

@niwinz 
sorry,  this is my config.env content:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/8721615/196102603-2d5a7523-df67-467b-9eaf-e1c31dd441a4.png">
<img width="635" alt="image" src="https://user-images.githubusercontent.com/8721615/196102661-90e69d42-0600-4045-84bd-f432e90135ef.png">
the banend logs content is : 
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/8721615/196115447-1bbf4fb0-fdd4-4d42-aebe-77673b56007d.png">

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/8721615/196103000-4c79266b-b69b-48fb-9240-f58e18d17201.png">

then i disable registe , use docker exec -ti penpot_penpot-backend_1 ./manage.sh create-profile to create account, then to login page, the login uri return 404  also.

backend version : 1.10.4-beta-6103-gbdfea7cda
in backend container:
<img width="942" alt="image" src="https://user-images.githubusercontent.com/8721615/196111847-4b683c53-1ec7-4143-b46b-b2bf3b0cda6e.png">

**Comment by ivanmissu** [comment]
@niwinz got any results？

**Comment by niwinz** [comment]
Hmm, I'm looking you are using backend version 1.10, but the frontend is  making a request /api/rpc/command/login-with-password that is from the 1.14 or 1.15; looks like you are using inconsistent versioning

**Comment by niwinz** [comment]
Ensure you are running the latest version from the all modules

**Comment by ivanmissu** [comment]
Documents on the official website I referred to， i used docker-compose.

wget https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml
wget https://raw.githubusercontent.com/penpot/penpot/main/docker/images/config.env

docker-compose.yaml content
<img width="727" alt="image" src="https://user-images.githubusercontent.com/8721615/196388614-0b32dd4c-1c7f-4363-aa5d-9274b2ab1531.png">
Is there any mistake？

**Comment by ivanmissu** [comment]
I'll try to specify the version number

**Comment by ivanmissu** [comment]
Got it ，  use specify the  version number is worked,   Maybe it's because I used Docker mirror 
@niwinz 
thanks！！
