### ISSUE TITLE
feature: Make rulers and guides X&Y values relative to selected artboard

### ISSUE THREAD

**Issue by motiapp** [uxbox/uxbox#2468]
### Is your feature request related to a problem? Please describe.

Rulers are only using global position. With multiple artboards or even a single artboard not at 0,0 the global ruler isn't that useful. If some people want a global ruler for some reason make it a feature that can be toggled by right clicking on the ruler or in preferences.

Dragging a new guide from the ruler in an artboard shows the X or Y position of the guide as you drag it, but it's using a global position which again isn't really useful. If I make guides on an artboard I want to know the position of that guide relative to the artboard.

### Describe the solution you'd like.

Rulers should recalculate their 0,0 to the selected artboard. If no artboard is selected then the ruler will be using the global position. In other words: make it work like Figma.

### Additional context

Guides that are inside artboards move relative to that artboard so they have local positions, but their reported X/Y positions aren't relative to that artboard when you hover over or drag the guide. So this is really a display issue.

**Comment by elhombretecla** [comment]
Thank you for your porposal. We just created this [User Story in Taiga](https://tree.taiga.io/project/penpot/us/4382) to track this new feature.
