### ISSUE TITLE
bug: update or delete on library elements reset color alpha values in document to 100%

### ISSUE THREAD

**Issue by carstenheyer** [uxbox/uxbox#2476]
### Steps To Reproduce

1. Add at least one color to the file library
2. Use this library color on any element (does not have to be a component) and change the alpha value in the color picker window (not the opacity value of the layer) 
3. Update or delete any library element (except graphics). In the screenshots below i deleted the typo.

### Expected behavior

The component should be deleted/updated. Nothing else should happen.

### Actual behavior

All colors from the file library which are used anywhere in the file and whichs alpha values are changed reset to 100% alpha.

### Screenshots or video

![alpha_10_percent](https://user-images.githubusercontent.com/88189340/196448617-e875e45c-cc04-4302-b682-f656e99454d7.PNG)
![picker_alpha_10_percent](https://user-images.githubusercontent.com/88189340/196448629-f813ce2e-15a3-47ee-8abd-25cbe913ecea.PNG)
![alpha_reset_100_percent](https://user-images.githubusercontent.com/88189340/196448627-480e4c47-dff1-459f-83de-76c7296060ce.PNG)

### Desktop (please complete the following information)

- OS: Windows 10
- Browser & version: Version 105.0.5195.127 (Official Build) (64-Bit)

**Comment by myfunnyandy** [comment]
Hi @carstenheyer, we've followed the steps to reproduce it and were not able to reproduce the issue. Can you check if is still happening?

**Comment by carstenheyer** [comment]
@myfunnyandy Hi, i checked it again and can tell you that the bug is fixed with version 1.15.4 (till today we were on version 1.15.2). Thank you :)

**Comment by myfunnyandy** [comment]
Great to know, thanks for the confirmation!
