### ISSUE TITLE
bug: text appears stretched after latest update

### ISSUE THREAD

**Issue by timunrau** [uxbox/uxbox#2482]
### Steps To Reproduce

1. create some text and type something.
2. Add a space at the end of your string.
3. You'll see the text stretches out.

This appears to be introduced in the latest update.

### Expected behavior

I expect the text to remain undistorted.

### Actual behavior

Text is distorted when adding a space in the string.

### Screenshots or video

https://user-images.githubusercontent.com/48539072/196749012-9beec99a-983b-4918-8cb1-c763889368b5.mp4

### Desktop (please complete the following information)

- Fedora 36
- Firefox 105.0.2

### Environment (please complete the following information)

https://design.penpot.app

**Comment by elhombretecla** [comment]
Hi @timunrau thank you so much for the report.

We just created this [issue in Taiga](https://tree.taiga.io/project/penpot/issue/4388) to fix this bug asap.

**Comment by superalex** [comment]
Thank you very much for reporting!, it should be fixed now :)
