### ISSUE TITLE
bug: Space disappears when 2 different format in one text section since the last update

### ISSUE THREAD

**Issue by LisonF** [uxbox/uxbox#2487]
### Steps To Reproduce

1. Create some text and type something with at least 2 words (we want a space between the words)
2. Select one of the word and change its color or its weight
3. The space between the words is no longer visible (while it exists when you are in text editing mode)

### Expected behavior

I expect the space between two words to remain visible even if the two words have different aethetics

### Actual behavior

The space between two words disappears when the two words embedded in the same container have different aethetics (I tested it with color and font weight).

### Screenshots or video

All text is in bold - no problem :
<img width="234" alt="Penpot bug  text - What I want" src="https://user-images.githubusercontent.com/100200707/196915097-2be0c22b-3eb7-4f48-9515-2ad516a22c11.PNG">

Text in bold and in regular weight - no space between "web" and "éthique": 
<img width="235" alt="Penpot bug  text - What I get" src="https://user-images.githubusercontent.com/100200707/196915094-d59483ab-3bb3-4e26-9c1f-cd2dc17e8070.PNG">

### Desktop (please complete the following information)

- Firefox 105.0.3 

### Environment (please complete the following information)

https://design.penpot.app

### Additional context

This problem started after the lastest update

**Comment by elhombretecla** [comment]
We ar experiencing some text format issues since last release. thanks for your report.

We are on it so it will be fixed asap :)

**Comment by superalex** [comment]
Thank you very much for reporting!, it should be fixed now :)
