### ISSUE TITLE
bug: Text in custom font is not at the expected position at export 

### ISSUE THREAD

**Issue by LisonF** [uxbox/uxbox#2489]
### Steps To Reproduce

1. Import a custom font (I used this one : https://luciole-vision.com/luciole-en.html#download)
2. Create some text and type something 
3. Apply the custom font to the text
4. Select the board and export it in pdf (the same problem happens for pdf, png and jpeg exports)
5. Compare the vertical positions you assigned in Penpot and in the exported document

### Expected behavior

I expect the text to remains at the assigned position in the exported document.

### Actual behavior

On the exported document, the text is higher on the page than assigned in penpot.

### Screenshots or video

What I want - this is a screenshot of the penpot board: 
<img width="269" alt="Penpot bug  What I want" src="https://user-images.githubusercontent.com/100200707/196919485-7601c764-1088-40b9-a19e-7b2cc8be9b04.PNG">

what it looks like - this is the exported document: 
![penpot bug  What it looks like](https://user-images.githubusercontent.com/100200707/196919495-831e03a2-709c-4189-a5be-d8ac95c2ff24.jpeg)

Note: I added a grey rectangle to show more precisely the problem in alignment, but the problem remains without the rectangle.

### Desktop (please complete the following information)

Firefox 105.0.3 (64 bits)

### Environment (please complete the following information)

https://design.penpot.app/

### Additional context

This problem was present in the previous version of penpot and remained in the new one. 
The problem did not occur when I used a system font (Source Sans Pro).

**Comment by elhombretecla** [comment]
Hi @LisonF We cannot reproduce this bug.

We've tried testing it with all font weights and export file types getting a successful result.

![image](https://user-images.githubusercontent.com/1045247/196933728-70c3de96-d966-4b4f-9c92-9344446dc75c.png)

Can you give us the penpot file?

**Comment by LisonF** [comment]
Hi @elhombretecla, 

Thank you for checking !

Here is the json+svg files: [text alignment bug.zip](https://github.com/penpot/penpot/files/9829207/text.alignment.bug.zip)

Have you tried with a **custom font** ? This problem happened to me on every file, every time I used a custom font. I never had this problem with the fonts already provided by Penpot.

**Comment by elhombretecla** [comment]
We are using the font family you shared before (Luciole)

![image](https://user-images.githubusercontent.com/1045247/196937306-d07662bc-c639-4de8-b430-9291dcb11223.png)

It is working using your file and parameters.

Can you give us more info? OS and environment (SaaS or OnPremise instance...) you're using.

Any console errors?

**Comment by LisonF** [comment]
Ok, thanks for double-checking ! 
I don't have any console error. 
I am working on a (old) Asus zenbook laptop using Windows 10.

**Comment by elhombretecla** [comment]
Ok, I got it. I've been able to reproduce it (finally!) in Firefox WIN 10.

So, Here is the [issue to manage this from Taiga](https://tree.taiga.io/project/penpot/issue/4394).

Thank you very much for your explanation :)

**Comment by jasalt** [comment]
First try using Penpot for typography graphic design and hit this problem too. Very visible when placing individual characters to same level as separate text elements, they end up more or less off every time. Using `Milligram-Macro-Extrabold-trial.ttf` from https://befonts.com/milligram-font-family.html. Font size here was 154 and seems that the random offsets get worse with larger font sizes.

![Screenshot 2022-10-22 at 19 48 02](https://user-images.githubusercontent.com/2306521/197352721-b8073bbc-2f25-4617-b146-7781470ebce5.jpg)

Using https://design.penpot.app (Firefox Stable / 106.0.1, Mac). Pardon my rough screenshotted documentation image, but it shows the alignment issue.

**Comment by MicahParks** [comment]
I'm also experiencing this issue on Google Chrome Ubuntu 22.04. I'm using `Ubuntu Mono` font. The size of the font doesn't seem to matter. The text is much higher than it its on the web editor.

**Comment by MicahParks** [comment]
I exported the SVG with text from penpot. Its text was still misaligned. I then imported the SVG into another editor. The text was aligned without editing, so I exported SVGs and PNGs from that editor and the result had the text aligned properly.

Not the best workflow, but it's working for now.

**Comment by superalex** [comment]
Hi!,

Thank you very much for all your information. I've been working on this issue trying to find what's happening and the underlying problem is related to how different operating systems and browsers manage custom web fonts.

I reduced the problem to this [codepen example](https://codepen.io/alejandro-alonso-fern-ndez/pen/mdjBWxy). If you select the text this is the result:
- Linux:
![post-fix](https://user-images.githubusercontent.com/1579633/213107888-a80daada-2402-4917-9acb-b6e72e20990b.png)
- Windows:
![post-fix](https://user-images.githubusercontent.com/1579633/213108127-9a51f9dd-200d-4929-ac7a-109af21a74a0.png)

You can see the line-height is different, it's not because of the css, it's because of the definition of the different ascend and descent attributes on the font (https://stackoverflow.com/questions/10044130/custom-fonts-with-different-vertical-metrics-between-oss).

To export png/pdf/whatever we use a headless browser running on linux, so if your custom font isn't prepared to be rendered equally on different operating systems you will differences on texts. This problem doesn't only affect to exporting. If in your team there are people working on the same file with "invalid" custom fonts from different operating systems the will probably find the same problem when selecting texts and editing them directly on penpot.

As a workaround you can "fix" your custom fonts using for example [fontsquirrel](https://www.fontsquirrel.com/tools/webfont-generator) . There is an option when generating the font to fix the vertical metrics:
![post-fix](https://user-images.githubusercontent.com/1579633/213109065-dca75a0d-eebf-4d5a-97fd-a29750cadb24.png)

We are also thinking about if we can "fix" the font just when you upload it :)

**Comment by MicahParks** [comment]
I used Ubuntu Mono, which seems to be built into PenPot. Does perhaps a fix could automatically be applied to that font as well?

**Comment by superalex** [comment]
Hi @MicahParks I can't reproduce the issue with Ubuntu Mono (I'm using arch). Could you please attach a .penpot faile showing the issue and some screenshots explaining how you see it?

Ubuntu Mono isn't built into Penpot, those are googlefonts so we can't fix or change those files.

**Comment by MicahParks** [comment]
@superalex, thank you for investigating this.

I think Ubuntu Mono actually is built into PenPot. I selected it from the menu on the right hand side and don't recall ever uploading it...

Please see the attached file for a `.zip` for screenshots and the `.penpot` along with the `.svg` and `.json`.
![OnPenPotWebUI](https://user-images.githubusercontent.com/66095735/213261963-0c291b99-8e07-48e9-bec0-9fbefe02a17d.png)
![OnUbuntu](https://user-images.githubusercontent.com/66095735/213261964-bbb48102-de5f-4443-aa36-8db60e425711.png)

[requested.zip](https://github.com/penpot/penpot/files/10449397/requested.zip)

**Comment by superalex** [comment]
Thank you very much, in your file I don't see any export setting. How are you doing it?

![Peek 2023-01-18 19-28](https://user-images.githubusercontent.com/1579633/213264391-85f9d280-bf3f-4d8c-9807-4f6cad87f539.gif)

**Comment by MicahParks** [comment]
Three dots in top left:
File > Download standard file (.svg + .json)

**Comment by superalex** [comment]
Hmmmm, so you unzip that file and your screenshot is what you see when you open your file "New File 8/4755a563-5b43-8015-8001-ecc96c76e934/4755a563-5b43-8015-8001-ecc96c76e935.svg"?

**Comment by MicahParks** [comment]
Yessir

**Comment by superalex** [comment]
Ok!, so you are really speaking about another issue @MicahParks 

How are you opening that svg?, I've seen tools like gimp not opening svg files properly . If you use inkscape or chromium directly you should see it right.

![image](https://user-images.githubusercontent.com/1579633/213266267-658a1086-cb4b-402f-a212-d7723d5fc8df.png)

**Comment by MicahParks** [comment]
Great diagnosis. That appears to be what I'm experiencing. I can view it fine in Chrome and I think the issue is the default Ubuntu image viewer.

Thank you!

**Comment by superalex** [comment]
You are welcome @MicahParks ! :)

**Comment by LisonF** [comment]
> 
Thank you @superalex, this solution worked perfectly for me!! :)

**Comment by superalex** [comment]
You are welcome @LisonF ! :)
