### ISSUE TITLE
consider supporting CSS "pixel-density" property to improve navigation / zoom performance

### ISSUE THREAD

**Issue by Awendel** [uxbox/uxbox#2492]
PenPot is implemented via a SVG render.

Compared to Figma, which uses a custom WebGL render, users will eventually run into performance problems, especially when they have many Elements on screen and especially during zoomIn / zoomOut when the Browser has to re-raster on every frame.

In its current implementation, it is sadly impossible for penpot to ever be as smooth as Figma in that regard.

Therefore I have proposed a new property at Web Incubator and hope that it gets adopted into the CSS standard soon:

https://github.com/WICG/proposals/issues/74

This would allow penpot to reduce the rendering resolution during zoom out (this is what Figma does too) in order to achieve 60fps even on 4k displays and even when there is many elements.

This would also allow designs to be displayed at "original" resolution (to preview actual pixels even when zoomed in)

I would kindly ask penpot contributors to comment on the above proposal and voice your support, especially how many end users it would positively affect (millions?).

**Comment by myfunnyandy** [comment]
Hi, we will take a deep look to the proposal and then consider to comment on it.
