### ISSUE TITLE
bug: OpenID not showing without cookies??

### ISSUE THREAD

**Issue by Rod-O** [uxbox/uxbox#2495]
### Steps To Reproduce

Open ID is not working without cookies???
Left the server in incognito mode, meaning no cookies,
to the right, normal with some cookies.

![image](https://user-images.githubusercontent.com/259931/197082116-f30cdebf-0c84-4976-855b-1c81abb04913.png)

### Expected behavior

OpenID button should be shown at all times

### Actual behavior

OpenID button is hidden

**Comment by niwinz** [comment]
Openid has nothing with with cookies, so the problem should be other. Is this a cache problem? I mean in normal mode  it is caching the config.js file that contains the variables for enable or disable it on the frontend

**Comment by Rod-O** [comment]
I don't know, now is working and can't reproduce it...
