### ISSUE TITLE
bug: Renaming File in Firefox

### ISSUE THREAD

**Issue by svnoak** [uxbox/uxbox#2502]
### Steps To Reproduce
This does not happen in Chrome, only in Firefox
1. Open a file (any file)
2. Double-click the name in the upper left corner to edit the name
3. Get "Internal Server Error"
4. Clicking on "Retry" reloads and the name is changed.

### Expected behavior

Renaming the file should not cast an error.

### Actual behavior

When the error occurs there is a error in the console "Error: Expected string, got: nil"

### Desktop (please complete the following information)

OS: Windows
Browser: Firefox (latest)

**Comment by myfunnyandy** [comment]
Hi @svnoak, I could not reproduce it. Can you check if it's still happening?

**Comment by svnoak** [comment]
I does not happen anymore (tested on two different machines). Maybe it was just Firefox acting up somehow.

**Comment by myfunnyandy** [comment]
It might have been something momentary or solved with the last release a few days ago.

Anyway, it is good to know that you don't have this problem anymore :)
