### ISSUE TITLE
feature: Use tabulation to move between layers

### ISSUE THREAD

**Issue by myfunnyandy** [uxbox/uxbox#2511]
### Is your feature request related to a problem? Please describe.

Adding easy keyboard navigation to the layers list.

### Describe the solution you'd like.

Having a layer selected, when pressing the tabulation key should change the selection to the next layer from the same hierarchy.

In this case the tabulation would be a way to change the selection of layers from top to bottom in the layers pannel. Once it reaches the end of the list, it goes back to the top, creating a loop.

### Additional context

[Taiga reference](https://tree.taiga.io/project/penpot/us/5010?backlog-owner=426680&no-milestone=1)

**Comment by TheHaymaker** [comment]
I'm looking for a good first PR issue. Think this would be a good one to start. What do you think @myfunnyandy ?

**Comment by myfunnyandy** [comment]
@TheHaymaker totally, this one was included among the "contributions welcome" list because of its clear and small scope and also the high value that will add to end users. It would be great if you go for it!

If you have doubts or need help just let us know :)
