### ISSUE TITLE
bug: Round corners outline

### ISSUE THREAD

**Issue by myfunnyandy** [uxbox/uxbox#2514]
### Steps To Reproduce

If I have a shape (like an elipse or a shape created with the pen tool) when they are selected you can see the rectangular box that surrounds the whole of the selection but also a green line surrounding the contour of the shapes selected. This is true for all of the cases except for rectangles that have rounded corners. In those cases I won't actually see the outline of the rounded cornered shape, but the outline of the original rectangle.  You can clearly see this when placing on top of the shapes an object that covers them, then selecting all of the items and noticing a ghost selection of the shapes below.

1. Go to a file
2. Create different shapes, including a rectangle with rounded corners
3. place a rectangle on top that covers all of the shapes
4. Select everything
5. See how the rectangle with rounded corners is not showing the rounded corners

### Expected behavior

Rounded corners are reflected in the outline.

### Actual behavior

Rounded corners are not reflected in the outline.

### Screenshots or video

[screen-capture-39.webm](https://user-images.githubusercontent.com/708713/197522035-c4276d23-52c5-4187-b6fd-b6d2dd83913a.webm)

### Additional context

[Taiga reference](https://tree.taiga.io/project/penpot/issue/4053)

**Comment by kylestarrtech** [comment]
This remains a bug in the current version of Penpot

**Comment by myfunnyandy** [comment]
Hi @kylestarrtech, 

I've just tried it out and it looks that is working properly (design.penpot.app, chrome, ubuntu).

<img width="615" height="494" alt="Image" src="https://github.com/user-attachments/assets/c134589c-8b41-4d3f-bfdb-6912a7925732" />

Could you provide an example and the conditions in which you can still reproduce the bug?

Thanks!
