### ISSUE TITLE
feature: Renaming layers

### ISSUE THREAD

**Issue by myfunnyandy** [uxbox/uxbox#2515]
### Is your feature request related to a problem? Please describe.

Automatically generated layer names have room for improvement.

### Describe the solution you'd like.

**Improvement 1: When creating a layer** it should be named by default with its name without adding anything afterwards. Eg:

- Group ---> Group
- Board ---> Board
- Rectangle ---> Rectangle
- Elipse ---> Elipse
- Text ---> Text
- Curve + Path ---> Path

*Images and svgs are an exception, because they will take the name of the imported file.

**Improvement 2: When duplicating a layer** (copy-pasting it, moving it while clicking alt….) let's not add -1, -2, -3… at the end of each layer name. Instead let's just leave the name intact.

[Taiga reference](https://tree.taiga.io/project/penpot/us/4036)

**Comment by niekvb** [comment]
Implementing improvement 2 would have a huge (positive) impact for my workflows. Copying elements an having to rename everything is a huge pain in the you know what, especially without something like #2569, and #2543 being an issue

**Comment by myfunnyandy** [comment]
Done and published at the release 1.17.
