### ISSUE TITLE
Automatic names for text layers

### ISSUE THREAD

**Issue by myfunnyandy** [uxbox/uxbox#2516]
### Is your feature request related to a problem? Please describe.

Text layer automatic names could be representative of their content.

Currently you always need to manually change the title of a text layer. In practice, this basically means typing text twice, because why would you give the layer a different name than what the text is in it?

### Describe the solution you'd like.

- If the title of a text layer has not been manually edited, the text of the title will be same as the text content of the layer. Limit of characteres shown: 280.
- If the title of a text layer has been manually edited, the title of the text will not be automatically set from that moment on.

### Additional context

[Taiga reference](https://tree.taiga.io/project/penpot/us/2836?no-milestone=1)

**Comment by ryanbreen** [comment]
I took a cut at this with https://github.com/penpot/penpot/pull/3153!
