### ISSUE TITLE
feature: Empty state for palettes (color, typographies)

### ISSUE THREAD

**Issue by myfunnyandy** [uxbox/uxbox#2522]
### Is your feature request related to a problem? Please describe.

The color and font palettes have no empty states. We need to improve the first state when opening a palette or the file library.

### Describe the solution you'd like.

The improvements included are:

- Placeholder for empty libraries (see [here the design](https://design.penpot.dev/#/view/ff578c40-f12e-11ec-80da-41df3d3e473f?page-id=8ff22710-858c-11ec-9e72-fbcf16f106de&section=interactions&index=0&share-id=ce552fec-7501-801a-8001-7de1348ae5f2)). When a user opens one color or font palette, if it's empty, an empty state must be shown.
- If the file library has no assets and at least one shared library with assets is connected, the first shared library found should be shown first.

### Additional context

[Taiga reference](https://tree.taiga.io/project/penpot/us/3481?no-milestone=1)

**Comment by jdittrich** [comment]
> (see [here the design](https://design.penpot.dev/#/view/ff578c40-f12e-11ec-80da-41df3d3e473f?page-id=8ff22710-858c-11ec-9e72-fbcf16f106de&section=interactions&index=0&share-id=ce552fec-7501-801a-8001-7de1348ae5f2))

![a sidebar at the bottom of the screen showing ›There are no Tpyography Styles in your library yet‹](https://user-images.githubusercontent.com/3416487/198733498-78474263-c90e-4154-afda-88255e8255c6.png)

compare to the current state, which is just an empty box
![empty sidebar at the bottom of the screen](https://user-images.githubusercontent.com/3416487/198733823-d1e6f637-6f12-4df0-a8f3-13315635e60f.png)
