### ISSUE TITLE
feature: Duplicating objects via alt + drag should also work via drag + alt

### ISSUE THREAD

**Issue by myfunnyandy** [uxbox/uxbox#2524]
### Is your feature request related to a problem? Please describe.

Duplicating objects via alt + drag should also work via drag + alt.

### Describe the solution you'd like.

Request from [Penpot Community:](https://community.penpot.app/t/duplicating-objects-via-alt-drag-should-also-work-via-drag-alt/731)

> For me my workflow efficiency is very important. One thing I do a lot in Figma is duplicating objects by holding alt and dragging. In Figma I can hold alt before I start dragging, and I can hold alt after the dragging has already begun. This means I can’t mess up because it works both ways.
> 
> In Penpot, if I don’t press alt before I drag, the object won’t duplicate. Because I move fast, I’d say half the time I press alt after I start dragging. I don’t want to have to correct this mistake over and over again and I don’t want to have to think about it. That slows me down.
> 
> It seems like a little thing, but anything that makes me feel more efficient and make less mistakes increases the perceived usability a ton.

### Additional context

[Taiga reference](https://tree.taiga.io/project/penpot/issue/4149)

**Comment by akshay-gupta7** [comment]
@myfunnyandy, I opened a PR to implement this feature #3147
Do have a peek whenever you get a chance!
Thanks!

**Comment by myfunnyandy** [comment]
@akshay-gupta7 we will review it next week, thanks!
