### ISSUE TITLE
feature: Drop shadow with negative spread

### ISSUE THREAD

**Issue by myfunnyandy** [uxbox/uxbox#2525]
### Describe the solution you'd like.

Allow to add negative values to Drop shadow spread property.

![image](https://user-images.githubusercontent.com/708713/197559705-4e0ec14e-57f2-4198-af84-4281591f3dd3.png)

### Additional context

[Taiga reference](https://tree.taiga.io/project/penpot/issue/4132)

**Comment by jdittrich** [comment]
for clarification: A negative spread for a drop shadow is something that is possible in CSS already; a positive spread makes the shadow larger, a negative spread makes it smaller.

![positive spread 10px](https://user-images.githubusercontent.com/3416487/197860199-7456277b-454f-495c-a1ee-fe6c86ff67d9.png)
![negative spread -10px](https://user-images.githubusercontent.com/3416487/197860338-beb00726-c2f2-4696-ac3a-b13585ef4112.png)

(both shown without the usual blur)

**Comment by niekvb** [comment]
In my opinion this should be listed as a bug. Using negative spread values is a very common use case.

**Comment by glippi** [comment]
Hello,

I was looking into this issue and I found a possible solution by just removing the `min` prop passed to the `numeric-input` component in `frontend/src/app/main/ui/workspace/sidebar/options/menus/shadows.cljs`.

As I red in the core code contributions guide that is always requested to discuss the change before submitting the PR, I was wondering if you also see it like a good option to just remove that prop (in my tests nothing breaks ;), but as I'm pretty new to the codebase it's definetely possible that I'm missing something or that someone knows about some other pitfalls.

In case everything is fine, I can open the PR with that change.

Thanks :)

**Comment by myfunnyandy** [comment]
@glippi your approach makes sense and at the Penpot team we don't see any other pitfall either, so be my guest opening that PR :)

**Comment by glippi** [comment]
> @glippi your approach makes sense and at the Penpot team we don't see any other pitfall either, so be my guest opening that PR :)

PR opened [here](https://github.com/penpot/penpot/pull/2902). If anything needs to be improved/changed just let me know, I'm available to do it :)
