### ISSUE TITLE
bug: Missing Docker images on Dockerhub

### ISSUE THREAD

**Issue by nullsumme** [uxbox/uxbox#2527]
### Steps To Reproduce

Go to:
https://hub.docker.com/r/penpotapp/frontend/tags
https://hub.docker.com/r/penpotapp/exporter/tags

### Expected behavior

Latest Tag: 1.16.0-beta

### Actual behavior

Latest Tag: 1.15.4-beta

**Comment by niwinz** [comment]
Hi @nullsumme 

Can you explain the issue better? I mean, the docker images for 1.16.0 are published 12 days ago:
![image](https://user-images.githubusercontent.com/843689/198967479-565fbe2d-80a9-481c-a1cc-0e75a56b2423.png)

**Comment by nullsumme** [comment]
The backend images are pushed, yes. But not the frontend / export images.

**Comment by niwinz** [comment]
ups, not verified these, hehe, i will look on what is happened

**Comment by niwinz** [comment]
all images are published, thanks for reporting
