### ISSUE TITLE
bug: Keyboard arrows triggers Internal error screen

### ISSUE THREAD

**Issue by Grga1712** [uxbox/uxbox#2529]
### Steps To Reproduce

1. Selecting any object (text, image, rectangle)
2. Using any arrow keys triggers an Internal error screen

### Expected behavior

Move the object according to arrow key press

### Actual behavior

Shows Internal error screen

### Screenshots or video

[Screencast from 25.10.2022 23:56:11.webm](https://user-images.githubusercontent.com/11547354/197890200-e6d8cb20-d8ee-4e87-94d9-2a4cde168826.webm)

### Desktop (please complete the following information)

- Fedora Linux 36 (Workstation Edition)
- Brave browser [Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by elhombretecla** [comment]
Hi @Grga1712 we couldn't reproduce your issue.

Can you give us more info? Console errors... SaaS or On Premise environment?... 

Also the url of the Penpot file could be great.

Thanks :)

**Comment by Grga1712** [comment]
Hi,

I dont konw how to give you console status. Could you please  tell me how
to do it?

Here is the link of the file:
https://design.penpot.app/#/workspace/92149e51-c3af-11eb-8557-f55ab9adbb41/67289d0b-79f1-800b-8001-7f24a2a45694?page-id=b651e164-2928-8081-8001-7f24d108ad9b

**Comment by myfunnyandy** [comment]
Hi @Grga1712,

We already found the bug, but still need to do and deploy the fix. In the meantime, you can easily fix it for yourself:

Inside a file, at the main menu, go to preferences > Nudge amount and set values for both small and big nudges.

![image](https://user-images.githubusercontent.com/708713/198231049-51eff3a3-6cfc-4c30-ab58-059c744b3746.png)

![unnamed (6)](https://user-images.githubusercontent.com/708713/198230787-1d2eac4d-03c0-4ab0-8e60-b407a355d0b8.gif)

I hope this helps.

**Comment by Grga1712** [comment]
Hi Andrés,
the solution works. It was obvious.🙂
Thx.
