### ISSUE TITLE
Penpot (web) on android tablet

### ISSUE THREAD

**Issue by QbieShay** [uxbox/uxbox#2531]
Hello, I am trying to use penpot of my Samsung galaxy s7 fe with pen, and it seems like I can't resize frames, rectangles, etc. It seems like clicks or click and drag isn't registered? 
Indont have the skills to set it up a dev environment  but I am very happy to test if anyone decides to take a look at this. 
I am hyped to use penpot ^^ you folks did a stellar job on this app!

**Comment by myfunnyandy** [comment]
Hi!

We are aware that the experience with pens is not up to the one with mouse yet. We still need to implement a lot of improvements like [this one](https://tree.taiga.io/project/penpot/us/2965).

And thanks for your offering, I took the liberty to add you to a list of beta-testers for these tablets & pens improvements. It won't be in the sort time as our priorities are now in other features, but we'll get there eventually.

**Comment by QbieShay** [comment]
Thanks! I'll be happy to test once you get to it.
