### ISSUE TITLE
bug: Justified text is stretched, both in the app and the render but not in the selection highlight

### ISSUE THREAD

**Issue by micouy** [uxbox/uxbox#2539]
### Steps To Reproduce

Add text, justify it. Play with the width to achieve stretched look. The effect is most visible when the width is small. After rendering (also to SVG and PDF), it looks the same. However, when the text is selected, you can see a second layer of text without stretching.

### Expected behavior

The text looks normal.

### Actual behavior

The text looks stretched.

### Screenshots or video

![image](https://user-images.githubusercontent.com/20628866/198903259-71f0f20d-991c-48b2-89a2-86d6bee22912.png)
![image](https://user-images.githubusercontent.com/20628866/198903446-50d4a1aa-9664-4a94-be3d-31d7c6ef83ac.png)

### Desktop (please complete the following information)

- Ubuntu 20.04
- Chromium 106.0.5249.119
- Same for Firefox 105

### Additional context

May be related to #2486 and #2482.

**Comment by myfunnyandy** [comment]
Hi, I've added the issue to our issue tracker: https://github.com/penpot/penpot/issues/2539 

Thanks for reporting!
