### ISSUE TITLE
bug: Scrollbars coversthe layer expand caret

### ISSUE THREAD

**Issue by onattech** [uxbox/uxbox#2541]
Hi, when I scroll over the expand caret on a layer, my thick scrollbar covers the caret. I am using firefox on linux mint cinnamon and I have a custom width setup for the scrollbar that I don't want to change. Is there a way to add some padding to right of the caret maybe or move the scrollbar to the left side? Thank you.

### Steps To Reproduce

Steps to reproduce the behavior
1. Hover over the expand caret

### Expected behavior

Caret should be visible.

### Actual behavior

Caret is hidden.

### Screenshots or video

Before hover
![image](https://user-images.githubusercontent.com/53895969/199202297-6f610f91-2b25-4c53-844e-6cf7f69d76a6.png)

After hover
![image](https://user-images.githubusercontent.com/53895969/199202364-24654019-d851-4651-8d25-d8516313b715.png)

**Comment by myfunnyandy** [comment]
Hi @onattech,

Could you tell me the browser and operative system where you're experiencing the issue?

Thanks!

**Comment by hirunatan** [comment]
@onattech how did you increase the width of the scroll bar? I'm afraid that the design of penpot screens is not easily modified without changing the source code.

The only means I can think about are, either to fork the project in Github and change a bit the CSS styles, or to write a Firefox plugin that modifies it live. But for both options you need some developer knowledge.

**Comment by onattech** [comment]
> @onattech how did you increase the width of the scroll bar? I'm afraid that the design of penpot screens is not easily modified without changing the source code.
> 
> The only means I can think about are, either to fork the project in Github and change a bit the CSS styles, or to write a Firefox plugin that modifies it live. But for both options you need some developer knowledge.

I did change it by going to settings by typing `about:config` in the address bar and changing the `widget.non-native-theme.scrollbar.size.override` value to 30.

I thought about writing an extension but ended up with a quicker solution. I have written a bookmark that removes the scrollbars. Check it out.

<img src="https://user-images.githubusercontent.com/53895969/200605244-c1fceaf7-0b9b-41ab-b8f0-c9ae34a717ba.png" alt="drawing" width="400"/>

Just click on the bookmark while on penpot. URL value needs to be `javascript:document.querySelectorAll('.tool-window-content').forEach(a=>a.setAttribute('style', 'scrollbar-width: none'))`

I think [stylus](https://add0n.com/stylus.html) may also be a good option.

**Comment by hirunatan** [comment]
Closing this issue, thanks for your suggestions.

I can tell you that we are in process of a general redesign of the app, so we'll take into account your ideas.
