### ISSUE TITLE
bug: Linear gradient, color picker from file or library color change deletes gradient

### ISSUE THREAD

**Issue by nbinding-cie** [uxbox/uxbox#2542]
Ello,

When using a colour gradient fill in a rectangle, picking a gradient colour on either end of the scale makes that colour the block fill - it then kills the gradient and switches back to a block fill colour.

**Steps To Reproduce**
create a rectangle
add a fill colour
change the fill type to a linear gradient
change either colour of the gradient using a colour from a file or library

**Expected behaviour**
Should be able to change the colour of the gradient as normal

**Actual behaviour**
Gradient is removed, replaced with a colour block of the new colour chosen.

**Screenshots or video**

https://user-images.githubusercontent.com/67122656/199382907-dda69b93-23ae-4412-932a-4a6d9cc53566.mov

**Comment by myfunnyandy** [comment]
Hi, I've added this issue to our issue tracker: https://github.com/penpot/penpot/issues/2542

Thanks for reporting it!
