### ISSUE TITLE
bug: Pasting SVG leads to "Internal Server Error"

### ISSUE THREAD

**Issue by LauraWebdev** [uxbox/uxbox#2548]
### Steps To Reproduce

Steps to reproduce:
- Copy the svg code
- Paste it into a document

### Expected behavior

Two options:
- This works, the icons stay in the board
- The workspace displays an error snackbar

### Actual behavior

The SVG is pasted and visible. A few seconds later, the workspace crashes with an "Internal Server error". The console displays an error hinting at spec validation.

### Screenshots or video

![image](https://user-images.githubusercontent.com/7365286/199749182-2b4c81dd-365f-42cc-9b56-a82e65658a90.png)
![image](https://user-images.githubusercontent.com/7365286/199749202-2dc6dc24-4cea-47ef-933a-ac5b4ed16f59.png)
![image](https://user-images.githubusercontent.com/7365286/199749272-8eaf479d-09c0-4938-a480-68b029f173b7.png)

### Desktop (please complete the following information)

- OS: Win 11 22H2 (Build 22623.875)
- Browser: Microsoft Edge Version 107.0.1418.24

### Environment (please complete the following information)

- Host: design.penpot.app

### Frontend Stack Trace

[Console error](https://gist.github.com/LauraWebdev/f0f399e9aeb4c60d59b41b345865d070)

### Additional context

[SVG code](https://gist.github.com/LauraWebdev/59ee949bbac9b5936ff067a5c6392f7a) (This is actually the SVG code copied from the penpot workspace dom)

**Comment by myfunnyandy** [comment]
It seems that the svg code fails and Penpot is not preventing this type of error. You can try to open it in Inkscape for instance, nothing is shown. It might be because widht and height are 0 and is composed by symbols. However, we've created an issue to prevent this cases:https://tree.taiga.io/project/penpot/issue/4447

Thanks for reporting it

**Comment by LauraWebdev** [comment]
@myfunnyandy what I find funny is that the svg is displayed correctly for a second before the workspace crashes. So I'm guessing this problem comes up with the automatic saving

**Comment by krapdude** [comment]
Will this issue get fixed?
I am stuck in the middle of the work
Don't make me regret for choosing pen pot

**Comment by elhombretecla** [comment]
Hi there, we are currently working on this.

It is a duplicated issue. Hope to fix it soon with a hotfix.

Sorry for the inconvenience

**Comment by krapdude** [comment]
why are you closing the issues without fixing them?

**Comment by elhombretecla** [comment]
We close the issue because it is fixed and deployed in the PRO environment.

Please @krapdude try it yourself. If you have any problem contact us.

**Comment by LauraWebdev** [comment]
@krapdude if issues have the "managed on taiga" label, that means you'll be able to see progress of that issue on taiga.io.
