### ISSUE TITLE
penpot Should be available on Cloudron

### ISSUE THREAD

**Issue by SamGreenwood1** [uxbox/uxbox#2551]
“[Cloudron](https://cloudron.io) is a platform that makes it easy to install, manage and secure web apps on your server.”

here’s a [link](https://docs.cloudron.io/packaging/publishing/) to how to publish an app to Cloudron.

**Comment by hirunatan** [comment]
Hello @SamGreenwood1 

We don't currently have in our plans to support other packaging than elest.io. But you are true that this could be a very interesting addition.

I've create this user story https://tree.taiga.io/project/penpot/us/4477. We'll study it, and could prioritize it higher if we manage to schedule time for it.

Thanks for the suggestion.
