### ISSUE TITLE
bug:  Unable to create account

### ISSUE THREAD

**Issue by hkdd** [uxbox/uxbox#2553]
### Steps To Reproduce

Setup via docker-compose using default config and docker-compose
Go to hostname:9001 and get the login screen
Click "create account"
Enter e-mail and password, press continue
Enter full name, press continue.  button turns gray then green again
Press continue again it stays gray this time
Click "go back" and attempt to login anyway
Go back and try to login, get:  "Something wrong has happened."

If I try to create the account again it says "Email already used"

### Expected behavior

Account is created and I login

### Actual behavior

Unable to login but account appears to exist in db ("email already in use" from above)

### Environment (please complete the following information)

self-hosted with docker-compose

**Comment by niwinz** [comment]
please, paste the docker logs (mainly of the backend container), with so little information we will not be able to help you

**Comment by hkdd** [comment]
Sure, here you go.
[docker-compose.txt](https://github.com/penpot/penpot/files/9946253/docker-compose.txt)

**Comment by niwinz** [comment]
hmm very strange, I will look into it tomorrow for check if everything is working as expected on docker images
In any case I suggest trying it again with different user (just for curiosity, because for some reason the prepare
returned 400
![image](https://user-images.githubusercontent.com/843689/200182432-e290cb7e-63bf-4e9b-9139-3c3009fbcce4.png)

Also, If you can repeat that process having the devconsole open and paste here the response of the failed request, this will be very helpful

**Comment by SaHeinem** [comment]
Had the exact same behavior today and saw issue [1979](https://github.com/penpot/penpot/issues/1979 ) 

adding the **disable-secure-session-cookies** flag on the 'PENPOT_FLAGS' in the **config.env** solved it for me.

**Comment by HendrikRoth** [comment]
i have the same issue, but the disable-secure-session-cookies flag does not help here.

**Comment by KvizadSaderah** [comment]
Hi @niwinz 
Any fixes or how-to?
Have absolutely the same :(

**Comment by niwinz** [comment]
if the solution of this thread does not helps you, is probably a different problem, so I suggest you to open a separate issue and provide enough context for us to be able to help you.

**Comment by roxburghm** [comment]
Same here, it's because it's runnning on http://localhost:9000 - as soon as I accessed on https it worked fine so thats why you need the display-secure-session-cookies flag if running in dev.
