### ISSUE TITLE
feature: desktop app

### ISSUE THREAD

**Issue by 6543** [uxbox/uxbox#2556]
### Is your feature request related to a problem? Please describe.

work without an penpot account or work without internet connection

### Describe the solution you'd like.

use tauri (or electron if more bloat is ok) and add a build targetd that removes the user accout logic, so

there could be a multi-platform desktop app released

### Describe alternatives you've considered.

self host a local instance on the dev pc and use it over localhost

**Comment by hirunatan** [comment]
The desktop app question is quite complex. There is a community thread about this:

https://community.penpot.app/t/faq-how-can-i-make-penpot-work-offline/51

Currently you can host a local instance using docker, and there is an unofficial desktop app by @Korbs
