### ISSUE TITLE
Issue : Subscribe button padding issue for mobile website

### ISSUE THREAD

**Issue by ashishk1331** [uxbox/uxbox#2559]
### Steps To Reproduce

Steps to reproduce the situation,
1. Go to penpot.app
2.  Scroll down to the subscribe section 

### Expected behavior

There should be a clear subscribe text on the button, which getting cropped out.

### Actual behavior

Proper padding in the button.

### Screenshots or video

![Uploading Screenshot_20221111-010337_Brave.jpg…]()

### Desktop (please complete the following information)

Android 12

### Smartphone (please complete the following information)

Samsung galaxy M31

**Comment by EvaMarco** [comment]
Hello @hugekontrast 
Thanks for pointiong out this problem, I've created an issue to solve this error as soon as posible.
You can check it here. https://tree.taiga.io/project/penpot/issue/4473

**Comment by EvaMarco** [comment]
We change the app and this problem no longer happens

**Comment by ashishk1331** [comment]
You guys are the best!
