### ISSUE TITLE
feature: Press `enter` to submit asset group name dialog

### ISSUE THREAD

**Issue by niekvb** [uxbox/uxbox#2567]
### Is your feature request related to a problem? Please describe.

When creating an asset group, you can only submit the group name by pressing the *Create* button.

Current workflow:
1. Drag (for ex.) one color from the assets tab into another.
2. Enter a name for the group into the popup dialog. (see screenshot)
3. Move your hand from your keyboard to your mouse.
4. Move your mouse to the *Create* button and click it.

![Untitled3](https://user-images.githubusercontent.com/37668320/202294263-1fd10f8c-6ca0-44fb-86aa-a7c4b35a4d3d.png)

### Describe the solution you'd like.

Press `enter` to submit the group name and create it.

This would greatly improve the workflow mentioned above as step 3 and 4 are likely to take up a lot of time (although we're still talking about 1-3 seconds :) )

### Describe alternatives you've considered.

You can still use `tab` (twice) to focus on the *Create* button, although there's no visible highlight or outline to indicate that you've focused on either the *Cancel* or *Create* button.

**Comment by EvaMarco** [comment]
Hello @niekvb:

I think this could be considered as a Bug, and I've created an issue in our Taiga project to fix it as soon as posible. Thanks for pointing out the problem.

You can check the issue [here](https://tree.taiga.io/project/penpot/issue/4506).
