### ISSUE TITLE
feature: Replace the "Drafts /" prefix in the project name with an `<a>` element

### ISSUE THREAD

**Issue by niekvb** [uxbox/uxbox#2568]
### Is your feature request related to a problem? Please describe.

I did not find a way to quickly open your *Drafts* dashboard in a new tab to open a second project.

In Figma you can do this by clicking the project name's prefix (eg *Drafts /*) to open this page in a new tab.

### Describe the solution you'd like.

Replace the *Drafts /* prefix of the project name (see screenshot) with an HTML `<a>` element.

This allows to open the drafts page in a new tab by either clicking it with your middle mouse button (scroll wheel click) or by clicking it with the right mouse button.

Alternatively, you could use the same implementation as Figma where it will open the drafts page in a new tab by default.

![Untitled4](https://user-images.githubusercontent.com/37668320/202301654-081db239-0214-43fd-9b58-ba02cb9bf722.png)

**Comment by EvaMarco** [comment]
Hello again @niekvb:
You have been busy :), just yoking. 
This is a very nice idea, and I have created another issue in Taiga, you can check it in [this link](https://tree.taiga.io/project/penpot/us/4504).
