### ISSUE TITLE
feature: Enlarge clickable area to edit component/asset name

### ISSUE THREAD

**Issue by niekvb** [uxbox/uxbox#2570]
### Is your feature request related to a problem? Please describe.

I often have to double-click multiple times on an item to edit it's name due to the ***height*** of the "clickable area" being smaller than the "button" (the blue striped lines vs purple area).

![Untitled8](https://user-images.githubusercontent.com/37668320/202348478-10f2d729-9bbb-4b22-83fd-d843f4b205f5.png)

### Describe the solution you'd like.

Please add a little bit of height to the clickable area of the button. (the button's height itself is fine)  :)

**Comment by EvaMarco** [comment]
Hello, @niekvb 
We are doing a redesign of our interface having in mind accessibility, and this is one of our tasks.
You can see some more information [here](https://tree.taiga.io/project/penpot/task/4167).
Thanks for pointing out this problem.
