### ISSUE TITLE
bug: Moving an element while holding `shift` causes it to drift from axis

### ISSUE THREAD

**Issue by niekvb** [uxbox/uxbox#2571]
### Steps To Reproduce

I didn't find a way to reliably reproduce yet 😕

I assume it has to do with snapping to other elements though.

### Expected behavior

1. Click and hold an element.
2. Start moving the element.
3. Hold <kbd>shift</kbd> to lock it to an axis.
4. The element will stick to either the X or Y axis.

### Actual behavior

4. The element will shift about 5 pixels from the axis.

### Screenshots or video

https://user-images.githubusercontent.com/37668320/202374387-6d88b425-ff74-4926-8eea-e5dec3e2a247.mp4

### Desktop (please complete the following information)

- Windows 10
- Firefox 106.0.5

**Comment by EvaMarco** [comment]
I've copied this information in a Taiga issue to fix it. You can follow it [here](https://tree.taiga.io/project/penpot/issue/4505).

**Comment by myfunnyandy** [comment]
Closing it as the fix is already published.
