### ISSUE TITLE
feature: Display type of component library not persistent

### ISSUE THREAD

**Issue by niekvb** [uxbox/uxbox#2576]
### Is your feature request related to a problem? Please describe.

Changing the display type (see screenshot) in the component library is not persistent.

To reproduce:
1. Click the display type to change it.
2. Activate the tab ***Layers***.
3. Switch back to tab ***Assets***.
4. Notice the display type being reset.

![image](https://user-images.githubusercontent.com/37668320/202745625-53ae5092-78ed-4686-bd47-e9fea045cdcf.png)

### Describe the solution you'd like.

Penpot to obey what I tell it to do 😈

**Comment by pabloalba** [comment]
Hello @niekvb
Thank you! I've created an enhancement about it. You can check it [here](https://tree.taiga.io/project/penpot/issue/4512).
