### ISSUE TITLE
bug: Penpot runs into an internal error when trying to apply border radius to Boards

### ISSUE THREAD

**Issue by alessandrogian** [uxbox/uxbox#2577]
### Steps To Reproduce

Create new file;
Create new Board;
Apply border radius

### Expected behavior

Applying a border radius to the Board

### Actual behavior

Program runs into Internal Error

### Desktop (please complete the following information)

Chrome OS Version 107.0.5304.110 (Official Build) (64-bit)

**Comment by pabloalba** [comment]
Hi @alessandrogian !

I've just try it and it works fine:
![Peek 2022-11-21 16-35](https://user-images.githubusercontent.com/782558/203095636-538bc4b1-fb52-4d34-9098-7c8da4f413d2.gif)

Can you give us more info? Or send the file that gives you problems to support@penpot.app?

Thank you!

**Comment by alessandrogian** [comment]
Hi! I was about to reply to my query by saying it works, but not how I expected it to. If I type in a number and then click somewhere else on the page, it effectively changes the border-radius. However, if I click Enter, then It displays the error message.
About the file, it's the same for every new file I create. If you need more info please let me know, I'd be very happy to help ;)

**Comment by pabloalba** [comment]
That's weird... Does it work for you on the web version? (I've just ask you on the penpot community too)

**Comment by tomjpeg** [comment]
I can confirm the issue. I also had it several times. Especially when you confirm the input with Enter.

**Comment by alessandrogian** [comment]
> That's weird... Does it work for you on the web version? (I've just ask you on the penpot community too)

I use the PWA and it doesn't work, also the web version has the same issue

**Comment by pabloalba** [comment]
Hi.
I've created a [bug report](https://tree.taiga.io/project/penpot/issue/4518), we will look into it as soon as possible.

Thank you!
