### ISSUE TITLE
bug: Misleading error message in Log in page

### ISSUE THREAD

**Issue by iprithvitharun** [uxbox/uxbox#2579]
### Steps To Reproduce

On the log in page, 

1. Enter incorrect credentials.
2. Click Login.
 

### Expected behavior

Should say "Email" instead of "username".

### Actual behavior

A username isn't given to an account and only an email address is accepted. So, the error message shouldn't say "username". 

### Screenshots or video

<img width="699" alt="incorrect form err message" src="https://user-images.githubusercontent.com/58725708/203071455-6378d475-7f01-4f21-a288-ecb99da9eafd.png">

### Desktop (please complete the following information)

macOS Monterey v12.4

**Comment by pabloalba** [comment]
I've just merged your PR. 

Thanks a lot!
