### ISSUE TITLE
bug: Suggestions to improve "Invitations" page

### ISSUE THREAD

**Issue by iprithvitharun** [uxbox/uxbox#2588]
### Steps To Reproduce

1. Go to Invitation page in a team.

### Expected behavior

**What could be improved?**

- Make the "Invite to team" button primary. The core functionality of the page is to invite people and with the button muted visibly, it's hard to notice it. 
- The empty state content can be improved a lot. Reads robotic. For example, no one presses the button, they click the button. 

### Actual behavior

- The "Invite to team" button is secondary, small. 

### Screenshots or video

<img width="1197" alt="Screenshot 2022-11-22 at 9 29 44 PM" src="https://user-images.githubusercontent.com/58725708/203361783-3ae86164-1c1a-4081-89bf-950c3268494d.png">

**Comment by myfunnyandy** [comment]
hi @iprithvitharun, as [this PR](https://github.com/penpot/penpot/pull/2590) has already been accepted I guess we can consider this one done, right?

**Comment by iprithvitharun** [comment]
@myfunnyandy Makes sense. This can be closed.

**Comment by myfunnyandy** [comment]
thanks!
