### ISSUE TITLE
Translate Chinese language.

### ISSUE THREAD

**Issue by hiyizi** [uxbox/uxbox#2604]
Hello, I'm a Chinese native speaker. I found the Chinese language is uncompleted, so I Want to contribute.

My weblate username is **hiyizi**

Thanks

**Comment by myfunnyandy** [comment]
We've already added you to the translation project. Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/) and select the languate you want to translate. "Chinese (Simplified)" is amost completed but "Chinese (Simplified)" still needs a lot of work.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
