### ISSUE TITLE
bug: Stroke width is taken into account for export even when there is no stroke color

### ISSUE THREAD

**Issue by dfelinto** [uxbox/uxbox#2611]
### Steps To Reproduce

1. Drag this circle into penpot:
![penpot_circle](https://user-images.githubusercontent.com/843498/204516374-bc42ca65-e31f-4b49-b740-7c9ebd78ea8c.svg)
2. Export it

### Expected behavior

I would expect the exported image to match the size of the circle that I see inside penpot.

### Actual behavior

The total image size takes into account the stroke width, even though the stroke is not visible/non-existent/corrupt.

### Screenshots or video

Outputted image:
![penpot_circle](https://user-images.githubusercontent.com/843498/204516795-5042f620-aeed-41a5-8ef0-7e926671f1b9.png)

### Additional context

I'm not sure if the issue is when importing the SVG, or when exporting the image. On Inkspace (where the SVG came from) it is possible to set a stroke width, without defining a Stroke color. In my case this was happening non-intentionally.

I would be fine just having the stroke info to be removed when importing. And that is probably the correct fix.

Right now it shows the color as "Mixed", which is a hint that something is amiss (though I would prefer something more descriptive like: Corrupted, or similar).

**Comment by myfunnyandy** [comment]
We'll take a look at it, I've added the issue to Taiga: https://tree.taiga.io/project/penpot/issue/4540

**Comment by superalex** [comment]
Thank you very much @dfelinto 

Finally we decided to include this as a hotfix for 1.19.0 release, it will be deployed to design.penpot.app in the next days :)

Regards,
