### ISSUE TITLE
bug: Deleting item causes penpot to crash

### ISSUE THREAD

**Issue by rileyseaburg** [uxbox/uxbox#2620]
### Steps To Reproduce

Install ProxMox Hyper V
Create a linux container with Ubuntu 20.04
Install Docker
Run penpot as described in the documentation for docker.

### Expected behavior

Allow user to delete and edit components as needed

### Actual behavior

I am trying to build a design system in Penpot. 
One of the widgets I am trying to build causes penpot to crash when I make changes or try to delete it. 

### Screenshots or video

![image](https://user-images.githubusercontent.com/48305658/205027462-50a10767-725b-4ac0-b77c-8bef758f378d.png)

![image](https://user-images.githubusercontent.com/48305658/205027790-0c38eb91-0dcc-41d5-852f-9db3a93a03e8.png)

### Desktop (please complete the following information)

Windows
Browser: Chromium - Edge (Can confirm same issue on Chrome)

### Environment (please complete the following information)

Self hosted
Ubuntu 20.04

**Comment by rileyseaburg** [comment]
Note the container has 8 cores and 8GBS of ram available.

**Comment by niwinz** [comment]
Hmm, i'm unable to reproduce this, the logs shows like you have expired token or something related to authentication.
Sorry for late response in any case; I close this issue, if this still happens feel free to reopen.
