### ISSUE TITLE
bug: whenever we place an svg or icons from the library on the artboard, the app crashes. Stating internal error.

### ISSUE THREAD

**Issue by krapdude** [uxbox/uxbox#2622]
### Steps To Reproduce

1. copy an svg or place an icon
2. click anywhere else
3. error page is shown

### Expected behavior

Can i simply place icons on the app

### Actual behavior

unable to place icon, the app shows internal error and asks to reload the page

### Screenshots or video

![image](https://user-images.githubusercontent.com/119596116/205048728-56c368dd-5720-4695-a089-2b0b89712550.png)
![image](https://user-images.githubusercontent.com/119596116/205048882-c37f66ad-6268-4e52-921b-c3c3a9065925.png)
![image](https://user-images.githubusercontent.com/119596116/205048917-4d54cbcc-9b2c-4695-a417-56ab3c004697.png)

### Desktop (please complete the following information)

Chrome Version 107.0.5304.122 (Official Build) (64-bit)

**Comment by elhombretecla** [comment]
Duplicated issue https://github.com/penpot/penpot/issues/2548

**Comment by krapdude** [comment]
its still an issue
why did you close it?

**Comment by elhombretecla** [comment]
Because another user report the same issue first. Specifically #2548 

Anyway, please @krapdude can you test the issue again? We just deployed a hotfix :)

Thanks!

**Comment by krapdude** [comment]
It is still their

**Comment by krapdude** [comment]
I am working on a big app, if this continues I am reporting this app and switching to figma.

**Comment by superalex** [comment]
Hey @krapdude !

After the hotfix I can't reproduce the issue anymore:

https://user-images.githubusercontent.com/1579633/205097461-258d4755-f0a2-40cf-b977-82c2e1e4288a.mp4

Are you doing any different thing?

It could be useful too if you show us your file url :)

Thanks!
