### ISSUE TITLE
bug: libraries cover image not shown/broken

### ISSUE THREAD

**Issue by ryanvanhoo** [uxbox/uxbox#2624]
### Steps To Reproduce

1. Have Penpot installed on-premise without a connection to internet.
2. Open Penpot 16.1.
3. Open the Libraries & Template tab from the bottom of the screen.
4. See the browser default "Image not found" icon instead of the cover image of each library.

### Expected behavior

Show the library cover image in the tab in the bottom of the screen.

### Actual behavior

Without a connection to the internet, the browser can't find the cover image. So it gives the browser default fallback icon for broken images.

### Screenshots or video

I had to recreate the issue online as we're not allowed to send screenshots "outside" our secured domain, but this is what it looks like. Note also that the cover images do work when the library is installed.

<img width="2168" alt="Screenshot 2022-12-01 at 13 55 15" src="https://user-images.githubusercontent.com/117077975/205058330-716e6195-7f9d-4dc9-b3e8-3b8b1d29fb19.png">

### Desktop (please complete the following information)

All browsers

### Additional context

The cover image does work after installing the library. It's just the URL of the cover image before installing it can't look up. I guess ideally you would like to use a local image for the library, seeing that it does have one when installed.

**Comment by EsterLatorre** [comment]
Thanks ryanvanhoo, 
We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/4573) to track this issue from here. We will try to fix it soon. 

Thanks for reporting it!
