### ISSUE TITLE
Translation access request for Bengali / Bangla Language

### ISSUE THREAD

**Issue by saif71** [uxbox/uxbox#2631]
I'd like to become a translator for the Bengali language (also known as Bangla). I'm a native speaker of Bengali.
My Weblate tsername is[ **Saif71**](https://hosted.weblate.org/user/saif71/)

With approximately 300 million native speakers and another 37 million as second language speakers, Bengali is the fifth most-spoken native language and the seventh most-spoken language by total number of speakers in the world. Bengali is the fifth most spoken Indo-European language.
https://en.wikipedia.org/wiki/Bengali_language

**Comment by myfunnyandy** [comment]
Hi!
We've already added you to the translation project and also the Bengali language at the languages list. It always makes us really happy to add a new language and this one specially! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/bn/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
