### ISSUE TITLE
bug: Separate Padding Option Mislabeled 

### ISSUE THREAD

**Issue by rileyseaburg** [uxbox/uxbox#2633]
### Steps To Reproduce

- Login to penpot self-hosted. 
- Create a board and place an item inside of it. 
- Select the board and try to adjust the bottom padding. 
   - The left padding will move on the board.
- Increase the left padding
   - The bottom padding will increase on the board. 

### Expected behavior

When entering left padding, left padding increases. 
When entering top padding, top padding increases. 

### Actual behavior

When entering left padding, vertical padding increases.
when entering top padding, left padding increases. 

### Screenshots or video

![Screenshot (1)](https://user-images.githubusercontent.com/48305658/205419426-3b30e18d-3091-4a32-9d87-49aeb3ea233a.png)
![Screenshot (2)](https://user-images.githubusercontent.com/48305658/205419465-ab7ec9c3-3156-430b-8399-bb0564cd3505.png)

### Desktop (please complete the following information)

- OS Windows
- Browser Edge

### Environment (please complete the following information)

Self-hosted on docker container on Ubuntu
Beta version 1.16

**Comment by niwinz** [comment]
Looks like a bug. Reported internally: https://tree.taiga.io/project/penpot/issue/4615

**Comment by pabloalba** [comment]
Hi! The new version of the layout fixes this. I'm closing the issue.
