### ISSUE TITLE
Translation access request for Korean

### ISSUE THREAD

**Issue by jgk9282** [uxbox/uxbox#2636]
Hello, there!

This is Peter Kim and it's such an honor to request translation access for Korean.

Penpot is an amazing tool and I am thrilled to see people use it in Korea.

If you give me the access, I will start the work right away.

Thanks and keep it up for the best product!

Weblate ID : jgk9282
Full name : Suhwan Kim
E-mail : jgk9282@gmail.com

Sincerely,
Peter Kim

**Comment by pabloalba** [comment]
Hi, Peter!

Thank you very much! I've just added you as a translator on weblate.

Best,
Pablo
