### ISSUE TITLE
bug: Unable to display OIDC login for Azure AD login

### ISSUE THREAD

**Issue by dalemccrory** [uxbox/uxbox#2637]
### Steps To Reproduce

1. After running the application in Elestio, open the terminal
2. Following the instructions for Azure AD to edit the env file at:
 https://help.penpot.app/technical-guide/configuration/#authentication-providers
3. Restart the service at Elestio
4. During troubleshooting, I learned about an additional flags, so the flags look like;
```
PENPOT_FLAGS="enable-smtp enable-registration enable-login-with-oidc
```

### Expected behavior

I expect the login with OIDC button to appear

### Actual behavior

Only the standard login appears after following the instructions to edit the environment variable and resetting the service. 

### Environment (please complete the following information)

Hosted on Elestio
https://penpot1-u721.vm.elestio.app/#/auth/login

version: 1.16.1-beta-8399-gca7ebdcc8

**Comment by superalex** [comment]
Hello @dalemccrory 

It sounds like something isn't correctly configured because if you access to https://penpot1-u721.vm.elestio.app/js/config.js the oidc login isn't listed

Regards,
