### ISSUE TITLE
bug: icons doesn't show。404

### ISSUE THREAD

**Issue by qingfengtaizi** [uxbox/uxbox#2641]
### Steps To Reproduce

When I import the Libraries & templates into my project ,icons doesn't show。404

### Expected behavior

icons show

### Actual behavior

icons doesn't show

**Comment by qingfengtaizi** [comment]
![image](https://user-images.githubusercontent.com/24245864/206177376-6a4e1e71-f3f8-4299-8573-5f0360782ac6.png)

**Comment by niwinz** [comment]
is this selfhosted or our saas?
which template are you using?

please, when you fill the issue, provide more details, this is very difficult for us guess what could happening with no information (and time consuming on requesting information that is already part of the issue request template).

**Comment by qingfengtaizi** [comment]
Thanks your answer！
My own server。using Docker

Docker compose file:
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_data:
  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9001:80

    volumes:
      - penpot_assets_data:/home/penpot/data

    env_file:
      - config.env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - penpot_assets_data:/home/penpot/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    env_file:
      - config.env
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:14"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - penpot_postgres_data:/home/penpot/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

**Comment by qingfengtaizi** [comment]
> is this selfhosted or our saas? which template are you using?
> 
> please, when you fill the issue, provide more details, this is very difficult for us guess what could happening with no information (and time consuming on requesting information that is already part of the issue request template).



> is this selfhosted or our saas? which template are you using?
> 
> please, when you fill the issue, provide more details, this is very difficult for us guess what could happening with no information (and time consuming on requesting information that is already part of the issue request template).

Thanks for your answer！
My own server。using Docker

**Docker compose file:**
version: "3.5"

networks:
penpot:

volumes:
penpot_postgres_data:
penpot_assets_data:

services:
penpot-frontend:
image: "penpotapp/frontend:latest"
ports:
- 9001:80

volumes:
  - penpot_assets_data:/home/penpot/data

env_file:
  - config.env

depends_on:
  - penpot-backend
  - penpot-exporter

networks:
  - penpot
penpot-backend:
image: "penpotapp/backend:latest"
volumes:
- penpot_assets_data:/home/penpot/data

depends_on:
  - penpot-postgres
  - penpot-redis

env_file:
  - config.env

networks:
  - penpot
penpot-exporter:
image: "penpotapp/exporter:latest"
env_file:
- config.env
environment:
- PENPOT_PUBLIC_URI=http://penpot-frontend/
networks:
- penpot

penpot-postgres:
image: "postgres:14"
restart: always
stop_signal: SIGINT

environment:
  - POSTGRES_INITDB_ARGS=--data-checksums
  - POSTGRES_DB=penpot
  - POSTGRES_USER=penpot
  - POSTGRES_PASSWORD=penpot

volumes:
  - penpot_postgres_data:/home/penpot/postgresql/data

networks:
  - penpot
penpot-redis:
image: redis:7
restart: always
networks:
- penpot

**config.env:**


PENPOT_PUBLIC_URI=http://my ip

PENPOT_FLAGS=enable-registration enable-login disable-email-verification disable-secure-session-cookies

PENPOT_HTTP_SERVER_HOST=0.0.0.0

PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
PENPOT_DATABASE_USERNAME=penpot
PENPOT_DATABASE_PASSWORD=penpot

PENPOT_REDIS_URI=redis://penpot-redis/0

PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/home/penpot/data/assets

PENPOT_TELEMETRY_ENABLED=true

PENPOT_SMTP_DEFAULT_FROM=******
PENPOT_SMTP_DEFAULT_REPLY_TO=******
PENPOT_SMTP_HOST=smtp.qq.com
PENPOT_SMTP_PORT=25
PENPOT_SMTP_USERNAME******
PENPOT_SMTP_PASSWORD=******
