### ISSUE TITLE
feature: 

### ISSUE THREAD

**Issue by damnedon** [uxbox/uxbox#2646]
### Is your feature request related to a problem? Please describe.

No ukrainian localization

### Describe the solution you'd like.

Would gladly help you to translate penpot to ukrainian.

Weblate ID : @anbroider
Full name : Vladyslav Hulin
E-mail : anbroider@gmail.com

**Comment by pabloalba** [comment]
Hi Vladyslav!

Thank you! I've just added you as a Penpot translator on Weblate.

Best,
Pablo
