### ISSUE TITLE
bug: prototype interaction position of artboard not respected

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#2660]
### Steps To Reproduce

1. Create a 'main' artboard that is high enough (to ensure scrolling is needed)
2. Add a horizontal bar (to represent a menu)
3. Add an object, e.g. a square (to represent a menu item)
4. Group the two elements and activate 'Fix when scrolling' on the group
5. Create a small 'secondary' artboard with an object
6. Via prototyping, add an 'interaction' for the object in the menu bar (added in step 3), with
  * trigger: mouse enter
  * action: open overlay
  * destination: secondary artboard (added in step 5)
  * position: any other than top-left
7. initiate prototype play and hover the 'menu item' with the interaction

### Expected behavior

The secondary artboard appears in the top left

### Actual behavior

The secondary artboard appears at the selected place

### Screenshots or video

Prototyping on the main artboard object:
![Screenshot_2022-12-13_18-07-43](https://user-images.githubusercontent.com/11229646/207415629-12b55b13-325e-4227-aa3d-45d2e9ea4158.png)

Object on the secondary artboard:
![Screenshot_2022-12-13_18-08-31](https://user-images.githubusercontent.com/11229646/207415622-60dae8aa-a96c-4e0d-a979-d8c18a401367.png)

Result:
![Screenshot from 2022-12-13 19-09-44](https://user-images.githubusercontent.com/11229646/207415614-04e17696-c982-4a98-9e87-d443305e1d2e.png)

### Desktop (please complete the following information)

Version 108.0.5359.71 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

### Environment (please complete the following information)

SAAS host

### Additional context

Interestingly, if for the 'Object on the secondary artboard' (2nd screenshot above) I activate 'Fix when scrolling', the selected prototype element position is respected:
![Screenshot from 2022-12-13 19-11-42](https://user-images.githubusercontent.com/11229646/207416420-5bf6ec97-8725-4d7c-8aa3-9c61273bae11.png)

**Comment by EsterLatorre** [comment]
Hello kenues,

Thanks for reporting the bug. I've logged it on taiga and you can check the progress here: https://tree.taiga.io/project/penpot/issue/4610. We'll work to have it fixed soon

Have a good day!

**Comment by pabloalba** [comment]
Hi! This is fixed, and will be released soon!

**Comment by pikhosh** [comment]
I ran into this problem too and had no idea it was related to the "Fix when scrolling" option! I was upset that I needed to switch to another alternative, but now I'm happy to see that the problem can be fixed and it's also fixed in Penpot :) Thank you for your efforts!
