### ISSUE TITLE
bug: "Create Component" seems to be missing from context menu, Ctrl+K works still

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#2670]
### Steps To Reproduce

Intent: Create a component. Actions: 

* Create a board
* Put some stuff on it
* Right click board…

### Expected behavior

The menu entry "Create component" should be in the context menu

### Actual behavior

There is a conext menu, but no option to creaste a component (as described in [the documentation](https://help.penpot.app/user-guide/components/#component-create)). Pressing Ctrl+K works, though.

### Screenshots or video

![grafik](https://user-images.githubusercontent.com/3416487/208115321-6157cbd5-92da-405d-b213-bce7d0d80091.png)

### Desktop (please complete the following information)

Firefox on Windows 11

**Comment by EsterLatorre** [comment]
Thanks for your comment jdittrich! 

I've added it as a bug in taiga, you can check its progress here: https://tree.taiga.io/project/penpot/issue/4611

Have a good day ;)
