### ISSUE TITLE
bug: Undoing group or component creation jumbles the elements' ordering

### ISSUE THREAD

**Issue by keychera** [uxbox/uxbox#2672]
### Steps To Reproduce

Steps to reproduce:
1. create 3 elements
2. select all of them and group them (or create component)
3. do Undo (cmd + z in my case)

### Expected behavior

The elements will still retain the previous ordering before grouping

### Actual behavior

the elements' order become jumbled

### Screenshots or video

https://user-images.githubusercontent.com/23203123/208228438-c45a9b48-e818-4254-8158-af960b0a00b7.mov

### Desktop (please complete the following information)

- OS: MacOS Monterey version 12.4
- Chrome: Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by niwinz** [comment]
Clearly a bug, thanks for report. Reported on our internal taiga: https://tree.taiga.io/project/penpot/issue/4613
