### ISSUE TITLE
bug: pressing the enter key gives you an internal error

### ISSUE THREAD

**Issue by Fnige** [uxbox/uxbox#2675]
### Steps To Reproduce

1. Get into a file, any file (Maybe)
2. Press the enter key
3. Oh...

### Expected behavior

Anything but an internal error lol. Probably target being deselected or nothing

### Actual behavior

Internal error.js

### Screenshots or video

https://user-images.githubusercontent.com/35159947/208300744-8c7e60cf-58d2-4427-8773-81a902ad5942.mp4

(Hopefully this is high quality enough)

![image](https://user-images.githubusercontent.com/35159947/208301310-b3fa87d0-347a-4845-ab7a-b8faef199c20.png)

### Desktop (please complete the following information)

- Windows 11 x64
    - 22H2 22623.1037

- Firefox 108.0
    - A couple extensions (can give if needed, but highly doubt theyre the issue)

### Additional context

This bug doesnt seem to happen all the time weirdly which is a worry

**Comment by Fnige** [comment]
The video doesnt seem to work for me until its downloaded for some reason (I dont think tech likes me today)

**Comment by JPustkuchen** [comment]
We can sadly confirm this issue. Happened in Windows 11 with Firefox, while on another machine with Windows 10 and 108.0.1 (64-Bit) everything worked fine in the same workspace.

I guess it's related to Firefox, but I'm not sure yet. It happened, whenever Enter was pressed, irrespective where.

**Comment by eniolajayi** [comment]
@JPustkuchen Hello. Any update on a fix for this issue? 
I have the same issue on Chrome Version 108.0.5359.125 (Official Build) (64-bit) - Windows 11. Might not be related to Firefox alone. Does it occur on MacOS?

I willing to offer more information if need be.
console:
![image](https://user-images.githubusercontent.com/62861035/210246442-77af3aff-45cb-409b-969d-3d5b8e88a9ca.png)

**Comment by superalex** [comment]
Thank you very much for reporting,

We are struggling to reproduce it, just one question, @eniolajayi @JPustkuchen @FnigePython in your failing browsers, if you open an incognito tab is it failing too?. Another user reported that it worked that way and I'm trying to find a pattern.

Thanks!

**Comment by JPustkuchen** [comment]
@superalex sorry on my device I wasn't able to reproduce this, but I triggered my colleague, where that happened. He'll surely reply at least next week after the holidays. :)

**Comment by superalex** [comment]
Thanl you very much @JPustkuchen :)

**Comment by eniolajayi** [comment]
@superalex It's not failing in incognito mode right now. It did yesterday. very tricky bug

**Comment by superalex** [comment]
@eniolajayi it sounds like some chrome plugin producing the error. If you can paste a list of the ones you have installed I can try one by one trying to find the guilty :)

**Comment by eniolajayi** [comment]
@superalex I don't think it's caused by a chrome extension but here they are:

![image](https://user-images.githubusercontent.com/62861035/210425632-2c35c612-e231-4565-9bcf-e84a77458924.png)
![image](https://user-images.githubusercontent.com/62861035/210425758-9cd0c29c-2f66-43e1-9acb-b6ccd7b2a663.png)
![image](https://user-images.githubusercontent.com/62861035/210425908-39902a77-6c28-4793-9b1d-1c47dff08285.png)
![image](https://user-images.githubusercontent.com/62861035/210425973-2cbf58ce-7064-4e04-a9e8-8fc5efa07603.png)

**Comment by superalex** [comment]
Thank you very much @eniolajayi 

@JPustkuchen I'm testing all those extensions but if you could check if your college has any of them installed that would be great

**Comment by superalex** [comment]
Hello!,

I think I found the bug (@eniolajayi you were right, it wasn't related to the chrome extensions). It was related to previous actions in the dashboard, a listener for the enter keyboard event wasn't released properly and it was causing the problem. If you refresh penpot the enter problem should be fixed.

Thank you very much!

**Comment by JPustkuchen** [comment]
@superalex Thank you so much for fixing the bug that quickly! Surely that wasn't easy to find out.

I'll let my colleague know. Thanks!! :)

**Comment by eniolajayi** [comment]
@superalex Nice work 👍. I'm glad it's fixed. Thanks for the quick response

**Comment by superalex** [comment]
You are welcome!, thank you very much for the help :)

**Comment by thomasfrobieter** [comment]
> I'll let my colleague know. Thanks!! :)

Testes in Brave and Firefox, works perfectly fine! Thank you so much (:

**Comment by superalex** [comment]
> Testes in Brave and Firefox, works perfectly fine! Thank you so much (:

Great! :)
