### ISSUE TITLE
translation: Finnish

### ISSUE THREAD

**Issue by kymppi** [uxbox/uxbox#2676]
Hi!
I'm a native Finnish speaker so I want to help translate this project. There aren't any translations for Finnish yet, but I hope I could change that :tada:  My weblate user is [Midka](https://hosted.weblate.org/user/kymppi/)

**Comment by myfunnyandy** [comment]
Hi, 

We've already added you to the translation project and also the Finnish language at the languages list. It always makes us really happy to add a new language! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/fin_FI/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information an about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thanks!
