### ISSUE TITLE
bug: Organizations' name misrepresented in homepage footer

### ISSUE THREAD

**Issue by iprithvitharun** [uxbox/uxbox#2677]
### Steps To Reproduce

1. Go to https://penpot.app/ 
2. Scroll down to footer

### Expected behavior

-  Github should be GitHub
- Linkedin should be LinkedIn
- Youtube should be YouTube

### Actual behavior

Wrong capitalization for organization/app names. 

### Screenshots or video

<img width="253" alt="Screenshot 2022-12-19 at 12 32 40 PM" src="https://user-images.githubusercontent.com/58725708/208371321-f8d56cba-0b96-4c8a-8fb5-b059d9e78c85.png">

### Additional context

Not sure which repo has this content. If you could point me to the repo I can raise a PR fix.

**Comment by myfunnyandy** [comment]
We are currently working on a full redesing of the public site and the footer will change completely. We will publish this soon so there's no point on fixing this, but we will take your suggestion into consideration at the moment of showing brand names in the new site. Thanks!
