### ISSUE TITLE
bug: Add text bug happens at random occasions

### ISSUE THREAD

**Issue by signnd** [uxbox/uxbox#2685]
### Steps To Reproduce

1. Use an optical mouse
2. Select the 'text' tool
3. Click once on an area

### Expected behavior

A textbox without specific dimensions is created and I can directly start typing, as documented on the docs (https://help.penpot.app/user-guide/objects)

### Actual behavior

When the bug kicks in, I need to click the left mouse button once again to fix the textbox dimensions (as if the app was treating the click as click-and-hold to drag items). Sometimes when I do so, the app treats all the keystrokes after it as keyboard shortcut to switch to other tools, but in other times it focuses on the text box when I can finally type something.

(video of the bug appears at around 01:00)

### Screenshots or video

https://user-images.githubusercontent.com/78679178/209146132-54f059fd-0e80-44c2-bd99-ec12f5925981.mp4

### Desktop (please complete the following information)

- Windows 11 22621.963
- Microsoft Edge 108.0.1462.46 (64-bit)
- Toshiba USB Optical Mouse U10

### Additional context

Weirdly, this only happens when in mouse, not when I'm using laptop's touchpad. I can assume that my mouse had no problems :)
(sorry if the title doesn't make it clear enough)

**Comment by superalex** [comment]
Thank you very much @signnd 

I've just created this issue (https://tree.taiga.io/project/penpot/issue/4618) on Taiga to manage it.

Just a few questions: can you reproduce this one with the same mouse and another browser?, and with another mouse?

Regards

**Comment by signnd** [comment]
Hi @superalex, thank you and I'm sorry I haven't got to check it with another mouse. But I can tell that the issue persists when using the same mouse and Firefox version 108.0.1

**Comment by superalex** [comment]
Hi @signnd 

This one was fixed some releases ago but we forgot to close it.

Thanks!
