### ISSUE TITLE
bug: Cannot scroll in handoff mode

### ISSUE THREAD

**Issue by georgkrause** [uxbox/uxbox#2688]
### Steps To Reproduce

1. Visit a design in handoff mode.
2. Try to scroll down or grab the scrollbar

### Expected behavior

The page scrolls down

### Actual behavior

I neither can grab the scrollbar on the right hand side of the page nor can I just page up/page down or the mousewheel to scroll down the page.

### Desktop (please complete the following information)

- Manjaro Linux, sway
- Firefox 108

### Environment (please complete the following information)

Self hosted in docker

**Comment by superalex** [comment]
Hello @georgkrause ,

If you are using https://design.penpot.app/ could you please include the url of the problematic file? (it would also be great if you could include a .penpot file)

Thanks!

**Comment by georgkrause** [comment]
@superalex its selfhosted, I can link or share a penpot file, what is more helpful?

It doesn't seem to be related to the penpot file, though. We have several ones and I experience the same issue for all of them.

**Comment by superalex** [comment]
If you share a penpot file that would be great, thanks! :)

**Comment by georgkrause** [comment]
@superalex I checked again and its indeed only one file which has the issue. I don't want to share it publicly on Github, how can I reach out to you to send it?

**Comment by EvaMarco** [comment]
Hello @georgkrause:

You can send us your files using this address [support@penpot.app](mailto:support@penpot.app)

**Comment by AzazelN28** [comment]
Hi! We've added this issue to Taiga https://tree.taiga.io/project/penpot/issue/4655

**Comment by georgkrause** [comment]
I did send the file today, please reopen!
