### ISSUE TITLE
bug: Text content's original location is preserved when shifting groups of boards around using keyboard controls

### ISSUE THREAD

**Issue by TheHaymaker** [uxbox/uxbox#2690]
### Steps To Reproduce

1. Create groups of boards with nested text content 
2. Select the boards
3. Move the selected boards using keyboard controls (left, right, up and down + shift) 

### Expected behavior

Moving groups of boards around with nested text content would behave the same with keyboard controls (left, right, up and down + shift) as it does with when dragging with mouse (text position is preserved accurately)

### Actual behavior

Text content within boards doesn't move from original position.

### Screenshots or video

![penpot-text-keyboard-move-bug](https://user-images.githubusercontent.com/11251616/209477506-69d3e473-6de9-4efd-897f-a06422dbf0d1.gif)

**Comment by superalex** [comment]
Thank you very much @TheHaymaker 

I've just created this https://tree.taiga.io/project/penpot/issue/4617 to track in using Taiga, we will try to fix it as soon as possible

Regards,

**Comment by Alotor** [comment]
@TheHaymaker thanks for the report, I've seen this error is only happening currently in the develop branch.

On which environment did you find this problem? 

Thanks!

**Comment by TheHaymaker** [comment]
@Alotor  So even though I am running the develop branch locally, I found this behavior while using the penpot.app deployed version as well as inside the deployed beta test branch for flex layout. I originally found it through additional testing in that beta branch.

For what it is worth - I'm running the develop branch locally using docker desktop/ windows / wsl2. 

Thank you so much @superalex @Alotor!
