### ISSUE TITLE
Create new layers at the bottom of the list

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#2712]
### Is your feature request related to a problem? Please describe.

When I create a new layer, it is created at the top of the layer list. Then it takes the id 0.

But when I have already shared my page, the URL leads to the layer 0. Then instead of landing on the right page, my devs land on the new page (sometimes not finished, sometime just a modal, it makes no sense).

### Describe the solution you'd like.

When a layer is created, it is created at the bottom of the layer list.

### Describe alternatives you've considered.

Maybe [this request](https://github.com/penpot/penpot/issues/1312) could help, but all my shares are not necessarily part of a Flow.

**Comment by EvaMarco** [comment]
Hello @NicolasLeboeuf

I'm sorry this is not between our priorities right now, but I have some work arounds that may help you solve this problem

- You can reorder your layers in the side panel
![reorder-layers](https://user-images.githubusercontent.com/48989967/210230738-2460ad7e-0110-4d6c-afb5-f51a5b02388a.gif)

- You can create a flow with the order you want for your shared boards.
![flow](https://user-images.githubusercontent.com/48989967/210231022-f2efc5e4-cd9d-41f6-9696-4da6e2ace168.gif)

- You can hide some boards in shared link
![Screenshot from 2023-01-02 13-26-26](https://user-images.githubusercontent.com/48989967/210231149-bcae5cd7-6842-4f05-b113-c429426db3db.png)

Hope this helps, and thank you so much for your time.
