### ISSUE TITLE
feature: Stick comments (positions) to elements

### ISSUE THREAD

**Issue by JPustkuchen** [uxbox/uxbox#2715]
### Is your feature request related to a problem? Please describe.

Comments are often relate to an element, so when moving the element, you'd expect to have the comment move with it. But the comments are currently placed absolute on the page.

When moving elements or complete groups, also moving the comments positions is a lot of work.

### Describe the solution you'd like.

Make the comments sticky to elements or allow putting them into groups with the elements.
There are many ways this could be solved, with different effects on UX, so I'm not yet sure, how to solve this best.

Some ideas might be (as written above):
- Stick comments to elements generally and move them with the element they are sticked on
- Handle comments like other elements, which allows to see them in the layers and put them into groups (which would move them with the group then)
- - ...?

**Comment by EvaMarco** [comment]
Hello @JPustkuchen:
Our comments are linked to the boards if they are created over one of them. After that if you move the board the comment will move with it. 
Link comments to any element is not between our priorities right now.

Thanks for your time and feedback

**Comment by JPustkuchen** [comment]
@EvaMarco thank you! Indeed, it was a board I was using, having this issue.

In detail, we were wireframing and at a later point had to add a section at the top and bottom. So we had to resize the board. This led to the case that all comments positions were wrong.

So, I'd highly appreciate, if you could think about discussing this issue or moving it to your project management as a feature request for later.

After reading your explanation, I'd say it would be super helpful to stick comments to elements, for example by placing it at the border. Or at least to groups and not only the board.

Anyway, thank you soooo much for PenPot, I really love it! :)

**Comment by KonradHEXANT** [comment]
So, almost 3 years now... annotations in Figma are a VITAL tool for describing details in the context of an item. Comments are good for input from the outside, but as a tool between designer and developer, they sucks if not linked to the element.
