### ISSUE TITLE
bug: "Update Components in a shared library" list is not responsive

### ISSUE THREAD

**Issue by candideu** [uxbox/uxbox#2720]
### Steps To Reproduce

1. Add multiple objects to the canvas (at least 30+)
2. Turn them into components
3. Select them all, right-click, and select "Update Components"

### Expected behavior

No list of components

OR 

List of components can be toggled

OR 

List of components displays inside a window with a scroll bar

OR

List of components is displayed as columns once it reaches the breakpoint

### Actual behavior

If the list of components is too long, the explanatory text and buttons are hidden

### Screenshots or video

Update Components List (100%)

![image](https://user-images.githubusercontent.com/55474996/210189363-a17a67a0-d78c-4dbb-b428-71333b7796ba.png)

Update Components List (50%)

![image](https://user-images.githubusercontent.com/55474996/210189371-4c086f8c-922f-41be-8ca7-8f14ec9cc329.png)

### Desktop (please complete the following information)

Windows 10
Firefox 108.0.1

### Environment (please complete the following information)

Hosted version: design.penpot.app

**Comment by EvaMarco** [comment]
Hi @candideu 

We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/4640) to track this issue from here. We will try to fix it soon.
