### ISSUE TITLE
feature: Set hyperlinks to layers

### ISSUE THREAD

**Issue by candideu** [uxbox/uxbox#2721]
### Is your feature request related to a problem? Please describe.

When I create mood boards in Penpot, I like to keep track of where I've sourced my images, in case I want to return to the source.

### Describe the solution you'd like.

I'd like the ability to set a layer as a hyperlink. Users could access the links by SHFT + Clicking the layer.

### Describe alternatives you've considered.

Making the layer name a hyperlink, adding the link as a comment

### Additional context

Inspiration: Lunacy app

https://twitter.com/Icons8_Lunacy/status/1504863489692680204

![](https://i.imgur.com/8gV42W8.gif)

**Comment by EvaMarco** [comment]
Hello @candideu 
This enhancement is not between our priorities right now, but we will keep this idea for the future. 

Thanks a lot for your feedback and your time.
