### ISSUE TITLE
Update library-file update individual overriden properties

### ISSUE THREAD

**Issue by Malte-Neu** [uxbox/uxbox#2727]
### Steps To Reproduce

I have not been able to repro the problem from the beginning, but I have a file with which it occurs reproducibly. 

- Import the bug.penpot file: [Bug.penpot.zip](https://github.com/penpot/penpot/files/10332472/Bug.penpot.zip)
- Open "Wireframe Instance" and check under Assets->Libraries that there is no update.
- Open "Wireframe Template" and change the position of the first artboard. Save and close the document.
- Open "Wireframe Instance" again and the information about the update appears in the library. It should look like this: 
![grafik](https://user-images.githubusercontent.com/915899/210253089-c2ddf80d-1a12-438b-b507-8e8d43efd8e0.png)
- Click on Update the library
--> oops and you see this:
![grafik](https://user-images.githubusercontent.com/915899/210253158-5de18e39-7487-43c4-8b7f-886fe33a4a46.png)

Component values have been overwritten and all the work from before is gone. And this although nothing was changed at the components, only at another place a text position was changed.

### Expected behavior

Nothing has changed, because no component values have been changed. Even if the components would have changed, all individually overwritten parameters should remain the same.

### Actual behavior

You should be able to see from the images what has happened.

### Desktop (please complete the following information)

Firefox 108.0.1

### Environment (please complete the following information)

Hosted Version https://design.penpot.app

**Comment by EvaMarco** [comment]
Hello @Malte-Neu 
I tried to reproduce your problem: Follow my steps and tell me if you did something different.

1. I had a library file with a component. This component is a rectangle with a text.
![Screenshot from 2023-01-03 09-50-09](https://user-images.githubusercontent.com/48989967/210325081-585cb377-5dfd-4b42-b8f2-26b9c98f99ee.png)

2. I import this library file into other and create 3 new elements with that component
![Screenshot from 2023-01-03 09-44-57](https://user-images.githubusercontent.com/48989967/210325238-1ebee773-7388-4e07-9bc4-4f62650fad26.png)

3. I change the text of two of them and the color of one just to check
![Screenshot from 2023-01-03 09-45-37](https://user-images.githubusercontent.com/48989967/210325319-f32c031b-bcc1-46d7-a265-583f110feaee.png)

4. I went back to the library file and modified the main component
![Screenshot from 2023-01-03 09-46-16](https://user-images.githubusercontent.com/48989967/210325389-37fa5dd4-d89b-4686-808d-575fe3af3add.png)

5. Then I updated my file with the library changes
![Screenshot from 2023-01-03 09-47-30](https://user-images.githubusercontent.com/48989967/210325491-3c86f3d0-bb44-4596-adbe-55269bd428cd.png)

The color and texts changes remain, so I think this is ok.

But please tell me. 
Have your components nested components?
Are your steps very different from mine?

**Comment by Malte-Neu** [comment]
@EvaMarco it's not that simple. Like you, I have also tried it in a completely new project. Unfortunately, I did not succeed in finding a reproducible way. It has occurred, if I have changed even more like sizes and the whole several times. I also used color templates. 

Please try it with my attached file. With it I could reproduce the error as I wrote it down.

**Comment by EvaMarco** [comment]
Hello @Malte-Neu:
I've tried the same with your file. 
1. Added some standar labels
![Screenshot from 2023-01-04 09-26-19](https://user-images.githubusercontent.com/48989967/210514393-ba9d6f0d-3ea0-4f9f-bf33-4f7e22370ec2.png)

2. I went to library page and modify that label with background color and text 
![Screenshot from 2023-01-04 09-27-32](https://user-images.githubusercontent.com/48989967/210514444-9b77a03e-cc1a-4b2e-b134-35531042ff04.png)

3. Come back to the file and and update label
Before updating
![Screenshot from 2023-01-04 09-28-38](https://user-images.githubusercontent.com/48989967/210514604-de5537d6-e536-47d3-923a-1c51cbe07fb6.png)

After updating
![Screenshot from 2023-01-04 09-28-47](https://user-images.githubusercontent.com/48989967/210514660-89c0c2d6-9820-4f4b-87c9-29cc2ecce06d.png)

As you can see I can not reproduce it eather, but we are going to check it more in deep.

**Comment by Malte-Neu** [comment]
Look at the other values. The ±23.00 became 123.00 again from the library. And the width properties were also changed.
![grafik](https://user-images.githubusercontent.com/915899/210537058-c45570e0-444a-43aa-a8b0-65a00ef12139.png)
There the properties were overwritten although they should not have been changed at all. In my case, I did not even edit a used component, I just moved an independent text field.

**Comment by EvaMarco** [comment]
ohh what¡¡ you are right, I was only looking to the labels... my bad. We are going to check it in deep. I will maintain you informed. 

Thanks for your patience

**Comment by hirunatan** [comment]
Sorry, this is a bug affecting component sync of text layers inside components.

I have isolated it (at https://tree.taiga.io/project/penpot/issue/4646) and it's already fixed. This will work well in the next Penpot release.

Until then, you can avoid text layers to be reset by changing anything of their size or position (e.g. changing the text size to "auto width" or moving them a bit and then moving them again to the initial position). The bug was related to the "modified" detection. If you do so, they will be correctly marked as modified and will not be overwritten with the library update.

(BTW: sorry the update library popup currently appears for any change of the library, even moving around an unrelated board; we have in the roadmap to detect what have changed and to show the popup only if there are relevant changes).

**Comment by Malte-Neu** [comment]
I'm glad to read that the bug was fixed quickly, I am looking forward to the new version. Is it possible to estimate when the deployment to penpot.app will happen?

**Comment by EvaMarco** [comment]
We are planing a release for the end of this month, but I'm not sure if It will be fixed sooner. 
Edit -> It's posible that this bug will be fixed by monday. :)

**Comment by hirunatan** [comment]
Yes, we have planned a hotfix update on monday, and this bug will be included.

**Comment by myfunnyandy** [comment]
Closing as this one is solved
