### ISSUE TITLE
feature: "deep click" to select nested elements quickly

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#2740]
### Is your feature request related to a problem? Please describe.

When working with nested elements, I sometimes want to edit an inner element. The problem is that I need to double click for every layer of grouping until I am there. 

### Describe the solution you'd like.

Figma has a "deep click" by using ctrl+click. Instead of going from the inside out, it processes the click from the element under the mouse cursor (jQuery UI used the term "greedy" for such interactions)

### Describe alternatives you've considered.

* Continue double clicking
* Make every click deep by default (this would be too confusing, since it is not standard behavior, but in theory would allow [autogrouping](https://www.fordes.de/posts/autostackautogroupinterfaces.html))

### Additional context

Particularly nice for editing text, which is almost always nested.

**Comment by myfunnyandy** [comment]
Hi @jdittrich, ctrl+click is also the way to do deep selection at Penpot. Here's a gif I've just made in which I'm pressing crtl while hovering layers that are inside a group. Could you try it again? 
![deep-click](https://user-images.githubusercontent.com/708713/211520590-617fdbe4-3c4f-453d-ac02-5c25fabe19f2.gif)

**Comment by jdittrich** [comment]
Thanks! I wonder why it did not work in my first try – a collague also assumed it did not work. I close this; if it turns out the feature is flaky (or whatever else might have caused our assumption), I will open a new one.
