### ISSUE TITLE
bug: Scaling text does not works in a group

### ISSUE THREAD

**Issue by viaz** [uxbox/uxbox#2756]
### Steps To Reproduce

1. Create a text layer and fill it
2. Create another layer and group it with the text layer
3. Enable Scale Text
4. Resize the group

### Expected behavior

Text in group or component should resize when the Enable Scale Text option is active.

### Actual behavior

Text in group or component do not follow the Scale Text option when activated

### Desktop (please complete the following information)

Windows 10
Tested on Edge and Chrome

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by myfunnyandy** [comment]
Hi, this is something that we will implement eventually. Here's the story at our roadmap, where I've added your request: https://tree.taiga.io/project/penpot/us/1951

**Comment by viaz** [comment]
Thanks for your answer, glad that it is on the roadmap

**Comment by myfunnyandy** [comment]
https://github.com/penpot/penpot/issues/1142#issuecomment-1438361980
