### ISSUE TITLE
Rows in the grid have the wrong height

### ISSUE THREAD

**Issue by Malte-Neu** [uxbox/uxbox#2774]
### Steps To Reproduce

- Create a board with the size 100x100
- Activate the grid with rows
- Configure the grid as following:
  - Rows: 9
  - Type: Top (when selecting the type, the pop-up window is positioned incorrectly.)
  - Height: 10px
  - Gutter: 1px
  - Margin: 0px

- Create another board with the size 100x100 with the same grid settings, but this time use 50 rows.

### Expected behavior

The rows are identical in both views and 10px high.

### Actual behavior

The rows of the second grid are much smaller and not the 10px high as defined. 
![grafik](https://user-images.githubusercontent.com/915899/212269090-1dd2092f-6820-4f89-9e0f-fc3bdca83efb.png)
![grafik](https://user-images.githubusercontent.com/915899/212269525-1f990c3d-eeb6-4014-a95c-a86af0331c00.png)

It looks like the stretch type is always uses as soon as the rows no longer fit on the board. Changing the type has no effect on the display.

### Desktop (please complete the following information)

Firefox 108.0.2 (64-Bit)

### Environment (please complete the following information)

Hosted https://design.penpot.app Version

**Comment by myfunnyandy** [comment]
The problem is that there's a collision between some of the settings. There is no way you can have 50 10px height rows separated by 1px in 100px. In this case you can have your height or your rows, but not both. Now rows are prioritized over height, but if we'd find a good reason we might rethink this decision.

**Comment by Malte-Neu** [comment]
From my point of view, it doesn't make sense at the moment, stretching only makes sense if I also select the "stretch" type. Otherwise I would like to have just a fixed size and not have to pay attention to whether my lines still fit into the board. My example was slightly over the top to show the effect, if it was only 12 lines you wouldn't see it right away, but the heights are already wrong. 

Especially if you want to create a line-oriented layout you have to take care that you don't specify one line too much.

From my point of view it would be sufficient that the type is prioritized higher than the number of lines. If you want to make it perfect, you would have to hide certain combinations in the gui. If you select the height "auto", then the type is actually no longer interested. If you choose a certain height, stretch again makes no sense.

**Comment by myfunnyandy** [comment]
I see your point and agree that preserving the rows amount is not useful in almost any case. I've added an issue at our roadmap and we will change this behaviour: https://tree.taiga.io/project/penpot/issue/4685

Thank you for taking the time of pointing it out and justifying it.
