### ISSUE TITLE
Usability: keyboard shortcut search

### ISSUE THREAD

**Issue by Goli4thus** [uxbox/uxbox#2780]
### Is your feature request related to a problem? Please describe.

This is the status quo when it comes to using the 'keyboard shortcuts' search:
- one opens the search via '?' key
- one has to click the search field via mouse
- one searches for a shortcut
- one needs to unfocus the search field via clicking somewhere else via mouse ('tab' key isn't helping in this case, cause it will just focus some other field) or close the whole area via the respective close button
- one can finally execute the desired shortcut

### Describe the solution you'd like.

Better usability would be this:
- one opens the search via '?' key
- **the search field gets auto-focused for input**
- one searches for a shortcut
- **one can just hit 'escape' to close the search area**
- one can finally execute the desired shortcut

This way there's no need for any mouse interaction, which speeds up the workflow quite a bit.

**Comment by myfunnyandy** [comment]
Very nice proposal, I've added it as priority enhancement to our roadmap as it seems to be very interesting in terms of accessibility. The issue at taiga: https://tree.taiga.io/project/penpot/issue/4713

**Comment by Goli4thus** [comment]
Thanks for considering, I'm looking forward to it!

**Comment by myfunnyandy** [comment]
Fact is that this one made the cut faster than usual because is related to some accesibility improvements that we're implementing. This gif shows the new interaction via keyboard. We will probably publish it with the next release.

![shortcuts-all1](https://user-images.githubusercontent.com/708713/213994662-529649be-6699-42cc-9e31-3853d176eb64.gif)

**Comment by Goli4thus** [comment]
Very nice, from what I can see, it's just like I had imagined!

I see, certainly didn't expect it to happen so fast, so in part a lucky coincidence. But I'm sure many users will appreciate upcoming accessibility improvements, cause even if it will be unconscious for some, little workflow improvements like this one add up and make the application feel like it aids one more in what one is trying to achieve.

Thanks again!
