### ISSUE TITLE
bug: login error 

### ISSUE THREAD

**Issue by witkeyshare** [uxbox/uxbox#2782]
### Steps To Reproduce

1. register account
2. login the account 
3. can not login in chrome  browser version :109.0.5414.74

### Expected behavior

hope login in chrome browser

### Actual behavior

can not login in chrome  browser version :109.0.5414.74

### Screenshots or video

![image](https://user-images.githubusercontent.com/1550026/212598020-2963450e-9b96-40c2-9b26-79b7c1d4e8eb.png)

![image](https://user-images.githubusercontent.com/1550026/212598149-d4bfebe3-78f7-4f29-a690-d787f120d462.png)

![image](https://user-images.githubusercontent.com/1550026/212598209-08b0ef04-f896-4465-90e7-1a8fc015ef1d.png)

**Comment by dishuostec** [comment]
I have same problem.
Get 404 when sign up or login.

I found some log:

> penpot-frontend_1  | 192.168.16.1 - - [16/Jan/2023:05:16:03 +0000] "POST /api/rpc/command/prepare-register-profile HTTP/1.1" 404 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
> penpot-frontend_1  | 192.168.16.1 - - [16/Jan/2023:05:16:19 +0000] "POST /api/rpc/command/login-with-password HTTP/1.1" 404 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"

It seems something wrong with `penpot-backend`.

Environments:
Docker version 20.10.12, build e91ed57
MacOS 13.0.1 (22A400)

**Comment by superalex** [comment]
It sounds like some kind of configuration error, what url are you using to access penpot?

**Comment by dishuostec** [comment]
For me, `http://localhost:9001/#/auth/login`.
Chrome request detail:

> General
Request URL: http://localhost:9001/api/rpc/command/login-with-password
Request Method: POST
Status Code: 404 Not Found
Remote Address: [::1]:9001
Referrer Policy: no-referrer

> Response Headers
Connection: keep-alive
Date: Mon, 16 Jan 2023 08:21:43 GMT
Server: nginx
Server-Timing: total;dur=3.033E-4
Transfer-Encoding: chunked

> Request Headers
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Content-Length: 69
content-type: application/transit+json
Host: localhost:9001
Origin: http://localhost:9001
sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
x-frontend-version: 1.16.2-beta-8405-g5605ac276

**Comment by dishuostec** [comment]
Here are my configurations.

<details><summary>config.env</summary>

```bash
PENPOT_PUBLIC_URI=http://localhost:9001
PENPOT_FLAGS=enable-registration enable-login disable-email-verification disable-secure-session-cookies
PENPOT_HTTP_SERVER_HOST=0.0.0.0
PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
PENPOT_DATABASE_USERNAME=penpot
PENPOT_DATABASE_PASSWORD=penpot
PENPOT_REDIS_URI=redis://penpot-redis/0
PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
PENPOT_TELEMETRY_ENABLED=false
PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com

```

</details>


<details><summary>docker-compose.yaml</summary>

```Dockerfile
---
version: "3.5"

networks:
  penpot:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    ports:
      - 9001:80

    volumes:
      - ./data/assets:/opt/data

    env_file:
      - config.env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    volumes:
      - ./data/assets:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    env_file:
      - config.env
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:14"
    restart: always
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot

```

</details>

**Comment by witkeyshare** [comment]
> It sounds like some kind of configuration error, what url are you using to access penpot?

i modify the env params, it ok

PENPOT_FLAGS disable-demo-warning enable-cors disable-secure-session-cookies enable-insecure-register enable-registration enable-login disable-email-verification disable-smtp

------->

PENPOT_FLAGS	enable-registration enable-login disable-email-verification disable-secure-session-cookies

and thx  @dishuostec  i copy your  config

**Comment by dishuostec** [comment]
I changed config.env, but it still get 404.


> penpot-frontend_1  | 172.21.0.1 - - [16/Jan/2023:09:31:31 +0000] "GET /api/rpc/query/profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
> penpot-frontend_1  | 172.21.0.1 - - [16/Jan/2023:09:32:11 +0000] "POST /api/rpc/command/login-with-password HTTP/1.1" 404 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
> penpot-frontend_1  | 172.21.0.1 - - [16/Jan/2023:09:32:15 +0000] "POST /api/rpc/command/prepare-register-profile HTTP/1.1" 404 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"

<details><summary>config.env</summary>

```bash

PENPOT_PUBLIC_URI=http://localhost:9001
PENPOT_FLAGS=disable-demo-warning enable-cors disable-secure-session-cookies enable-insecure-register enable-registration enable-login disable-email-verification disable-smtp
PENPOT_HTTP_SERVER_HOST=0.0.0.0
PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
PENPOT_DATABASE_USERNAME=penpot
PENPOT_DATABASE_PASSWORD=penpot
PENPOT_REDIS_URI=redis://penpot-redis/0
PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
PENPOT_TELEMETRY_ENABLED=false
PENPOT_SMTP_DEFAULT_FROM=no-reply@example.com
PENPOT_SMTP_DEFAULT_REPLY_TO=no-reply@example.com

```

</details>

**Comment by niwinz** [comment]
404 is because your backend is running different version that frontend, ensure you pull the same version for backend and frontend on docker

**Comment by niwinz** [comment]
I mean, @dishuostec you have different error than @witkeyshare 
In your case, the backend report 404 (NOT FOUND) this means this endpoint does not exists on the current instance running  but frontend exepect it to exists; the unique cause of this, is that backend image is running some old image that does not match the current version.

Try run `docker compose pull`before start and then restart. If it does not works, try setting `1.16.2-beta` tag on all penpot images on the compose file instead of `latest`, then pull and restart all containers.

**Comment by dishuostec** [comment]
@niwinz I see. I removed docker registry mirror and pulled latest images, and It worked.

**Comment by dishuostec** [comment]
Thank all you guys. @witkeyshare Shall we close this issue now?

**Comment by witkeyshare** [comment]
ok, thx
