### ISSUE TITLE
enhancement: "Export boards to PDF" language review

### ISSUE THREAD

**Issue by iprithvitharun** [uxbox/uxbox#2791]
### Steps To Reproduce

This action seems similar to Word's "Save as" feature. So, looking at it from this perspective the option is going to save (or export) the particular board in the mentioned format (PDF).

Also, people are more used to seeing (and using) "to" for converting actions. Converting _from_ one format _to_ one. For example, "Convert EPUB to PDF". This sentiment was echoed by UX Writing community members (credits: Asif Ali and Unnathi).

"Export board _to_ PDF" can also be interpreted as exporting the selected board to an existing local PDF. Like, adding an additional page to an existing PDF file.

In the early days of PDF, the print stream was outputted _to_ PostScript which was then translated _to_ PDF using Acrobat. Now, in the modern days, as things evolved, direct export has become possible and efficient. So, there is no point in using _to_. This is my theory and not could be wrong.

The fact that the competitors are also using **_to_** was considered and I think those instances are confusing as well.

All this being said, I recommend using **_as_** instead of **_to_**. Like, Export boards as PDF.

@myfunnyandy I'd like to know the team's thoughts before contributing. 

<img width="640" alt="Screenshot 2023-01-16 at 8 48 31 PM" src="https://user-images.githubusercontent.com/58725708/212829532-30a9fdb7-f8f5-4e6e-81b2-7b58ffb7027d.png">

**Comment by myfunnyandy** [comment]
@iprithvitharun our only concern is that if competitors are using _**to**_, our users might be also familiarized with the expression. However, we found the argument very convincing and we feel confortable going with the _**as**_ option, agreeing that is a more correct one. We'd be happy to have this contribution.

**Comment by iprithvitharun** [comment]
@myfunnyandy Thanks. PR raised. 

About the familiarity, I did consider it. But the consistency with _behavior_ and _position_ will offset the content change. I still strongly believe that users wouldn't notice this change because now it reads more natural and conversational.
