### ISSUE TITLE
Sizes will be reset after updating the library file

### ISSUE THREAD

**Issue by Malte-Neu** [uxbox/uxbox#2794]
### Step by step
Create library file:
- Create new File
- Create a SVG-Path
- Create component from this path
- Publish the library
- Close library file
- OR use the attached File [Lib-File.penpot.zip](https://github.com/penpot/penpot/files/10433194/Lib-File.penpot.zip)
 
Use the library File  and create a new component
- Create a  new file 
- Use the previously created lib-file
- place the component inside a rect and resize it
- create a component from this newly created objects
- use this component
- close the document

Modify Library file
- Open library file again
- change anything in the file like move a component
- close the file

Open the other file again.
- It appears "There are updates in shared libraries"
- Click Update

### Or with the attached file: 
[bug-using-lib.zip](https://github.com/penpot/penpot/files/10433514/bug-using-lib.zip)
- Open "Using Lib-Component" -> everything is correct
- Close and open "Lib-File" 
- Move anythin in the file
- close and open the other file
- Update the shared libraries

### Expected behavior

Nothing changed

### Actual behavior

The instance of the component from the file has the original size again.

### Screenshots or video

![Recording 2023-01-17 at 10 48 33](https://user-images.githubusercontent.com/915899/212871181-a5683bdd-6ac1-4dd8-a874-8b4fa924cb4a.gif)

### Desktop (please complete the following information)

Firefox

### Environment (please complete the following information)

Hosted https://design.penpot.app

**Comment by myfunnyandy** [comment]
We've added the issue to our issue tracker. You can check the progress here: https://tree.taiga.io/project/penpot/issue/4716

**Comment by hirunatan** [comment]
Sorry. This is not exactly a bug, but a limitation of the current components structure and synchronization algorithm.

I've changed this to an User Story, to be studied in the components redesign we are working on https://tree.taiga.io/project/penpot/us/4745

As a (not very good) workaround, you may do a "Reset overrides" in the composed component, after it brokes, and it should come back as it should be. BUT if the component contains any path, this will not work. There is anoter, related, bug about it https://tree.taiga.io/project/penpot/us/4745. This one is already solved, it will be available in the next release.

I apologize for the complicated response...
