### ISSUE TITLE
Updating the library resets values of instances

### ISSUE THREAD

**Issue by Malte-Neu** [uxbox/uxbox#2795]
### Steps To Reproduce

- Create a component from a rectangle and a text
![grafik](https://user-images.githubusercontent.com/915899/212874798-b89717bd-5d01-4bde-b714-63f9cff6a285.png)
- Create a instance of the component and remove the text
- Create another component from this changed component instance
![grafik](https://user-images.githubusercontent.com/915899/212877465-f78cede1-489b-4d2a-a2ee-f9b6f64d662b.png)
- publish the library
![grafik](https://user-images.githubusercontent.com/915899/212877595-f8e89992-6da7-4375-9707-08be6e1f6093.png)
- close the file
- create a new file and add the previous created library 
- add both components and resize these (maybe resizing is not necessary)
![grafik](https://user-images.githubusercontent.com/915899/212879330-4e38b16b-717b-4156-a76b-f048e213fc87.png)
- all step up to here are in this file: [bug_reset.zip](https://github.com/penpot/penpot/files/10434098/bug_reset.zip)
- close the file and go back to the library docuament
- move one of the elements and close 
- open the instance file again
- click update on "There are updates in shared libraries"

### Expected behavior

Nothing changed

### Actual behavior

The component with the deleted text contains text again.
![grafik](https://user-images.githubusercontent.com/915899/212880054-34940844-0c3f-4b45-a191-ff5547615cbd.png)

### Screenshots or video

![Recording 2023-01-17 at 12 27 51](https://user-images.githubusercontent.com/915899/212887762-904a760d-73e8-42d5-8c7a-379bad25b261.gif)

### Desktop (please complete the following information)

Firefox

### Environment (please complete the following information)

Hosted Version https://design.penpot.app

**Comment by myfunnyandy** [comment]
Added to our issue tracker: https://tree.taiga.io/project/penpot/issue/4717

We are currently working on a whole revamp of the components system, we hope include fixing this issue and the previous one among the changes.
