### ISSUE TITLE
Translation access request for Indonesian

### ISSUE THREAD

**Issue by Linerly** [uxbox/uxbox#2804]
Hello there, I would like to help out translating Penpot to Indonesian :slightly_smiling_face:

I am [Linerly](https://hosted.weblate.org/user/Linerly/) on Weblate

**Comment by myfunnyandy** [comment]
We've already added you to the translation project. Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/id/) and start translating. 

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!

**Comment by Linerly** [comment]
I've recently finished the translation — 100% translated

**Comment by myfunnyandy** [comment]
That's really impressive @Linerly, we hope to publish these changes soon.

Thank you very much for your contribution.

**Comment by myfunnyandy** [comment]
Hi @Linerly, it took us more than expected but the indonesian translations are already available for all Penpot users. Thanks!
