### ISSUE TITLE
bug: Non-AWS S3 Providers (such as MinIO) only seem to work with a Port defined

### ISSUE THREAD

**Issue by Dan6erbond** [uxbox/uxbox#2811]
### Steps To Reproduce

1. Deploy a S3 compatible service such as MinIO.
2. Make sure the S3 service is exposed as a public URL, something like `s3.mydomain.com`.
3. Use the public domain to configure Penpot's `PENPOT_STORAGE_ASSETS_S3_ENDPOINT` parameter.

### Expected behavior

Uploading and viewing files should work.

### Actual behavior

A 500 is thrown in the Penpot backend as it isn't able to reach `<bucket-name>.s3.mydomain.com`. Penpot should use path-style access to S3 services possibly with an environment variable like `PENPOT_STORAGE_ASSETS_S3_USE_PATH_STYLE=true` to avoid this.

### Desktop (please complete the following information)

- OS: Windows
- Browser: Chrome

### Additional context

This is related to #2306 where the issue of accessing S3 on local paths (= with ports) seems to have been fixed, but unless I misconfigured something it doesn't work with public S3 services.

**Comment by Dan6erbond** [comment]
Just checked through the commit history and found that on `staging` there's a commit #2719 that fixes this issue. At least my limited understanding of Clojure says so. Any ETA on when it will be released? Or a way for me to build & deploy it myself? I really would love to get this project running ASAP. Thanks so much for the entire team's effort!

**Comment by niwinz** [comment]
soon, probably 2 weeks or so.

**Comment by niwinz** [comment]
For build docker image locally you will need to do:

- first you need to generate the bundle with `./manage.sh build-bundle`
- then `./manage.sh build-docker-images` 

All on `staging` branch.

**Comment by Dan6erbond** [comment]
@niwinz just saw that the latest Penpot backend release includes the fix. Awesome! Just one question. How do I enable S3 to use path-style access with MinIO? After updating the backend image I still get the same error, with this config:

```hcl
    PENPOT_STORAGE_ASSETS_S3_REGION   = "homelab01"
    PENPOT_STORAGE_ASSETS_S3_BUCKET   = minio_s3_bucket.penpot.bucket
    PENPOT_STORAGE_ASSETS_S3_ENDPOINT = "https://${var.s3_host}"
```

**Comment by Dan6erbond** [comment]
Hmm, weird. I teared down the entire infra and spinned up a new instance of Penpot, and noticed that I see this in the logs:

```console
[2023-01-31 15:35:51.698] I app.main - msg="welcome to penpot", flags="backend-api-doc,secure-session-cookies,backend-worker,login-with-oidc,registration", worker?=true, version="1.16.1-beta-8399-gca7ebdcc8"
```

Is it possible the Docker release didn't properly update the binaries? I'm explicitly setting the `1.17.0` image tag so it should have updated Penpot.

**Comment by superalex** [comment]
You are wright @Dan6erbond I was regenerating those just now, I will need still some minutes :)

Thanks!

**Comment by Dan6erbond** [comment]
Hmm, now I'm getting this @superalex:

```console
[2023-01-31 16:57:31.642] E app.http.errors - hint="Unable to execute HTTP request: javax.net.ssl.SSLProtocolException: Cannot decode named group: x25519"
TRACE:
 →  software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: javax.net.ssl.SSLProtocolException: Cannot decode named group: x25519 (SdkClientException.java:111)
 →  io.netty.handler.codec.DecoderException: javax.net.ssl.SSLProtocolException: Cannot decode named group: x25519 (ByteToMessageDecoder.java:499)
 →  javax.net.ssl.SSLProtocolException: Cannot decode named group: x25519 (:-1)
DETAIL:
 →  software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: javax.net.ssl.SSLProtocolException: Cannot decode named group: x25519 (SdkClientException.java:111)
```

My MinIO instance is behind Traefik with valid SSL certificates. Almost all of my apps deployed to Kubernetes use it in some capacity without issue, so what could be the cause here?

**Comment by niwinz** [comment]
Yep, looks like an internal issue on the new approach on how we generate the JRE, I will revert the change and push new images soon that should fix this issue.

**Comment by Dan6erbond** [comment]
Hey, thanks for your responsiveness! I appreciate it a ton. Just waiting on this fix to get Penpot set up, since I like to avoid using too many PVCs where it isn't necessary and I can use S3 instead. It makes the configuration more lightweight and I have better control over the data with MinIO's panel.

Any ETA on when I can try out the fix? Will this be another quick patch like earlier or will I need to wait for the next release? Thanks!

**Comment by niwinz** [comment]
It will be available for this release. I will update the images ASAP, i'm performing the last checks on the build process right now.

**Comment by niwinz** [comment]
new images published, pull the latest or the `1.17.0-1` tag

**Comment by Dan6erbond** [comment]
Hey, thanks for the quick fix! I pulled the image and uploading works! I noticed that the default Helm chart config creates an `nginx.conf` file that doesn't quite work. I get a 502 when trying to access `/assets` but I simply moved from using Nginx to serve assets (and handle API requests, exporter and websockets) directly via the Ingress to the applicable service.

So for anyone interested this is what my Ingress config looks like in Terraform:

```hcl
resource "kubernetes_ingress_v1" "penpot" {
  metadata {
    name      = "penpot"
    namespace = kubernetes_namespace.penpot.metadata.0.name
    annotations = {
      "traefik.ingress.kubernetes.io/router.entrypoints"      = "websecure"
      "traefik.ingress.kubernetes.io/router.tls.certresolver" = "letsencrypt"
      "traefik.ingress.kubernetes.io/router.middlewares"      = "${kubernetes_namespace.penpot.metadata.0.name}-${kubernetes_manifest.penpot_wss_middleware.manifest.metadata.name}@kubernetescrd"
    }
  }
  spec {
    rule {
      host = var.host
      http {
        path {
          path      = "/"
          path_type = "Prefix"
          backend {
            service {
              name = kubernetes_service.penpot_frontend.metadata.0.name
              port {
                name = "http"
              }
            }
          }
        }
        path {
          path      = "/api"
          path_type = "Prefix"
          backend {
            service {
              name = kubernetes_service.penpot_backend.metadata.0.name
              port {
                name = "http"
              }
            }
          }
        }
        path {
          path      = "/api/export"
          path_type = "Prefix"
          backend {
            service {
              name = kubernetes_service.penpot_exporter.metadata.0.name
              port {
                name = "http"
              }
            }
          }
        }
        path {
          path      = "/assets"
          path_type = "Prefix"
          backend {
            service {
              name = kubernetes_service.penpot_backend.metadata.0.name
              port {
                name = "http"
              }
            }
          }
        }
        path {
          path      = "/ws/notifications"
          path_type = "Prefix"
          backend {
            service {
              name = kubernetes_service.penpot_backend.metadata.0.name
              port {
                name = "http"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by nealf** [comment]
I ran into the same [502 response issue](https://github.com/penpot/penpot/issues/2811#issuecomment-1411605486) with our deployment on Kubernetes and using S3/Minio. Apparently the `resolver 127.0.0.11` setting in the [nginx.conf](https://github.com/penpot/penpot/blob/develop/docker/images/files/nginx.conf) will only work to resolve Docker/Kubernetes internal names, and was failing to resolve the FQDN of my Minio host on redirect with messages like `recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53`.

I followed @Dan6erbond advice and added an additional ingress for the `/assets` path pointing to the penpot-backend service directly, and things are working now. There might be some better way to configure nginx to accommodate both situations (if I figure it out I'll open an issue/PR), but the workaround is good for now. Thanks!

**Comment by HugoDuret** [comment]
I had the same problem as @nealf:
- deployment on Kubenetes
- using Minio as a S3 solution
- getting a 502 response for GET requests _/assets/by-file-media-id/014538e7-8bb5***_

I did the hack of adding a specific path for _/assets/by-file-media-id_ directly to the backend in my Ingress, and it works.

Digging into the problem, it seems to be a problem with the nginx redirection of media_id containing dashes (**-**).
To demonstrate this hypothesis:
```
root@penpot-frontend-774d96ccfd-jmvck:/# curl localhost/assets/by-file-media-id/014538e7-8bb5-8007-8003-606d1bdd3423
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@penpot-frontend-774d96ccfd-jmvck:/# curl localhost/assets/by-file-media-id/014538e7
["^ ","~:type","~:not-found","~:hunt","object not found"]
```
where, from inside the frontend container, I searched
1. an existing file of which the media_id contains dashes. I get a 502 after a time
2. a non-existing file without dashes. I get immediately a 404

Both use localhost so it goes through nginx

But if, still inside the frontend container, I run
```
root@penpot-frontend-774d96ccfd-jmvck:/# curl penpot-backend/assets/by-file-media-id/014538e7-8bb5-8007-8003-606d1bdd3423 -v
*   Trying 10.3.161.226:80...
* Connected to penpot-backend (10.3.161.226) port 80 (#0)
> GET /assets/by-file-media-id/014538e7-8bb5-8007-8003-606d1bdd3423 HTTP/1.1
> Host: penpot-backend
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< cache-control: max-age=86400000
< x-host: minio.***.***
< x-mtype: image/gif
```
I get the correct file, direclty asking the backend container without going through nginx.

Is is a nginx issue? Or a penpot's?

Hope it helps.

**Comment by planecore** [comment]
I have the same `recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53` error in the frontend container when trying to load assets using the `assets/get-file-media-id` route. I deployed the penpot helm chart and using minio for storage. Uploads do work as usual, very weird.

**Comment by andreyrd** [comment]
@planecore See https://github.com/penpot/penpot-helm/issues/12
You may need to set `config.internalResolver` to the IP of your CoreDNS service.

Even with that I was getting 499s for `/asset` on the frontend container until I created an extra ingress for `/asset` that goes directly to the backend. AND I had to publicly expose my S3 service since it uses just a redirect instead of proxying.

**Comment by amanos1022** [comment]
To build on the answer by @andreyrd :

Ingress K8s resources (note that this has a fix for a websocket issue I  was facing as well):
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: penpot-assets
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: penpot.yourdomain.com
      http:
        paths:
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: penpot-backend
                port:
                  number: 6060
          - path: /ws(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: penpot-backend
                port:
                  number: 6060
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-public
spec:
  rules:
    - host: minio.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
```

Get K8 cluster's CoreDNS ip:
```bash
kubectl get svc -n kube-system | grep kube-dns | awk -n '{print $3}'
```
put that in `config.internalResolver` of your helm chart values, though I'm pretty sure that just sets the `PENPOT_INTERNAL_RESOLVER` env var in the pod.

Finally apply using `kubectl`.

This isn't ideal, since now we have to expose the minio server to the public as well as have K8s Ingress resources that are maintained outside of the `penpod/penpod` helm chart.
