### ISSUE TITLE
bug: Next board arrow isn't aligned properly

### ISSUE THREAD

**Issue by iprithvitharun** [uxbox/uxbox#2824]
### Steps To Reproduce

1. Open a file and click Prototype (View mode).
2. Click **Handoff**.
3. Click **Code**.
4. Click the right arrow key to move to the next board. 

### Expected behavior

The arrow key should align when users open the code panel.

### Actual behavior

The arrow key isn't moving/aligning when users open the code panel. 

### Screenshots or video

https://user-images.githubusercontent.com/58725708/214064452-eddfa7c0-ddb3-4741-87e7-399f40577d39.mov

### Desktop (please complete the following information)

macOS Monterey 12.6.2 (21G320)

Chrome browser version - 109.0.5414.87 (Official Build) (arm64)

**Comment by myfunnyandy** [comment]
Added to our issue tracker: https://github.com/penpot/penpot/issues/2824

Thanks!
