### ISSUE TITLE
feature: dumb proof install manual

### ISSUE THREAD

**Issue by KvizadSaderah** [uxbox/uxbox#2863]
### Is your feature request related to a problem? Please describe.

I have absolutely the same [issue](https://github.com/penpot/penpot/issues/2553)  , and as I see there some other's lie me, but in previous year at least

### Describe the solution you'd like.

Can you expand install manual part for even dumb like people could make it? :)

Please.

**Comment by myfunnyandy** [comment]
Hi, the issue you referenced is solved, is there anything else that you're missing? Are you having a different problem?

We've recently published a couple of article with info about self-hosting Penpot that you might find of interest:
https://community.penpot.app/t/self-hosting-penpot-i/2336
https://community.penpot.app/t/self-hosting-penpot-ii/2337

**Comment by KvizadSaderah** [comment]
Let me check again.

**Comment by KvizadSaderah** [comment]
nope, that bug is 100% reproducing for me, that should be my skill :)

ok, i would use official public instance for now. 
Too much work, and i can write reply really late, so I'd close this
