### ISSUE TITLE
bug: top bar hides behind browser address bar

### ISSUE THREAD

**Issue by icubyx** [uxbox/uxbox#2871]
### Steps To Reproduce

1. Use latest firefox browser. 
2. Open a penpot file. 
3. Select a board. 
4. You will notice that the top bar shifts and hides below the browser address bar and there is no way to bring it back down. 

### Expected behavior

The top bar should not shift and hide below the address bar. 

### Actual behavior

The top bar shifts up and hides behind address bar. 

### Desktop (please complete the following information)

OS - Windows 10
Browser - Firefox 109

### Smartphone (please complete the following information)

NA

### Environment (please complete the following information)

https://design.penpot.app

**Comment by jdittrich** [comment]
Thanks for reporting!
Could you make a screenshot? I can't reproduce this on Firefox/Windows.

**Comment by icubyx** [comment]
https://user-images.githubusercontent.com/36615794/215979791-66aa0121-1481-4c7e-9548-f8cd383d89d3.mp4

Hope the video helps.

**Comment by jdittrich** [comment]
Thanks! I do not have this behavior and I wonder if your other issue, #2872, is related to this. Could it be that a firefox extension causes this behavior?

**Comment by EvaMarco** [comment]
Hello¡¡ Yes @jdittrich  both issues are related. I'm going to check it and create an issue on our taiga Project.
https://tree.taiga.io/project/penpot/issue/4774
