### ISSUE TITLE
bug: cannot select text by clicking ON it

### ISSUE THREAD

**Issue by icubyx** [uxbox/uxbox#2872]
### Steps To Reproduce

1. Select a board
2. Using the text tool, write something.
3. Click elsewhere to deselect the text. 
4. Now try to select the text by clicking ON it

### Expected behavior

Text should get selected when someone clicks it. 

### Actual behavior

One has to move a few pixels BELOW the text to highlight and select it. 

### Desktop (please complete the following information)

OS - Windows 10
Browser - Firefox 109

### Smartphone (please complete the following information)

NA

### Environment (please complete the following information)

[https:](https://design.penpot.app/)

**Comment by jdittrich** [comment]
I can’t reproduce this; both click-to-select-object and click-to-select-text (like in a word processor) work for me without the offest you describe. Could you record a short GIF or the like?

**Comment by hugovermaak** [comment]
So, I think what @icubyx means is that when trying to single-click on existing text with the text tool, it creates a new text element instead of selecting the original clicked one to edit it. Single-clicking a text element with the text tool to select it for the edit is the expected behavior. This is how it works in XD and in Figma.

I am trying to export it GIF but it is taking forever, will upload it when it is done.

**Comment by icubyx** [comment]
> So, I think what @icubyx means is that when trying to single-click on existing text with the text tool, it creates a new text element instead of selecting the original clicked one to edit it. Single-clicking a text element with the text tool to select it for the edit is the expected behavior. This is how it works in XD and in Figma.
> 
> I am trying to export it GIF but it is taking forever, will upload it when it is done.

That also is another problem I'm having. Thanks for mentioning that. But the current issue is exactly what I say - can't select the text with a pointer when I click ON it. The video should explain it better.

**Comment by icubyx** [comment]
https://user-images.githubusercontent.com/36615794/215980816-333413bb-93f5-4eb5-9a5c-553d8a39335e.mp4

Notice how I have to hover BELOW the text area to highlight it and click there to select it. The text is not highlighted when I'm hovering or clicking over it.

**Comment by icubyx** [comment]
I have disabled all extensions, restarted the browser and notice the same behaviour. Now that you mention it, this one and #2871 are related. When I load this file, I can click on the text properly. However once I click on the text, the top bar moves and hides behind the address bar AND now, I have to click BELOW the text to select it. Attaching the screen capture below. Some weird displacement of the target...


https://user-images.githubusercontent.com/36615794/216004623-5d90b825-a5a4-4bee-a637-fa6b48523d37.mp4

**Comment by superalex** [comment]
Hmmmmm, @icubyx could you please export a .penpot file and include it here to see if we can reproduce the issue too?

**Comment by icubyx** [comment]
[New File 11.zip](https://github.com/penpot/penpot/files/10555576/New.File.11.zip)

Done!

**Comment by superalex** [comment]
Thanks @icubyx 

I've tested on windows with firefox with your same version and couldn't reproduce


https://user-images.githubusercontent.com/1579633/216009191-a1f8e773-d650-4502-adef-081abfeda8ee.mp4

Did you try an incognito tab to see if it still happens?

**Comment by icubyx** [comment]
yes. happens in incognito / private tab too. Let me check if happens in chrome also and get back.

**Comment by icubyx** [comment]
I confirm same behavior in brand new install of chrome too.

**Comment by superalex** [comment]
It's so strange...In your video I see some white space appearing on the screen, could it be something you have installed in your system?, some tool for texts?, could you please record your entire screen and not only the browser window?

**Comment by ondrejkonec** [comment]
Hello guys, it looks like it's exactly the same distance as a height white space below browser. That might be an issue.
![Snímek obrazovky 2023-02-01 v 12 06 38](https://user-images.githubusercontent.com/28909808/216026252-3812c8cc-08e2-407d-bed3-5f91f389569e.png)

@icubyx what is your device please? I think I have familiar issues with Firefox on mobile.

**Comment by icubyx** [comment]
No there is nothing I have installed. Uploading the complete screen record using brand new chrome install without any extensions. Same result...

https://user-images.githubusercontent.com/36615794/216030153-3b9b1a9b-fd27-4d5d-b115-31faa972df96.mp4

**Comment by icubyx** [comment]
> Hello guys, it looks like it's exactly the same distance as a height white space below browser. That might be an issue. ![Snímek obrazovky 2023-02-01 v 12 06 38](https://user-images.githubusercontent.com/28909808/216026252-3812c8cc-08e2-407d-bed3-5f91f389569e.png)
> 
> @icubyx what is your device please? I think I have familiar issues with Firefox on mobile.

I'm using FF 109 in windows 10

**Comment by superalex** [comment]
Just one more question, whats your screen resolution?, I think this one is related to small ones :)


https://user-images.githubusercontent.com/1579633/216033798-a00a2ba7-abc4-403a-be94-28cf85b34090.mp4

**Comment by EvaMarco** [comment]
Ey  @icubyx  Thanks for your help we could reproduce it. and thanks @jdittrich and @ondrejkonec you got the hint we need.
I've created an issue on Taiga to solve this. https://tree.taiga.io/project/penpot/issue/4774

**Comment by icubyx** [comment]
> Just one more question, whats your screen resolution?, I think this one is related to small ones :)
> Peek.2023-02-01.12-44.mp4

1920 x 1080

**Comment by EvaMarco** [comment]
In the video you have the left toolbar outside the bottom border, and that happens when your viewport is less than 650px height. Are you sure your viewport is on 1080? do you have your dev tools open or something like this?

**Comment by icubyx** [comment]
> In the video you have the left toolbar outside the bottom border, and that happens when your viewport is less than 650px height. Are you sure your viewport is on 1080? do you have your dev tools open or something like this?

My screen height is 1080 - so excluding the browser nav and address bar + windows taskbar, the actual res could be more like 800px.

**Comment by EvaMarco** [comment]
Do you have added some zoom to the UI? (sorry for all this questions, jejje just triying to fix it now) :)

**Comment by icubyx** [comment]
> Do you have added some zoom to the UI? (sorry for all this questions, jejje just triying to fix it now) :)

No. It is just like it is :) It is a 13" screen if that makes a difference...- Actually 894 px high as calculated after taking a screenshot. Thanks for all the effort!

**Comment by ondrejkonec** [comment]
I still think that that has something to do with some Windows / Browser settings. 

@icubyx could you please paste the whole screenshot on the screen when you have opened Penpot web app? By this I mean also Windows toolbar if you have enabled. Thanks!

**Comment by icubyx** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/36615794/216045890-988963cb-6a5e-4de4-b630-ae698ae39be7.png)

**Comment by icubyx** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/36615794/216046701-9820320b-7097-40d4-8753-7fd82380864e.png)

this one with Chrome

**Comment by EvaMarco** [comment]
Thanks¡¡¡ I'll merge as soon as posible, an tell you to try it after deploy :)

**Comment by EvaMarco** [comment]
Hello @icubyx, Could you please check if the problem still happens?, refresh page before testing please

**Comment by icubyx** [comment]
Yep. The top bar doesn't move up and I can still select the text by clicking on it. So both #2871 and #2872 are fixed.

**Comment by superalex** [comment]
Great!, thank you very much!
