### ISSUE TITLE
bug: Layout/"Flex Elements" changes container, not elements → consider naming

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#2873]
### Steps To Reproduce

1. create a simple flex layout, e.g. a container with some contained elements in it
2. with the container selected, there is a section called "flex elements" with the only section "sizing": 
![a small section of a UI called "flex elements"/"sizing" and 4 icons](https://user-images.githubusercontent.com/3416487/215834937-0b181eb6-8d0b-4281-ae9d-4c1ac6e00a6c.png)
3. When I click the icons, they affect not the "flex elements" but their container. 

### Expected behavior

Since flex element\*s\*  seems to refer to the children of the container, I expect that the buttons influence the children rather than the container itself.

### Actual behavior

The container is resized according to its content. Which is nice to have BUT it seems to have a misleading label.

### Additional context

- Just "sizing", **not** in a sub-section of "flex elements" might be sufficient.
- While I know it refers to "flexbox" in CSS, the term of "flex elements" is hard to understand if one is not a CSS dev. I wonder if "contained" or "layouted" elements is better (the latter would also nicely match the functions title, "layout")

**Comment by myfunnyandy** [comment]
The "Flex elements" block is being used to show different settings in different situations and I agree that in this particular case the organization makes no sense and Sizing should be placed at the same level of the rest of the properties. I've created a story to solve it: https://tree.taiga.io/project/penpot/us/4786?no-milestone=1

**Comment by elhombretecla** [comment]
Hi again @jdittrich :)

We have implemented a new approach with the release of version 1.18. The first level of the flex board will now be labeled as "Flex Board," while the nested elements will be labeled as "Flex Element." We believe that this model best aligns with users' expectations.
