### ISSUE TITLE
bug: Typing CMD+Z on MacOS turns the cursor into a Zoom cursor

### ISSUE THREAD

**Issue by tahoeschrader** [uxbox/uxbox#2877]
### Steps To Reproduce

This is happening for both me and someone I'm collaborating with. 

1. Do anything in penpot
2. Type CMD+Z on Mac keyboard

The last thing you did will be undone, but then the cursor turns into a Zoom cursor and you can't go back to the normal cursor mode without closing penpot. 

### Expected behavior

CMD+Z undoes the last action and doesn't turn cursor into a Zoom cursor. 

### Actual behavior

CMD+Z undoes the last action and turns cursor into a Zoom cursor. 

### Screenshots or video

https://user-images.githubusercontent.com/26147461/215936031-b6b5e35c-e68f-4709-bea9-af3d24fe7f15.mov

### Desktop (please complete the following information)

- MacOS M2 13.1 (22C65)
- Google Chrome Version 109.0.5414.119 (Official Build) (arm64)

### Environment (please complete the following information)

https://design.penpot.app

**Comment by myfunnyandy** [comment]
Thanks for reporting it, we will fix it as soon as possible. Here you can track the progress https://tree.taiga.io/project/penpot/issue/4778

**Comment by jaydonteh** [comment]
For a temporary solution, I've found you can revert back to the move (V) cursor mode by pressing the 'Z' key.

**Comment by superalex** [comment]
Thank you very much!, this one should be fixed and deployed to https://design.penpot.app/
