### ISSUE TITLE
bug: prototype interaction position of artboard not respected

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#2879]
### Steps To Reproduce

1. Create a 'main' artboard
2. Create a secondary artboard
3. Add Shadow (to secondary artboard)
![image](https://user-images.githubusercontent.com/11229646/215966640-ce58774d-1f5a-459e-9a2e-01824e2a3cf6.png)
4. Via prototyping, add an 'interaction' for the artboard (added in step 2), with
- trigger: after delay
- action: open overlay
- destination: secondary artboard (added in step 2)
- position: manual

### Expected behavior

Display overlay on manually set location.

### Actual behavior

Overlay is displayed in wrong location.

### Screenshots or video

![Screenshot from 2023-02-01 07-10-30](https://user-images.githubusercontent.com/11229646/215967816-916b1dfa-f7f8-4372-a006-92949550d000.png)

![Screenshot from 2023-02-01 07-07-23](https://user-images.githubusercontent.com/11229646/215967831-9d965345-5445-4693-9888-32c91d5b2c1d.png)

### Desktop (please complete the following information)

- OS: Ubuntu
- Browser: Chromium 109.0.5414.74

### Environment (please complete the following information)

- Host: design.penpot.app

### Additional context

This seems to occur because of the added shadow. Seems similar to #2660.

**Comment by myfunnyandy** [comment]
Hi @keunes, this is happening because the overlay object has a shadow which area is being taken into account to position the overlay. We consider this a bug and it is already added at Taiga: https://tree.taiga.io/project/penpot/issue/4752

I'll crosslink this issue there.
