### ISSUE TITLE
bug: cannot delete or copy elements or ctrl+z  using keyboard

### ISSUE THREAD

**Issue by akibrk** [uxbox/uxbox#2881]
### Steps To Reproduce

Steps to reproduce this behavior

- Copy any element, (text or rectangle)
- Try deleting any element
- Try ctrl+z any action

### Expected behavior

- Should be able to copy 
- Should be able to undo
- Should be able to delete using keyboard

### Actual behavior

- Paste pastes previous element not currently selected element
- Delete via keyboard doesn't work
- Undo doesn't work via keyboard

### Desktop (please complete the following information)

- Windows 11
- Chrome Version 109.0.5414.120 (Official Build) (64-bit)

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by superalex** [comment]
Hello @akibrk 

Thank you very much for reporting your issue but I can't reproduce it...I've recorded a video with what I did:


https://user-images.githubusercontent.com/1579633/216003396-263a9c81-1a30-4654-984d-e215a936cb5c.mp4

**Comment by akibrk** [comment]
[Screen Capture Video](https://www.veed.io/view/0d63b418-33a9-4a43-a469-a21e9ec55ea7?sharingWidget=true&panel=share)

**Comment by superalex** [comment]
Hi @akibrk 

Did you try using an incognito tab on chrome or with another browser like firefox?

**Comment by akibrk** [comment]
That seems to work now, I wasn't logged into other's so didn't try, doing refresh didn't work, after clearing cache it's working. Sorry about that.

Thank you for taking the time.

**Comment by superalex** [comment]
No problem @akibrk and thank you very much for reporting! :)
