### ISSUE TITLE
bug: Typing CMD+Z on MacOS does not undo 

### ISSUE THREAD

**Issue by lane-hogan** [uxbox/uxbox#2887]
### Steps To Reproduce

This is an extension of issue #2877.

1. Do anything in Penpot
2. Type CMD+Z on keyboard

### Expected behavior

The last action will be undone.

### Actual behavior

The last action is not undone and the cursor turns into zoom mode.

### Screenshots or video

https://user-images.githubusercontent.com/53493489/216082789-6759b4d6-3456-41fc-b64e-44d6fd025088.mov

I'm trying to mash CMD+Z to undo but it's not working, although you can see it says I have 'Unsaved Changes' at the top.

### Desktop (please complete the following information)

* MacOS M1 Max 13.1 (22C65)
* Google Chrome Version 109.0.5414.119 (Official Build) (arm64)

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by eih** [comment]
See also #2877, and follow the progress at https://tree.taiga.io/project/penpot/issue/4778

**Comment by lane-hogan** [comment]
I mentioned that issue in my initial report, this is an extension of that because in that issue they were able to undo, I am not.

**Comment by superalex** [comment]
Hello @lane-hogan I think this one should be fixed too and deployed to https://design.penpot.app/ could you please confirm if it's solved?

**Comment by jaydonteh** [comment]
@superalex I too have the issue and I've tested, it's fixed on my end 😊

**Comment by superalex** [comment]
Thank you very much @jaydonteh ! :)

**Comment by lane-hogan** [comment]
@superalex It works fine for me now! Thanks for your help :)

**Comment by superalex** [comment]
Great!, thank you very much @lane-hogan :)

**Comment by KristijanZic** [comment]
I'd like this issue reopened as I can confirm that this issue is still present and makes Penpot unusable.

**Comment by uglyeoin** [comment]
I also confirm this issue on Chrome, PC.

**Comment by thomasfrobieter** [comment]
Still a problem in Brave on PC too, it seems that some actions aren't go to the history at all. So CTRL+Z is working, but the stuff it reverts is something else then expected.

Example: I have a Mask-Group, if I change the height of this group, its doesn't land in the history.

Edit: Not even moving a text block is currently logged in the history :/

Should we re-open this issue or create a new one?

**Comment by weberc2** [comment]
Still a bug on Chrome, MacOS

**Comment by taseret** [comment]
Command Z in Chrome does not work anymore for me on MacOS (15.3.2). Nothing happens. 
On Safari command Z works, the last action gets undone.
