### ISSUE TITLE
Pointer turning into zoom after ctrl+z bug: 

### ISSUE THREAD

**Issue by victoruxui** [uxbox/uxbox#2890]
### Steps To Reproduce

Steps to reproduce:
1. Create an element
2. Create a second element
3. Group them into a flex layout
4. Select the group and hit ctrl+c to copy it
5. hit ctrl+v to paste it within the same container
6. Then hit ctrl+z to undo

### Expected behavior

Undo pasting the element and keep the normal "move (v)" pointer

### Actual behavior

The pointer that it's currently as "move(v)" turns into "zoom" and it's impossible to go back to the "move(v)" pointer type. So refreshing is needed to go back to normal pointer.

### Screenshots or video

https://user-images.githubusercontent.com/74031164/216156319-af70bc22-1e41-4997-8eaf-daf4ea389e22.mov

### Desktop (please complete the following information)

- MacOS Monterey 12.6
- Chrome Versión 109.0.5414.119 (Build oficial) (arm64)

**Comment by eih** [comment]
See also #2877, and follow the progress at https://tree.taiga.io/project/penpot/issue/4778

**Comment by superalex** [comment]
Thank you very much!, this one should be fixed and deployed to https://design.penpot.app/
