### ISSUE TITLE
bug: When using flex layout within flex layouts, trying to manipulate or delete objects causes Penpot to freeze

### ISSUE THREAD

**Issue by garrett** [uxbox/uxbox#2899]
### Steps To Reproduce

I've been working on a mockup today and playing around with the flex layout. It's super useful. Thanks for the feature!

However, on both Firefox and Chrome, when I'm trying to modify or even delete an object with nested flex layouts, Penpot freezes.

### Expected behavior

Penpot shouldn't freeze. I should be able to modify objects.

### Actual behavior

Penpot freezes.

### Screenshots or video

Folders is highlighted in this screenshot. I can select it, but I cannot do anything with it without Penpot freezing.

![image](https://user-images.githubusercontent.com/10246/216389044-6e8a32ef-7d8b-49d1-b6e1-64db79a95670.png)

### Desktop (please complete the following information)

Firefox and Chrome on Fedora Linux 37 on Wayland

### Environment (please complete the following information)

On Penpot.app hosted site.

### Frontend Stack Trace

I don't know how useful this is, but with Firefox dev tools open with sourcemaps on, the debugger pointed me to this line:

```
    (when-let [s (seq coll)]
```

in this block in `core.cljs` (currently line 5213 here):

```
(defn filter
  "Returns a lazy sequence of the items in coll for which
  (pred item) returns logical true. pred must be free of side-effects.
  Returns a transducer when no collection is provided."
  ([pred]
    (fn [rf]
      (fn
        ([] (rf))
        ([result] (rf result))
        ([result input]
           (if (pred input)
             (rf result input)
             result)))))
  ([pred coll]
   (lazy-seq
    (when-let [s (seq coll)]
      (if (chunked-seq? s)
        (let [c (chunk-first s)
              size (count c)
              b (chunk-buffer size)]
          (dotimes [i size]
              (when (pred (-nth c i))
                (chunk-append b (-nth c i))))
          (chunk-cons (chunk b) (filter pred (chunk-rest s))))
        (let [f (first s) r (rest s)]
          (if (pred f)
            (cons f (filter pred r))
            (filter pred r))))))))
```

Topmost function is the `let ... add-space-to-items` line in this code:

```
(defn distribute-space
  [prop prop-min prop-max min-value bound-value items]
  (loop [to-share (- bound-value min-value)
         items    items]
    (if (<= to-share 0)
      items
      (let [[items remainder] (add-space-to-items prop prop-min prop-max to-share items)]
        (assert (<= remainder to-share) (str remainder ">" to-share))
        (if (or (<= remainder 0) (= remainder to-share))
          items
          (recur remainder items))))))
```

### Additional context

I've renamed the file to `Navigator.penpot.zip` so GitHub would allow it to be uploaded. Rename it to `Navigator.penpot` and import.

[Navigator.penpot](https://github.com/penpot/penpot/files/10571310/Navigator.penpot.zip)

(I tried a fresh import already; it didn't work. So you should be able to recreate it by trying to modify the folders group. I duplicated it to change it and that's where I hit this bug. I couldn't even remove the duplicate.)

**Comment by Alotor** [comment]
Thanks for the report. We'll fix it asap. Sorry for the inconvenience.

**Comment by superalex** [comment]
Thank you very much @garrett 

@Alotor fixed the issue and now it's merged and deployed to https://design.penpot.app

**Comment by Ugwokeze** [comment]
Uu

**Comment by garrett** [comment]
Wow! That was fast. :rocket: I can confirm it works for me now too. Thank you!

I love the new flex feature. It's so wonderful! Thanks again for Penpot!
