### ISSUE TITLE
bug: self-hosted OIDC base_uri not injected using ENV var [PENPOT_OIDC_BASE_URI]

### ISSUE THREAD

**Issue by brandonkzw** [uxbox/uxbox#2901]
### Steps To Reproduce

1. Run your own self-hosted penpot
2. Include `enable-logic-with-oidc` in your PENPOT_FLAGS
3. add in PENPOT_OIDC_BASE_URI to your environment variable (For example https://abcd.com/auth/realms/example/)
4. Start penpot backend

### Expected behavior

Penpot backend should run and auto-discover OIDC configurations using the PENPOT_OIDC_BASE_URI appended with '.well-known/openid-configuration' forming 'https://abcd.com/auth/realms/example/.well-known/openid-configuration'

### Actual behavior

Penpot backend will print invalid URI scheme upon starting, showing the uri as only '.well-known/openid-configuration' only

### Desktop (please complete the following information)

Docker

### Environment (please complete the following information)

Image version: penpot/backend:1.17.0-1
Docker Engine Version: 20.10.22
OS Version: Windows 11

**Comment by niwinz** [comment]
This is probably a  bug, I will look on it

**Comment by niwinz** [comment]
https://github.com/penpot/penpot/pull/2908 fixes the issue and will be released soon

**Comment by niwinz** [comment]
New images are released, this should be fixed
