### ISSUE TITLE
bug: invite members text on button not completely visible and button should be a button

### ISSUE THREAD

**Issue by d-koppenhagen** [uxbox/uxbox#2907]
### Steps To Reproduce

Open the dashboard and enter the invite members dialog

### Expected behavior

The displayed message to invite a new member should be visible in all languages completely.

### Actual behavior

The text is not completely shown (e. g. in German language).
Also the corresponding HTML element should be an actual button to increase the degree of accessibility.

### Screenshots or video

<img width="1724" alt="Bildschirm­foto 2023-02-05 um 23 05 12" src="https://user-images.githubusercontent.com/4279702/216848759-08b24844-96ca-489b-b880-67b65f403edd.png">

### Additional context

The corresponding source code is here:

1. [Translation (German language)](https://github.com/penpot/penpot/blob/develop/frontend/translations/de.po#L2006)
2. [Template](https://github.com/penpot/penpot/blob/develop/frontend/src/app/main/ui/onboarding/team_choice.cljs#L199-L201)

**Comment by d-koppenhagen** [comment]
I suggest to add a "a11y" and an "i18n" label to group accessibility issues as well issues related to localized texts displayed.

**Comment by pabloalba** [comment]
Hi!

I've just open a ticket on Taiga, you can monitor the advances in this there: https://tree.taiga.io/project/penpot/issue/4794

I like your suggestion about tags too :)

Thank you!

**Comment by myfunnyandy** [comment]
Also, the green icons lose their aspect ratio with some text amounts. I've added it to the Taiga story.

**Comment by ondrejkonec** [comment]
@d-koppenhagen Hi, can you tell me how I can show this dialog, that is in you image? When I click on the "Invite members", I have different option - with dropdown menu.
![Snímek obrazovky 2023-02-08 v 11 23 05](https://user-images.githubusercontent.com/28909808/217502917-e5cf13f1-aefe-4412-87e8-eaf9c4806b8e.png)

@myfunnyandy do you have any idea?

Thanks!

**Comment by d-koppenhagen** [comment]
Hey, unfortunately I wasn't able to reproduce this situation. I think the dialog will just appear directly after the account creation.

**Comment by myfunnyandy** [comment]
That's it, this dialog is shown only at the onboarding for a new sign-up if create team and add members have been selected along the way. The problem is that we probably checked the window only in english and spanish and it is not prepared to deal with long texts, which is the typical case in german.

**Comment by d-koppenhagen** [comment]
Yes. Let me know if I can support you with some more ugly-looking German weird words like "Eichhörnchenschwanz" 😅

**Comment by myfunnyandy** [comment]
@d-koppenhagen Well, actually you can easily become a translator at Penpot https://community.penpot.app/t/how-to-become-a-penpot-translator/

PS: I don't have anything personal against ugly looking weird words, my problem is only with long ones ;)
