### ISSUE TITLE
bug: Color picker closes if mouse gesture ends out of its bounds

### ISSUE THREAD

**Issue by inexcode** [uxbox/uxbox#2911]
### Steps To Reproduce

Steps to reproduce:
1. Select any component and open color picker to change its color
2. Hold left mouse button on the color palette and move it around
3. If you move your mouse out of the popup and release the left mouse button, popup closes

### Expected behavior

Color picker shouldn't close

### Actual behavior

Color picker closes

### Screenshots or video

https://user-images.githubusercontent.com/13254627/217010571-9b4f07e5-509e-4685-9f46-2aacfe6f6959.mp4

### Desktop (please complete the following information)

- OS: NixOS 22.11
- Browser & version: Firefox 109.0

### Environment (please complete the following information)

- Host: Self-hosted
- OS Version (e.g. Ubuntu 16.04): Ubuntu 22.04.1
- Docker / Docker-compose version: docker-compose version 1.29.2, docker version 20.10.23
- Image version (e.g. Alpine): latest (1.17)

**Comment by hirunatan** [comment]
Thanks for reporting. I've reproduced the bug (occurs in Firefox but not Chrome).

Created an issue in Taiga to process here: https://tree.taiga.io/project/penpot/issue/4820
