### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by rajf** [uxbox/uxbox#2915]
I've encountered a strange issue where some machines can access the frontend of a Penpot Docker install on our private network but others fail to render due to a script error.

Initial HTML and assets are returned to the browser and no network errors detected. 

Dev tools stack trace:

`
shared.7ab91f68a.js:4572 Uncaught SyntaxError: Unexpected token '?'
main.7ab91f68a.js:1352 Uncaught SyntaxError: Unexpected token '?'
`

Error line from shared.js

`
function ykb(a){return VI(function(b){return jF(kF(0,Qd(Math.pow(b,1.1))),function(c){return xkb(function(d){d=wkb(c,d);var e=Fjb(b,a);return ob(function(g,k){return jF(kF(0,10),function(p){return 0===p?e:Fjb(k,ukb.g?ukb.g(g):ukb(g))})},e,d)})})})}var zkb=ykb(skb),Cab=ykb(Xab);xG=!0;var Akb=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;function YI(a){return Mh(a)?a:"string"===typeof a?m(ch(Akb,a))?fi(a):wl:wl}function ZI(a){return""+(a??"")}$F(zu,G(Lk,G(CA,ww,sB),G(Uh,Pc,G(PA,G(gy,new N(null,1,5,O,[yya],null),G(yqa)),Aoa))),UF(eG(G(CA,ww,sB),YI,null,!0,ZI),function(){return gF(function(){return Pfb()},zkb)}));
`

Error line from Main.js

`
function iQb(a,b,c){var d=IJ.createElement("a");b=Klb(b);a=m(m(b)?!ED(a,b):b)?""+(a??"")+(b??""):a;rJ(d,"href",c);rJ(d,"download",a);rJ(d.style,"display","none");document.body.appendChild(d);d.click();return d.remove()}function jQb(a){return DD(a,"#")?a.substring(1):a}
`

Steps to reproduce:

1) Browser to PenPot front end on port 9001

Browsers:

- Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Firefox 71.0 (64-bit)

Client OS:
- WIndows 10 Pro (64-bit)
- Firewall disabled

**Comment by niwinz** [comment]
This is because you are using a pretty old version of the browsers, that does not support some features that penpot requires.
You will need probably at least chrome 88 or firefox 85, at least for make this exception disappear.
