### ISSUE TITLE
bug: Still zoom to cursor when using keyboard for zooming

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#2924]
### Steps To Reproduce

1. Create some objects or paste an image to see the effects of zooming
2. Use the keys + and - to zoom in an out

### Expected behavior

The zoom should center on the current cursor position. This would be the same behavior that I get when I use Ctrl+Mousewheel

### Actual behavior

The zooms center seems to be determined by the general coordinate system of the file

### Screenshots or video

Cursor+Mousewheel: 
![zoom in cursor](https://user-images.githubusercontent.com/3416487/217532182-9b023312-b73b-4d5e-a52a-90029b4886d2.gif)

\+ on keyboard:
![zoom in keyboard](https://user-images.githubusercontent.com/3416487/217532215-aa087c30-783d-4747-9e7b-0caf64bb28b4.gif)

### Additional context

If there is no cursor on the canvas, it could still fall back to the global 0,0 point (or whatever cursor-less reference there is)

**Comment by hirunatan** [comment]
Yes, it seems that there is a bug about it. I've created a Taiga issue to track it there https://tree.taiga.io/project/penpot/issue/4825
