### ISSUE TITLE
bug: Export looks very different than the design itself

### ISSUE THREAD

**Issue by anujdeshpande** [uxbox/uxbox#2926]
### Steps To Reproduce

1. Add any image
2. Add text next to that image in Bungee Shade font
3. Increase the font of the text to 1000
4. Export to PNG

### Expected behavior

The text should be aligned with the image of the dog 

### Actual behavior

The text goes out of frame

### Screenshots or video

<img width="197" alt="image" src="https://user-images.githubusercontent.com/969376/217766828-96489649-8ebd-46c9-88c6-bedb88380b7a.png">
<img width="524" alt="image" src="https://user-images.githubusercontent.com/969376/217766903-1f4fd332-ed30-4648-8f94-cedb709849c6.png">
<img width="201" alt="image" src="https://user-images.githubusercontent.com/969376/217767106-d2b7c19d-94ce-441f-8425-86c94868cc2c.png">
![11](https://user-images.githubusercontent.com/969376/217767775-33cc8633-8df6-4f00-9cde-dadb1ebca1ec.png)

### Desktop (please complete the following information)

- Win11
- Brave Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-bit)

**Comment by anujdeshpande** [comment]
![11](https://user-images.githubusercontent.com/969376/217768656-7164e7df-29f3-4d95-85a2-089599c44911.png)

**Comment by hirunatan** [comment]
Sorry, I can't reproduce the bug. Could you please send me the url of a file with this happening? You can also send it to support@penpot.app. Or send an exported .penpot file. Thanks.

**Comment by anujdeshpande** [comment]
@hirunatan sent mail

**Comment by hirunatan** [comment]
Thanks, we'll take a look at it.

**Comment by superalex** [comment]
heelo @anujdeshpande 

I think I discovered the problem. I've been checking this font (it's a google font) using https://vertical-metrics.netlify.app/2086 and it has different ascender and descender values for linux and windows:

![1](https://user-images.githubusercontent.com/1579633/218487612-75ef17a4-cbc2-43ef-b374-423eaf4ab07f.png)

As the exporter is using a chrome browser under a linux OS the text is rendered out of the board. This same situation should appear directly in your workspace if you access using different browsers and operative systems.

A possible workaround could be uploading a custom font fixed to penpot and use that one.

The font can be downloaded here: https://fonts.google.com/specimen/Bungee+Shade

And a fixed version can be genereted with https://transfonter.org/

![image](https://user-images.githubusercontent.com/1579633/218488293-3c9c5de7-d25e-4d9d-9b5b-9d860944b7e5.png)

Regards,
