### ISSUE TITLE
bug: Misaligned Points

### ISSUE THREAD

**Issue by Chrissi2812** [uxbox/uxbox#2930]
### Steps To Reproduce

1. Create a new Path
2. Zoom to the Pixelgrid
3. Switch to Edit / Move Point tool (V)
4. Drag The point by clicking next to it and move

### Expected behavior

The Point should snap to the pixelgrid.

### Actual behavior

The Point is no longer aligned to the pixel-grid. It' offset by the distance the cursor had when the drag started.

### Screenshots or video

https://user-images.githubusercontent.com/6141652/217873102-77b2f06d-e01a-4b68-82cd-0a630d1033c6.mp4

Here it's maybe more visible that the point is misaligned with the pixel grid
![image](https://user-images.githubusercontent.com/6141652/217873406-ae69caf1-23ad-4737-8067-84d1e7c1602a.png)

### Desktop (please complete the following information)

- Windows 11 (22H2 Build: 22621.1105)
- Chrome 110.0.5481.78

### Environment (please complete the following information)

- Host: https://design.penpot.app/

**Comment by hirunatan** [comment]
Thanks for the reporting. I have added it to Taiga, for our tracking https://tree.taiga.io/project/penpot/issue/4828
