### ISSUE TITLE
bug: imported font display problem on different user

### ISSUE THREAD

**Issue by pikmin-rgb** [uxbox/uxbox#2931]
### Steps To Reproduce

Steps to reproduce the behaviour:
1. Use an imported font
2. Create some text
3. The selected font may appear with different display depending on the user

### Expected behavior

![Screenshot_11](https://user-images.githubusercontent.com/29428817/217890579-a0b9062f-15a1-4b3d-b5ed-7bea9e8b7e80.png)

Expected behavior is the right font on display for every user.

### Actual behavior

![image12](https://user-images.githubusercontent.com/29428817/217890745-de992e32-503d-4dec-9aac-32b0103c2c9e.png)

Some users have the wrong font display after putting the good font.

(both screenshot are from the same file shared between user, but we actually see different display of the font)

### Desktop (please complete the following information)

- Windows 10
- Google chrome Version 109.0.5414.120 (Build officiel) (64 bits)

### Environment (please complete the following information)

- Debian
- Docker compose 3.5

**Comment by hirunatan** [comment]
Are the users that don't see the custom font using a different browser or operating system? Or is there any other difference that could be significative?

Could you send us the font file, for us to check if it has any problem?

**Comment by pikmin-rgb** [comment]
I encounter the problem with 2 differents user. One is on MacOS and the other one use the exact same configuration as me (he tested with different browser as well and the problem stills there).

Here is the font file :
[font.zip](https://github.com/penpot/penpot/files/10724569/font.zip)

Thank you for your help !

**Comment by superalex** [comment]
Hi @Unacoli !

Did you upload those fonts recently?, with the last release penpot shows a message informing about the potential issue:

![1](https://user-images.githubusercontent.com/1579633/218532428-929e10af-d0e9-47f5-a48a-372ebbee0f98.png)

Using https://vertical-metrics.netlify.app/ you can check this:

![1](https://user-images.githubusercontent.com/1579633/218532565-66382993-bbb0-4aec-8c1a-17ebdc41fd7b.png)

You could try using https://transfonter.org/ to fix the issues with the font and upload this modified version of the font (and apply it to the conflicting texts)

![image](https://user-images.githubusercontent.com/1579633/218532792-a63aeaad-9f35-471a-a115-d1cf84a158da.png)

**Comment by pikmin-rgb** [comment]
Hi !

I try to fix the font using your advice, but I can't manage to have them in the same family font with different style. It keep uploading as individual font. Do you think you can help me fix this ?

Thank you very much for your time !

Edit : I did manage to reformat the font with transfonter, but the font still not looking the way its expected (and I still can't manage to have it at one family instead of individual font)

**Comment by superalex** [comment]
Hello @Unacoli 

Sorry but the fonts you included in your zip file don't include that info (each file has its own different family) so penpot upload them as individual fonts:

![1](https://user-images.githubusercontent.com/1579633/218650097-d138ddf1-d384-43b6-b4cf-79d028f24c25.png)

I suppose you could look for a font editor and fix it.

When you say "the font still not looking the way its expected", could you please attach here one of the fixed font files?

**Comment by pikmin-rgb** [comment]
The font is still looking like this :
![image](https://user-images.githubusercontent.com/29428817/219118131-5867df95-2426-4552-a93d-be5fd3cfcb8b.png)

I attach here the fixed font : 
[transfonter.org-20230213-203016.zip](https://github.com/penpot/penpot/files/10746161/transfonter.org-20230213-203016.zip)

**Comment by superalex** [comment]
Thank you very much @Unacoli 

Could you please do one more test?, in the failing browser, open the network tab when trying to edit a file using that font and filter them by font (I'm trying to check if the browser isn't able to get the font):

![1](https://user-images.githubusercontent.com/1579633/219120147-85f07bf6-6f6e-4857-bd66-0a85e19ef68f.png)

**Comment by pikmin-rgb** [comment]
![image](https://user-images.githubusercontent.com/29428817/219124306-919579df-dcb0-49a9-a4e3-a5727ac8853d.png)

It seems that the browser isn't able to get the font indeed (I switched on one other font and between all the imported ones)

**Comment by superalex** [comment]
That's very strange...

Those users with the wrong font display, what browsers/operative systems are they using? and the ones who see it right?. In the problematic users, using another browser make it work?

**Comment by pikmin-rgb** [comment]
Actually it starts doing this to me too, I ask other user and with some refresh time, everybody have this problem with the font.
Changing the browser don't resolve the problem.

**Comment by superalex** [comment]
Are all of you under the same network?

**Comment by superalex** [comment]
@Unacoli  I've been trying to reproduce the issue and I think I detected if that user click on the home button:

![1](https://user-images.githubusercontent.com/1579633/219402750-7c7d134f-3112-4f5d-9f15-c2ad8e567cc4.png)

and navigate to the file clicking through the folders, the text is shown ok?

**Comment by pikmin-rgb** [comment]
We might have a problem somewhere else with our config... 

I'll try look at this tonight and come back here if I find any news about this, thanks again !

**Comment by pikmin-rgb** [comment]
Update : It works now !

I changed all the font in https://www.glyphrstudio.com/online/ with the good name and good style for each one after applying the first fix you provided and export it with otf format.

![image](https://user-images.githubusercontent.com/29428817/220210483-44bb0535-077f-4846-a215-16a932f46264.png)

![image](https://user-images.githubusercontent.com/29428817/220210502-3932d2a4-80df-4e03-8ffd-8919bc2b291b.png)

In case someone need the font one day, here it is : 
[TTDaysSans.zip](https://github.com/penpot/penpot/files/10788265/TTDaysSans.zip)

Thank you again for your help :)

**Comment by superalex** [comment]
Great!, thank you very much @Unacoli :)
