### ISSUE TITLE
feature: Allow absolute positioning in layout ("flex") containers

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#2933]
### Is your feature request related to a problem? Please describe.

**Story:** I want to absolutely position elements within a board that holds a flex layout.

Currently, this is not possible (children to a layout container are always layouted), so one needs to create a board to hold the positioned element and then a board within it to hold the flex layout. 

### Describe the solution you'd like.

* [Figma has a toggle for elements to position them](https://uxdesign.cc/absolute-positioning-in-figma-cc5cb0a299c6)  freely in a layouted container. The positioned element is "in" the layout container; it is not in the autolayout flow and it can have constraints set, like any other unlayouted element. 
* figma positions the toggle at the size and position panel, though it might also be at the flex element panel.
* Such absolute-in-flex-container behavior [is even consistent with CSS](https://chenhuijing.com/blog/flexbox-and-absolute-positioning/) 

(created based on infos someone [shared on the penpot discourse](https://community.penpot.app/t/flex-layout-absolute-position-inside-flex-container/2511/3?u=jdittrich))

### Describe alternatives you've considered.

It is a nice-to-have improvement that makes the process smoother; continuing to nest containers is not terribly bad either.

**Comment by EvaMarco** [comment]
Hello @jdittrich:

We have this idea flying around for some time now. I've created a US in our backlog to design this and implementing it as soon as we can. https://tree.taiga.io/project/penpot/us/4834
Thanks for your help

**Comment by diacritica** [comment]
This feature request was released as part of our 1.18 https://github.com/penpot/penpot/releases/tag/1.18.0
Now closing! Thanks @jdittrich ! this was one of the highlights of this release!
