### ISSUE TITLE
bug: Empty images / 404 media error

### ISSUE THREAD

**Issue by nickian** [uxbox/uxbox#2937]
### Steps To Reproduce

Upload an image onto an artboard.

### Expected behavior

Expect to see the image show up on the artboard.

### Actual behavior

Images show up empty. 404 Error in the console:

```
GET https://mydomain.com/assets/by-file-media-id/22457d5f-6d54-80d8-8002-0d7801bb42b0 404 http.cljs:92
```

### Screenshots or video

<img width="1998" alt="Screenshot 2023-02-12 at 8 28 35 PM" src="https://user-images.githubusercontent.com/590678/218363878-45642552-612a-4a53-8bbe-83488f4720aa.png">

### Desktop (please complete the following information)

- Mac OS
- Brave 1.47.186 / Chromium 109.0.5414.119

### Environment (please complete the following information)

- Self-hosted, docker-compose.
- Ubuntu 20.04
- Penpot 1.17

**Comment by EvaMarco** [comment]
Hello @nickian :

Can you please share with us your docker configuration? 
Thanks¡¡

**Comment by niwinz** [comment]
We have had some related issues on release and all of them should be already fixed. Please, ensure pull the latest images and use the latest [docker-compose.yaml ](https://github.com/penpot/penpot/blob/main/docker/images/docker-compose.yaml)file

**Comment by nickian** [comment]
Sorry, I think it was related to this issue. https://github.com/penpot/penpot/issues/2918

Seems to be working fine now. Maybe there was some weird caching going on at first.
