### ISSUE TITLE
bug: Updating main component Parent marks Children as having no overrides

### ISSUE THREAD

**Issue by hashkool** [uxbox/uxbox#2949]
### Steps To Reproduce

Main issue 

When a parent component B has some child instance A with overrides to A, updating main component B makes Penpot think it's child components have no overrides.

Steps to reproduce:

Penpot file: [child-component-overrides.penpot.tar.gz](https://github.com/penpot/penpot/files/10756289/child-component-overrides.penpot.tar.gz)
---

![Step1](https://user-images.githubusercontent.com/5623050/219366184-02c86338-f117-4065-b14a-049a50b93402.png)

---

![Step2](https://user-images.githubusercontent.com/5623050/219366190-07b36e42-9ec9-41dd-abc5-ee7c54a1dce2.png)

---

![Step3](https://user-images.githubusercontent.com/5623050/219377921-00bdf69e-befa-4392-b7f7-64b160385f50.png)

---

![Step4](https://user-images.githubusercontent.com/5623050/219366195-3b4f4959-ddd6-44bf-9d56-5c595246d962.png)

---

![Step5](https://user-images.githubusercontent.com/5623050/219366198-048fbedf-8ff0-40f3-84de-d6a42d0c9b45.png)

---

![Step6](https://user-images.githubusercontent.com/5623050/219382365-c019e4ec-c621-4a6f-aca6-e0fa7d7fbc61.png)

### Expected behavior

When a component B wraps component A (meaning: A is a child of B), then overrides to A in B should be kept as __B holds a B-specific flavour of A__.

When updating main component B, any overides to its child components should be remembered (and indicated in the layer panel).

Updating main component A from a different context (meaning : A is not the same child of B) should not remove the overrides B has made to it's child A.

### Actual behavior

- Update main component B:

  - marks B as having no overrides _to itself_. Correct. :heavy_check_mark:
  - marks _any child components A_ as having no overrides anymore in the layer panel. Wrong. :no_entry:

- Update main component A from a different context (meaning : A is not the same child of B):
  - overrides B has made to it's child A are removed. Wrong. :no_entry:

### Desktop (please complete the following information)

Firefox 109.0.1

### Additional context

The current behaviour makes components highly unpredictable.

When Penpot thinks A inside B has no overrides,  one can toggle the visibility of child A in B two times to trick Penpot into thinking A inside B does have overrides. This is of course a very cumbersome workaround.
Detaching instance B inside A defeats the whole purpose of components, and is not a workaround.

**Comment by EvaMarco** [comment]
Hello @hashkool :

I've created an issue in our Taiga project with all the information you have provided, you can check it [here](https://tree.taiga.io/project/penpot/issue/4873).

We are working on a complete rework of components in this moment, I hope this issue can be fixed at the same time.

Thanks

**Comment by madalenapmelo-kp** [comment]
I'm closing this issue since the behavior of the components has changed as of the release of Penpot 2.0!
