### ISSUE TITLE
feature: disable or host locally Google fonts

### ISSUE THREAD

**Issue by rajf** [uxbox/uxbox#2950]
### Is your feature request related to a problem? Please describe.

Reliance on external references to Google fonts could fall foul of GDPR compliance. Additionally if hosting on an internet air gapped system having Google fonts served locally would improve the usability of the application.

### Describe the solution you'd like.

Reference a local version of Google fonts or optionally provide a toggle to disable the use of Google fonts globally.

### Describe alternatives you've considered.

Using a docker container with nginx to proxy external requests to a local source.

**Comment by Alotor** [comment]
Thanks for the suggestion @rajf we definetely going to address this when we're able.

I've added it to our internal list of enhancements.
https://tree.taiga.io/project/penpot/issue/4901

**Comment by myfunnyandy** [comment]
Closing as this has been implemented at the 1.19 release.
