### ISSUE TITLE
feature: Changing nested components

### ISSUE THREAD

**Issue by Redigen** [uxbox/uxbox#2953]
### Is your feature request related to a problem? Please describe.

I can't make one component of a button with an icon and change the icon depending on the need. 
Instead, I have to make several buttons with different icons.

### Describe the solution you'd like.

Figma and Sketch allow you to replace a nested component with any component from the library.

**Comment by Alotor** [comment]
Hello @Redigen 

We're planning to support a similar feature as "variants". Would that kind of feature be enough for your use case? or do you think this enhancement in a different way?

**Comment by Redigen** [comment]
Hello @Alotor 

Using variants involves creating copies of components with different components inside? Or will I be able to replace the nested component from the properties panel?

I want to easily replace a component within a component with any other. For example, in a text box, I might have a search or filter icon. Or in an infobar, I might have a button or link component. There can be complex components from many nested components, for example, a sidebar with components from different lists, where I want to replace one component with a list with another

**Comment by hirunatan** [comment]
We also are advancing in a US to replace one asset with another: https://tree.taiga.io/project/penpot/us/1331

Perhaps this is what you want. If you follow this story you will see its road until implemented.

**Comment by Manueljlin** [comment]
added in v2, thanks penpot folks <3
