### ISSUE TITLE
Can't write custom text in onboarding flow (eg I am using Penpot to teach, can't select this, says it's invalid)

### ISSUE THREAD

**Issue by jaanaltosaar** [uxbox/uxbox#2954]
![image](https://user-images.githubusercontent.com/5317244/219875156-ff3cfe0f-a1ad-4052-942b-cd8029376c6a.png)

**Comment by Alotor** [comment]
Hello @altosaar 

The form you're showing is an option selection so you have to choose from the list of options. Sorry for the inconvenience.
