### ISSUE TITLE
enhancement: Content for "Padding - multiple" is confusing

### ISSUE THREAD

**Issue by iprithvitharun** [uxbox/uxbox#2964]
### Steps To Reproduce

1. Hover over the **Padding - multiple** icon.
2. Tooltip will appear.

### Expected behavior

The content should be consistent with the "Individual corners" tooltip. Like, 

* Individual padding

### Actual behavior

It's hard to read and inconsistent with other tooltip formats.  

### Screenshots or video

<img width="224" alt="Screenshot 2023-02-20 at 10 16 16 PM" src="https://user-images.githubusercontent.com/58725708/220166773-400a94f3-3cc0-4c8c-bac7-311ce1f72423.png">

**Comment by myfunnyandy** [comment]
Hi @iprithvitharun,

We had a little talk at the design team about this topic and we agree we agree with most of your proposal and disagree with something that is actually a cause of the current design.

Agree:
- "Padding - multiple" is confusing, not descriptive.
- The tooltip for this toggle should be consistent with the one for the corners.

Disagree:
We are not sure that "Individual padding/corner" is the best way to describe the action. The word "Individual" migh suggest that it's only for one value or one of the 4 options. We we rather like the option **"Independent paddings/corners"** to avoid potential ambiguity.

This might be an oportunity to improve not only one but both tooltips. What do you think?

**Comment by iprithvitharun** [comment]
@myfunnyandy Agreed 💯 Will update the PR. 

I'd also prefer "Independent" over "Individual".

**Comment by iprithvitharun** [comment]
@myfunnyandy Updated. Please review.

**Comment by myfunnyandy** [comment]
Perfect, we'll merge it later.

Thanks!
