### ISSUE TITLE
feature: SVG id when exporting files

### ISSUE THREAD

**Issue by zoix** [uxbox/uxbox#2965]
### Is your feature request related to a problem? Please describe.

We are looking for a friendly way to export an SVG file that contains an ID per object/group. Currently, the IDs are random UUIDs that don't match the object name.

### Describe the solution you'd like.

Assign the object or group name as the ID of the exported SVG file.  

### Describe alternatives you've considered.

- Editing the SVG file. Problem: not friendly with non-technical users.

### Additional context

From Figma:

<img width="494" alt="CleanShot 2023-02-20 at 12 17 03@2x" src="https://user-images.githubusercontent.com/44326641/220168172-34f9eee4-2ecc-4e55-b368-01be9616718c.png">

**Comment by Alotor** [comment]
Thank you for the suggestion. 

I think we really need to improve the use case to export SVG files because we've received several complains. I'll include your feedback so when we revisit it we try to add something along those lines.

**Comment by myfunnyandy** [comment]
I've crosslinked this issue with [the taiga story](https://tree.taiga.io/project/penpot/us/4134?backlog-q=svg&no-milestone=1) where we are gathering the info and requests.
