### ISSUE TITLE
bug: invalid invitation

### ISSUE THREAD

**Issue by cristiano-j-pereira** [uxbox/uxbox#2972]
### Steps To Reproduce

1- Send an invitation for someone from any project

### Expected behavior

Valid invitation

### Actual behavior

invalid invitation
This invitation may have been canceled or may have expired

**Comment by Alotor** [comment]
I've tried to invite some people to a team to make sure, and seems to be working. An invitation can became invalid if the invited user navigates to the URL or given some time.

You can check the state of the invitations in the team admin panel. There are more info here: https://help.penpot.app/user-guide/teams/#teams-invites

**Comment by fqd0711** [comment]
How to solve this problem, I also encountered the same problem recently, click the invitation link verify-token returns 400
