### ISSUE TITLE
bug: Search field has implemented shared styles for "close icon" and "search icon" 

### ISSUE THREAD

**Issue by ondrejkonec** [uxbox/uxbox#2975]
### Steps To Reproduce

Go to the App Dashboard, and hover over search icon in Search field - icon is red.

### Expected behavior

Search icon should not have red color.

### Actual behavior

Search icon has red color instead of primary/gray.

### Screenshots or video

<img width="304" alt="Screenshot 2023-02-23 at 15 08 24" src="https://user-images.githubusercontent.com/28909808/220932235-9038880b-3c60-46ce-8e47-af270047c67e.png">

### Additional context

I can try to fix this visual bug. Can you help me with finding another search field, where this red hover effect make sense? I think it can be something with "x" icon, when you want to delete the specified expression. But I couldn't find it.

**Comment by Alotor** [comment]
Thanks for the report @ondrejkonec,

I've added it to our internal Taiga https://github.com/penpot/penpot/issues/2975
