### ISSUE TITLE
bug: Invisible text on Assets preview

### ISSUE THREAD

**Issue by SatarisGIT** [uxbox/uxbox#2986]
### Steps To Reproduce

To reproduce:

1. Create simple project named for example: "Name"
2. Import, for example Material Design Kit
3. Go to "Name" and all library "Material Design Kit"
4. Look on Assets preview - there is no any text on components

### Expected behavior

I can see component preview like it is in real library

### Actual behavior

I cant see text on component preview

### Screenshots or video

![image](https://user-images.githubusercontent.com/28608081/221606457-db18c0dc-688d-48e2-a952-34bbe9699644.png)

### Desktop (please complete the following information)

- Win 11
- Chrome 110.0.5481.177

### Environment (please complete the following information)

- Host: design.penpot.app

**Comment by pabloalba** [comment]
Thanks for the report @SatarisGIT 

I've added it to our internal Taiga https://tree.taiga.io/project/penpot/issue/4962
