### ISSUE TITLE
text in gui input fields remains selected on second click

### ISSUE THREAD

**Issue by ponderboy** [uxbox/uxbox#2991]
### Steps To Reproduce

Select a shape. Click in the gui input for position. (selects text). Click again (behind the text)

### Expected behavior

Click inside and the text inside gets selected. Click again and have the cursor at the clicked position. For example at the end to add "+50" to a width (BTW. so cool you guys integrated math already).

### Actual behavior
Click inside and the text inside gets selected. Click again and the text stays selected. I need to use "pos1", "end" or arrow keys on the keyboard to achiev that.

### Screenshot

![screenshot-design penpot app-2023 02 28-18_39_20](https://user-images.githubusercontent.com/5340556/221936928-faa1f01a-0992-4c33-9eda-933e098d61a5.png)

### Environment

Firefox Developer Edition 111.0b6 (64-Bit) on Windows 10

design.penpot.app

**Comment by pabloalba** [comment]
Thanks for the report @ponderboy,

I've added it to our internal Taiga: https://tree.taiga.io/project/penpot/issue/4963
