### ISSUE TITLE
bug: when I try to paste an SVG with blank components, an internal server error occurs.

### ISSUE THREAD

**Issue by hsiong** [uxbox/uxbox#2995]
### Steps To Reproduce

1. Go to [penpot app](https://design.penpot.app/)
2. Create a new penpot project
3. Paste or import a svg with blank components: [svg example - blank component](https://user-images.githubusercontent.com/37357447/222389531-e1bedf67-fa91-4e53-b34f-d1a16f9c0764.svg)
4. Internal Server Error: 
<img width="1631" alt="Screen Shot 2023-03-02 at 17 27 42" src="https://user-images.githubusercontent.com/37357447/222389981-caef05f4-746b-44f5-9e6d-6b22f4d6245d.png">

### Expected behavior

It would work fine when I paste an SVG with blank components in Penpot app. I have tried the same in Adobe XD, Axure, and Figma, and they all work fine.

### Actual behavior

When I try to paste an SVG with blank components, an internal server error occurs.

### Desktop (please complete the following information)

- OS:  MacOS montery 12.5.1
- Chip: Apple M1 Pro
- Browser version:  Google Chrome 110.0.5481.177 (arm64)

**Comment by pabloalba** [comment]
Hi @hsiong !

Thank you. I've just added it to our bug tracker: https://tree.taiga.io/project/penpot/issue/4964

Best

**Comment by hsiong** [comment]
Thanks a lot,  best wishes 😄
