### ISSUE TITLE
feature/bug: Scrolling behavior is hard to configure

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#2998]
### Is your feature request related to a problem? Please describe.

**Use case:** I want to create an interface in which there is a fixed side menu and a scrolling main area

**Problem:** _It is really cumbersome to simulate scrolling_ ; the only way is to make the frame larger than the view area in preview mode and then pin static elements which need to be adusted to the preview-mode’s width and height (thus I do not know how well that translates to other people’s screen) 

### Describe the solution you'd like.

_Figma’s solution is pretty good_ imho (even though it takes a bit to discover): In prototype-edit mode, selected frames can be set to different scroll modes. (I also think these settings could be at the frame settings, where you can also set "clip", but it makes sense at prototype, actually). 
Ideally, there would be a way to show the operating systems scroll indicators if wanted.

### Describe alternatives you've considered.

Leave it as-is (makes sense if prototyping is not a major concern and the focus is more on static mockups)

### Additional context

* See this forum post: https://community.penpot.app/t/how-can-i-do-a-fixed-position-aside-menu/2684/2
* See the documentation on prototyping: https://help.penpot.app/user-guide/prototyping/ ("We are aware that this capability is still difficult to use whithout being able to restrict the screen size at the View Mode, something that we are already working on.")
* related on interactive prototypes: [Simple text input in prototypes #1098](https://github.com/penpot/penpot/issues/1098) and [native input elements](https://community.penpot.app/t/penpot-and-native-input-elements/2289)

**Comment by pabloalba** [comment]
Hi @jdittrich !

Yes, this is in our roadmap. We have an [user story about this](https://tree.taiga.io/project/penpot/us/4519) pretty high in our backlog, so I hope we will implement it soon. Stay tuned!

**Comment by bloemer** [comment]
Seems that the design work is done, but no dev assigned to this topic.
[PenPot Taiga](https://tree.taiga.io/project/penpot/us/4519)

Now that this ticket is closed, where is the solution?
