### ISSUE TITLE
bug: Relative overlay position is wrong

### ISSUE THREAD

**Issue by ghost** [uxbox/uxbox#3003]
### Steps To Reproduce

Add a nested item (view image 1).
Add to the item:
Add Prototype > On Click
Action Toggle overlay
Destionation: a board
Realtive To Button (self)
Position: manual

### Expected behavior

It should be relative to the item itself and not relative to a parent component.

### Actual behavior

It seems that the position is relative to a parent item.

### Screenshots or video

![1](https://user-images.githubusercontent.com/31160860/222817280-88edffe6-6775-4c87-8696-e979e39d0ad6.png)
![2](https://user-images.githubusercontent.com/31160860/222818432-515471d2-4721-4699-8ffe-59f329afdcc3.png)

### Smartphone (please complete the following information)

- Linux MInt
- Version 110.0.5481.177

### Environment (please complete the following information)

- Linux Mint 21.1
- Docker 23.0.1
- Image 1.17.2

**Comment by EsterLatorre** [comment]
Hello Farnsi,

I have tried your issue and it's working fine for me... could you please send me the file so we can see the issue in more detail please? at support@penpot.app

Thanks a lot!

**Comment by elhombretecla** [comment]
Hi again @Farnsi ,

We have created this issue in Taiga and will review it asap.

Thanks again!

[https://tree.taiga.io/project/penpot/issue/5092](https://tree.taiga.io/project/penpot/issue/5092)
