### ISSUE TITLE
bug: No preview image of jpeg file extension in Assets > Graphics

### ISSUE THREAD

**Issue by ghost** [uxbox/uxbox#3007]
### Steps To Reproduce

Add a ".jpeg" file under Assets > Graphis > +

### Expected behavior

Preview image

### Actual behavior

It shows a broken image symbol.

### Screenshots or video

![broken](https://user-images.githubusercontent.com/31160860/222962879-96eed829-ba88-4a1b-9434-662a5ad922ee.png)

**Comment by EsterLatorre** [comment]
Hi Farnsi,
Does it happen to you with all of the jpgs you try to upload? Maybe the file is corrupt?
Also please let us know your OS, browser, environment etc
Thanks!

**Comment by ghost** [comment]
Only with the file ending jpeg, the same file renamed to jpg works. (the file is not corrupted)
And only the preview image in assets-tab. if you D&D the image into the content, the image is visible.

**Comment by niwinz** [comment]
is this a selfhosted instance or our saas?

Please, try to provide a bit more context on your issue, we can't help with no information.

**Comment by ghost** [comment]
The self hosted docker files.
Tried it online in your saas and it is ok.

**Comment by niwinz** [comment]
Then this is probable related to permissions and/or configuration issue.

**Comment by ghost** [comment]
Try it today with another file and it is ok. Did not have the jpeg from 2 weeks ago to verify.
