### ISSUE TITLE
bug: disable-login-with-password flag doesn't disable login with password

### ISSUE THREAD

**Issue by alexeyyakimovich** [uxbox/uxbox#3013]
### Steps To Reproduce

Provide disable-login-with-password to PENPOT_FLAGS
Start containers
Go to login page
See login/password inputs

### Expected behavior

login/password inputs not shown

### Actual behavior

They are presented

**Comment by niwinz** [comment]
Hello, sorry for late reply

What version of penpot you are using, the flag `desable-login-with-password` is introduced on the 1.17,
if you are using a previous one, probably you will need to use `disable-login`

**Comment by icsy7867** [comment]
So I ran into this as well and was getting frustrated.  However, it ended up being that Chrome was caching the old javascript for me.  So even though I would reload the page,  it would still show the normal login button.

However after popping into an incognito tab, it looked as expected and only showed an "LDAP" button.

I did a hard cache reset on my deployment and everything was happy.
