### ISSUE TITLE
bug: Penpot services only work when accessed from localhost

### ISSUE THREAD

**Issue by RobertBrown3** [uxbox/uxbox#3016]
### Steps To Reproduce

1. Install Penpot on server using docker-compose. Use docker-compose.yaml provided on Penpot's GIT page. No changes made to the file except changing email information (SMTP. From address, etc)
2. Create an account *on localhost* (creating one on any other machine fails).
3. Log in on localhost, to make sure the account works.
4. After handling all the new account stuff, log back out.
5. Go to any other machine and bring up the login screen.
6. Enter the correct login credentials

### Expected behavior

You should be logged in.

### Actual behavior

You get a rather cryptic message: "Something wrong has happened".
It should be noted that all account -related functionality fails if you are attempting to access Penpot from a machine other than the one it is running on. As stated previously, you can only create an account from localhost. If you attempt to do so from any other machine. you can enter the new username and password, and you can enter the user's full name as the next step, but when you click on the "Create Account" button after entering the full name, nothing happens.

### Screenshots or video

![loginproblem](https://user-images.githubusercontent.com/13591779/223286813-a8d5675a-8a68-4536-954f-9ff58aa4b4d1.PNG)
[logs.txt](https://github.com/penpot/penpot/files/10904093/logs.txt)

### Desktop (please complete the following information)

- Multiple desktops on different operating systems: Windows 10, MacOS, Linux (Almalinux).
- Browsers: Google Chrome and Firefox
- Penpot itself is running in Docker on Almalinux

### Smartphone (please complete the following information)

Not being used

### Environment (please complete the following information)

Self- hosted. Running in a Docker container on an Almalinux machine

### Frontend Stack Trace

```console
No known stack traces. The combined logs for frontend and backend are attached
```

### Backend Stack Trace

```console
No known stack traces. The combined logs for frontend and backend are attached
```

**Comment by superalex** [comment]
Hi @RobertBrown3 

What url are you using to access penpot from the other machine?.

Could you check the network tab of your browser to check if there is more info about the failing requests?

Regards,

**Comment by RobertBrown3** [comment]
I am not using any special URL at this point. I am currently just using the IP address of the server (192.168.1.103) in order to access Penpot. It doesn't matter, though. I have used different URL setups, using domains (prototype.factor3webworks.net) and the actual name of the host machine (Sol-2). I am getting the same failure.

As for the network info, what is weird here is that there are no failing requests. The logs show that all requests made by the client (see logs.txt which I included in the screenshots section). The network traffic on the browser side reflects a successful POST request, then a successful GET request each time I click on the login page, as indicated below. It is almost as if one of the JS files is failing whenever I access Penpot from another machine.

![network](https://user-images.githubusercontent.com/13591779/223437428-36af51b4-32f7-4d59-a516-7c5966428a16.PNG)

**Comment by niwinz** [comment]
Sinse you don't access using localhost, you should setup HTTPS or use
disable-secure-session-cookies
flag.
Documented here:
https://help.penpot.app/technical-guide/configuration/#other-flags

**Comment by RobertBrown3** [comment]
niwinz:

Thanks for the pointer.

1. The documentation you pointed to does not specify which of the components (Penpot client or Penpot server) the disable-secure-session-cookies flag should be set in. Should it be set in the client, the server, or both?
2. Where is the documentation for setting up Penpot to use HTTPS?

**Comment by niwinz** [comment]
Hi @RobertBrown3 

1. You are right, but if you put it in both, in one it will be ignored. In any case the authentication and cookie stuff is backend related. So it should be on backend. You can look on the [docker-compose.yam](https://github.com/penpot/penpot/blob/main/docker/images/docker-compose.yaml#L129) file that has commets with relevant flags for each section.
2. There are nothing penpot specific for setting up HTTPS, so this is why it is not documented as-is, you just need an http/https server + ssl certificate on front of penpot. The previously [docker-compose.yaml](https://github.com/penpot/penpot/blob/main/docker/images/docker-compose.yaml#L14) has a commented traeffic service that facilitates it, but as I said previously, setting up https depends on how the end user deploys penpot on its own server.

**Comment by RobertBrown3** [comment]
Some very strong suggestions:

1. If setting Penpot to use HTTPS is necessary to insure that it will work on systems other than localhost, this fact should be pointed out in the startup documentation. And while there is a "disable-secure-session-cookies" flag that will allow HTTP access outside of localhost, the fact that you can use this flag if you don't want to use HTTPS should also be in the startup documentation. This would be very useful for those who already have services running on their home labs and want to add Penpot to them.
2. I had asked for documentation on setting up Penpot to use HTTPS because based on what niwinz said I had assumed that the Penpot components had some mechanism for its components to process SSL certs. Since using a reverse proxy (like Traefik) is the sole means of setting up Pepot to use HTTPS, there should be a statement to that effect in the startup documentation. It is good that in the docker-compose.yml file that there is an optional Traefik setup for Penpot, what of those who (like me) already have services they are using with a reverse proxy? When first running Penpot, the usual procedure is to run it with the defaults and see what happens. That is what I did. Had I known that I needed to run Penpot using HTTPS in order to access it from machines other than localhost, I would have saved myself a lot of time (and avoided publishing this bug report) by simply setting it up to be used behind the reverse proxy that I am running. The startup documentation needs to inform newcomers of the need to use HTTPS in order to run Penpot on machines other than localhost -- and it also needs to inform them that to run Penpot using HTTPS they should either uncomment the Traefik settings in the docker compose yaml file, or set it up to be accessed through any reverse proxy system that they might happen to be using.

I found a bug here, but I was wrong about there being a bug in Penpot itself. The bug is in the documentation. Following these suggestions will fix this bug.

**Comment by niwinz** [comment]
1. If you already have a homelab with https, you already know how to do it, I mean, penpot has nothing different and nothing special. And in other case,  the default compose file already provides a commented service that facilitates HTTPS gateway using traefik and letsencrypt.
2. That said, the docker compose file already comes with it
![image](https://user-images.githubusercontent.com/843689/223770190-cf845be5-8356-4925-b7b4-33e4e1441726.png)

The startup documetation is intended for installing it on localhost, installing it on your own servers has the pecularities of your own servers and we can't document all the posiblities, just provide example configuration with and without https and with corresponding warnings:

![image](https://user-images.githubusercontent.com/843689/223770800-44707135-be36-49da-bcc0-f21bacb16be6.png)

I take in account your suggestion to improve documentation and make it more explicit. But the example compose file has all the essential warnings and configuration examples right now.

**Comment by RobertBrown3** [comment]
niwinz:

1. As I stated in my previous comment, my problem wasn't that I "didn't know" how to set up Penpot to use HTTPS with a reverse- proxy. The problem was that some applications (like Nextcloud, or many of the dockerized services I provide) can be set up to use HTTPS without using a reverse proxy. I did not know whether or not Penpot had that capability, and even the documentation in the docker-compose file does not make that clear. Once you made that clear in your previous comment, I knew what I needed to do. I am suggesting that the text be amended so that it is clear.
2. Putting the things I suggest in the startup documentation will give people the information they need without having to "document all possibilities".  This is because the amendments I suggest actually cover all possibilities. My suggestion is to merely tell people in the startup documentation that if they want to use Penpot on systems other than localhost that they need to either set it up to use HTTPS behind a reverse proxy (nginx, traefik, etc) or use the disable-secure-session-cookies flag. This one statement will cover any unique setup for any home lab that wants to use Penpot for anything other than a toy to be played with on localhost.   You don't have to worry about describing what to do in different homelab setups. You just need to tell homelabbers what to do. 

So again: the bug is in your documentation. Add one or two statements and that bug will be fixed.

**Comment by niwinz** [comment]
Yep, thanks, we take a note on this and we try to improve soon.

Thank you very much.

**Comment by Luke1982** [comment]
> Sinse you don't access using localhost, you should setup HTTPS or use disable-secure-session-cookies flag. Documented here: https://help.penpot.app/technical-guide/configuration/#other-flags El mar., 7 mar. 2023 14:35, RobertBrown3 ***@***.***> escribió:

Is this an either/or? So should penpot work through HTTP when this flag is set? I tried it in the YAML file, but still couldn't log in.
