### ISSUE TITLE
feature: Background images in objects

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#3024]
### Is your feature request related to a problem? Please describe.

**Problem:** When one wants to have a texture or other background pattern, one needs to manually prepare it in another app and place it at the back of the layer stack in frame. 

### Describe the solution you'd like.

Have a function that allows to use images as background images instead of color or color gradient, similar to the corresponding function in figma. 

This could also be useful for communication, showing developers/managers how the effect can be archieved with a small texture that does not increase load times a lot. 

### Additional context

Based on this community post: ["Is there something like “background image repeat” currently in the app?"](https://community.penpot.app/t/is-there-something-like-background-image-repeat-currently-in-the-app/2707)

**Comment by EsterLatorre** [comment]
Hello jdittrich,
We currently have that functionality designed and it is ready to develop, and will be considered soon! You can check it out, and its progress here: https://tree.taiga.io/project/penpot/us/2983

Thanks for your message!

**Comment by berserkwarwolf** [comment]
> Hello jdittrich, We currently have that functionality designed and it is ready to develop, and will be considered soon! You can check it out, and its progress here: https://tree.taiga.io/project/penpot/us/2983
> 
> Thanks for your message!

I'm waiting for this feature to test Penpot as a HTML book cover designer. HTML Paged media to PDF conversion has advanced enough to be a viable workflow.

**Comment by cristianonisor007** [comment]
> Hello jdittrich, We currently have that functionality designed and it is ready to develop, and will be considered soon! You can check it out, and its progress here: https://tree.taiga.io/project/penpot/us/2983
> 
> Thanks for your message!

Do you know if https://tree.taiga.io/project/penpot/us/2983 will be included in the sprint 50 release, on 16 of November 2023?

**Comment by udany** [comment]
Was looking for this feature and saw it's marked as closed on Taiga, neat!

If you don't mind me asking, what is the expected timeline on this actually shipping?

[EDIT] I found components.penpot.dev and saw I could register there, maybe it's not yet been fully updated, but I noticed the dark theme and decided to test it out and couldn't find a way to make the image fill repeat itself:

https://github.com/penpot/penpot/assets/6425637/ae5a6d04-62a8-401c-aa5d-727f0457175c
