### ISSUE TITLE
bug: Color Asset Unlinks from Object when Clicking Inside HEX Field

### ISSUE THREAD

**Issue by candideu** [uxbox/uxbox#3026]
I often use my Colour Assets to keep brand colour hex codes handy for copy-pasting. That said, whenever a Color Asset is applied to an object, and I go to the object's Fill properties to copy the HEX code of the Color Asset, the Color Asset is removed from the object when I click away, even though I didn't modify the HEX code.

### Steps To Reproduce
1. Create a Colour Asset
2. Create a rectangle
3. Add the Colour Asset to the rectangle
4. Click on the Fill property and click inside the HEX field to copy it
5. Click away on the canvas
6. Click on the rectangle and notice the Fill colour

### Expected behavior

Fill colour should remain as the Colour Asset

### Actual behavior

Colour Asset is removed as the object's Fill Colour

### Screenshots or video

https://user-images.githubusercontent.com/55474996/223841022-08e0d416-a90a-41b0-913b-9c80d4971a1d.mp4

### Desktop (please complete the following information)

Windows 10
Firefox 110.0

### Additional context

Alternately: It would be nice to have a "Copy HEX Code" option in the Colour Assets panel when a user hovers over a colour, or something.

![image](https://user-images.githubusercontent.com/55474996/223843176-2dbad54d-0cb1-4a7d-8cfb-56877615d958.png)

**Comment by superalex** [comment]
Thank you very much @candideu 

I've juts created this issue on Taiga to track it: https://tree.taiga.io/project/penpot/issue/5003 I hope it can be fixed soon
