### ISSUE TITLE
bug: Font-Kerning does not work on Artboard Export to PNG/JPG/PDF

### ISSUE THREAD

**Issue by dawe-rgb** [uxbox/uxbox#3029]
### Steps To Reproduce

1. Select an Artboard with Text
2. Goto Export (Right-Side Bottom)
3. Select 2x and PNG
4. Export 1 Element

### Expected behavior

Font is rendered like in Penpot with correct kerning

### Actual behavior

Kerning is broken, spaces between the letters are not right. 

### Screenshots or video

![font-kerning-bug](https://user-images.githubusercontent.com/56391227/224271925-e05a98a0-fdaa-43d3-8536-0f5312a9e00f.png)

Font used: Inter (I have the issue with other fonts too)

### Desktop (please complete the following information)

Mac OS 13.2.1
Brave: [Version 1.48.171 Chromium: 110.0.5481.177 (Offizieller Build) (arm64)](https://brave.com/latest/) 

### Environment (please complete the following information)

https://penpot.weberruss.com
Ubuntu 20.04.5 LTS

**Comment by superalex** [comment]
Hello @dawe-rgb could you please attach a .penpot example file? 

Thanks!

**Comment by dawe-rgb** [comment]
Hi @superalex, thanks for your reply. Here is the .penpot example file: 
[Kerning bug.penpot.zip](https://github.com/penpot/penpot/files/10955278/Kerning.bug.penpot.zip)

**Comment by dawe-rgb** [comment]
I have found a workaround: Using the Chrome "Full Page Screen Capture" extension, I take a screenshot in the Prototype fullscreen view and then crop it. Bit more time consuming but it works for now. :)

**Comment by superalex** [comment]
Thank you very much @dawe-rgb 

I've been working on this and I found the problem :)

We are using a headless chrome browser to render the exported svg and it seems it has som kerning issues when executed in that mode (https://stackoverflow.com/questions/52552573/kerning-issues-with-headless-chrome). I've justo fixed it and it will be available in the next release

The taiga link related to the issue -> https://tree.taiga.io/project/penpot/issue/5046

**Comment by dawe-rgb** [comment]
Thank you for fixing it! :-)
