### ISSUE TITLE
bug: Board outlines always cover the content inside, even when `clipping content` isn't selected

### ISSUE THREAD

**Issue by Manueljlin** [uxbox/uxbox#3031]
### Steps To Reproduce

1. Create a new board, we'll name it `container`
2. Add an outline to `container`
3. Disable `Clip content`
4. Create a new subboard inside `container` called `row` that is larger than `container`

### Expected behavior

The content of `row` **doesn't get** obscured by the superboard `container`
![Screenshot_20230310_114302](https://user-images.githubusercontent.com/11275573/224295727-d6efc8ca-49e0-4f45-8ca3-120b7f10f63f.png)

### Actual behavior

The content of `row` **gets** obscured by the superboard `container`

![image](https://user-images.githubusercontent.com/11275573/224295912-816443b0-7923-40db-a57e-18544c516d8a.png)

### Screenshots or video

[vokoscreenNG-2023-03-10_11-34-50.webm](https://user-images.githubusercontent.com/11275573/224296371-73503d85-2320-4994-9693-29b0a172c411.webm)

### Desktop (please complete the following information)

Operating System: openSUSE Tumbleweed 20230222
KDE Plasma Version: 5.27.0
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.12-1-default (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C91
System Version: 3.0

### Environment (please complete the following information)

Using penpot.app

**Comment by EsterLatorre** [comment]
Hello Manuel! 

If I understood correctly, I've logged the issue in taiga and I consider it to be of high priority, so we will try and fix it soon. You can check it out here: https://tree.taiga.io/project/penpot/issue/5031

Thanks for your message!

**Comment by superalex** [comment]
Hello @Manueljlin 

We have been discussing it internally and right now we will let it work as it is. For us it make sense having the strokes over and the fills under the shape. You can always take the element out of the anidated board and make it work as you want:

![image](https://user-images.githubusercontent.com/1579633/226534392-4c8f9cea-ecb2-4700-8db0-c58033cd12ff.png)

A college described the problem this way: "if you have a picture on a wall and you put a canvas that comes out of the frame, do you cover the frame with the canvas?".
