### ISSUE TITLE
feature: Penpot API file for autogenerating API libraries? 🤔 e.g.  OpenAPI 👀

### ISSUE THREAD

**Issue by Filip-Anicic** [uxbox/uxbox#3034]
### Is your feature request related to a problem? Please describe.

Creating an code library to communicate with Penpot takes a lot of time creating boilerplate for API calls and the API documentation is sparse, only [documented](https://design.penpot.app/api/_doc) with Clojure spec which not everyone is familiar with.

A boilerplate code generator for the API would solve the issue of creating and maintaining a long list of API functions to communicate with Penpot, but there is no good resource to generate the functions from.

### Describe the solution you'd like.

I'd like a resource/file for developers to easily parse and auto generate boilerplate code for the Penpot API, making it easier to make Penpot libraries for different programming languages.

Researching on the internet, there is an open-source standard called [OpenAPI](https://github.com/OAI/OpenAPI-Specification) and a code generation tool called [Swagger-Codegen](https://github.com/swagger-api/swagger-codegen). It is able to generate API client libraries, server stubs and documentation automatically based on an OpenAPI file to a large variety of [programming languages and frameworks](https://github.com/swagger-api/swagger-codegen#overview).

### Describe alternatives you've considered.

Currently I'm scrubbing information from the [Builtin API documentation page](https://design.penpot.app/api/_doc) to auto generate Python API functions, but I don't think it is sustainable, because if someone changes the format of the HTML page or adds a new Clojure spec to the API, my scrubbing script would go **boom**💥.

example of a **WIP** generated function
``` python
def create_comment(session: Session, profile_id :str, thread_id :str, content :str, share_id :str) -> str:
	"""
	tag: AUTH,
	Added: on v1.15,

	Parameters
	----------
	Required
	profile_id : str, required
	thread_id : str, required
	content : str, required

	Optional
	share_id : str, optional
	"""
	if profile_id is None: raise ValueError('profile-id is not set')
	if thread_id is None:  raise ValueError('thread-id is not set')
	if content is None:    raise ValueError('content is not set')

	headers = { "Content-Type": "application/json" }
	payload = { "profile-id": profile_id, "thread-id": thread_id, "content": content }

	if share_id is None: payload["share-id"] = share_id

	succeded, response = sendRequest(session, 'POST', apiEndpoint, headers, payload)
```

### Additional context

My primary goal was to make a framework from which I can create python or C++ plugins for Unreal Engine to integrate Penpot into the game development workflow.

I'm still green in this area of web API development and Clojure, since I come from a game development background, so I'm open to any suggestions of alternatives from people with more knowledge in the field.

**Comment by jdittrich** [comment]
Indeed, OpenAPI and Swagger are very much the standard tools here. It has nothing to do with Clojure itself, though different languages will have different tooling to support creation of these files. Some web frameworks like FastAPI (python) would autogenerate such API documentation but they can also be manually written.

**Comment by niwinz** [comment]
hi @Filip-Anicic and @jdittrich 

In summary, I'm already started working on it. I know that the spec approach is not very comfortable and indeed is pretty bad as documentation. I have started a new approach for it that allows specify the params the output and webhook event if the method generates it. Expose in human readable and programmable access.

I can't give it a deadline, but the work is already started. I don't know if the result of my work can be used directly with swagger codegen (never used), but my intention is provide a openapi type for each endpoint params and the openapi type for the output.

**Comment by niwinz** [comment]
Additional note: access tokens are also landed in the backend API, still not exposed on UI, but they will be available sooner or later, because backend already supports it. Access tokens allows access the API using a simple token without need to proceed with constant authentication.

**Comment by Filip-Anicic** [comment]
> In summary, I'm already started working on it. I know that the spec approach is not very comfortable and indeed is pretty bad as documentation. I have started a new approach for it that allows specify the params the output and webhook event if the method generates it. Expose in human readable and programmable access.

I have **0** experience in making APIs, so I'm glad to hear I seem to hit the nail on what you were planning for the API.

> I can't give it a deadline, but the work is already started. I don't know if the result of my work can be used directly with swagger codegen (never used), but my intention is provide a openapi type for each endpoint params and the openapi type for the output.

I'd assume if it follows the spec, (again **0** experience) it should work with swagger. Even if it's partial, it's still something to start from and enable easier time creating and updating code libraries to communicate with penpot.

**Comment by niwinz** [comment]
#3053 comes with the initial work that enables fully compliant openapi 3.0 json output, swagger ui, and many other related stuff. It is still in development...

**Comment by capjan** [comment]
Hello,
is there any update on this topic? 
I would like to use color, fonts, and possibly whole views defined in penpot in a native iOS app. I believe accessing the data via an API would be the most suitable approach for this.

**Comment by sneko** [comment]
I think this issue can be closed. On https://design.penpot.app/api/doc in the first paragraph they give a link to the OpenAPI schema (https://design.penpot.app/api/openapi.json). From there you can generate a client in whatever language you want 👍

**Comment by tmcdos** [comment]
The file is no longer there - giving error 404. And it is no longer mentioned in any parahraph of the API documentation.

**Comment by sneko** [comment]
@tmcdos it has moved to https://design.penpot.app/api/main/doc/openapi.json . I saw your other issue for `figpot`, will try to find time to fix the issue

**Comment by tmcdos** [comment]
Thank you for the rapid reaction !
