### ISSUE TITLE
bug: Wrong translations

### ISSUE THREAD

**Issue by SatarisGIT** [uxbox/uxbox#3035]
### Steps To Reproduce

1. Create some element with text on it
2. Go to "View Mode"
3. Click on "text" element
4. Now you can see it on right panel

### Expected behavior

It is only misspelled translations keys and one translation missing :)

### Actual behavior

You can see it in screen below

### Screenshots or video

![image](https://user-images.githubusercontent.com/28608081/224564353-71003c3c-797d-484f-9607-00cc180cd79f.png)

**Comment by superalex** [comment]
Thank you very much for reporting!,

I've just created this on Taiga to track it https://tree.taiga.io/project/penpot/issue/5011
