### ISSUE TITLE
feature: Specify the user UID and GID of the penpot application running inside the docker container

### ISSUE THREAD

**Issue by suiyueou** [uxbox/uxbox#3040]
### Is your feature request related to a problem? Please describe.

When I first deployed penpot half a month ago, I encountered the error `An unexpected error occurred while uploading images`, specifically due to a folder permission problem when mounting data using the host path, which was solved by changing the access rights of the folder to 777, see #2961 for details.

### Describe the solution you'd like.

So I was wondering, when penpot is started with docker-compose.yml, whether it is possible to support specifying the user used to run penpot inside the container by uid and gid, for example:

```
services:
  penpot:
    ......
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ......
```

For a concrete implementation, perhaps see the implementation of another open source project, [gitea](https://github.com/go-gitea/gitea), on this: [Dockerfile](https://github.com/go-gitea/gitea/blob/main/Dockerfile) and [entrypoint](https://github.com/go-gitea/gitea/blob/main/docker/root/usr/bin/entrypoint)

**Comment by niwinz** [comment]
Thanks @suiyueou, but this was a bug on our containers and it is already fixed for new installs.
