### ISSUE TITLE
bug: Scroll state not preserved when switching pages

### ISSUE THREAD

**Issue by NusryNizam** [uxbox/uxbox#3052]
### Steps To Reproduce

1. Open a penpot file which contains multiple pages
2. Click on a page in the left sidebar

### Expected behavior

The respective page shows while the scroll position is preserved in the pages list.

### Actual behavior

The respective page shows but the scroll position is not preserved in the pages list.

### Screenshots or video

[penpot.webm](https://user-images.githubusercontent.com/24385617/225819709-1247e604-269d-4f26-9eb8-850dce55d6a0.webm)

### Desktop (please complete the following information)

- Ubuntu 22.10
- Firefox 111 (64-bit)

### Environment (please complete the following information)

- https://design.penpot.app

**Comment by EsterLatorre** [comment]
Hi Nusry Nizam,
I've noticed that this only happens in firefox, I'll upload the issue and we'll try to fix it soon: https://tree.taiga.io/project/penpot/issue/5045
Thanks for your message!
