### ISSUE TITLE
bug: Server responded with status of 502

### ISSUE THREAD

**Issue by akibrk** [uxbox/uxbox#3055]
### Steps To Reproduce

Just work with the app for 1 hour. Working with images does this more often.

### Expected behavior

Should not crash and make all my work disappear. 

### Actual behavior

Crashing every 2mins, then working for sometimes and crashing continuously. 

### Screenshots or video

![image](https://user-images.githubusercontent.com/33821998/226199746-8365abfa-90b4-414a-a816-6fb63c371d41.png)

### Desktop (please complete the following information)

- Windows 11
- i5 12 Gen, 16GB RAM
- Chrome is up to date
Version 111.0.5563.65 (Official Build) (64-bit)

### Additional context

It keeps crashing while saving, attached screenshot.

**Comment by niwinz** [comment]
Sorry for late response, but we still researching the possible cause of this 502 response

**Comment by madalenapmelo-kp** [comment]
Hi @akibrk,

Could you please confirm if you are still experiencing this behavior?

**Comment by akibrk** [comment]
Sorry, I have stopped using penpot after those issues. I would have to recreate account.
