### ISSUE TITLE
feature: Add support for switching nested frames/components inside components

### ISSUE THREAD

**Issue by Manueljlin** [uxbox/uxbox#3056]
### Is your feature request related to a problem? Please describe.

Just like how React and Vue components have slots that support adding arbitrary content inside...

```html
// component.vue
<div class="flex flex-col py-4 px-6 bg-light-sun gap-2">
  <slot></slot>
</div>
```

```html
// page.vue
<Card>
  <Profile />
  <h1>
    {{ post.title }}
  </h1>
  <p>
    {{ post.body }}
  </p>
  <ActionsRow>
    <Action type="comment">
    <Action type="like">
  </ActionsRow>
</Card>
```

components inside a design kit should also have them too.

#### Ideally:
Allow users to add a slot to a component where you can add any arbitrary content, component or not. For example, a Card component that only handles the Flex Layout, fill and shadow, and allows you to add titles, shapes and other components such as buttons which might themselves also have slots to add icons or descriptions, etc.

#### If the above isn't feasible:
Allow users to swap components inside other components with other, different components. For example, a Card component that has three placeholder components allows you to swap the first for a Title component, the second for an Image component and the third for a Button component. The button component would also have a frame that gets swapped with the Icon component.

### Describe alternatives you've considered.

- Detaching a card component instance to add a single line of text and being sad.
- Creating a bunch of components to accomplish the same thing (makes maintaining the design kit quite a pain).

### Additional context

Design tools like Sketch and Figma have (to some extent*) support for slot-like behavior by allowing you to swap one nested component for another:

[*] as you can see way above in the `.vue` examples, you can **add an arbitrary amount** of content. In Sketch's and Figma's case, you can only **swap** existing content or placeholders that act as slots. This is not ideal, but it's better than nothing.

1. First, create a component slot placeholder:
![image](https://user-images.githubusercontent.com/11275573/226205640-3269339b-9931-4587-8624-732143fc7ade.png)
^ Here, PlaceholderFrame is literally just a frame with a fill, that will get swapped out by another component.
ViewFrame is a different component that just handles the layout/content arrangement behavior via auto layout. By default it just has a PlaceholderFrame inside.

2. Then, create a component with a nested ViewFrame. This will act as the slot.
![Screenshot_20230319_211941](https://user-images.githubusercontent.com/11275573/226206720-55129760-a0d9-4793-b591-595d9c6e447d.png)

Example on how this is used:

[vokoscreenNG-2023-03-19_20-32-42.webm](https://user-images.githubusercontent.com/11275573/226204639-f2f40213-f30d-48a0-bedc-83f49ae72813.webm)

![image](https://user-images.githubusercontent.com/11275573/226205292-7fed54fd-b895-40ea-9145-73a5cfb60c88.png)

![image](https://user-images.githubusercontent.com/11275573/226205349-0f8c5aac-0253-4a29-9139-052141f9df8b.png)

Here's another approach used by the Figma devs (quite different in execution but same concept): https://www.youtube.com/watch?v=FOGgsPz3UTk

**Comment by EsterLatorre** [comment]
Hello Manueljlin,
We're currently working on a redesigned version of the components. This that you're suggesting will be in a phase 2 of it. We'll take your considerations on board.
Thanks for your suggestions!
