### ISSUE TITLE
bug: "Hide grid" keyboard shortcut broken in Chrome on Linux

### ISSUE THREAD

**Issue by gma** [uxbox/uxbox#3071]
### Steps To Reproduce

1. Launch Chromium on Linux (I'm  on Pop!_OS [so basically Ubuntu])
2. Navigate to a Penpot file that has a grid (I'm using a basic 12 column grid)
3. Press `Ctrl + '` to show/hide the grid (which doesn't work for me)

### Expected behavior

I expect the grid's visibility to toggle on/off when pressing the key combo (it works when I select the "View -> Show grids/Hide grid" menu items, not for the keyboard shortcut).

### Actual behavior

Nothing happens when I type the `Ctrl + '` key combo in Chromium based browsers.

### Desktop (please complete the following information)

- OS: Pop!_OS 22.04
- Browsers: 
  - Chromium Version 110.0.5481.100 (totally clean, no extensions installed) — doesn't work
  - Brave (Version 1.49.120, based on Chromium: 111.0.5563.64) — doesn't work
  - Firefox — works fine

**Comment by elhombretecla** [comment]
Hi @gma thanbks for your feedback :)

We've created the issue in Taiga to managa it asap.

[https://tree.taiga.io/project/penpot/issue/5102](https://tree.taiga.io/project/penpot/issue/5102)

Thanks!

**Comment by gma** [comment]
Thanks for getting to this so quickly. I've just logged in to check, and see that 1.18 is released. :+1:

Unfortunately I'm not finding that `Ctrl + '` works in any of my chrome-based browsers. It's still working in Firefox.

Browsers used for testing:

- Chromium (Version 111.0.5563.146), with no extensions installed
- Brave 1.49.132 (Chromium Version 111.0.5563.147), in private window (i.e. no extensions)

In Firefox it just works, as it did before I filed the bug. /cc @superalex

**Comment by superalex** [comment]
Hey @gma 

Are you sure you are using ' and not ´ ?

And one more question, if access to https://www.toptal.com/developers/keycode and press ', what code is shown?

**Comment by gma** [comment]
I am. I keep mentioning Firefox works to give us all more confidence that I'm not the cause of the fail! ;-)

**Comment by gma** [comment]
[Original reply deleted, and reposted via web UI to enable Markdown support]

I am. I keep mentioning Firefox works to give us all more confidence that I'm not the cause of the fail! ;-)

The toptal keycode page is interesting (what a handy page!)

Here's the Chrome event dump:

```json
{
 "key": "'",
 "keyCode": 192,
 "which": 192,
 "code": "Quote",
 "location": 0,
 "altKey": false,
 "ctrlKey": true,
 "metaKey": false,
 "shiftKey": false,
 "repeat": false
}
```

In Firefox I get this:

```json
{
 "key": "'",
 "keyCode": 222,
 "which": 222,
 "code": "Quote",
 "location": 0,
 "altKey": false,
 "ctrlKey": true,
 "metaKey": false,
 "shiftKey": false,
 "repeat": false
}
```

In both browsers I'm seeing the same "Description"; "single quote / ø / ä". It's just `event.which` that differs.

What I'm finding quite confusing at this point is that the MDN keyCode page [1] lists 192 as "Backquote". I'm definitely not pressing backquote, I've got the toptal debug page open in both browsers, next to each other. And in both they're reporting the key as "Quote", even though `event.which` is different!

I'm wondering if my GNOME desktop keyboard settings are messing with this somehow. I've not configured anything that should affect "'" itself, but I have remapped CAPS to Ctrl. I've been testing this with a real physical Ctrl key though, not my remapped CAPS key. I'll clear those settings and re-test.

**Comment by gma** [comment]
Update on the above; the GNOME keyboard settings aren't related. If I press `'` on its own on the Toptal page, I get 192 in Chromium and Brave and 222 in Firefox.

If I press the backtick key, I get 223 in Chromium and Brave, and 192 in Firefox.

In all browsers, backtick puts "Backquote" in `event.code`.

Is Penpot checking `event.which` to determine what was pressed? Perhaps it's more reliable to check `event.code` instead? :shrug:

I checked MDN and the `UIEvent.which` page does say that it's deprecated.

**Comment by superalex** [comment]
Thank you very much @gma that's really helpful 

We could but actually we are relying on https://github.com/ccampbell/mousetrap to manage keyboard shortcuts. In our roadmap we have this user story to manage custom keys combinations (https://tree.taiga.io/project/penpot/us/541) probably we should use something more updated when affording it. 

I think this is the problematic bug -> https://github.com/ccampbell/mousetrap/issues/85

**Comment by gma** [comment]
Yes, I think you're right. I am using a UK layout.

From what I've read on MDN, this line looks suspicious to me!

https://github.com/ccampbell/mousetrap/blob/2f9a476ba6158ba69763e4fcf914966cc72ef433/mousetrap.js#L195

Let me know if you'd like help testing any future fixes/changes.
