### ISSUE TITLE
bug: GnuTLS recv error (-110): The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by VVege** [uxbox/uxbox#3073]
### Steps To Reproduce

1. sudo ./manage.sh build-backend-bundle
2. when `Downloading: org/apache/maven/maven-artifact/3.8.6/maven-artifact-3.8.6.jar from central` occur this error

> 

Downloading: org/apache/maven/maven-artifact/3.8.6/maven-artifact-3.8.6.jar from central
Cloning: https://github.com/penpot/im4java
Execution error (ExceptionInfo) at clojure.tools.gitlibs.impl/git-clone-bare (impl.clj:103).
Unable to clone /home/penpot/.gitlibs/_repos/https/github.com/penpot/im4java
fatal: unable to access 'https://github.com/penpot/im4java/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.

### Expected behavior

I find that the problem need recompile git ，like this ： https://stackoverflow.com/questions/52529639/gnutls-recv-error-110-the-tls-connection-was-non-properly-terminated

but this happend inside of devenv‘s container，i think recompile git inside the container is not  a right way，what should i do？

### Actual behavior

Downloading: org/apache/maven/maven-artifact/3.8.6/maven-artifact-3.8.6.jar from central
Cloning: https://github.com/penpot/im4java
Execution error (ExceptionInfo) at clojure.tools.gitlibs.impl/git-clone-bare (impl.clj:103).
Unable to clone /home/penpot/.gitlibs/_repos/https/github.com/penpot/im4java
fatal: unable to access 'https://github.com/penpot/im4java/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.

### Desktop (please complete the following information)

centos 7

**Comment by niwinz** [comment]
I'm pretty surprised by this error, this is happening inside devenv container, and this container already has all dependencies for build penpot, I and the whole team is using daily for doing that. We never experimented this error and we don't needed to recompile git...

I just throw random ideas but try to ensure you using the latest devenv image:
```
docker pull penpotapp/devenv:latest
```

This is the hash of the image I'm using:

```
~/penpot develop *4 !5 ?26 ❯ docker images                                                                                                                                                                                              10:36:38
REPOSITORY                TAG                     IMAGE ID       CREATED        SIZE
penpotapp/devenv          latest                  8a19eef72553   7 days ago     1.58GB
```
