### ISSUE TITLE
bug: devenv error 

### ISSUE THREAD

**Issue by VVege** [uxbox/uxbox#3077]
### Steps To Reproduce

1. get source code of  tag 1.17.1 
2. ./manage.sh pull-devenv
3. ./manage.sh run-devenv

2. I also try code of tag 1.17-hotfix-15,it has the same problem

### Expected behavior

it can success in http://localhost:3449/ 。 and backend in tmux is continue。

### Actual behavior

backend exit 

> + clojure -A:dev -M -m app.mainWARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.math.numeric-tower, being replaced by: #'clojure.math.numeric-tower/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.contrib.humanize, being replaced by: #'clojure.math.numeric-tower/abs
Reflection warning, user.clj:113:28 - call to static method alength on clojure.lang.RT can't be resolved (argument types: unknown).
Reflection warning, user.clj:114:28 - call to static method alength on clojure.lang.RT can't be resolved (argument types: unknown).
Reflection warning, user.clj:115:28 - call to static method alength on clojure.lang.RT can't be resolved (argument types: unknown).
Reflection warning, user.clj:116:28 - call to static method alength on clojure.lang.RT can't be resolved (argument types: unknown).
Reflection warning, user.clj:117:28 - call to static method alength on clojure.lang.RT can't be resolved (argument types: unknown).
penpot@a6fbb9f887ce:~/penpot/backend$ 

> 

when I use ./manage.sh log-devenv,it puts

> penpot-devenv-redis   | 1:C 28 Mar 2023 12:46:59.085 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.086 * monotonic clock: POSIX clock_gettime
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.087 * Running mode=standalone, port=6379.
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.087 # Server initialized
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.088 * Loading RDB produced by version 7.0.10
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.088 * RDB age 9 seconds
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.088 * RDB memory usage when created 0.82 Mb
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.088 * Done loading RDB, keys loaded: 0, keys expired: 0.
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.088 * DB loaded from disk: 0.000 seconds
penpot-devenv-redis   | 1:M 28 Mar 2023 12:46:59.088 * Ready to accept connections
penpot-devenv-main    | usermod: no changes
penpotdev-ldap-1      | 6422e110 @(#) $OpenLDAP: slapd  (Nov 17 2020 01:23:45) $
penpotdev-ldap-1      |         Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
penpotdev-ldap-1      | 6422e111 slapd starting
penpotdev-ldap-1      | 6422e1b7 daemon: shutdown requested and initiated.
penpotdev-ldap-1      | 6422e1b7 slapd shutdown: waiting for 0 operations/tasks to finish
penpotdev-ldap-1      | 6422e1b7 slapd stopped.
penpotdev-ldap-1      | 6422e1c3 @(#) $OpenLDAP: slapd  (Nov 17 2020 01:23:45) $
penpotdev-ldap-1      |         Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
penpotdev-ldap-1      | 6422e1c3 slapd starting

### Desktop (please complete the following information)

Mac OS

**Comment by niwinz** [comment]
there are no error so I can't help you, looks external to penpot
