### ISSUE TITLE
bug: Text set as justified does not appear as justified

### ISSUE THREAD

**Issue by timunrau** [uxbox/uxbox#3084]
### Steps To Reproduce

1. Create a text box with some content in it. 
2. Set the text as justified.

### Expected behavior

The text should appear justified.

### Actual behavior

The text continues to be left aligned.

### Screenshots or video

https://user-images.githubusercontent.com/48539072/228621270-67531a47-cc92-425b-8a58-e20d62fd73e7.mp4

### Desktop (please complete the following information)

- Fedora Linux 37
- Firefox  111.0

### Environment (please complete the following information)

https://design.penpot.app

**Comment by elhombretecla** [comment]
Hi @timunrau thanks you for tour report :)

We couldn't reproduce your issue.

![bug-justify](https://user-images.githubusercontent.com/1045247/228746167-60bbc0b1-c44d-469b-b699-64dce0977283.gif)

Can you send to us the penpot file to test it in depth? info@penpot.app

Thanks!

**Comment by elhombretecla** [comment]
Hi again @timunrau it seems that is a Firefox issue [https://bugzilla.mozilla.org/show_bug.cgi?id=1253840](https://bugzilla.mozilla.org/show_bug.cgi?id=1253840)

**Comment by timunrau** [comment]
> Hi again @timunrau it seems that is a Firefox issue https://bugzilla.mozilla.org/show_bug.cgi?id=1253840

Thanks for digging into this. I will try chromuim based browser. Sorry for not responding earlier.

**Comment by jkoop** [comment]
Last I checked web developers were supposed to make websites that worked on browsers. Not the other way around.
