### ISSUE TITLE
bug: when I update penpot from 1.15.2 to 1.17.2, the data lost 

### ISSUE THREAD

**Issue by VVege** [uxbox/uxbox#3088]
### Steps To Reproduce

`docker compose -f docker-compose.yaml pull`

When I finished the update, I found that the previous data was gone。

### Expected behavior

The old data should remains even after the update 1.17.2.

### Actual behavior

I found out, that the location of docker volumes changed。

> 

1.15.2 docker-compose.yaml

`penpot_assets_data:/opt/data`
`penpot_postgres_data:/var/lib/postgresql/data`

> 
1.17.2 docker-compose.yaml
frontend
`penpot_assets:/opt/data/assets`

backend
`penpot_assets:/opt/penpot/assets`

`penpot_postgres_v15: /var/lib/postgresql/data`

How can I migrate the previous data over?    What was the reason for the name change?

**Comment by VVege** [comment]
I am trying to copy data volumes, specifically I have copied "penpot_assets_data" to "penpot_assets", and "penpot_postgres_data" to "penpot_postgres_v15". However, I am getting an error on the webpage with a 502 bad gateway error when trying to access "/api/rpc/query/profile". I am not sure what to do， and the data is very important to me. Thank you for your response.

I check the docker container，the postgres:15 container is fail, and the logs is:
---------------
> 
PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-03-30 13:11:51.931 UTC [1] FATAL:  database files are incompatible with server
2023-03-30 13:11:51.931 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 15.2 (Debian 15.2-1.pgdg110+1).

>

How can I upgrade from Postgres 13 to 15?

**Comment by superalex** [comment]
Helo @VVege 

@niwinz documented this here -> https://community.penpot.app/t/how-to-upgrade-postgresql-version-in-docker-container/2104

Could you please check if it solves your issue?

**Comment by VVege** [comment]
> 

Yes, this tutorial helped me successfully upgrade PostgreSQL. Thank you very much. However, now there is another issue, which is that the volume name for the asset has also changed: 1.15.2: penpot_assets_data. 1.17.2: penpot_assets.

If I directly copy the penpot_assets_data volume to penpot_assets, there will still be errors. After testing, I found that I need to copy penpot_assets_data/assets to penpot_assets, and then it will work. However, I do not know if there will be any other issues with this operation, and I have not found any relevant documentation. I want to confirm if what I did is appropriate.

**Comment by niwinz** [comment]
On upgrading, the volume name should not be changed, they are under the user control I mean, this is just a label, and can be the old one (for assets)

**Comment by VVege** [comment]
> On upgrading, the volume name should not be changed, they are under the user control I mean, this is just a label, and can be the old one (for assets)

ok，thanks，It seems like I was overthinking it. I'm going to try not renaming the assets volume and see how that works.
