### ISSUE TITLE
bug: Unable to invite members to join the team Invitation to Join Invite link verify-token 400

### ISSUE THREAD

**Issue by fqd0711** [uxbox/uxbox#3090]
### Steps To Reproduce

When I invite members to join the team by sending an email after creating the team, the member will click the link after receiving the email to prompt that the invitation is invalid, or the invitation is cancelled or expired. What should I do to make it effective.I even made the same mistake by copying the invitation link

### Expected behavior

Team members accept invitations to join the team via an email link

### Actual behavior

Team members cannot join the team by clicking the email link, and the email link is invalid

### Screenshots or video

![image](https://user-images.githubusercontent.com/33388956/229011721-e3eb14fc-37da-4e87-a322-a55634131b7b.png)
![image](https://user-images.githubusercontent.com/33388956/229084177-4c3e8a21-f916-49de-afea-c9ce351310f5.png)
![image](https://user-images.githubusercontent.com/33388956/229085214-b1ff3915-2354-44f0-84da-1c611f0d146c.png)

### Environment (please complete the following information)

cenos7.8 Docker version 23.0.2  penpot version 1.17.2

### Frontend Stack Trace

172.23.0.1 - - [31/Mar/2023:09:03:21 +0000] "GET / HTTP/1.0" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.23.0.1 - - [31/Mar/2023:09:03:21 +0000] "GET /api/rpc/query/profile HTTP/1.0" 200 633 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.23.0.1 - - [31/Mar/2023:09:03:22 +0000] "GET /api/rpc/command/get-teams HTTP/1.0" 200 437 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.23.0.1 - - [31/Mar/2023:09:03:22 +0000] "POST /api/rpc/command/verify-token HTTP/1.0" 400 115 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.23.0.1 - - [31/Mar/2023:09:03:22 +0000] "GET /ws/notifications?session-id=52ab44c2-4320-8002-8002-48fe2820e03a HTTP/1.0" 400 130 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
172.23.0.1 - - [31/Mar/2023:09:03:24 +0000] "GET /ws/notifications?session-id=52ab44c2-4320-8002-8002-48fe2820e03a HTTP/1.0" 400 130 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"

### Backend Stack Trace

</html>
------=_Part_4_1369626881.1680250991842--

------=_Part_3_501762884.1680250991842--
.
250 2.0.0 OK  1680250992 n19-20020a9d6f13000000b006a11dd6d2c1sm874088otq.29 - gsmtp
DEBUG SMTP: message successfully delivered to mail server
QUIT
221 2.0.0 closing connection n19-20020a9d6f13000000b006a11dd6d2c1sm874088otq.29 - gsmtp

### Additional context

---
version: "3.5"
networks:
  penpot:
volumes:
  penpot_postgres_v15:
  penpot_assets:
services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9001:80
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
    labels:
      - "traefik.enable=true"
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password
  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-postgres
      - penpot-redis
    networks:
      - penpot
    environment:
      - PENPOT_FLAGS=enable-registration disable-demo-users enable-login-with-password enable-email-verification enable-smtp enable-prepl-server enable-smtp-debug
      - PENPOT_PUBLIC_URI=https://xxxxx.com
      - PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=penpot
      - PENPOT_REDIS_URI=redis://penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=true
      - PENPOT_SMTP_HOST=smtp.gmail.com
      - PENPOT_SMTP_PORT=587
      - PENPOT_SMTP_USERNAME=xxxxx@gmail.com
      - PENPOT_SMTP_PASSWORD=xxxxxx
      - PENPOT_SMTP_TLS=true
      - PENPOT_SMTP_SSL=false
  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot
    environment:
      - PENPOT_PUBLIC_URI=https://xxxxx.com
      - PENPOT_REDIS_URI=redis://penpot-redis/0
  penpot-postgres:
    image: "postgres:15"
    restart: always
    stop_signal: SIGINT
    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data
    networks:
      - penpot
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot
  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot
  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - penpot

**Comment by superalex** [comment]
Hello @fqd0711 

I've just created a new local instance with docker and a configuration almost equals to yours and everything seems to work ok (the only difference is the public url).

Are you sure you are testing the invitation link in a non logged tab? (if you are logged in with user A, invitates user B and use that link for the user A logged in it won't work, you should test it in a new incognito tab).

Regards,

**Comment by lpadula** [comment]
Exactly same problem here, with the docker instance

**Comment by niwinz** [comment]
Ensure you have correctly set a permanent PENPOT_SECRET_KEY, if not all invitations created from one start, becomes invalid on the next container restart, I don't know if this is the cause of this issue, but this can be a possible one

https://github.com/penpot/penpot/blob/main/docker/images/docker-compose.yaml#L142

**Comment by lpadula** [comment]
Now its working. Thanks.

**Comment by fqd0711** [comment]
> 现在它的工作。谢谢。

Which p configuration did you modify to make it work? I still can't work now

**Comment by fqd0711** [comment]
> Ensure you have correctly set a permanent PENPOT_SECRET_KEY, if not all invitations created from one start, becomes invalid on the next container restart, I don't know if this is the cause of this issue, but this can be a possible one
> 
> https://github.com/penpot/penpot/blob/main/docker/images/docker-compose.yaml#L142
Later, I used the python3 -c "import secrets; print(secrets.token_urlsafe(64))" method in the document to configure the key, but it still doesn't work, whether it is configured or not configured with PENPOT_SECRET_KEY, it will not take effect, I am not sure Is the key configuration generated by python3 -c "import secrets; print(secrets.token_urlsafe(64))" correct?
