### ISSUE TITLE
Translation: Latvian(Latviešu)

### ISSUE THREAD

**Issue by nikita-kozlovs** [uxbox/uxbox#3095]
Hi there!
I'm a native speaker of Latvian. I would like to help translate this project. 
There's no Latvian translations yet, but I hope to change that so 🎉  I can implement your solution in my current organization. 
My username on Weblate is [@nikita.kozlovs](https://hosted.weblate.org/user/nikita.kozlovs/)

**Comment by elhombretecla** [comment]
Hi @nikita-kozlovs your weblate user is now available :)

Thank you so much for your contribution!

**Comment by nikita-kozlovs** [comment]
@elhombretecla, I apologize, but it appears that you have not yet pushed any modifications to the Weblate translation repository. The repository still indicates that the Latvian translation is unavailable, and my account is restricted from making changes to this language.
![image](https://user-images.githubusercontent.com/129505748/229425445-8f4c30e3-b182-4a47-9233-7446714c2a2d.png)

**Comment by elhombretecla** [comment]
Please try again, now should works :)
