### ISSUE TITLE
feature: Customizable controls / shortcuts

### ISSUE THREAD

**Issue by mhanuszh** [uxbox/uxbox#3098]
### Is your feature request related to a problem? Please describe.

Some controls conflict with my muscle memory.

### Describe the solution you'd like.

A control / shortcut editor would be beneficial.

**Comment by elhombretecla** [comment]
Hi @mhanuszh thanks for your suggestion :)

We have this feature in our roadmap since a few months. Here you have the [link to track it](https://tree.taiga.io/project/penpot/us/541?backlog-q=shortcut&no-milestone=1). We will prioritize and develop as soon as we can.
