### ISSUE TITLE
bug: Export is not working: Bad Gateway

### ISSUE THREAD

**Issue by dawe-rgb** [uxbox/uxbox#3105]
### Steps To Reproduce

1. Select an Artboard
2. Go to "Export +"
3. Select 2x PNG or anything else
4. Click on Export

### Expected behavior

Downloading an PNG File

### Actual behavior

Error Message: Bad Gateway

### Desktop (please complete the following information)

MacOS 13.3
Chrome Version 111.0.5563.146 (Offizieller Build) (arm64)

### Environment (please complete the following information)

- Host (https://penpot.weberruss.com)
- OS: Ubuntu 20.04.6 LTS
- Docker: docker-compose version 1.25.0, build unknown

### Backend Stack Trace

```console
penpot-penpot-frontend-1   | 172.19.0.1 - - [04/Apr/2023:07:15:46 +0000] "POST /api/export HTTP/1.1" 502 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
penpot-penpot-frontend-1   | 2023/04/04 07:15:46 [error] 9#9: *715 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "POST /api/export HTTP/1.1", upstream: "http://172.19.0.2:80/api/export", host: "penpot.weberruss.com"
```

### Additional context

First I upgraded from 1.17 to 1.18, later I tried it with an fresh install and it also didn't work. I run an NGINX-Proxy on Port 443 and 80.

**Comment by myfunnyandy** [comment]
Hi @dawe-rgb, there's a recent PR that might be the solution for this problem. Could you take a look at it and confirm if it works?

The PR: https://github.com/penpot/penpot/pull/3108

**Comment by dawe-rgb** [comment]
Hi @myfunnyandy, I just pulled the new version and it works now. Thank you!! :)
