### ISSUE TITLE
feature: Set 'Stroke', 'Shadow' color from color palette 

### ISSUE THREAD

**Issue by SatarisGIT** [uxbox/uxbox#3107]
### Is your feature request related to a problem? Please describe.

This is not problem, but discomfort :P

### Describe the solution you'd like.

It would be nice to have feature that's will give availability to set color to stroke, shadow and other from color palette.

At this moment, I can only set "Fill" from color palette, but when I want to set stroke or other color properties using this, it is not possible. I must select color from palette bellow color picker that's is not sorted, and it is ultra time-consuming for searching specific color. 

### Additional context

![image](https://user-images.githubusercontent.com/28608081/229761750-5db20d51-d0f2-4119-86a5-e2c520656d46.png)
![image](https://user-images.githubusercontent.com/28608081/229761890-765a55c5-974f-40ca-b3c0-f9c946299e6d.png)

**Comment by myfunnyandy** [comment]
Hi @SatarisGIT, you can set a stroke color from the color palette by holding the Alt / ⌥ key while clicking on the color. https://help.penpot.app/user-guide/styling/#color-palette

**Comment by SatarisGIT** [comment]
Ow, so nice, it works :)
