### ISSUE TITLE
bug: Flex layout not updated when an element is deleted

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3113]
### Steps To Reproduce

1. Create a flex element with 3 elements in it
2. Delete the element 2
3. The element 3 does not stick to the element 1
4. The flex layout is not properly resized

### Expected behavior

Before the 1.18, when an element was deleted in a flex layout, all the other elements and the flex layout were moved and resized to stay consistent.

Regarding the steps above : 
- the element 3 should stick to the element 1
- the flex layout should be resized to fit the size of elements 1 and 3

### Actual behavior

Nothing moves:
- the element 3 is disconnected from the element 1
- the flex layout is not resized

### Screenshots or video

Context:
![image](https://user-images.githubusercontent.com/62602652/230101190-e7e7fd7b-78d2-42dc-96e0-df8f46d94837.png)

Remove element 2:
![image](https://user-images.githubusercontent.com/62602652/230101325-4a6cc813-8178-4e9c-accf-bd890f47e326.png)

### Desktop (please complete the following information)

- Ubuntu 22.04
- Chrome 111

### Additional context

The flex layout resizes well when clicking on the "Size" parameter

![image](https://user-images.githubusercontent.com/62602652/230101955-d5b64797-e8f7-4f6b-8638-e152df4bbf57.png)

**Comment by myfunnyandy** [comment]
Thanks for the report, we've added [the issue to taiga](https://tree.taiga.io/project/penpot/issue/5134) and we'll fix it soon.

**Comment by Alotor** [comment]
We've fixed this and will be released in the next release.
