### ISSUE TITLE
bug: positionning of children elements in a flex layout still not good

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3114]
### Steps To Reproduce

1. Create a flex layout with a button in it
2. Create a 2nd board, serving as "action menu"
3. Create an interaction on the button:
    - open overlay
    - to board 2
    - manual

### Expected behavior

The board 2 is displayed where I place its ghost.

### Actual behavior

The placement of the board 2 makes no sense, it is not related to the interactive button.

### Screenshots or video

Setup:
![image](https://user-images.githubusercontent.com/62602652/230104254-92455892-af91-44c3-aae2-9e27b0d5fc4a.png)

Interaction + ghost placement:
![image](https://user-images.githubusercontent.com/62602652/230104379-da052661-477a-4f99-8fdc-2ef9586d51b5.png)

Result:
![image](https://user-images.githubusercontent.com/62602652/230104471-ab93adb2-fd85-454c-b3e3-e7b00cb09707.png)

### Desktop (please complete the following information)

- Ubuntu 22.04
- Chrome 111

### Additional context

Should have been fixed in https://github.com/penpot/penpot/issues/3003 but I still have the issue.

**Comment by myfunnyandy** [comment]
It seems that the problem happens with nested boards. We'll take a look soon: https://tree.taiga.io/project/penpot/issue/5135
