### ISSUE TITLE
bug: run with docker api:get-profile 404

### ISSUE THREAD

**Issue by 991547436** [uxbox/uxbox#3119]
### Steps To Reproduce

Hello:
I installed penpot using docker, but after startup, I can’t access it normally, and it prompts api error

Is there any log file that can help troubleshoot this error, the following are some specific steps, please help me, thank you very much

I have confirmed that ports 1080, 9000, 9001 are confirmed to be unoccupied

docker-compose.yaml
I turned on - PENPOT_PREPL_HOST=0.0.0.0
And modify - PENPOT_PUBLIC_URI=http://10.0.33.176:9001

Use docker compose -p penpot -f docker-compose.yaml up -d
Started the service and everything looks good

Figure 1 is the service run by docker
Figure 2 is a web page error message
![centos](https://user-images.githubusercontent.com/15355274/230872930-7c49bfac-e54f-402c-83f5-f738256d8e71.png)

![web](https://user-images.githubusercontent.com/15355274/230872940-1ae76353-f7aa-4349-9153-37921d85d11f.png)

### Expected behavior

404：
http://10.0.33.176:9001/api/rpc/command/get-profile 

### Actual behavior

404：
http://10.0.33.176:9001/api/rpc/command/get-profile

**Comment by VVege** [comment]
Check whether the backend docker container is running normally, you can use docker logs to check the backend logs

**Comment by niwinz** [comment]
Looks like your backend version is different that frontend version, ensure you are using the same version for all 3 modules: frontend, backend and exporter

**Comment by 991547436** [comment]
Exactly the same steps, I replaced a virtual machine and it works fine now

**Comment by wesguirra** [comment]
@991547436 how did you solve this issue, I'm having the same issue, version of containers are equal.

**Comment by 991547436** [comment]
> @991547436 how did you solve this issue, I'm having the same issue, version of containers are equal.

I installed a brand new centos and it worked, the reason for not working may be conflicts with other applications in the old system

**Comment by kaiixing** [comment]
> > @991547436 how did you solve this issue, I'm having the same issue, version of containers are equal.
> 
> I installed a brand new centos and it worked, the reason for not working may be conflicts with other applications in the old system

I'm having the same issue with Centos7.9.2009, which centos version you used now?

**Comment by 991547436** [comment]
> > > @991547436 how did you solve this issue, I'm having the same issue, version of containers are equal.
> > 
> > 
> > I installed a brand new centos and it worked, the reason for not working may be conflicts with other applications in the old system
> 
> I'm having the same issue with Centos7.9.2009, which centos version you used now?

7.9，最小化安装
