### ISSUE TITLE
feature: Request new localization for "Burmese language".

### ISSUE THREAD

**Issue by phyozawtun** [uxbox/uxbox#3122]
### Is your feature request related to a problem? Please describe.

I don't have permission for new language add.

Weblate username: Christian P
Weblate account: @phyozawtun91
Screenshot:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/55659312/230916632-db973cdf-0ea4-4a17-a7e9-7c893cf85b9f.png">

### Describe the solution you'd like.

Please add the Burmese language from your end and give me language edit permission.

**Comment by myfunnyandy** [comment]
Hi @phyozawtun, we've just added the Burmese to our translations list: https://hosted.weblate.org/projects/penpot/frontend/my/

We've also added you as editor to the Weblate project so you can start translating anytime.

Thanks!
