### ISSUE TITLE
feature: Translation Request

### ISSUE THREAD

**Issue by 675056817** [uxbox/uxbox#3126]
### Is your feature request related to a problem? Please describe.

Translation language: Chinese
Translation type: New translation (add the currently untranslated), change existing translation (subsequently, if a problematic translation is found, even if it is corrected)
Weblate information:
Username：wangshiyang
E-mail: wangshiyangchina@gmail.com

### Describe the solution you'd like.

Same as the previous question

**Comment by myfunnyandy** [comment]
You've been already added to the Weblate project :)
