### ISSUE TITLE
feature: How to run this code please note down in Readme.md Thanks

### ISSUE THREAD

**Issue by amitdevteams** [uxbox/uxbox#3131]
### Is your feature request related to a problem? Please describe.

when i download this code im unable to run this project please write down in Readme.md file

### Describe the solution you'd like.

when i download this code im unable to run this project please write down in Readme.md file

**Comment by superalex** [comment]
Hello @amitdevopsschool we have a long README.md containing all the necessary info about installation, are you missing something concrete?

![1](https://user-images.githubusercontent.com/1579633/231672344-fab7b3ee-daf7-469f-b053-905c94c1caf1.png)
