### ISSUE TITLE
./manage.sh run-devenv bug: Cannot install packages. Network error in container?

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3139]
### Steps To Reproduce

1. git clone the repository and cd into it
2. Run `./manage.sh pull-devenv` and `./manage.sh run-devenv`
3. You should/may get the error:

```
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@sentry/minimal/-/minimal-6.17.9.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/penpot/penpot/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

### Expected behavior

Install should work.

### Actual behavior

Install didn't work.

### Screenshots or video

![image](https://user-images.githubusercontent.com/433707/231836594-19734349-31b3-49cf-a585-b0fa445fc095.png)

### Desktop (please complete the following information)

Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

### Environment (please complete the following information)

Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

Docker version 23.0.3, build 3e7cbfd

yarn -v
1.22.19

**Comment by ile** [comment]
At first I got an error from tslib:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/tslib/-/tslib-1.14.1.tgz: ETIMEDOUT".
```

But this time I got an error from "minimal".

And now I got this:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@sentry/browser/-/browser-6.17.9.tgz: ETIMEDOUT".
```

All of them exist though when I go to the url ... so maybe there is a network error from the container?

**Comment by ile** [comment]
I logged into the container, it seems like a network error. Not sure how to fix it.

```
penpot@02e98e04791f:/home$ ./start-tmux.sh 
[start-tmux.sh] Installing node dependencies
~/penpot/frontend ~
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/826
```

**Comment by ile** [comment]
Does this have something to do with it:

```
penpot@372ad61d22ce:/home$ cat /etc/resolv.conf 
search Home
nameserver 127.0.0.11
```

**Comment by icsy7867** [comment]
I would guess your container isn't able to resolve dns

Easy test ....
Exec into a container and install iputils-ping and curl if they aren't already installed.

Does ping 8.8.8.8 work?
Does ping google.com work?

Does the same test produce the same results on the host?

**Comment by ile** [comment]
I don't have it installed anymore, but I would say DNS was indeed the problem.

**Comment by niwinz** [comment]
This is usually happens when something is in conflict with the host. I have had this issue on the past when I pass to connect or disconnect from vpn (after network change, docker containers become completly useless because they stop receiving network traffic) also, a similar when I change from wifi to ethernet.

Your problem looks a bit different, but maybe this helps. In any case it has nothing with penpot as-is. Is just a issue between your operating system and the docker subsystem :(

**Comment by ile** [comment]
I did try all kinds of docker trickery with the DNS, but I couldn't get it to work. Not sure if that `resolv.conf` is the reason? 

I'll close this one though, maybe this has nothing to do with Penpot.

**Comment by niwinz** [comment]
> I did try all kinds of docker trickery with the DNS, but I couldn't get it to work. Not sure if that `resolv.conf` is the reason?
> 
> I'll close this one though, maybe this has nothing to do with Penpot.

I don't think is related to the resolv.conf, that ip is correct in the docker network, looks like the dns is not reachable, so the fault is probably on the network layer.
