### ISSUE TITLE
bug: Distribute vertical spacing failing for overlapped text

### ISSUE THREAD

**Issue by dfelinto** [uxbox/uxbox#3141]
### Steps To Reproduce

1. Create three text elements.
2. Make sure they overlap.
3. Try to distribute vertical spacing

### Expected behavior

They should be able to get vertically distributed, even though they have overlap.

### Actual behavior

The action does nothing.

### Screenshots or video

![image](https://user-images.githubusercontent.com/843498/232022209-e3cb7802-417f-4017-acfd-8265053e2dea.png)

**Comment by hirunatan** [comment]
Sorry, this is behaving as expected. This button, as its name says, distributes the vertical spacing between elements. If there is no space, because elements overlap, it does nothing.

The expected result you want, perhaps could be achieved if the elements are the same height, but it will not make much sense for the general case, I think.

**Comment by dfelinto** [comment]
Hi, I run in this situation enough that I would like to respectfully agree to disagree here :) And I know this is not a valid argument, but Inkscape handles this as I expect (and I even opened figma for the first time yesterday and they also handle this as I expected).

And I see that the code is doing exactly what was designed to. I even dived into it yesterday and found a way to get the behaviour I was expecting and indeed the current behavior is by design (#3267). I just think the design should accomodate to the negative space cases.

Also keep in mind that although the "space" may appear to be negative, sometimes you even have your real elements inside a group already with some internal gapping.

For example:
![image](https://github.com/penpot/penpot/assets/843498/65b4bc75-7274-4d09-91f9-8925730ede7b)
