### ISSUE TITLE
feature: Be able to select texts in View mode

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3148]
### Is your feature request related to a problem? Please describe.

My developpers can not copy/paste the texts that I put in my mockups.

Then I have to manage bad sources for my translation work, as for my developpers, it would be a lot of wasted time to type the text instead of copy/paste it. Then they do shorter, and less relevant for me.

### Describe the solution you'd like.

Be able to select any text on a mockup in View mode.

### Describe alternatives you've considered.

A "copy" option on a text element (on right-click?), it would copy the entire text of the element.

**Comment by superalex** [comment]
Hello @NicolasLeboeuf 

The texts can be selected in the view mode

![image](https://user-images.githubusercontent.com/1579633/232492425-59850158-be0e-40c8-8063-533d3faf8501.png)

**Comment by NicolasLeboeuf** [comment]
Ha, I didn't see the tiny box. My bad then.

**Comment by superalex** [comment]
No problem! :)
