### ISSUE TITLE
bug: changing fill color has issues

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3150]
### Steps To Reproduce

I'm using the cloned repository in dev mode directly. The dev mode is without docker - I'm starting the backend with backebd/scripts/start-dev and frontend with npm run watch-main. I have redis and postgres installed separately and running.

I'm trying out the "Whiteboarding & mapping kit" example.

Caveat: I'm new here, so maybe I'm doing something wrong.

The problem:

I'm editing one of the elements - bringing it to front and changing the fill color. At first changing the fill color works, but then changing it again and "playing with it" doesn't work. 

### Expected behavior

Fill color should change.

### Actual behavior

Fill color doesn't seem to change.

### Screenshots or video

[Screencast from 20.04.2023 09.33.18.webm](https://user-images.githubusercontent.com/433707/233278627-91f4c194-9ea2-4abc-aa94-84a764ab7bca.webm)

### Desktop (please complete the following information)

Ubuntu 22.04

### Environment (please complete the following information)

Ubuntu
Latest Brave
[Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by EvaMarco** [comment]
Hello @ile 
I've checked your issue and I've opened an issue in our taiga project. You can see it [here](https://tree.taiga.io/project/penpot/issue/5196). 
Thanks

**Comment by ile** [comment]
Great. If I were to guess, the picker loses the target what it's supposed to change.
