### ISSUE TITLE
feature: JWT for authentication

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3151]
### Is your feature request related to a problem? Please describe.

Authentication could be even easier.

### Describe the solution you'd like.

How about doing the authentication the same way that [Jitsi](jitsi.org) does it: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/#authentication-using-jwt-tokens

This is a very easy way to integrate with a third party app: you can use a library like https://github.com/auth0/node-jsonwebtoken to create a JWT with a suitable payload (email, name, avatar, etc.) and send the JWT in the url to the Penpot or JItsi, which then uses it to create the user. 

You could do it even so that you go directly to the design screen of the file and put the JWT in the url and Penpot would create the user based on that JWT. Or do it in the POST request if GET is too insecure.

### Additional context

Now that I think of it, is this secure enough?

**Comment by niwinz** [comment]
Hello @ile 
Can you explain the motivation behind this? What is the problem will solve it? Can you explain a real use case?

I mean, the current session tokens are already JWE tokens (almost compatible with JWT standard but just using different claims encoded as json). There are nothing that JWT has to offer that the currently used tokens for auth/authz already can do.

**Comment by ile** [comment]
Hey @niwinz. Let me say that Penpot is great, I will be using it for a long time. I don't know how it can be free. 😮 So thanks!

I was in the impression, that Penpot will want to do the authentication itself and set the cookie by itself (or have OIDC set it). The motivation would be to be able to provide the token to Penpot directly, without any authentication flows (login dialogs) between the third app and Penpot. 

I was starting to figure out if I want to switch from the regular session-based authentication to OpenID Connect in my web app. That could be one way to do it, I suppose? I definitely will want to avoid any authentication flows (extra dialogs) between my app and Penpot.

**Comment by ile** [comment]
Let me also add that as I'm planning to use this, I'm also planning to sponsor this if I just can. (If my product gets users.)

**Comment by ile** [comment]
Can you say what would be the best way to do the authentication right now, if I wanted to avoid any extra login dialogs/login flows between my app and Penpot?

**Comment by niwinz** [comment]
\o/ nice, now I guess I understand the underlying motivation.

On first, we can't provide a way to create authentication tokens by third party applications.

Now, If I understand it correctly you want simplify authentication on your system and proceed with single sign on, right?, In this case there are two options:
- Setup a common OIDC provider, or use your other app as OIDC provider.
- Use penpot as OIDC provider for other app (**Not implemented and not planned for the near future**)

But, something that I guess will make a solution for the **"avoid any extra login dialogs/login flows between my app and Penpot"**, we are already working on a simpler but effective solution for solve that use case: access-tokens. They allow to setup a token that can be used for that purpose. You will be able to create it on profile section and use them for authenticate the api calls between third party apps and penpot.

The current status of access-tokens feature is mostly done on the backend and still missing the UI/frontend. So I guess they will be available on the next version

**Comment by ile** [comment]
I think I will do the common OIDC provider – I was already on that path. That should take care of this problem quite easily.

I will be using Penpot's design page, the actual UI. And maybe Penpot's main page too (at first). So it sounds like I need more than just access-token. 

I'll close this, my problem is solved with the common OIDC provider. Thanks!

**Comment by ile** [comment]
Hi there again @niwinz,

There is one problem with moving from regular session based authentication to OIDC:

My app has a subdomain for each client -- they choose the subdomain when registering. The app is Aamu.app and subdomain could be ile.aamu.app.

Now, when they log in, the password will get saved for that subdomain in the browser. When I'm using OIDC, I think I have to choose a domain for that authentication provider -- like auth.aamu.app. As I log in, the password will get saved for that auth.aamu.app. 

The same user can have many subdomains (like in Slack). Saving the password at auth.aamu.app is quite bad for this reason. 

I couldn't get it to save the password for the actual subdomain. Making the provider/issuer domain match the user domain *could* be possible, but it seemed like a bit of a hack and may violate even some OIDC rule. In this case the password would be saved for the correct domain though.

Anyway, let's ask again: would it be feasible to do the authentication to Penpot the same way as Jitsi does it? That is, I would just send the user to Penpot with jwt appended to the URL and that would take care of that?

**Comment by niwinz** [comment]
> Hi there again @niwinz,
> 
> There is one problem with moving from regular session based authentication to OIDC:
> 
> My app has a subdomain for each client -- they choose the subdomain when registering. The app is Aamu.app and subdomain could be ile.aamu.app.
> 
> Now, when they log in, the password will get saved for that subdomain in the browser. When I'm using OIDC, I think I have to choose a domain for that authentication provider -- like auth.aamu.app. As I log in, the password will get saved for that auth.aamu.app.

Looks strange, because the password should not be saved on the browser/domain. The password should be stored on the OIDC provider. When a user wants authenticate you redirect form APP_A to AUTH, auth verifies the user and redirects to APP_A, thats it and how it works.

If you look on design.penpot.app, and log with google per example, it redirects to google, autheticates and returns to design.penpot.app, it does not stores passwords on the google domain nor he penpot domain...

This is how a standard single sign on auth scheme works, and your case don't looks different.

> 
> The same user can have many subdomains (like in Slack). Saving the password at auth.aamu.app is quite bad for this reason.
> 
> I couldn't get it to save the password for the actual subdomain. Making the provider/issuer domain match the user domain _could_ be possible, but it seemed like a bit of a hack and may violate even some OIDC rule. In this case the password would be saved for the correct domain though.
> 
> Anyway, let's ask again: would it be feasible to do the authentication to Penpot the same way as Jitsi does it? That is, I would just send the user to Penpot with jwt appended to the URL and that would take care of that?

I don't know how jitsti works but, generating jWT token on thrirdparty on behalf of the service and sending it on URL is a bug security issue (unless I'm misunderstanding).

**Comment by ile** [comment]
I think I didn't explain it clearly:

When I click "Login to the site", there will be the username and password fields, at `auth.aamu.app`. I have made it so that I can login with username and password.

So I will enter those, OIDC will confirm that they are good and it takes me forward, something like this:

```javascript
const accountId = getUserAccount(...);

const grant = new provider.Grant({
  accountId,
  clientId: params.client_id,
});

grant.addOIDCScope(['openid', 'profile'].join(' '));

const grantId = await grant.save();
const result = {
  consent: { grantId },
  login: {
    accountId,
  },
};

await provider.interactionFinished(req, res, result, { mergeWithLastSubmission: false });
```

So now it forwards me back to `ile.aamu.app`. At this point the browser asks me if I want to save the username and password to the browser's password store. Which I do, but the site will be `auth.aamu.app` and not `ile.aamu.app` that they were stored for.

So I could host the OIDC provider at each subdomain, but it looked like I would have to do modify source code in a couple of package to make this possible (there are checks for "issuer" in here for example: https://openid.net/specs/openid-connect-basic-1_0.html#IDTokenValidation ... The 1.)

> I don't know how jitsti works but, generating jWT token on thrirdparty on behalf of the service and sending it on URL is a bug security issue (unless I'm misunderstanding).

Actually LiveKit (which is similar to Jitsi -- they are both WebRTC video calling software) works the same way: https://docs.livekit.io/concepts/authentication/#overview

So you create a jwt key, sign it with a secret and pass that jwt to the url where the video call will be happening. Which then can retrieve the profile data for that particular video call.

**Comment by ile** [comment]
Sorry to bother again, but do you think this could be possible?

Maybe the whole process*) could be done with this package: https://github.com/auth0/node-jsonwebtoken

It would be a lot simpler to integrate Penpot to an app than using OIDC (for example). OIDC seems to be quite hard/come with problems.

There are at least two big software (LiveKit & Jitsi) that use this method so I suppose it works fine.

*) 
- encrypting/decrypting profile data
- ie. creating the jwt key
- ie. doing authentication/authorization

**Comment by niwinz** [comment]
Sorry but I still not understand clearly what exactly penpot need to do. And honestly I didn't have time for look on it a bit deeper.

Right now, penpot session tokens are JWE tokens, that can be generated externally if you know the secret key of your penpot instance. I'mean there are nothing in penpot that prevens you generate an token externally if the both parts has the private key. I can give you hints on how it can be done if you are not comfortable on reading clojure code.

On the other hand, accepting token on URL is not an option from penpot side, if other does that is not enough to convince us to change is, passing auth token on URL has known security issues.

**Comment by ile** [comment]
Generating a JWE token would work fine, as I would be running Penpot on the same domain as the other app. So the token would be in the session.

I actually tried to go this path already - I tried to look at OIDC generating code, but that was a bit complicated. 

Any pointers would be greatly appreciated!

**Comment by ile** [comment]
I found the functions in `app.tokens` -- they are probably enough to get forward.

**Comment by ile** [comment]
Hey again @niwinz!

Just to say that setting the cookie `auth-token` isn't probably enough. I seem to have to also write a corresponding row to the `http_session` table, i.e. in effect to log the user in.

I can do that, but just to say that this is getting a bit more complicated... :)

**Comment by ile** [comment]
With a lot of help from ChatGPT I finally did it. :tada: 

Turns out ChatGPT is pretty good at Clojure.

I don't want to go into details, as I'm sure I cut some corners.
