### ISSUE TITLE
How do I contribute to the Penpot UI?

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3158]
I have ideas for improvements to the interface, and I want to contribute, but not what I should do.

 If I should create an interface send it here, if I should speak directly with the UI team to see what has already been done and suggest improvements.

**Comment by elhombretecla** [comment]
Hi @allytiago! Thank you for reaching out and expressing your interest in contributing to our project! We are truly honored and proud to have you collaborate with us. Your ideas and suggestions for improvements to the interface are most welcome.

The best way to share your ideas with our design team is by visiting our community platform at https://community.penpot.app/. There, you can engage in discussions, share your suggestions, and even view what has already been done by others. Our design team actively monitors this platform and will respond to your contributions as soon as possible.
