### ISSUE TITLE
bug: The Brazilian Portuguese language is not being enabled

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3159]
### Steps To Reproduce

1. Go to profile
2. Settings
3. Languages

### Expected behavior

The expectation is that when you select the option, the site changes to Brazilian Portuguese and not to Portuguese.  But the site remains in Portuguese from Portugal, changing only a few words.

### Actual behavior

What I noticed is that choosing one or the other, the site does not change the language 100%, just a few specific words and the rest remains in the pt-pt pattern instead of pt-br.

 I went to look at the weblate to understand what was going on and I noticed that the translations into Brazilian Portuguese are correct, but it is not applied on the website.  I noticed that words that were in pt-br before penpot left beta are simply in pt-pt

**Comment by myfunnyandy** [comment]
Closing this as the language is already published.
