### ISSUE TITLE
bug: Typography - random loosing connection with definitions

### ISSUE THREAD

**Issue by SatarisGIT** [uxbox/uxbox#3162]
### Steps To Reproduce

Hello! I've spotted problem which has been haunting me for about 2 months now, but unfortunately I cannot spot way to reproduce it.

1. Create text
2. Set predefined typography to this text
3. ??? ??? ???
4. Click on text and you will see there is correct font size, variant, line height, letter spacing etc. but there is no connection with typography.

### Expected behavior

There is connection between text and typography. If I change main typography settings, it will propagate to all texts using this typography

### Actual behavior

Randomly lost connection between typogreaphy definitions nad texts

### Desktop (please complete the following information)

Windows 11, 
Chrome 112.0.5615.138

### Environment (please complete the following information)

- Host - https://design.penpot.app

**Comment by EvaMarco** [comment]
Hi @SatarisGIT 
I'll keep an eye on those typefaces.
But in the meantime:
Do you have any file, that you can share, with that problem?
Does it happen with all types of fonts or maybe with some custom one?
Is the typography imported from a library?
Thanks

**Comment by SatarisGIT** [comment]
But in the meantime:
*Do you have any file, that you can share, with that problem?: *No, I don't
know when this happening
*Does it happen with all types of fonts or maybe with some custom one?: *With
all, randomly
*Is the typography imported from a library?: * Yes, this is imported typo
from library prepared by me, grouping all typos for all projects

śr., 3 maj 2023 o 15:37 Eva Marco ***@***.***> napisał(a):

**Comment by EvaMarco** [comment]
Did you modify the library file? the one with the typographies?

**Comment by SatarisGIT** [comment]
No, when I spotted this problem, my typo lib file was not modified

czw., 4 maj 2023 o 14:09 Eva Marco ***@***.***> napisał(a):

**Comment by SatarisGIT** [comment]
I've update app to latest version - problem still occurring. One day I click on my text and see fill color as some pre-defined (for example 'gray-700') and another day it spontaneously changes on its own to '#616161'

**Comment by EvaMarco** [comment]
Hello @SatarisGIT I'm sorry to hear this is still happening, I have created an issue about your problem, you can check it [here](https://tree.taiga.io/project/penpot/issue/5939).

**Comment by SatarisGIT** [comment]
Thank you for your response.
Additionally, I will add that I switch from cloud app version, to
self-hosted. Problem still occurring.

czw., 5 paź 2023 o 10:25 Eva Marco ***@***.***> napisał(a):

**Comment by EvaMarco** [comment]
I will update the issue with this info, and I have asked all the team if this has happened to them. Waiting for answers

**Comment by madalenapmelo-kp** [comment]
Hi @SatarisGIT,

I just wanted to let you know that we are introducing many changes related to Assets management in Penpot 2.0, and we believe those changes should address this issue.

I'm closing this issue here but please reopen it if you continue to see it after the release of Penpot 2.0!
