### ISSUE TITLE
bug:  Perfomance with multiple shared library import

### ISSUE THREAD

**Issue by enieber** [uxbox/uxbox#3178]
### Steps To Reproduce

1. create new project
2. create board and add new text
3. add 2  library to proejct
4. use some items from library
5. edit text

### Expected behavior

the perfomance is good because no has many components in board

### Actual behavior

the performance is not good because to each change in board has one request to library

### Desktop (please complete the following information)

- OS linux nixos 22.1
- Browser firefox 111.0.1

### Environment (please complete the following information)

usign design.penpot.app

**Comment by EvaMarco** [comment]
Hi @enieber 
We are working non-stop trying to improve performance, and any feedback is very welcome.

Is the library you used a template? or maybe they were your own libraries?
Is the library too heavy or have too many assets?
Any information you can give us will be of great help.

**Comment by enieber** [comment]
The perfomance issue has because library with many icons:

![Screenshot 2023-05-07 at 15-42-56 Penpot Design Freedom for Teams](https://user-images.githubusercontent.com/7907068/236696639-e1086a94-e5d5-4580-a251-0a370878ee29.png)

![Screenshot 2023-05-07 at 15-44-04 Penpot Design Freedom for Teams](https://user-images.githubusercontent.com/7907068/236696633-4d995e5e-a2be-4914-879f-b20be3dbab7a.png)

**Comment by SatarisGIT** [comment]
Spotted the same problem.

**Comment by EvaMarco** [comment]
Hi @SatarisGIT 
Sorry for the inconvenience
We have encountered some issues with the material design template, and we are trying to fix it. Stay tuned!
And thanks for the info.
