### ISSUE TITLE
bug: manually created shape has no fill

### ISSUE THREAD

**Issue by keunes** [uxbox/uxbox#3182]
### Steps To Reproduce

1. Open the attached penpot file, with elements created a long time (couple of versions) ago

### Expected behavior

The manually drawn shape 'Contrib graph' has no fill.

### Actual behavior

The shape does have a fill.

### Screenshots or video

By chance I double-clicked the shape and saw that something's off with the nodes (?). Moving them made the fill visible at some points.

https://user-images.githubusercontent.com/11229646/235526345-af1666f0-6a9e-4bee-9935-995f09c1e6fe.mp4

This is a crop-out of an export from feb '22 (a year ago), showing what the shape looked like before:
![Homepage redesign (copy)](https://user-images.githubusercontent.com/11229646/235526607-dc75f5a5-07e8-48ee-804c-df91b5f46b26.png)

### Desktop (please complete the following information)

Chromium Version 112.0.5615.49 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

### Environment (please complete the following information)

design.penpot.app

### Additional context

Here's the penpot file: [AntennaPod website.zip](https://github.com/penpot/penpot/files/11367912/AntennaPod.website.zip) (zipped because GitHub doesn't accept .penpot files)

**Comment by EvaMarco** [comment]
Hi @keunes:
I will go through the file and try to find the problem with that path. I'll let you know my findings.

**Comment by EvaMarco** [comment]
Hello again @keunes 
Thanks to the problem you reported we have found a bug related to paths and we are going to fix it. 
I have tried to fix your path as best as I could, let me know if it is ok for you.
[AntennaPod website.zip](https://github.com/penpot/penpot/files/11382623/AntennaPod.website.zip)
