### ISSUE TITLE
bug: "show fill in export" not working?

### ISSUE THREAD

**Issue by felixsanz** [uxbox/uxbox#3183]
### Steps To Reproduce

I have a board and i'm unchecking "show in exports" in the fill section, but the resulted exported svg contains it:

```
<g class="fills" id="fills-ea361042-f31e-802e-8002-71afce1c0c0f"><rect rx="0" ry="0" x="0.5000000000003411" y="0" transform="matrix(1.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000)" width="703.9999999999993" height="128.00000000000068" class="frame-background"/></g>
```

this option stopped working? It always export fills no matter what i do. I tried both global export from the menu and the little option in the right sidebar

### Expected behavior

No background if option is unchecked

### Actual behavior

Background is always exported in SVG export

**Comment by EvaMarco** [comment]
Hello @felixsanz 
In order to reproduce your error I need a bit more information. 
Are you trying to export just the shape, in what format (I'm guessing as SVG, but just to be sure)?
Or maybe you are trying to export as pdf?
Is the board empty?

**Comment by felixsanz** [comment]
> Hello @felixsanz In order to reproduce your error I need a bit more information. Are you trying to export just the shape, in what format (I'm guessing as SVG, but just to be sure)? Or maybe you are trying to export as pdf? Is the board empty?

Hi there! I'm trying to export the board in SVG format. Board is not empty. Imagine a board with 2 jpgs inside.

I just found this is not a penpot issue while trying to reproduce it (or maybe it is?)

When I export the SVG and open it in gimp, it is indeed transparent. No fill **COLOR** was exported, but the board dimmensions are exported in a `<rect>`.

Because of this, if you embed the SVG in a website, the browser interprets this is a background and sets *always* a black background (even if inside penpot the board fill color is red).

Outcome:

### Penpot (disable fill export)

![1683125506](https://user-images.githubusercontent.com/6182099/235953484-5df71792-4e50-400f-8e75-4a8ee96c8b63.png)

### gimp (it is indeed transparent)

![1683125516](https://user-images.githubusercontent.com/6182099/235953565-be4f5707-20ab-482f-adc3-9a5354c0d8f0.png)

### Browser (it always has a black background!)

![1683125527](https://user-images.githubusercontent.com/6182099/235953601-6fcf6f2a-8fe4-4c85-a6ff-7c03cbc155fc.png)

---

Should penpot remove that `<g class="fills"><rect ....` in the export when `fill export` is unchecked? Or totally legit since it can have stroke or many other options and that *layer* should be always exported? If that's the case... any idea what's going on with the browser or how to avoid it without manually editing every exported SVG?

Gracias vecina :P

**Comment by EvaMarco** [comment]
Hola vecino¡ :)
I will talk to the team and discuss it. Tomorrow I'll let you know what's going on. 
Thank you very much for your help

**Comment by superalex** [comment]
Hmmmmm,

I'm doing a similar test :

![1](https://user-images.githubusercontent.com/1579633/236153147-c56466d8-63cd-4bfd-9981-700e6ec758f4.png)

And using chrome and firefox I see no brackground:

![1](https://user-images.githubusercontent.com/1579633/236153322-69a88920-9084-4c4c-9db4-b38b0c6aeb46.png)

And embedding it directly in a html

![Uploading 1.png…]()
 

How are you opening those svgs and with what browsers and versions?

**Comment by felixsanz** [comment]
Damn, i'm sorry! I thought it was a penpot issue because I was using a black background for my board (not red), and I was seeing the black background in the website, so I thought it was penpot exporting it.

But now it's clearly not an issue with penpot, but how i'm inserting the SVG in the website with an `<Image>` component that forgets to add the `fill="none"` to the `<sgv>` tag that was present in penpot.

That's the key! Anyway I was workarounding this removing the layer with: `svg.replaceAll(/<g class="fills">.*?<\/g>/g, '')`, so that also fixes it in my case and also saves some bytes! (But I admit in other cases it will probably break something).

Again.. sorry for opening the issue and thanks for the help!
