### ISSUE TITLE
feature: Corner radius for curve points.

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3198]
### Is your feature request related to a problem? Please describe.

Recently I had to create an object using the path tool because the object involved more than one edge and eventually I would have to round it to match the project style, but when I went to do it, the penpot didn't have the function and I ended up having to I resorted to figma, which I created the element, I rounded the points using figma and when I was finished, I copied the object and pasted it into the penpot that imported the svg already with the rounding.

### Describe the solution you'd like.

The solution to the problem is to add the corner radius option (which the penpot currently has for rectangles) in the path tool, which can be used on the points individually or as a whole

### Describe alternatives you've considered.

As the Penpot still doesn't have the function, I see it as a suggestion to use the option present in Figma and even Inkscape as a base.

### Additional context

Figma
![image](https://user-images.githubusercontent.com/47113005/236984868-5b3f1c7e-b9d3-4aea-914a-4a058921131c.png)
Using the corner radius
![image](https://user-images.githubusercontent.com/47113005/236985144-fc6c5a04-07b4-4ccb-923a-8a4fe572c38e.png)
---

Penpot
![image](https://user-images.githubusercontent.com/47113005/236985521-845f55b7-25ac-4844-ab5d-caa4996f0472.png)
![image](https://user-images.githubusercontent.com/47113005/236985540-bf2237c1-6b7c-49d2-8c1f-935de2579636.png)
---

### How the object I created should look
![image](https://user-images.githubusercontent.com/47113005/236985916-538b30cd-cbbd-4919-ab60-3ebac92e82be.png)
> In figma I managed to do what was expected
![image](https://user-images.githubusercontent.com/47113005/236986016-547f1c0f-10ec-427f-a635-5824dd752102.png)

### How I didn't want it to stay
![image](https://user-images.githubusercontent.com/47113005/236986408-8ac560ca-88bf-4aa0-8eea-3b02f2f892a5.png)
![image](https://user-images.githubusercontent.com/47113005/236986430-6f36c703-7532-454e-8b0a-6f71a60cc27f.png)
---

It's true that this could be done using the curves in the path tool, but the penpot tool is still limited and even if it existed, it would take time that in some situations it would be more feasible to go to figma, create the object, copy the svg and paste in penpot.  Not everyone has the ability to use curves well and in cases of precision, it would be more laborious or unfeasible.

**Comment by Alotor** [comment]
Hi @allytiago ,

Thanks for your support. This enhancement is already in our backlog and it's even designed. We hope to start developing soon:

If you want to follow along this is it:

https://tree.taiga.io/project/penpot/us/3416?backlog-exclude_status=2076392,2501717&backlog-q=corner&no-milestone=1
