### ISSUE TITLE
feature: Coordinates for the path tool points

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3199]
### Is your feature request related to a problem? Please describe.

I went to get the coordinates of the points to make an object aligned to the point with greater precision and when I notice, I can't see the x and y positions of the specific point.

### Describe the solution you'd like.

When clicking on the point, there will be the option of coordinates as well as all objects that can be placed on the artboard

### Describe alternatives you've considered.

Demo in figma
![image](https://user-images.githubusercontent.com/47113005/236987864-42004224-a417-49b5-bf8f-26b321e5ee88.png)

How is it in the penpot
![image](https://user-images.githubusercontent.com/47113005/236987952-60020bde-454c-4cee-a62e-47996869726a.png)

**Comment by Alotor** [comment]
Hello @allytiago ,

The same US that have the rounded corners had this feature as well:

https://tree.taiga.io/project/penpot/us/3416?backlog-exclude_status=2076392,2501717&backlog-q=corner&no-milestone=1
