### ISSUE TITLE
feature:  plugin support

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3201]
### Is your feature request related to a problem? Please describe.

There are currently three options available in the penpot.  Either the object is a component, or you copy the svg directly on the website or download and import it into penpot

### Describe the solution you'd like.

The solution is to bring a tool that allows plugins to solve some functions, even simple ones, such as inserting an icon, emoji, illustration or even using type-scale.

### Additional context

You can even add plugins for these tools:
- https://phosphoricons.com/
- https://undraw.co/
- https://typescale.com/

If you want to create your own plugins.  I find it useful to create one based on the functions that these sites offer
- https://www.layoutgridcalculator.com/type-scale/
- https://www.fluid-type-scale.com/

**Comment by Alotor** [comment]
Hi @allytiago ,

Plugins are in our "short term" roadmap, we're already investigating how to add them into the platform. 

I'm going to close this as it's already planned but feel free to comment anything you want us to take into account.

Thanks!
