### ISSUE TITLE
bug: can not add an interaction on a text element 

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3205]
### Steps To Reproduce

I can not reproduce the bug all the time, but:

1. Create a Board 1 with a button nested in a flex layout
2. Create a flex layout containing a list of text elements. Turn it on a component
3. Add the component as a Board 2.
4. On a button of the Board 1, add an interaction to the Board 2, on "Toggle overlay" (basically, a dropdown action button)
5. Create a Board 3
6. On one of the text elements, try to add a interaction to Board 3.
7. The interaction panel is empty

### Expected behavior

I can add an interaction like on any other element.

### Actual behavior

The interaction panel is empty

### Page setup
Page:
![image](https://github.com/penpot/penpot/assets/62602652/ab46af33-efb3-46c6-ab49-6d8e8dcc95e1)

Tree:
![image](https://github.com/penpot/penpot/assets/62602652/b8b16b0d-9a65-483c-b4ce-019226f5b44c)

### Toggle

![image](https://github.com/penpot/penpot/assets/62602652/fe3f3c16-3837-4f10-8296-36bc5e52b646)

### No interaction

![image](https://github.com/penpot/penpot/assets/62602652/cdef4ba4-1094-43c6-99db-fc68dce2ef47)

### Desktop (please complete the following information)

Ubuntu 22.04
Chrome 113

### Additional context

Maybe related to the nested flex layouts?
The Group in the Action button was a test to bypass the bug, as it might have worked in the past. But the behavior is the same with or without it.

**Comment by Alotor** [comment]
Sorry @NicolasLeboeuf I'm not able to reproduce the error. Do you mind exporting the file and attaching the file here? or send us the exported file to support@penpot.app

Thanks

**Comment by NicolasLeboeuf** [comment]
The email is sent. It's even simpler than what I described, see the email.

Thanks for the quick response.

**Comment by pabloalba** [comment]
Hi! This is a difficult one... I've just created an issue in our Taiga to manage it: https://tree.taiga.io/project/penpot/issue/5307
