### ISSUE TITLE
About disk space

### ISSUE THREAD

**Issue by suiyueou** [uxbox/uxbox#3207]
Hi! Opened this issue just to ask if penpot does a periodic cleanup of attached files that have been uploaded but not referenced by any project or file for a long time, to optimize disk space.

**Comment by niwinz** [comment]
Hello @suiyueou yep, it does, but after some period of file inactivity. When file stays for 7 days of inactivity, this is right now hard-coded in the source, but we have a plan to make it configurable.

**Comment by suiyueou** [comment]
> Hello @suiyueou yep, it does, but after some period of file inactivity. When file stays for 7 days of inactivity, this is right now hard-coded in the source, but we have a plan to make it configurable.

I Get it! Thanks.
