### ISSUE TITLE
bug: SVG icon behave unexpected when duplicate

### ISSUE THREAD

**Issue by ondrejkonec** [uxbox/uxbox#3208]
### Steps To Reproduce

1. Create new Board
2. Go to https://tabler-icons.io/ for some free resources SVG icons
3. Paste icon and insert some text
4. Select section and duplicate using pressed `option key` (on MacOS)

### Expected behavior

SVG is duplicated as a new object.

### Actual behavior

SVG is not duplicated, it create only new shapes in SVG folder. When I want to select duplicated SVG, it looks like it's under one group.

### Screenshots or video

https://github.com/penpot/penpot/assets/28909808/d370979c-7678-4229-8761-8a269598f46f

### Desktop (please complete the following information)

MacOS Ventura 13.0
Chrome Version 112.0.5615.137 (Official Build) (arm64)

**Comment by Alotor** [comment]
Sorry @ondrejkonec i don't understand well what's the problem. The video seems to work fine.

When you press CMD the groups are "ignored" so you're selecting only the children from that group. When you duplicate the shapes the elements are duplicated within its parents. If you want to duplicate the whole thing you should select the group without the Cmd key.

**Comment by ondrejkonec** [comment]
Hey @Alotor sorry for misunderstanding. I hope I understand how it should be.

Situation:
When I click on SVG and then use option key for duplicate, it works and it duplicate the **whole SVG** (group and paths).

Problem is when I select multiple objects (texts + SVG's) and I try to do the same thing - duplicate this selected section. It's duplicated, but SVG root "folder" (on the left menu svg - see the screen below) is not and it copy only SVG paths and put this paths to the original "folder". 

Is it more clear? If not, I'll try to do it in another way.
![Screenshot 2023-05-12 at 13 57 29](https://github.com/penpot/penpot/assets/28909808/bee43b5f-b1a1-4473-b02d-87c83ae7fa15)

**Comment by ondrejkonec** [comment]
Here is what happened with SVG when I duplicate selection with SVG and text as you can see on video:

It does not duplicate the whole "svg folder", but only it's paths **into** original "svg folder"
![Screenshot 2023-05-12 at 14 00 36](https://github.com/penpot/penpot/assets/28909808/df491a7e-fbe9-4da0-a428-528cdebac93b)

**Comment by Alotor** [comment]
In the video you're selecting the children elements (probably because you're pulsing command). If you want to duplicate the whole svg folder you need to select first the folder (or not pulsing command)

**Comment by ondrejkonec** [comment]
@Alotor you are right. When I want to make selection, it select children path's. I was expecting that it will select the whole SVG object. So if it's not bug, can you please close it? 

I think that everything should be chosen (including 'svg folder') - but that's up to you. Thanks for the reply!

<img width="426" alt="Screenshot 2023-05-12 at 14 32 51" src="https://github.com/penpot/penpot/assets/28909808/d296ff0b-4064-416c-813c-36be07ea3d70">
