### ISSUE TITLE
bug: Autoparenting for flexbox too greedy; catching elements through layers

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#3210]
**Description:** Autoparenting for flexbox too greedy; catching even through layers on top of it. This leads to unexpected behavior – drag/dropped elements might "disappear" into a currently invisible or partly visible flexbox element and expected direct manipulation (elements usually stay where they are dropped) does not work. 

Credit: Bug was noticed by by [FREEZX](https://community.penpot.app/u/FREEZX) on discourse ([post](https://community.penpot.app/t/drag-move-object-changes-layout/3039)), I just reproduced it and report it here.

### Steps To Reproduce

1) Overlap a flexbox container (a) with another, non-flexbox board (b) on top (imagine an overlapping sidebar or palette-window over some content) 
2) Drag an element on the non-flexbox element. 

### Expected behavior

The element should become a child of the "top" non-flexbox container

### Actual behavior

The flexbox container is "greedy" across layers and will auto-parent any element dropped at its screen position, even if other elements overlap on top of it. 

### Screenshots or video

A video can be found here https://nextcloud.dark-1.com/s/CyNkCJQEFsksr4t which was posted by [FREEZX](https://community.penpot.app/u/FREEZX) on discourse ([post](https://community.penpot.app/t/drag-move-object-changes-layout/3039))

**Comment by FREEZX** [comment]
I would like to add that I think this behaviour is overall difficult to work with if it's the default as is currently the case. Positioning a sidebar on top of a full page list consisting of flexboxes is next to impossible.
I suggest changing it to work with a modifier key, or at least disable it with a modifier key

**Comment by mrcasio** [comment]
It would be fantastic if there was an option to disable the auto-parenting with a modifier key, allowing one to freely move an element without changing its position in the layer hierarchy. This feature would greatly enhance precision and control in layout management, especially in complex scenarios where elements need to be positioned accurately without inadvertently nesting them within the wrong container.

**Comment by madalenapmelo-kp** [comment]
Hi @jdittrich,

I was unable to reproduce this issue, could you let me know if you are still experiencing this? If so, would you be able to share a screen recording?

**Comment by markadrake** [comment]
I can't move an element around on the screen without the "auto parenting" feature. I tried every ctrl/alt/option/shift combination. This ticket should be reconsidered, please.

**Comment by madalenapmelo-kp** [comment]
Hi @markadrake,

Could you share a screen recording of this behavior so that we can take a look? Could you also confirm which browser you are using?

**Comment by mrcasio** [comment]
I’d like to confirm that the issues shown in the video still persist. When attempting to drag an element over a layout element, it continues to automatically become a child element, even though that’s not the intended behavior. It would be really helpful if there were an option to disable the auto-parenting via a modifier key, allowing for more precise layout management, especially when working with overlapping elements.

**Comment by madalenapmelo-kp** [comment]
@mrcasio could you share a screen recording of the issue? I still haven't been able to reproduce this so it would be really helpful to see the steps you are following

**Comment by jdittrich** [comment]
Reproduced in Firefox 130, Win11,Penpot 2.1. 
I can record it, but it looks like the video already existing.

**Comment by jdittrich** [comment]
@mrcasio:

> [suggestion:] disable the auto-parenting via a modifier key, allowing for more precise layout management, especially when working with overlapping elements.

Is there a common scenario where dropping on greedyly matching invisible elements is the wanted default behavior? I think that in most situations sticking with the  visual order makes sense, i.e. if I drop an element on another element, the hit check should starts in front, just like it is visuall represented.

**Comment by jdittrich** [comment]
Can also reproduce in edge.

**Comment by jdittrich** [comment]
Video of reproduction in Firefox: 
![greedyFlexboxPenpot](https://github.com/user-attachments/assets/59383897-4663-43a3-a17b-436fad3d17af)

(when not dragged over a flexbox, the green box is drawn on top of the gray rect)

**Comment by madalenapmelo-kp** [comment]
Hi @jdittrich,

Thanks for sending the recording! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8721

**Comment by madalenapmelo-kp** [comment]
Hi jdittrich,

The team has reviewed this issue and this is not something that we plan to address in the foreseeable future. You can find more about the motivations for this decision at the Taiga issue: https://tree.taiga.io/project/penpot/issue/8721

**Comment by jdittrich** [comment]
For context, the reason from Taiga: "We couldn't reproduce this issue. There are two most likely possibilities: either we've fixed it when solving a different bug, or it's something that happens with other Firefox versions (and the current one is working)"

@madalenapmelo-kp: I can still reproduce it on design.penpot.com (and me and other previously reproduced it also in edge/chromium). Is there any video of someone from the team reproducing it? Maybe we tried to do different things.

**Comment by Alotor** [comment]
@jdittrich I've been trying to reproduce it for a while, can you export a Penpot file with your example to see if there is something I'm missing? Thanks!

**Comment by Alotor** [comment]
Ok, sorry for the misunderstanding. I thought in your example that the gray square was a board.

The functionality is working as expected, the rectangle doesn't "hide" the board behind, I've checked with the designers and this behavior is indeed correct.

What we're going to do is add a visual cue on the board on which we're hovering so it's more explicit.

**Comment by jdittrich** [comment]
> The functionality is working as expected, the rectangle doesn't "hide" the board behind.

Okay, that makes this less of a programming bug but a usability issue, since the "what I see" and the "what happens" diverges. 

Is there an existing solution to the problem that @FREEZX posted about, e.g. putting a sidebar or popup on top of other, flexboxed elements? (Is it enough to put the popup or a sidebar on a board? If yes, is there any way that users can find out about it?)

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!

**Comment by mrcasio** [comment]
awesome. it works :) thank you!
