### ISSUE TITLE
bug: Zooming while color picker breaks UI

### ISSUE THREAD

**Issue by Applicafroguy** [uxbox/uxbox#3214]
### Steps To Reproduce

1. Select the Eyedropper Tool.
2. Select the eyedropper
3. Zoom in on the area that contains the color you want to select
4. Click on the color with the Eyedropper Tool
5. Zoom out to see the entire canvas

### Expected behavior

Zoom in and pick a color with the Eyedropper Tool and then Zoom out to see the entire canvas

### Actual behavior

Zoom in and pick a color with the Eyedropper Tool and then Zoom out, the UI is missing

### Screenshots or video

[New File 5 - Penpot (2).webm](https://github.com/penpot/penpot/assets/17473507/26bc6fdd-3da0-467b-88d1-cf61887bddca)

### Desktop (please complete the following information)

**System**: 
MacBook Air Apple M1 (2020)
Ventura 13.0 (22A380)

**Browser**: 
Chrome Version 113.0.5672.92 (Official Build) (arm64)

### Environment (please complete the following information)

https://design.penpot.app/

### Additional context

Zooming and using the color picker, as soon as you select the desired color using the eyedropper the UI breaks.

**Comment by claragvinola** [comment]
Hi! We're going to fix this. You can follow the progress here: https://tree.taiga.io/project/penpot/issue/5271
Thank you for letting us know!

**Comment by superalex** [comment]
Hello @Applicafroguy 

This one should be fixed and deployed to https://design.penpot.app
