### ISSUE TITLE
feature: Hide bounding box when adjusting value

### ISSUE THREAD

**Issue by NusryNizam** [uxbox/uxbox#3232]
### Is your feature request related to a problem? Please describe.

The bounding box of a selected object makes it harder to see the output when changing a value.

### Describe the solution you'd like.

It would be great if the bounding box is hidden when adjusting a value in the right menu so we can see what exactly it looks like.

### Describe alternatives you've considered.

I like the approach of Figma where they hide the bounding box when making adjustments.  

### Additional context

https://github.com/penpot/penpot/assets/24385617/429712e4-9eaa-444e-85eb-9c6ca689fe45

https://github.com/penpot/penpot/assets/24385617/3178037c-dd66-4ee4-8e65-e93d05b447f2

**Comment by pabloalba** [comment]
Hi! That's a good idea!

I've just created an issue on our Taiga to do it: https://tree.taiga.io/project/penpot/issue/5309

**Comment by NusryNizam** [comment]
Awesome!

**Comment by pomydoro** [comment]
@pabloalba Hi I am interested in working on this issue as my first contibution to an open source project. Could you provide a bit more context into what should trigger hiding of the box? Should it be hidden all the time while the sizing box is activated by the user? Or should it be hidden for a time interval after the size of the element inside bounding box has been changed?

**Comment by myfunnyandy** [comment]
Hi @pomydoro, I've just added at [the story](https://tree.taiga.io/project/penpot/issue/5309) a paragraph briefly explaining the mechanics. I hope it's enough to start with, but please don't hesitate in asking for further details. Thanks!

**Comment by pomydoro** [comment]
@myfunnyandy thank you for the explanation in the story, I will definitely ask for further details when needed.

**Comment by gyanendra-baghel** [comment]
@pabloalba Hi I am interested in this issue as my first contibution to an open source project and I will be happy to get your guidance in this contribution.

**Comment by pabloalba** [comment]
Awesome! We have all the information to start here: https://help.penpot.app/contributing-guide/code-contributions/

Please ask any doubts here or on our community :)

**Comment by NusryNizam** [comment]
@niwinz @VasilevsVV  Thanks for making the adjustments. Is it possible to add this feature when modifying stroke sizes of objects?

**Comment by myfunnyandy** [comment]
@NusryNizam that makes a lot of sense. And, if we value consistency, not only for the strokes but for the rest of the design properties. I've created a [new issue](https://github.com/penpot/penpot/issues/4587) to keep this one closed and treat it as a separate enhancement.
