### ISSUE TITLE
bug: objects get moved in hidden / locked boards while dragged 

### ISSUE THREAD

**Issue by 72dpigraphics** [uxbox/uxbox#3233]
### Steps To Reproduce

While moving / dragging objects (Shapes, boards, text etc.) over a board / or nested board that is hidden and locked, the moved Elements get switched inside the hidden Board and also are invisible (because there now inside the hidden Board.

1. create a layout board
2. create a second board inside with a fill (for visibility)  
3. set the filled nested board to hidden and locked, in the layer panel
4. create a shape, text or board and drag it over the hidden board (like moving object while editing a layout)
5. the dragged objects now moved inside the hidden board 

### Expected behavior

Ignore hidden and / or locked boards for mouse-actions like dragging object over them, so the objects dont get rearranged inside the hidden board an just stay at there layer hierarchy

### Actual behavior

dragged objects get moved inside hidden / locked Boards

### Desktop (please complete the following information)

- MacOs
- Brave / Firefox

**Comment by pabloalba** [comment]
Thank you for the report!

I've just created an issue in our Taiga to fix it: https://tree.taiga.io/project/penpot/issue/5308

**Comment by soutiagojose** [comment]
I came to report the same problem, only in flex-layouts. Even blocked, I manage to add elements inside, an action that shouldn't happen. It also happened in the components.
