### ISSUE TITLE
bug: logging with ::l/raw doesn't seem to print anything

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3239]
### Steps To Reproduce

I was trying to get `enable-log-emails` to work. I got to the point where they were logged, but nothing appeared in the console.

I tracked the problem to `(l/info ::l/raw out)` which doesn't seem to print anything (well, it prints an empty logging line). The `::l/raw` seems to be the actual problem.

Didn't inspect further because Clojure got too complicated.

### Expected behavior

Should print the email.

### Actual behavior

Didn't print the email.

**Comment by niwinz** [comment]
Maybe there some bugs here, In any case I strongly recommend use a mail catcher service instead of logging emails to console.

**Comment by ile** [comment]
I will be disabling registration + SMTP. I will create the users with the API.

The bug itself is not serious of course, just wanted to tell about it.
