### ISSUE TITLE
feature: Effect backdrop blur

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3247]
### Is your feature request related to a problem? Please describe.

I went to create a menu that would have the backdrop-filter: blur effect to create a blur on the elements that are behind the menu, but when I tried to do that, I noticed that the penpot did not add the function.

### Describe the solution you'd like.

I saw that there is a blur option, but the one that exists is on the element itself and not on those behind the element.

What the penpot team can do:
In the existing option called blur, there are two options: the layer blur that is for the function that the app already has and the backdrop blur or background blur for the effect that I am requesting.  When the user chooses the type of effect, he will choose the value in px to reach the result.
The choice of options can be based on a selection function and next to it, the input to insert the value in px

### Additional context
The function is inspired by the css effect: `backdrop-filter: blur()` and the background blur function of figma:
- https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter
- https://help.figma.com/hc/en-us/articles/360041488473-Apply-shadow-or-blur-effects#background-blur

Lunacy and Sketch are the closest to what I mean the backdrop blur function and what comes closest to how the function is used on websites.  Using the blur+ saturation effect
- https://lunacy.docs.icons8.com/styling/#blurs
- https://www.sketch.com/docs/designing/styling/blurs/

**Comment by superalex** [comment]
Thank you very much @allytiago 

I think this request is similar to this https://github.com/penpot/penpot/issues/1185 and we also created it in Taiga to manage it https://tree.taiga.io/project/penpot/issue/2024. I'm including your comments there and closing this one.

Thanks!
