### ISSUE TITLE
bug: *32 open() "/opt/data/..." failed (13: Permission denied),

### ISSUE THREAD

**Issue by MrMK0R** [uxbox/uxbox#3256]
### Steps To Reproduce

1. Login to Penpot Front End
2. Open New Project (or existing)
3. Upload a Image

**Steps Tried to fix error:**
1. docker compose exec penpot-frontend chown -R penpot:penpot /opt/data/
2. docker compose exec penpot-frontend chmod -R 777 /opt/data/
3. sudo chown -R penpot:penpot /bucket/penpot/
4. sudo chmod -R 777 /bucket/penpot/

### Expected behavior

The image should display once uploaded

### Actual behavior

Image show outlines but no image displayed

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/112554159/8a2d1366-d258-4abe-837b-a301c28d4de7)

### Desktop (please complete the following information)

Windows 11
Edge (chromium)

### Environment (please complete the following information)

OS: Ubuntu 22.04LTS
Docker: Version 24.0.2, build cb74dfc
Docker Compose: Version v2.18.1

### Frontend Stack Trace

```console
penpot-penpot-frontend-1  | 172.20.0.1 - - [29/May/2023:08:00:10 +0000] "GET /ws/notifications?session-id=f47cc186-7b78-8039-8002-94e57b165ade HTTP/1.0" 400 130 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57"
penpot-penpot-frontend-1  | 172.20.0.1 - - [29/May/2023:08:00:12 +0000] "POST /api/rpc/command/upload-file-media-object HTTP/1.0" 200 345 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57"
penpot-penpot-frontend-1  | 2023/05/29 08:00:12 [error] 10#10: *32 open() "/opt/data/assets/44/fd/89570fdb4bb18e062caea322150d.gz" failed (13: Permission denied), client: 172.20.0.1, server: _, request: "GET /assets/by-file-media-id/09b5a1fb-1333-810e-8002-94e580762bce HTTP/1.0", upstream: "http://172.20.0.7:6060/assets/by-file-media-id/09b5a1fb-1333-810e-8002-94e580762bce", host: "website.here.io"
penpot-penpot-frontend-1  | 2023/05/29 08:00:12 [error] 10#10: *32 open() "/opt/data/assets/44/fd/89570fdb4bb18e062caea322150d" failed (13: Permission denied), client: 172.20.0.1, server: _, request: "GET /assets/by-file-media-id/09b5a1fb-1333-810e-8002-94e580762bce HTTP/1.0", upstream: "http://172.20.0.7:6060/assets/by-file-media-id/09b5a1fb-1333-810e-8002-94e580762bce", host: "website.here.io"
```

### Backend Stack Trace

```console
penpot-penpot-backend-1  | SUMMARY:
penpot-penpot-backend-1  |  →  java.nio.file.AccessDeniedException: /opt/data/assets/ca (UnixException.java:90)
penpot-penpot-backend-1  | DETAIL:
penpot-penpot-backend-1  |  →  java.nio.file.AccessDeniedException: /opt/data/assets/ca (UnixException.java:90)
penpot-penpot-backend-1  |     at: sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
penpot-penpot-backend-1  |         sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
penpot-penpot-backend-1  |         sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
penpot-penpot-backend-1  |         sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:313)
penpot-penpot-backend-1  |         java.nio.file.Files.createDirectories(Files.java:772)
penpot-penpot-backend-1  |         datoteka.fs$create_dir.invokeStatic(fs.clj:328)
penpot-penpot-backend-1  |         datoteka.fs$create_dir.invoke(fs.clj:321)
penpot-penpot-backend-1  |         datoteka.fs$create_dir.invokeStatic(fs.clj:323)
penpot-penpot-backend-1  |         datoteka.fs$create_dir.invoke(fs.clj:321)
penpot-penpot-backend-1  |         app.storage.fs$eval32956$fn__32959$fn__32962.invoke(fs.clj:64)
penpot-penpot-backend-1  |         promesa.exec$wrap_bindings$fn__5316.invoke(exec.cljc:163)
penpot-penpot-backend-1  |         promesa.util.Supplier.get(util.cljc:34)
penpot-penpot-backend-1  |         java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
penpot-penpot-backend-1  |         java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
penpot-penpot-backend-1  |         java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
penpot-penpot-backend-1  |         java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
penpot-penpot-backend-1  |         java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
penpot-penpot-backend-1  |         java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
penpot-penpot-backend-1  |         java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Additional context

There was a prior post of this in the reports #2876 which I followed and seemed to work for the backend. I can now download templates, however the issue is the frontend not wanting to accept or display images.

My local storage is "/bucket/penpot/" which is a S3 bucket.

**My volume points are**
Frontend
  volumes:
      - /bucket/penpot/frontend:/opt/data/assets

Backend
  volumes:
     - /bucket/penpot/backend:/opt/data/assets

_**PS.** This is my first ever post, I'm sorry if I'm missing any information but I really wanted to get into the opensource community._

**Comment by superalex** [comment]
Hi!,

I think the problem is you executed 
`docker compose exec penpot-frontend chown -R penpot:penpot /opt/data/`

but it should be:
`docker compose exec penpot-penpot-backend-1 chown -R penpot:penpot /opt/data/`

Could you please execute it and paste here the output?

**Comment by MrMK0R** [comment]
I definitely used docker instead of docker compose, however, this is the new logs I get.

`docker compose exec penpot-penpot-backend-1 chown -R penpot:penpot /opt/data/`
`service "penpot-penpot-backend-1" is not running container #1`

Running `docker compose ps` gives me:
![image](https://github.com/penpot/penpot/assets/112554159/02fc115e-a30c-4331-8692-9c980c8bdde0)

**Comment by superalex** [comment]
That output means the command wasn't correctly executed

Please try:
`docker exec penpot-penpot-backend-1 chown -R penpot:penpot /opt/data/`

**Comment by MrMK0R** [comment]
Here is the output. I tired a few other options as well in this output.

root@server:/apps/penpot# docker exec penpot-penpot-backend-1 chown -R penpot:penpot /opt/data/
chown: cannot access '/opt/data/assets': Permission denied
root@server:/apps/penpot# sudo docker exec penpot-penpot-backend-1 chown -R penpot:penpot /opt/data/
chown: cannot access '/opt/data/assets': Permission denied
root@server:/apps/penpot# sudo docker exec -u root penpot-penpot-backend-1 chown -R penpot:penpot /opt/data/
root@server:/apps/penpot# sudo docker exec -it root penpot-penpot-backend-1 /bin/bash
Error response from daemon: No such container: root
root@server:/apps/penpot# sudo docker exec -it penpot-penpot-backend-1 /bin/bash
penpot@9cecf412bd3d:~/backend$ cd /opt/data
penpot@9cecf412bd3d:/opt/data$ ls -l
ls: cannot access 'assets': Permission denied
total 0
d????????? ? ? ? ?            ? assets

![image](https://github.com/penpot/penpot/assets/112554159/fb344631-51f1-40b0-9f97-d1b67b750081)

**Comment by superalex** [comment]
Ok, one more, please: 

`docker exec  -u 0 penpot-penpot-backend-1 chown -R penpot:penpot /opt/data`

**Comment by MrMK0R** [comment]
I ended up deleting the image, container, and volume just to see if the issue was persistent on a new install.

Running the below and restarting the container didn't seem to fix the issue
`docker exec  -u 0 penpot-penpot-backend-1 chown -R penpot:penpot /opt/data`
`docker exec penpot-penpot-backend-1 chown -R penpot:penpot /opt/data/`

on #2876, at the bottom was posted
> This work perfectly. Just add this line for the sake of later people's convenience who use docker compose. In the docker compose folder (which has docker-compose.yml file) run: `docker compose exec -u root penpot-backend chown -R penpot:penpot /opt/data`

I decided to try the below with no luck.
`docker compose exec -u root penpot-frontend chown -R penpot:penpot /opt/data`
`docker compose exec  penpot-frontend chmod 777 /opt/data`
`docker compose exec -u root penpot-backend chown -R penpot:penpot /opt/data`
`docker compose exec  penpot-backend chmod 777 /opt/data`

Running `docker compose exec -it -u root  penpot-backend /bin/bash` then going to  /opt/data/assets with `ls -l` shows as 777
Running `docker compose exec -it -u penpot  penpot-backend /bin/bash` then going to /opt/data/assets with `ls -l` shows permission denied". The previous folder of /opt/ and /opt/data is accessible to the penpot user, just not assets.

I then decided to try the below with a container restart and no luck.
`docker compose exec -u root penpot-frontend chown -R penpot:penpot /opt/data/assets`
`docker compose exec  penpot-frontend chmod 777 /opt/data/assets`
`docker compose exec -u root penpot-backend chown -R penpot:penpot /opt/data/assets`
`docker compose exec  penpot-backend chmod 777 /opt/data/assets`

All the commands above input properly, however `docker compose exec  penpot-backend chmod 777 /opt/data/assets` gives off `chmod: cannot access '/opt/data/assets': Permission denied`

Going back to `docker compose exec -it -u root penpot-backend /bin/bash` shows the user folder is owned by "penpot:penpot".

**Comment by MrMK0R** [comment]
I've determined this only happens when you want to change the location of the data (from the container to the local file system).

When a fresh install using these lines in the docker-compose.yaml the uploading has no issues on both the front and back end of penpot.

```
penpot-frontend:
  volumes:
    penpot_assets:/opt/data/assets

penpot-backend:
  volumes:
    penpot_assets:/opt/data/assets` 
```

When you change these to a local folder such as
```
penpot-frontend:
  volumes:
    penpot_assets:/opt/data/assets

penpot-backend:
  volumes:
    /home/folder/outside/of/container:/opt/data/assets
```
the first error is encountered. To fix the first error, you will use:
`docker exec -u 0 penpot-penpot-backend-1 chown penpot:penpot /opt/data`
`docker exec -u 0 penpot-penpot-backend-1 chmod -r 777 /opt/data`

After this change, you can now download templates with no error. When creating a new project however, you cannot upload images. Using the commands:
`docker exec -u 0 penpot-penpot-frontend-1 chown penpot:penpot /opt/data`
`docker exec -u 0 penpot-penpot-frontend-1 chmod -r 777 /opt/data`
the front end allows uploads, but does not preview the images. You will see the following happen if you try to upload a file.
![241683448-8a2d1366-d258-4abe-837b-a301c28d4de7](https://github.com/penpot/penpot/assets/112554159/a65a2993-0945-4500-b5fb-83261817e936)

I have tried to solve the issue of the file not wanting to be displayed, however I cannot seem to figure out what the issue is. I hope this helps with troubleshooting the docker install a bit more.

**Comment by niwinz** [comment]
You should have the same value for the both volume mounts.

With the following config (copy paste of your config)
```yaml
penpot-frontend:
  volumes:
    penpot_assets:/opt/data/assets

penpot-backend:
  volumes:
    /home/folder/outside/of/container:/opt/data/assets
```

You can upload, but you can't see it, because frontend can't access the files.

That should looks something like this:


```yaml
penpot-frontend:
  volumes:
    /home/folder/outside/of/container:/opt/data/assets

penpot-backend:
  volumes:
    /home/folder/outside/of/container:/opt/data/assets
```

**Comment by MrMK0R** [comment]
Starting again from a brand new container (deleted previous ones), I've attached my data points as follows
![image](https://github.com/penpot/penpot/assets/112554159/b78dc94e-c72d-430c-96f3-ba047b85f3cb)
![image](https://github.com/penpot/penpot/assets/112554159/accd28ab-c4df-417c-9b10-321e91664c22)

Upon trying to download a template, I get this error:
![image](https://github.com/penpot/penpot/assets/112554159/69daebd0-ff94-4d8a-a75d-aeeb6134d7fe)

I then run :
`docker exec  -u 0 penpot-penpot-backend-1 chown -R penpot:penpot /opt/data` and restart the container. The error seems to persist.


The backend error is
`[2023-06-27 22:51:13.784] E app.http.errors - hint="Unexpected error", message="/opt/data/assets/b5"
SUMMARY:
 →  java.nio.file.AccessDeniedException: /opt/data/assets/b5 (UnixException.java:90)
DETAIL:
 →  java.nio.file.AccessDeniedException: /opt/data/assets/b5 (UnixException.java:90)
    at: sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:313)
        java.nio.file.Files.createDirectories(Files.java:772)
        datoteka.fs$create_dir.invokeStatic(fs.clj:328)
        datoteka.fs$create_dir.invoke(fs.clj:321)
        datoteka.fs$create_dir.invokeStatic(fs.clj:323)
        datoteka.fs$create_dir.invoke(fs.clj:321)
        app.storage.fs$eval32956$fn__32959$fn__32962.invoke(fs.clj:64)
        promesa.exec$wrap_bindings$fn__5316.invoke(exec.cljc:163)
        promesa.util.Supplier.get(util.cljc:34)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`

Since none of the above worked, I tried (docker compose instead)
`docker compose exec -u root penpot-backend chown -R penpot:penpot /opt/data/assets` and again restart the container. The error in the backend ends up being the same.

**Comment by AllenCHM** [comment]
I successfully set up and restarted the Docker instance, but still reported an error.

Set Results
```Shell
# docker exec -it -u 0 penpot_penpot-backend_1 /bin/bash
root@88e8e7aad274:/opt/penpot/backend# cd /opt/data/
root@88e8e7aad274:/opt/data# ls -lh
total 4.0K
drwxrwxrwx 2 penpot penpot 4.0K Jul 23 12:57 assets
```

Request Record
```
penpot-frontend_1   | 192.168.2.1 - - [23/Jul/2023:13:37:19 +0000] "POST /api/rpc/command/update-file HTTP/1.1" 200 234 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
penpot-frontend_1   | 192.168.2.1 - - [23/Jul/2023:13:37:23 +0000] "POST /api/rpc/command/upload-file-media-object HTTP/1.1" 200 259 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
penpot-frontend_1   | 2023/07/23 13:37:23 [error] 8#8: *73 open() "/opt/data/assets/1f/4c/2ec1be8249ae9a4c88c751061ed9" failed (2: No such file or directory), client: 192.168.2.1, server: _, request: "GET /assets/by-file-media-id/c7c0c4a5-2c57-80e3-8002-dc021dcfaac4 HTTP/1.1", upstream: "http://172.31.0.6:6060/assets/by-file-media-id/c7c0c4a5-2c57-80e3-8002-dc021dcfaac4", host: "192.168.2.213"
penpot-frontend_1   | 192.168.2.1 - - [23/Jul/2023:13:37:23 +0000] "GET /assets/by-file-media-id/c7c0c4a5-2c57-80e3-8002-dc021dcfaac4 HTTP/1.1" 404 178 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
penpot-frontend_1   | 192.168.2.1 - - [23/Jul/2023:13:37:23 +0000] "POST /api/rpc/command/update-file HTTP/1.1" 200 517 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
```


My operating system is ubuntu.
Penpot is the latest version.

**Comment by parasiteoflife** [comment]
I'm facing the same problem with local filesystem instead of docker volumes.
running `docker exec  -u 0 penpot-penpot-backend-1 chown -R penpot:penpot /opt/data` worked for me but still would be great not to have to run extra commands

**Comment by ruslan-mogilevskiy** [comment]
Why this issue was closed as it wasn't fixed up until the present time?
The issue is still present on a fresh installation because the penpot user doesn't have access to the /opt/data/assets folder when a docker host's folder is attached to the /opt/data/assets volume both for FE/BE:

```
ls -la /opt/data/
drwxr-xr-x 3 penpot penpot 4096 Sep  5 16:02 .
drwxr-xr-x 1 root   root   4096 Sep  5 16:02 ..
drwxr-xr-x 2 root   root   4096 Sep 25 19:54 assets
```

**Comment by avks** [comment]
Yes, the problem is still there. Running `docker exec  -u 0 penpot-penpot-backend-1 chown -R penpot:penpot /opt/data` did not, in my case, solve the issue.

**Comment by dynnian** [comment]
Encountered this issue when deploying my instance recently, I did this from the host system:
`chown -R 1001:1001 /home/path/to/data`

This because I saw that the penpot user in the container is UID 1001 inside the container with:
`docker exec -it penpot-backend cat /etc/passwd | grep penpot`

Everything seems to work just fine with this.
