### ISSUE TITLE
bug:  dragging to clone a board makes the app to crash

### ISSUE THREAD

**Issue by isaaacme** [uxbox/uxbox#3257]
### Steps To Reproduce

1. click on board
2. use command + dragging the board to clone

### Expected behavior

a new copy of the board should appear where i let go of the board 

### Actual behavior

the app crashes

### Screenshots or video

![chrome-capture-2023-4-29](https://github.com/penpot/penpot/assets/11567781/cc146d65-e734-4eb5-977b-9513411f9a21)

### Desktop (please complete the following information)

mac os ventura 13.3.1 
chrome Version 113.0.5672.126 (Official Build) (arm64)

**Comment by superalex** [comment]
Hello @isaaacme 

May be something is wrong with the file, if it's hosted in [penpot.app](https://design.penpot.app/) could you please include the url?

**Comment by isaaacme** [comment]
> Hello @isaaacme
> 
> May be something is wrong with the file, if it's hosted in [penpot.app](https://design.penpot.app/) could you please include the url?

yes on the penpot app -> https://design.penpot.app/#/workspace/e8678d30-3fbe-11ed-b414-cf2300df1f4f/88d87192-d205-8007-8002-8f1ff81214f2?page-id=88d87192-d205-8007-8002-8f1ff81214f3

**Comment by superalex** [comment]
Thank you very much @isaaacme 

I think I found the error, it's related to some color assets with invalid values. Do you remember how you created the file or those assets?, did you do something special?

**Comment by isaaacme** [comment]
no, did it all from scratch

**Comment by superalex** [comment]
Thanks @isaaacme 

One more question, did you create those assets this way?


https://github.com/penpot/penpot/assets/1579633/2b7f8618-c7ba-4afb-bdf9-d5dfa9dc4fbb

**Comment by isaaacme** [comment]
no just using the plus icon in the color palette

**Comment by superalex** [comment]
This way?


https://github.com/penpot/penpot/assets/1579633/e5e0c043-8e27-481f-928c-98d95a3e8177

**Comment by isaaacme** [comment]
yep

**Comment by superalex** [comment]
Thank you very much @isaaacme 

I'm trying to find what can be producing the bug and fix it.

as a workaround you could temporary remove the fill from the frame you are duplicating (and setting it again after doing it). Sorry for the inconvenience

**Comment by isaaacme** [comment]
thats ok thank you for taking the time , just updating: it works, but moving the artboard "on top" of a board with a gradient it crashes again

**Comment by superalex** [comment]
You are welcome!

The problem is that gradient, for some reason it's using invalid color assets (some of them have invalid opacity values) and that make penpot crash because the data validation fails. I'm still trying to find the best way to solve the problem.

**Comment by superalex** [comment]
Hello @isaaacme 

Thank you very much for your, I fixed the issue and deployed it some minutes ago. Your file should be working ok now ;)

**Comment by isaaacme** [comment]
![image](https://github.com/penpot/penpot/assets/11567781/92f12950-b066-4949-be88-040c0c7c3439)
