### ISSUE TITLE
bug: Persistent Performance Issues and Frequent Freezing in Penpot UI Design Software

### ISSUE THREAD

**Issue by jonathan-matheus** [uxbox/uxbox#3271]
### Steps To Reproduce

The issue occurs consistently during normal usage, irrespective of specific actions or file sizes. It affects both new projects and existing ones.

### Expected behavior

It was expected that the software does not crash

### Actual behavior

While using Penpot, the software experiences frequent small freezes and performance slowdowns, hindering my workflow and causing frustration.

### Environment (please complete the following information)

- OS: Fedora Linux 38 (Workstation Edition) x86_64 
- Kernel: 6.2.9-300.fc38.x86_64
- DE: GNOME 44.1 
- CPU: Intel i7-3770 (8) @ 3.900GHz
- GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
- Memory: 3739MiB / 7881MiB

**Comment by jonathan-matheus** [comment]
I deleted some images from the project, and it went back to working normally, apparently the error occurs when there are many images or very large images in the project.

**Comment by EsterLatorre** [comment]
Hello Jonathan,
Sorry for the late response. As you mention, this might be due to the large images. We are working on optimizing performance, and this is an ongoing priority for us, so hopefully it will work more smoothly soon.
Thanks for your message

**Comment by madalenapmelo-kp** [comment]
Hi @jonathan-matheus,

Could you please confirm if you continue to experience this behavior?

**Comment by jonathan-matheus** [comment]
Unfortunately, I haven't been using Penpot since the day I reported this issue here. However, I plan to test the software again on a personal project. If the problem has been resolved, I'll start using it in production and will inform here.

**Comment by madalenapmelo-kp** [comment]
Thank you for letting me know! In that case, I'm closing this issue here but please open a new one if you see this behavior when you start working with Penpot again :slightly_smiling_face:
