### ISSUE TITLE
bug: slashes in board name cause directories to be created in zip export

### ISSUE THREAD

**Issue by networkException** [uxbox/uxbox#3276]
### Steps To Reproduce

1. Create at least two boards
2. Name one of them "Something / something" or even "Something / ../../../something"
3. Select both boards
4. Use Export Selection (with type PDF) to export both boards as a ZIP archive

### Expected behavior

The zip file should contain both slides as PDFs with the proper names set

### Actual behavior

THe zip file contains directories

### Desktop (please complete the following information)

- Chromium 113.0.5672.93

### Environment (please complete the following information)

- Ubuntu 22.04
- Docker Compose
- Penpot 1.18.3

**Comment by superalex** [comment]
Thank you very much for the report.

I've just added https://tree.taiga.io/project/penpot/issue/5423 to manage it, I hope we can fix it soon.
