### ISSUE TITLE
code :unable-to-auth, :hint "not enough permissions"

### ISSUE THREAD

**Issue by Shree08-io** [uxbox/uxbox#3278]
When I login with openID I am redirecting to provider, after successful login it is redirecting to penpot URL with error not enough permissions. 

I have configured below env in docker compose file for backend
```
      - PENPOT_OIDC_CLIENT_ID=<client ID>
      - PENPOT_OIDC_BASE_URI=https://<keyclaok-url>/auth/realms/<realm-name>
      - PENPOT_OIDC_CLIENT_SECRET=<secret>
      - PENPOT_OIDC_AUTH_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/auth
      - PENPOT_OIDC_TOKEN_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/token
      - PENPOT_OIDC_USER_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/userinfo
      - PENPOT_OIDC_ROLES=penpot_user
      - PENPOT_OIDC_ROLES_ATTR=roles
      ## - PENPOT_OIDC_EMAIL_ATTR=email
      - PENPOT_OIDC_NAME_ATTR=username
```
additionally when I use below configuration getting error **incomplete userinfo**
Conf:
      - PENPOT_OIDC_EMAIL_ATTR=attributes__email
      - PENPOT_OIDC_NAME_ATTR=attributes__name

Output
```
dt: {:type :internal,
penpot-penpot-backend-1    |          :code :incomplete-user-info,
penpot-penpot-backend-1    |          :hint "inconmplete user info",
penpot-penpot-backend-1    |          :info {:backend "oidc",
penpot-penpot-backend-1    |                 :fullname nil,
penpot-penpot-backend-1    |                 :email nil,
penpot-penpot-backend-1    |                 :props {:oidc/given_name "John",
penpot-penpot-backend-1    |                         :oidc/email "johnd@example.com",
penpot-penpot-backend-1    |                         :oidc/sub "sec-sub",
penpot-penpot-backend-1    |                         :oidc/name "John D",
penpot-penpot-backend-1    |                         :oidc/email_verified true,
penpot-penpot-backend-1    |                         :oidc/family_name "D",
penpot-penpot-backend-1    |                         :oidc/preferred_username "johnd@example.com"}}}
```

can anyone help me fix this.

Thank you

**Comment by niwinz** [comment]
hello @Shree08-io 

Looks like you are declaring expected roles, when the response from the OIDC provider does not provides it. So in this case it raises **no enough permissions** as expected, as solution to that problem is: remove roles related configuration or configure your OICD provider to properly provide roles attr on the user-info response.

With later config change are making the configuration more incorrect it because the defaults are already correct for your use case but you change it for incorrect ones.

Lets try with this simple config, I mean, without additional configuration:
```
      - PENPOT_OIDC_CLIENT_ID=<client ID>
      - PENPOT_OIDC_BASE_URI=https://<keyclaok-url>/auth/realms/<realm-name>
      - PENPOT_OIDC_CLIENT_SECRET=<secret>
      - PENPOT_OIDC_AUTH_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/auth
      - PENPOT_OIDC_TOKEN_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/token
      - PENPOT_OIDC_USER_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/userinfo````
```

**Comment by Shree08-io** [comment]
@niwinz Thank you for your quick response and solution, I will try with above config.
:)

**Comment by Shree08-io** [comment]
> hello @Shree08-io
> 
> Looks like you are declaring expected roles, when the response from the OIDC provider does not provides it. So in this case it raises **no enough permissions** as expected, as solution to that problem is: remove roles related configuration or configure your OICD provider to properly provide roles attr on the user-info response.
> 
> With later config change are making the configuration more incorrect it because the defaults are already correct for your use case but you change it for incorrect ones.
> 
> Lets try with this simple config, I mean, without additional configuration:
> 
> ```
>       - PENPOT_OIDC_CLIENT_ID=<client ID>
>       - PENPOT_OIDC_BASE_URI=https://<keyclaok-url>/auth/realms/<realm-name>
>       - PENPOT_OIDC_CLIENT_SECRET=<secret>
>       - PENPOT_OIDC_AUTH_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/auth
>       - PENPOT_OIDC_TOKEN_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/token
>       - PENPOT_OIDC_USER_URI=https://<keycloak-url>/auth/realms/<realm-name>/protocol/openid-connect/userinfo````
> ```

@niwinz This worked perfectly for me. 

Thank you. !!!!
