### ISSUE TITLE
bug: Cant select through stroke only rectangle.

### ISSUE THREAD

**Issue by d3ntatous** [uxbox/uxbox#3289]
### Steps To Reproduce

1. Create a board and:
2. Create a rectangle
3. Create a text layer (could be any type really).
4. Make sure the rectangle layer is on top and large enough to cover the text layer.
5. Remove fill and stroke from the rectangle layer.
6. Try to select the text layer.

### Expected behavior

I should be able to select the text layer (Text 2) directly in this situation. Instead I am selecting the rectangle (StrokeRect).

![image](https://github.com/penpot/penpot/assets/20995205/63e5d765-d312-4b99-a2ad-d1d72ff2f189)

### Actual behavior

Viewport selection is purely driven by the hierarchy tree, and whats on top.

**Comment by superalex** [comment]
Thank you very much @d3ntatous 

I've just created this issue in Taiga https://tree.taiga.io/project/penpot/issue/5484 to track it
