### ISSUE TITLE
bug: Some image formats include the extension when importing

### ISSUE THREAD

**Issue by ahmed-0011** [uxbox/uxbox#3293]
### Steps To Reproduce

* Import jpg/png/svg images

### Expected behavior

I think that in the case of svg images - not including the extension in the image name - is the correct behavior,
because:

1. There is no benefit from including the extension in the image's name, but instead we can display the type/extension of the image  next to the image's name as a hint.
2. If you imported an image let's call it penpot.png and then when you are going to export it again as .png the exported image will be downloaded as penpot.png.png unless of course you removed the extension from the image name.

### Actual behavior

When importing an svg image, the image in Penpot will be imported and the extension (.svg) will not be included in it's name, but when importing png or jpg images the extension will be included in the image's name.

### Screenshots or video

![penpot1](https://github.com/penpot/penpot/assets/74181508/4a265c3d-8328-48ea-8443-75e43ff10fce)
![penpot2](https://github.com/penpot/penpot/assets/74181508/d8f7423e-8fde-4004-84a7-af467050395e)

### Desktop (please complete the following information)

- OS: Windows 10
- Browser: Chrome/Firefox

**Comment by superalex** [comment]
Thank you very much @ahmed-0011 

I've just created this issue on Taiga to track it -> https://tree.taiga.io/project/penpot/issue/5485

**Comment by Omsoni06** [comment]
I am taking initiative to solve this issue
