### ISSUE TITLE
bug: Independent corner radius input tooltips only say "Radius" instead of which corner it is for

### ISSUE THREAD

**Issue by astudentinearth** [uxbox/uxbox#3305]
### Steps To Reproduce

1. Select a board
2. Choose "Independent radius" for corner radius
3. Hover on any of the inputs and read the tooltip

### Expected behavior

The input should tell which corner it will apply the radius to. This behavior is seen in "Independent padding", and margins in flex layout.

### Actual behavior

The tooltip doesn't say which corner the input affects. All 4 of the tooltips read "Radius"

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/95227070/4ff8d041-dee8-47db-bda4-5e50b9114e03)

### Desktop (please complete the following information)

- OS: Arch Linux
- Browser: Firefox 114.0.1

### Environment (please complete the following information)

- Host: design.penpot.app

**Comment by superalex** [comment]
Thank you very much @astudentinearth 

I've just created this Taiga issue to track it -> https://tree.taiga.io/project/penpot/issue/5486
