### ISSUE TITLE
bug: Missing config.env

### ISSUE THREAD

**Issue by SatarisGIT** [uxbox/uxbox#3311]
### Steps To Reproduce

Hello! 

I want to ask, why between versions 1.16 -> 1.17 - config.env file was removed in docker configuration? 
How to now deal with it?

### Expected behavior

As in desc

### Actual behavior

As in desc

**Comment by superalex** [comment]
Hello @SatarisGIT 

No config.env is not necessary, everything should be managed in the docker-compose.yaml file (you can check the last version here https://github.com/penpot/penpot/blob/develop/docker/images/docker-compose.yaml)

These are the diffs for the documentation -> https://github.com/penpot/penpot-docs/pull/123/files

Regards!
