### ISSUE TITLE
feature: Remember the color selector type

### ISSUE THREAD

**Issue by mjbartholomew** [uxbox/uxbox#3316]
### Is your feature request related to a problem? Please describe.

I have to make an additional click each time I open the color selector.

### Describe the solution you'd like.

When designing in Adobe Illustrator and Affinity Designer, I prefer to use HSL as my color selector. In both of those applications, they remember the last color selector you chose. It would be great if Penpot had the same feature, so that I don't have to keep clicking the HSV tab each time the color selector displays.

**Comment by EsterLatorre** [comment]
Hello mjbartholomew,

I'm also going to log this one as it makes a lot of sense, you can check it's progress [here](https://tree.taiga.io/project/penpot/issue/5508)

Thanks!

**Comment by belen-albeza** [comment]
This was solved on September, I'm closing this.
