### ISSUE TITLE
bug: HSV values change unexpectedly

### ISSUE THREAD

**Issue by mjbartholomew** [uxbox/uxbox#3317]
### Steps To Reproduce

1. Open HSV color picker
2. Reset HEX to #000000
3. Update H value to 200
4. Update S value to 20
5. Update V value to 20

### Expected behavior

This should result in the HEX value updating at each change to reflect the values found in the H, S, and V fields, which according to DuckDuckGo's built in color converter would result in #282f33. 

### Actual behavior

Once the V value is updated to 20, both the H and S values reset to 0.

### Screenshots or video

**Penpot**
https://github.com/penpot/penpot/assets/16119136/ba3dcb11-b77b-4f86-8235-6b25e96d261b

**Affinity Designer**
https://github.com/penpot/penpot/assets/16119136/1308af0f-7543-4c40-9910-4d11c62fed03

### Desktop (please complete the following information)

macOS 12.6.3
Safari 16.3

### Environment (please complete the following information)

Local instance
Debian 11
Docker version 24.0.2, build cb74dfc

### Additional context

It would be great if when editing in HSV, those values are untouched by the application, and instead the HEX value was a reflection of the HSV values. It, instead, appears that whenever a HSV value is changed, the HEX is recalculated, and then the HSV values are recalculated based on the newly recalculated HEX value.

It would be really nice if when HSV is used to pick a color, the actual values for H,S, and V are saved for the object, and then the HEX value is calculated dynamically. This would allow me, the user, to pick up where I left off on a design, and see the HSV values I entered previously, instead of the calculated HSV values based on the calculated HEX value.

**Comment by EsterLatorre** [comment]
Hi mjbartholomew!
That sounds like an unchecked bug. I'm going to log it for you in taiga and you can track its progress [here](https://tree.taiga.io/project/penpot/issue/5496).
Thanks for your message :-)

**Comment by NicolasLeboeuf** [comment]
Hi,

I got the same kind of bug, tell me if it can be linked or if I have to open another bug.

For me it's when using the color picker and the saved colors.

[Capture vidéo du 28-06-2023 15:17:28.webm](https://github.com/penpot/penpot/assets/62602652/7bde0377-b54e-495d-b675-3d0bf80cafe0)
[Capture vidéo du 28-06-2023 15:01:41.webm](https://github.com/penpot/penpot/assets/62602652/510caa7c-ec41-4a6b-9f00-72543165738c)
