### ISSUE TITLE
bug: Move tool becomes hand tool

### ISSUE THREAD

**Issue by Adhiyankumar** [uxbox/uxbox#3318]
### Steps To Reproduce

the action should be like after using a hand tool, it should change to the move tool whenever you hit the move tool shortcut, but still, it remains the same after hitting the move tool, or shortcut key

### Expected behavior

Once the hand tool is used and shifted to move the tool it still is showing move tool, even if you use short cut keys.

### Actual behavior

But Once the hand tool is used then shifted the move tool it is still remains hand tool after using shortcut and manually given to move tool

**Comment by EsterLatorre** [comment]
Hello Adhiyankumar!
Thanks for your message. 
Can you provide us with the OS and browser you're using? I think some of that might be involved..
Cheers

**Comment by Adhiyankumar** [comment]
Hey Hi, I am using Chrome and due to the slowness, I am using the penpot in the local host but still facing the same problem.

**Comment by EsterLatorre** [comment]
Hello Adhiyankumar, 
I've tracked your issue in taiga and hopefully, it will get solved soon :) You can have a look [here](https://tree.taiga.io/project/penpot/issue/5719)
