### ISSUE TITLE
feature: Remember last active team across logouts / sessions

### ISSUE THREAD

**Issue by jancborchardt** [uxbox/uxbox#3325]
### Is your feature request related to a problem? Please describe.

Oftentimes when I open Penpot back up, I land in the "Your Penpot" team, which I rarely ever use since I mostly work in the Nextcloud team. Then I need to switch over.

### Describe the solution you'd like.

The last active team could be remembered across logouts / sessions. I don't know exactly when this info gets lost, for example when you just close the tab and reopen design.penpot.app again, it does go to the correct team.

**Comment by EsterLatorre** [comment]
Hello Jancborchardt!
I've logged your suggestion to [Taiga](https://tree.taiga.io/project/penpot/issue/5507), it makes a lot of sense! 
Thanks for your input :)

**Comment by superalex** [comment]
Thanks @jancborchardt this one should be fixed now :)

**Comment by jancborchardt** [comment]
Love it! Thanks a bunch :)
