### ISSUE TITLE
feature: Text-based instead of binary penpot files

### ISSUE THREAD

**Issue by politician** [uxbox/uxbox#3326]
### Is your feature request related to a problem? Please describe.

.penpot files are in a binary format, that means we have files containing many hours of work, thoughts, intelligence but we cannot do anything with them except import and export them in Penpot.

### Describe the solution you'd like.

Having a schema-adhering text-based import/export functionality instead of .penpot files would allow for:
- **Version-controlled** [template/libraries](https://penpot.app/libraries-templates): The libraries could be hosted in their own repos, accept PR's, issues, etc.
- Libraries, templates, could actually sit next to their HTML/CSS/JS counterparts
- Easier distribution of penpot component files rather than whole libraries, templates
- Opens for Penpot to add DesignOps functionalities around the checkout/commit/pull processes
- **Allow to work programmatically with Penpot files**. This actually would open up a whole range of endless possibilities such as auto-generating/updating files ready to be used in Penpot, pull or update new color styles, add components, keep HTML components in sync with Penpot components, use Penpot as a CMS, generate Penpot designs from ChatGPT, etc. 
- and more....

IMHO, this would actually be another big USP over Figma.

**Comment by superalex** [comment]
Hi @politician 

Right now penport support two formats:

![2](https://github.com/penpot/penpot/assets/1579633/6f9af52d-b113-485e-8314-8ae54b5e28a5)

Just use the other option and you can achieve everything you posted ;)

**Comment by politician** [comment]
Ah! Shame on me 😣
BTW, I tried to export [Material Design 3](https://github.com/penpot/penpot-files/raw/main/Material%20Design%203.penpot) like you suggested and then re-import it, it failed.
It worked on other files though, maybe this one is too big.
