### ISSUE TITLE
bug: Registration Domain Whitelist is not working with login-with-google

### ISSUE THREAD

**Issue by devadattas** [uxbox/uxbox#3348]
### Steps To Reproduce

Steps to reproduce:

1. Set `PENPOT_REGISTRATION_DOMAIN_WHITELIST=example.com`
2. Set `enable-login-with-google`
3. Setup `PENPOT_GOOGLE_CLIENT_ID` and `PENPOT_GOOGLE_CLIENT_SECRET`
4. Now start penpot and Click on Login with Google
5. Use any Google Account which doesn't have `example.com` email
6. Registration works

### Expected behavior

Using any Google account which has email different from `example.com` should prevent registration / login based on `PENPOT_REGISTRATION_DOMAIN_WHITELIST`.

### Actual behavior

Using any Google account which has email different from `example.com` allows registration / login based ignoring `PENPOT_REGISTRATION_DOMAIN_WHITELIST`.

**Comment by niwinz** [comment]
Looks like a bug, I will look on it, thanks!
