### ISSUE TITLE
bug: If I remove colour of a rectangle why dos it become black, I have to delete them to make the background transparent

### ISSUE THREAD

**Issue by likeanushkaa** [uxbox/uxbox#3349]
### Steps To Reproduce

![Board](https://github.com/penpot/penpot/assets/65487589/ad4d5079-2647-4efe-8048-7d5ebe8bb784)
Step 1: Paste this svg in penpot
Step 2: In this svg, remove the dark blue bg colour, you can see it becomes black as soon as you remove it

### Expected behavior

On removing the dark blue, it should show white as the bg colour, which is the bg colour of the board, and on removing it in general, it should have become transparent.

### Actual behavior

 If I remove the colour of a rectangle it becomes black, and I have to delete it to see the bg colour.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/65487589/4b1f3639-6f1b-4079-b7a1-273f9793a5f7)

### Desktop (please complete the following information)

Chrome 114 on macOS (Ventura)

**Comment by superalex** [comment]
Hello @likeanushkaa 

If you check the svg directly in your browser out of penpot you will see the main shape has a black background color. So it makes sense the black color is shown if you remove only the blue background of the contained shape. I'm attaching a video showing the idea:


https://github.com/penpot/penpot/assets/1579633/c668b427-dc01-426f-8b44-6e6c3853ef40
