### ISSUE TITLE
feature: show the number of comments in comment sticker

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3361]
### Is your feature request related to a problem? Please describe.

Now it shows a number, but it's not clear what the number means. I think it would be logical if the number would show the number of comments in the section.

![image](https://github.com/penpot/penpot/assets/433707/06c5e4b8-e2ac-4fb6-adf1-bfa86a3f9b06)

### Describe the solution you'd like.

Show the number of comments.

**Comment by elhombretecla** [comment]
Hi @ile :)

The comments are numbered based on their creation order. This number is used to identify them in the workspace, on the right-hand sidebar. This is how the comments are associated with their indicators.

![image](https://github.com/penpot/penpot/assets/1045247/9f6135c9-b0d1-4274-8d05-df50e39c6f8b)
