### ISSUE TITLE
bug: comment sticker visible for a deleted element

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3362]
### Steps To Reproduce

- Create element
- Add a comment
- Delete element

### Expected behavior

Comment sticker not visible.

### Actual behavior

Comment sticker is visible.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/433707/09d615c2-516f-4692-be5c-20b6ae571f95)

**Comment by elhombretecla** [comment]
Thank you for providing you feedback @ile 

This behavior is expected. Comments are not linked to any specific element; they exist independently. That's why they should remain even if the element is deleted or moved. If you want to delete a comment, you need to do it through the comment's options.
