### ISSUE TITLE
bug: comment stickers flash and not stay visible in certain case

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3363]
### Steps To Reproduce

- Create elements with comment stickers
- Select "Path tool"
- Select "Comment tool"
- The comment sticker will only flash and then disappear. 

If you select some other tool than "Path" it works correctly.

### Expected behavior

Sticker should keep showing

### Actual behavior

Stickers disappear.

### Screenshots or video

[Screencast from 29.06.2023 06.59.05.webm](https://github.com/penpot/penpot/assets/433707/33e92fe4-a440-41c8-b413-5ff00ae1c53a)

**Comment by elhombretecla** [comment]
Thanks for your feedback!

We will manage this from Taiga and fix it as soon as we can.

https://tree.taiga.io/project/penpot/issue/5585
