### ISSUE TITLE
feature: Post a comment with ctrl+enter

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3364]
### Is your feature request related to a problem? Please describe.

Usually you are able to post a comment with ctrl+enter - this works in almost every web app.

### Describe the solution you'd like.

I think it would be good if it worked also in Penpot.

**Comment by elhombretecla** [comment]
Thank you for your suggestion @ile :)
Could you please provide additional details or examples of the functionality you are proposing? It would be helpful to understand how you envision this feature being implemented and any specific context or use cases you have in mind. Feel free to provide more information, screenshots, videos or mockups, and I'll be happy to assist you further.

**Comment by ile** [comment]
Currently I think you need to click the button to submit the comment. The suggestion is to submit the comment with also ctrl+enter.

**Comment by ile** [comment]
On Mac you would probably use cmd+enter.

These work in many web apps.

**Comment by LalitDeore** [comment]
Is this feature added or not?  Can I go  with this feature?

**Comment by belen-albeza** [comment]
This is now being tracked on Taiga https://tree.taiga.io/project/penpot/issue/6085

**Comment by belen-albeza** [comment]
Hi @LalitDeore I'm working on it, but thanks for offering!

**Comment by belen-albeza** [comment]
> Is this feature added or not? Can I go with this feature?

Hi @LalitDeore! I'm working on it, but thanks for offering!
