### ISSUE TITLE
bug: Bug in grid cuts on primary boards

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3365]
### Steps To Reproduce

1. Create a board with grid
2. Create another board smaller than the first one
3. Check the box to cut the inner contents of the smaller board
4. Place the first board inside the second board

### Expected behavior

The expectation is that since the smaller board has the content cut flag turned on, any grid belonging to another internal board will also be cut.

### Actual behavior

The penpot does not cut the internal grids that go beyond the main board boundary.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/47113005/28dad34d-0377-4be0-8e5f-f53a78744a1b)

### Additional context

Note that in Figma, the primary frame cuts through the grids of the inner frame.
![image](https://github.com/penpot/penpot/assets/47113005/a38281ae-260d-46f9-8788-62a9758cd0e9)

In my situation, I created 1080x1080 boards to simulate the grid of the Instagram profile and inside the boards there would be another 1080x1350 board that would be the one for the post, which has grids to help with the alignment of the post and that, after finishing, would be placed in one of the boards 1080x1080 to get a sense of how it would look on the instagram grid.

This problem can happen in several situations and not only in mine to simulate the Instagram grid.  The same can happen with Flex-Layout which also allows grids.  And these leaks will disrupt the project at some point.

**Comment by elhombretecla** [comment]
Great, thanks @allytiago :)

We will review this as soos as we can. Thanks for the report https://tree.taiga.io/project/penpot/issue/5584
