### ISSUE TITLE
feature: Translator permissions request on Weblate

### ISSUE THREAD

**Issue by KristijanZic** [uxbox/uxbox#3366]
### Is your feature request related to a problem? Please describe.

Croatian language currently has incomplete and in some cases wrong translations

Weblate username: kristijan.zic

### Describe the solution you'd like.

I'd like to contribute my understanding of Croatian language, translating knowledge and time.

**Comment by myfunnyandy** [comment]
@KristijanZic we gave you permissions already. Thanks for your contribution!
