### ISSUE TITLE
bug: Exporter not working

### ISSUE THREAD

**Issue by RonElwaya** [uxbox/uxbox#3368]
### Steps To Reproduce

1. create an object to export
2. click on the object
3. click on export and choose export 1 element

### Expected behavior

item will be exported

### Actual behavior

error pops up saying "something wrong has happened (on backend)"
exporter logs show the following:
![20230702_151053](https://github.com/penpot/penpot/assets/138373187/dc67ead6-6fd3-4961-b284-030092f188cb)

### Desktop (please complete the following information)

Windows 10
Chrome 103.0.5060.134

### Environment (please complete the following information)

self hosted with the following setup
frontend, backend, and exporter using penpot official 1.18.4 docker images.
personal mail server
redis using redis official docker image version 7

**Comment by niwinz** [comment]
Looks like an issue with a configuration. Can you paste a relevant part of the configuration and the compose file for to understand what may be happening.

**Comment by RonElwaya** [comment]
its deployed on openshift so no compose file, attaching the deployment file:
![20230704_135450](https://github.com/penpot/penpot/assets/138373187/d8f05f1a-7376-4e8a-9d49-a4ebf872efe6)

**Comment by niwinz** [comment]
In this case unfortunately I don't know how to help you, looks like exporter is unable to reach the frontend, this is the most probable reason for this issue.

**Comment by RonElwaya** [comment]
tried from the exporter to "curl $PENPOT_PUBLIC_URI" and i got the page back, meaning it should succeed reaching the frontend so i dont know where it might go wrong

**Comment by liorbraude** [comment]
I also have the same problem with a similar configuration. Any idea?

**Comment by RonElwaya** [comment]
any updates? its still not working and quite important

**Comment by niwinz** [comment]
I mean, we don't have experience with openshift, so I'm unable to help here, looks like there are no correctly configured communication between exporter and frontend container, but I can't provide more help

the problem is clearly related to the deploy platform and not directly related to penpot issue

**Comment by RonElwaya** [comment]
So i think i found the issue, the openshift enviornment im running it on creates a default user on every pod and im unable to switch users within the pod. Does anyone know what permissions and stuff does the penpot user have inorder for me to give those stuff to the user thats being created?
