### ISSUE TITLE
bug: images with split bug after upload

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3372]
### Steps To Reproduce

1. Shift+k
2. Choose the image
3. Select
4. Upload

### Expected behavior

When the image was sent to the penpot, that the transparent background did not have any pixels in the area and that the image was exactly like the original file

### Actual behavior

After uploading any image, note that at the edges, there is a line of pixels equivalent to the pixels on the opposite side of the border.  That is, at the top of the image there will be a pixel line that is equal to the pixel line at the bottom of the image.  The same goes for left and right.  Which leads us to believe that when sending the penpot, it creates a split of the image, placing the main one in the center and copies one above, left, right and bottom of the image, but the duplicates are cut, leaving only the pixels on their edges.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/47113005/e604a677-15c0-49cf-870f-40496abfdfae)
![image](https://github.com/penpot/penpot/assets/47113005/25c41308-047d-4c43-befa-b1e2a5184365)
![image](https://github.com/penpot/penpot/assets/47113005/142f4bc9-53e4-4f0d-8842-cf2962d9adb1)
![image](https://github.com/penpot/penpot/assets/47113005/f3cc7082-6c48-4244-b026-f0ca9ad99679)
> On the left side, the image sent by upload, on the right, a board created inside the penpot and then exported in png that ended up being the image on the left.

**Comment by elhombretecla** [comment]
Hi @allytiago thank you so much for your feedback.

We are going to manage this issue from Taiga. Here is teh link to track it :)

https://tree.taiga.io/project/penpot/issue/5583

**Comment by niwinz** [comment]
@allytiago can you upload here the images you have used? Thanks

**Comment by soutiagojose** [comment]
> @allytiago can you upload here the images you have used? Thanks
I used this png for testing. When I zoomed in until I saw the pixel grid, the lines were more visible. 
![image](https://github.com/penpot/penpot/assets/47113005/87e2eea6-035d-42f0-a037-3510803d3680)

**Comment by Alotor** [comment]
Thanks @allytiago we've found the issue and will be fixed in the next release.

**Comment by shellheim** [comment]
Still experiencing this. Unfortunately ordered a poster which has a picture edited in penpot without seeing the line, and it's gonna have that line in it. Should reopen. @superalex @Alotor 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/24957e69-74ba-4040-bd96-edf3784af9f3" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/30eb3c65-62c2-4f5f-a3eb-8e19f35fde38" />
