### ISSUE TITLE
bug: Overlay won't close when the interaction is added to a board or text. Works when added to a rectangle.

### ISSUE THREAD

**Issue by NusryNizam** [uxbox/uxbox#3373]
### Steps To Reproduce

1. Select a screen
2. Connect the screen to another overlay screen (Prototyping)
3. On the overlay screen, select a board / text object and give the 'close overlay' interaction.
4. Prototype the system

### Expected behavior

The overlay should close when clicking the board or the text object

### Actual behavior

The system doesn't close when clicking the respective board or the text.

### Screenshots or video

https://youtu.be/AN1g_tsn5iQ?t=193

You can see it here.

### Desktop (please complete the following information)

- Firefox 114.0.2 on Ubuntu 21.10

### Environment (please complete the following information)

Host: design.penpot.app

### Additional context

The overlay closes when the interaction is added to a rectangle object instead of a board or text.

**Comment by elhombretecla** [comment]
Thank you so much for your feedback @NusryNizam :)

We will manage this from Taiga https://tree.taiga.io/project/penpot/issue/5587

**Comment by hirunatan** [comment]
Hello @NusryNizam. Thanks for reporting this issue.

I've solved the bug with the boards, and it will be available in the next release. But I can't reproduce the failure with texts. If I make a text layer and add the interaction to close the overlay, it works ok.

Could you please send us a file where this is happening? You can send the url of the file or a .penpot export to support@penpot.app. Thanks.

**Comment by NusryNizam** [comment]
Thank you @hirunatan 


The text object was inside the board. The text object was not on itself. I
couldn't clarifty it earlier. Hope you'd be able to reproduce the issue.
