### ISSUE TITLE
How long does it take to update Google Fonts?

### ISSUE THREAD

**Issue by soutiagojose** [uxbox/uxbox#3378]
### Steps To Reproduce

1. Enable the text function 
2. Choose the font

### Expected behavior

Selected font appears

### Actual behavior

Not all fonts appear, for example Playfair, Martian Mono and Anuphan

### Additional context

How long does penpot take to update the font bank?  I see that some sites use a google fonts api and have a very fast update, except in Penpot

**Comment by elhombretecla** [comment]
Hi again @allytiago :)

We are going to review the outdated Google fonts catalog and update it. Here is the link to track this issue https://tree.taiga.io/project/penpot/issue/5592

**Comment by niwinz** [comment]
> ### Additional context
> How long does penpot take to update the font bank? I see that some sites use a google fonts api and have a very fast update, except in Penpot

The fonts are updated on demand, I mean, we don't use google fonts API.
