### ISSUE TITLE
Button for scaling text

### ISSUE THREAD

**Issue by r25s** [uxbox/uxbox#3380]
### Is your feature request related to a problem? Please describe.

There is no button for scaling text. As a new user, I was looking for a way to scale text in the absence of a dedicated button. I couldn't find the answer quickly from online searches or the help docs (not saying that it isn't there, I don't know). I resorted to opening up Figma, looking at the shortcut they use by hovering over the dedicated button (which is K), and then trying it in Penpot. Voila!

### Describe the solution you'd like.

Have a dedicated button to switch to text scaling mode.

**Comment by elhombretecla** [comment]
Thank you so much for your feedback @ronmegg :)

We will managa this enhancement from Taiga https://tree.taiga.io/project/penpot/issue/5595

**Comment by madalenapmelo-kp** [comment]
Hi @r25s,

I'm closing this issue as this is already being tracked at issue #1045.
