### ISSUE TITLE
Help: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Xenxia** [uxbox/uxbox#3386]
Hello,

I use Penpot + Oauth Gitea for authentication all in HTTPS which goes through Nginx (Nginx does the conversion to https)

When I click on the OpenID button and authorize on Gitea, it returns to the login page.

In the logs you can find :
[log.txt](https://github.com/penpot/penpot/files/11970846/log.txt)

I assume it has something to do with the self-signed certificate but I can't find a key to give a certificate.

I'm running penpot under docker :

Front : penpotapp/frontend:latest

- PENPOT_FLAGS=disable-login-with-password disable-registration enable-secure-session-cookies enable-login-with-oidc

Back : penpotapp/backend:latest

- PENPOT_OIDC_CLIENT_ID=ID
- PENPOT_OIDC_BASE_URI=https://gitea/
- PENPOT_OIDC_CLIENT_SECRET=SECRET

- PENPOT_OIDC_AUTH_URI=https://gitea/login/oauth/authorize
- PENPOT_OIDC_TOKEN_URI=https://gitea/login/oauth/access_token
- PENPOT_OIDC_USER_URI=https://gitea/login/oauth/userinfo

PENPOT_FLAGS=disable-email-verification disable-smtp enable-prepl-server disable-login-with-password disable-registration enable-secure-session-cookies enable-login-with-oidc

PENPOT_PUBLIC_URI=https://penpot

Thanks for your help

Other information:
- Self-hosted ; OS debian 11

**Comment by shrpow** [comment]
Bruh, why did you just close the issue silently?

**Comment by shrpow** [comment]
For those who are faced with this problem:
Reverse Proxy to Selfhosted Gitea can use a self-signed SSL certificate.
Java requires adding such certificates to KeyChain

I did the following:
1. Created Dockerfile next to Docker-Compose with the following content

```yaml
FROM penpotapp/backend AS image

USER root

ADD caddy.crt /usr/local/share/ca-certificates/caddy.crt
RUN chmod 644 /usr/local/share/ca-certificates/caddy.crt && update-ca-certificates
RUN openssl x509 -in /usr/local/share/ca-certificates/caddy.crt -inform pem -out ca.der -outform der
RUN echo yes | keytool -importcert -alias startssl -keystore \
    $JAVA_HOME/lib/security/cacerts -storepass changeit -file ca.der

USER penpot

CMD ["/bin/bash", "run.sh"]
```

(it uses a pre-built image and simply makes some changes)

2. In Docker-Compose, in the Backend section, I added the following: 
```yaml
    build:                                               
      context: .                                         
      dockerfile: Dockerfile.backend 
```
Now the certificate is automatically added to KeyChain and requests are held without ssl errors
