### ISSUE TITLE
bug: Self Hosted: Error 400 on image upload

### ISSUE THREAD

**Issue by olivierb2** [uxbox/uxbox#3392]
### Steps To Reproduce

Attempt to upload image (either into profile or into Mokup).

### Expected behavior

Having image upload working

### Actual behavior

On image upload, the only error I can see is from network tab of my debug tool of my browser. I can see a POST on `https://penpot.iabsis.com/api/rpc/command/upload-file-media-object`. The server reply error `400 Bad Request` with the following response.

~~~
[
  "^ ",
  "~:type",
  "~:validation",
  "~:code",
  "~:invalid-image",
  "~:hint",
  "invalid image"
]
~~~

### Desktop (please complete the following information)

- OS server : Debian Bullseye

### Environment (please complete the following information)

- OS : Debian Bullseye
- Java openjdk 19.0.2 2023-01-17
- On-Premise custom install based on Dockerfile (not using Docker)

I cannot use Docker in my environment, I installed everything based on Dockerfile and docker-compose available. Everything is working good, I can upload penpot file by example, but issue seems only related to image.

I tried to make many fix based on this issue https://github.com/penpot/penpot/issues/1917 but with not luck.

### Additional context

As requested, here the image I try to upload.

![Capture d’écran du 2023-07-07 14-38-56](https://github.com/penpot/penpot/assets/2324018/80d32f37-52f5-452e-a0e8-0e882457d61c)

_No response_

**Comment by niwinz** [comment]
Can you provide the image you are trying to upload, and more info about the environment where you trying to upload (i mean our SAAS or on-premise, in case of on-premise, you are using our docker images or custom installation)

**Comment by olivierb2** [comment]
Thanks for this quick reply, I updated my issue.

**Comment by niwinz** [comment]
Given that it is a custom installation and the type of error, it is most likely that it is a version problem or a lack of libraries. Penpot uses imagemagick v6 and it is important that it is installed on the system as it is the tool used to verify (among other things) user uploaded images.

I have tried to use this image in a clean docker images based installation and it works as expected.

**Comment by olivierb2** [comment]
Many thanks for your reply.

I assume it would be very nice to get more details of the error in the logs.

We used chatGPT that help to debug by editing the file `src/app/media.clj` and adding the following lines:

~~~
# Near the top of the file
(require '[clojure.java.io :as io])

# A bit later in the code
(defmethod process-error org.im4java.core.InfoException
  [error]
  (let [file-path "/tmp/penpot.debug" ; Spécifiez le chemin et le nom du fichier de sortie
        error-content (str error)]
    (spit file-path error-content))

  (ex/raise :type :validation
            :code :invalid-image
            :hint "invalid image"
            :cause error))
~~~

I rebuilt and voila, I got a message into `/tmp/penpot.debug` that is saying

~~~
org.im4java.core.InfoException: org.im4java.core.CommandException: java.io.IOException: Cannot run program "identify": error=2, No such file or directory
~~~

I finally changed my PATH in env file from `PATH=/opt/jdk/bin/:$PATH` to `PATH=/opt/jdk/bin/:/usr/bin:$PATH`.

Now it's working perfectly !!

**Comment by niwinz** [comment]
I have added an improvement for making this debug more easy, thanks for the hint.
