### ISSUE TITLE
bug: Negative Spread value on Drop Shadow does not behave as expected

### ISSUE THREAD

**Issue by TheHaymaker** [uxbox/uxbox#3421]
### Steps To Reproduce

Steps to reproduce behavior:
1. Create a rectangle.
2. Add a drop shadow.
3. Increase Blur of drop shadow to 20
4. Decrease Spread of drop shadow to -22

### Expected behavior

A negative spread should decrease the total surface area of the drop shadow relative to the value. The same behavior as increases the spread with a positive value (only in reverse)

### Actual behavior

A negative spread value does not decrease the surface area of the shadow at all. If the negative value exceeds a certain threshold, you can observe the bound-box for the drop shadow is reduced in size. Any Blur that falls outside of the bounding-box is hidden.

### Screenshots or video

![Screenshot 2023-07-13 102938](https://github.com/penpot/penpot/assets/11251616/8ae23a56-b514-401d-ab39-c6b2f51df435)

### Desktop (please complete the following information)

Using the penpot.app cloud-deployed version 1.18 using Microsoft Edge v 114.0.1823.79 on Windows 11.

### Smartphone (please complete the following information)

Windows 11 Home V 22H2
OS Build 22621.1992
Dell XPS 15 9500

### Environment (please complete the following information)

Host: design.penpot.app

https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb5e43005fb6/8ec95363-4e2c-80a4-8002-cb5e442fa5d8?page-id=8ec95363-4e2c-80a4-8002-cb5e442fe3c8

**Comment by myfunnyandy** [comment]
I've added [this issue to our taiga project](https://tree.taiga.io/project/penpot/issue/5637) so we can take a proper look and track it. Thanks!
