### ISSUE TITLE
bug: Text area while editing showing double

### ISSUE THREAD

**Issue by APattjoshi** [uxbox/uxbox#3429]
### Steps To Reproduce

Steps to reproduce
1. click the text option
2. write some text
3. click outside to deselect
4. double click to edit the text
5. seeing two overlapping text elements

### Expected behavior

I want to double-click and change the text element style or rewrite certain words.

### Actual behavior

When I change the style of text it shows two lines hence unable to clearly select it and while deleting and editing some other text is getting deleted or edited.

### Screenshots or video

![Penpot img_issue](https://github.com/penpot/penpot/assets/47391164/6ab5d024-84da-4a74-a419-c4422311c27f)

### Desktop (please complete the following information)

OS: (Windows 10)
Browser (chrome)
Version 114.0.5735.199 (Official Build) (64-bit)

### Environment (please complete the following information)

SAAS (https://design.penpot.app/)

**Comment by EvaMarco** [comment]
Hello @APattjoshi 
Can you please send us the file where this happend to support@penpot.app?
We will check why this happened and try to fix it.

**Comment by madalenapmelo-kp** [comment]
Hi @APattjoshi,

Could you confirm if you are still experiencing this behavior?

Thanks!
