### ISSUE TITLE
bug: Whitespace in email breaks registration

### ISSUE THREAD

**Issue by Vikvam** [uxbox/uxbox#3432]
### Steps To Reproduce

1. Go to penpot [registration page](https://design.penpot.app/#/auth/register)
2. Use email address with whitespace, eg. " me@example.org"
3. Click at "Create and account"

### Expected behavior

User gets registered with email address "me@example.org" or gets feedback on what is wrong

### Actual behavior

No visible change, nothing in the console

### Desktop (please complete the following information)

- Browser: Mozilla Firefox for Arch Linux 114.0.2

### Environment (please complete the following information)

- https://design.penpot.app

**Comment by EvaMarco** [comment]
hello @Vikvam 
I have try this on my computer and on "chrome" it works just fine. I have tried it also on firefox and then the problem appears.
It looks like a firefox problem with email inputs. I have made some research and arrive to this. 
https://bugzilla.mozilla.org/show_bug.cgi?id=849611

But I think we can fix it for our inputs, so I created an issue -> https://tree.taiga.io/project/penpot/issue/5665
