### ISSUE TITLE
AYUDENME a recuperar mi correo tiene verificación de Dos pasós 

### ISSUE THREAD

**Issue by Alondra0101** [uxbox/uxbox#3433]
https://github.com/penpot/penpot/blob/c1013c359d18aa51c514ead628e316abdd15396e/frontend/translations/es.po#L181#: src/app/main/ui/auth/register.Graceflores010203@gmail.com
/cesaresquivel010203@gmail.com

**Comment by EvaMarco** [comment]
Hola¡

Porf avor escribenos a la cuenta de soporte con la información de la cuenta y lo ocurrido a ver si podemos ayudarte.
[support@penpot.app](mailto:support@penpot.app)
