### ISSUE TITLE
bug: Penpot appears to renders z-indexes wrongly depending on the zoom level and if an element is selected

### ISSUE THREAD

**Issue by KristijanZic** [uxbox/uxbox#3449]
### Steps To Reproduce

There aren't any particular steps, it just started happening. Look at the attached video.

### Expected behavior

Images of the tablets to be above the gradients.

### Actual behavior

If I zoom out gradient is above the tablet image, if I zoom in it's below it. If I select anything on the board it always renders correctly.

### Screenshots or video

https://github.com/penpot/penpot/assets/10299892/911aad08-dbfb-43a6-b403-3f9a9f0bf6dc

### Desktop (please complete the following information)

OS: macOS 13.4 22F66 arm64
Host: MacBookPro18,3
Kernel: 22.5.0
Uptime: 1 day, 2 hours, 16 mins
Packages: 205 (brew)
Shell: zsh 5.9
Resolution: 1512x982
DE: Aqua
WM: Rectangle
Terminal: /dev/ttys009
CPU: Apple M1 Pro
GPU: Apple M1 Pro
Memory: 2849MiB / 16384MiB

Browser: Brave (Version 1.56.11 Chromium: 115.0.5790.102 (Official Build) (arm64))

### Environment (please complete the following information)

Host design.penpot.app

**Comment by EvaMarco** [comment]
Hello @KristijanZic 

Can you please send us your file to support@penpot.app to examinate it?

Thanks

**Comment by KristijanZic** [comment]
I needed to complete the work so I deleted and recreated those designs, sorry :/

**Comment by EvaMarco** [comment]
Ouch, sorry to hear that. I'm trying to recreate that effect. If it happens again, copy that element and send it to us please.

**Comment by KristijanZic** [comment]
This should have been left open, it's happening more but I couldn't share designs.

**Comment by claragvinola** [comment]
Ok Kristijan, maybe it's related to gradients. We're going to look at it.

**Comment by claragvinola** [comment]
We have tried but we are not able to reproduce the error. If you can, when it happens to you again, share the file with us
