### ISSUE TITLE
feature: penpot backend, can I  check myself telemetry data?

### ISSUE THREAD

**Issue by VVege** [uxbox/uxbox#3461]
### Is your feature request related to a problem? Please describe.

I want to check telemetry data, but it is sended to https://telemetry.penpot.app/.  which  not support anyone check data. 

### Describe the solution you'd like.

have someway to check myself penpot telemetry data?

thanks

**Comment by niwinz** [comment]
You have two ways:
- setting up the `PENPOT_TELEMETRY_URI` to a custom  http endpoint
- look the code and inspect what it does (everything is opensource)
