### ISSUE TITLE
When I use the docker version, the mail registration function cannot be used

### ISSUE THREAD

**Issue by ghostxiu** [uxbox/uxbox#3464]
to SET FLAGS like that：
      `-PENPOT_FLAGS=enable-registration enable-login-with-password enable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies` 
      ` - PENPOT_SMTP_DEFAULT_FROM=service@myservice.com` 
      ` - PENPOT_SMTP_DEFAULT_REPLY_TO=service@myservice.com` 
     `  - PENPOT_SMTP_HOST=mail.myservice.com` 
      ` - PENPOT_SMTP_PORT=25` 
     `  - PENPOT_SMTP_USERNAME=service@myservice.com` 
      ` - PENPOT_SMTP_PASSWORD=xxx` 
      ` - PENPOT_SMTP_TLS=false` 
      ` - PENPOT_SMTP_SSL=false` 

After registering with an email address, the verification code cannot be received, and there is no prompt on the page

**Comment by niwinz** [comment]
Hi @ghostxiu,
without more information (logs, email server logs, etc) I can't help
we use the same code in our SAAS so it works, looks like there are some problem between penpot app and email server

**Comment by ghostxiu** [comment]
你好！您的邮件已收到，处理成功后会与您联系。修ghostxiu

**Comment by ghostxiu** [comment]
你好！您的邮件已收到，处理成功后会与您联系。修ghostxiu
