### ISSUE TITLE
bug: Click on breadcrum opens in ne tab

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3470]
### Steps To Reproduce

1. Open a project and a file
2. Click on the project name in the breadcrum
3. It opens in a new tab, no way to prevent this

### Expected behavior

The project opens in the same tab, as before today's release

### Actual behavior

With the new release, a click on the breadcrum always opens a new tab. That's very annoying to use

### Screenshots or video

[Capture vidéo du 31-07-2023 15:12:49.webm](https://github.com/penpot/penpot/assets/62602652/628c1172-6ace-4922-bd79-85155545986a)

### Desktop (please complete the following information)

- Ubuntu 20.04
- Chrome 114

### Additional context

I had created a ticket [here ](https://github.com/penpot/penpot/issues/1869) to have this behavior, but on demand, not all the time.

**Comment by claragvinola** [comment]
We're going to check that. Thank you for let us know! You can check the progress in here: https://tree.taiga.io/project/penpot/issue/5709

**Comment by claragvinola** [comment]
Hi again Nicolas, after reviewing your bug we have seen that our design team and a group of test users asked for this to work like this and also that you can always return to the main level by clicking a little more to the left.
Thanks!
