### ISSUE TITLE
bug: Wrong version built with docker for version 1.19.0

### ISSUE THREAD

**Issue by mecseid** [uxbox/uxbox#3474]
### Steps To Reproduce

1. Download the latest frontend and backend app from Docker Hub
2. Start the application
3. The version shows 1.17.2

### Expected behavior

The latest docker image is built from the expected version.

### Actual behavior

```
$ docker run -ti --rm --entrypoint /bin/bash penpotapp/frontend:1.19.0
root@cee4fd4410af:/# cat /var/www/app/version.txt
1.17.2-9408-g24fa4f71a
```
```
$ docker run -ti --rm --entrypoint /bin/bash penpotapp/backend:1.19.0
cpenpot@5b4f8e889375:~/backend$ cat version.txt
1.17.2-9408-g24fa4f71a
```
Exporter doesn't have a 1.19.x version.

**Comment by dawe-rgb** [comment]
I have exactly the same problem. It would be great if the new images were reinstalled soon. It's a bit of a pity to work with the old 1.17 version. I use Penpot productively as a designer for my studio. Looking forward to the new version! :)

**Comment by dawe-rgb** [comment]
There was an update - thank you, the pull has now worked with the correct version 1.19. :-)

**Comment by superalex** [comment]
Thanks!, I think @niwinz generated the correct versions some hours ago :)
