### ISSUE TITLE
feature: Make visible who are main editors/collaborators of a file

### ISSUE THREAD

**Issue by jancborchardt** [uxbox/uxbox#3475]
### Is your feature request related to a problem? Please describe.

We work in a design team of 4, additionally sometimes with developers and people from the community. Unless the person editing is right there in Penpot with you and it shows in the top bar, it is completely invisible (at least as far as I can see) who mainly works on this particular file.

### Describe the solution you'd like.

Already in the projects & files overview, the avatars could be displayed on the relevant files.

An example for this could be in the bottom right of the mockup preview. Could also be anywhere else – bottom left of the mockup preview, or left of the 3-dot menu although then there is less space for the mockup title, which is why I went for this solution:
![Board](https://github.com/penpot/penpot/assets/925062/b5a86713-22b2-4ba4-b82f-b73dee338487)

(No idea why the image is such bad quality, just did screenshot, import to Penpot, export from Penpot and upload here.)

**Comment by claragvinola** [comment]
Thank you for your idea! We're going to think about it. You can check the progress in here: https://tree.taiga.io/project/penpot/issue/5710
