### ISSUE TITLE
bug: export png x2 error 'Something wrong has happened (on backend)'

### ISSUE THREAD

**Issue by BlancaRiveraCampos** [uxbox/uxbox#3482]
### Steps To Reproduce

When I try to export a board as png x2, I get the following error message: 'Something wrong has happened (on backend)'
1. Create a board of 3666 x 8897 px
2. Select the board 
3. Click on Export > 2x > PNG > Export 1 element
4. Export fail and get an error message

### Expected behavior

Get the file exported in PNG 2x

### Actual behavior

Export does not occur and get the following error message 'Something wrong has happened (on backend)'

### Screenshots or video

![CleanShot 2023-08-02 at 15 42 43@2x](https://github.com/penpot/penpot/assets/66494279/ee72f780-4b6c-4c17-8181-881cef5506e6)

### Desktop (please complete the following information)

- macOS 13.3.1 (a), Processor 2,6 GHz 6-Core Intel Core i7
- Chrome Version 115.0.5790.114

### Additional context

[Banner.penpot.zip](https://github.com/penpot/penpot/files/12240784/Banner.penpot.zip)
Please find in this .zip the .penpot file

**Comment by claragvinola** [comment]
Hi Blanca!
The main problem with SVG shadows is that if you want to simulate a proper drop shadow (with all the parameters that a drop shadow has in Photoshop or Figma) you need to simulate it with different SVG filters and specifically one of them, the <feGaussianBlur>, consumes more CPU time the larger its stdDeviation parameter is, which is directly related to the size of the shadow.
So if the shadow is too big, the export fails.
We are trying to find a solution for this. Meanwhile, in designs with large shadows, perhaps those elements with shadows should be processed in some image processing tool and imported in transparent png.
