### ISSUE TITLE
bug: Duplicating a "Board" element with a Layout corrupts the undo history and the duplicated elements

### ISSUE THREAD

**Issue by azuredusk10** [uxbox/uxbox#3483]
### Steps To Reproduce

1. Create a new project in Penpot
2. Create a text element. Type in a few words.
3. With the text element selected, press Shift + A to wrap the text in a Board element.
4. Give the board a background fill colour.
5. Duplicate the board with Control + D several times. Notice how each duplicated board has 1 or more extra text layers inside them. 
6. Try deleting any of the text layers which are inside the duplicated boards. See them unexpectedly all disappear at once.
7. Try and undo the changes. The original board's contents are now deleted.

Eventually, Penpot also crashes sometimes when fiddling around with these duplicated boards.

### Expected behavior

Duplicating a board element with children should replicate the original elements exactly, without affecting the original board element or its children.

Undoing the duplicate action should not destroy the original board element or its children.

### Actual behavior

Duplicating a board element causes the children inside each duplicated element to also be duplicated a second time. This causes unexpected behaviour in the file.

Undoing this action deletes the children of the original board element, causing irreversible loss of data in the file.

### Desktop (please complete the following information)

- OS: Fedora Workstation 38
- Browser: Chrome (Version 115.0.5790.110 (Official Build) (64-bit) and Firefox (115.0.2 (64-bit))

### Environment (please complete the following information)

design.penpot.app

**Comment by superalex** [comment]
Thank you very much @azuredusk10

We generated this issue some hours ago with a hotfix :(

I'm just deploying a fix for it. It will be available in the next minutes

**Comment by superalex** [comment]
Hi @azuredusk10 I've just deployed to design.penpot.app, it should be working ok again. Thank you very very much for reporting.
