### ISSUE TITLE
Export fails every time when there is a shadow on an element

### ISSUE THREAD

**Issue by KristijanZic** [uxbox/uxbox#3485]
### Steps To Reproduce

Create a svg rectangle, put a shadow on it, try to export the board that element is a part of. Observe the export failure.

Or export the board in this file I've sent to the penpot email. Email is titled "Github bug: #3485".

### Expected behavior

Export succeeds 

### Actual behavior

Export fails

### Desktop (please complete the following information)

Any OS, any browser.

**Comment by claragvinola** [comment]
Hi Kristijan!
The main problem with SVG shadows is that if you want to simulate a proper drop shadow (with all the parameters that a drop shadow has in Photoshop or Figma) you need to simulate it with different SVG filters and specifically one of them, the <feGaussianBlur>, consumes more CPU time the larger its stdDeviation parameter is, which is directly related to the size of the shadow.
So if the shadow is too big, the export fails.
We are trying to find a solution for this. Meanwhile, in designs with large shadows, perhaps those elements with shadows should be processed in some image processing tool and imported in transparent png.
All the best

**Comment by KristijanZic** [comment]
I feel like at least a better error message should be given when that happens. Currently it just says something like "Error on the backend" or "Export failed". This should be documented and a user should be presented with a proper error code and message when this happens.

Should I create a feature request for that or will you just reopen this issue? As it's also a bug to not give a proper error to the user.

**Comment by KristijanZic** [comment]
@claragvinola
