### ISSUE TITLE
feature: Restore deleted items

### ISSUE THREAD

**Issue by vrishtrix** [uxbox/uxbox#3492]
### Is your feature request related to a problem? Please describe.

Sometimes people delete their prototypes but need them back after a while.

### Describe the solution you'd like.

A garbage bin system that stores the designs for x days before completely deleting them.

**Comment by claragvinola** [comment]
Hi Vrishtrix! We have in our roadmap the US related to this. You can check the progress in here: https://tree.taiga.io/project/penpot/us/187?backlog-q=histo&no-milestone=1
Thanks for the suggestion!
