### ISSUE TITLE
bug: challenges with text visibility after choosing typography and color from assets

### ISSUE THREAD

**Issue by VekkuliHKI** [uxbox/uxbox#3495]
### Steps To Reproduce

I have a weird challenge with text. I just created a new penpot project where I utilize the M3 pack. But I have been tackling with text the first day…

So, this is what happens: I add a text element into the board and write the content. So far all good. 
…But when I choose the color and typography from assets (based on M3), something goes wrong. The typography and fill color look correct on the design pane, but they are not displayed correctly on the board.

1) At times, the text seems too small considering the chosen typography, but when I paint it, the painted text grows into a size that seems correct. The smaller text version is still visible behind the painted correct sized text version, so I can see the same text two times simultaneously.

2) At other times, after choosing the color and typography, the text becomes invisible. The fill colour and size seem correct on the design pane, but the text cannot be seen on the board. When I paint the text, it becomes visible.

I am using Chrome version 114.0.5735.133

### Expected behavior

The text is visible in correct size and color

### Actual behavior

The text is either invisible or too small. When I paint the text, the painted text is visible in correct size.

### Screenshots or video

![IMG_6139](https://github.com/penpot/penpot/assets/141430850/f75bfc97-8426-4e66-8b8c-e0309e3c4dc7)
![IMG_6140](https://github.com/penpot/penpot/assets/141430850/24af06b9-948d-4aad-98b2-dc85f1809d8a)
![IMG_6141](https://github.com/penpot/penpot/assets/141430850/e6c8b9d9-0eff-4904-8f30-4d079229a218)
![IMG_6142](https://github.com/penpot/penpot/assets/141430850/e1e8e538-8812-49d7-bd05-57905262d49c)

### Desktop (please complete the following information)

Windows 10 64-bit
Chrome version 114.0.5735.133

### Environment (please complete the following information)

Local version penpot.leijona.local

**Comment by EsterLatorre** [comment]
Hello VekkuliHKI,
Hmmm, I've tried following your steps and I don't seem to have the same problem. We've tried it in windows as well... Can you please send us the file if it persist? So we can have a closer look.
Thanks!

**Comment by VekkuliHKI** [comment]
This issue seems quite similar. https://github.com/penpot/penpot/issues/3429 
I will also send you the file

**Comment by VekkuliHKI** [comment]
I tried to attach the penpot file but got an error message "we don't support that mail type". Should I send it by e-mail?

**Comment by EsterLatorre** [comment]
Can you please try to reproduce the issue in our environment design.penpot.app?
If it still persist, you can attach a file if you compress it first ;)

**Comment by VekkuliHKI** [comment]
I tried but I couldn't reproduce the issue in yoir environment. Everything related with texts, changing typography and colours worked just perfect. Here's the compressed file: 
[Asiakaspalvelu.penpot.zip](https://github.com/penpot/penpot/files/12311800/Asiakaspalvelu.penpot.zip)

**Comment by superalex** [comment]
@VekkuliHKI could you please check what version of penpot exactly are you running? (our instance has always the latest changes so may be you have an outdated version)

**Comment by VekkuliHKI** [comment]
It is 1.18

**Comment by superalex** [comment]
That can be the problem @VekkuliHKI upgrade to the last version 1.19 please

**Comment by madalenapmelo-kp** [comment]
Hi @VekkuliHKI,

Could you confirm if upgrading to the last version resolved the issue and, if so, close this issue?

Thanks!
