### ISSUE TITLE
bug: one more `penpot-exporter` error, bad token on launch.

### ISSUE THREAD

**Issue by c4lliope** [uxbox/uxbox#3502]
### Steps To Reproduce

Penpot's been running amazingly smoothly for months, using your recommended `docker-compose.yaml`. I placed a bunch of the env vars inside a `config.env` for ease of management. Once I heard of the flexbox upgrades, I made a quick command, `~/cycle.sh`:

```
#!/bin/env bash
cd /root/paper
docker compose down
docker compose pull
docker compose up -d
```

I run this as much as I can, so I'm sure to be on the most recent published images. This morning, I'm seeing that `penpot-exporter` has an error on launch, and hence is blocking the `penpot-frontend` process also.

```
root@garden:~/paper# docker compose run penpot-exporter bash
penpot@3133627eba4f:~/exporter$ node app.js
/opt/penpot/exporter/node_modules/playwright-core/lib/utilsBundleImpl.js:1



SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/penpot/exporter/node_modules/playwright-core/lib/utilsBundle.js:28:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.15.0
```

A couple other recent issues mention `penpot-exporter`, though they seem to be dissimilar causes here. #3368 and #3294 only break on a real export operations, in my case there is no launch and the app is inoperable. Hope someone can share directions.

### Expected behavior

`docker compose pull; docker compose up -d` should bring up penpot.

### Actual behavior

`penpot-exporter` crashes and application is unable to launch.

### Desktop (please complete the following information)

nonapplicable.

### Smartphone (please complete the following information)

nonapplicable.

### Environment (please complete the following information)

Debian LXC container running on Proxmox.
```bash
root@garden:~/paper# uname -a
Linux garden 5.15.108-1-pve #1 SMP PVE 5.15.108-1 (2023-06-17T09:41Z) x86_64 GNU/Linux
```

### Frontend Stack Trace

```console
root@garden:~/paper# docker compose logs -f penpot-frontend
paper-penpot-frontend-1  | 2023/08/07 14:44:12 [emerg] 1#1: host not found in upstream "penpot-exporter" in /etc/nginx/nginx.conf:125
paper-penpot-frontend-1  | nginx: [emerg] host not found in upstream "penpot-exporter" in /etc/nginx/nginx.conf:125
```

### Backend Stack Trace

```console
looks good.
```

### Additional context

`¯\_(ツ)_/¯`

**Comment by c4lliope** [comment]
Error is also on `penpotapp/penpot-exporter:1.19.0` image; backing up to `1.18.6` enables success on launch.

**Comment by niwinz** [comment]
Hello @c4lliope 
I'm unable to reproduce it. I just started a clean vm, installed docker and setup a basic penpot from scratch using latest version and everything worked ok. Honestly, I don't know how I can help, as I don't know what might be going on...

The issues you mention, have nothing in common with this issue.

**Comment by c4lliope** [comment]
Yep, this one is curious.
There is a similar issue described on the `playwright` codebase, the source of the error:
https://github.com/microsoft/playwright/issues/24459

I am using an LXC image called `debian-11-standard_11.6-1_amd64.tar.zst`;
I began to see if I could recompile the docker images to use other versions of `playwright`;
should the process roughly be...?

```bash
echo 'local-branch' > ./version.txt
# Change up any `playwright` dependency or code as needed.
./manage.sh build-frontend-bundle
./manage.sh build-backend-bundle
./manage.sh build-exporter-bundle
./manage.sh build-docker-images
```

and then I could use inside my `docker-compose.yaml`:

* `penpotapp/frontend:local-branch`
* `penpotapp/backend:local-branch`
* `penpotapp/exporter:local-branch`

I hope this is a good direction to learn more on the issue -
I'll also back up my docker volumes, db, and config, so I can redeploy the app cleanly on a newer Debian.

**Comment by c4lliope** [comment]
CC @pavelfeldman - a playwright issue has popped up; you can see the link to your codebase's closed issue, in my comment from a couple days ago. I hope this backtrace of the error can help lead us to some repair.

**Comment by niwinz** [comment]
I'm still very confused with this issue.
It is assumed that docker images, one of its objectives is that the execution is reproducible. How is it possible that for some it fails to start playwright in the nodejs of the image and for others it works correctly using absolutely the same image. What is really the difference that makes it behave differently?
