### ISSUE TITLE
bug: "Fix when scrolling" renders groups invisible in preview

### ISSUE THREAD

**Issue by flberger** [uxbox/uxbox#3508]
### Steps To Reproduce

1. Create some shapes
2. Set one shape to "📌 Fix when scrolling" in the inspector
3. Group the shapes
4. Observe that all shapes are perfectly visible in the workspace
5. Open view mode
6. Observe that all but the fixed shapes are invisible
7. Go back to workspace and select the offending shape within the group
8. Observe that "📌 Fix when scrolling" is not available while the shape is in the group

### Expected behavior

The view mode should not unexpectedly differ from the workspace view: all shapes should be visible.

If fixing a shape will inevitably create a problem in the view mode, the user should be warned about it.

Else the attribute should be cleared when an object is added to a group.

### Actual behavior

The view mode unexpectedly differs from the workspace view: all but the shape set to "fix when scrolling" before are gone, for no apparent reason.

The user is not warned that adding a fixed shape to a group will render the group invisible.

The "fix when scrolling" attribute is not cleared when an object is added to a group, although it has no effect, or in the present implementation an adverse effect.

### Screenshots or video

A series of shapes, with the ellipse set to "fix when scrolling".
![2023-08-penpot01](https://github.com/penpot/penpot/assets/8035998/37b78510-de42-4419-8f05-b98a8eb3578a)

The view mode is fine.
![2023-08-penpot02](https://github.com/penpot/penpot/assets/8035998/bc7c2ba9-de6c-457b-99e3-1e2d46e2624b)

The objects are grouped now. Note that the inspector option "fix when scrolling" is gone.
![2023-08-penpot03](https://github.com/penpot/penpot/assets/8035998/2c420b31-e9a6-44c0-a7a4-33aa99bf78b8)

In view mode, all but the offending objects are invisible.
![2023-08-penpot04](https://github.com/penpot/penpot/assets/8035998/8a02bc0e-8e3b-4229-b9e0-2fcd9fbe265e)

### Desktop (please complete the following information)

- Artix Linux (an Arch Linux variant)
- Chromium 117.0.5851.0 (64bit)

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by EsterLatorre** [comment]
Hello flberger,
I've logged it in Taiga so it can get fixed. You can track the progress [here](https://tree.taiga.io/project/penpot/issue/5723)
Thanks for your message!
