### ISSUE TITLE
bug: File Library colors not ordered

### ISSUE THREAD

**Issue by JStuve** [uxbox/uxbox#3510]
### Steps To Reproduce

Steps to reproduce:
1. Create a File Library of colors that have alpha ordering 
<img width="257" alt="image" src="https://github.com/penpot/penpot/assets/14914689/ffdde135-d9ee-4cee-b5f4-6414dbb8cbb5">

2. Create any shape, add a stroke color, and switch the dropdown to File Library (It also occurs for Fill). The colors are beautifully in order
<img width="860" alt="image" src="https://github.com/penpot/penpot/assets/14914689/2524138b-6df9-4f79-b204-e3b951d89745">

3. Close the color picker
4. Open the color picker

### Expected behavior

1. The color picker should have File Library selected
2. The colors should all be in order

### Actual behavior

1. The color picker should have File Library selected
2. The colors are all mixed up
<img width="346" alt="image" src="https://github.com/penpot/penpot/assets/14914689/f3f58794-f31e-463c-bc9f-28f7398e703b">

### Desktop (please complete the following information)

- OS: Monterey 12.6.5

### Environment (please complete the following information)

- Penpot Desktop: 0.2.34

**Comment by EsterLatorre** [comment]
Hello JStuve!
One half or your suggestion about the ordering is already being considered and hopefully will be with us soon. You can track it [here](https://tree.taiga.io/project/penpot/us/5399).
Regarding having the last used library selected by default when you close and open the color picker again, that's not happening to me, I'm guessing it it might be related to the desktop app... Just to be sure, could you try and check if it happens in design.penpot.app?
Thanks for your message :)

**Comment by madalenapmelo-kp** [comment]
Hi @JStuve,

Could you please confirm that this has been resolved and close this issue?

Thanks in advance :slightly_smiling_face:

**Comment by JStuve** [comment]
@madalenapmelo-kp Confirmed that the issue is resolved, thank you!
