### ISSUE TITLE
bug: editing a component doesn't update its instances

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3512]
### Steps To Reproduce

1. Create a component in "File 1"
2. Use it in a board in "File 2"
3. Update the component
4. There is no more pop-up "update components" in "File 2" as it used to be
5. The instance in "File 2" is not updated automatically (which could explain the disappearance of the pop-up), I have to "cancel changes" on the instance to get the new version

### Expected behavior

The instance is automatically updated (preferred)

OR

The return of the pop-up

### Actual behavior

Nothing happens

### Desktop (please complete the following information)

- Ubuntu 22.04
- Chrome 115

**Comment by EsterLatorre** [comment]
Hi NicolasLeboeuf,

Just to be sure I'd like to check that you edited an instance of the component and then clicked on "update main component"?
I've followed the steps you're mentioning and its working fine for me. If there is any extra info that might be useful, or if you can send the files over, maybe we can be of further help ;)

Thanks for your mesage!

**Comment by diamsa** [comment]
https://github.com/penpot/penpot/assets/76075288/3ed925c0-9102-4ec6-989e-52bb1d542d49

Hi! I'm having the same problem. The update option only shows up when I create a new component where the main component is.

**Comment by NicolasLeboeuf** [comment]
Thanks for the video diamsa, it's exactly the same :)

**Comment by elhombretecla** [comment]
Hi @NicolasLeboeuf @diamsa Thabk you so much for your feedback :)

We have been able to reproduce this error, and we will try to resolve it in the next few days. Here's the link for [tracking the issue on Taiga](https://tree.taiga.io/project/penpot/issue/5725). 

Thank you very much again.

**Comment by superalex** [comment]
Hi @NicolasLeboeuf and @diamsa 

This one should be fixed and deployed to design.penpot.app

Thank you very much!
