### ISSUE TITLE
bug: OpenID error Authentication provider not configured

### ISSUE THREAD

**Issue by vm32** [uxbox/uxbox#3514]
###   Environment Setup:
        Penpot Version: 1.18.4
        Deployment Type:  Docker
        Browser: [ Chrome , Firefox]

###  Enable OpenID Authentication:
            Following Penpot Configurations pages https://help.penpot.app/technical-guide/configuration/ 
             [backend/scripts/repl]
```
             export PENPOT_OIDC_CLIENT_SECRET="XXXXXXXXX"
             export PENPOT_OIDC_CLIENT_ID="XXXXXXXX"
             export PENPOT_OIDC_USER_URI="https://xxxxxx.outseta.com/connect/userinfo"
             export PENPOT_OIDC_TOKEN_URI="https://xxxxxx.outseta.com/connect/token"
             export PENPOT_OIDC_BASE_URI="https://xxxxxx.outseta.com/"
             export PENPOT_OIDC_SCOPES="openid,profile,email"
```
             [common/src/app/common/flags.cljc]
             
```
              [:disable-registration
               :disable-login-with-password
               :enable-login-with-oidc])

```

        Save the settings.
        All This settings 

    Attempt to Login via OpenID:
        Go to the Penpot login page.
        Select the OpenID login option.
        Observe the error message "Authentication provider not configured".

    Check Configuration:
        Navigate back to the configuration/settings panel.
        Verify that all OpenID settings are still correctly populated.

    Review Logs:
        Check Penpot's logs to identify any error messages or warnings related to OpenID authentication.

### Expected behavior

After configuring OpenID settings, users should be able to log in using the OpenID provider without any errors.

### Actual behavior

Upon attempting to log in using OpenID, the error "Authentication provider not configured" is displayed.

### Screenshots or video

https://github.com/penpot/penpot/assets/21219411/6757e44c-05f0-4b98-9bfa-bcfa9053aead

### Desktop (please complete the following information)

MacBook Air M2 - OS MacOS Ventura 13.4.1 (c)

**Comment by niwinz** [comment]
Hello @vm32

I'm not clearly understand how you provide the flags settings to the application.
For example, you should not modify the common/src/app/common/flags.cljc file.

All flags should be passed through the environment variable `PENPOT_FLAGS` for all modules (frontend, backend and exporter)

**Comment by vm32** [comment]
So, like `PENPOT_FLAGS="..." ./manage.sh run-devenv`?

**Comment by vm32** [comment]
So, like `PENPOT_FLAGS="..." ./manage.sh run-devenv`?

**Comment by niwinz** [comment]
Are you running devenv?, You should have mentioned it in the issue body...

On devenv, looks like you are modifying the backend/scripts/repl but probably you are using the backend/scripts/start-dev
Try to put the same export environment variables inside start-dev script instead of repl

**Comment by niwinz** [comment]
And put the PENPOT_FLAGS also inside the backend/scripts/start-dev
```
export PENPOT_FLAGS="enable-login-with-oidc"
```

In any case, If you plan to use it as final user and not get involved in developmnent, running it as devenv is highly discouraged.
