### ISSUE TITLE
bug: font type support information is inconsistent between Penpot UI and help docs

### ISSUE THREAD

**Issue by diacritica** [uxbox/uxbox#3520]
### Steps To Reproduce

**To Reproduce**

Based on https://github.com/penpot/penpot/issues/2376 (this bit was not fixed)

1.  Go to 'https://design.penpot.app/#/dashboard/team/<team_id>/fonts' and you will see the following:
![Screenshot 2022-09-29 at 01-54-16 Penpot Design Freedom for Teams](https://user-images.githubusercontent.com/840585/192908876-520661de-c539-4406-bd10-4da01ef71a64.png)

2. The [documentation](https://help.penpot.app/user-guide/custom-fonts/) indicates:
  ![Screenshot 2022-09-29 at 01-53-53 15· Custom fonts](https://user-images.githubusercontent.com/840585/192909014-f163c9b3-9673-4269-bb03-3c52df155dca.png)

### Expected behavior

If indeed WOFF font format is suppoorted, help docs should add that information.
The docs should say "You can upload fonts with the following formats: TTF, OTF and WOFF"

### Actual behavior

The helps docs don't show the WOFF support

### Desktop (please complete the following information)

N/A

### Smartphone (please complete the following information)

N/A

### Environment (please complete the following information)

N/A

**Comment by myfunnyandy** [comment]
Now managed on Taiga: https://tree.taiga.io/project/penpot/issue/5731
