### ISSUE TITLE
bug: applying color styles does not stay after exporting and them importing, inconsistently

### ISSUE THREAD

**Issue by rehrar** [uxbox/uxbox#3522]
### Steps To Reproduce

This is a difficult bug to reproduce because it worked for 99% of our color styles. Given the seeming random inconsistency, I cannot give meaningful steps to reproduce. The file is very large with many screens, however.

### Expected behavior

Applying a named color style in the selection colors tab retains this color style upon export and subsequent import.

### Actual behavior

There are a select few colors that, after applying a color style through the selection colors tab, does not survive when exported as a .penpot and subsequently imported. It instead reverts to an unnamed color style. We have tried to apply this style on a self-hosted Penpot instance, as well as the one on design.penpot.com. Also attempted with browser and desktop app.

### Screenshots or video

How it should look, and before export:
![image](https://github.com/penpot/penpot/assets/26863955/ddcbe187-73bf-44ba-80d4-20f53adfd9ba)

Once exported and reimported:
![image](https://github.com/penpot/penpot/assets/26863955/4c0bbc0f-aa1b-4138-9191-cea5943f15d9)

### Desktop (please complete the following information)

Windows 11,
Mozilla 116.0.2 (64-bit),
Also attempted with Penpot desktop app v0.2.3 Beta

### Environment (please complete the following information)

Host: design.penpot.app

**Comment by myfunnyandy** [comment]
Hi @rehrar, could you send us a file where the issue can be reproduced to support@penpot.app so we can take a better look? 

Thanks!

**Comment by rehrar** [comment]
Hello, the repos with the .penpot files can be found here.

https://github.com/cypherstack/bitcoin-ui-kit-penpot

**Comment by madalenapmelo-kp** [comment]
Hi @rehrar,

I was able to reproduce this behavior and I've opened an issue at Taiga, you can check the details here: https://tree.taiga.io/project/penpot/issue/6107

Thanks for reporting this!
