### ISSUE TITLE
bug: Checkbox for Terms and Privacy not visible when running via Docker 

### ISSUE THREAD

**Issue by vm32** [uxbox/uxbox#3539]
### Steps To Reproduce

    Docker version: 4.20.0 (109717)
    OS: MacOS M2 13.4.1 
    Browser Firefox 

### Expected behavior

I expected to see the checkbox for agreeing to the Terms and Privacy when registering a new account

### Actual behavior

The checkbox for the Terms and Privacy is not visible.

### Screenshots or video

<img width="857" alt="Screenshot 2023-08-21 at 2 33 48 PM" src="https://github.com/penpot/penpot/assets/21219411/a710dd5c-913b-4b0c-acda-569993c0d187">
My Localhost

**Comment by niwinz** [comment]
The privacy and terms is related to our SAAS, if you mount a penpot service on-premise, you should provide your own terms and privacy policy to your users, because you are responsible of the data stored on this service.

**Comment by niwinz** [comment]
But if you still want to enable the checkbox you can use the `enable-terms-and-privacy-checkbox` flag.
