### ISSUE TITLE
bug: view mode: flow selection: flows shown outside selection box and not available when too many

### ISSUE THREAD

**Issue by carstenheyer** [uxbox/uxbox#3545]
### Steps To Reproduce

1. Create a large amount of flow starts, depending on your screen resolution (e.g. at least 25 to 30 for 1080px height)
2. Start view mode
3. Open the flow dropdown 

### Expected behavior

All created flows (no matter how many) should be available to select.
First but maybe not best idea could be to get a scrollbar inside the dropdown list.

### Actual behavior

The dropdown shows all flows using the maximum height of the browser window, but only the first 12 flows (less if browser height is restricted) are visible due to their white background layer, the rest is more or less invisible when black font meets black background. 

### Screenshots or video

Screenshot showing selected Flow 25 and opened flow dropdown with hovered Flow 22:
 
![image](https://github.com/penpot/penpot/assets/88189340/9119f3db-6b95-47c9-ab5e-863a5e55651c)

Example with 30 flows:
https://design.penpot.app/#/view/30d53b09-0290-8050-8001-feacefcec456?page-id=069f6d81-449f-8080-8003-02652a97bc08&section=interactions&index=0&share-id=a4a1c11b-aa9f-8104-8003-02842c8e052c

### Desktop (please complete the following information)

- Windows 10
- Chrome Version 115.0.5790.171 (Official Build) (64-bit)

### Environment (please complete the following information)

- Host https://penpot.app 22.08.2023 Version 1.19

**Comment by myfunnyandy** [comment]
This issue is now managed on Taiga (https://tree.taiga.io/project/penpot/issue/5753).

@carstenheyer thanks for the report!
