### ISSUE TITLE
bug: changing asset view style to list will be discarded when switched to tab Layers and back to Assets

### ISSUE THREAD

**Issue by carstenheyer** [uxbox/uxbox#3547]
### Steps To Reproduce

1. Create a few components or graphics
2. Switch to list view in assets tab
3. Chose Layer tab
4. Chose Assets tab

### Expected behavior

The chosen view style in Assets tab should be remembered at least as long as the browser window/tab is not closed or updated.

### Actual behavior

Every time the user switches to the Layers tab and back to Assets tab the component view style is reset to default tile view style.

### Screenshots or video

![2023-08-22 15-27-27](https://github.com/penpot/penpot/assets/88189340/022712ad-708a-4686-8089-c8ed1fe326b4)

### Desktop (please complete the following information)

- Windows 10
- Chrome Version 115.0.5790.171 (Official Build) (64-bit)
- Firefox Version 116.0.3 (64-Bit)

### Environment (please complete the following information)

Host https://penpot.app/ 22.08.2023 Version 1.19

**Comment by niwinz** [comment]
I have reported it internally:  https://tree.taiga.io/project/penpot/issue/5788

Thanks for opening the issue.
