### ISSUE TITLE
bug: Problems with colorPicker element

### ISSUE THREAD

**Issue by Wheatgrh** [uxbox/uxbox#3562]
### Steps To Reproduce

I used penpot for the first time and immediately caught this bug. The color picker stopped working completely in my project. I can't say for sure after which it broke, but I can give access to the project. I tried to open the project on different computers, with different OS, but the result is always the same.

### Expected behavior

Color Picker working right.

### Actual behavior

Color Picker does not see colors on the screen.

### Screenshots or video

https://github.com/penpot/penpot/assets/14089214/d380a323-9029-4ccf-ae56-09578de96fc4

### Desktop (please complete the following information)

- Mac OS / Windows
- Google Chrome / Safari / Firefox

**Comment by niwinz** [comment]
Thanks for report this issue.
It happens in some circumstances when penpot is unable to render as bitmap the whole visible workspace viewport.

If it is possible if you can share the link to your file in order to us check what is exactly happens.

Also, we already started to develop a better approach for handling this color picker

**Comment by ahsmha** [comment]
facing same issue. @niwinz please do keep us posted on this issue

**Comment by ahsmha** [comment]
> Also, we already started to develop a better approach for handling this color picker

@niwinz what is the new approach? and how was it implemented before?

**Comment by Wheatgrh** [comment]
@niwinz It is exported project file. Git doesn't allow you to attach a penpon file directly.
https://drive.google.com/file/d/1UV0qFuhnr7krL7QR_rSTK5jUU5CyBbls/view?usp=sharing

**Comment by niwinz** [comment]
Thanks, I have downloaded file and will recheck, In any case I guess the bug is already fixed  by the refactor of that part and I'm pretty sure that the next version will come with  the fix

**Comment by Panini-Manganini** [comment]
I'm facing the same issue currently even though it's allegedly been addressed already
