### ISSUE TITLE
bug: pointing to elements weirdly alters text

### ISSUE THREAD

**Issue by KazimirPodolski** [uxbox/uxbox#3564]
### Steps To Reproduce

1. Get penpot
2. Get Material Design library
3. Open second page "How it works"
4. Point to something on the page

### Expected behavior

Nothing weird

### Actual behavior

Italic text twitches/changes.

### Screenshots or video

[recording-2023-08-27_16.23.49.webm](https://github.com/penpot/penpot/assets/6647438/4b402a30-bb23-4c65-8dbb-8bc6ebb8572a)

### Desktop (please complete the following information)

- Ubuntu 22.04
- Chrome 116

### Environment (please complete the following information)

Cloud

**Comment by niwinz** [comment]
yep, we have found the issue (two issues in reality) and we are already working to fix it.
Thanks for reporting it.
