### ISSUE TITLE
bug: Assets tab is slow and not cached

### ISSUE THREAD

**Issue by KazimirPodolski** [uxbox/uxbox#3565]
### Steps To Reproduce

Assets tab is quite inconveniet to use as it does not seem to cache components and stuff, reloading it every time.

1. Get e.g. Material Design library, or some other big library
2. Do your things
3. Get to Assets tab from time to time 

### Expected behavior

List of assets is immediately available after first load

### Actual behavior

List of assets loads every time the tab is opened

### Screenshots or video

[recording-2023-08-27_16.54.52.webm](https://github.com/penpot/penpot/assets/6647438/15ce87e9-2285-44b0-add9-99c63bed8590)

### Desktop (please complete the following information)

- Ubuntu 22.04
- Chrome 116

### Environment (please complete the following information)

Cloud

**Comment by niwinz** [comment]
Yep, we are aware of the issues on the assets tab and we already have different lines of improvements: some are more immediate and some other will require probably design changes.

Thanks
