### ISSUE TITLE
Contribution to Penpot French translation

### ISSUE THREAD

**Issue by louischance** [uxbox/uxbox#3583]
Hi,

I'm a French native and would be happy to help finish translating the Penpot frontend French strings and words in Weblate.

My Weblate username is louischance.

**Comment by myfunnyandy** [comment]
Hi @louischance, 

We've already added you to the translation project. Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
