### ISSUE TITLE
bug: When exporting on the desktop app the font are not loaded which results in squares for each letter

### ISSUE THREAD

**Issue by Chepycou** [uxbox/uxbox#3607]
### Steps To Reproduce

select one element
click + right to export
export as png for instance

### Expected behavior

The save as popup window should have readable text

### Actual behavior

The save as popup window has no text (see image below)

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/46412738/724871ce-2d35-4484-9ed4-1394ce757d59)

### Desktop (please complete the following information)

Fedora Linux 36 with KDE version 5.27.4
My browser is the latest version of Firefox but I'm running this in the Desktop App, installed via snap, version 0.2.4

### Environment (please complete the following information)

Host :  https://design.penpot.app

**Comment by ghost** [comment]
This is an issue related to Snap only.

**Comment by ghost** [comment]
![image](https://github.com/penpot/penpot/assets/51213244/5a5d0113-be32-4502-b555-5becefc207f2)

Yeah, same for me in Snap version. 
Flathub version works fine...

**Comment by Chepycou** [comment]
Gonna use the Flatpak :+1: (sad thought for the Ubuntu fellows)

**Comment by ghost** [comment]
Oh it works great on Ubuntu itself, I just tested on a VM.
If the user installs the Snap version, I assume they are on Ubuntu, and according to Metrics that is the case.

**Comment by ghost** [comment]
This issue is related to Penpot Desktop, close this.
