### ISSUE TITLE
bug: export format selection not displayed on desktop App

### ISSUE THREAD

**Issue by Chepycou** [uxbox/uxbox#3609]
### Steps To Reproduce

select one element
click + right to export
click on the default output option (PNG if I'm not mistaken)

### Expected behavior

This should open a select menu with several export options (PDF, PNG, SVG ...)

### Actual behavior

The select menu is half open half not, no text is displayed, the window freezes (and sometimes crashes) 
note that clicking randomly in the empty space can change the export type, so one can guess the position of the export type

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/46412738/4ea13358-61c6-4169-92a3-443f6e0fe5a7)

### Desktop (please complete the following information)

Fedora Linux 36 with KDE version 5.27.4
My browser is the latest version of Firefox but I'm running this in the Desktop App, installed via snap, version 0.2.4

### Environment (please complete the following information)

Host : https://design.penpot.app/

**Comment by Chepycou** [comment]
Note it also happens for the magnification selection option
![image](https://github.com/penpot/penpot/assets/46412738/732ea097-7cd1-4149-ae28-477b097017d2)

**Comment by Chepycou** [comment]
And second note : after getting it to bug a bunch of times, it finally worked. I could not reproduce what made the difference.

![image](https://github.com/penpot/penpot/assets/46412738/936af503-906c-4f7e-8b4d-b3da9d3a4903)

**Comment by girafic** [comment]
@Raphael124 is this bug also occures on Firefox? If it's only on the Desktop App, please open a new ticket here --> https://sudovanilla.com/code/Korbs/Penpot-Desktop

**Comment by Chepycou** [comment]
Looks like it's a desktop-only issue, gonna upstream/downstream the ticket thanks

**Comment by ghost** [comment]
Interesting...
