### ISSUE TITLE
bug: warped textboxes

### ISSUE THREAD

**Issue by carstenheyer** [uxbox/uxbox#3631]
### Steps To Reproduce

I found no way to reproduce this behaviour. From time to time there are textboxes that have warped edges and as far as i know this is not possible to do while using the implemented tools!?
The only commonality on every occurence is the used font respectively the used typography asset (see: Additional context). But at time only 3 of 50 texts using this asset are warped.

### Expected behavior

It should not be possible to warp text box as long as there is no feature to reset it at any time afterwards.

### Actual behavior

Once a text box is warped there is no possibility to "unwarp"/reset it.

I've copied the concerning text boxes:
https://design.penpot.app/#/view/30d53b09-0290-8050-8001-feacefcec456?page-id=069f6d81-449f-8080-8003-02652a97bc08&section=interactions&index=0&share-id=a4a1c11b-aa9f-8104-8003-02842c8e052c
Call page: "Drafts/bugs/warped textbox"

### Screenshots or video

![warped01](https://github.com/penpot/penpot/assets/88189340/dd5f2d92-a192-4b41-9fe3-ba4e5a341de4)
![warped02](https://github.com/penpot/penpot/assets/88189340/f7a6d70e-854c-4487-978e-f3201d199e2f)

### Desktop (please complete the following information)

- Windows 10
- Chrome Version 117.0.5938.63 (Official Build) (64-bit)

### Environment (please complete the following information)

Error appeared on self hosted:
- Docker Image with Version 1.18

Copied to (and still existing):
https://penpot.app/ 14.09.2023 Version 1.19

### Additional context

typography asset:
- Antenna
  - font weight: bold
  - font size: 16
  - line height: 2
  - uppercase

**Comment by myfunnyandy** [comment]
Hi @carstenheyer,

We've took a look at the Penpot link you've shared but it seems that there're no warped texts there that we can take a look at. Could you please send us the .penpot file so we can take a better look? You could attach it here at GitHub or you could send it to us to support@penpot.app just in case you prefer to do it privately.

Thanks.

**Comment by carstenheyer** [comment]
Hi @myfunnyandy ,

attached you can find the penpot file. I removed everything that is not part of this bug from the file. I hope this will help to fix it.
Thank you.

[bug warped textbox.zip](https://github.com/penpot/penpot/files/12700893/bug.warped.textbox.zip)

**Comment by myfunnyandy** [comment]
@carstenheyer thanks! now taht we have a test file, we'll keep track of this issue at [Taiga](https://tree.taiga.io/project/penpot/issue/5909).

**Comment by madalenapmelo-kp** [comment]
Hi @carstenheyer,

We were unable to reproduce this, could you please confirm whether you are still experiencing it? If you are no longer experiencing this, could you go ahead and close this issue?

**Comment by carstenheyer** [comment]
Checked it and it seems that all occurences since the day i posted it came from copy & paste.
