### ISSUE TITLE
bug: OIDC was working in 1.18.3, but no longer working in 1.19.x

### ISSUE THREAD

**Issue by icsy7867** [uxbox/uxbox#3638]
### Steps To Reproduce

Have a working OIDC connection in 1.18.3, upgrade to 1.19.x (I tried .0,.1,.2)

### Expected behavior

Expecting to authenticate in the same way

### Actual behavior

I get redirected back to the login with this URL:
https://myserver.com#/auth/login?error=unable-to-auth&hint=inconmplete+user+info&type=internal&code=incomplete-user-info

### Environment (please complete the following information)

Docker-compose

### Frontend Stack Trace

```console
Will provide later, I had to restored the service for now
```

### Backend Stack Trace

```console
Will provide later, I had to restored the service for now
```

### Additional context

Restoring back to 1.18.3 allowed me to log back in again.

**Comment by niwinz** [comment]
Hmm, I have tried setting up a clean instance using 1.18.3, configured OIDC with auth0, then upgraded to 1.19.3 without no config changes, and it worked correctly. So without more context is a bit difficult to be able to help you.

**Comment by icsy7867** [comment]
Sorry work got a little more chaotic than anticipated the past week.

```
[2023-09-19 15:43:28.071] I app.main - hint="welcome to penpot", flags="backend-openapi-doc,backend-api-doc,secure-session-cookies,log-emails,backend-worker,login-with-oidc,smtp,email-verification,login-with-ldap", worker?=true, version="1.19.0-10601-g15a9035ed"
[2023-09-19 15:43:31.066] W app.auth.oidc - hint="received incomplete profile info object (please set correct scopes)", info={:backend "oidc", :fullname nil, :email nil, :props {:oidc/at_hash "xxxxxxxx", :oidc/acr "mfa-duo", :oidc/state "xxxxxxxx", :oidc/email_verified "jsmith3@domain.com", :oidc/amr ["DuoSecurityAuthenticationHandler"], :oidc/nbf 1695137911, :oidc/client_id "xxxxx", :oidc/preferred_username "jsmith3", :oidc/family_name "Smith", :oidc/given_name "John", :oidc/name "Smith", :oidc/email "jsmith3@domain.com", :oidc/auth_time 1695126434, :oidc/jti "xxxxxxx"}}
[2023-09-19 15:43:31.073] E app.auth.oidc - hint="error on oauth process"
SUMMARY:
 →  clojure.lang.ExceptionInfo: inconmplete user info (oidc.clj:440)
DETAIL:
 →  clojure.lang.ExceptionInfo: inconmplete user info (oidc.clj:440)
    at: app.auth.oidc$get_info.invokeStatic(oidc.clj:440)
        app.auth.oidc$get_info.invoke(oidc.clj:416)
        app.auth.oidc$callback_handler.invokeStatic(oidc.clj:566)
        app.auth.oidc$callback_handler.invoke(oidc.clj:563)
        app.auth.oidc$fn__29112$fn__29114$fn__29116.invoke(oidc.clj:580)
        app.http.session$wrap_authz$fn__21721.invoke(session.clj:226)
        clojure.core$partial$fn__5908.invoke(core.clj:2640)
        promesa.util.Supplier.get(util.cljc:34)
        java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        java.lang.VirtualThread.run(VirtualThread.java:287)
        java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:174)
        jdk.internal.vm.Continuation.enter0(Continuation.java:327)
        jdk.internal.vm.Continuation.enter(Continuation.java:320)
    dt: {:type :internal,
         :code :incomplete-user-info,
         :hint "inconmplete user info",
         :info {:backend "oidc",
                :fullname nil,
                :email nil,
                :props {:oidc/at_hash "xxxxxxx",
                        :oidc/acr "mfa-duo",
                        :oidc/state "xxxxxxxxxxx",
                        :oidc/email_verified "jsmith3@domain.com",
                        :oidc/amr ["DuoSecurityAuthenticationHandler"],
                        :oidc/nbf xxxx,
                        :oidc/client_id "xxxxxxx",
                        :oidc/preferred_username "jsmith3",
                        :oidc/family_name "John",
                        :oidc/given_name "Smith",
                        ...}}}
```
This might have something to do with an edit you created a little while ago, where you allowed an env variable to be used to specific a different path/location for the various OIDC variables
config.env

```
PENPOT_OIDC_SCOPES=openid profile email
PENPOT_OIDC_EMAIL_ATTR=attributes__email
PENPOT_OIDC_NAME_ATTR=attributes__preferred_username
```

**Comment by icsy7867** [comment]
Ahhhh

So, you also updated the OIDC function previously to work with the token (as specified in the OIDC protocol) instead of using the user-info endpoint.

So I commented those lines out for the custom scopes/locations and everything worked fine!

**Comment by skerit** [comment]
I kept running into this error, but it turns out I had to set `conformIdTokenClaims: false` in my `oidc-provider` configuration, which I'm using as my node-based oidc server.

However: while I no longer get the `received incomplete profile info object (please set correct scopes)` error, Penpot is always redirecting me back to the login page 🤷

Seems like this issue: https://github.com/penpot/penpot/issues/2819
But my well-known info document is in order. And even after I set them manually it does not work.
Guess I'll create a new issue.
