### ISSUE TITLE
Proposal: Page directories/groups - or 'sub-pages'

### ISSUE THREAD

**Issue by SatarisGIT** [uxbox/uxbox#3644]
### Discussed in https://github.com/penpot/penpot/discussions/2935

<div type='discussions-op-text'>

<sup>Originally posted by **SatarisGIT** February 11, 2023</sup>
Hello everyone! 

My problem is, thats in one project I have soo many pages in one feature. I can greatly managing my layers in one page, but in every prototyping system I can't simply create sub-page, page group, or pages directory. I think it would be nice to have some sort or this feature in PenPot :) </div>

**Comment by myfunnyandy** [comment]
Hi @SatarisGIT 

We already have plans for page groups/directories but they are not yet prioritized. We will take your suggestions into consideration once we start working on them. Just in case you are interested, you can see some details at the [user story](https://tree.taiga.io/project/penpot/us/4835).

Thanks!

**Comment by madalenapmelo-kp** [comment]
Hi @SatarisGIT,

As there is already another open issue for this (issue #2936), I'm closing this one to prevent duplicates.

Thanks!
