### ISSUE TITLE
bug: broken local login profile creation : manage.py create-profile stores password in plain text

### ISSUE THREAD

**Issue by yoxteam** [uxbox/uxbox#3651]
### Steps To Reproduce

* start Penpot 1.19.1 using docker-compose behind traefik reverse proxy for ssl
* using flags (among others) disable-registration , disable-smtp , enable-prepl-server , enable-login-with-password , disable-login-with-ldap , enable-secure-session-cookies
* starting with empty non-Docker postgres 13 database with uuid extension
* run docker exec -ti penpot-backend python3 ./manage.py create-profile -e 'some@email.account' -n 'Some Name' -p 'verysecret'
* on database run SELECT password FROM profile WHERE email = 'some@email.account'
* try to log in on the webgui with 'some@email.account' and password 'verysecret'

### Expected behavior

The behaviour on a fresh DB with 1.18.1 is finding a hash like 'argon2id$f924846fae9fa0.....3b61' as password in the database and getting the error "Email or password is incorrect" in the webgui.

### Actual behavior

The behaviour on a fresh DB with 1.19.1 is finding plaintext 'verysecret' as password in the database and login in without error in the webgui.

### Desktop (please complete the following information)

Docker on Ubuntu, using Chrome browser

### Smartphone (please complete the following information)

n/a

### Environment (please complete the following information)

self-hosted, no internet

### Additional context

took me some long time and headbanging to figure out why I was not able to log in... 😅

**Comment by yoxteam** [comment]
Thanks for fixing #3619 
Now tried with 1.19.3 docker images, still plaintext in database, still error on login

When trying the same with 1.18.6 docker images the database contains the hash and the login still works.

So the issue was introduced between 1.18.6 and 1.19.1.

**Comment by yoxteam** [comment]
Updated the original report post. I see I incorrectly reported which version resulted in the hash and which version resulted in the plaintext... (I swapped them around...). The text is now correct and makes more sense with the later comment. Sorry for any confusion. The issue is still the same.

**Comment by katerius** [comment]
I installed penpot using docker and got the same problem (1.19.3). I got a error on login when using the python script ...
I use Nginx Proxy Manager as reverse proxy and i tried without reverse proxy this is not the problem.
also I use the postgres container provided by default

**Comment by yoxteam** [comment]
@niwinz Some users requested me to update to the latest Penpot, but we are stuck at 1.18.6 because of this issue. When we switch to the latest version we are unable to create new working local accounts.

I spend quite some time trying to determine which commit [between 1.18.6 and 1.19.1](https://github.com/penpot/penpot/compare/1.18.6...1.19.1) created this issue, but I was unable to. My inexperience with Clojure or similar languages might be the problem.

Could you please help determine what caused this problem?

**Comment by CiaranGruber** [comment]
Still experiencing the same issues with a fresh Penpot install (v1.19.3). I've had to downgrade the install to 1.18.6 for now as the normal log-in process seemed to be buggy as well (Pressing Create account didn't change the site, but still added to the database, however attempting to then log in failed).

As an additional note, I did downgrade to 1.19.0 first, however this had the same bug, suggesting the commit is somewhere before that release but after 1.18.6
