### ISSUE TITLE
Contribution for Portuguese (Portugal) translation

### ISSUE THREAD

**Issue by TheScientistPT** [uxbox/uxbox#3657]
Hello,

I'm a Portuguese native speaker and I would like to help translate Penpot's frontend on Weblate.

My Weblate username is TheScientistPT.

Thank you in advance and kind regards.

**Comment by myfunnyandy** [comment]
Hi @TheScientistPT,

We've already invited you to the translation project, once you accept the invitation you'll be able to start translating.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
