### ISSUE TITLE
bug: Issue when resizing a duotone FA icon

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3659]
### Steps To Reproduce

1. Import a duotone svg icon from FA (need Pro subscribing)
2. Resize the icon
3. One layer of the icon hierarchy, making the duotone possible, is not resized, and can not be

### Expected behavior

All the sub-elements of the svg are resized the same way as the icon

### Actual behavior

The "svg-style" layer is not resized. Consequently, there are issues when hovering it with the mouse.

### Screenshots or video

[Capture vidéo du 2023-09-21 14-20-19.webm](https://github.com/penpot/penpot/assets/62602652/47c48744-2871-45de-98d0-5610cb712b30)

### Desktop (please complete the following information)

Chrome 117
Ubuntu 23.04

**Comment by myfunnyandy** [comment]
Hi @NicolasLeboeuf,

Unfortunately we don't have a FA subscription so we are not able to reproduce the issue. Could you please send us an example to support@penpot.app?

Thanks!

**Comment by NicolasLeboeuf** [comment]
Hi, sorry I didn't see your answer, I'm on it

**Comment by madalenapmelo-kp** [comment]
@NicolasLeboeuf Thank you for reporting! This issue is being managed on Taiga: https://tree.taiga.io/project/penpot/issue/5935
