### ISSUE TITLE
bug: updating a component causes instances to be displayed dismantled

### ISSUE THREAD

**Issue by roberto-red** [uxbox/uxbox#3660]
### Steps To Reproduce

You have a master component and you already have several instances in the design. Now, you update the main component.

### Expected behavior

The instances applied in the layout are updated correctly.

### Actual behavior

I have a master component and I already have several instances in the design. When I updated the main component, the instances that were already applied to the design were dismounted. But it seems like a display problem because without having touched anything afterwards, everything has been put back in place, or if you double click on the text box, it goes back into place.

### Screenshots or video

Master component:

![imagen](https://github.com/penpot/penpot/assets/69057305/ee0aef42-6422-49fa-89f5-c847b52acc31)

Instances dismounted:

![imagen](https://github.com/penpot/penpot/assets/69057305/653bb96d-fb78-4b52-abaa-29e9efa23b6d)

https://github.com/penpot/penpot/assets/69057305/68488ee5-7929-401b-9728-1c5da3b74530

### Desktop (please complete the following information)

- OS: macOS
- Browser: Chrome (also observed on Firefox 117.0)

### Environment (please complete the following information)

- Host: https://design.penpot.app
- Version: 1.19

This started to happen **after a Penpot UI crash**, like https://github.com/penpot/penpot/issues/3661 and https://github.com/penpot/penpot/issues/3662. We don't recall experiencing it before. 

### Additional context

(I'm reporting this on behalf of a design colleague)

**Comment by madalenapmelo-kp** [comment]
As per my [comment](https://github.com/penpot/penpot/issues/3662#issuecomment-2066645129) on issue #3662, I'm closing this issue but please reopen it if this issue resurfaces!
