### ISSUE TITLE
bug: missing or pixelated boards rendering

### ISSUE THREAD

**Issue by roberto-red** [uxbox/uxbox#3661]
### Steps To Reproduce

Have a Penpot file, with 8 pages, several master components, images, and flex-layout applied. Now, zoom in and out on a board or swipe from one board to the other.

### Expected behavior

That the file is displayed well, without pixelation.

### Actual behavior

The file looks pixelated at times, and a broken image icon appears when in fact what is behind it is a layout with text and different layers.

### Screenshots or video

Pixelated rendering:
![imagen](https://github.com/penpot/penpot/assets/69057305/ced22300-b499-4019-adf2-2dcd56d61b00)

Broken image icon:
![imagen](https://github.com/penpot/penpot/assets/69057305/fe713b57-df35-4df6-8bd3-71d9ca2bf97d)

### Desktop (please complete the following information)

OS: macOS
Browser: Chrome (also observed on Firefox 117.0)

### Environment (please complete the following information)

Host: https://design.penpot.app/
Version: 1.19

This started to happen **after a Penpot UI crash**, like https://github.com/penpot/penpot/issues/3660 and https://github.com/penpot/penpot/issues/3662. We don't recall experiencing it before.

### Additional context

(I'm reporting this on behalf of a design colleague)

**Comment by myfunnyandy** [comment]
Hi @roberto-red,

Could you send us the .penpot file to support@penpot.app so we can take a deeper look at it?

Thanks!

**Comment by roberto-red** [comment]
Sure! 👌

**Comment by madalenapmelo-kp** [comment]
@roberto-red Thank you for reporting! This issue is being managed on Taiga: https://tree.taiga.io/project/penpot/us/5828

**Comment by hades200082** [comment]
@Alotor I'm still getting this issue in Penpot 2. 

![image](https://github.com/penpot/penpot/assets/1023581/42a1ae9a-4eb5-48b5-941d-f0526e7aefd5)

Self-hosted using Docker Compose & Coolify.

**Comment by itsgabrieloliver** [comment]
@hades200082 Getting the same issue on v2
