### ISSUE TITLE
bug: elements are displayed dismantled

### ISSUE THREAD

**Issue by roberto-red** [uxbox/uxbox#3662]
### Steps To Reproduce

You have several elements built with flex-layout, and you go to another place in the document and return to where you had the element.

### Expected behavior

The design of the element remains as you left it.

### Actual behavior

The element appears disassembled. It seems like a display problem because without having touched anything afterwards, everything has been put back in place, or if you double click on the text box, it goes back into place.

### Screenshots or video

![imagen](https://github.com/penpot/penpot/assets/69057305/22e2c1f5-f37b-4e3a-b49f-4c4dfdd79d50)

https://github.com/penpot/penpot/assets/69057305/435a08a2-1cb8-4bc7-852c-084045da4e80

### Desktop (please complete the following information)

OS: macOS
Browser: Chrome (also observed on Firefox 117.0)

### Environment (please complete the following information)

Host: https://design.penpot.app/
Version: 1.19

This started to happen after a Penpot UI crash, like https://github.com/penpot/penpot/issues/3660 and https://github.com/penpot/penpot/issues/3661. We don't recall experiencing it before.

### Additional context

(I'm reporting this on behalf of a design colleague)

The underlying cause may be the same as https://github.com/penpot/penpot/issues/3660, but this one doesn't use components, just flex layout.

**Comment by madalenapmelo-kp** [comment]
Hi @roberto-red,

Could you please confirm if you are still experiencing this behavior as well as the one reported on #3660?

**Comment by roberto-red** [comment]
I can't reproduce it right now using Firefox 124.0 (aarch64) on macOS 14.3.1.

But as I reported this on behalf of my design colleage @AnnaMassana, let's see if she can confirm it first-hand.

**Comment by madalenapmelo-kp** [comment]
Hi @roberto-red,

As you haven't been able to reproduce this and we haven't received feedback from @AnnaMassana, I'm closing this issue as well as #3660 but if you continue to experience it please feel free to open a new one!
