### ISSUE TITLE
bug: unlinked stroke color styles after duplicating a document

### ISSUE THREAD

**Issue by roberto-red** [uxbox/uxbox#3682]
### Steps To Reproduce

You have a document with various styles of colors created and applied on borders, svg paths... (everything that has a stroke applied) Then, you download this document and then upload in penpot (duplicate).

### Expected behavior

The color styles are still applied to all those elements that we mentioned above.

### Actual behavior

When I duplicate this document, the color styles appear unlinked from those elements where they were correctly applied in the base document. 

### Screenshots or video

Base document (stroke "dark"):

![imagen](https://github.com/penpot/penpot/assets/69057305/41c6acde-b20c-4b48-8732-65d4b78fbea4)

Duplicate document (stroke "hex. code"):

![imagen](https://github.com/penpot/penpot/assets/69057305/e2b830ab-fcbc-4d12-a79c-d23c10268b4e)

Video:

https://github.com/penpot/penpot/assets/69057305/e2a2b0f5-437f-4bb9-8de7-4a02ece98943

### Desktop (please complete the following information)

- OS: macOS
- Browser: Chrome (also observed on Firefox 117.0)

### Environment (please complete the following information)

- Host: https://design.penpot.app
- Version: 1.19

`.penpot` file: https://github.com/PIWEEK/easyfest/blob/71ceb0de39afdd946222e2d4568c5e05c91709b7/easyfest-design-template.penpot

### Additional context

(I'm reporting this on behalf of a design colleague)

**Comment by roberto-red** [comment]
May be a duplicate of https://github.com/penpot/penpot/issues/3522, but we are not sure.

**Comment by madalenapmelo-kp** [comment]
Hi @roberto-red,

I was unable to reproduce this issue, could you please confirm if you are still experiencing it?

**Comment by AnnaMassana** [comment]
Hi @madalenapmelo-kp, I just checked this and it seems to be fixed now, thanks!

**Comment by roberto-red** [comment]
(@madalenapmelo-kp: I reported this on behalf of @AnnaMassana, so she is in fact the design colleage that experienced this firsthand)
