### ISSUE TITLE
bug: changed typography assets' properties are not reflected on pages other than the active one

### ISSUE THREAD

**Issue by roberto-red** [uxbox/uxbox#3683]
### Steps To Reproduce

You have a document with several font styles created and applied on different pages... Then, you decide to change some parameters of the font styles through the library.

### Expected behavior

Changes made to the library's font styles are automatically reflected on all pages of the document.

### Actual behavior

Changes made to library font styles are only reflected on the page I am viewing right at the time of the changes. If I move to another page, I don't see the changes applied, I have to double click on the text box for it to show correctly.

### Screenshots or video

https://github.com/penpot/penpot/assets/69057305/4061c8db-3015-47e0-ab7e-69adfbff5ed7

### Desktop (please complete the following information)

- OS: macOS
- Browser: Chrome (also observed on Firefox 117.0)

### Environment (please complete the following information)

- Host: https://design.penpot.app
- Version: 1.19

`.penpot` file: https://github.com/PIWEEK/easyfest/blob/71ceb0de39afdd946222e2d4568c5e05c91709b7/easyfest-design-template.penpot

### Additional context

(I'm reporting this on behalf of a design colleague)

**Comment by madalenapmelo-kp** [comment]
Hi @roberto-red,

Thank you for reporting this! I have created an issue for this, you can see at Taiga [here](https://tree.taiga.io/project/penpot/issue/6027).
