### ISSUE TITLE
bug: fit-content not recalculated after deleting an element

### ISSUE THREAD

**Issue by roberto-red** [uxbox/uxbox#3684]
### Steps To Reproduce

You have a layout made with flex-board with fit-content applied, then you delete a section of the layout.

### Expected behavior

The design board fit to the content.

### Actual behavior

The layout board does not fit the content, you must press "fix-height" and then "fit-content" to fit correctly.

### Screenshots or video

https://github.com/penpot/penpot/assets/69057305/6e9446ee-4812-41d9-844a-69adb5a7c095

### Desktop (please complete the following information)

- OS: macOS
- Browser: Chrome (also observed on Firefox 117.0)

### Environment (please complete the following information)

- Host: https://design.penpot.app
- Version: 1.19

`.penpot` file: https://github.com/PIWEEK/easyfest/blob/71ceb0de39afdd946222e2d4568c5e05c91709b7/easyfest-design-template.penpot

### Additional context

(I'm reporting this on behalf of a design colleague)

**Comment by madalenapmelo-kp** [comment]
Hi @roberto-red, 

This issue is now being managed on Taiga, you can find the details [here](https://tree.taiga.io/project/penpot/issue/5968). Thank you for reporting this!
