### ISSUE TITLE
Contributing to translate Penpot (for missing Turkish texts)

### ISSUE THREAD

**Issue by merihg** [uxbox/uxbox#3689]
Hi there!

I'm Turkish native speaker and I would like to help translate Penpot's frontend on Weblate.

My Weblate username is: merih

Thanks!

**Comment by madalenapmelo-kp** [comment]
Hi @merihg,

We've already invited you to the translation project, once you accept the invitation you'll be able to start translating!

You can find more information about how to contribute to the translations here: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!

**Comment by merihg** [comment]
Thanks! I made many additions. However, there are formal and informal sentences in the Turkish translations. What should the general approach be? @madalenapmelo-kp
