### ISSUE TITLE
thumbnail is performance killer 

### ISSUE THREAD

**Issue by VVege** [uxbox/uxbox#3696]
### Is your feature request related to a problem? Please describe.

The thumbnail mechanism of Penpot is a performance killer if there are many boards on my page.
Manifestation 1:
When entering the page, thumbnails for all boards will be loaded, which might be dozens and take up several hundred megabytes, prolonging the loading speed.
Manifestation 2:
When operating elements on a board, the thumbnail will be updated. If the board has a high resolution, the process of generating a thumbnail will consume CPU, leading to operational lag.

### Describe the solution you'd like.

I would like to ask what problems the thumbnail mechanism aims to solve primarily, and what issues will arise if I remove all thumbnail mechanisms from the code?

Thank you.

**Comment by AzazelN28** [comment]
Hi @VVege, thanks for reporting this issue

This is a known issue, in fact we're trying to tackle some of these problems right now, but thumbnails (they should be called impostors or imposters, they replace real content with "fake" content) are necessary to make things like panning or zooming better in terms of performance and user responsiveness.

**Comment by VVege** [comment]
Thank you for the response; I fully understand the rationale behind this mechanism. My users frequently complain about the slow loading speed of the documents and laggy operation. Therefore, I plan to remove all thumbnail-related mechanisms in my fork version: including downloading, caching, and updating.

I'd like to confirm two issues:
1. Is the thumbnail solely used as a substitute for the DOM within the workspace, without any other purpose?
2. Which aspects might be most affected if it is removed?

I have also made some preliminary attempts:
For the first question, I have not found any other uses.
For the second question, I found that both my loading speed and operation lag were optimized.

These two points have strengthened my idea of wanting to remove the thumbnail mechanism. Moreover, as my understanding might not be exhaustive and there may be oversights, I am eagerly awaiting your advice. Thank you so much.

**Comment by AzazelN28** [comment]
To go into a little more detail on why thumbnails (imposters) are used, they are used to:
- Reduce DOM complexity when necessary (usually in overviews where we want to have an overview of a page with several boards and don't need to see the details).
- Speed up board rendering: if a board is very complex and has many nested elements or elements with effects (blur, shadows, etc), rendering these elements in each frame can seriously affect performance and responsiveness when there are multiple complex boards on screen.

Obviously it has its tradeoffs:
- Longer load times when opening a file (it shouldn't be problematic with good network connections, also all image decoding is async and should not affect responsiveness).
- It takes up more database space and more memory space.
- There may be small discrepancies between SVG and PNG rendering.
- Sometimes when boards are too tall or too wide they can be pixelated or blurred.

We are aware of all these problems and we are trying to find the best solution to make working with penpot easier, faster and better.

**Comment by VVege** [comment]
Thank you for your response. After reading your reply, I carefully experienced the issues that arise after removing the thumbnail mechanism. Indeed, when there are many DOM elements, zooming and panning do exhibit lag. I plan to add a settings button to my forked version, allowing users to choose whether to disable the thumbnail mechanism themselves.

**Comment by VVege** [comment]
> To go into a little more detail on why thumbnails (imposters) are used, they are used to:为了更详细地了解为什么使用缩略图（冒名顶替者），它们用于：
> 
> * Reduce DOM complexity when necessary (usually in overviews where we want to have an overview of a page with several boards and don't need to see the details).必要时降低 DOM 复杂性（通常在概述中，我们希望对包含多个板的页面进行概述，而不需要查看详细信息）。
> * Speed up board rendering: if a board is very complex and has many nested elements or elements with effects (blur, shadows, etc), rendering these elements in each frame can seriously affect performance and responsiveness when there are multiple complex boards on screen.加快电路板渲染速度：如果电路板非常复杂，并且有许多嵌套元素或具有效果（模糊、阴影等）的元素，则当屏幕上有多个复杂的电路板时，在每一帧中渲染这些元素会严重影响性能和响应能力。
> 
> Obviously it has its tradeoffs:显然，它有其权衡：
> 
> * Longer load times when opening a file (it shouldn't be problematic with good network connections, also all image decoding is async and should not affect responsiveness).打开文件时加载时间更长（良好的网络连接应该没有问题，所有图像解码都是异步的，不应影响响应能力）。
> * It takes up more database space and more memory space.它占用更多的数据库空间和更多的内存空间。
> * There may be small discrepancies between SVG and PNG rendering.SVG 和 PNG 渲染之间可能存在细微差异。
> * Sometimes when boards are too tall or too wide they can be pixelated or blurred.有时，当板太高或太宽时，它们可能会像素化或模糊。
> 
> We are aware of all these problems and we are trying to find the best solution to make working with penpot easier, faster and better.我们意识到所有这些问题，我们正在努力找到最佳解决方案，使使用penpot更容易，更快，更好。

Thank you for your response. After reading your reply, I carefully experienced the issues that arise after removing the thumbnail mechanism. Indeed, when there are many DOM elements, zooming and panning do exhibit lag. I plan to add a settings button to my forked version, allowing users to choose whether to disable the thumbnail mechanism themselves.

**Comment by VVege** [comment]
> To go into a little more detail on why thumbnails (imposters) are used, they are used to:
> 
> * Reduce DOM complexity when necessary (usually in overviews where we want to have an overview of a page with several boards and don't need to see the details).
> * Speed up board rendering: if a board is very complex and has many nested elements or elements with effects (blur, shadows, etc), rendering these elements in each frame can seriously affect performance and responsiveness when there are multiple complex boards on screen.
> 
> Obviously it has its tradeoffs:
> 
> * Longer load times when opening a file (it shouldn't be problematic with good network connections, also all image decoding is async and should not affect responsiveness).
> * It takes up more database space and more memory space.
> * There may be small discrepancies between SVG and PNG rendering.
> * Sometimes when boards are too tall or too wide they can be pixelated or blurred.
> 
> We are aware of all these problems and we are trying to find the best solution to make working with penpot easier, faster and better.

Thank you for your response. After reading your reply, I carefully experienced the issues that arise after removing the thumbnail mechanism. Indeed, when there are many DOM elements, zooming and panning do exhibit lag. I plan to add a settings button to my forked version, allowing users to choose whether to disable the thumbnail mechanism themselves.
