### ISSUE TITLE
Translation into Afrikaans

### ISSUE THREAD

**Issue by hugovermaak** [uxbox/uxbox#3706]
I would like to request access to translate PenPot into Afrikaans. It is a language that is not currently listed in Weblate. Not sure how to go about it.

**Comment by hugovermaak** [comment]
Oh Weblate handle is @hugovermaak

**Comment by madalenapmelo-kp** [comment]
Hi @hugovermaak ,

I've added you to the translation project and also the Afrikaans language to the languages list! We're always really happy to add a new language! Now you just need to enter [here](https://hosted.weblate.org/projects/penpot/frontend/af/) and start translating. 

Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!

**Comment by hugovermaak** [comment]
Hi @madalenapmelo-kp. The "Save and continue" button is disabled. When I hover over it the tooltip reads: "Insufficient privilages for saving translations"

**Comment by hugovermaak** [comment]
@madalenapmelo-kp so sorry, never saw the email invite. Accepted it now. All is good.
