### ISSUE TITLE
bug: Penpot Desktop don't have "exit" button on Linux Cinnamon and app icon

### ISSUE THREAD

**Issue by RuanLucasGD** [uxbox/uxbox#3710]
### Steps To Reproduce

I tried use penpot desktop on my linux mint cinnamon but the editor don't have a "exit" button and don't have app icon on apps bar.

### Expected behavior

Penpot desktop have show exit button and app icon

### Actual behavior

Penpot desktop don't show exit button and app icon

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/79365912/1e71a4d8-096d-4da5-9a16-0954dc8c3c6f)
![image](https://github.com/penpot/penpot/assets/79365912/e044658a-2286-4d22-aba0-9162771a23a0)

### Desktop (please complete the following information)

![image](https://github.com/penpot/penpot/assets/79365912/71af6e8f-d5e8-42ee-b66a-2cd7d59855e2)

**Comment by girafic** [comment]
@RuanLucasGD This issue is not related to Penpot, please open a new ticket for the desktop app here --> https://sudovanilla.com/code/Korbs/Penpot-Desktop
