### ISSUE TITLE
bug: Board titles illegible due to overlap when zoomed out

### ISSUE THREAD

**Issue by arcastro** [uxbox/uxbox#3729]
### Steps To Reproduce

1. Place two boards side by side, each with their own name
2. Zoom out

### Expected behavior

* Board titles should never overlap
* If user zooms out too much and the board becomes smaller, then the board titles should also become smaller so that the width of the board title never exceeds the width of the board.
![image](https://github.com/penpot/penpot/assets/4576794/6d3898ae-dc86-4f80-af8a-a55b9b06e85c)

### Actual behavior

* The board titles are always the same size irrespective of zoom, resulting in illegible overlapping of titles
![image](https://github.com/penpot/penpot/assets/4576794/92d82484-cb95-4ae2-82b7-8c94bb11a854)

**Comment by madalenapmelo-kp** [comment]
Hi @arcastro,

Thank you for reporting this! This is now being managed on Taiga, you can find more details at the user story [here](https://tree.taiga.io/project/penpot/issue/6065).

**Comment by arcastro** [comment]
@madalenapmelo-kp , looks like this issue can be closed (according to the Taiga story you linked).

I have not been able to verify the fix myself, since the [docker image](https://hub.docker.com/r/penpotapp/frontend/tags) was last updated seven months ago for 1.19.3, but I'm excited to try it out once 1.20 comes out.
