### ISSUE TITLE
Contributing to French localization 

### ISSUE THREAD

**Issue by luigidotmoe** [uxbox/uxbox#3763]
Hi there,

I started using Penpot not long ago because I can't bear Figma anymore and noticed that there are some strings missing a French translation.

As a French native, I'd be glad to help with this chore. My Weblate username is the same as here on GitHub.

**Comment by madalenapmelo-kp** [comment]
Hi @luigidotmoe,

We've already added you to the translation project. Here you can find more information about how to contribute to the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
