### ISSUE TITLE
bug: options menus don't work in dashboard in Firefox

### ISSUE THREAD

**Issue by prolewall** [uxbox/uxbox#3770]
### Steps To Reproduce

1. Open Firefox browser
2. Go to Projects dashboard
3. Click on any Options button for a project, file or draft

### Expected behavior

An appropriate list of options appears for each of these buttons.

### Actual behavior

Nothing happens, the buttons don't do anything.

### Screenshots or video

When clicking on options in Firefox nothing happens (the same is for any "three dots" button):
![image](https://github.com/penpot/penpot/assets/66006229/b44509ba-1d78-4287-8d36-b3085b10c2d5)

The same action works in Opera:
![image](https://github.com/penpot/penpot/assets/66006229/2f9c6b06-1b2a-4382-8203-329a317eb658)

### Desktop (please complete the following information)

- OS: Windows 10
- Browser: Firefox 119.0 (64 bit)

**Comment by absurdity9** [comment]
It works for me - what version of Firefox are you using? Do you have console errors?
![Screenshot 2023-11-06 at 13 20 17](https://github.com/penpot/penpot/assets/7194972/c8367d0a-ec56-423d-89f1-125579c4c9be)
![Screenshot 2023-11-06 at 13 21 02](https://github.com/penpot/penpot/assets/7194972/20751c18-a98a-4461-b614-149a5ee2d8e4)

**Comment by prolewall** [comment]
Okay I figured it out, I'm using [PopUpOFF extension](https://popupoff.org/) and it seems it's breaking this site. I guess I'll report it there. Sorry for the trouble, I'll close the issue.
