### ISSUE TITLE
bug: broken project 

### ISSUE THREAD

**Issue by Ali1Jamal** [uxbox/uxbox#3778]
### Steps To Reproduce

...

### Expected behavior

If they were removed, they should not appear after opening my project. If they weren't removed, they should work and not just disappear.

### Actual behavior

the elements it's just disappear.

### Screenshots or video

https://github.com/penpot/penpot/assets/40013555/7d0ef428-79cd-474d-86cf-c783295d3442

### Desktop (please complete the following information)

windows 10
microsoft edge Version 119.0.2151.44 (Official build) (64-bit)

### Environment (please complete the following information)

https://design.penpot.app/

### Frontend Stack Trace

```console
no errors after opening the project
```

### Backend Stack Trace

```console
...
```

### Additional context

I’m working on website design and I’ve noticed that the home view is just replicating everything. It shows a tree view as a list without nested elements, or it shows a tree view and replicates the elements without nesting, I’ve reloaded the project two or three times and the problem is still there. So, I thought I might have duplicated the element by mistake.
 So, I just removed the elements and they were indeed removed from the view(This indicates that I didn't duplicate the elements by mistake), I then pressed Ctrl+Z. However, after a minute or two, it showed me an internal error. I reloaded the project as shown in the video. The disappearing elements are the ones that I removed and then restored using Ctrl+Z.
If they were removed, they should not appear after opening my project. If they weren't removed, they should work and not just disappear.

**Comment by madalenapmelo-kp** [comment]
Hi @Ali1Jamal,

Thank you for reporting this! Could you send the .penpot file where you experienced this to [support@penpot.app](mailto:support@penpot.app)? In case you need additional details on how to export the .penpot file, it is explained [here](https://help.penpot.app/user-guide/import-export/#importing-export).

**Comment by Ali1Jamal** [comment]
@madalenapmelo-kp ok i'm not interested in fixing the project but I'm reporting this issue to make penpot better.
I'm sending the file to the support now.
