### ISSUE TITLE
feature: Hue bar in color picker wider

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3779]
### Is your feature request related to a problem? Please describe.

I think the hue in the color picker could be at least twice the height/wideness as it is now:

![image](https://github.com/penpot/penpot/assets/433707/61a6232a-f8af-471d-8370-b1ae9985ec79)

### Describe the solution you'd like.

It would be easier to pick the hue if the bar was wider - targeting a wider area with the mouse would be easier.

You can see the same problem when a scrollbar is very thin - that's why they are a bit wider:

![image](https://github.com/penpot/penpot/assets/433707/ec9d2712-6728-46cd-b125-abc66085cf47)

**Comment by madalenapmelo-kp** [comment]
Hi @ile,

Thank you for the suggestion! I have opened an issue on Taiga so that we can consider this enhancement: https://tree.taiga.io/project/penpot/issue/6127 :slightly_smiling_face:

**Comment by ile** [comment]
Thanks. "Wider" was a wrong word, but more height in it. I'm sure everybody understood anyway.
