### ISSUE TITLE
bug: text auto width bug

### ISSUE THREAD

**Issue by VVege** [uxbox/uxbox#3782]
### Steps To Reproduce

When clicking on the text field width, it continuously shrinks under certain circumstances.
The specific situation is: a section of text has different colors and font sizes."

### Expected behavior

width change directly and Accurately，not animation。

### Actual behavior

It will undergo an animation process, slowly getting smaller, sometimes to the point where only one character fits on a line.

can test it in
https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-ce88da41e26e/b509ea44-7222-80be-8003-67055f611eb7?page-id=b509ea44-7222-80be-8003-67055f611eb8

### Screenshots or video

https://github.com/penpot/penpot/assets/41810973/2598d0e0-ba64-4752-9d62-53c05ad5e799

https://github.com/penpot/penpot/assets/41810973/d139a4df-ac97-4a10-a388-c4d4258cc395

### Desktop (please complete the following information)

mac os and windows 

### Environment (please complete the following information)

chrome
penpot 1.19.2

**Comment by madalenapmelo-kp** [comment]
Hi @VVege,

Thanks for reporting this! Could you send the .penpot file to support@penpot.app? In case you need additional details on how to export the .penpot file, it is explained [here](https://help.penpot.app/user-guide/import-export/#importing-export).
