### ISSUE TITLE
bug: copy and paste board and delete/hide element set text width to 0.01

### ISSUE THREAD

**Issue by carstenheyer** [uxbox/uxbox#3784]
### Steps To Reproduce

I don't know how to reproduce it on purpose. From time to time it occurs while copying/pasting boards. 
Using the attached penpot file you can try to reproduce it with the following steps:

1. delete the red colored "title" text
2. when duplicating the board with copy and paste the text elements inside the layouted area will be further rearranged

### Expected behavior

Deleting a single element should not change the size, height, coordinates of any other element.

P.S. In my case the coordinates my be changed because of the layouted elements.

### Actual behavior

Deleting (and also hide) an element changes other elements size (and height (and coordinates)).

### Screenshots or video

![2023-11-08 1 19 text width to zero](https://github.com/penpot/penpot/assets/88189340/d6ae8063-29e8-4cc7-9106-d67d9f31465a)

### Desktop (please complete the following information)

- Windows 10
- Chrome Version 119.0.6045.106 (Official Build) (64-bit)

### Environment (please complete the following information)

Error appeared on self hosted:
- Docker Image with Version 1.19

### Additional context

The penpot file with the boards from the screenshot:
[bug width set to 0.zip](https://github.com/penpot/penpot/files/13298000/bug.width.set.to.0.zip)

**Comment by madalenapmelo-kp** [comment]
Hi @carstenheyer,

Thanks for reporting this! I have open an issue on Taiga so that we can look into it: https://tree.taiga.io/project/penpot/issue/6126
