### ISSUE TITLE
bug: backend not working properly

### ISSUE THREAD

**Issue by RonElwaya** [uxbox/uxbox#3816]
### Steps To Reproduce

The problems happen on their own after you are logged in for some time (sometimes after 5 minutes sometimes after 30). 

### Expected behavior

The app will work as it should without stuff happening randomly.

### Actual behavior

There are a few problems that occur:
- stuff moves around without touching them
- sometime ctrl+Z not working 
- takes alot of time to save changes
- after loging in again objects sometimes change sizes

### Environment (please complete the following information)

Backend running on a container docker image 1.18.4 with 1600m CPU and 4GB RAM

**Comment by madalenapmelo-kp** [comment]
Hi @RonElwaya,

Are you still experiencing these issues as of the latest version?
