### ISSUE TITLE
bug: Messing up page components and not loading page view

### ISSUE THREAD

**Issue by alimoradi67** [uxbox/uxbox#3824]
### Steps To Reproduce

1. go to " penpot"
2. go to "my team" and " my projects"
3. open a project file that contains several pages and each page is designed with frames, components, design kits, etc.

### Expected behavior

When opening the project pages, the components of the designed pages can be displayed without any problems and without moving, and they have an acceptable performance and there is no problem in displaying the overall image of the pages. The components of the pages are in place and according to the design.

### Actual behavior

I expected pages to load without problems and with acceptable performance. But some pages are loaded incompletely. The thumbnail image of some pages is not loaded and a default image is displayed instead. And even by clicking on it, the screen image will be displayed at once.
And I have to clear the browser cache again for it to be displayed. This problem is while the PenPot self-host server in our collection is very strong and the systems of designers and programmers are very strong.
Parts of the pages have been messed up and moved many times. both in frames and auto layout.
And I have to return them to their original state in Auto Layout by show/hide their layer and in frames by realigning them.

### Desktop (please complete the following information)

-OS ( Windows 10 enterprise)
- Browser & version ( Chrome 119 )
- Ram ( 24 GB)
- Graphic (NVIDIA GeForce GTX TITAN X)
- CPU ( Intel(R) Core(TM) i5-8400 )

### Environment (please complete the following information)

- Host ( Local instance )
Os version ( ubuntu, updated )

**Comment by madalenapmelo-kp** [comment]
Hi @alimoradi67,

Could you let me know if you are still experiencing this issue as of the latest update?
