### ISSUE TITLE
bug: eyedropper tool doesn't work

### ISSUE THREAD

**Issue by axrolld** [uxbox/uxbox#3830]
### Steps To Reproduce

From a project with different layers, i'm trying to pick one of the oclors with the eyedropper.

### Expected behavior

The eyedropper should allow me to pick a color from my different layers.

### Actual behavior

They tool's only giving me transparent color, no matter where my pointer is.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/86296016/d568225d-31ee-4489-90b2-25d593ccb89f)

### Desktop (please complete the following information)

Chrome
Windows 11

**Comment by madalenapmelo-kp** [comment]
Hi @axrolld,

Thank you for reporting this! We are already working on PR #3814 to fix this issue.

**Comment by axrolld** [comment]
My bad i didn't see this PR ! Thanks a lot !
