### ISSUE TITLE
bug: export timeout on design.penpot.app

### ISSUE THREAD

**Issue by mstieranka** [uxbox/uxbox#3839]
### Steps To Reproduce

1. Go to https://design.penpot.app
2. Load the project contained in export-fail.penpot (contained in the following ZIP due to GitHub constraints: [export-fail.zip](https://github.com/penpot/penpot/files/13440829/export-fail.zip))
3. Click on "2480x520 board" board in the "Page 1" sidebar section
4. Click "Export 1 element" with scale set to 1x and format set to PNG (though no other format works either)

### Expected behavior

The image is exported and downloaded.

### Actual behavior

A message about a backend error is shown.

### Desktop (please complete the following information)

Windows 11, Firefox 119.0.1

### Environment (please complete the following information)

Host: https://design.penpot.app

### Frontend Stack Trace

```console
Server Error [errors.cljs:46:5](https://design.penpot.app/js/app/main/errors.cljs)
{:type :server-error}
```

### Backend Stack Trace

```console
{"~:type":"~:server-error","~:hint":"locator.screenshot: Timeout 29978.542999267578ms exceeded.\n=========================== logs ===========================\ntaking element screenshot\n  waiting for element to be visible and stable\n============================================================"}
```

### Additional context

If adjusting the render period is somehow possible when selfhosting, do let me know, since I don't mind hosting an instance myself, but it would probably be good for other users if this worked on the shared instance as well.

**Comment by madalenapmelo-kp** [comment]
Hi @mstieranka,

Thank you for reporting this! I have opened an issue on Taiga so that we can look into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/6228
