### ISSUE TITLE
bug: In the team project, the color eyedropper tool is not functioning.

### ISSUE THREAD

**Issue by hongbo-code** [uxbox/uxbox#3885]
### Steps To Reproduce

1.9.2
In the team project,
When selecting：
![image](https://github.com/penpot/penpot/assets/878648/81d9c128-e80a-47da-ba39-dad4b644f7c8)
after selection：
![image](https://github.com/penpot/penpot/assets/878648/eb4100cd-1bc4-420f-b8f7-1e298189583a)

### Expected behavior

The issue only occurs in the team project，your penpot has no bugs.

### Actual behavior

 the color eyedropper tool is not functioning.

### Desktop (please complete the following information)

win11 edge&chrome

**Comment by madalenapmelo-kp** [comment]
Hi @bobo521bobo,

Thank you for reporting this! Could you [export this file](https://help.penpot.app/user-guide/import-export/) and send it to support@penpot.app so that we can look into this?

**Comment by bobo521bobo** [comment]
> Hi @bobo521bobo,
> 
> Thank you for reporting this! Could you [export this file](https://help.penpot.app/user-guide/import-export/) and send it to [support@penpot.app](mailto:support@penpot.app) so that we can look into this?

Email sent, also I logged in using locally deployed gitlab, might that have something to do with it?

**Comment by hongbo-code** [comment]
> Hi @bobo521bobo,
> 
> Thank you for reporting this! Could you [export this file](https://help.penpot.app/user-guide/import-export/) and send it to [support@penpot.app](mailto:support@penpot.app) so that we can look into this?

I found the problem, the color eyedropper tool only works if there is a board on the page, if there is no board, it doesn't work.

**Comment by miguelgargallo** [comment]
In my case I cannot use the tool even with board, here is a small video demo of some seconds, may help the team to fix this, and make things easier https://youtu.be/bAzAkiBTY30
