### ISSUE TITLE
feature: Add user option to change or disable auto-save interval 

### ISSUE THREAD

**Issue by JMHeartley** [uxbox/uxbox#3896]
### Is your feature request related to a problem? Please describe.

When using this product the UI often lags because I'm making a change/moving an object while it's trying to save my project automatically. Let's say I'm using Ctrl + Arrow Key to move an object 10 pixels down. If I use the hot key a few times quickly, the object jumps back and forth between where it was to where it should be. I'm thinking this is because PenPot is trying to save the file where it moved to +10y but I've moved it 10-40y more before it could save so the object goes from 0y to 10y then 40y back to 10y then to 40y. I'm having to wait for it to update before moving it again or doing anything. This isn't limited to moving objects but it's the best example.

I'm not sure if this is caused by my hardware or what. I only noticed this start to happen after working in a project with 13 "desktop" frames (not all completely designed/populated with lots of objects). 

### Describe the solution you'd like.

If I were to just change this interval to make it less frequent or disable it altogether it would dramatically increase the speed of my workflow. I understand that the _best_ solution would be to dig through the code and make optimizations but I think my proposed solution would be a good band-aid solution for now. I love this product besides this one thing but it really making the user experience lower quality. Maybe you can also add Ctrl + S to save the project to keep the ability for a project to be quickly saved.

### Additional context

I'm using Micrsoft Edge Version 119.0.2151.97 (Official build) (64-bit). I'm not sure what other info you'd like but I'm happy to provide it or more context.

**Comment by JMHeartley** [comment]
I'm using penpot.app, not using the self-hosting version

**Comment by madalenapmelo-kp** [comment]
Hi @JMHeartley,

Thanks for the suggestion! I have opened an enhancement in our backlog on Taiga so that we can consider this in the future, you can check the details here: https://tree.taiga.io/project/penpot/issue/6326

**Comment by madalenapmelo-kp** [comment]
Hi @JMHeartley,

The team has reviewed this issue, and we have decided that since the performance has been dramatically improved and we will continue working on improving it further, this is not something that we plan to address in the foreseeable future so I'm closing this issue.

**Comment by JMHeartley** [comment]
Hello @madalenapmelo-kp,

I just checked and this doesn't occur after the upgrade to pen pot 2. Thanks for the follow-up 🙏🏼
