### ISSUE TITLE
bug: History is not preserved across sessions (or even page reloads)

### ISSUE THREAD

**Issue by garrett** [uxbox/uxbox#3909]
### Steps To Reproduce

1. Create a document
2. Do a lot of things
3. Leave the document and come back (or reload the page)

### Expected behavior

History should be preserved, so I could undo actions, even if I edited the page over time, or if someone else edited a shared document while I was away.

### Actual behavior

All history is lost.

### Desktop (please complete the following information)

- Firefox and Chrome on Linux

### Environment (please complete the following information)

design.penpot.app

**Comment by madalenapmelo-kp** [comment]
Hi @garrett,

Thank you for reporting this! We have already a User Story in our backlog to improve this, you can check the details here: https://tree.taiga.io/project/penpot/us/187?backlog-q=187&no-milestone=1

**Comment by adamcnaglich** [comment]
Is this supposed to work on self-hosted instances? Because it doesn't appear to be working for me.
