### ISSUE TITLE
bug: unable to get OIDC to work in 1.19.3

### ISSUE THREAD

**Issue by skerit** [uxbox/uxbox#3922]
### Steps To Reproduce

I set up my own OIDC provider, using the [oidc-provider](https://www.npmjs.com/package/oidc-provider) npm package.

At first I was running into issue https://github.com/penpot/penpot/issues/3638
No matter what I did, Penpot could not get the email and fullname info.
Even though the issue stated that Penpot's behaviour was compliant with the specification, `oidc-provider` required me to enable the `conformIdTokenClaims: false` setting. Saying this in their documentation:

> [OIDC Core 1.0 - Requesting Claims using Scope Values](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) defines that claims requested using the scope parameter are only returned from the UserInfo Endpoint unless the response_type is id_token.
Despite of this configuration the ID Token always includes claims requested using the scope parameter when the userinfo endpoint is disabled, or when issuing an Access Token not applicable for access to the userinfo endpoint.

After enabling the setting, I no longer got any `received incomplete profile info object (please set correct scopes)` error.

But now Penpot was always redirecting me back to the login screen.
Not a single error message or warning in the console.

This looks a lot like this issue:
https://github.com/penpot/penpot/issues/2819

But that issue had to do with the `well-known` data being read out wrong, and has been fixed early 2023.
Still, my provider *is* mounted under a path, so I did manually configure the `PENPOT_OIDC_USER_URI`, `PENPOT_OIDC_TOKEN_URI` and `PENPOT_OIDC_AUTH_URI` environment variable anyway.

But still: the same issue persists.

### Expected behavior

I expect to be logged in

### Actual behavior

I am not logged in, but always redirected to the frontpage

**Comment by madalenapmelo-kp** [comment]
Hi @skerit,

Could you please confirm if you are still experiencing this issue in the latest version?
