### ISSUE TITLE
bug: open overlay places frame in the wrong position when paired with a fixed element

### ISSUE THREAD

**Issue by Panini-Manganini** [uxbox/uxbox#3928]
### Steps To Reproduce

1. Create a board with an element whose position is fixed
2. Create a second board
3. In the prototype section, link the fixed element to the second board and select "open overlay"
4. Run the prototype

### Expected behavior

For the overlay board to be opened where it was set (whether manually or using the existing placing options)

### Actual behavior

The overlay board is opened in the top left instead of where it was set. 

### Screenshots or video

https://github.com/penpot/penpot/assets/153460250/2d20a16d-1b4a-4b22-93ba-540eff40c4fd

### Desktop (please complete the following information)

Windows 10
Chrome 120.0.6099.71

### Additional context

I saw a couple of posts about similar issues, but on Taiga they're all marked as closed/solved. Also it didn't seem like it was specific to fixed elements before, which currently it is.

**Comment by madalenapmelo-kp** [comment]
Hi @KemamSermala,

Thank you for reporting this! I have opened an issue on Taiga so that we can look into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/6385
