### ISSUE TITLE
bug: OIDC 404

### ISSUE THREAD

**Issue by rodude123** [uxbox/uxbox#3934]
### Steps To Reproduce

Setup OIDC:
1. add enable-login-with-oidc for both frontend and backend flags
2.  add base client id base URI, client secret and scopes
3. restart docker container

my oidc config
```yml
      - PENPOT_OIDC_CLIENT_ID=<client-id>

      # Mainly used for auto discovery the openid endpoints
      - PENPOT_OIDC_BASE_URI=https://oauth.id.jumpcloud.com/.well-known/openid-configuration
      - PENPOT_OIDC_CLIENT_SECRET=<client-secret>
      - PENPOT_OIDC_SCOPES="email"

```

### Expected behavior

it should log me in

### Actual behavior

gives an NGINX 404 error

### Desktop (please complete the following information)

Tested on: Firefox 120

### Environment (please complete the following information)

Self-hosted running on Ubuntu 22.04 with docker and docker-compose using penpot:latest

**Comment by JensUweB** [comment]
I have the same problem with the latest Version with docker based deployment.
When I click on the "OpenID" Button (btw: can I change that text somehow?)  I get redirected to

```
https://penpot.domain.tld/?clientId=something&&redirect_uri=httpss%3A//penpot.domain.tld/api/auth/oauth/oidc/callback<more stuff>
```

instead of my oidc provider.
The PENPOT_OIDC_BASE_URI environment variable is set correctly.

Edit: Looks like it is working with Version v1.18.6.

**Comment by rodude123** [comment]
How do I update penpot if I'm using docker?

Edit: 
pull with docker compose reload the browser and I still get the same 404 error.

**Comment by t3cneo** [comment]
Penpot adds the endpoint after the base URL itself, [see here](https://github.com/penpot/penpot/blob/8abab982e7e213ed2c65dc91021ddef748f7fbe1/backend/src/app/auth/oidc.clj#L53)

PENPOT_OIDC_BASE_URI should contain only the base URL of the auth provider.
When you say it like that it seems obvious but I did the same mistake as well when first spinning up penpot hehe

@rodude123 in your case your env should be :

`- PENPOT_OIDC_BASE_URI=https://oauth.id.jumpcloud.com`

**Comment by rodude123** [comment]
> Penpot adds the endpoint after the base URL itself, [see here](https://github.com/penpot/penpot/blob/8abab982e7e213ed2c65dc91021ddef748f7fbe1/backend/src/app/auth/oidc.clj#L53)
> 
> PENPOT_OIDC_BASE_URI should contain only the base URL of the auth provider. When you say it like that it seems obvious but I did the same mistake as well when first spinning up penpot hehe
> 
> @rodude123 in your case your env should be :
> 
> `- PENPOT_OIDC_BASE_URI=https://oauth.id.jumpcloud.com`

So I changed it to what you suggested, but I still get an error
I get this error in the URL `The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.#/` 

For the redirect URI inside the JumpCloud config I added this `https://penpot.mysite.co.uk/api/auth/oauth/oidc/callback`

For the main login URL I put `https://penpot.mysite.co.uk/#/auth/login`

I have specified attributes inside JumpCloud although I have not used them inside penpot env. I'm guessing I should have done that

![image](https://github.com/penpot/penpot/assets/10896262/e3035e81-5906-43ea-a1fd-235d7bbc6c6f)

**Comment by t3cneo** [comment]
I don’t know jumpcloud sorry…

I’m using Zitadel self hosted.

Did you try without `- PENPOT_OIDC_SCOPES="email" ` ?

With Zitadel it is working without this env which default to `email profile openid`



Edit : 
did you correctly set `PENPOT_PUBLIC_URI=https://penpot.mysite.co.uk` ?

**Comment by rodude123** [comment]
> I don’t know jumpcloud sorry…
> 
> I’m using Zitadel self hosted.
> 
> Did you try without `- PENPOT_OIDC_SCOPES="email" ` ?
> 
> With Zitadel it is working without this env which default to `email profile openid`
> 
> 
> 
> Edit : 
> did you correctly set `PENPOT_PUBLIC_URI=https://penpot.mysite.co.uk` ?
> 

I removed the scopes and that did nothing still the same error 

Also yes, the URL is set correctly

**Comment by niwinz** [comment]
Hello @rodude123 I just have tried clean installation and configured OIDC with Auth0 (a test account).

```
export PENPOT_OIDC_BASE_URI=https://dev-ei1xxxxxx.us.auth0.com
export PENPOT_OIDC_CLIENT_ID=daBTMxxxxxxxxxxxx6lyMVwB
export PENPOT_OIDC_CLIENT_SECRET=nPL2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvSS99
```
On the oauth:

Redirect uri: http://localhost:3449/api/auth/oauth/oidc/callback
Allowed origin: http://localhost:3449/

And everything worked correctly. I know nothing about jumpcloud, but as soon as I can, I will try to create a test account there and test it. But looks like some config issue.

**Comment by rodude123** [comment]
I will give it ago! Thank you

**Comment by rodude123** [comment]
I'm not sure if I should create a new issue or not but when I try and use my jumpcloud with all levels of security, none, basic, and post I always end up getting this `https://penpot.example.co.uk/#/auth/login?error=unable-to-auth&hint=unable+to+retrieve+token&type=internal&code=unable-to-retrieve-token` not sure what to do. In my compose file I have added the enable-login-with-oidc to PENPOT_FLAGS I'm not sure what to do here

**Comment by ycsh-w** [comment]
> > I don’t know jumpcloud sorry…
> > I’m using Zitadel self hosted.
> > Did you try without `- PENPOT_OIDC_SCOPES="email" ` ?
> > With Zitadel it is working without this env which default to `email profile openid`
> > Edit :
> > did you correctly set `PENPOT_PUBLIC_URI=https://penpot.mysite.co.uk` ?
> 
> I removed the scopes and that did nothing still the same error
> 
> Also yes, the URL is set correctly

I just tried today, and it seems like whether to keep a trailing `/` is important for `PENPOT_PUBLIC_URI`. For me, it does not work without a `/`, but having the `/` at the end does the trick.
