### ISSUE TITLE
Contributing to Dutch localization

### ISSUE THREAD

**Issue by Stephan-P** [uxbox/uxbox#3935]
I could contribute to the Dutch language.
Kind regards, Stephan

**Comment by madalenapmelo-kp** [comment]
Hi @Stephan-P, 

We'd love for you to help us with Dutch translations! The only thing we need to grant you permissions to edit translations is your [Weblate](https://weblate.org/) username. Once we have this we will add you to the project as soon as we can. 

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thanks!

**Comment by Stephan-P** [comment]
I log into Weblate using my Github account.
https://hosted.weblate.org/user/Stephan-P/

**Comment by Stephan-P** [comment]
Thank you for adding me to the Dutch team on Weblate

**Comment by Stephan-P** [comment]
How could I get in contact with the Dutch language Editor in chief/proofreader to discuss my suggestions?

**Comment by madalenapmelo-kp** [comment]
Hi @Stephan-P,

Dutch language translations are based on contributions from our Community, so we don't have an Editor in Chief or Proofreader. You are welcome to post your suggestions on the Penpot Community and get the conversation going, there is already a post about Dutch translations: https://community.penpot.app/t/translation-for-dutch-netherlands/3142

You can also find more information on how to contribute to translations in our [Contribution Guide](https://help.penpot.app/contributing-guide/translations/#translations-howto) :slightly_smiling_face:
