### ISSUE TITLE
bug: Selecting from Color Palette does not work for board when there is no existing fill

### ISSUE THREAD

**Issue by rohannelson** [uxbox/uxbox#3941]
### Steps To Reproduce

1. Create a board
2. Open color palette (if not open already)
3. Try to select a color

### Expected behavior

Selecting a color should create a fill of the selected color in the board.

### Actual behavior

No color is selected. If a fill is manually created from the side panel, it is then possible to select colors using the color palette. 
For rectangles and ellipses there is no need to create a fill manually first, partly because they start with a fill by default, but even if you delete the fill on a rectangle or ellipse selecting a color from the color palette still works. If boards worked like rectangles and ellipses it would remove one step from selecting the desired color for a board which would improve usability.

### Desktop (please complete the following information)

Windows 10, Firefox 121.0

### Environment (please complete the following information)

https://design.penpot.app

**Comment by madalenapmelo-kp** [comment]
Hi @rohannelson,

Thank you for reporting this! Just to make sure I understand the behavior you are describing, would you be able to share a screen recording?

**Comment by rohannelson** [comment]
Sure thing, here it is -
[PenPot Issue.zip](https://github.com/penpot/penpot/files/13826622/PenPot.Issue.zip)
Hope it's clear.
By the way, I noticed after recording that demo that boards start with white fill when they are parent level, but if it is a board within a board then by default they start without a fill - this was what I was encountering on my project. Happy to send through another recording if that is helpful.

**Comment by madalenapmelo-kp** [comment]
Hi @rohannelson,

Thanks for the video, all clear now! I have opened a Bug on Taiga so that we can look into fixing this, you can check the details here: https://tree.taiga.io/project/penpot/issue/6464

**Comment by rohannelson** [comment]
Great, thanks! :)
