### ISSUE TITLE
Contribute to Latvian translation

### ISSUE THREAD

**Issue by eandersons** [uxbox/uxbox#3947]
Hello,

I would like to fix (or add suggestions to) some translations in Latvian that currently are incorrect
I most probably will try to add missing translations as well.

My Weblate username is @Edgarsons.

**Comment by madalenapmelo-kp** [comment]
Hi @eandersons,

I've invited you to the translation project, once you accept the invitation you'll be able to start translating!

You can find more information about how to contribute to the translations here: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
