### ISSUE TITLE
bug: Adding vector path points before first point of existing open path not working

### ISSUE THREAD

**Issue by eeropic** [uxbox/uxbox#3998]
### 1. Draw an open vector path
<img width="279" alt="image" src="https://github.com/penpot/penpot/assets/6544296/af9d8a9a-a9b9-4ea9-b314-e87e96db4773">

### 2. Start editing the path from the other end, i.e. start from the first point (top left in the example)
<img width="232" alt="image" src="https://github.com/penpot/penpot/assets/6544296/e12f3f95-07c5-4d1e-99c0-c31c3fb0ec99">

### 3. After adding one point, the path tool resets so that path drawing continues from the last point
<img width="254" alt="image" src="https://github.com/penpot/penpot/assets/6544296/54455bbb-fc34-4950-9f4d-6ab4e59b67cf">

### Expected behavior

The path editing should continue from the previous point drawn
<img width="275" alt="image" src="https://github.com/penpot/penpot/assets/6544296/a5c52deb-d2be-4bca-a2dd-4148a7201b19">

### Actual behavior

The path editing continues from the original "last point" drawn in the path
<img width="283" alt="image" src="https://github.com/penpot/penpot/assets/6544296/55b427eb-04b9-44c1-8f89-2ea2b2cb8fbd">

### Desktop (please complete the following information)

macOS Monterey 12.7.2 - Firefox 120.0.1

### Environment (please complete the following information)

- Replicated on design.penpot.app 1.19.4-10723-gdce2eb03c
- Replicated on grid preview build on penpot.app 1.21.0-12037-g470cf0813

**Comment by eeropic** [comment]
Also - sometimes it doesn't even draw the newly added point, just resets to continue editing from the original last drawn point

**Comment by madalenapmelo-kp** [comment]
Hi @eeropic,

Thank you for reporting this! I've created an issue on Taiga so that we can look into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/6593
