### ISSUE TITLE
 Contribute to Simplified Chinese translation

### ISSUE THREAD

**Issue by GeekSquirrel** [uxbox/uxbox#3999]
Hello, I would like to add new translation and fix existing translation if I find mistakes. My weblate account is @GeekSquirrel.
By the way, I'm going to make some videos to promote Penpot to Chinese users.

**Comment by madalenapmelo-kp** [comment]
Hi @GeekSquirrel,

Thank you for your contributions, we really appreciate it :) 

I've already added you to the translation project and you can now start adding and fixing translations! Here you can find more information about how to contribute to the translations: https://help.penpot.app/contributing-guide/translations/

Thank you again for your contribution!
