### ISSUE TITLE
feature: Create components with code/script

### ISSUE THREAD

**Issue by parrotcar00** [uxbox/uxbox#4010]
### Is your feature request related to a problem? Please describe.

If one has created a component with known design before, it might be easier to write a small chunk of code to duplicate that and then go from there. Cuts down on repetitive tasks while doing ui prototyping.
Figma has a plugin called scripter for this: https://www.figma.com/community/plugin/757836922707087381/scripter
The scripter plugin has a lot of potential but it doesn't work as well because Figma plugin API has a limitation of not allowing plugin to run in a separate window.
Penpot has a huge edge here because of its Clojure foundation and better potential to build a more expressive API.

### Describe the solution you'd like.

A code editor view where one can type in code that creates ui components.

### Additional context

I'm curious if Penpot already offers something for this that I have missed.

**Comment by madalenapmelo-kp** [comment]
Hi @parrotcar00,

Thank you for the suggestion! This is a discussion that [has been raised in the Penpot Community](https://community.penpot.app/t/what-are-penpot-s-plans-for-a-plugin-system/2412/4), I recommend sharing this suggestion there.

We understand that plugins are key to add capabilities and empower the community to contribute to Penpot. You can stay up to date about the progress on this here: https://tree.taiga.io/project/penpot/us/1129

**Comment by madalenapmelo-kp** [comment]
Hi @parrotcar00,

We have reviewed this feature and while this is not something that we plan to address in the foreseeable future, we plan to introduce plugins soon so this could be a community developed plugin. 

We encourage you to share this idea at our global [Penpot community](https://community.penpot.app), where you could raise interest and start a productive conversation about this!
