### ISSUE TITLE
Improve Layer Overview Interaction

### ISSUE THREAD

**Issue by bsoltani** [uxbox/uxbox#4046]
### Steps To Reproduce

1. create a group
2. create a subgroup
3.  repeat steps 1 and 2

### Expected behavior

Opening or closing elements in the Layer Overview should not accidentally trigger the scroll bar.

Mouse interaction near the chevron icon should be refined to reduce the probability of accidentally locking elements.

### Actual behavior

When working in the Layer Overview, I've noticed that opening or closing elements often accidentally triggers the scroll bar. Additionally, while attempting to prevent this by moving the mouse to the left side of the chevron icon, there's a chance to accidentally lock the element.

### Screenshots or video

![nested-layer](https://github.com/penpot/penpot/assets/108335513/df609b31-4af5-4e7c-b0d9-4f6c2a962798)

### Desktop (please complete the following information)

I’m using Chrome Version 120.0.6099.200 (Official Build) (64-bit)

**Comment by madalenapmelo-kp** [comment]
Hi @bsoltani,

We already have some enhancements planned around the layer overview although they are not yet prioritized. You can find the details on Taiga [here](https://tree.taiga.io/project/penpot/issue/2345) and [here](https://tree.taiga.io/project/penpot/us/4334?milestone=262806).

**Comment by madalenapmelo-kp** [comment]
Hi @bsoltani,

As there are already an open issue for this, I'm closing this one but you can keep up with the progress made on this on Taiga or at #1374!
