### ISSUE TITLE
Add Board (B) context to Design in the Sidebar

### ISSUE THREAD

**Issue by ikonnow** [uxbox/uxbox#4064]
### Is your feature request related to a problem? Please describe.

If you select Board (B) the Sidebar shows Export only. (I guess bcz the content info isn't there yet). 

### Describe the solution you'd like.

Select Board (B), the Sidebar shows all the helpful context - presets and such. It makes sense to have the options available before any Board exists.

### Describe alternatives you've considered.

Well currently the alternative is to create any board and adjust it after it exists

**Comment by madalenapmelo-kp** [comment]
Hi @ikonnow,

Thank you for your suggestion :slightly_smiling_face: This is something that we are already considering, you can find the details on Taiga here: https://tree.taiga.io/project/penpot/us/494?backlog-q=presets&no-milestone=1

**Comment by ikonnow** [comment]
ok i just close it then to avoid doubles
