### ISSUE TITLE
bug: Thumbnail Feature doesn't work after the update to 1.19

### ISSUE THREAD

**Issue by ikonnow** [uxbox/uxbox#4065]
### Steps To Reproduce

1.  Create a project, create a file / click on any preexisting file (no thumbail)
2. Close the project / select "set as Thumbnail"
3. Close the file / project

### Expected behavior

As in the previous version the thumbail should work even if you did not specify a board

### Actual behavior

The thumbnail isn't created / doesn't exist, even if the files from the previous version had a thumbnail.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/25803775/77bed102-614c-4d9e-8491-dd4a5645aac7)
![image](https://github.com/penpot/penpot/assets/25803775/4c34dc50-d452-4070-9533-09cb4c72608f)

### Desktop (please complete the following information)

tested it on Edge, Chrome and Thorium

### Environment (please complete the following information)

Self hosted

**Comment by niwinz** [comment]
This is probable of the configuration change issue and/or permissions problem on upgrade.
But without more info it is complicated to know the real issue.

**Comment by ikonnow** [comment]
> This is probable of the configuration change issue and/or permissions problem on upgrade.
> But without more info it is complicated to know the real issue.

Exactly. Actually I think the issue is proxy related. I had a similar one with another docker container/stack. Yesterday I discovered that the export feature doesn't work properly as well. I will test further as soon as I get the chance

**Comment by icsy7867** [comment]
Did you ever get this working?

**Comment by ikonnow** [comment]
> Did you ever get this working?

Yes and no. The thumbnails work after the first install but don't work after any update. That's my experience - even with V2 lately

**Comment by ikonnow** [comment]
Since the 2.1 update it was working again. Thx for the thumbnails!
