### ISSUE TITLE
Bug: non-accessible “save color style" button

### ISSUE THREAD

**Issue by SINF-KEN** [uxbox/uxbox#4114]
### Steps To Reproduce

1. Navigate to Penplot.
2. Populate the Local library with several colors. 
3. Click on the "Edit" option (adjust color).
4. The "save color style" button may become inaccessible due to its positioning beyond the screen border. [Refer to the GIF for clarification.] 
(note: in this example i used "CoreUI DesignSystem (DEMO)" ) 
![its-not-a-JIF-its-a](https://github.com/penpot/penpot/assets/148757725/a37c2bd7-7792-4d6f-bb3c-974e41a31150)

### Expected behavior

Ensure that the popup remains within the confines of the screen, with continuous accessibility to the save button.

### Actual behavior

The popup color picker window goes under the screen boundaries. 

### Screenshots or video

<img width="590" alt="image" src="https://github.com/penpot/penpot/assets/148757725/13376a35-4617-4267-befd-4d65c1deaaa5">

### Desktop (please complete the following information)

NA

### Environment (please complete the following information)

penpot 2.0 beta website( <3 fosdem ) 

### Additional context

love the work 🫶
[it's GIF not JIF](https://youtu.be/N1AL2EMvVy0)

**Comment by madalenapmelo-kp** [comment]
Hi @SINF-KEN,

Thank you for reporting this :slightly_smiling_face:  I have opened a bug on Taiga so that we can look into correcting this, you can find the details here: https://tree.taiga.io/project/penpot/issue/6923

**Comment by SINF-KEN** [comment]
fixed in https://github.com/penpot/penpot/pull/4118 
thanks 👍
