### ISSUE TITLE
feature: Malay translation

### ISSUE THREAD

**Issue by shoen1x** [uxbox/uxbox#4120]
### Is your feature request related to a problem? Please describe.

Translation language: Malay
Translation type: New translation (add the currently untranslated), change existing translation (subsequently, if a problematic translation is found, even if it is corrected)

Weblate username : @shoen1x.

### Describe the solution you'd like.

Same as above

**Comment by madalenapmelo-kp** [comment]
Hi @shoen1x,

I've already added you to the translation project and also Malay to the languages list. It always makes us really happy to add a new language :slightly_smiling_face: 

Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!

**Comment by shoen1x** [comment]
![Tangkap layar 2024-02-09 195444](https://github.com/penpot/penpot/assets/38944205/ea79c146-1306-4742-9ba3-528a5d923231)

It seems not working for me
