### ISSUE TITLE
bug: adding layout to a group resets group title

### ISSUE THREAD

**Issue by cyberalien** [uxbox/uxbox#4125]
### Steps To Reproduce

1. Select multiple layers
2. Group them
3. Rename group
4. Click "Layout" button on right side

### Expected behavior

Expected not to change title.

### Actual behavior

Group is renamed to "Board"

Current behavior sort of makes sense because group is converted to a board, so it is probably a new node. However, it is counter intuitive. Maybe copy title from group to board if group has a custom title?

### Desktop (please complete the following information)

- OS: macOS 14.3
- Browser: Chrome 121.0.6167.160
- Penpot: 1.19 (online version)

### Environment (please complete the following information)

- Host: https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @cyberalien,

Thank you for reporting this! I have opened an issue on Taiga so that we can look into fixing it, you can see the details here: https://tree.taiga.io/project/penpot/issue/6948
