### ISSUE TITLE
bug: color picker is incorrect when picking from raster image

### ISSUE THREAD

**Issue by cyberalien** [uxbox/uxbox#4128]
### Steps To Reproduce

1. Import attached `screenshot.png` to a Penpot document
2. Try to pick border color below text input, as shown in attached video.

### Expected behavior

Expected a precise tool, picking color `#e7e7e7`

### Actual behavior

Zoom in color picker is blurry, picking border shows `#f3f3f3` in Chrome, `#f5f5f5` in Firefox, both are way off the mark. Zoom is set to 100%.

Cannot zoom in on screenshot to attempt to do more precise targetting because zoomed in image is very blurry.

### Screenshots or video

Source screenshot used in demo:
![screenshot](https://github.com/penpot/penpot/assets/822287/39ed8bf8-82e2-41ba-b3aa-121dddc43b7b)

Demo, showing picking color:
https://github.com/penpot/penpot/assets/822287/1b84a3ae-f551-4ca6-ab6e-82afe123b937

Screenshot of zoom tool in Penpot failing to pick color:
![color-picker-penpot](https://github.com/penpot/penpot/assets/822287/90da5ccf-c49f-4af5-92e5-b51c29c416fe)

### Desktop (please complete the following information)

- OS: macOS 14.3
- Browser: Chrome 121.0.6167.160

### Environment (please complete the following information)

- Host: https://design.penpot.app/, also on self-hosted version 1.19

### Additional context

Screenshots of similar zoom tool in Figma and Sketch, showing how it is supposed to work:
![color-picker-figma](https://github.com/penpot/penpot/assets/822287/6ecba457-526a-4fec-b89f-d350d569ba6d)

![color-picker-sketch](https://github.com/penpot/penpot/assets/822287/9caa1802-1605-4434-bbec-ccd9b45b61a1)

**Comment by madalenapmelo-kp** [comment]
Hi @cyberalien,

Thank you for reporting this! Would you be able to send the `.penpot` file where you are experiencing this to support@penpot.app so that we can take a look?

In case you need additional details on how to export the `.penpot` file, it is explained [here](https://help.penpot.app/user-guide/import-export/#importing-export).

**Comment by cyberalien** [comment]
Sure. Sent.

**Comment by cyberalien** [comment]
If you cannot recreate issue, this got me thinking that there might be something else causing problem.

Maybe its because of Retina display? I'm working on Macbook Pro 16"

**Comment by cyberalien** [comment]
Tested on normal monitor, issue is less prevalent there, but still bugged. Raster image is still slightly blurred, trying to pick that color results in `#eaeaea` or `#ebebeb`, which is incorrect but a bit closer to target.

So Retina display is not the issue, but it does make it worse.

**Comment by madalenapmelo-kp** [comment]
Hi @cyberalien,

Thank you for the additional details! I have opened an Taiga issue so that we can look further into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/6995
