### ISSUE TITLE
bug: Board and/or images are not loaded

### ISSUE THREAD

**Issue by Verhoeckx** [uxbox/uxbox#4162]
### Steps To Reproduce

1. Create a document in Penpot
2. Save/close the document
3. Open it again

### Expected behavior

All boards and/or images are shown.

### Actual behavior

Boards and/or images are not shown (see screenshot).

### Screenshots or video

The below workspace contains five boards, but none are shown.
![image](https://github.com/penpot/penpot/assets/64807887/bca5e2a1-7a2a-41b2-9ef9-4d2d294af58d)

### Desktop (please complete the following information)

Fedora 39 Silverblue
Firefox 122

### Environment (please complete the following information)

Self hosted
Penpot 1.19
RHEL 9.3
Docker 25.0.3

Reverse proxy
```
<VirtualHost *:80>
    ServerName [domain name]
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =[domain name]
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
    ServerName [domain name]

    RewriteEngine On
    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /(.*) ws://localhost:9001/$1 [P,L]
    
    ProxyPass / http://localhost:9001/ nocanon
    ProxyPassReverse / http://localhost:9001/
    
    SSLCertificateFile /etc/letsencrypt/live/[domain name]/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/[domain name]/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

I tried changing localhost to my domain name, but after doing that I couldn't load Penpot any more.

### Additional context

When I look in the console of my browser (Firefox), I see the following error messages:
![image](https://github.com/penpot/penpot/assets/64807887/f8810684-a634-46f5-b596-e6ad23c34f36)

**Comment by niwinz** [comment]
The error message shows that browser is unable to reach penpot, I don't know a reason but it does not looks to be a penpot issue. Look if this requests reaching penpot for fully understand where is the issue.

**Comment by Verhoeckx** [comment]
Personally I think it is a Penpot bug, because when I start working on the document the images were shown (sorry, I didn't tell you that). And when I zoom in on the document the images are also shown (one at the time). 

When Penpot 2.0 arrives, I will update the container and see if this solves the problem. Until then you can close this bug report. I will report it in the future when it comes back.

**Comment by Verhoeckx** [comment]
I see I can close this bug report myself, so I will do that!

**Comment by Verhoeckx** [comment]
I think it was a Penpot bug, because I upgraded to version 2.0 and the all images are shown. I also don't see error messages any more in the browser console. :+1:
