### ISSUE TITLE
bug:text cannot be editted when paste svg in workspace

### ISSUE THREAD

**Issue by griffinmao1999** [uxbox/uxbox#4181]
### Steps To Reproduce

Neither the svg code nor the svg file format can be edited when copied to the workspace

https://github.com/penpot/penpot/assets/76414406/e4750616-50dc-4b75-9f2e-6f5e450380cb

### Expected behavior

When the svg is copied in, the text tags in the svg can be edited as if they were text.

### Actual behavior

text tag in svg code was changed to a “svg-rect”

### Desktop (please complete the following information)

macOS Sonoma 14.0
Chrome 121.0.6167.160

### Additional context

This is very much affecting my workflow, I hope you guys can help with this, thanks!

**Comment by madalenapmelo-kp** [comment]
Hi @griffinmao1999,

Thank you for reporting this! Unfortunately, I'm not able to watch the screen recording, would you be able to send the recording to support@penpot.app instead?

**Comment by griffinmao1999** [comment]
@madalenapmelo-kp Of course, I've sent the video to this e-mail address

**Comment by madalenapmelo-kp** [comment]
Hi @griffinmao1999,

Thank you for sending the video! I have opened an issue on Taiga so that we can look further into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/7041

**Comment by madalenapmelo-kp** [comment]
Hi @griffinmao1999,

Our team has reviewed this issue and, unfortunately, it is something that we do not support right now. 

When you paste or import an SVG, it is treated like an SVG node and converting it to a format that Penpot can support would mean losing information about the text or having a text that is not properly placed.

I'm closing this issue as we won't be able to address it at this time but if anything else comes up please feel free to open a new issue or reach out to support@penpot.app :slightly_smiling_face:
