### ISSUE TITLE
Contribute to Traditional Chinese and Simplified Chinese translation

### ISSUE THREAD

**Issue by Jvcon** [uxbox/uxbox#4224]
Hello, I would like to add new translation and fix existing translation if I find mistakes. My weblate account is @Jvcon.

**Comment by madalenapmelo-kp** [comment]
Hi @Jvcon,

I've already added you to the translation project 🙂

Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/) and start translating. Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
