### ISSUE TITLE
bug: Layer opacity is uneven for icon components and fonts in penpot 2.0 beta

### ISSUE THREAD

**Issue by unaaagy** [uxbox/uxbox#4252]
### Steps To Reproduce

1. Go to design.penpot.dev and create a new project.
2. Insert a icon component and a text block side by side as follows:

![image](https://github.com/penpot/penpot/assets/155830121/0d94a6f8-84c3-4216-882d-c657454c26cc)

3. Apply a 30% layer opacity to both the icon and the font

Note: The icon must be a component or be nested within a board like below:

![image](https://github.com/penpot/penpot/assets/155830121/7cadcad9-2d34-4aa8-a47f-4fb5f4c57521)

### Expected behavior

The result should be like the image below:

![Screenshot from 2024-03-12 18-44-25](https://github.com/penpot/penpot/assets/155830121/7037b0a8-3d8c-4e47-89d4-a56575f8a5c9)

### Actual behavior

The opacity for the icon is higher.

![Screenshot from 2024-03-12 18-44-13](https://github.com/penpot/penpot/assets/155830121/3a536be7-987c-4cd1-b16b-8088c46493bc)

### Environment (please complete the following information)

- Host: https://design.penpot.dev/

**Comment by madalenapmelo-kp** [comment]
Hi @unaaagy,

Thank you for reporting this! I couldn't reproduce this issue, could you export the .penpot file and send it to support@penpot.app so that we can look into it?

**Comment by unaaagy** [comment]
I checked again and wanted to clarify that the issue seems to be with the `Text`. I have sent the .penpot file just now.

**Comment by madalenapmelo-kp** [comment]
Hi @unaaagy,

Thank you for clarifying! I have opened an issue on Taiga so that we can look further into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/7191
