### ISSUE TITLE
bug: Issue displaying uploaded images in Penpot deployed on Kubernetes

### ISSUE THREAD

**Issue by dawogid** [uxbox/uxbox#4280]
Hi!

I'm encountering an issue where images I upload in projects are not being displayed, as shown here:
 
![image](https://github.com/penpot/penpot/assets/140388441/346eeb2c-9067-4b07-884c-261aa37a0d81)

The images are created correctly in pod containing penpot-backend at path **/opt/data/assets**. However, I'm seeing an error in the logs for the pod containing penpot-frontend:

`[error] 12#12: *252 open() "/opt/data/assets/a3/09/e1d7aeea4db38cf1028cefd33079" failed (2: No such file or directory), client: 10.244.18.162, server: _, request: "GET /assets/by-file-media-id/780e0e20-92ac-816e-8004-0bd84f7e2cc0 HTTP/1.1", upstream: "http://10.0.85.40:6060/assets/by-file-media-id/780e0e20-92ac-816e-8004-0bd84f7e2cc0", host: "penpot.mydomain.net"`

I deployed Penpot on Kubernetes using modified chart from: https://artifacthub.io/packages/helm/codechem/penpot
using the latest version **1.19.3** of the Penpot images (backend, frontend, and exporter).

I set environment variables as:

```
PENPOT_ASSETS_STORAGE_BACKEND:       assets-fs
PENPOT_STORAGE_ASSETS_FS_DIRECTORY:  /opt/data/assets
```

This issue seems similar to past reported issues that were supposedly fixed. I've double-checked the path /opt/data/assets and the environment variables. What could be causing this issue?

Thanks in advance for any help or insights!

### Expected behavior

Uploaded images should be visible

### Actual behavior

Uploaded images are not visible

### Environment (please complete the following information)

Kubernetes: 1.28.5

penpotapp/backend env variables:
![image](https://github.com/penpot/penpot/assets/140388441/54b2dfd2-5792-430b-9c50-31b598c61479)

penpotapp/frontend env variables:
![image](https://github.com/penpot/penpot/assets/140388441/1c89e3d5-4d9d-4a01-88f1-653b0cb1ec88)

penpotapp/exporter env variables:
![image](https://github.com/penpot/penpot/assets/140388441/c61b5935-9cd7-42bc-a1ec-bc5e7e147500)

### Frontend Stack Trace

`[error] 12#12: *252 open() "/opt/data/assets/a3/09/e1d7aeea4db38cf1028cefd33079" failed (2: No such file or directory), client: 10.244.18.162, server: _, request: "GET /assets/by-file-media-id/780e0e20-92ac-816e-8004-0bd84f7e2cc0 HTTP/1.1", upstream: "http://10.0.85.40:6060/assets/by-file-media-id/780e0e20-92ac-816e-8004-0bd84f7e2cc0", host: "penpot.mydomain.net"`

**Comment by Char-Ten** [comment]
**same problem！！**
I don't know if it's caused by file permission restrictions

**Comment by Char-Ten** [comment]
the problem was resolved!
You must mount the same volume（/opt/data/assets） to both containers（frond and backend）

**Comment by dawogid** [comment]
Thanks @Char-Ten, it works! 
Closing bug.
