### ISSUE TITLE
bug: PlantUml Error on technical documentation

### ISSUE THREAD

**Issue by rvz420** [uxbox/uxbox#4299]
### Steps To Reproduce

go to https://help.penpot.app/technical-guide/developer/architecture/frontend/

### Expected behavior

Show a correct uml

### Actual behavior

Shows an error message

### Screenshots or video

![Captura](https://github.com/penpot/penpot/assets/21206715/f20192b7-f3a7-438c-84f9-eb7b502048a0)

**Comment by madalenapmelo-kp** [comment]
Hi @rvz420,

Thank you for reporting this! I've opened an issue on the [penpot-docs repository](https://github.com/penpot/penpot-docs/issues/173) as this is an issue on the documentation so I'm closing this one here :slightly_smiling_face:
