### ISSUE TITLE
bug: [Penpot 2.0 beta] Non-alphabet characters get shifted backward for components in the component switcher

### ISSUE THREAD

**Issue by unaaagy** [uxbox/uxbox#4300]
### Steps To Reproduce

1. Go to https://design.penpot.dev
2. Create a component with a name like '1 square', '_ rectangle '

The result might look like this on the layers and assets section:

![image](https://github.com/penpot/penpot/assets/155830121/2443dad8-3077-4d38-906f-03e1be25564a)

### Expected behavior

The name should be consistent everywhere.

### Actual behavior

Non-alphabet characters are shifted backwards in the component switcher.

![image](https://github.com/penpot/penpot/assets/155830121/1d4d75d8-7889-44be-bc9f-c5c7bec86905)

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/155830121/650c19e1-eaf4-4fec-86c3-023cb2a8f3d4)

### Environment (please complete the following information)

https://design.penpot.dev

**Comment by madalenapmelo-kp** [comment]
Hi @unaaagy,

Thank you for reporting this! Could you send the `.penpot` file to support@penpot.app so that we can look further into it?
