### ISSUE TITLE
bug: [devenv] nginx 404 not Found

### ISSUE THREAD

**Issue by lewisHeart** [uxbox/uxbox#4337]
### Steps To Reproduce

```
git clone https://github.com/penpot/penpot/
./manage.sh pull-devenv
./manage.sh run-devenv
```
or 
```
git clone https://github.com/penpot/penpot/
cd penpot/dcoker/devenv/
docker compose -p penpot -f docker-compose.yaml up -d
```

### Expected behavior

Open the Penpot when it entered the URL http://localhost:3449

### Actual behavior

When I open the http://localhost:3449 it simply gives NGINX an error saying the page was not found, only in the owl.

 Penpot "Stable" works normal when I install via docker.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/32145272/08f3c08c-f994-498e-8585-c658b532504c)

### Desktop (please complete the following information)

- Archlinux x86_64
- Kernel: 6.8.2-arch2-1

**Comment by superalex** [comment]
Hi @lewisHeart 

When you use `./manage.sh run-devenv` you should have a tmux with four different tabs (gulp, shadow-watch, exporter and backend). Check all of them have been launched correctly and if there are any errors or extra info on them

**Comment by simontxxx** [comment]
Nginx can't find index.html!  U can run in frontend:   "./script/build" make index.html
