### ISSUE TITLE
bug: Chrome extension causes UI to not render

### ISSUE THREAD

**Issue by stevenhaskell** [uxbox/uxbox#4366]
### Steps To Reproduce

1. Selfhost or use online Penpot
2. Use Chrome browser
3. Have [CardPointers extension](https://chromewebstore.google.com/detail/cardpointers-x-credit-car/hlambnnbnnjkabpgemeompijpdliimkm) installed
4. Try to access Penpot.

### Expected behavior

I would expect the UI to render without an issue. The extension has not impacted any other sites. 

### Actual behavior

When accessing Penpot, the UI does not render. Disabling the extension allows the UI to render again.

### Screenshots or video

https://github.com/penpot/penpot/assets/28311046/873517a1-d9c7-47ab-b916-b154ba021b10

### Desktop (please complete the following information)

- MacOS Sonoma 14.4.1
- Chrome Browser 123.0.6312.107
- CardPointer Extension 5.3.1

### Environment (please complete the following information)

- https://design.penpot.app/
- https://penpot.stevenhaskell.com/

**Comment by madalenapmelo-kp** [comment]
Hi @stevenhaskell,

Thank you for reporting this! We have just released Penpot 2.0, could you please confirm if you still experience this behavior as of the release?

**Comment by stevenhaskell** [comment]
@madalenapmelo-kp No problem! I just tested it in Penpot 2.0. Enabling the extension still causes the UI to disappear.

**Comment by madalenapmelo-kp** [comment]
Hi @stevenhaskell,

Thanks for confirming! I have created an issue on Taiga so that we can look further into this, you can find it here: https://tree.taiga.io/project/penpot/issue/7436

**Comment by madalenapmelo-kp** [comment]
Hi @stevenhaskell,

We have reviewed this issue and, unfortunately, this is not something we can address on our side. We recommend reaching out to CardPointers directly to report this issue.
