### ISSUE TITLE
bug: vertical / horizontal path hitbox too small to drag

### ISSUE THREAD

**Issue by ShibuyaCyana** [uxbox/uxbox#4369]
### Steps To Reproduce

1. Make some strictly vertical / horizontal paths and try to move them by mouse dragging

### Expected behavior

Some margin to help dragging them around

### Actual behavior

Insanely small hitbox, almost impossible to drag around

### Screenshots or video

https://github.com/penpot/penpot/assets/39703247/26ece045-4a31-4750-af8b-b4c4fc98c8ff

### Desktop (please complete the following information)

- Windows 11 22H2
- Firefox 124.0.2 (64-bit)

**Comment by madalenapmelo-kp** [comment]
Hi @ShibuyaCyana,

Thank you for reporting this! We have created an issue on Taiga to look further into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/7407
