### ISSUE TITLE
bug: Grouping ungroups subgroups after upgrade to Penpot 2.0

### ISSUE THREAD

**Issue by kevpaquette** [uxbox/uxbox#4375]
### Steps To Reproduce

1. Select a list of layers that includes groups
2. CTRL + G

### Expected behavior

A new group is created and all subgroups remain unchanged.

### Actual behavior

A new group is created, but all subgroups are ungrouped.

### Screenshots or video

https://github.com/penpot/penpot/assets/35848542/28a3c15e-0818-4b6d-9dee-95e97fc069ac

### Desktop (please complete the following information)

- Windows 10
- Google Chrome 123.0.6312.106

**Comment by madalenapmelo-kp** [comment]
Hi @kevpaquette,

Thank you for reporting this! I have opened an issue on Taiga so that we can look further into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/7412

**Comment by madalenapmelo-kp** [comment]
Hi @kevpaquette,

We have just released a fix for this so you should no longer be seeing this behavior, could you please confirm?

**Comment by kevpaquette** [comment]
Thanks a lot!

I confirm, I don't have the issue anymore.
