### ISSUE TITLE
bug: V2 crashes on moving Main Components with Nested Components between Frames, Pages, and Files

### ISSUE THREAD

**Issue by l-kgr** [uxbox/uxbox#4377]
### Steps To Reproduce

1. Create new Penpot V2 File (https://design.penpot.app/)
2. Copy content of attached CopyThisElements.rtfd to paste
[CopyThisElements.rtfd.zip](https://github.com/penpot/penpot/files/14906801/CopyThisElements.rtfd.zip)
3. Paste to Penpot V2 File
4. Crash with Crashlog 
"error on validating file referential integrity"
[report-copyingbetweenfiles.txt](https://github.com/penpot/penpot/files/14906803/report-copyingbetweenfiles.txt)

This was the only option to reproduce the error consistently.

Crashes also happend when moving Main Components between frames and/or pages (e.g. copying main components needed while translating a design-system from V1.92 to V2). 

Got even to the point, in which the main components got deleted, leading no history behind and the asset-panel empty (see attached screenshot). 
<img width="585" alt="deleted-components" src="https://github.com/penpot/penpot/assets/147325029/f04c9770-626f-4a5b-b910-32699c9d4e95"> When trying to drag the component (without preview), system crashes with -> 
[report-crashonemptycomponentdrag.txt](https://github.com/penpot/penpot/files/14906837/report-crashonemptycomponentdrag.txt)

Further reports of system-crashes of V2 which could be related to these errors are attached.
[pot-related-crashlogs.zip](https://github.com/penpot/penpot/files/14906805/pot-related-crashlogs.zip)

Edit: If not the main component rather an instance of it is copied between files the system does not crash.

### Expected behavior

Moving Main Components between Files, Frames and Pages while keeping the Main Component Flag without System-crash

### Actual behavior

V2 crashes with internal error. 
After reloading, last done 1-3 steps are not existent. Moved files are partially deleted in some cases. 

### Desktop (please complete the following information)

- MacOS Sonoma 14.2.1 (23C71) - M1
- Chrome Version 123.0.6312.105 (Official Build) (arm64)
- Offical Penpot https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @l-kgr,

Thanks for reporting this! We just released a fix that should address this issue, could you clear your browser cache and let me know if the issue persists?

**Comment by l-kgr** [comment]
Hi @madalenapmelo-kp ,

Can confirm, pasting the [CopyThisElements.rtfd.zip](https://github.com/penpot/penpot/files/14906801/CopyThisElements.rtfd.zip) 
into a new file on design.penpot.app **does NOT crash the V2 system any more**. The tool seems stable. 

Regarding other reports/crashes, which where not consistently reproducable;  I'll keep my eyes open if similar error-reports regarding "referential integrity" will occur in the next days and report back if so in a new ticket.

Well done quick fix! Thanks

**Comment by madalenapmelo-kp** [comment]
Thank you so much @l-kgr!
