### ISSUE TITLE
Penpot 2.0 Docker images

### ISSUE THREAD

**Issue by p1ngod** [uxbox/uxbox#4380]
Hi penpot team!

As we all were super excited for the release of 2.0, I would like to ask when you plan to release it on Docker Hub?

Best, ping

**Comment by madalenapmelo-kp** [comment]
Hi there,

We plan to release the docker images for Penpot 2.0 in the next couple of days :slightly_smiling_face:

**Comment by p1ngod** [comment]
Thank you! I would like to keep the issue open until release :)

**Comment by sawa-ko** [comment]
I can't wait to test version 2.0 with the docker images. 🙏

**Comment by rawzone** [comment]
It's go time! Thanks team, will upgrade and have a look right away.

**Comment by Arya-Sourav** [comment]
Seems like penpot has been updated on docker hub.

**Comment by madalenapmelo-kp** [comment]
Hi all,

You can now update your on-premise instance to 2.0! You can follow [the steps described here](https://help.penpot.app/technical-guide/getting-started/#update-penpot-1) :slightly_smiling_face:

**Comment by pikmin-rgb** [comment]
Is the upgrade of postgresql necessary to the migration ? I had a problem with the migration script, so I thought it came from that
