### ISSUE TITLE
bug: Images not being applied as fill on layers

### ISSUE THREAD

**Issue by jimirobaer** [uxbox/uxbox#4382]
### Steps To Reproduce

1. Create a new object (polygon, or any object that has fills)
2. Create a new fill or update an existing fill and change the type to 'Image'
3. Upload an image

### Expected behavior

An uploaded image should be applied directly to the layer. 

### Actual behavior

After uploading, the fill modal returns back to the default fill (Solid). Changing the fill type to 'Image' reveals the uploaded image, but no way to apply it.

### Screenshots or video

https://github.com/penpot/penpot/assets/8984769/dec11307-0ba1-4edc-8644-f2fdfe98b6c2

### Desktop (please complete the following information)

- OS: macOS 14.2.1 
- Browser: Google Chrome 123.0.6312.87 (arm64)

### Environment (please complete the following information)

- Host: https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @jimirobaer,

Thanks for reporting this! I've opened a bug on Taiga so that we can look into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/7414
