### ISSUE TITLE
bug: emoji causes crash as first character

### ISSUE THREAD

**Issue by jeremiahlee** [uxbox/uxbox#4385]
### Steps To Reproduce

1. Create a text node
2. Use macOS's Emoji & Symbols palette to insert an emoji
3. Witness the crash: "Internal Error Something bad happened. Please retry the operation and if the problem persists, contact support."

If any other non-emoji characters precede the emoji input, there is no crash.

### Expected behavior

Adding the emoji character without crashing

### Actual behavior

Adding an emoji character as the first character in a text node causes a crash

### Screenshots or video

https://github.com/penpot/penpot/assets/106775223/2d614f3f-a2b1-4998-9094-282722b297b9

### Desktop (please complete the following information)

- Penpot 2
- Firefox 124.0.2
- macOS 14.4.1

### Environment (please complete the following information)

https://design.penpot.app

**Comment by madalenapmelo-kp** [comment]
Hi @jeremiahlee,

Thank you for reporting this! I haven't been able to reproduce this behavior nor the one described in #4386, could you confirm if you also experience this behavior when working with other browsers?

**Comment by jeremiahlee** [comment]
@madalenapmelo-kp Safari 17.4.1 does not crash, but it does stretch.

https://github.com/penpot/penpot/assets/106775223/a33768d4-bae1-4fda-b4c7-a3960d429e48

**Comment by hypercross** [comment]
A similar crash happens when you use an IME to type the first character for like Chinese. You don't get the crash if you type a space before. The crash complains about calling `removeChild` on a `Node` that is not a child anymore.

**Comment by madalenapmelo-kp** [comment]
Hi @hypercross,

You're right - this is a known issue that we intend to fix in the future, however, because it requires some rework this is not something that we can prioritize at the moment. 

We have an [issue in our backlog on Taiga](https://tree.taiga.io/project/penpot/issue/6999) so that we can work on this at a later date.

I'm closing this issue here as this is already being tracked on #4163.
