### ISSUE TITLE
feature: Adding French Language Support 

### ISSUE THREAD

**Issue by Arylite** [uxbox/uxbox#4391]
### Is your feature request related to a problem? Please describe.

Yes, currently the project is only available in English, which may pose an issue for French-speaking users who are not proficient in English.

### Describe the solution you'd like.

I would like to add the French language to the project to allow French-speaking users to have a complete experience in their native language. 

### Describe alternatives you've considered.

An alternative would be to keep the project in English only and provide separate documentation in French. However, this could make the user experience less seamless and consistent for French-speaking users.

### Additional context

My weblate.org username is @Voxary

**Comment by madalenapmelo-kp** [comment]
Hi @V-o-x-a-r-y,

You can change the language to French by clicking on your name at the bottom left, going to **Your account -> [Settings](https://design.penpot.app/#/settings/options)**.

Let me know if there is anything else we can help you with :slightly_smiling_face:
