### ISSUE TITLE
bug: Transform Values of Instance overwritten on Name Change of Main Component - V2

### ISSUE THREAD

**Issue by l-kgr** [uxbox/uxbox#4396]
### Steps To Reproduce

1. Create some Main Component
2. Create Instance of Main Component
3. Rotate Instance
4. Change Name of Main Component
5. Instance gets rotated back

File to test: 
[bug-feature_ Keep local changes to variable if name changed.penpot.zip](https://github.com/penpot/penpot/files/14929347/bug-feature_.Keep.local.changes.to.variable.if.name.changed.penpot.zip)

### Expected behavior

If transform values of instance get overwritten by user manually (e.g. needed if a component needs to be rotated) and afterwards the main components name is changed (e.g. re-naming for better component structuring) the instance-transform should only be overwritten, if the users uses the right click modal menu option /reset-changes. 

Add:
This is a behavior I personally would expect to make the use of components more flexible. Not sure if the seen behaviour is intended or just a quality-of-live feature and not a bug. But noticably, if colors in the main component are changed, this change does not get translated automatically to the instance even if the main is re-named.

### Actual behavior

Transforms of instance get overwritten on name change of main component. 

### Screenshots or video

https://github.com/penpot/penpot/assets/147325029/5292cc39-7b1f-4a3a-b82f-5ca8cca47f5c

### Desktop (please complete the following information)

MacOS Sonoma 14.2.1 (23C71) - M1
Chrome Version 123.0.6312.105 (Official Build) (arm64)
Offical Penpot https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @l-kgr,

Thank you for reporting this! I've opened an issue on Taiga so that we can dig deeper into this - you can find the details here: https://tree.taiga.io/project/penpot/issue/7429

**Comment by hirunatan** [comment]
This bug has been fixed. Now geometric changes (rotation and resize) are independent of other ones like change name or color.
