### ISSUE TITLE
bug: Flags do not update for frontend container

### ISSUE THREAD

**Issue by bramvdzee** [uxbox/uxbox#4398]
### Steps To Reproduce

1. Update PENPOT_FLAGS environment variable for frontend to ' PENPOT_FLAGS=disable-registration disable-login-with-password enable-login-with-oidc'
2. Update PENPOT_FLAGS environment variable for backend to '- PENPOT_FLAGS=disable-registration enable-login-with-oidc disable-login-with-password disable-email-verification enable-smtp enable-prepl-server'
 3. Restart container

### Expected behavior

Front- and back-end flags should be updated.

### Actual behavior

Only back-end flags are updated. The front-end has no visual change.

### Screenshots or video

<img width="1792" alt="image" src="https://github.com/penpot/penpot/assets/6660590/e31e89d4-8b07-4fd2-842f-60242068fbb5">

### Desktop (please complete the following information)

- MacOS
- Firefox, Safari & Chome

### Environment (please complete the following information)

- Docker Compose v1.19.3

### Additional context

Back-end logs show that OIDC is configured correctly, but the front-end doesn't reflect this. Login is shows in the front-end, but disabled in the back-end.
I've cleared cache and cookies, and I've hard-reloaded the browser multiple times. It also doens't work in any other browser or in incognito mode.

**Comment by bramvdzee** [comment]
Changing my URL to something different seemed to help, but it seems like the config file was cached through Traefik (even though the cache-controlw as set to not have any cache).

**Comment by niwinz** [comment]
We will look in prove this but for now this looks a cache issue, that is not really a penpot problem as-is.
In any case, thanks for reporting.
