### ISSUE TITLE
bug: Working with the Path tool collapses the toolbar indefinitely

### ISSUE THREAD

**Issue by ancashoria** [uxbox/uxbox#4401]
### Steps To Reproduce

1. Click on Path tool
2. Click on Move Nodes
3. Move cursor outside of the toolbar
4. Toolbar remains collapsed

### Expected behavior

I should at least be able to open the toolbar by clicking on it.
Best outcome would be for the toolbar to remain open.

### Actual behavior

.

### Screenshots or video

https://github.com/penpot/penpot/assets/4144110/4916f218-4bb8-4e9d-93a5-0cd0e7cd7591

**Comment by madalenapmelo-kp** [comment]
Hi @ancashoria,

Thank you for reporting this! We are already working on fixing this, you can keep up with the progress made here: https://tree.taiga.io/project/penpot/issue/7411

**Comment by madalenapmelo-kp** [comment]
Hi @ancashoria,

This issue is now fixed!
