### ISSUE TITLE
bug:  Undo /Redo shorcuts do not work in text fields

### ISSUE THREAD

**Issue by adambelis** [uxbox/uxbox#4403]
### Steps To Reproduce

1. create text
2. type in  random charcters
3.  undo by ctrl+z

characters

### Expected behavior

Undo - last character should be removed

### Actual behavior

Nothing

### Desktop (please complete the following information)

- Win 10 Chrome

**Comment by madalenapmelo-kp** [comment]
Hi @adambelis,

Thank you for reporting this! I have opened an issue on Taiga so that we can look further into this, you can check it here: https://tree.taiga.io/project/penpot/us/1830

I'm closing this issue as this is already being tracked on issue #1479.
