### ISSUE TITLE
bug: Dragging bezier handle  stops working 

### ISSUE THREAD

**Issue by adambelis** [uxbox/uxbox#4409]
### Steps To Reproduce

1. drav circle 
2. double clcik on  circle so you can edit geometry
3. click and drag and hold LBM on bezier handel
4. holt alt to brake symmetry
5. let go  of ALT key but  still hold  LBM and movedraw

### Expected behavior

 symmetry would link back after i let go of ALT. and I could still move a bezier handle 
 
![inkscape_2HY1I8FW6J](https://github.com/penpot/penpot/assets/50795097/50416690-3ab1-4816-bf36-08d90f49c37f)

### Actual behavior

i no  longer manipulate position of bezier handel 

### Screenshots or video

![chrome_5aQoEOjqnU](https://github.com/penpot/penpot/assets/50795097/0ec1e4b5-6743-48bd-8bae-8c6bcd0f9188)

**Comment by madalenapmelo-kp** [comment]
Hi @adambelis,

Thanks for reporting this! Could you let me know which browser you are working with?

**Comment by adambelis** [comment]
its a chrome latest  win 10

**Comment by madalenapmelo-kp** [comment]
@adambelis I haven't been able to reproduce this behavior, could you export the `.penpot` file where you are experiencing this and send it to support@penpot.app so that we can look into it?
