### ISSUE TITLE
bug: Right panel overflows beyond the Edge in Microsoft Edge Browser

### ISSUE THREAD

**Issue by marekbrze** [uxbox/uxbox#4416]
### Steps To Reproduce

1. Select any frame (or any other element)
2. Try to add layout, border or something else
3. The button to add this setting is barely visible and most of it is hidden

### Expected behavior

Button to add layout/border etc should be clearly visible

### Actual behavior

Most of the button is overflowing outside of the viewport
![image](https://github.com/penpot/penpot/assets/1033055/c054bd31-c6d7-4cbb-99a4-e085bc17751b)

### Desktop (please complete the following information)

Windows 10 Enterprise
21H2
19044.4170
11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz   2.61 GHz
Microsoft Edge version 123.0.2420.81

### Additional context

_No response

**Comment by marekbrze** [comment]
![image](https://github.com/penpot/penpot/assets/1033055/3c16f47c-5339-4bfd-8cb7-52dcba15d47f)

**Comment by vixov** [comment]
The right panel doesn't have the 'plus' buttons. I noticed that the issue occurs in the Polish language version. In the English version, it's okay. @marekbrze  , I recommend temporarily switching to the English version.

**Comment by marekbrze** [comment]
Yup, the tabs on top are also too long. There needs to be some work done in the Polish version (I can offer help if needed)

**Comment by madalenapmelo-kp** [comment]
Hi,

Thank you all for reporting this! We are already working on fixing this, you can find more details on Taiga here: https://tree.taiga.io/project/penpot/issue/7421

**Comment by madalenapmelo-kp** [comment]
Hi @marekbrze,

This issue is now solved!
