### ISSUE TITLE
feature: Disable onboarding

### ISSUE THREAD

**Issue by KaKi87** [uxbox/uxbox#4421]
### Is your feature request related to a problem? Please describe.

Having to reply all the onboarding questions when self-hosting is highly annoying.

### Describe the solution you'd like.

Allow disabling onboarding.

### Describe alternatives you've considered.

None

### Additional context

None

---

Thanks

**Comment by niwinz** [comment]
You can use the following flags:  `disable-onboarding-questions`, `disable-onboarding-newsletter`, `disable-onboarding-team`, `disable-onboarding`, `disable-dashboard-templates-section` 
for disable all this and start always with clean dashboard.

**Comment by ghost** [comment]
Where can I add these flags for Penpot to skip the onboarding.

I tried it in the docker-compose yaml. With all kinds of variations 
I tried adding a config.edn 

after restarting docker, the onboarding screen is still there when creating new profiles

**Comment by KaKi87** [comment]
It worked immediately for me : just add those, space-separated, on the `PENPOT_FLAGS` line of the `penpot-frontend` section (not the `penpot-backend` section).

![](https://github.com/user-attachments/assets/9242e394-74cc-4211-b9b7-40df81ff5ddb)
