### ISSUE TITLE
bug: I can no longer paste a SVG directly on penpot

### ISSUE THREAD

**Issue by dfelinto** [uxbox/uxbox#4423]
### Steps To Reproduce

1. Go to https://ui.blender.org/icons
2. Click on any icon
3. Copy SVG code
4. Paste in Penpot

### Expected behavior

Before Penpot 2.0 pasting an SVG would simply work. Now I have to download the SVG, then drag it inside Penpot.

### Actual behavior

The SVG is pasted as simple text:
```
<svg
inkscape:export-ydpi="96"
inkscape:export-xdpi="96"
inkscape:export-filename="blender_icons.png"
style="display:inline;enable-background:new"
inkscape:output_extension="org.inksc
```

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/843498/0426293d-554c-4efe-a578-b56d07d9280d)

### Desktop (please complete the following information)

MacOS + Chrome Version 123.0.6312.107 (Official Build) (arm64)

### Environment (please complete the following information)

https://design.penpot.app

**Comment by niwinz** [comment]
We will look on it, thanks for reporting.

**Comment by madalenapmelo-kp** [comment]
Hi @dfelinto,

This issue is fixed, you can now paste the SVG directly on Penpot!

**Comment by dfelinto** [comment]
Thank you :)
