### ISSUE TITLE
bug: Collapsing 'Pages' section leaves empty space in the 'Layers' sidebar

### ISSUE THREAD

**Issue by unaaagy** [uxbox/uxbox#4425]
### Steps To Reproduce

1. Open a file with preferably many items in the `Components` section
2. Collapse the `Pages` section

### Expected behavior

The `Components` section should expand to the bottom.

### Actual behavior

Empty space is present at the bottom which obstructs the components.

### Screenshots or video

![annotely_image (1)](https://github.com/penpot/penpot/assets/155830121/4c1599de-8b6e-4434-87f1-9efb4470c64a)

### Desktop (please complete the following information)

- Browser: Google chrome

**Comment by madalenapmelo-kp** [comment]
Hi @unaaagy,

Thanks for reporting this! This is now being managed on Taiga, you can find the details here: https://tree.taiga.io/project/penpot/issue/7466

**Comment by madalenapmelo-kp** [comment]
Hi @unaaagy,

This issue has been fixed!
