### ISSUE TITLE
bug: Pixels in images are blurred

### ISSUE THREAD

**Issue by TheGreenSquare** [uxbox/uxbox#4433]
### Steps To Reproduce

1. Download the image I've attached.
2. Upload it into a Penpot workspace.
3. Zoom in far enough that the pixel grid is visible.

### Expected behavior

The pixels would be clearly displayed.

### Actual behavior

The pixels are blurred.

### Screenshots or video

This is the image I am using to test. I'll be using a section around the text "Bubbler" for the demonstration.
![samwidge](https://github.com/penpot/penpot/assets/93544652/a33fb3ad-6da4-4f01-8e03-9db2aed6615d)

This is how the zoomed in image is displayed in Penpot. The pixels are blurred way too much.
<img width="657" alt="Screenshot 2024-04-13 at 18 38 42" src="https://github.com/penpot/penpot/assets/93544652/977ada78-9901-45eb-a3d8-d7233c2341b0">

The same section in Figma, for comparison. The pixels are clearly visible, even at this level of zoom.
<img width="616" alt="Screenshot 2024-04-13 at 18 38 53" src="https://github.com/penpot/penpot/assets/93544652/51f37ea0-9262-4fd7-b935-894157b285e4">

### Desktop (please complete the following information)

- macOS 14.3.1
- Chrome 117

**Comment by madalenapmelo-kp** [comment]
Hi @Zephiii,

Thank you for reporting this! This is a known issue that will be addressed as part of a wider work to improve performance. 

Unfortunately, because this requires some rework, it is not something that we can prioritize at the moment.
