### ISSUE TITLE
bug: Color picker names are not displayed correctly on their tooltips

### ISSUE THREAD

**Issue by BOTzola** [uxbox/uxbox#4435]
### Steps To Reproduce

1. Click on the color palette for an element
2. Hover over the different options (rgb color pickers and hsv)
3. Check that the name displayed on the tooltip shows [object Object]

### Expected behavior

The tooltip label show mention the correct name of these different color pickers.

### Actual behavior

The color pickers name is not correctly parsed so it's showing [object Object] instead.

### Screenshots or video

![penpot color palette bug](https://github.com/penpot/penpot/assets/76270763/1dcca688-03c0-4a7d-9500-d6d33684cf94)

### Desktop (please complete the following information)

OS: Ubuntu 22.04
Browser: Mozilla Firefox 123.0.1

### Environment (please complete the following information)

Host: https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @BOTzola,

Thank for reporting this! I've created a bug on Taiga so that we can look into this, you can find it here: https://tree.taiga.io/project/penpot/issue/7460

**Comment by madalenapmelo-kp** [comment]
Hi @BOTzola,

This issue is now fixed!
