### ISSUE TITLE
bug: Shape selection is triggered on mouseup, so click+dragging shapes doesn't work

### ISSUE THREAD

**Issue by eeropic** [uxbox/uxbox#4440]
### Steps To Reproduce

- Create any shape
- Try to click and drag that shape, i.e. press mouse on object, and move mouse

### Expected behavior

The shape should be selected on mouse press, and moved while dragging / keeping mouse pressed

### Actual behavior

The shape is selected only when moving mouse or releasing mouse button -
so the shape is not moving while dragging -
it requires user to 
- first click to select
- next click + drag to move the object

### Screenshots or video

![shape-selection-drag-bug_](https://github.com/penpot/penpot/assets/6544296/a9f699df-07c8-47d1-b00e-fc88482c46ad)

### Desktop (please complete the following information)

- MacOSX 12.7.4
- Firefox 124.0.2

### Environment (please complete the following information)

[http://design.penpot.app](http://design.penpot.app)

### Additional context

The behaviour is like before when you click and drag a board from its title (as seen in the screenshot)

**Comment by eeropic** [comment]
I see this is already managed on taiga

[https://tree.taiga.io/project/penpot/issue/7448](https://tree.taiga.io/project/penpot/issue/7448)

But I would like to emphasize this seems like regression/bug, as the behaviour is as expected on v1.19

**Comment by madalenapmelo-kp** [comment]
Hi @eeropic,

You're right - this is where we're tracking this on Taiga, I've linked this issue there to be considered once we start working on this.

Thank you!

**Comment by madalenapmelo-kp** [comment]
Hi @eeropic,

Just to let you know that this issue has been fixed!
