### ISSUE TITLE
feature: Mouse drag to increase/decrease input values

### ISSUE THREAD

**Issue by Correct-Syntax** [uxbox/uxbox#4447]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like.

  Most design software (Figma, Sketch, etc.) allow you to "drag" the mouse over the input to increase or decrease values. Double-clicking allows you to edit the value by typing.

PenPot currently just allows typing values into the input. It would be nice if PenPot had this option.

**Comment by madalenapmelo-kp** [comment]
Hi @Correct-Syntax,

Thank you for the suggestion! We already have a User Story in our backlog on Taiga but it hasn't been prioritized yet, you can find the details here: https://tree.taiga.io/project/penpot/us/4080?backlog-q=drag&no-milestone=1

In the meantime, I'm closing this issue as this is already being tracked on #2466.
