### ISSUE TITLE
Failed to load thumbnails of projects and drafts.bug: 

### ISSUE THREAD

**Issue by yehao1991** [uxbox/uxbox#4448]
### Steps To Reproduce

Failed to load thumbnails of projects and drafts on the homepage.

### Expected behavior

Failed to load thumbnails of projects and drafts on the homepage.

### Actual behavior

Failed to load thumbnails of projects and drafts.
![image](https://github.com/penpot/penpot/assets/158235386/2bd7b487-1a1d-4121-9c38-1344c26dab15)

### Environment (please complete the following information)

ubuntu 22.04  Docker Compose version v2.26.1

**Comment by Eschin** [comment]
I'm seeing this also. I had the "spinning pencils" issue before I upgraded to 2.0. But now I just get 'broken thumbnails', like the screenshot shared above. (At least the spinning pencils went away 😆 )

I've seen 1 or 2 other similar issues posted for this kind of behavior too... I'll keep monitoring and watch out for fixes/suggestions, but if anyone needs any information/troubleshooting/debugging from my self-hosted instance, just let me know 👍 😃

**Comment by icsy7867** [comment]
I have lots of these loading issues as well

**Comment by synchromatik** [comment]
same, bump.

**Comment by Megastrik3** [comment]
Same here. No thumbnails will load for me. The browser console gives me 404 errors.

**Comment by Megastrik3** [comment]
Update for everyone who is experiencing this issue. From what I can tell, this is a permissions issue within the backend container. I found another support form for an issue relating to uploading libraries that seems to have fixed this issue for me.  https://github.com/penpot/penpot/issues/2876#issuecomment-1413296174

Based on the current docker compose file, using the command:
`docker exec -u 0 penpot-penpot-backend-1 chown penpot:penpot /opt/data/assets`
fixed the issue for me. Just make sure that `/opt/data/assets' is matches the backend containers internal directory path.

_Note: The thumbnails will still be broken for new files that don't have any contents in them. As soon as you add anything to the canvas though, the thumbnail appears._

**Comment by icsy7867** [comment]
Thanks for the post! This did not work for me.  I changed the permissions of all those files and directories.  However still no change.

Penpot needs the ability to regenerate thumbnails.  Looking into my console, I find the image URL for a non-working thumbnail.  In my case this looks like:

```
<img src="https://penpot.company.org/assets/by-id/de3e2487-ce6d-4627-af4c-cb187z3086b0" loading="lazy" decoding="async" class="main_ui_dashboard_grid__grid-item-thumbnail-image">
```

However that image URL ends up with a 404 - not found.  Working thumbnails get a 200 obviously, as it finds it and loads just fine.

*EDIT*

JUST KIDDING!  I did as you said, and slightly tweaked a canvas.  After leaving the page, I see the rotating pencil, and after about 30-45 seconds the thumbnail appears!

It would be great if you could manually trigger a "Thumbnail" regeneration somehow.

**Comment by Eschin** [comment]
> Update for everyone who is experiencing this issue. From what I can tell, this is a permissions issue within the backend container. I found another support form for an issue relating to uploading libraries that seems to have fixed this issue for me. [#2876 (comment)](https://github.com/penpot/penpot/issues/2876#issuecomment-1413296174)
> 
> Based on the current docker compose file, using the command: `docker exec -u 0 penpot-penpot-backend-1 chown penpot:penpot /opt/data/assets` fixed the issue for me. Just make sure that `/opt/data/assets' is matches the backend containers internal directory path.
> 
> _Note: The thumbnails will still be broken for new files that don't have any contents in them. As soon as you add anything to the canvas though, the thumbnail appears._

Thanks! This did fix it(sorta) :)

The thumbnails will only reappear after permissions are fixed for `/opt/data/assets`, and you open the canvas/file, and make a change/addition. Then the thumbnail regenerates and appears fine on the dashboard.

There must be some way to trigger a 'system wide thumbnail regeneration' after the changes, to avoid manually updating each file to get the thumbnail to reappear after fixing ownership..... 🤔 

Either way, this definitely fixes the thumbnails issue.
