### ISSUE TITLE
bug: "Move Nodes" mode in Path drawing makes the path "jump" in coordinates

### ISSUE THREAD

**Issue by eeropic** [uxbox/uxbox#4459]
### Steps To Reproduce

1. Draw a Path, for example 3 points
2. Select the points
3. Drag from one of the points

### Expected behavior

The path should move without "jumping", i.e. taking into account which point was dragged

### Actual behavior

The path "jumps" in coordinates, so that the last point is the reference point (arrowhead in screen capture gif below)

### Screenshots or video

![vector-path-point-move-bug](https://github.com/penpot/penpot/assets/6544296/37428d5c-613c-4b1e-930c-37291320bfc5)

### Desktop (please complete the following information)

MacOSX 12.7.4
Firefox 124.0.2

**Comment by madalenapmelo-kp** [comment]
Hi @eeropic,

Thank you for reporting this! I have opened an issue on Taiga so that we can look into this, you can see it here: https://tree.taiga.io/project/penpot/issue/7487

**Comment by eeropic** [comment]
@Alotor this issue arises from this line

https://github.com/penpot/penpot/blob/d1d3b4353a743f7dc683671b8d1d8968db48d18b/frontend/src/app/main/data/workspace/path/edition.cljs#L163

Commenting it out makes it work like expected, but probably breaks this fix below (moving path points zoomed):

https://github.com/penpot/penpot/commit/468e61e1e06a57135179b0956abe08fde10958e9

**Comment by eeropic** [comment]
I would like to point out that this is really an issue for anyone who draws vector icons, for example

I assume fixing this https://github.com/penpot/penpot/issues/2930 broke the behaviour
