### ISSUE TITLE
How to configure 'max-multipart-body-size' for the backend

### ISSUE THREAD

**Issue by suwagawaki** [uxbox/uxbox#4460]
I am unable to import a PenPot project file due to its size, which is close to 130MB. According to the log, which shows:
 
`→  io.undertow.server.RequestTooBigException: UT000020: Connection terminated as request was larger than 125829120 (FixedLengthStreamSourceConduit.java:173)
`
I believe it's related to this:

`max-multipart-body-size (* 1024 1024 120)} ; default 120 MiB`

Is this setting related to my issue and how can I adjust the setting to allow larger file sizes?

I have changed the 100MB file limit in my nginx.conf, which I believe is the other setting related to my issue and I do not see any errors in the frontend log since modifying that setting.

I've also tried setting an environment variable `JVM_OPTS=-Dapp.http.server.max-multipart-body-size=209715200` and variations of it to attempt to change the setting with `run.sh` at launch.

**Comment by carloshe-perez** [comment]
@suwagawaki how did you resolve this?
