### ISSUE TITLE
bug: Workspace-palette items stay hidden when opening with keyboard-shortcut

### ISSUE THREAD

**Issue by lplath** [uxbox/uxbox#4461]
### Steps To Reproduce

![panel](https://github.com/penpot/penpot/assets/4710568/11e328c9-f4ad-4a10-bc29-7eeb56fd1958) ![collapsed](https://github.com/penpot/penpot/assets/4710568/b75f5ed6-4361-484a-9b49-043a6a81aedd)

1. Double click the handle to fully collapse the workspace-palette
2. Reopen either the color- or typography palette using the keyboard-shortcut (Alt+ P or Alt + T)

### Expected behavior

![expected](https://github.com/penpot/penpot/assets/4710568/dc2f6416-c133-407f-9eeb-7ac9ef1d58fe)

### Actual behavior

The panel opens but the content is still hidden
![actual](https://github.com/penpot/penpot/assets/4710568/7d10ca21-37c5-4b43-91fd-8488219867be)

### Desktop (please complete the following information)

- Browser: Chrome 123 & Firefox 124

### Environment (please complete the following information)

- Host: https://penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @lplath,

Thank you for reporting this! I've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/7489

**Comment by madalenapmelo-kp** [comment]
Hi @lplath,

This issue is now fixed!
