### ISSUE TITLE
bug: unconnected dot expands selection area of an open path

### ISSUE THREAD

**Issue by ShibuyaCyana** [uxbox/uxbox#4473]
### Steps To Reproduce

1. draw an open path
2. press enter to end it, then place an unconnected dot nearby
3. press enter to exit path editing mode
4. watch the selection box becomes unreasonably wide.

### Expected behavior

Unconnected dot is automatically ignored.

### Actual behavior

Unconnected dot expands last drawn path selection box.

### Screenshots or video

https://github.com/penpot/penpot/assets/39703247/38f1550e-04ba-4448-a3c3-21571f29f89f

### Desktop (please complete the following information)

Windows 11 22H2
Firefox 124.0.2 (64-bit)

**Comment by madalenapmelo-kp** [comment]
Hi @ShibuyaCyana,

Pressing `Enter` only, will stop editing but to exit the editing mode you should then click `Esc`. Without exiting the edit mode, clicking somewhere else will create a new corner node.
