### ISSUE TITLE
bug: Prototype: "Open overlay relative to position center" doesn't work

### ISSUE THREAD

**Issue by dialmove** [uxbox/uxbox#4479]
### Steps To Reproduce

1. Create a component with a main state and several instances as sub-states, like the Action Button in the example image

![image](https://github.com/penpot/penpot/assets/3824360/dece5ab0-cb64-4a0c-913f-c10e6ce51ee3)

2. Link the main state to the first state with:
    * Action: Open overlay
    * Destination: the first sub-state instance
    * Relative to: Action Button (self)
    * Position: Center
3. Drag a copy of the main state inside a Board, and set a Flow start at the Board
4. Start the prototype

### Expected behavior

When the action is triggered, the overlay should appear centered over the Action Button initial main state.

![image](https://github.com/penpot/penpot/assets/3824360/1876d6a7-4007-4f81-8d91-810495c32c71)

### Actual behavior

The overlay is opened at the top left of the Board.

![image](https://github.com/penpot/penpot/assets/3824360/1b21f0ca-44f3-4ca7-a733-ac4896e9a4e8)

To fix the issue and make the overlay appear over the Action Button, _Position_ needs to be set manually instead.

![image](https://github.com/penpot/penpot/assets/3824360/5381b0b1-ac79-4e1e-adae-7a86eb8fad3e)

**Comment by madalenapmelo-kp** [comment]
Hi @dialmove,

Thanks for reporting this! I've opened an issue on Taiga so that we can look further into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/7563

**Comment by madalenapmelo-kp** [comment]
Hi @dialmove,

This issue is now fixed!
