### ISSUE TITLE
bug: Heavely slow and crashes all time handleing files

### ISSUE THREAD

**Issue by miguelgargallo** [uxbox/uxbox#4483]
### Steps To Reproduce

Work normally on files of version 1 on version 2, now it's unstable

### Expected behavior

bug: Heavely slow and crashes all time handleing files

### Actual behavior

bug: Heavely slow and crashes all time handleing files

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/5947268/a2c8e145-560e-4249-9bfc-7477e00fdc30)

**Comment by madalenapmelo-kp** [comment]
Hi @miguelgargallo,

Could you let me know the steps you followed prior to seeing this error? If you could send a screen recording of the steps leading up to this error and the `.penpot` file in which you are experiencing this to support@penpot.app, it would be really helpful!

**Comment by miguelgargallo** [comment]
Any file from the previous penpot v, besides content is confidential, our apologies
