### ISSUE TITLE
bug: Problem when adding text using the external penpot library

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4493]
### Steps To Reproduce

1. Try to call createText on the penpot library with a google font
2. A fetch is made to /internal/gfonts/css (we can only modify host using penpotPublicURI)
```html
    <script>
      window.penpotPublicURI = 'https://design.penpot.app';
    </script>
```

4. It will fail because of cors issues related to not having origin (request made from inside Figma)

More code here: https://github.com/penpot/penpot-exporter-figma-plugin/pull/61

The code can be executed in a simple Figma file:
1. Compile with npm run build (node 20)
2. Import plugin in Figma
3. Create a simple document with just a text
4. Try to export to get the error

### Expected behavior

On previous versions of the penpot library there was no call to /internal/gfonts/css. It was implemented here:  https://github.com/penpot/penpot/pull/3342

We think with previous versions of the penpot library there was no issue here. The ideal world would be to have a customizable url (so we can try to use the original from google fonts), or no need to do any api call to export texts (because we might have the same issue about null origins)

Is that something that could be customizable?

### Actual behavior

Unable to export texts with font family due to error on fetch

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/1137485/f421b895-afcd-40d5-a628-907d5400ad1f)

**Comment by jordisala1991** [comment]
I can confirm that trying to hack the library to make the calls directly to google does not help here:
![image](https://github.com/penpot/penpot/assets/1137485/44ffb1fa-db5c-4302-9bfa-bce3c92e4407)

But then, how was this working before? Maybe a call to google was not required before?

**Comment by jordisala1991** [comment]
We have doing further tests and it seems loading or not the font from google fonts does not affect anything on the generated file. So maybe the api call is needed in other parts of penpot but not for exporting with the penpot library.

The ideal solution would be to load the font in another point where does not interfere with the creation of the text: `createText` function. Another option is having the api call under a flag that we can disable on the figma exporter.

Maybe there are other alternatives that I am unaware since I don't exactly this font loading works and why it is needed.

**Comment by Alotor** [comment]
I don't think it's needed. Probably the font loading is a side effect that it's happening but we don't realize on the frontend. The exporter code probably is making a call that produces this side effect.

I've cloned your repostory to see if I can reproduce the error but at least on the main branch is not happening. If you let me try on your branch I can try to debug it.

**Comment by Cenadros** [comment]
Hi there @Alotor, 

You can test this in this branch: https://github.com/penpot/penpot-exporter-figma-plugin/tree/feature/text-fonts

The steps to reproduce are the same as described before.

Thank you!

**Comment by superalex** [comment]
Hi!, just merged the @Alotor PR related to this!

**Comment by Cenadros** [comment]
Thank you @Alotor @superalex. We just tried and it's working now.

**Comment by jordisala1991** [comment]
Closing as it is fixed now. Thanks ❤️
