### ISSUE TITLE
bug: Export frames loses opacity

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4494]
### Steps To Reproduce

1. Create a new document
2. Add an iframe with any opacity below 100
3. Export the document using zip format
4. Re import the same file

### Expected behavior

The frame of the imported document should be at the correct value. To give more context this is something that works as expected using the .penpot file, but it should also work on the .zip format file.

### Actual behavior

The frame of the imported document is always at 100 opacity

### Screenshots or video

https://www.loom.com/share/1be5da9f16c544b8ae9a4e2c95ffd54a?sid=c4395f75-c410-48de-9882-d828b73a8b05

**Comment by madalenapmelo-kp** [comment]
Hi @jordisala1991,

Thanks for reporting this - I have created an issue on Taiga so that we can look into it, the issue will be managed here: https://tree.taiga.io/project/penpot/issue/7592

**Comment by hirunatan** [comment]
Fixed!
