### ISSUE TITLE
bug: Export invisible shapes (any shape) are lost

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4495]
### Steps To Reproduce

1. Create any shape on a document
2. Make it not visible
3. Export file using .zip format
4. Re import the same file

### Expected behavior

All shapes are still in the document but not visible. This is what happens using .penpot format, but not with .zip

### Actual behavior

Not visible shapes are not in the result document.

### Screenshots or video

https://www.loom.com/share/6fd3ec8f9c0d427d950193bf57552110?sid=8c04ba75-f984-4e39-8f64-863ea8e70bf8

**Comment by madalenapmelo-kp** [comment]
Hi @jordisala1991,

Thanks for reporting this! I have opened a bug on Taiga so that we can look further into this, the details can be found here: https://tree.taiga.io/project/penpot/issue/7595

**Comment by madalenapmelo-kp** [comment]
Hi @jordisala1991,

This issue has been fixed!
