### ISSUE TITLE
bug: Export shapes that are rotated act a bit strange when reimported

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4496]
### Steps To Reproduce

1. Create any shape (ideally a shape that is not the same width than height, so you notice better the problem)
2. Apply a rotation
3. Export the document using .zip format
4. Re import the document and open it

### Expected behavior

The shape is rotated, and I can select it correctly, and if I want to remove the rotation I can do it. (This is what happens with .penpot format, but not with .zip)

### Actual behavior

The shape looks rotated, but I think internally penpot thinks its not. The mouse is only able to select if you click on the non rotated position (take a look at the video), and if you remove rotation, it looks like it is applying another rotation.

To give you more context, we are trying to apply rotations when exporting from Figma. And we encounter this issue, there are also other issues regarding rotations but lets do one by one.

### Screenshots or video

https://www.loom.com/share/c51bc667635549c9b7f0b8b71df7d553?sid=31905e2c-64b7-4ce2-b42d-b4dab5311fc0

**Comment by jordisala1991** [comment]
We also have more issues related to rotations but we can open different issues for them.

**Comment by madalenapmelo-kp** [comment]
Hi @jordisala1991,

Thanks for reporting this! I have opened an issue on Taiga so that we can look into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/7585

**Comment by hirunatan** [comment]
fixed

**Comment by jordisala1991** [comment]
I just tried again with the code from develop (using a local install of Penpot) and the Figma plugin compiled with the latest version of the penpot library, and the same behavior is happening.

Not sure if I have the correct version, but locally with the develop branch I can reproduce it using the video provided in the initial post.

**Comment by jordisala1991** [comment]
NVM, we just saw in our last demo that everything works now in the dev envinroment, so please forget my last comment.
