### ISSUE TITLE
bug: Missing latest source strings in Weblate

### ISSUE THREAD

**Issue by girafic** [uxbox/uxbox#4497]
### Steps To Reproduce

Missing latest source strings in Weblate.
 
<img width="359" alt="grafik" src="https://github.com/penpot/penpot/assets/1187276/0430274d-3976-4b39-ad35-a5a9668a9858">

### Expected behavior

Upload latest source strings to Weblate.

### Actual behavior

Missing latest source strings in Weblate.

**Comment by madalenapmelo-kp** [comment]
Hi @girafic,

Thank you for reporting this! We expect to publish the latest translations updates by the end of the week.

**Comment by superalex** [comment]
Hi @girafic 

Thank you very much for reporting this, latest source strings should be available in Weblate ;)
