### ISSUE TITLE
bug: Realy laggy on firefox

### ISSUE THREAD

**Issue by wineTGH** [uxbox/uxbox#4509]
### Steps To Reproduce

1. Use firefox
2. Done

### Expected behavior

Work smooth as figma

### Actual behavior

Highly floating frame rate. Just impossible to use

### Screenshots or video

[output.webm](https://github.com/penpot/penpot/assets/66317493/742b22cb-f313-4cf2-bf1d-2d04fdffe434)

### Desktop (please complete the following information)

- System: Fedora 40
- Browser: Firefox 125.0

### Environment (please complete the following information)

- Host: https://design.penpot.app
- System: Fedora 40
- DE: Gnome 46
- Graphical session: wayland

**Comment by myfunnyandy** [comment]
Hi @wineTGH 

Thank you for your report, we are aware that there are performance challenges that we need to face. However, some best practices might help you out:
Chrome is the faster and most efficient browser when working with Penpot. If you are using another, consider switching to Chrome.
File size and layer amount affect the performance. Consider dividing your work in more files and more pages to get better performance.
We've identified that shadows with big values significantly affect performance.

We are also working on the Penpot performance overall, we expect to publish improvements in the next releases.
