### ISSUE TITLE
bug: When drawing a line with an stroke cap, if you apply a inner shadow to it, the stroke cap partially disappears

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4517]
### Steps To Reproduce

1. Draw a line (the direction of it does not matter)
2. Apply a stroke cap (for example an arrow)
3. Apply a inner shadow to it

### Expected behavior

The line and the stroke cap get the inner shadow

### Actual behavior

Part of the arrow is invisible now. It looks like after applying the inner shadow, the bounding box acts like a mask (when previously allowed the arrow cap to be outside its bounds)

### Screenshots or video

https://www.loom.com/share/67bcd24b8e6b4fa7acb549fcb9d195df?sid=d57c88b0-82c3-4ff6-8072-e7709b94d2cc

**Comment by daniel-herrero** [comment]
Hi,

We've opened [a bug at Taiga](https://tree.taiga.io/project/penpot/issue/7627) to track this issue from here. We will try to fix it soon. 

Thanks for reporting it!
