### ISSUE TITLE
bug: Keycloak OIDC not working

### ISSUE THREAD

**Issue by nsauter** [uxbox/uxbox#4529]
### Steps To Reproduce

I added the Environment Variables in docker-compose.yaml and restarted the docker containers:

      - PENPOT_FLAGS=enable-login-with-password disable-email-verification enable-prepl-server enable-registration disable-login enable-login-with-oidc
      ## Keycloak OIDC
      - PENPOT_OIDC_CLIENT_ID=penpot
      # Mainly used for auto discovery the openid endpoints
      - PENPOT_OIDC_BASE_URI=https://auth.mydomain.de/auth/realms/myrealm/
      - PENPOT_OIDC_CLIENT_SECRET=super_secure_secret_here
      - PENPOT_OIDC_AUTH_URI=https://auth.mydomain.de/realms/myrealm/protocol/openid-connect/auth
      - PENPOT_OIDC_TOKEN_URI=https://auth.mydomain.de/realms/myrealm/protocol/openid-connect/token
      - PENPOT_OIDC_USER_URI=https://auth.mydomain.de/realms/myrealm/protocol/openid-connect/userinfo
      - PENPOT_OIDC_ROLES=""
      - PENPOT_OIDC_ROLES_ATTR=""
      - PENPOT_OIDC_SCOPES="openid profile email"
      - PENPOT_OIDC_NAME_ATTR="preferred_username"
      - PENPOT_OIDC_EMAIL_ATTR="email"

### Expected behavior

Keycloak Login is successful and Penpot login works

### Actual behavior

When i try to access penpot i get asked for my keycloak credentials with a keycloak login screen. But after Login i only get a 404 nginx error. 

### Screenshots or video

![Bildschirmfoto vom 2024-04-26 09-53-17](https://github.com/penpot/penpot/assets/32739286/6c8ebab0-e29b-4a1e-b555-4f5b1f1e8e3b)

**Comment by nsauter** [comment]
Sorry, i had something misconfigured.

**Comment by thebaultyoann** [comment]
> Sorry, i had something misconfigured.

Can you precise what was misconfigured ?
