### ISSUE TITLE
bug: Letter spacing for text is not being correctly applied when importing a .zip without position-data

### ISSUE THREAD

**Issue by Cenadros** [uxbox/uxbox#4533]
### Steps To Reproduce

We're working in the https://github.com/penpot/penpot-exporter-figma-plugin and we've generated a .zip file from Figma containing a text node with all the information given in the content. Although the letter-spacing is being imported, it's not being rendered.

The steps to reproduce are these:

1. You can try from the main branch of the [penpot-exporter](https://github.com/penpot/penpot-exporter-figma-plugin) or download the [generated .zip](https://github.com/penpot/penpot/files/15145852/Untitled.zip). If you use the attached .zip you can jump to step 6.
2. Build the plugin with node 20 (npm run build)
3. Import the plugin in FIgma using the manifest.json.
4. Create a text node in Figma and assign a letter space (you can do it in px or % but it's easier to see the translation in px)
5. Use the plugin to export the file.
6. Import the generated file into Penpot

### Expected behavior

The letter spacing being imported through text content should be rendered correctly.

### Actual behavior

The letter spacing is being imported but it's not being rendered until you modify the property in Penpot.

### Screenshots or video

The imported file with 50px of letter spacing but not rendered:
![image](https://github.com/penpot/penpot/assets/5689481/25e78845-3e85-4c65-826e-044359d71d99)

The same text with correct 50px of letter spacing after modifying it:
![image](https://github.com/penpot/penpot/assets/5689481/3871e63a-b8c7-421d-8c68-3446c9a3f4ac)

**Comment by madalenapmelo-kp** [comment]
Hi @Cenadros,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8118

**Comment by superalex** [comment]
Hi @Cenadros 

I've been checking the problem and in the attached zip the line-height has a value of 50 (numeric) and it should be "50" (string). Could it be a problem in the plugin when generating this value?

**Comment by Cenadros** [comment]
I'm closing this issue because it's an issue from our plugin that we're currently solving.
