### ISSUE TITLE
bug: ⚔️ Issues in importing svgs.

### ISSUE THREAD

**Issue by omegaui** [uxbox/uxbox#4542]
### Steps To Reproduce

Grab an svg from any of [fffuel image genertors](https://fffuel.co/).
And try to import it in by drag and drop.

### Expected behavior

Colored svg, the actual one should be imported.

### Actual behavior

A blank svg with no content is imported.

### Desktop (please complete the following information)

Chrome.

**Comment by madalenapmelo-kp** [comment]
Hi @omegaui,

I was able to drag and drop the SVG samples into Penpot without any issues.

[Screencast from 06-05-2024 17:54:52.webm](https://github.com/penpot/penpot/assets/144885032/1f69d39b-6aae-48b6-9035-24bb46b381e2)

The problem may be the format of the SVG shapes on the generator so there seems to be something on the service preventing the drag and drop action under certain conditions. It doesn't seem like this is a problem on Penpot's side so I would suggest contacting https://fffuel.co/contact/ directly.

**Comment by omegaui** [comment]
@madalenapmelo-kp Thanks for testing it out.
I'm sure this behaviour is replicable, I've seen it many a times on penpot, the same thing works fine in figma.

I'll try again, if the issue still persist, I'll put a sample svg here.
