### ISSUE TITLE
bug: Toolbar keeps toggling on and off on spacebar press

### ISSUE THREAD

**Issue by Manueljlin** [uxbox/uxbox#4544]
### Steps To Reproduce

1. Open Penpot document
2. Click on the top toolbar line to hide
3. Hold space and click to pan

### Expected behavior

Focus is taken away from the toolbar hide action right after toggling visibility (or at least, when hiding)

### Actual behavior

After clicking the toolbar hiding DOM element, the focus on it is kept, so each time an user wants to pan in the document by holding space, it triggers the toolbar's onKeyDown event (toggling visibility) until the user clicks on the canvas or another UI region.

### Desktop (please complete the following information)

- OS: openSUSE Tumbleweed
- Browser: Firefox 125.0.2

### Environment (please complete the following information)

Official instance (penpot.app)

**Comment by madalenapmelo-kp** [comment]
Hi @Manueljlin,

I've added this issue to our backlog on Taiga, you can find the details here: https://tree.taiga.io/project/penpot/issue/7654

**Comment by madalenapmelo-kp** [comment]
Hi @Manueljlin,

This issue is now solved!
