### ISSUE TITLE
bug: changing a color on imported svg also changes the stroke alignment

### ISSUE THREAD

**Issue by Mai-Lapyst** [uxbox/uxbox#4548]
### Steps To Reproduce

1. Import the "Lucide-Icons" library.
2. Create a new file and import the "Lucide-Icons" library.
3. Choose any icon (i.e. "rocket") and place it onto the workspace/canvas.
4. Change the color attribute from black to any other color and notice how the lines itself changes.
5. Revert back (or place a new one)
6. Disconnect the component
7. Click any path of the icon (i.e. the main body of the rocket), find the "Stroke" section and change the color again.
8. Notice the same effect and also that the "stroke.alignment" value has changed from "Center" to "Inside".

### Expected behavior

That a simple colorchange of imported svg's (espc. ones that are used for icons) do not break when only changeing the color, so users can color the icons accordingly.

### Actual behavior

By setting the color, either the color inherited from strokes for a component or the color of a stroke directly, the stroke itself changes it's alignment value back to the default of "Inside".

### Screenshots or video

https://github.com/penpot/penpot/assets/67418776/064a9cf7-e1be-4d2a-be4f-7a56f9f83793

### Desktop (please complete the following information)

- OS: Arch Linux
- Browser: Firefox 124.0.1 & Vivaldi 6.6.3271.55

### Environment (please complete the following information)

- Host: design.penpot.app

**Comment by madalenapmelo-kp** [comment]
Hi @Mai-Lapyst,

Thanks for reporting this! We are now tracking this on Taiga, you can find the details here: https://tree.taiga.io/project/penpot/issue/7673

**Comment by madalenapmelo-kp** [comment]
Hi @Mai-Lapyst,

This issue is now fixed!
