### ISSUE TITLE
bug: Image export failing frequently on design.penpot.app

### ISSUE THREAD

**Issue by jamesapyrich** [uxbox/uxbox#4566]
### Steps To Reproduce

1. Create 1920x1080 board
2. Populate with image & text assets
3. Select board
4. Click the dots, File -> Export
5. Confirm the selection of the board to 1920x1080 PNG

### Expected behavior

PNG file is exported

### Actual behavior

Notification: "Export failed: Retry"
Attempting to retry does not work

### Desktop (please complete the following information)

- Windows 11
- Brave 1.65.123

### Smartphone (please complete the following information)

n/a

### Environment (please complete the following information)

- Host: https://design.penpot.app/

### Frontend Stack Trace

```console
None
```

### Backend Stack Trace

```console
None
```

### Additional context

POST to `https://design.penpot.app/api/export` does return a success
Websocket on `wss://design.penpot.app/ws/notifications` comes back with
```
{
  "~:type":"~:export-update",
  "~:resource-id":"png.157db790-1d89-8046-8004-5190720a2705",
  "~:status":"error",
  "~:cause":"locator.waitFor: Timeout 10000ms exceeded.\nCall log:\n  - waiting for locator('#screenshot-9a2a3990-0e6a-804d-8003-b7b47e0ada5f') to be visible\n"
}
```

**Comment by madalenapmelo-kp** [comment]
Hi @jamesapyrich,

I haven't been able to reproduce this behavior, could you [export the .penpot file](https://help.penpot.app/user-guide/import-export/#files-export) and send it support@penpot.app so that we can look further into it?

**Comment by jamesapyrich** [comment]
Absolutely, sending that off now. Thanks!

**Comment by madalenapmelo-kp** [comment]
Hi @jamesapyrich,

The team has reviewed this and this is a known rendering issue that will be addressed as part of a wider work to improve performance.

Unfortunately, because this requires some rework, it is not something that we can prioritize at the moment.
