### ISSUE TITLE
bug: SVG attrs are not handled correctly when exporting/importing in .zip

### ISSUE THREAD

**Issue by Cenadros** [uxbox/uxbox#4593]
### Steps To Reproduce

The steps to reproduce are as follow:

1. Insert [this .svg](https://github.com/penpot/penpot/assets/5689481/07c43e47-5732-404c-9296-b09fb2d378d1) which has a specific `fill-rule="evenodd"` setting  into a blank document in penpot.
2. Export the document as .zip.
3. Reimport the .zip -> The fill-rule is ignored and the .svg is not visualized correctly

### Expected behavior

The svg attributes are translated correctly

### Actual behavior

The svg attributes are handled and translated correctly into penpot.

### Screenshots or video

- Svg file imported into Penpot:

![image](https://github.com/penpot/penpot/assets/5689481/67fa016a-e05f-48a2-bff6-cd4594ec0958)

- .zip file imported into Penpot after exporting previous document:

![image](https://github.com/penpot/penpot/assets/5689481/4e7ec291-1b79-4056-acfa-2c891a56a917)

**Comment by madalenapmelo-kp** [comment]
Hi @Cenadros,

I have added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/7920

**Comment by madalenapmelo-kp** [comment]
Hi @Cenadros,

This issue is now fixed!
