### ISSUE TITLE
bug: weird movement to the left when selecting an artboard

### ISSUE THREAD

**Issue by mlgarchery** [uxbox/uxbox#4597]
### Steps To Reproduce

I experienced a weird issue where the current object I was editing is slightly moved to the left when selecting it, which was super annoying. Note that duplicating the project removed the issue in the newly created project.
I have exported the project in which it happened after having removed everything but a simple artboard.

To reproduce:
- import the penpot file: [decalage.zip](https://github.com/penpot/penpot/files/15367162/decalage.zip)
- open the project
-  select &deselect the artboard to see a movement from left to right

### Expected behavior

There should be no movement of the selected object.

### Actual behavior

The object is moving, thus adding some unwanted shifting

### Screenshots or video

[Screencast from 19-05-2024 02:22:52.webm](https://github.com/penpot/penpot/assets/16239564/271502d1-f620-4352-8784-cea59da2fd60)

### Desktop (please complete the following information)

- Ubuntu, Vivaldi

**Comment by madalenapmelo-kp** [comment]
Hi @mlgarchery,

I haven't been able to reproduce this behavior, could you try it on other browsers and let me know if you see it there as well?
