### ISSUE TITLE
bug: Inverted order of exported boards in PDF

### ISSUE THREAD

**Issue by icubyx** [uxbox/uxbox#4598]
### Steps To Reproduce

Steps to reproduce:
1. Create 3 boards with different content
2. Duplicate board 2, name it as board 4, and place it below the row of 3 boards
3. File > export boards as PDF
4. View - PDF is in inverted order - starts with last board first and does not follow placement

### Expected behavior

Exported boards should be in same order as created and placed - left to right, top to bottom, no matter what the creation / duplication order is. So the order in this case should be - Board 1, 2, 3, 4

### Actual behavior

Exported boards are ordered from last to first like this - Board 3,4,2,1

### Desktop (please complete the following information)

MacOS 14.4
Firefox 126

### Environment (please complete the following information)

https;//design.penpot.app

**Comment by madalenapmelo-kp** [comment]
Hi @icubyx,

Thanks for reporting this! This is now being managed on Taiga: https://tree.taiga.io/project/penpot/issue/7851

**Comment by madalenapmelo-kp** [comment]
Hi @icubyx,

The team has reviewed this issue and this behavior is actually working as intended since the order of the PDF pages reflects the order of the layers rather than their position at the viewport.

Changing this behavior would require proper consideration and design, and this is not something that we plan to address in the foreseeable future.

**Comment by AnneFaubry** [comment]
I do admit I found this very inconenient as well. I expected just the same behavior as @icubyx detailed. 
At least @madalenapmelo-kp , maybe an explanation as you gave could be added in the interface when we export? At least thanks to your feedback I could reorder my layers properly to export a clean file but it is a shame we need to go to GitHub to learn that.
