### ISSUE TITLE
Contributing to Korean Translation

### ISSUE THREAD

**Issue by cypar** [uxbox/uxbox#4611]
Hello, I would like to contribute to translate to Korean. My Weblate ID is **@cypark**. Please let me know if there is anything else you need. Thank you.

**Comment by madalenapmelo-kp** [comment]
Hi @cy-park,

I've already added you to the translation project! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/ko/) and start translating. 

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution :slightly_smiling_face:
