### ISSUE TITLE
feature: mirror app to present apps design on mobile

### ISSUE THREAD

**Issue by noor-tg** [uxbox/uxbox#4622]
### Is your feature request related to a problem? Please describe.

I tried to use penpot from android browser (brave, firefox) to present mobile app. like the plant app from templates and libraries.and it is not working correctly. 
- when I try fill the design to screen it is not working. sometimes the designed page is bigger sometimes smaller.
- even fit is not working correctly.
- and when I try to use fullscreen . there is top bar space as I drafted issue about it before.
- the presentation topbar is not responsive with mobile screen. so some buttons is hidden when open penpot presentation page in mobile browser

### Describe the solution you'd like.

simply app like figma mirror to mirror design presentations and show them in fullscreen. and better if it detect realtime change and show them directly if the mirror app is open.

or make custom presenter for mobile browsers

### Describe alternatives you've considered.

I tried to open penpot from mobile browser . and there is many problems as it is described above.

### Additional context

exactly or partially like [figma mirror](https://play.google.com/store/apps/details?id=com.figma.mirror)

**Comment by madalenapmelo-kp** [comment]
Hi @noor-tg,

Thanks for the suggestion! We already have an improvement in our backlog for this, I've linked this issue there so that your input will be considered once we start working on it!

In the meantime, I'm closing this issue as this is already being tracked at #2421 :slightly_smiling_face:
