### ISSUE TITLE
bug: Panning with spacebar doesn't work when the zoom cursor is enabled

### ISSUE THREAD

**Issue by cypar** [uxbox/uxbox#4628]
### Steps To Reproduce

1. Press `z` key to turn cursor into the `[+] magnifier`.
2. While pressing `z`, press `option (⌥)` key to turn it `[-] magnifier`. 
3. Release both `z` and `option (⌥)` key. Confirm that the cursor is now `[+] magnifier`.
4. Press `spacebar` and confirm the cursor shape changes to `Hand`. 
5. Try to pan around with mouse dragging while pressing `spacebar`. Confirm it doesn't pan (this is a bug).

### Expected behavior

When `Hand` cursor appears, it should pan around with mouse dragging.

### Actual behavior

The viewport doesn't pan, staying frozen.

### Desktop (please complete the following information)

OS: macOS Ventura 13.0.1 (22A400)
Browser: Chrome Version 124.0.6367.210 (arm64)

**Comment by madalenapmelo-kp** [comment]
Hi @cy-park,

Thanks for reporting this! It seems like this is an issue with macOs specifically, I've transfered this to Taiga so that we can look further into it: https://tree.taiga.io/project/penpot/issue/7980

**Comment by madalenapmelo-kp** [comment]
Hi @cy-park,

I'm closing this issue as it has been reviewed internally and we are no longer able to reproduce it.

Thanks!
