### ISSUE TITLE
bug: Guides stay in place when moving board in the sidebar

### ISSUE THREAD

**Issue by lplath** [uxbox/uxbox#4640]
### Steps To Reproduce

1. Create a board
2. Add a guide

![initial](https://github.com/penpot/penpot/assets/4710568/93bab63c-4aa5-4aa4-ab21-75f0454bbab1)

### Expected behavior

When moving the board, the guides should move with it. This is the case, when moving the board by dragging.

![expected](https://github.com/penpot/penpot/assets/4710568/723cbc88-e33d-4a31-8930-98da1c9892f9)

### Actual behavior

When editing the Y-position of the board in the sidebar by +100px, the guide seems to shift in the opposite direction by 100px but really just stays in place.

![actual](https://github.com/penpot/penpot/assets/4710568/68a44187-4b74-4d41-a930-788dc3aa9455)

**Comment by madalenapmelo-kp** [comment]
Hi @lplath,

Thanks for reporting this! I've added this to our backlog on Taiga so that we can look into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8010

**Comment by madalenapmelo-kp** [comment]
Hi @lplath,

This issue is now solved!
