### ISSUE TITLE
feature: permit to have an image as background instead of color

### ISSUE THREAD

**Issue by henri9813** [uxbox/uxbox#4656]
### Is your feature request related to a problem? Please describe.

I want to be able to create a container, define it a "background" image ( without playing with z index ).

And set content inside.

### Describe the solution you'd like.

<img width="266" alt="image" src="https://github.com/penpot/penpot/assets/4645967/4099ff0b-0d9e-4b6b-9bff-3f41b5dfb37a">

Instead having only "colors", I would like to set an image.

**Comment by madalenapmelo-kp** [comment]
Hi @henri9813,

You can already define an image as a background by opening the color fill and selecting the color type **Image** :slightly_smiling_face: 
![Screenshot from 2024-05-30 13-05-41](https://github.com/penpot/penpot/assets/144885032/e3453139-5994-4719-9f49-572429e1c922)

**Comment by henri9813** [comment]
Hello,

Thanks for your reply, indeed you right, the feature is present.

Is there a way to improve to placement of this to make this more "easy to find" ? 

<img width="263" alt="image" src="https://github.com/penpot/penpot/assets/4645967/25529075-a870-4f98-9fe7-fc7f2af430e6">

**Comment by madalenapmelo-kp** [comment]
Hi @henri9813,

I've added your suggestion to our backlog so that we can consider it down the line, but please consider that this is not a priority for us at the moment so this could take some time to review.

Thanks!

**Comment by henri9813** [comment]
Hello,

Totally agree with you ! It's just to keep it somewhere :)

Best regards and thanks to develop Penpot !

**Comment by henri9813** [comment]
@madalenapmelo-kp , can we recreate an issue for this improvement ?
