### ISSUE TITLE
bug: Deleted components can't be restored when importing in .zip

### ISSUE THREAD

**Issue by Cenadros** [uxbox/uxbox#4669]
### Steps To Reproduce

Steps to reproduce:

1. Create a component
2. Create an instance from that component
3. Delete the component
4. Export the file as svg+json
5. Import the file
6. Try to restore the deleted component

### Expected behavior

The main component is restored as it happens when exporting/importing in .penpot format.

### Actual behavior

The main component can't be restored because of an internal error.

### Screenshots or video

Working in .svg + .json format:

https://github.com/penpot/penpot/assets/5689481/ec56d9f4-f50c-4928-98b3-fd114d1ca511

Working in .penpot format:

https://github.com/penpot/penpot/assets/5689481/9031b7fd-80d7-4f15-b12f-a5df4d3cb62c

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be release soon!
