### ISSUE TITLE
bug: Component Library is lost after exporting/importing in .zip format

### ISSUE THREAD

**Issue by Cenadros** [uxbox/uxbox#4672]
### Steps To Reproduce

Steps to reproduce:

1. Create a new document in penpot.
2. Create a component.
3. Export the document in .svg + .json format.
4. Import the file
5. Export the new file again in .svg + .json format.
6. Import the new file again.

### Expected behavior

Component library is imported.

### Actual behavior

Component library is lost after the second import.

### Screenshots or video

https://github.com/penpot/penpot/assets/5689481/6e11e68b-f263-471f-a1ff-d99ee256665c

**Comment by hirunatan** [comment]
I've created an issue in taiga to track this in the current sprint.

https://tree.taiga.io/project/penpot/issue/8030

**Comment by hirunatan** [comment]
Fixed!
