### ISSUE TITLE
bug: display grid wrong percentage calculation

### ISSUE THREAD

**Issue by henri9813** [uxbox/uxbox#4688]
### Steps To Reproduce

When using display grid mode,

the 30% is computed as 3000% ( cf the screenshot ).

<img width="259" alt="image" src="https://github.com/penpot/penpot/assets/4645967/8071c45c-a372-4898-8d9e-df034bdf8013">

Best regards

### Expected behavior

30% should be computed as 30%

### Actual behavior

30% is computed as 3000%

**Comment by madalenapmelo-kp** [comment]
Hi @henri9813,

Thanks for reporting this! I've opened an issue on Taiga so that we can look into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/8050

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be release soon!
