### ISSUE TITLE
bug: :bug: Components visibility and opacity

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4694]
### Steps To Reproduce

1. Create a component A
2. Create a frame an put inside 2 copies of the component A
3. Create a component B with the frame
4. Create an instance of component B
5. Modify the 2 copies of the instance of component B (one of them make it visible false and the other make it with 0 opacity)
6. Export the file in zip format
7. Import the file

### Expected behavior

The opacity and visibility is respected

### Actual behavior

The invisible componet got removed and the opacity is not respected

### Screenshots or video

https://www.loom.com/share/01c092d56bc648b4bd6f9703ccb45727

### Additional context

The visibility thing is something that happens on all kinds of shapes, not only on components. But it is specially problematic on components, since you are not suposed to be deleting inner pieces of a component instance (you instead make them invisible).

The opacity thing is specific from component instances

**Comment by jordisala1991** [comment]
Once this issue is fixed we can apply this PR to the penpot-exporter-figma-plugin: https://github.com/penpot/penpot-exporter-figma-plugin/pull/146

**Comment by hirunatan** [comment]
I've created this issue in Taiga to track the work here https://tree.taiga.io/project/penpot/issue/8070

**Comment by hirunatan** [comment]
Fixed. You can find it in develop branch
