### ISSUE TITLE
bug: Penpot interface copletely zoomed out and cant zoom in

### ISSUE THREAD

**Issue by Supervisor360** [uxbox/uxbox#4705]
### Steps To Reproduce

Jus press ctrl and -, and it zooms out evenything and now i can see the buttons nor can work on my ui.

### Expected behavior

all i wanted was to zoom out in the ui viewer. Not the whole damn interface

### Actual behavior

So when i press ctrl -, it will make the whole app small and i cant see anything. I try to press ctrl + to zoom back in but it does nothing...

### Screenshots or video

![Captura desde 2024-06-08 16-45-29](https://github.com/penpot/penpot/assets/105894549/20fa35b6-df55-4a1f-80d0-d601dddc8ff6)

### Desktop (please complete the following information)

- Fedora Linux 40  Gnome (Client from Flatpak)

### Environment (please complete the following information)

Fedora 40 gnome

**Comment by madalenapmelo-kp** [comment]
Hi @Supervisor360,

Could you let me know if you are still experiencing this issue?

**Comment by Supervisor360** [comment]
i quit penpot, so no im not, thanks tho

**Comment by alea-dm** [comment]
I have the exact same issue and it happened the exact same way

<img width="3840" height="2400" alt="Image" src="https://github.com/user-attachments/assets/8d0ab07a-be00-4f28-addb-22b3a8bd723e" />

**Comment by alea-dm** [comment]
the only thing that seemed to work was to delete the application and re-install it.
