### ISSUE TITLE
bug: Basic Functionalities not working as intended

### ISSUE THREAD

**Issue by EaZyStudiio** [uxbox/uxbox#4706]
### Steps To Reproduce

Am just show like 5 bugs at once with a video since they are maily all canvas related bug I don't think making seperate requests would help...

Move tool: Selection selecting objects Must be from an offset
 - Objects (a line) must be inside a group rotated 45degrees
 - at the end of the video I was clicking and dragging to move the line

https://github.com/penpot/penpot/assets/55167211/fb834acc-2148-47ba-be58-3671a803fbb5

Tool bar randomly going into it's shell: 

https://github.com/penpot/penpot/assets/55167211/bf4c29ca-0d33-4b0f-ac06-6d829434155e

could not reproduced on video but I had distribution bugs with the line where when I tried to increase the vertical lines all at once my spacing just got messed up

Zoom: Zooming with touch not working??

Sorry about the low quality`videos github 10mb max And I though external links might be too spooky 🥲

### Expected behavior

in steps to reproduce

### Actual behavior

in steps to reproduce

### Screenshots or video

in steps to reproduce

### Desktop (please complete the following information)

Windows
Egde 126.0.2592.36

**Comment by EaZyStudiio** [comment]
New Bug Flipping Horizontal or Vertical

it Just Kinda works until you go into edit mode:
    - Create a rectangle round 2 Coners "yes just 2 not 4"
    - flip it horizontal 
    - double click on it

and U get the magic below

![image](https://github.com/penpot/penpot/assets/55167211/4e076613-665b-4d19-8b05-349cf4c40b93)

Hope this helps

**Comment by madalenapmelo-kp** [comment]
Hi @EaZyStudiio,

Thanks for reporting these issues! The toolbar going into shell is a known behavior that we are already looking into, and the zooming with touch is a feature that has already been planned into our backlog though it hasn't been prioritized yet.

I was unable to reproduce the other behaviors you described, could you let me know if you experience these issues when working with other browsers as well? Could you also attach a screen recording of the steps leading up to the horizontal flipping issue?

**Comment by EaZyStudiio** [comment]
ohh definitely I'll try it with 4 different browsers "ALL chromium Based though" and get back to you with the video and update on if this issues still persist "Edge have truly been buggy lately should have tried this already 😅"

**Comment by EaZyStudiio** [comment]
First of All this glitches fix them self after a reload But I figured if I did just random things/work for like 1-2Mins  then try doing this I was able to reproduce this issues consistently On 5 chromium browsers:
- Edge
-Arc Windows
-OperaMini
-Whale Browser
-Vivaldi
All Are on their latest versions "I think but edge definitely"


5. Rendering issues...  I was just showing my parameters on the right and on the canvas is the actual issue 

https://github.com/penpot/penpot/assets/55167211/33cc89cd-35cc-4728-a86f-c7af37e3a8e1

4. Shift + Drag
    - Should work in move node mode 
    - Pressing shift and the selecting and draging an object does not work I have to do it in reverse

https://github.com/penpot/penpot/assets/55167211/2a6de7ec-0484-4ca9-957d-7329d2c777e4

3. When I create a new bord with nothing selected on a completely empty area it takes a previous group and auto child it

https://github.com/penpot/penpot/assets/55167211/08d17a54-eba3-4fd4-b56a-51e83ed56c19

2. ALT+click dragging Should resize an object on opposite ends 

https://github.com/penpot/penpot/assets/55167211/1c85d18d-447e-4219-884c-5fae2ad78265

1. The Duplication glitch (Shift+H) And a Temporary selection glich where it'll not regisiter/just do radom selection when am CTRL+Clicking to select another thingy it comes back after like 3 secs (worse in componet mode)

https://github.com/penpot/penpot/assets/55167211/62a3096d-0abe-4b29-8683-2e6295d8b134

**Comment by EaZyStudiio** [comment]
I was not able to reproduce : Move tool: Selection selecting objects Must be from an offset

it seems to be fixed or I think I did smt before that am forgetting

**Comment by madalenapmelo-kp** [comment]
Hi @EaZyStudiio,

Thank you for testing on other browsers! I haven't been able to reproduce these issues so it does seem to be browser related - for the time being, Chrome is the faster and most efficient browser when working with Penpot. That being said, we are working on the Penpot performance overall and we expect to publish improvements in the next releases.

In the meantime, we have just released the fix for the toolbar going into shell issue!
