### ISSUE TITLE
bug: Looks like you need to wait a bit and retry; we are performing small maintenance of our servers

### ISSUE THREAD

**Issue by TheDevelolper** [uxbox/uxbox#4707]
### Steps To Reproduce

As per instructions here: https://help.penpot.app/technical-guide/getting-started/#start-penpot

``` powershell
$ curl -o docker-compose.yaml https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml

$ docker compose -p penpot -f docker-compose.yaml up -d
```

Wait for everyt

### Expected behavior

Penpot should run when I go to https://localhost:9001

### Actual behavior

I see a message saying: 

Looks like you need to wait a bit and retry; we are performing small maintenance of our servers

### Screenshots or video

backend appears to be running:
![image](https://github.com/penpot/penpot/assets/4026553/d47ed934-0dc2-45c9-a4bd-ac42442b9a79)

Browser shows this:
![image](https://github.com/penpot/penpot/assets/4026553/98a3f593-55d6-46d6-89aa-57cc1701b042)

### Desktop (please complete the following information)

- OS Windows 11

### Additional context

I suspect that this might be due to an https redirect and it's serving on http?? Not sure.. How can I make it serve on https?

**Comment by smileBeda** [comment]
Yeah, same here. Installed it once, was "functioning" in the sense that it loaded the front end but said `Something wrong has happened.`  when trying to log in.
_Scratched the entire server, set up the identical infrastructure, re-installed with exact same steps following the exact same doc_ and now `Looks like you need to wait a bit and retry; we are performing small maintenance of our servers.`. And I tried that 5 times already.

**You can try to load it in another browser where you never loaded it before and it _might_ work.**
Not that it _will work_ because the next issues will happen then:
user created with the console won't log in: `Something wrong has happened.` 
However that is unrelated to this ticket... Just saying: perhaps the documentation requires _slight_ improvements, because clearly it is not how it should be installed, since it does basically not work after install, unless one goes through several more steps than what is outlined at https://help.penpot.app/technical-guide/getting-started/#install-with-docker

**Comment by superalex** [comment]
Hello @smileBeda and @TheDevelolper it would be helpful if you attach screenshots of the network request to see exactly what's happening. You can also launch docker with.

Usually that gateway problem means backend didn't boot correctly. If you execute ```docker logs --follow penpot-penpot-backend-1``` you should see something like this when backend is correctly executing:
![1](https://github.com/user-attachments/assets/c465644d-3ec4-4466-a149-3f5b77a2da0a)

**Comment by larmaysee** [comment]
Same Issue in 

Backend-1 service could not start 

`        clojure.lang.AFn.applyToHelper(AFn.java:154)
penpot-backend-1    |         clojure.lang.AFn.applyTo(AFn.java:144)
penpot-backend-1    |         clojure.lang.Var.alterRoot(Var.java:310)
penpot-backend-1    |         clojure.core$alter_var_root.invokeStatic(core.clj:5563)
penpot-backend-1    |         clojure.core$alter_var_root.doInvoke(core.clj:5558)
penpot-backend-1    |         clojure.lang.RestFn.invoke(RestFn.java:428)
penpot-backend-1    |         app.main$start.invokeStatic(main.clj:545)
penpot-backend-1    |         app.main$start.invoke(main.clj:541)
penpot-backend-1    |         app.main$_main.invokeStatic(main.clj:611)
penpot-backend-1    |         app.main$_main.doInvoke(main.clj:603)
penpot-backend-1    |         clojure.lang.RestFn.invoke(RestFn.java:400)
penpot-backend-1    |         clojure.lang.AFn.applyToHelper(AFn.java:152)
penpot-backend-1    |         clojure.lang.RestFn.applyTo(RestFn.java:135)
penpot-backend-1    |         clojure.lang.Var.applyTo(Var.java:707)
penpot-backend-1    |         clojure.core$apply.invokeStatic(core.clj:667)
penpot-backend-1    |         clojure.main$main_opt.invokeStatic(main.clj:515)
penpot-backend-1    |         clojure.main$main_opt.invoke(main.clj:511)
penpot-backend-1    |         clojure.main$main.invokeStatic(main.clj:665)
penpot-backend-1    |         clojure.main$main.doInvoke(main.clj:617)
penpot-backend-1    |         clojure.lang.RestFn.applyTo(RestFn.java:140)
penpot-backend-1    |         clojure.lang.Var.applyTo(Var.java:707)
penpot-backend-1    |         clojure.main.main(main.java:40)
penpot-backend-1    |     dt: {:reason :integrant.core/build-failed-spec,
penpot-backend-1    |          :system
penpot-backend-1    |          {:app.auth.oidc.providers/github nil,
penpot-backend-1    |           :app.db/pool #object[com.zaxxer.hikari.HikariDataSource 0x417018dc "HikariDataSource (main)"],
penpot-backend-1    |           :app.auth.oidc.providers/gitlab nil,
penpot-backend-1    |           :app.http.client/client
penpot-backend-1    |           #object[jdk.internal.net.http.HttpClientFacade 0x58253d40 "jdk.internal.net.http.HttpClientImpl@2399b9c5(1)"],
penpot-backend-1    |           :app.email/blacklist nil,
penpot-backend-1    |           :app.auth.oidc.providers/generic nil,
penpot-backend-1    |           :app.email/whitelist nil,
penpot-backend-1    |           :app.migrations/migrations nil,
penpot-backend-1    |           ...},
penpot-backend-1    |          :key :app.setup/props,
penpot-backend-1    |          :value
penpot-backend-1    |          {:app.db/pool #object[com.zaxxer.hikari.HikariDataSource 0x417018dc "HikariDataSource (main)"],
penpot-backend-1    |           :app.main/migrations nil}}
penpot-backend-1    |
penpot-backend-1    |  →  java.lang.AssertionError: Assert failed: expected valid key string (setup.clj:78)
penpot-backend-1    |     at: app.setup$eval42321$fn__42322.invoke(setup.clj:78)
penpot-backend-1    |         clojure.lang.MultiFn.invoke(MultiFn.java:234)
penpot-backend-1    |         integrant.core$wrapped_assert_key.invokeStatic(core.cljc:548)
penpot-backend-1    |         integrant.core$wrapped_assert_key.invoke(core.cljc:547)
penpot-backend-1    |         integrant.core$build_key.invokeStatic(core.cljc:425)
penpot-backend-1    |         integrant.core$build_key.invoke(core.cljc:423)
penpot-backend-1    |         clojure.core$partial$fn__5931.invoke(core.clj:2656)
penpot-backend-1    |         clojure.core.protocols$fn__8275.invokeStatic(protocols.clj:167)
penpot-backend-1    |         clojure.core.protocols/fn(protocols.clj:123)
penpot-backend-1    |         clojure.core.protocols$fn__8229$G__8224__8238.invoke(protocols.clj:19)
penpot-backend-1    |         clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
penpot-backend-1    |         clojure.core.protocols$fn__8262.invokeStatic(protocols.clj:74)
penpot-backend-1    |         clojure.core.protocols/fn(protocols.clj:74)
penpot-backend-1    |         clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
penpot-backend-1    |         clojure.core$reduce.invokeStatic(core.clj:6965)
penpot-backend-1    |         clojure.core$reduce.invoke(core.clj:6947)
penpot-backend-1    |         integrant.core$build.invokeStatic(core.cljc:453)
penpot-backend-1    |         integrant.core$build.invoke(core.cljc:430)
penpot-backend-1    |         integrant.core$init.invokeStatic(core.cljc:675)
penpot-backend-1    |         integrant.core$init.invoke(core.cljc:667)
penpot-backend-1    |         integrant.core$init.invokeStatic(core.cljc:672)
penpot-backend-1    |         integrant.core$init.invoke(core.cljc:667)
penpot-backend-1    |         app.main$start$fn__48565.invoke(main.clj:551)
penpot-backend-1    |         clojure.lang.AFn.applyToHelper(AFn.java:154)
penpot-backend-1    |         clojure.lang.AFn.applyTo(AFn.java:144)
penpot-backend-1    |         clojure.lang.Var.alterRoot(Var.java:310)
penpot-backend-1    |         clojure.core$alter_var_root.invokeStatic(core.clj:5563)
penpot-backend-1    |         clojure.core$alter_var_root.doInvoke(core.clj:5558)
penpot-backend-1    |         clojure.lang.RestFn.invoke(RestFn.java:428)
penpot-backend-1    |         app.main$start.invokeStatic(main.clj:545)
penpot-backend-1    |         app.main$start.invoke(main.clj:541)
penpot-backend-1    |         app.main$_main.invokeStatic(main.clj:611)
penpot-backend-1    |         app.main$_main.doInvoke(main.clj:603)
penpot-backend-1    |         clojure.lang.RestFn.invoke(RestFn.java:400)
penpot-backend-1    |         clojure.lang.AFn.applyToHelper(AFn.java:152)
penpot-backend-1    |         clojure.lang.RestFn.applyTo(RestFn.java:135)
penpot-backend-1    |         clojure.lang.Var.applyTo(Var.java:707)
penpot-backend-1    |         clojure.core$apply.invokeStatic(core.clj:667)
penpot-backend-1    |         clojure.main$main_opt.invokeStatic(main.clj:515)
penpot-backend-1    |         clojure.main$main_opt.invoke(main.clj:511)
penpot-backend-1    |         clojure.main$main.invokeStatic(main.clj:665)
penpot-backend-1    |         clojure.main$main.doInvoke(main.clj:617)
penpot-backend-1    |         clojure.lang.RestFn.applyTo(RestFn.java:140)
penpot-backend-1    |         clojure.lang.Var.applyTo(Var.java:707)
penpot-backend-1    |         clojure.main.main(main.java:40)
penpot-backend-1    |
penpot-backend-1 exited with code 255`

**Comment by DonyeaF** [comment]
To resolve the Assertion failed on key :app.setup/props error in the Penpot backend, open the sample Docker Compose file from the [Penpot repository](https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml) and locate the penpot-backend service definition. Within the environment section of penpot-backend, uncomment the line PENPOT_SECRET_KEY: my-insecure-key. After saving the changes to your docker-compose.yaml file, rebuild and restart your Docker containers by running the command docker-compose up --build.

**Comment by iambudi** [comment]
> Within the environment section of penpot-backend, uncomment the line PENPOT_SECRET_KEY: my-insecure-key. After saving the changes to your docker-compose.yaml file, rebuild and restart your Docker containers by running the command docker-compose up --build.

Does not work

I have to delete and recreate the container twice to make sure thing works. Thank you.
