### ISSUE TITLE
bug: no frontend after updating in Docker

### ISSUE THREAD

**Issue by nickvk** [uxbox/uxbox#4708]
### Steps To Reproduce

1. doing a docker-compose pull with the "frontend", "backend" and "exporter" having tag "latest".
2. a restart of the containers with docker-compose up -d.

### Expected behavior

Getting a login page, and after that the dashboard with all projects on it. Which can be opened.

### Actual behavior

A white page with an error in the console.

### Screenshots or video

![Schermafbeelding 2024-06-09 232025](https://github.com/penpot/penpot/assets/6170449/99f580d2-a404-48d6-8cfe-a19c15570f35)

### Desktop (please complete the following information)

- Chrome
- Windows 11

### Smartphone (please complete the following information)

- Chrome
- Android

### Environment (please complete the following information)

- OS version: 22.04
- Docker version: 26.1.4
- Docker-compose version: 1.29.2
[docker compsoe file Penpot.txt](https://github.com/user-attachments/files/15754256/docker.compsoe.file.Penpot.txt)

### Frontend Stack Trace

```console
Uncaught SyntaxError: Invalid or unexpected token
Uncaught ReferenceError: shadow$provide is not defined
    at main.5eee1cdbf.js:1:13
    at main.5eee1cdbf.js:55:31653
```

### Backend Stack Trace

```console
There is none
```

### Additional context

Before updating it all worked perfectly.

**Comment by Dennis4720** [comment]
I have this issue too.

**Comment by nickvk** [comment]
All of a sudden, without doing anything or reinstalling anything, it works again on mobile! On desktop I still get the same error. But it kinda works now, it's better than nothing. If the problem can be fixed for good, that will be better.

**Comment by superalex** [comment]
@nickvk if that works without doing anything...could it be a cache problem?

We released new docker  versions some days ago, did you update to the last ones?.

Feel free to reopen the issue if the problem still happens
