### ISSUE TITLE
translation: English to French 

### ISSUE THREAD

**Issue by UnrealSimulation** [uxbox/uxbox#4725]
### Is your feature request related to a problem? Please describe.

Hello Penpot team.
I would like to help to translate the current and futur text in french for penpot. Could you add me in the Weblate team please? Thank you for your time and your help.
Language: French
Translation type: new translation
Weblate user: @unrealvisionyt

### Describe the solution you'd like.

Hello Penpot team.
I would like to help to translate the current and futur text in french for penpot. Could you add me in the Weblate team please? Thank you for your time and your help.
Language: French
Translation type: new translation
Weblate user: @unrealvisionyt

**Comment by madalenapmelo-kp** [comment]
Hi @UnrealSimulation,

I've added you to the translation project, now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/fr/) and start translating. 

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution! :slightly_smiling_face:

**Comment by UnrealSimulation** [comment]
Hi @madalenapmelo-kp ,
It looks like I can't save any translation. Weblate says I don't have the permission to save any change. Can you help me please? Thanks a lot! 😄
![image](https://github.com/penpot/penpot/assets/50368770/ecb2e050-20f2-437a-8ca1-e84759af2b20)

**Comment by madalenapmelo-kp** [comment]
Hi @UnrealSimulation,

Could you check now?

**Comment by UnrealSimulation** [comment]
Hello again @madalenapmelo-kp ,
Thank you for your help. I just refreshed my page but nothing new. I still have the same message as the screenshot above.

**Comment by madalenapmelo-kp** [comment]
It seems that you have not yet accepted the invitation to the Penpot translation project, could you accept it and retry?

**Comment by UnrealSimulation** [comment]
Oh I didn't know I received an invitation in my mails. It's weird we don't have any notification in the Weblate's interface.
Anyway, I accepted it: everything is fine now. Thanks a lot! 😃

**Comment by madalenapmelo-kp** [comment]
Thanks for confirming :smile:

**Comment by UnrealSimulation** [comment]
No problem, @madalenapmelo-kp. :)
One last thing: do you know why the glossary in Weblate is empty? Can we have the permission to add words in it?
It could help to have constancy with terminology in Weblate for translation.
