### ISSUE TITLE
bug: Removing Underline and Strikethrough Affects the Previous Text Object

### ISSUE THREAD

**Issue by superev12** [uxbox/uxbox#4743]
### Steps To Reproduce

- Create a new document with two text boxes (A and B).
- Underline the text in A
- Underline the text in B
- Remove the underline in A

### Expected behavior

A is no longer underlined, B is still underlined.

### Actual behavior

A is still underlined, B is not underlined.

### Screenshots or video

[Screencast from 2024-06-13 16-35-09.webm](https://github.com/penpot/penpot/assets/9501448/2aba15cd-6240-433e-8c56-889cacc7863c)

### Desktop (please complete the following information)

Linux 6.1.69, NixOS 23.11, Gnome 45, X11
Google Chrome Version 120.0.6099.109

### Smartphone (please complete the following information)

n/a

### Environment (please complete the following information)

https://design.penpot.app

### Frontend Stack Trace

```console
n/a
```

### Backend Stack Trace

```console
n/a
```

**Comment by madalenapmelo-kp** [comment]
Hi @superev12,

Thanks for reporting this! I've opened an issue on Taiga so that we can look into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/8103

**Comment by madalenapmelo-kp** [comment]
Hi @superev12,

This issue has been fixed! Could you please confirm and close this?

**Comment by madalenapmelo-kp** [comment]
This issue is now fixed!
