### ISSUE TITLE
Feature: Variables and text inputs in prototypes

### ISSUE THREAD

**Issue by JorenC** [uxbox/uxbox#4748]
### Is your feature request related to a problem? Please describe.

When doing UX prototyping, there is a tendency to focus on the visual design, e.g. Figma prototypes or clickable prototypes. While these are good, often the critical factor is functionality and interactions that you can't mimic, e.g. text inputs or database scrolls. 

In addition, personalisation is not possible. One of the advantages of UXPin (and e.g. Axure....) is that you can use, save and restore variables. For example, adding a text input on a first page allows you to enter names, ages etc - and during the prototype you can call them back and show them, e.g. in my environments, creating a much more realistic response.

### Describe the solution you'd like.

I'd like to have real touch inputs - opening a keyboard. In addition, I'd like to be able to store variables and use them in interactions, e.g. fill text fields or text inputs. 

### Describe alternatives you've considered.

UXPin has this feature, and it can work great, but is paid and locked behind their security measures, rather than the open source alternative for PenPot.

**Comment by madalenapmelo-kp** [comment]
Hi @JorenC,

Thank you for the suggestion! We have added it to our backlog on Taiga to be considered in the future, you can find the details at https://tree.taiga.io/project/penpot/issue/8115

**Comment by jdittrich** [comment]
Probably best split into two issues: 
1) Setting, reading and displaying variables (or the like), might be #1994
2) ~~Allow text input in prototypes~~  Issue is: #1098

**Comment by jdittrich** [comment]
@JorenC  if the two linked issues (#1994, #1098) are what you imagine, you could close this issue again. If they diverge in details, close this issue and write a comment. If they are different, keep this open.

**Comment by madalenapmelo-kp** [comment]
Hi @JorenC,

I'm closing this issue since, as @jdittrich mentioned, these suggestions are already being tracked elsewhere! Feel free to reopen if you feel that they are different :slightly_smiling_face:
