### ISSUE TITLE
bug: Rotated frames get cut when you re import the file in zip format

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4753]
### Steps To Reproduce

1. Create one/two or more frames with some contents inside
2. Rotate the frames
3. Export and Import
4. Move around the file clicking on the frames

### Expected behavior

It should not do anything strange. Just like the original file

### Actual behavior

Frames lose some of the shape (it actually looks like if the frame is not really rotated)

### Screenshots or video

https://www.loom.com/share/ccb0c3a6366b49e2a6d31b005f007494?sid=fc685309-15e7-410d-b314-471932222256

**Comment by madalenapmelo-kp** [comment]
Hi @jordisala1991,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8106

**Comment by jordisala1991** [comment]
This one is already fixed, closing.

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be release soon!
