### ISSUE TITLE
bug: Rotated text loses rotation upon importing (from Figma)

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4755]
### Steps To Reproduce

1. Draw a frame (it is important, otherwise the bug cannot be reproduced)
2. Write a text inside
3. Rotate the text
4. Export using the plugin (using dev version, main branch)
5. Import on Penpot
6. Open the file and see how it loses the rotation when you open it.

### Expected behavior

Text not losing the rotation (actually not only loses the rotation but it gets a bit deformed)

### Actual behavior

Text loses the rotation and gets deformed.

### Screenshots or video

https://www.loom.com/share/198170a13e8d4fce8ccab139b53ed129

I can also pass my export from the video:
[Untitled.zip](https://github.com/user-attachments/files/15872320/Untitled.zip)

**Comment by madalenapmelo-kp** [comment]
Hi @jordisala1991,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8108

**Comment by jordisala1991** [comment]
This one is already fixed, closing.
