### ISSUE TITLE
Typo Desing -> Design

### ISSUE THREAD

**Issue by yarons** [uxbox/uxbox#4766]
https://github.com/penpot/penpot/blob/cba62c0172c3d4d8a3429a08f553538c69aaeb5e/frontend/translations/en.po#L2561

Spotted while translating, already reported in the comments of the string in Weblate.

**Comment by jdittrich** [comment]
easyfix I assume for people who want to get familiar with contributing?

**Comment by madalenapmelo-kp** [comment]
Hi @yarons,

Thanks for reporting this! This has already been fixed!
