### ISSUE TITLE
bug: Color library loses association with shapes when exporting/importing the document

### ISSUE THREAD

**Issue by jordisala1991** [uxbox/uxbox#4770]
### Steps To Reproduce

1. Create a new document
2. Add any shape on it
3. Create a color on the color library
4. Asociate it with the shape in the fill section\
5. Export and Import (zip format)
6. The color is there but the shape is no longer associated with it

### Expected behavior

The shape is still associated with the color library

### Actual behavior

The shapes loses association (even if it maintains the color)

### Screenshots or video

https://www.loom.com/share/221880ce065240f08904c3fdec37b3fd

**Comment by madalenapmelo-kp** [comment]
Hi @jordisala1991,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8132
