### ISSUE TITLE
bug: Image Color Library is not persisted when exporting/importing in .zip

### ISSUE THREAD

**Issue by Cenadros** [uxbox/uxbox#4771]
### Steps To Reproduce

1. Create a new document in penpot
2. Create a new color library of type image
3. Export the file
4. Import the file

### Expected behavior

The library is there and works as expected.

### Actual behavior

The image is lost in the process

### Screenshots or video

https://github.com/penpot/penpot/assets/5689481/5ae3366a-9396-4837-af3e-2b652864b4a7

**Comment by madalenapmelo-kp** [comment]
Hi @Cenadros,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8131
