### ISSUE TITLE
feature: Persistent Dark Mode/Light Mode toggle for PenPot interface

### ISSUE THREAD

**Issue by MMachado05** [uxbox/uxbox#4791]
### Is your feature request related to a problem? Please describe.

Not quite a problem, per se, but changing the theme of the PenPot webapp requires going into your "Account Settings," which I always felt was a settings section meant for things like email preferences, billing information, etc, rather than website functionalities.

### Describe the solution you'd like.

Like on other websites[[1]](https://krita.org/en/)[[2]](https://whitep4nth3r.com/), a theme toggle that persists across website sections (drafts view, project view) should be implemented to make toggling between light and dark themes as seamless and intuitive as possible!

### Describe alternatives you've considered.

Perhaps a different settings option can be added. For example, instead of having everything under "account settings," there could be a simple "settings" section, and a separate "account preferences" section.

### Additional context

N/A

**Comment by EaZyStudiio** [comment]
Alt+M or Option+M

**Comment by madalenapmelo-kp** [comment]
Hi @MMachado05,

Thanks for the suggestion! As @EaZyStudiio mentioned, you can switch color themes using Alt+M on Linux and Windows, or Option+M on macOS :slightly_smiling_face:

**Comment by MMachado05** [comment]
I didn't know this! However, I do feel like a visual cue might be helpful, since new users might not come to this website knowing what the keyboard shortcut is.

**Comment by EaZyStudiio** [comment]
ohh but it is. here you go on the right side they pointed to the shortcut. hope that helps

![image](https://github.com/penpot/penpot/assets/55167211/b13ff04a-5fc3-44f0-b522-7d54791a95c8)

also you can do SHIFT+? to bring up shortcut help menu and do a search. have a fun one 😁
