### ISSUE TITLE
access to weblate

### ISSUE THREAD

**Issue by vanja-san** [uxbox/uxbox#4818]
I see the need to help with translation.
- **lang**: Russian
- **type**: new translation & change (correct) an existing
- **user**: The_BadUser (``@vanja-san``)

**Comment by madalenapmelo-kp** [comment]
Hi @vanja-san,

I've added you to the Weblate project, all you need to do now is accept the invitation and access here: https://hosted.weblate.org/projects/penpot/-/ru/

Thank you for your contribution :slightly_smiling_face:
