### ISSUE TITLE
request: Need access to weblate translation hub

### ISSUE THREAD

**Issue by KungfuSnail** [uxbox/uxbox#4820]
### Steps To Reproduce

See Additional context

### Expected behavior

See Additional context

### Actual behavior

See Additional context

### Additional context

I followed https://help.penpot.app/contributing-guide/translations/ to here.

I would like to be able to contribute to penpot. 
I need some permission to be able to contribute to weblate
Target language: Persian
User: @NimNim

**Comment by KungfuSnail** [comment]
It isn't a "bug" but I wasn't sure if I was supposed to choose bug or feature request.

**Comment by madalenapmelo-kp** [comment]
Hi @KungfuSnail,

I have invited you to the Weblate project, all you need to do now is accept the invite and access here to start translating: https://hosted.weblate.org/projects/penpot/-/fa/

Thank you for your contribution :slightly_smiling_face:
