### ISSUE TITLE
bug: Again and again showing this message internal error, Please help how to solve this problem

### ISSUE THREAD

**Issue by uplAmit** [uxbox/uxbox#4846]
### Steps To Reproduce

![Screenshot_2](https://github.com/penpot/penpot/assets/60697918/ece0e68c-1bf9-469a-b523-6629505a6db2)

### Expected behavior

It is very problematic for a designer to every time again and again click on Refresh button and create the design.
The web app should be optimized for designers so that it can help us create designs easily.

### Actual behavior

It is very problematic for a designer to every time again and again click on refresh and create the design 

### Screenshots or video

![Screenshot_2](https://github.com/penpot/penpot/assets/60697918/634e6190-4e1a-4fec-9e1c-5f2e3e6cc9d8)

**Comment by madalenapmelo-kp** [comment]
Hi @uplAmit,

Thanks for reporting this! Could you let me know the specific steps that lead up to this error? If you could share a screen recording, that would be really helpful!
