### ISSUE TITLE
bug: Some Time pen tool is hide from my editor and I can't access the editor properly  

### ISSUE THREAD

**Issue by uplAmit** [uxbox/uxbox#4847]
### Steps To Reproduce

working with pen, after clicking on pen tool tool bar is not showing

### Expected behavior

The toolbar should be shown at the top at all times.

### Actual behavior

Some Time pen tool is hidden from my editor and I can't access the editor properly. I can't see the toolbar & I can't unhide clicking on the bar also.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/60697918/14f907d0-3c56-4e07-85f5-bae080adf1d7)

### Desktop (please complete the following information)

OS-
2024-06 Cumulative Update Preview for Windows 10 Version 22H2 for x64-based Systems (KB5039299)

Chrome is up to date-
Version 126.0.6478.127 (Official Build) (64-bit)

### Environment (please complete the following information)

2024-06 Cumulative Update Preview for Windows 10 Version 22H2 for x64-based Systems (KB5039299)

**Comment by madalenapmelo-kp** [comment]
Hi @uplAmit,

Thank you for reporting this! We have already fixed this issue and we expect to release the fix very soon!
