### ISSUE TITLE
bug: Custom LDAP Query gets ignored by backend

### ISSUE THREAD

**Issue by ahorn42** [uxbox/uxbox#4848]
### Steps To Reproduce

Set up penpot via the docker-compose file.
Configure the use of LDAP with a custom `PENPOT_LDAP_USER_QUERY`
Start up docker compose
Have a look at the backend start-up log with `docker logs penpot-penpot-backend-1 -f`
Try to login

### Expected behavior

If I configure a custom ldap query in `PENPOT_LDAP_USER_QUERY` I expect this query to be used by penpot and that I can login to the system.

### Actual behavior

The penpot backend uses the default ldap query that is defined in the source code and ignores the settings provided by the docker-compose.yaml.
If you run a `printenv` command in the running docker backend container (`docker exec -it penpot-penpot-backend-1 printenv`) you can even see, that the custom query was successfully passed as environment variable.
But, if you have a look at the logs of the backend (`docker logs penpot-penpot-backend-1 -f`) you will notice it is not using the custom query, but the default query. Therefor the login does not work.

### Screenshots or video

Log output of the backend regarding LDAP:

```
[2024-07-03 15:17:46.645] I app.auth.ldap - hint="provider initialized", provider="ldap", host="example.com", port=389, tls?=false, ssl?=false, bind-dn="CN=example,OU=example,OU=example,DC=example,DC=com", base-dn="DC=example,DC=com", query="(|(uid=:username)(mail=:username))" 
```

whereas the environment variable contains the following query:
```
PENPUT_LDAP_USER_QUERY=(&(userPrincipalName=:username)(memberOf=CN=PENPOT_Users,OU=example,OU=example,OU=example,DC=example,DC=com))
```

### Desktop (please complete the following information)

not relevant

### Smartphone (please complete the following information)

not relevant

### Environment (please complete the following information)

Host OS: Debian 11
docker --version: Docker version 26.1.3, build b72abbb 
penpotapp/backend container: https://hub.docker.com/layers/penpotapp/backend/latest/images/sha256-1fa2f0b0ba0c342a700a0ccde182bc10377d1e150064eaf9f7fb9622e9738698?context=explore

### Additional context

The LDAP Attribute `userPrincipalName` is an email address but a different compared to the one from the `mail` attribute. I can login with the address form the `mail` attribute, but we would prefer to use the address stored at `userPrincipalName`. And also the variable is supposed to be used and not to be ignored ;)

Thanks a lot for your nice tool anyways :)

**Comment by superalex** [comment]
Hi @ahorn42 ,

Your environment variable says PENP**U**T_LDAP_USER_QUERY and it should be PENP**O**T_LDAP_USER_QUERY (be careful with that u)

My log output with the same value you used:

![splash2](https://github.com/user-attachments/assets/bd0d9474-610c-4ebb-866d-88a44d267c0d)

Did you try setting the PENPOT_LDAP_ATTRS_EMAIL variable to userPrincipalName to login with that address?

**Comment by ahorn42** [comment]
ouch - sorry for bothering you with a typo! But also thanks for pointing it out.

**Comment by superalex** [comment]
No problem!, you are welcome @ahorn42 ! :)
