### ISSUE TITLE
request: Need access for translation

### ISSUE THREAD

**Issue by KungfuSnail** [uxbox/uxbox#4854]
### Is your feature request related to a problem? Please describe.

Additional context

### Describe the solution you'd like.

Additional context

### Describe alternatives you've considered.

Additional context

### Additional context

Sorry but I didn't accept the invitation in time before it expired, can I have another one? 
Related: https://github.com/penpot/penpot/issues/4820

I followed https://help.penpot.app/contributing-guide/translations/ to here.

I would like to be able to contribute to penpot.
I need some permission to be able to contribute to weblate
Target language: Persian
User: @NIMNIM

**Comment by madalenapmelo-kp** [comment]
Hi @KungfuSnail,

I've resent the invitation!
