### ISSUE TITLE
bug: Toggling off button "show in view mode" also removes all interactions

### ISSUE THREAD

**Issue by eli-stergiouli** [uxbox/uxbox#4868]
### Steps To Reproduce

1. Create 2 boards with one button on the first
2. Create an interaction to navigate from that button to the second board
3. In the view mode you will have 3 images, the first board, next the button on its own, and then the second board if you navigate with the arrows.
4. To remove it from the view so you only see the 2 boards, select the button and toggle off "show in view mode"
5. All interactions automatically removed.

### Expected behavior

The only thing that should happen is the button not show up in the view mode. Why should the interactions also be removed? This morning this behavior wasn't happening.

### Actual behavior

Toggling off button "show in view mode" also removes all interactions

### Desktop (please complete the following information)

Windows 11, Firefox 128.0 (64-bit)

**Comment by jota0222** [comment]
This is also happening to me recently, I want to keep the navigation of my prototype without showing each interactive element as a page in the view, I mean, for the following example, the view mode should always show 2 pages and allow me to interact, however, it's not possible right now. Here is a video:

https://github.com/user-attachments/assets/a483a019-8b45-4542-b1ed-17ad407c7992

**Operating System:**
Linux Debian 10

**Browser:**
Google Chrome Version 126.0.6478.126 (Official Build) (64-bit)

**Comment by madalenapmelo-kp** [comment]
Hi @astroneli,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8416

In the meantime, as a workaround, you can create buttons using rectangles instead of boards, to prevent the element showing on its own on the view mode.

**Comment by eli-stergiouli** [comment]
> In the meantime, as a workaround, you can create buttons using rectangles instead of boards, to prevent the element showing on its own on the view mode.

I already use rectangles for buttons and I can still see them in the view mode.

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!
