### ISSUE TITLE
bug: docker hub images are not in sync with released version

### ISSUE THREAD

**Issue by santimar** [uxbox/uxbox#4869]
### Steps To Reproduce

I expected that every version found in [Release page](https://github.com/penpot/penpot/releases) would have a corresponding image on [docker hub](https://hub.docker.com/u/penpotapp), but this is not the case.

For example, latest releases  on github are:
- 2.1.0
- 2.0.0
- 1.19.2

On docker hub, (for frontend, backend and exporter) we have:
- 2.0.3
- 2.0.1
- 2.0.0
- 1.19.3
- 1.19.2

### Expected behavior

The release pipeline should produce and upload a docker image with the same tag

### Actual behavior

The docker image is missing

**Comment by madalenapmelo-kp** [comment]
Hi @santimar,

I checked docker hub for frontend, backend and exporter and every version in the [Release page](https://github.com/penpot/penpot/releases) now has a corresponding image on docker hub!
