### ISSUE TITLE
bug: smtp using another port even if env var is set

### ISSUE THREAD

**Issue by marioromera** [uxbox/uxbox#4872]
### Steps To Reproduce

Self hosted with docker, remove disable-email-verification, try to create a new user...

### Expected behavior

user would received email account

### Actual behavior

Error:
penpot-backend-1    | [2024-07-11 09:55:00.819] E app.worker.runner - hint="unhandled exception on task"
penpot-backend-1    | SUMMARY:
penpot-backend-1    |  →  com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp-legacy.office365.com, 465; timeout -1 (SMTPTransport.java:2210)
penpot-backend-1    |  →  java.net.ConnectException: Connection timed out (Net.java:-2)

### Environment (please complete the following information)

      - PENPOT_SMTP_DEFAULT_FROM=Penpot <no-reply@email.com>
      - PENPOT_SMTP_DEFAULT_REPLY_TO=Penpot <no-reply@email.com>
      - PENPOT_SMTP_HOST=smtp.office365.com
      - PENPOT_SMTP_PORT=587
      - PENPOT_SMTP_USERNAME=smtp.noreply@email.com
      - PENPOT_SMTP_PASSWORD=dummypass
      - PENPOT_SMTP_TLS=true
      - PENPOT_SMTP_SSL=true

### Backend Stack Trace

penpot-backend-1    | [2024-07-11 09:55:00.819] E app.worker.runner - hint="unhandled exception on task"
penpot-backend-1    | SUMMARY:
penpot-backend-1    |  →  com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp-legacy.office365.com, 465; timeout -1 (SMTPTransport.java:2210)
penpot-backend-1    |  →  java.net.ConnectException: Connection timed out (Net.java:-2)

**Comment by madalenapmelo-kp** [comment]
Hi @marioromera,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8471

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be release soon!
