### ISSUE TITLE
bug: Selfhosted, ERR_PROXY_CONNECTION_FAILED on export multiple

### ISSUE THREAD

**Issue by ALPOFF** [uxbox/uxbox#4875]
### Steps To Reproduce

1. Selfhosted by docker
2. Add some component on board
3. Try to export as e.g. PNG, PDF …

### Expected behavior

Successful export of component

### Actual behavior

After click on export button, I get an error screen with internal server error.

### Environment (please complete the following information)

OS: Linux

### Backend Stack Trace

```console
penpot-exporter container logs:

TRC [app.browser) hint="exec:handle:start", browser-id=2
INF [app.renderer.bitmap) uri=#lambdaisland/uri "http://penpot-frontend/render.html?file-
id=7df29002-655d-81b4-8004-696e5a320746&page-id=7df29002-655d-81b4-8004-
696e5a320746&object-id=715235a6-3f3e-805b-8004-a37ec017af2f&route=objects"
INF (app.browser) origin="factory", action="destroy", browser-id=2
ERR (app.handlers.export-shapes) hint="unexpected error on export multiple"
page.goto: net::ERR_PROXY_CONNECTION_FAILED at http://penpot-frontend/render.html?file-
id=7df29002-655d-81b4-8004-696e5a320746&page-id=7df29002-655d-81b4-8004-
696e5a320746&object-id=715235a6-3f3e-805b-8004-a37ec017af2f&route=objects
Call log:
- navigating to "http://penpot-frontend/render.html?file-id=7df29002-655d-81b4-8004-
696e5a320746&page-id=7df29002-655d-81b4-8004-696e5a320746&object-id=715235a6-3f3e-805b-
8004-a37ec017af2f&route=objects", waiting until "networkidle"
at app.browser.nav_BANG_.cljs$core$|Fn$_invokeSarity$3 (/opt/penpot/exporter/app.js:75480:18)
at app.browser.nav_BANG_.cljs$coreSiFn$_invokeSarity$2 (/opt/penpot/exporter/app.js:75474:32)
at/opt/penpot/exporter/app.js:78941:87
at Object.resolve (/opt/penpot/exporter/app.js:74488:107)
at Sjscomp$scope$84173391$24$processNextTick (/opt/penpot/exporter/app.js:73398:78)
at /opt/penpot/exporter/app.js:73502:30
ERR [app.handlers] hint="unexpected internal error"
page.goto: net::ERR_PROXY_CONNECTION_FAILED at http://penpot-frontend/render.html?file-
id=7df29002-655d-81b4-8004-696e5a320746&page-id=7df29002-655d-81b4-8004-
696e5a320746&object-id=715235a6-3f3e-805b-8004-a37ec017af2f&route=objects
Call log:
- navigating to "http://penpot-frontend/render.html?file-id=7df29002-655d-81b4-8004-
696e5a320746&page-id=7df29002-655d-81b4-8004-696e5a320746&object-id=715235a6-3f3e-805b-
8004-a37ec017af2f&route=objects", waiting until "networkidle"
at app.browser.nav_BANG_cljs$coreSIFnS_invokeSarity$3 (/opt/penpot/exporter/app.js:75480:18)
at app.browser.nav_BANG_cljs$coreSIFnS_invokeSarity$2 (/opt/penpot/exporter/app.js:75474:32)
at /opt/penpot/exporter/app.js:78941:87
at Object.resolve (/opt/penpot/exporter/app.js:74488:107)
at SjscompSscope$84173391524SprocessNextick (/opt/penpot/exporter/app.js:73398:78)
at /opt/penpot/exporter/app.js:73502:30
```

### Additional context

Before updating to version 2.0, export worked properly. 
In chrome console - POST query on /api/export not successful with 500 error.

**Comment by superalex** [comment]
Hi @ALPOFF 

It seems like some kind of connectivity issue between exporter and frontend. I've just tested a 2.1 installation using this docker-compose and export works ok -> https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml

Could you check if your docker-compose file has any significant difference with the base penpot one? 

What docker version of the images are you using?

**Comment by ALPOFF** [comment]
Hi, @superalex!
I found out why I had this error (and basically with any export).
My host system had the HTTP_PROXY and HTTPS_PROXY environment variables set, which were eventually passed to the container and accordingly affected the exporter service.

P.S. Maybe someone else will encounter this problem. Check the container itself via docker inspect command, and check "Env" section or check other settings related to "proxying".

P.P.S. I use version 2.6 and it also had this "oddity", I will try to update to the latest version to check if it is present there.
