### ISSUE TITLE
bug: ability to let users to authenticate with a private oidc provider only

### ISSUE THREAD

**Issue by vladimirdulov** [uxbox/uxbox#4882]
### Steps To Reproduce

Hello, 

We are packaged `penpot` app for `Cloudron` (https://cloudron.io).

Recently authentication seems to be changed in v2.1.0 and now we are facing with an issue that login via our Cloudron OIDC provider stopped to work until `enable-registration` flag is set.

The configuration we'd like to have working:

```
PENPOT_FLAGS="enable-login-with-oidc disable-registration disable-login-with-password disable-email-verification enable-smtp"
```

But it causes `Registration is currently disabled` error if OIDC user authenticates first time.

![Screenshot 2024-07-15 at 12 36 07](https://github.com/user-attachments/assets/9cbfd13f-0a8a-4dbf-a639-c99ae343ee78)

If we set `enable-registration` flag, authentication via OIDC starts to work but also `Create an account` link appears on the login form which doesn't have any sense in our case as we'd like users from Cloudron user directory to authenticate.

![Screenshot 2024-07-15 at 12 29 15](https://github.com/user-attachments/assets/6460f04b-d38f-44fc-a54a-568377f14624)

maybe you can implement `enable-registration-with-oidc` flag to automatically create OIDC users or create respective users automatically w/o additional flag?

### Expected behavior

The configuration we'd like to have working:

```
PENPOT_FLAGS="enable-login-with-oidc disable-registration disable-login-with-password disable-email-verification enable-smtp"
```

maybe you can implement `enable-registration-with-oidc` flag to automatically create OIDC users or create respective users automatically w/o additional flag?

### Actual behavior

But it causes `Registration is currently disabled` error if OIDC user authenticates first time.

![Screenshot 2024-07-15 at 12 36 07](https://github.com/user-attachments/assets/9cbfd13f-0a8a-4dbf-a639-c99ae343ee78)

If we set `enable-registration` flag, authentication via OIDC starts to work but also `Create an account` link appears on the login form which doesn't have any sense in our case as we'd like users from Cloudron user directory to authenticate.

![Screenshot 2024-07-15 at 12 29 15](https://github.com/user-attachments/assets/6460f04b-d38f-44fc-a54a-568377f14624)

### Desktop (please complete the following information)

any browser

### Environment (please complete the following information)

https://www.cloudron.io/store/app.penpot.cloudronapp.html

**Comment by thebaultyoann** [comment]
I'm not sure, but maybe you could put the flag ` disable-registration` on the frontend container, and ` enable-registration` on the back-end container ?

**Comment by vladimirdulov** [comment]
@thebaultyoann Thanks for a workaround.
I've tried to implement it and it really hides the registration link and makes OIDC auth working but I suspect there could be some security risks that somebody will still be able to register by submitting necessary data.

**Comment by thebaultyoann** [comment]
Check the API on the /api/doc endpoint of your penpot url. It exists a route to register people, so I guess yes, somebody can register anyway.

But is that really an issue ? 
They could register and create an account, but for that they would need to first know the api endpoints, and then try to add an account.
And even with that, someone that use this user would only have his personnal access to penpot and only through the API if you have the flag "disable-login-with-password"

The only issue could be that someone managed through API requests to put himself into your penpot's team and export all the data you have. I didn't took the time to check, but I don't think Penpot team such a security breach open.

**Comment by vladimirdulov** [comment]
It's not a problem to research endpoints, params, etc. in the code.

When somebody registers in penpot, an email confirmation arrives to confirm the email address specified, if the person follows by the link he gets an access to the dashboard.

**Comment by june128** [comment]
Reverting 81b52d7170245aec974f1a17c1bab936150819e8 seems to restore the behavior of OIDC working with `disable-registration` set. I assume this commit was made in response to #4283.
Tho reverting works as a hotfix, this obviously isn't ideal. A solution might be to allow for more fine-grained control over registrations. Maybe flags like this:

- `disable-local-registrations` for disabling local accounts registrations.
- `disable-oidc-registrations` for disabling OIDC account registrations.
- Maybe one for ldap as well? Unsure how that integrates as I don't use it.
- `disable-registrations` to disable all registrations

I believe these flags should support basically all registration use-cases.

**Comment by niwinz** [comment]
I will look on it ASAP, and we trigger a patch release when it is fixed.

**Comment by niwinz** [comment]
Added the `enable-oidc-registration` flag.

https://github.com/penpot/penpot/pull/4963

will be released on the next patch version.

**Comment by madalenapmelo-kp** [comment]
Hi @vladimirdulov,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8477

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be release soon!

**Comment by vladimirdulov** [comment]
I'm sorry but it doesn't seem to be fixed.

I've configured Penpot v2.1.2 with the following flags:
```
PENPOT_FLAGS="disable-registration enable-login-with-oidc enable-odic-registration disable-onboarding disable-login-with-password disable-email-verification enable-smtp"
```

I got the following login screen:
![Screenshot 2024-08-13 at 13 42 31](https://github.com/user-attachments/assets/41b2eead-3dcb-4725-be80-f7dcf260739e)

When I click "OpenId" button, it brings `Registration is currently disabled` error.
![Screenshot 2024-08-13 at 13 42 38](https://github.com/user-attachments/assets/0ec835d3-ee49-4a48-97b9-0f8864e317a4)

Could you please check if it's an issue with my configuration or there is still a bug.
