### ISSUE TITLE
bug: Prototypes don't work in view mode

### ISSUE THREAD

**Issue by ghost** [uxbox/uxbox#4887]
### Steps To Reproduce

I'm actually unsure how to reproduce this. I have a project I'm working on and once in a while all the prototypes I make will break. And by break, I mean in the view mode it will focus the wrong board. Even after selecting the right one, clicking on an item, nothing happens. There are no logs either.

### Expected behavior

After iteratively making updates to a project, prototypes should continue to work. Especially when unrelated boards are updated

### Actual behavior

The more changes are made, the more prototypes stop functioning.

### Screenshots or video

Here's a flow in the editor

![image](https://github.com/user-attachments/assets/590b2f65-16ca-4d5a-804c-b67f8b9e9260)

after clicking the play button on the flow, this is what I get

![image](https://github.com/user-attachments/assets/616f217c-3ba9-4840-9d91-df08d1c79cf0)

notice that the flow selector is empty

![image](https://github.com/user-attachments/assets/3d47a1a9-7294-4e95-a43b-9ea9d1b8a7bb)

Even after selecting a flow, it doesn't switch to another board.

### Desktop (please complete the following information)

- OS: NixOS 24.05
- Browser: Firefox 127

### Environment (please complete the following information)

https://design.penpot.app

### Additional context

[Here's the link to the existing prototype](https://design.penpot.app/#/view/352e9fc6-6a46-8154-8004-a78d24a66a21?page-id=352e9fc6-6a46-8154-8004-a78d24a66a22&section=interactions&index=0&share-id=3d05e112-61de-81a6-8004-aa65a34f452f). Dunno if it'll work or not. I duplicated the project and for some reason the duplicate works :shrug: 

Here's the "standard" export [Social butler desktop.zip](https://github.com/user-attachments/files/16254556/Social.butler.desktop.zip)

**Comment by madalenapmelo-kp** [comment]
Hi @LoveIsGrief,

Thank you for reporting this! I noticed that for all of these board the option "**Show in view mode**" was deactivated, could you try activating this option (see screenshot below for reference) and let me know if the problem persists?

![image](https://github.com/user-attachments/assets/6df24f16-8d19-4756-9eb9-23d544820ff1)

**Comment by ghost** [comment]
Thank you @madalenapmelo-kp that was indeed the issue. I'm not sure why the layers switched from that. Might've been an error on my part or Ctrl+D doesn't copy that attribute; I dunno. Now it's become second nature to select everything and hit the "Show in view mode" button before opening view mode.

A few improvement suggestions:

1. maybe all the layers connected to a flow should toggle on "show in view mode"
2. when view mode is requested to be opened and a flow is selected, if layers in the flow aren't visible in view mode, maybe there should be some feedback (visual or otherwise) that the flow might not work as expected. furthermore the elements in the flow without view mode on, could be toggled
3. a mode could be introduced that toggles visibility of items to be hidden in view mode
4. when in view mode, flows that have layers which are unavailable in view mode should have some visual indicator e.g orange color with a warning sign

**Comment by madalenapmelo-kp** [comment]
Hi @LoveIsGrief,

Thank you for confirming and for the suggestions! I've shared this internally so that we can look into improvements around the "Show in view mode" behavior :slightly_smiling_face: 

I'm closing this issue for now, but you can find the details on Taiga here: https://tree.taiga.io/project/penpot/issue/8414
