### ISSUE TITLE
feature: Rounded corners for custom paths (custom pen shapes and boolean operations)

### ISSUE THREAD

**Issue by Manueljlin** [uxbox/uxbox#4892]
### Is your feature request related to a problem? Please describe.

Designers can round the corners of square shapes and frames, but they can't round the corners of custom shapes, which is really useful when designing icons like the following: <br>
![image](https://github.com/user-attachments/assets/9852a798-5a2e-4773-b622-94685a7e62ff)

This example is composed of three shapes. As you can see in the figma layers panel, it's a mix of a pure pen shape (layer says rectangle, but it's flattened to a shape) and a couple of boolean operations. <br>
![image](https://github.com/user-attachments/assets/4d94ff5b-3c65-49c0-94b3-1a680a113ed1)
![image](https://github.com/user-attachments/assets/f0f79c8a-9377-4eea-b8fe-04b28472788d)

The green shape's corner radius isn't set by the underlying shapes, but applied on top of the boolean operation group. <br>
![image](https://github.com/user-attachments/assets/402b15b1-e32a-47e6-b7a9-083859e548eb)

This specific icon is next to impossible to replicate in Penpot, requiring workarounds listed in the "alternatives" section.

### Describe the solution you'd like.

Allow for rounding of shapes and boolean operations

### Describe alternatives you've considered.

[Rounding the icon by hand](https://x.com/tylerglaiel/status/1807860162222608474), but if the designer started the icon using outlines: <br>
![image](https://github.com/user-attachments/assets/0815e8c4-e775-4847-9f35-59b12398cf1b)

They would have to start over and replicate it doing the outline manually as it can't be flattened to a shape yet (#4829), which can add frustration. Even then, as you can tell, the horizontal line thickness of the skewed rectangle is different than the vertical one, as it's made by hand and isn't perfect. And it takes very long.

![image](https://github.com/user-attachments/assets/69de4bfa-7913-4b42-bf63-34ea7d84fece) <br>
![image](https://github.com/user-attachments/assets/a7ea5baa-08dd-4026-96fb-69c6417c347e)

(not identical to the figma example but you get the idea)

**Comment by madalenapmelo-kp** [comment]
Hi @Manueljlin,

Thank you for the suggestion! This is something that has already been planned into our roadmap, though it hasn't been prioritized yet.

I'm closing this issue but you can find the details here: https://tree.taiga.io/project/penpot/us/3416?backlog-q=paths&no-milestone=1

**Comment by Manueljlin** [comment]
Leaving this information in case it's interesting to developers:

- https://arxiv.org/abs/2405.00127
- https://youtu.be/UrnnCKYw6aA?si=DmRSPBTZZgDE2QvS

I'd recommend anyone with Taiga access to add it to there :D

**Comment by maxwxyz** [comment]
Any news on this?
