### ISSUE TITLE
bug: Multi node drag operation starts from seemingly random node instead of the one that initiates the event

### ISSUE THREAD

**Issue by Manueljlin** [uxbox/uxbox#4893]
### Steps To Reproduce

1. Edit custom pen shape
2. Select multiple nodes
3. Start dragging from one of the selected nodes

### Expected behavior

The nodes will move based on the node that was selected, held and dragged

### Actual behavior

It seemingly picks a random node from the opposite end...

### Screenshots or video

[multi-node-selection-penpot-bugreport.webm](https://github.com/user-attachments/assets/e3fdd764-c167-4887-bdd6-e3ebc3b0ace1)

**Comment by madalenapmelo-kp** [comment]
Hi @Manueljlin,

Thanks for reporting this! Could you let me know which browser you are using?

**Comment by Manueljlin** [comment]
This is on the latest version of Firefox. It's probably also reproducible in Chrome, but to be fair I haven't tested there.

**Comment by madalenapmelo-kp** [comment]
Hi @Manueljlin,

We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8434

**Comment by eeropic** [comment]
duplicate of https://github.com/penpot/penpot/issues/4459

seems like it uses the first point (in drawing order) of the selected points as reference

**Comment by Manueljlin** [comment]
well that sounds fun :(

**Comment by madalenapmelo-kp** [comment]
Hi @Manueljlin,

I'm closing this issue as it is indeed a duplicate of #4459, so it will be tracked there.
