### ISSUE TITLE
bug: When removing a layout or detach a component instance the container becomes a board but should become a group instead

### ISSUE THREAD

**Issue by thomasfrobieter** [uxbox/uxbox#4894]
### Steps To Reproduce

1. create a grid, add contents
2. remove the grid
3. the grid becomes a board, so it's shown in the preview

### Expected behavior

The grid should become a group instead a board, as this has no implications, like showing up in the preview.

### Actual behavior

The grid becomes a board, so it's shown in the preview.

### Desktop (please complete the following information)

- Windows
- Vivaldi

### Environment (please complete the following information)

Host: https://design.penpot.app

**Comment by madalenapmelo-kp** [comment]
Hi @thomasfrobieter,

Could you clarify what you are referring to when you say "preview"? Just to make sure I understand the issue :slightly_smiling_face:

**Comment by madalenapmelo-kp** [comment]
Hi @thomasfrobieter,

Just following-up on this as I believe you are referring to the view mode - you can prevent the board from showing in the view mode by deselecting the option "Show in view mode" (see below) at the Design tab.

![image](https://github.com/user-attachments/assets/c07fd7bb-8f7f-4fe3-8fed-968e2405915b)

**Comment by thomasfrobieter** [comment]
Hi @madalenapmelo-kp, sorry for the delay.

Yes, by "preview" I mean "view mode". I know that it is possible to disable boards from showing up in the preview, but my point here is that it makes no sense at all (to me) to convert them to boards. What's the advantage over groups? I can only see disadvantages.

But it seems that the behaviour has changed a bit since then? Show in view mode is now disabled by default when the layout is removed: https://sharing.clickup.com/clip/p/t4723376/b727b233-1505-4b6f-8b56-7df1bb9777fd/screen-recording-2024-07-31-16%3A10.webm

This prevents unlayouted layouts from showing up in the preview, very nice. 

But still, kind of weird having boards inside boards for nor reason.
