### ISSUE TITLE
bug: Login using GitHub account doesn't work anymmore

### ISSUE THREAD

**Issue by jota0222** [uxbox/uxbox#4896]
### Steps To Reproduce

1. Go to the login screen https://design.penpot.app/#/auth/login
2. Click in the GitHub button to login
3. Check the error returned.

### Expected behavior

It allows me to login in my acount which was created using GitHub 

### Actual behavior

An error is displayed, saying that I'm not allowed to use that authentication method

### Screenshots or video

https://github.com/user-attachments/assets/ccb3d34c-4b9a-425a-a468-1ce209f3d319

### Desktop (please complete the following information)

OS: Linux Debian 10
Browsers tested:
- Firefox Developer Edition129.0b5 (64-bit)
- Google Chrome 126.0.6478.126 (Official Build) (64-bit)

### Environment (please complete the following information)

- Host: https://design.penpot.app

### Frontend Stack Trace

```console
Concedido automáticamente acceso al almacenamiento para el particionado de estado dinámico “https://github.com” en “https://design.penpot.app”. design.penpot.app
[PLUGINS] Loading plugin system index.js:7856:9
Removing unpermitted intrinsics index.js:1970:41
INF [app.main] message="Welcome to penpot", version="2.1.0-13942-gff43d4302", asserts=false, build-date="Wed, 10 Jul 2024 05:45:35 +0000", public-uri="https://design.penpot.app/" impl.cljc:102:17
TRC [app.main.features] hint="initialized features", team="", runtime="" impl.cljc:102:17
Error en el mapeo fuente: Error: request failed with status 404
URL del recurso: https://design.penpot.app/plugins-runtime/index.js
URL del mapa fuente: index.js.map
La cookie “sessionid” ha sido rechazada porque se encuentra en un contexto de sitios cruzados y su “SameSite” es “Lax” o “Strict”. 2 array.js
La cookie “dmn_chk_0190c7ac-b045-740a-a2f5-897e378e1151” ha sido rechazada por un dominio no válido. storage.ts:52:8
Advertencias de cookies 7
INF [app.worker.impl] hint="configure worker", key=:public-uri, val="https://design.penpot.app/" impl.cljc:102:17
INF [app.rasterizer] hint="initialized", public-uri="https://design.penpot.app/", parent-uri="https://design.penpot.app/" impl.cljc:102:17
XHRPOST
https://design.penpot.app/api/rpc/command/push-audit-events
[HTTP/2 401  190ms]
```

### Additional context

It was working 2 weeks ago, starting from the last week, I had to create a password using the option to recover the account.

**Comment by madalenapmelo-kp** [comment]
Hi @jota0222,

This error indicates that the account was created using another authentication method, could you please confirm if logging in with your Google account or email address/password generates a similar error?
