### ISSUE TITLE
Login for selfhosting?

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [uxbox/uxbox#4899]
### Steps To Reproduce

Install penpot via docker

### Expected behavior

Use the software

### Actual behavior

Login is required

### Additional context

So I'm self hosting it but I still need to login?

**Comment by madalenapmelo-kp** [comment]
Hi @4e576rt8uh9ij9okp,

Thanks for the question! If you are self-hosting, you can disable the login with password as mentioned in our documentation here: https://help.penpot.app/technical-guide/configuration/#other-flags :slightly_smiling_face:
