### ISSUE TITLE
Error Importing .penpot file 

### ISSUE THREAD

**Issue by aerahn** [uxbox/uxbox#4944]
### Steps To Reproduce

On the Projects screen, click the three dots next to the + button and select "Import Penpot Files". Select .penpot file (size is approximately 1,300 KB) and then click the continue button. 

### Expected behavior

File is uploaded into projects and can be viewed/edited. 

### Actual behavior

Received error that "0 files have been imported successfully"

### Screenshots or video

Error in console appears as follows:
ERR [app.worker.import]
hint="unexpected error on import process", project-id=#uuid "2f56afe9-16be-8109-8004-bc3dea55ea31"
Error data:
{:type :validation, :code :request-body-too-large}

### Environment (please complete the following information)

Self hosted, Ubuntu-22.04, Penpot (latest version 2.0.0)

### Additional context

Is there a way to increase the size limit?

**Comment by madalenapmelo-kp** [comment]
Hi @aerahn,

Thanks for reporting this! Could you let me know the size of the files you are trying to import? Could you also confirm if you are able to import the file in [design.penpot.app](https://design.penpot.app/)?

**Comment by aerahn** [comment]
Hi, The file size is approximately 1300KB. Unfortunately I can’t actually upload the file to design.penpot.app because it’s on an air gapped network, however, I can tell you that I tried another file that was under 1 MB and it worked, so I’m thinking there may be some configuration setting that isn’t allowing me to upload files over 1MB.

**Comment by madalenapmelo-kp** [comment]
Hi @aerahn,

Is it possible that you have a gateway on front of Penpot that limits the upload size?

**Comment by aerahn** [comment]
Hi, I don't think that's this issue as I've tried some other tests, and think there may also be an issue exporting as a Penpot file. 
Here is what I did:

1. Imported the file "Avataaars by Pablo Stanley" because it's a fairly large Penpot file. 
2. Exported the file as a "penpot" file and noticed the exported file size decreased from 12,016 KB to 3,256 KB.
3. Tried to re-import the file that I just exported and received error. 
4. Again exported the "Avataaars by Pablo Stanley" template, but this time did it as standard file (.svg + .json), size 7,678 KB.
5. Successfully imported the standard file (.svg + .json) file.

I then tried the same thing with the "prototype-examples" file, however, when I tried to import it as a standard file (.svg + .json) I got error messages in the console that said "Error uploading media: ..."

It seems to handle some files, but not others and I'm not sure why.

**Comment by madalenapmelo-kp** [comment]
Hi @aerahn,

I have followed the steps you described on [design.penpot.app](https://design.penpot.app/) and I didn't come across any errors, could you please confirm if you see these errors on [design.penpot.app](https://design.penpot.app/) as well?

**Comment by aerahn** [comment]
Good Morning,
     Thank you for following up. I am using [Coder](https://coder.com/) to run my Docker Penpot instance on an air-gapped network and it turns out the problem was with the Coder setup. I doubt a lot of people will be running Penpot this way, but just in case it is helpful for someone, the solution was for the Coder admins to add the proxy-body size annotation to the ingress portion of the Coder helm charts. 
     Thanks again for looking into this!
