### ISSUE TITLE
bug: Shadow artifacts

### ISSUE THREAD

**Issue by VSGagarski** [uxbox/uxbox#4950]
### Steps To Reproduce

1. Open Simple.penpot
[Simple.penpot.zip](https://github.com/user-attachments/files/16445032/Simple.penpot.zip)
2. On Board one Rectangle with Shadow X:0 Y:1
3. Sometimes when zoom in/out vertical shadows shows up.

System 
`Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux`
Browser
`Google Chrome 126.0.6478.126`

PS

I've check same rectangle in Figma, shadow looks good

### Expected behavior

Rectangle without vertical shadow
![image](https://github.com/user-attachments/assets/3dc71e93-e0e7-484d-a8a9-3fd67ee1ac19)

### Actual behavior

Rectangle with vertical shadow
![image](https://github.com/user-attachments/assets/af2ac015-0f6a-4b81-9ddd-6c3958b8e4d9)

**Comment by madalenapmelo-kp** [comment]
Hi @VSGagarski,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8456

**Comment by madalenapmelo-kp** [comment]
Hi VSGagarski,

The team has reviewed this issue and this is not something that we plan to address in the foreseeable future. You can find more about the motivations for this decision at the Taiga issue: https://tree.taiga.io/project/penpot/issue/8456
