### ISSUE TITLE
bug: Prototype Sitemap is showing both 'source board' and 'destination' boards

### ISSUE THREAD

**Issue by navaneethon** [uxbox/uxbox#4951]
### Steps To Reproduce

Create two big boards, say one is home page and another about page.
Create a button in first page. 
Go to prototype tab and add on-click interaction to the button to navigate to the second page.
Then go to view mode. Click the sitemap dropdown, and you see the button is also in the sitemap.

### Expected behavior

Usually we need only the board in the site map. If all the source boards start appearing in the site map, it is very confusing. Source element (here - the button in a page) should be not automatically added into view mode sitemap.

### Actual behavior

Right now I am seeing 'home page', **'the button**' and 'the about page'.  Source element should be avoided
![penpot_prototype](https://github.com/user-attachments/assets/0c8dff1e-ddee-4b2f-ae94-1387d3e4b570)
![penpot_prototype_sitemap](https://github.com/user-attachments/assets/49984805-c706-4a39-acc3-9f4c08355c8c)

### Desktop (please complete the following information)

OS: Windows 10.
Browser : Chrome

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @navaneethon,

Thank you for reporting this! There is already a task in our backlog to look further into this issue, you can find the details here: https://tree.taiga.io/project/penpot/issue/8416

In the meantime, I'm closing this issue as this is already being tracked at #4868!

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be release soon!
