### ISSUE TITLE
I want support the Korean translation! 

### ISSUE THREAD

**Issue by sangpil** [uxbox/uxbox#4954]
### Is your feature request related to a problem? Please describe.

I can see a lot of uses for penpot in Korean, but it seems like there's a lot to translate compared to other languages. 

### Describe the solution you'd like.

Can I help you speed up your Korean translation progress? Invite me to the weblate project and I'll help you too~. My Weblate id is @sangpil.

**Comment by madalenapmelo-kp** [comment]
Hi @sangpil,

We've already added you to the translation project! Now you just need to accept the invite and [enter here](https://hosted.weblate.org/projects/penpot/frontend/ko/) to start translating.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution :slightly_smiling_face:

**Comment by sangpil** [comment]
Hi. @madalenapmelo-kp~

Thank you for letting me in!
