### ISSUE TITLE
bug: "Design System" sample looks broken

### ISSUE THREAD

**Issue by mindplay-dk** [uxbox/uxbox#4966]
### Steps To Reproduce

1. Sign up
2. Select the "Design System" sample.

### Expected behavior

![image](https://github.com/user-attachments/assets/cab23600-51dc-4579-b19d-7803a3012ad7)

### Actual behavior

![image](https://github.com/user-attachments/assets/4b3cdaae-4e00-4831-a6ef-958abdaa4630)

### Desktop (please complete the following information)

- Chrome `Version 127.0.6533.73 (Official Build) (64-bit)`
- Windows 11

### Environment (please complete the following information)

- `design.penpot.app`

### Additional context

Looks like an issue with loading the file, perhaps an incompatibility with an earlier version of the file format?

The alignment of the text is wrong (on both axis) until you change it, as shown here - first changing it, then changing it back, for some reason makes it align the way it's actually configured to align:

![penpot-bug](https://github.com/user-attachments/assets/f921ec47-833e-479a-a0d8-c3c2ec94940c)

**Comment by myfunnyandy** [comment]
Hi, thanks for the report.

We are about to share the brand new Penpot's design system with the new UI and we don't intend to maintain the old one, which is the one in which you found the problem.

**Comment by mindplay-dk** [comment]
Okay, but isn't this bug likely to affect others when opening Penpot docs from the same earlier version?
