### ISSUE TITLE
feature: ⬤ > ◠ ability to make an open halfcircle from a circle  

### ISSUE THREAD

**Issue by LAGENCECREE** [uxbox/uxbox#4974]
### Is your feature request related to a problem? Please describe.

basic feature like in illustrator 
- draw a primitive like a circle
- add stroke and remove fills
- remove the bottom point
- the half circle is created but the point of the cut are linked
- fail , i wanted an opened half circle (arc)

### Describe the solution you'd like.

- hability to remove segments from shapes

### Describe alternatives you've considered.

using illustrator or equivalents

**Comment by madalenapmelo-kp** [comment]
Hi @LAGENCECREE,

Thanks for the suggestion! We already have a task in our backlog to explore this option further, you can find the details here: https://tree.taiga.io/project/penpot/us/1672?backlog-q=arc&no-milestone=1

In the meantime, I'm closing this issue as this is already being tracked at #928!
