### ISSUE TITLE
bug: possible to register with invitation token, even if login with password is disabled

### ISSUE THREAD

**Issue by june128** [uxbox/uxbox#4975]
### Steps To Reproduce

1. Run penpot using Docker with the flag `disable-login-with-password` set.
2. Invite a user to a team using their email address.
3. Have the user get the invitation email and click on the "Accept invite" button.
4. Have the user sign up, be logged in and see the team workspace.
5. Observe the user only having this one session, since login is disabled, so once they loose it (e.g. getting logged out/cookies cleared/etc.), they can't access the teams workspace anymore.

### Expected behavior

With the `disable-login-with-password` flag set, no user shouldn't be able to register an account, even when having an invitation token, since they can't login.

### Actual behavior

Users can register an account and have one active session. However they can't login on another browser/device and once the session is lost, they can't use penpot anymore.

### Environment (please complete the following information)

- Host: local instance
- OS version: NixOS 24.05
- Docker version 24.0.9, build v24.0.9
- Image version: `docker.io/penpotapp/[exporter/backend/frontend]:2.1.2`
- Setup: hosted via NixOSs `virtualisation.oci-containers` replicating the provided docker-compose setup

### Additional context

I wrote [a quick hotfix for this problem](https://github.com/june128/penpot/commit/f799da132bf5a51015859031f45154172fbf7cd0), so that at least the user account can't be created.
However the sign-up UI shouldn't be there either and no email should be sent in the first place.
Tho especially the email part is harder to implement, since one still wants to send an email to OIDC users for example. Maybe just sending the email and only having the OIDC UI be there is enough tho.

**Comment by superalex** [comment]
Hello @june128 

Actually disabling the register is controlled with whe `disable-registration ` penpot flag, did you try using it?

**Comment by june128** [comment]
@superalex Yes, I have that flag set. However one can still register with an invitation token.
This here seems to be the relevant code enabling that: https://github.com/penpot/penpot/blob/d1d3b4353a743f7dc683671b8d1d8968db48d18b/backend/src/app/rpc/commands/auth.clj#L183-L186
As I read it, registration only fails when registrations aren't enabled and one doesn't have an invitation token, which is fair enough. However it shouldn't allow registrations, when login with password is also disabled (as outlined in the original post).

**Comment by superalex** [comment]
Thank you very much @june128 I'll review this :)

**Comment by madalenapmelo-kp** [comment]
Hi @june128,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8554

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be release soon!

**Comment by superalex** [comment]
Thank you very much @june128 , this PR https://github.com/penpot/penpot/pull/5008 was merged some minutes ago, we will release 2.1.3 docker versions in the next days ;)

**Comment by june128** [comment]
Awesome!! Thanks for the quick fixing! :3

**Comment by superalex** [comment]
You are welcome @june128 , yesterday we published the 2.1.3 versions in dockerhub :)
