### ISSUE TITLE
bug: Penpot login in loop to login.

### ISSUE THREAD

**Issue by eduamf** [uxbox/uxbox#4977]
### Steps To Reproduce

I created my account using Github.
Then I checked my email and the permissions from Github.
Then I tried to login using Github.
After that, the button is not to login, but to create an account again! 

### Expected behavior

Login on Penpot using Github.

### Actual behavior

Trying to create an account again, but the link doesn't call Penpot. It just shows the grants.

### Desktop (please complete the following information)

Windows 11 Pro

**Comment by mistycaseyward12** [comment]
I think turn bug backwards then try to replace it back into code

**Comment by madalenapmelo-kp** [comment]
Hi @eduamf,

I haven't been able to reproduce this issue, could you please confirm if you received the verification email? Could you also confirm which browser you are using?

**Comment by mistycaseyward12** [comment]
Just turn around all the parts like backwards and try code again

**Comment by mistycaseyward12** [comment]
So am I going reproduce

**Comment by eduamf** [comment]
I tried with Chrome and It is working now! Many thanks.
