### ISSUE TITLE
permission to help with traditional Chinese (zh-TW / zh-Hant) translation

### ISSUE THREAD

**Issue by PeterDaveHello** [uxbox/uxbox#4984]
Hello,

As a native speaker of Traditional Chinese with translation experience, I would like to help improve and update the existing Traditional Chinese (zh-TW / zh-Hant) translation for Penpot. Please grant me the necessary permissions to contribute. My Weblate handle is PeterDaveHello, and my profile can be found here: https://hosted.weblate.org/user/PeterDaveHello/.

Thank you!

**Comment by madalenapmelo-kp** [comment]
Hi @PeterDaveHello,

I've already added you to the Weblate project - as soon as you accept the invitation, you can access here to start translating: https://hosted.weblate.org/projects/penpot/glossary/zh_Hant/

Thank you for your contribution!

**Comment by PeterDaveHello** [comment]
Got the invitation, thanks for the quick response!

**Comment by PeterDaveHello** [comment]
@madalenapmelo-kp I am unsure if this needs your attention: #4986, but I should wait until the warning is resolved.
