### ISSUE TITLE
VCS Repository Outdated Warning on Weblate

### ISSUE THREAD

**Issue by PeterDaveHello** [uxbox/uxbox#4986]
There's a warning in Weblate regarding the project https://hosted.weblate.org/projects/penpot/frontend/#alerts:

> **Repository outdated.**
> The VCS repository is not up to date with the upstream one. Please merge changes manually or set up hooks to automate this.
> [Documentation](https://docs.weblate.org/en/latest/admin/continuous.html#update-vcs)

It says this warning first appeared a month ago. Could someone take a look at this?

It would be great to ensure everything is in sync before the translation to avoid any potential issues. Thanks.

**Comment by madalenapmelo-kp** [comment]
Hi @PeterDaveHello,

These alerts depend on someone from our team syncing the translations, which is something we do periodically - specifically before releases, but it's not something we do on a daily or weekly basis.

There should be no reason for concern, so feel free to ignore this alert :slightly_smiling_face:

**Comment by PeterDaveHello** [comment]
Okay, thanks!
