### ISSUE TITLE
feature: Serbian language on Weblate

### ISSUE THREAD

**Issue by crnobog69** [uxbox/uxbox#4991]
### Is your feature request related to a problem? Please describe.

Penpot not on Serbian :(

### Describe the solution you'd like.

I would want to translate Penpot to Serbian.

### Additional context

👋

**Comment by madalenapmelo-kp** [comment]
Hi @crnobog69,

I've already added you to the translation project and also the Serbian language to the languages list. It always makes us really happy to add a new language! :slightly_smiling_face: 

Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/sr/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
