### ISSUE TITLE
bug: enable-odic-registration doesn't seem to be working

### ISSUE THREAD

**Issue by vladimirdulov** [uxbox/uxbox#4995]
### Steps To Reproduce

Relevant issue:
https://tree.taiga.io/project/penpot/issue/8477
https://github.com/penpot/penpot/pull/4963
https://github.com/penpot/penpot/issues/4882

I'm sorry but it doesn't seem to be working.

I've configured Penpot v2.1.2 with the following flags:
```
PENPOT_FLAGS="disable-registration enable-login-with-oidc enable-odic-registration disable-onboarding disable-login-with-password disable-email-verification enable-smtp"
```

I got the following login screen:
![Screenshot 2024-08-13 at 13 42 31](https://github.com/user-attachments/assets/41b2eead-3dcb-4725-be80-f7dcf260739e)

When I click "OpenId" button, it brings `Registration is currently disabled` error.
![Screenshot 2024-08-13 at 13 42 38](https://github.com/user-attachments/assets/0ec835d3-ee49-4a48-97b9-0f8864e317a4)

Could you please check if it's an issue with my configuration or there is still a bug.

### Expected behavior

When both `enable-odic-registration` and `disable-registration` flags specified, new OIDC users would be created and authenticated at the first login. 

### Actual behavior

![Screenshot 2024-08-13 at 13 42 31](https://github.com/user-attachments/assets/41b2eead-3dcb-4725-be80-f7dcf260739e)

When I click "OpenId" button, it brings `Registration is currently disabled` error.
![Screenshot 2024-08-13 at 13 42 38](https://github.com/user-attachments/assets/0ec835d3-ee49-4a48-97b9-0f8864e317a4)

**Comment by superalex** [comment]
I did a test using your PENPOT_FLAGS in https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml with my own PENPOT_OIDC_BASE_URI  PENPOT_OIDC_CLIENT_ID PENPOT_OIDC_CLIENT_SECRET and PENPOT_OIDC_SCOPES and it's working:


https://github.com/user-attachments/assets/b8e7ed63-c11d-47cc-9bbc-a2e7ef61ba4e

**Comment by superalex** [comment]
Thank you very much for reporting @vladimirdulov we are checking what's the problem exactly ;)

**Comment by superalex** [comment]
Mistery solved @vladimirdulov you wrote enable-o**di**c-registration and  should be enable-o**id**c-registration ;)

Regards,

**Comment by vladimirdulov** [comment]
> Mistery solved @vladimirdulov you wrote enable-o**di**c-registration and should be enable-o**id**c-registration ;)
> 
> Regards,

Sorry, cut'n'pasted from the issue comment.
https://github.com/penpot/penpot/issues/4882#issuecomment-2270806997

**Comment by superalex** [comment]
> Sorry, cut'n'pasted from the issue comment.

Ops!, thank you very much, I updated the comment ;)

**Comment by mistycaseyward12** [comment]
That tick is way up in the mistral range down back @amiskov to the right side of your face it[]()![image](https://github.com/user-attachments/assets/cf31abf4-70ae-40d6-8755-1e182481cc01)

**Comment by mistycaseyward12** [comment]
It's a bare face and a deer associated
