### ISSUE TITLE
bug: Issues with Writing Chinese in a Text Box

### ISSUE THREAD

**Issue by QueennaLi** [uxbox/uxbox#4998]
### Steps To Reproduce

![2221723705576_ pic](https://github.com/user-attachments/assets/d8967251-89e5-44ee-bbe1-c1b522149e4f)
Hello, I have an issue related to text input. When I use a text box and first input Chinese characters, then press Enter or Space on the keyboard, an error occurs. I noticed that this same error occurs on your official website as well. However, if I first input text like numbers or English letters without using the Space or Enter key, delete that text, and then input Chinese characters followed by pressing Enter or Space, the error does not occur. I hope this issue can be resolved. Thank you!

### Expected behavior

When using the text box, enter Chinese using enter or space, and there will be no error.

### Actual behavior

 I have an issue related to text input. When I use a text box and first input Chinese characters, then press Enter or Space on the keyboard, an error occurs. I noticed that this same error occurs on your official website as well. However, if I first input text like numbers or English letters without using the Space or Enter key, delete that text, and then input Chinese characters followed by pressing Enter or Space, the error does not occur. I hope this issue can be resolved. Thank you!

**Comment by madalenapmelo-kp** [comment]
Hi @QueennaLi,

Thanks for reporting - this is a known issue that we are already working on fixing, though we don't yet have an exact ETA.

I'm closing this issue here as this is already being tracked on #4163.
