### ISSUE TITLE
feature: Finished the translation

### ISSUE THREAD

**Issue by crnobog69** [uxbox/uxbox#5002]
### Is your feature request related to a problem? Please describe.

[Translation](https://hosted.weblate.org/projects/penpot/frontend/sr/)

### Describe the solution you'd like.

I finished translation today for Serbian language

### Additional context

👻

**Comment by madalenapmelo-kp** [comment]
Hi @crnobog69,

That's great! Thank you so much for your contribution :slightly_smiling_face: 

Our team syncs the translations periodically, specifically before releases so the translations should be available in the near future!
