### ISSUE TITLE
bug: No tooltips for some text properties

### ISSUE THREAD

**Issue by inexcode** [uxbox/uxbox#5012]
### Steps To Reproduce

1. Create a text field
2. Write some text
3. Go to the "Text" section of the right panel
4. Try to hover mouse over different fields

### Expected behavior

There are tooltips for every input. It might not be very clear by the icon that a field is for line height or letter spacing (if I even guessed it right)

### Actual behavior

There are no tooltips for:
- Font selector
- Font size
- Font weight
- Line height (?)
- Letter spacing (?)
- Case selector

There **are** tooltips for:
- Text align
- Sizing
- Decorations
- LTR/RTL switch

### Screenshots or video

[Kooha-2024-08-21-19-25-38.webm](https://github.com/user-attachments/assets/1c766194-a45f-40dc-8b75-5f1f94e2553b)

On this screenshot you can see that there is no `title` on these elements, compared to those, where tooltips work

![image](https://github.com/user-attachments/assets/25a5e63a-6e48-4dec-985d-618f218d51e5)

### Desktop (please complete the following information)

- NixOS 24.11 (unstable)
- Firefox 129.0

### Environment (please complete the following information)

- Self-hosted
- NixOS 24.05
- Docker version 25.0.6
- image: "penpotapp/frontend:latest"
- Default Docker compose config

**Comment by madalenapmelo-kp** [comment]
Hi @inexcode,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8572

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!
