### ISSUE TITLE
bug: too many colors cannot be scrolled

### ISSUE THREAD

**Issue by sneko** [uxbox/uxbox#5024]
### Steps To Reproduce

1. Have a library of colors big enough
2. Create a text
3. Try to customize the color and try to scroll

<img width="580" alt="image" src="https://github.com/user-attachments/assets/dae871ee-37a3-43b7-b0cd-8a4374461bc5">

### Expected behavior

Ability to scroll.

### Actual behavior

Cannot scroll.

### Additional context

Just a suggestion, maybe a searchbar would help also to find specific colors by their name instead of having to focus on each to have the overlay/tooltip.

**Comment by madalenapmelo-kp** [comment]
Hi @sneko,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8590

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be release soon!
