### ISSUE TITLE
bug: Export Crash: Unable to Export Layout1.penpot as SVG, PNG, or PDF

### ISSUE THREAD

**Issue by vm32** [uxbox/uxbox#5026]
### Steps To Reproduce

Open the layout1.penpot file.
Attempt to export the file as SVG, PNG, or PDF.
Observe the crash and the export failure.
[layout1.zip](https://github.com/user-attachments/files/16741326/layout1.zip)

### Expected behavior

The file should be exported successfully in the selected format without causing a crash.

### Actual behavior

The application crashes every time I try to export the file, regardless of the format selected (SVG, PNG, or PDF).

### Screenshots or video

![Screenshot from 2024-08-25 20-24-53](https://github.com/user-attachments/assets/77935bd4-95a2-4be0-ac88-0e0266b30cd8)

### Desktop (please complete the following information)

Arch Linux + windows 11
Firefox last update

### Additional context

Logs :
Hint:    <input>:35:2337: Invalid character in entity name
Prof ID: 82e31d90-3829-8139-8002-c73f0c6c08f3
Team ID: 82e31d90-3829-8139-8002-c73f0c6cb467

Data:
{:type :server-error, :hint "<input>:35:2337: Invalid character in entity name"}

Trace:
d@https://design.penpot.app/plugins-runtime/index.js:3416:42
PENPOT.Dh@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:3476:38
PENPOT.Eh@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:3476:355
PENPOT.Fh@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:3476:308
PENPOT.Tx@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:4423:110
FQa/<@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:4397:236
u@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:242:276
p@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:242:218
d@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:149:99
next@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:158:12
next@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:220:222
d@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:149:99
next@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:158:12
next@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:242:350
d@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:149:99
next@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:158:12
next@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:220:222
d@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:149:99
next@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:158:12
shadow$provide[1]/r/</<@https://design.penpot.app/js/shared.f73e5446a-1724392518.js:150:383

Last events:
[":app.main.data.workspace.notifications/handle-presence"
 ":app.main.data.workspace.notifications/initialize"
 ":app.main.data.workspace.shape-layout/initialize"
 ":app.main.data.fonts/load-team-fonts"
 ":app.main.data.workspace/bundle-fetched"
 ":app.main.data.fonts/team-fonts-loaded"
 ":app.main.data.workspace/workspace-data-loaded"
 ":app.main.data.workspace/libraries-fetched"
 ":app.main.data.workspace.fix-deleted-fonts/fix-deleted-fonts"
 ":app.main.data.workspace.fix-broken-shapes/fix-broken-shapes"
 ":app.main.data.workspace/workspace-initialized"
 ":app.util.router/navigate"
 ":app.main.data.workspace/go-to-page"
 ":app.util.router/navigated"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.changes/apply-changes-localy"
 ":app.main.data.changes/update-indexes"
 ""
 ":app.main.data.changes/commit"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.changes/commit-changes"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/persist-commit"
 ":app.main.data.persistence/run-persistence-task"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/append-commit"
 ":app.main.data.exports/request-simple-export"
 ":app.main.data.persistence/commit-persisted"
 ":app.main.data.persistence/discard-commit"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/run-persistence-task"
 ":app.main.data.persistence/update-file-revn"
 ":app.main.data.dashboard/set-file-thumbnail"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.workspace.viewport/update-viewport-position"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.viewport/update-viewport-position"
 ":app.main.data.exports/clear-export-state"
 ":app.main.data.events/event"]

**Comment by madalenapmelo-kp** [comment]
Hi @vm32,

I haven't been able to reproduce this issue, could you send a screen recording of the steps leading up to the error so that we can look further into it?

**Comment by vm32** [comment]
[Screencast from 2024-08-26 10-55-10.webm](https://github.com/user-attachments/assets/469a5c40-49f9-4859-8c19-44df6b3c3978)
Here is the video for it

**Comment by madalenapmelo-kp** [comment]
Hi @vm32,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8601

**Comment by madalenapmelo-kp** [comment]
Hi @vm32,

Just to let you know that this will be fixed in the next release which should be available very soon!
