### ISSUE TITLE
bug: Welcome page doesn't let me continue if I pick "Product or UX design"

### ISSUE THREAD

**Issue by dfelinto** [uxbox/uxbox#5043]
### Steps To Reproduce

This happens in a fresh installation of self-hosted Penpot running with docker.

Steps to reproduce this:
1. Setup penpot dev environment.
2. Create a new account.
3. Login with the account for the first time.
4. Get at the 3/5 login page, where it asks about What kind of work do you do.

If I pick "Product or UX design" I cannot proceed to the next page.

### Expected behavior

To be able to click on "Next"

### Actual behavior

The "Next" button is grayed out unless I pick a different anwser to the first question ("What kind of work do you do?").

### Screenshots or video

![image](https://github.com/user-attachments/assets/12b533e4-aafc-4a5b-8eaf-f4ac68e5c74e)

### Desktop (please complete the following information)

macOS + Version 128.0.6613.86 (Official Build) (arm64)

### Environment (please complete the following information)

Self-hosted, Docker version 27.1.1, build 6312585
Penpot: develop branch: d703205921c808c9300196625e6b74f3a6240f49

### Additional context

This doesn't happen with the officially deployed penpot. But there also the Product or UX option is not the first on the list.

**Comment by madalenapmelo-kp** [comment]
Hi @dfelinto,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8691

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!

**Comment by dfelinto** [comment]
Thanks :) This bug didn't affect me directly, but I can imagine the metrics team pulling the hair if this issue would ever get deployed.
