### ISSUE TITLE
bug: component doesn't update after text change

### ISSUE THREAD

**Issue by Benjaminpr** [uxbox/uxbox#5048]
### Steps To Reproduce

- Create a component with a text (a title)
- Place the component somewhere 
- Place another instance of the component somewhere else
- Update the text value on the first child component
- Update the font size of the title on the parent component

### Expected behavior

The font size should be updated on both child components

### Actual behavior

The font size is updated only on the second child component, the one with the modified title value isn't updated

**Comment by myfunnyandy** [comment]
Hi, 

This a behavior that we intend to change, it will be part of some other improvements for components. Just in case you are interested, you can see some details at the [user story](https://tree.taiga.io/project/penpot/us/7434).

Thanks!
