### ISSUE TITLE
bug: using arrows while editing a text field changes "context" instead

### ISSUE THREAD

**Issue by dfelinto** [uxbox/uxbox#5049]
### Steps To Reproduce

* Add a rectangle.
* Double-click on its name to rename it.
* While typing a new name, use the arrows to go back one character.

### Expected behavior

I would expect to continue editing the text, but with the active text cursor pointing to a different character.

### Actual behavior

It changes from Layers to Assets.

If I edit e.g, the width of a component and use the arrows, it changes from Design to Prototype and Inspect.

### Desktop (please complete the following information)

macOS + Version 128.0.6613.86 (Official Build) (arm64)

### Environment (please complete the following information)

Self-hosted, Docker version 27.1.1, build 6312585
Penpot: develop branch: https://github.com/penpot/penpot/commit/d703205921c808c9300196625e6b74f3a6240f49

### Additional context

This doesn't happen with the officially deployed penpot.

**Comment by madalenapmelo-kp** [comment]
Hi @dfelinto,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8699

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!
