### ISSUE TITLE
bug: https://design.penpot.app/#/auth/register/success not sending the conformation email.

### ISSUE THREAD

**Issue by zelalemMK** [uxbox/uxbox#5051]
### Steps To Reproduce

Once I login using either Google or GItHub, it won't send the email to confirm. 

### Expected behavior

Send email to confirm. 

### Actual behavior

Email is not sent.

**Comment by madalenapmelo-kp** [comment]
Hi @zelalemMK,

Could you please confirm if you still have not received the verification email? Could you also confirm if you used an email alias to create your account?

**Comment by zelalemMK** [comment]
Still not sending the confirmation email. I used the GitHub SSO option.

**Comment by madalenapmelo-kp** [comment]
Thanks for confirming! We've checked this internally and it doesn't seem like there were any issues sending the verification email, could you check with your email provider in case it is being filtered? 

Could you also confirm if the email address you signed up with is an email alias? As well as confirm that you have checked your spam folder?
 
Using an email alias can cause a delay in receiving the verification email, but it should arrive nonetheless.
