### ISSUE TITLE
bug: inner shadow is on top of frame border, despite "Clip Content" being on

### ISSUE THREAD

**Issue by rangelovd** [uxbox/uxbox#5058]
### Steps To Reproduce

1. Create a frame
2. Add Border (inner)
3. Add Inner Shadow (0% blur, 2px Y, 0% Spread, 100% transparency)

### Expected behavior

Inner Shadow is behind the border

### Actual behavior

Inner Shadow is on top of the border

### Screenshots or video

![image](https://github.com/user-attachments/assets/4f365d01-d4df-495b-9368-acc98db62ba1)

Also notice how shadow on the right is growing incorrectly, though this is another bug

### Desktop (please complete the following information)

Windows 10, Google Chrome

### Environment (please complete the following information)

design.penpot.app

### Additional context

Figma shows inner shadows on top if content is not clipped, and behind if it's cilpped.

**Comment by rangelovd** [comment]
![image](https://github.com/user-attachments/assets/10137378-3e5b-4778-9a8d-1415fb32693e)
![image](https://github.com/user-attachments/assets/e291ccbb-c168-4894-91fe-3b8ab2697728)

This is the element I want to create. If the behavior is expected, please share how should this be achieved.

**Comment by madalenapmelo-kp** [comment]
Hi @rangelovd,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8700
