### ISSUE TITLE
Translation Join Request: Ukrainian

### ISSUE THREAD

**Issue by ghost** [uxbox/uxbox#5059]
Language I want to translate: Ukrainian (українська, ukr_UA) 
Type of translation: change an existing translation
Hosted Weblate username: denkisil

**Comment by myfunnyandy** [comment]
Hi @ossenjoyer!

We've already added you to the translation project and the Ukrainian language is already on the languages list. It always makes us really happy to add a new language! Now you just need to [enter here](https://hosted.weblate.org/projects/penpot/frontend/pl/) and start translating. 

Here you can find more information about how to contribute to translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!

**Comment by ghost** [comment]
I'm sorry, but are you sure what you added me to the translation project? 
I still can't even suggest to strings in ukr_UA.

My Weblate username is `denkisil`, just in case.

![image](https://github.com/user-attachments/assets/7d653d47-02ba-41d5-9060-4e41c91643bc)

**Comment by ghost** [comment]
Oh, I'm apologize. I had to check my inbox first :)

Have a nice day and thank you for invitation!
