### ISSUE TITLE
bug: Show/Hide element icon not visible when layer is locked

### ISSUE THREAD

**Issue by venomgfx** [uxbox/uxbox#5074]
### Steps To Reproduce

1. Add an element.
2. Lock it.
3. Notice the "eye" icon disappears although I can still click on the empty area.

### Expected behavior

I'd expect the eye icon to not disappear when locked.

Locking does not stop you from changing visibility (which is a great thing!), so I'd simply show the eye open/closed icon regardless of the lock status.

### Actual behavior

The eye icon disappears.

### Screenshots or video

https://github.com/user-attachments/assets/00b36ca8-ed6c-48b4-a7f1-32a2bbab06f2

### Desktop (please complete the following information)

- macOS Sonoma 14.6.1 (23G93)
- Chrome 128.0.6613.115

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @venomgfx,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8705
