### ISSUE TITLE
bug: crash when swapping components which are part of another component and are inside a group

### ISSUE THREAD

**Issue by dfelinto** [uxbox/uxbox#5075]
### Steps To Reproduce

Simple way:

1. Import Penpot File:
[Component Swap Bug.zip](https://github.com/user-attachments/files/16910897/Component.Swap.Bug.zip)

2. Select the "Socket / Circle-2" as shown in the picture below, and swap it with the "Socket / Square" component:

<img width="996" alt="image" src="https://github.com/user-attachments/assets/46cac9e0-cc48-43ae-b13c-d0503f0d62ff">

3. At first the socket just disappears, then after a bit it just crashes. This is the report:
[report (1).txt](https://github.com/user-attachments/files/16910890/report.1.txt)

---

How to re-create the file from scratch:

1. Create a circle; make it a component: "Socket / Circle"
2. Create a rectangle; make it a component: "Socket / Rectangle"
3. Create another shape (e.g., Background Rectangle), add it to a group (Widget);
4. Add an instance of the "Socket / Circle" into this group, add a group for the Instance (Sockets).

```
Widget (group)
  |-> Sockets (group)
  |      L-> Instance of "Socket / Circle"
  L> Background Rectangle 
```

5. Make a component out of this group.
6. Create an instance of this component.
7. Swap the "Socket / Circle" instance inside the instance of the Widget component with the "Socket / Rectangle".

### Expected behavior

The component should swap to:

<img width="465" alt="image" src="https://github.com/user-attachments/assets/f3d62e36-7aa9-4d53-95f0-f3861a6a8cde">

### Actual behavior

The element disappear and I get a crash.

### Desktop (please complete the following information)

- macOS 14.5
- Chrome: Version 128.0.6613.119 (Official Build) (arm64)

### Environment (please complete the following information)

Both on https://design.penpot.app/ and on
---
Self-hosted, Docker version 27.1.1, build 6312585
Penpot: develop branch: https://github.com/penpot/penpot/commit/eb720b053a76bd16119ea688ec27e1f210d9b776

### Additional context

I'm trying to create icon components that are used by other components and can be swapped. However not all the icons are the same size, so my idea was to add a group where the icon sits, and move the group inside my component.

This way when I swap the icons, their position will match the previous icon position because the group would be the one translating the icon in relation with the new component.

Sorry if it sounds convoluted, but it should be simpler to understand with the demo file and image.

**Comment by madalenapmelo-kp** [comment]
Hi @dfelinto,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8736

**Comment by hirunatan** [comment]
This is fixed now, it'll be solved in the next release.

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!
