### ISSUE TITLE
bug: Cmd + U shortcut to underline text doesn't work during text editing

### ISSUE THREAD

**Issue by dfelinto** [uxbox/uxbox#5078]
### Steps To Reproduce

1. Add a new text
2. Edit the text (write Penpot)
3. Select the P
4. Try Ctrl + u / Cmd + u

### Expected behavior

I would expect P to get underscored.

### Actual behavior

Nothing happens.

### Screenshots or video

The "misleading" tooltip:

<img width="128" alt="image" src="https://github.com/user-attachments/assets/34048a80-ae19-4556-ab0a-4df58c083b20">

### Desktop (please complete the following information)

macOS 14.5
Chrome: Version 128.0.6613.119 (Official Build) (arm64)

### Environment (please complete the following information)

https://design.penpot.app/

### Additional context

The only way of making this work is by manually clicking on the `U` icon.

For the records, this is what I was doing:

<img width="395" alt="image" src="https://github.com/user-attachments/assets/8c85e563-7345-4027-b2c0-149a6df02d48">

As you can see each line gets a different character to be underlined. To have to manually expand the styling menu and clicking on the U was a bit annoying.

---

Thank you :)

**Comment by madalenapmelo-kp** [comment]
Hi @dfelinto,

Thanks for reporting this! I noticed that this is the case for all text editing shortcuts so I've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8724

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!

**Comment by dfelinto** [comment]
Thanks @madalenapmelo-kp :)
