### ISSUE TITLE
Translation Join Request: German

### ISSUE THREAD

**Issue by Error504TimeOut** [uxbox/uxbox#5079]
Hi,

I'd like to both add and change existing translations for the German language.
My weblate username would be @504timeout

Thank you

**Comment by madalenapmelo-kp** [comment]
Hi @Error504TimeOut,

We'd love you to help us with German translation! I've added you to the Weblate project and as soon as you accept the invitation you can start translating :slightly_smiling_face: 

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thanks!
