### ISSUE TITLE
feature: Finished the swedish translation

### ISSUE THREAD

**Issue by Henke1983** [uxbox/uxbox#5084]
### Is your feature request related to a problem? Please describe.

I have done the translation for Swedish in Weblate
https://hosted.weblate.org/projects/penpot/frontend/sv/
My weblate user: @henrik@thexorb.com

### Describe the solution you'd like.

I finished translation today for Swedish language

**Comment by madalenapmelo-kp** [comment]
Hi @Henke1983,

That's great! Thank you so much for your contribution 🙂

Our team syncs the translations periodically, specifically before releases so the translations should be available in the near future!
