### ISSUE TITLE
feature: UI Scale

### ISSUE THREAD

**Issue by m-bobi** [uxbox/uxbox#5100]
### Is your feature request related to a problem? Please describe.

The issue is when doing stuff on a laptop, you are already limited to the visibility, everything is too ""clunky"" and all in your face. I feel like the UI is larger than it needs to be.

### Describe the solution you'd like.

I want to be able to scale down/up the UI of the tool.

### Additional context

The thing I had to do in order to achieve this "feature" was,

- Go back to main menu / Where the design files are 
- Zoom out there
- Go back into my design file

I want this process to be a bit simpler, if possible. 

(i am loving the tool, absolutely amazing 👍🏽)

**Comment by madalenapmelo-kp** [comment]
Hi @m-bobi,

Thanks for the suggestion! You can achieve this directly in the workspace by decreasing the browser zoom, does this option work for you?

**Comment by m-bobi** [comment]
Hey @madalenapmelo-kp,

Yes, It works by increasing/decreasing the browser zoom, but to make this happen I have to leave the design file, go back to the "home page" and do it there, then go back to the design file. I guess when you do this, you will have the zoom icon on the address bar which solves this issue. It just takes a lot of unnecessary steps.

**Comment by madalenapmelo-kp** [comment]
You should be able to increase/decrease the browser zoom within the design file (please see the screenshot below for reference), without the need to go back to the dashboard.
![image](https://github.com/user-attachments/assets/3b6f99c9-8d9e-4e7e-8792-199f37511c8e)

**Comment by m-bobi** [comment]
This is my first time seeing that zoom there haha, that's way easier! I'm sorry for any inconvenience I caused. 😂 😅

**Comment by madalenapmelo-kp** [comment]
No inconvenience at all, I'm glad I could help :slightly_smiling_face:
