### ISSUE TITLE
bug: Update File API EndPoint with Changes Object

### ISSUE THREAD

**Issue by arthurpeixotomelo** [uxbox/uxbox#5112]
### Steps To Reproduce

1. Generate an access token
2. Get a Penpot project and annotate their file ID
3. Make a HTTP POST call to the Penpot API for the update-file RPC specifying:
    - An Authorization: Token YOUR_ACCESS_TOKEN header
    - An Accept: application/json header
    - A Content-Type: application/json header
    - The required params:
        - ID = FILE_ID
        - SESSION_ID (?) = FILE_ID
        - REVN = INT
        - CHANGES = copy example with less params from OPENAPI JSON (add-page)

```javascript
const body = {
    "id": env["PORTFOLIO_ID"],
    "sessionId": env["PORTFOLIO_ID"],
    "revn": 0,
    // "changes": [{"type": "add-page" }],
}

const name = 'updateFile'
const res = await fetch("https://design.penpot.app/api/rpc/command/update-file", {
    "method": "POST", "headers": {
        "Accept": "application/json", 
        "Content-Type": "application/json", 
        "Authorization": `Token ${env["PENPOT_TOKEN"]}`
    }, "body": JSON.stringify(body)
})

const data = await res.json()

console.log(res.status)

Deno.writeTextFile(`./${name}.json`, JSON.stringify(data, null, 2))
```

### Expected behavior

It should create a new page.

### Actual behavior

Whenever changes array param is set it gives out an error of type validation. Otherwise, when changes array is not set it returns with status 200 and the last successful changes (with are none because they error out).

### Screenshots or video

when changes is empty:
![image](https://github.com/user-attachments/assets/9eb5b7b1-8b0e-4b08-9825-eada4e1a6b0d)

when changes has anything:
![image](https://github.com/user-attachments/assets/ad7e9fd5-3031-4681-b481-2989849b47b3)

### Environment (please complete the following information)

- Host: https://design.penpot.app/
- Version: 2.0

### Additional context

I opened up a [discussion](https://github.com/penpot/penpot/discussions/4180) to get answer or help of what could be me doing something wrong but got no answer... and since I couldn't find a similar bug/attempt using the API I'm filling this issue as it could be a real bug.

**Comment by madalenapmelo-kp** [comment]
Hi @arthurpeixotomelo,

I've been trying to reproduce this issue but so far I have been unable to. Just to confirm, if you set just `"changes": [{"type": "add-page" }]` you get the **400 Bad Request**?

**Comment by arthurpeixotomelo** [comment]
Exactly, whenever i add arguments in changes array it return 400 with the responde being json I'd taken screenshot. I'd tried others params like "add-color", "del-page" worked same....I'd even tried to add incorrect arguments like:
"changes": [{"addPage": {"type": "add-page"}}]
but it returns slightly diferent error message

**Comment by madalenapmelo-kp** [comment]
Could you share the error response JSON when setting just `"changes": [{"type": "add-page" }]` and no other arguments?

**Comment by arthurpeixotomelo** [comment]
Sorry for the delay, i spend some time organizing the code i did for test to create a repo to reproduce and share the errors, but as i did the test to generate the errors...now it's working.
this is the same request as before:
![image](https://github.com/user-attachments/assets/38fa92e7-b651-46eb-92eb-98f4d015cda8)
this is the response now:
![image](https://github.com/user-attachments/assets/410ef472-92dd-4adb-b514-c4b0d8b3388e)
this is the getFile response with a new page:
![image](https://github.com/user-attachments/assets/e4fd7bef-ca2d-468f-a3bf-a1b2b818006e)
this is the last check to make sure it really worked:
![image](https://github.com/user-attachments/assets/6de9b8dc-90a1-4c64-90bf-ea434f892bc8)

also i'd noticed it got a new release recently and found this in the changelog [JSON API](https://tree.taiga.io/project/penpot/us/8372)

**Comment by madalenapmelo-kp** [comment]
Thanks for confirming that it's working now! In that case, I hope you don't mind that I close this issue :slightly_smiling_face: 

Also we recommend opening discussions at the [Penpot Community](https://community.penpot.app/) instead of the Discussions as the Penpot team is no longer participating in Discussions.
