### ISSUE TITLE
Request for Translation to Spanish

### ISSUE THREAD

**Issue by 1d645wadwa789d4wa9** [uxbox/uxbox#5116]
Hello,

I would like to contribute by translating into Spanish. I would like to:

- Translate new texts.
- Make changes to existing translations.

My Weblate username is `crendai`.

Thank you!

**Comment by madalenapmelo-kp** [comment]
Hi @crendai,

We'd love you to help us with the Spanish translation! I've added you to the Weblate project and as soon as you accept the invitation you can start translating 🙂

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thanks!
