### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by youseiushida** [uxbox/uxbox#5128]
Hello👋,

I found a closed issue regarding Japanese translation (#2126 ). I would like to participate in translating the project into Japanese. My Weblate account username is `@healthitJP`.

Thank you for your excellent work!

**Comment by madalenapmelo-kp** [comment]
Hi @healthitJP,

We'd love you to help us with the Japanese translation! I've added you to the Weblate project and as soon as you accept the invitation you can start translating 🙂

Here you can find more information about how to contribute to the translations: https://help.penpot.app/contributing-guide/translations/

Thanks!
