### ISSUE TITLE
Weblate permission request

### ISSUE THREAD

**Issue by TethysPlex** [uxbox/uxbox#5129]
I would like to help translate Penpot to Chinese (Simplified) and Chinese (Traditional).
My Weblate username is IsCycleBai

**Comment by madalenapmelo-kp** [comment]
Hi @IsCycleBai,

We'd love you to help us with the Chinese translations! I've added you to the Weblate project and as soon as you accept the invitation you can start translating 🙂

Here you can find more information about how to contribute on the translations: https://help.penpot.app/contributing-guide/translations/

Thanks!

**Comment by IsCycleBai** [comment]
Thanks, but Weblate still seems to prompt me that I do not have sufficient permissions in the Chinese (Simplified) translation.

**Comment by madalenapmelo-kp** [comment]
Just to confirm, you are trying to access the project here: https://hosted.weblate.org/projects/penpot/frontend/

Is that correct?

**Comment by TethysPlex** [comment]
Sorry, I just didn't see the invitation in my mailbox.
