### ISSUE TITLE
bug: Nested flex layouts don't get updated when toggling visibility with the <del> button

### ISSUE THREAD

**Issue by martonlente** [uxbox/uxbox#5143]
Hi, 

When a flex layout is nested within a component, its sub-items' visibility can be toggled on or off, making instances very flexible. This nice feature doesn't work as expected though when toggling visibility by pressing the `<del>` button. See the videos below for details. 

### Expected behavior

When toggling visibility with the mouse, everything works as expected:

https://github.com/user-attachments/assets/4c3e7b4e-baed-4c42-bdde-c0d195f9555d

### Actual behavior

When toggling visibility with the `<del>` button, the following issues happen:
- When toggling a visible item, the item gets hidden, but the layout doesn't get updated. 
- When about toggling an invisible item, pressing the `<del>` button doesn't do anything.

https://github.com/user-attachments/assets/3a513ca2-3647-4d8a-bd96-7a4ed4d60bf7

### Additional context

I'd expect the same behaviour when toggling an item with the mouse or the `<del>` button (similarily to how it works in for example Figma). 

I've attached the Penpot file for reference as well: [Blender BCON 2024 programs brochure bug report.penpot.tar.gz](https://github.com/user-attachments/files/17276363/Blender.BCON.2024.programs.brochure.bug.report.penpot.tar.gz)

Thank you for looking into this!

**Comment by madalenapmelo-kp** [comment]
Hi @martonlente,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/8919

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!

**Comment by martonlente** [comment]
That's amazing, thank you!
