### ISSUE TITLE
Incorrect russian translation

### ISSUE THREAD

**Issue by inexcode** [uxbox/uxbox#5148]
After updating to Penpot 2.2 from 2.1, my typography components now look broken

![image](https://github.com/user-attachments/assets/737234a5-001b-415a-a792-80649f52f6ac)

This caused by incorrect translation of the following string: https://hosted.weblate.org/translate/penpot/frontend/ru/?checksum=44758aa0aeeb82b0#history

Please revert this translation. I would like to do it myself, but it requires more privileges. I would appreciate if you add me as a translator, so I can fix the issues without creating noise on GitHub. My Weblate ID is `@inexcode`.

**Comment by madalenapmelo-kp** [comment]
Hi @inexcode,

Thanks for reporting this! I've added you to the Weblate project as a Translator, as soon as you accept the invite you can start contributing!

Thank you again!
