### ISSUE TITLE
bug:  cannot toggle between move tool and comment tool with shortcuts

### ISSUE THREAD

**Issue by Steve-Carlton** [uxbox/uxbox#5154]
### Steps To Reproduce

have move tool selected (select move tool w/ mouse or shortcut 'v')
select comment tool with mouse or shortcut (c)
press move tool shortcut (v)

### Expected behavior

I expect to be able to select the move tool from the comment tool when hitting the v key regardless of what tool I had selected prior to comment tool.

### Actual behavior

No input seems to register. I select another tool, e.g. board, then select move tool as a work around.

### Desktop (please complete the following information)

Win11
Edition	Windows 11 Pro
Version	23H2
Installed on	‎9/‎26/‎2022
OS build	22631.4249
Experience	Windows Feature Experience Pack 1000.22700.1041.0

Chrome: 
Version 129.0.6668.101 (Official Build) (64-bit)

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @Steve-Carlton,

Thanks for reporting this! We already have a task in our backlog to look into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/7524

I've linked this report there as well so that hopefully we can prioritize this soon!

**Comment by madalenapmelo-kp** [comment]
Hi @Steve-Carlton,

Thanks for reporting this! We already have a task in our backlog to look into this, you can find the details here: https://tree.taiga.io/project/penpot/issue/7524

I've linked this report there as well so that hopefully we can prioritize this soon!

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by madalenapmelo-kp** [comment]
Hi @Steve-Carlton,

I'm closing this issue here as this is already being tracked at issue #4589 :slightly_smiling_face:
