### ISSUE TITLE
bug: Grid Editor overflows with too many columns (or rows)

### ISSUE THREAD

**Issue by lplath** [uxbox/uxbox#5185]
### Steps To Reproduce

1. Add a grid layout
2. Add a lot of columns

### Expected behavior

The column-panel should crop the overflowing text

### Actual behavior

The column-panel grows wider than the layout-container, hiding part of the interface.

### Screenshots or video

![edit_grid_panel](https://github.com/user-attachments/assets/132e650f-a284-4afa-b1fe-84a383a4bf0f)

**Comment by madalenapmelo-kp** [comment]
Hi @lplath,

Thanks for reporting this! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/9057

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!
