### ISSUE TITLE
bug: When the first character of the text I input is Simplified Chinese, the system crashes

### ISSUE THREAD

**Issue by impro5** [uxbox/uxbox#5186]
### Steps To Reproduce

1. Use Google Chrome to enter the design file
2. Choose a text tool
3. Insert a text box into the file and enter Simplified Chinese
4. System crash, enter error reminder page

### Expected behavior

Support direct input of Simplified Chinese

### Actual behavior

Input Simplified Chinese error

### Screenshots or video

https://github.com/user-attachments/assets/caec79d6-d64a-44bc-a46f-58aa5186e4f7

### Desktop (please complete the following information)

- windows 11 or MAC OS12.1
- Chrome 129.0.6668.71

### Environment (please complete the following information)

self-host
- openEuler 22.03 (LTS-SP3)
- Docker version 27.3.1, build ce12230

**Comment by madalenapmelo-kp** [comment]
Hi @impro5,

Thanks for reporting - this is a known issue that we are already working on fixing, though we don't yet have an exact ETA.

I'm closing this issue here as this is already being tracked on https://github.com/penpot/penpot/issues/4163.
