### ISSUE TITLE
bug: SVG Import Issue - Text content converts text to vector path instead of retaining text format

### ISSUE THREAD

**Issue by mrajaganapathy** [uxbox/uxbox#5187]
### Steps To Reproduce

Steps to Reproduce:

1. Create an SVG file with text content.
2. Import or paste the SVG into Penpot.
3. Observe that text content is converted to vector paths.

### Expected behavior

Expected Behavior:
Text content should remain editable as text, not converted to vector paths.

### Actual behavior

Actual Behavior:
Text content is converted to vector paths, losing editability.

### Screenshots or video

<svg xmlns=http://www.w3.org/2000/svg width="102" height="19" viewBox="0 0 102 19">
  <text id="Test" data-name="Test" transform="translate(0 15)" fill="#909090" font-size="14" font-family="Roboto-Regular, Roboto"><tspan x="0" y="0">Test angle order</tspan></text>
</svg>

**Comment by madalenapmelo-kp** [comment]
Hi @mrajaganapathy,

Thanks for reporting this! Unfortunately, this is something that we do not support right now.

When you paste or import an SVG, it is treated like an SVG node and converting it to a format that Penpot can support would mean losing information about the text or having a text that is not properly placed.

I'm closing this issue as we won't be able to address it at this time but if anything else comes up please feel free to open a new issue 🙂
