### ISSUE TITLE
bug: Changes not saved

### ISSUE THREAD

**Issue by muzirian** [uxbox/uxbox#5217]
### Steps To Reproduce

make some changes,
wait for the button to change to check mark to say its saved.
Close the window, open again

### Expected behavior

Should show the last edits, as it said saved

### Actual behavior

Saved changes lost

### Desktop (please complete the following information)

M1, firefox 131.0.3

### Environment (please complete the following information)

design.penpot.app

**Comment by muzirian** [comment]
looks like, its syncing slow.
cos when i added missing assests and when exporting again i noticed it duplicated, thinking changes synced later.

**Comment by madalenapmelo-kp** [comment]
Hi @muzirian,

Thanks for reporting this! Could you please confirm if you are experiencing this on Firefox only or on other browsers as well? Could you also share a screen recording of this behavior?
