### ISSUE TITLE
Thai Translation

### ISSUE THREAD

**Issue by latenightdef** [uxbox/uxbox#5230]
Hello, I'd like to become a translator for Thai language.

My Hosted Weblate username is [@latenightdef](https://hosted.weblate.org/user/latenightdef/)

Thank you for the awesome prototyping software!

**Comment by madalenapmelo-kp** [comment]
Hi @latenightdef,

We've already added you to the translation project and also the Thai language to the languages list. It always makes us really happy to add a new language! 

Now you just need to accept the invitation, [enter here](https://hosted.weblate.org/projects/penpot/frontend/th/) and start translating. Once there is a significant % of translated texts we will publish the language so it will be available in the languages list at the user's profile.

Here you can find more information about how to contribute to translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution!
