### ISSUE TITLE
docker images not yet updated to v2.3

### ISSUE THREAD

**Issue by glowingkitty** [uxbox/uxbox#5251]
After the official release announcement of v2.3 I tried to upgrade my local penpot (via docker compose/docker) to the latest version. Turns out, its still on v2.2. Are you aware of this and will the docker updates follow the coming days?

Looking forward to try out the updated self hosted v2.3 on my machine.

**Comment by madalenapmelo-kp** [comment]
Hi @glowingkitty,

We expect to update the Docker images in the coming days, I'll keep you posted!

**Comment by madalenapmelo-kp** [comment]
The Docker images have now been updated!
