### ISSUE TITLE
bug: plugin manager doesn't show up in v2.3.1 docker

### ISSUE THREAD

**Issue by glowingkitty** [uxbox/uxbox#5258]
### Steps To Reproduce

I upgraded my penpot from 2.2 to 2.3(.1) today by using the docker compose pull command. It all worked fine, and the interface of penpot greets me with the "What's new in 2.3" screen, explaining also plugins and how to install them. But when I then open a penpot design, the plugin button that is supposed to show up at the top doesn't exist.
What now?

### Expected behavior

The plugin button should show up in the frontend.

### Actual behavior

Button doesn't show up.

### Screenshots or video

![image](https://github.com/user-attachments/assets/40dce5c2-45d2-4026-8887-eb31b57bd8bb)

### Desktop (please complete the following information)

- MacOS 15.1 (MacBook Pro M1)
- Arc v1.67.0

### Environment (please complete the following information)

- self hosted penpot, via localhost

**Comment by LloydNA** [comment]
Same issue here, shortcut to open plugin manager doesn't work, and neither the option is present in the three dots menu:
<img width="232" alt="imagen" src="https://github.com/user-attachments/assets/e36fdb45-1045-4a88-900c-0dd967fff1dc">

**Comment by impro5** [comment]
Same issue here

**Comment by superalex** [comment]
Hi @glowingkitty and @LloydNA did you add the enable-feature-plugins to the PENPOT_FLAGS variable in the docker-compose.yaml file?

**Comment by roadbearstudios** [comment]
Same problem here, even after adding the enable-features-plugin flag.

**Comment by superalex** [comment]
@roadbearstudios could you please show us your docker-compose.yaml ?

**Comment by roadbearstudios** [comment]
> @roadbearstudios could you please show us your docker-compose.yaml ?

Ofcourse, but when I looked at the docker-compose.yaml I saw I added the enable-features-plugin flag to the environment of the backend. I tried adding it to the environment of the frontend, and now it works.  Thanks!

**Comment by superalex** [comment]
You are welcome @roadbearstudios :)

**Comment by glowingkitty** [comment]
why is this off by default? and not explained anywhere how to activate it? Conscious decision or no one had the time yet and its on the todo list?

**Comment by superalex** [comment]
Both things @glowingkitty , it will be on by default soon and we still have to update the doc ;)

**Comment by LloydNA** [comment]
> Hi @glowingkitty and @LloydNA did you add the enable-feature-plugins to the PENPOT_FLAGS variable in the docker-compose.yaml file?

Thanks, it worked now with that flag
