### ISSUE TITLE
bug: can't login, in Safari

### ISSUE THREAD

**Issue by glowingkitty** [uxbox/uxbox#5259]
### Steps To Reproduce

- opened localhost (self hosted penpot) in safari
- login interface shows up
- I enter my login data (which are 100% correct, as tested minutes before in arc browser)
- when clicking login, I get a "Something wrong has happened" 
- docker compose log shows no clear explanation either (why not? errors should show up in the log)

### Expected behavior

login should work

### Actual behavior

login doesn't work in safari

### Screenshots or video

![image](https://github.com/user-attachments/assets/6fbca3f3-1d64-4795-a81a-53b4d88443e7)

### Desktop (please complete the following information)

- MacOS 15.1, MacBook Pro M1
- Safari 18.1

### Environment (please complete the following information)

- self hosted penpot, via localhost

### Backend Stack Trace
```
penpot-frontend-1   | 192.168.65.1 - - [07/Nov/2024:08:43:14 +0000] "GET /api/rpc/command/get-file?id=4942a9a0-9d09-814f-8005-1bbd5872f1d6&features=layout/grid&features=styles/v2&features=components/v2&features=fdata/shape-data-type&project-id=4942a9a0-9d09-814f-8005-1bbd4ebc8eb7 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
penpot-frontend-1   | 192.168.65.1 - - [07/Nov/2024:08:43:14 +0000] "GET /api/rpc/command/get-file-object-thumbnails?file-id=4942a9a0-9d09-814f-8005-1bbd5872f1d6 HTTP/1.1" 200 1754 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
penpot-postgres-1   | 2024-11-07 08:43:15.120 UTC [26] LOG:  checkpoint starting: time
penpot-frontend-1   | 192.168.65.1 - - [07/Nov/2024:08:43:15 +0000] "GET /api/rpc/command/get-font-variants?team-id=4942a9a0-9d09-814f-8005-1bbd33a74498 HTTP/1.1" 200 33 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
penpot-frontend-1   | 192.168.65.1 - - [07/Nov/2024:08:43:15 +0000] "GET /api/rpc/command/get-file-libraries?file-id=4942a9a0-9d09-814f-8005-1bbd5872f1d6 HTTP/1.1" 200 33 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
penpot-postgres-1   | 2024-11-07 08:43:15.562 UTC [26] LOG:  checkpoint complete: wrote 5 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.411 s, sync=0.007 s, total=0.442 s; sync files=5, longest=0.005 s, average=0.002 s; distance=17 kB, estimate=12161 kB
penpot-frontend-1   | 192.168.65.1 - - [07/Nov/2024:08:46:37 +0000] "POST /api/rpc/command/login-with-password HTTP/1.1" 200 525 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15"
penpot-frontend-1   | 192.168.65.1 - - [07/Nov/2024:08:46:37 +0000] "GET /api/rpc/command/get-profile HTTP/1.1" 200 79 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15"
```

**Comment by llunacb** [comment]
This happened to me. I found it was a problem with cookies not saving correctly and fixed it with the `disable-secure-session-cookies` flag in the backend configuration.

**Comment by madalenapmelo-kp** [comment]
Hi @glowingkitty,

There was another report of this issue https://github.com/penpot/penpot/issues/5362 and it seems like the user was able to find https://github.com/penpot/penpot/issues/5362#issuecomment-2500048313, can you check if this works for you?

>It maybe you're not using ssl. Try to use ssl. There must be an option about secure cookie in penpot flags (as far as I can remember), you can disable it.

**Comment by niwinz** [comment]
The fix is using  `disable-secure-session-cookies` flag.
