### ISSUE TITLE
bug: Protyping : Not able to connect to the main board

### ISSUE THREAD

**Issue by navaneethon** [uxbox/uxbox#5297]
### Steps To Reproduce

1. Create two boards say, Home page and About page, in which about page is flex layout with elements fill the area.
2. In prototype mode when we connect a button from home page to the about page, the connection automatically select the child elements inside the about page. I am not able to connect to the main board

### Expected behavior

We should be able to connect to the main board and not the children inside the board.

### Actual behavior

The connection automatically select the child elements inside the about page. I am not able to connect to the main board

### Screenshots or video

https://github.com/user-attachments/assets/a6981e63-0b79-4a33-b8d9-0a167d97f05e

### Desktop (please complete the following information)

OS : Windows
Browser: Chrome

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @navaneethon,

Inner boards have priority to get selected as an interaction target so this is working as intended. We have recently revisited this behavior but decided not to change it for the time being.

You can select the main board as the destination to navigate to from the **Prototype** mode tab: https://help.penpot.app/user-guide/prototyping/#prototyping-actions-navigate :slightly_smiling_face:

**Comment by navaneethon** [comment]
Hi Madalena Melo,
Thank you for your quick reply.
