### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by motzarello** [uxbox/uxbox#5310]
Hi, I would like to become a translator for the Italian language. 

My weblate username is @NicolaBortoletto.
https://hosted.weblate.org/user/NicolaBortoletto/

Thank you very much, I hope I can help!

**Comment by madalenapmelo-kp** [comment]
Hi @motzarello,

We've already added you to the translation project - now you just need to accept the invitation, [enter here](https://hosted.weblate.org/projects/penpot/frontend/it/) and start translating.

Here you can find more information about how to contribute to translations: https://help.penpot.app/contributing-guide/translations/

Thank you very much for your contribution! :slightly_smiling_face:
