### ISSUE TITLE
bug: Typo in onboarding screens

### ISSUE THREAD

**Issue by nwanduka** [uxbox/uxbox#5319]
### Steps To Reproduce

1. Go to https://penpot.app/
2. Click on "sign up for free"
3. Sign up with google or email

### Expected behavior

Here's what the correct copy should read:
Image 1: "We are beyond _excited_ about ..."
Image 2: "Find everything you need in _our_ full comprehensive ..."
Image 3: ♥

### Actual behavior

There are a couple of typos in the onboarding copy. I'll share screenshots below highlighting the typos.
Image 1: "We are beyond _excitement_ about ..."
Image 2: "Find everything you need in _ouor_ full comprehensive ..."
Image 3: "<3" (I assume this should be a heart emoji but it didn't render properly)

### Screenshots or video

Image 1 👇
![Screenshot (170)](https://github.com/user-attachments/assets/5f9958e2-2686-4a0f-9058-868fb8c0f615)

Image 2 👇
![Screenshot (171)](https://github.com/user-attachments/assets/c066e222-911c-429b-a9ec-e07990989163)

Image 3 👇
![Screenshot (172)](https://github.com/user-attachments/assets/544262af-2405-4d1b-ae6a-2e3fb280c6a7)

**Comment by madalenapmelo-kp** [comment]
Hi @nwanduka,

Thanks for reporting this! We will fix it as soon as possible!
