### ISSUE TITLE
bug: self-hosted can't login

### ISSUE THREAD

**Issue by rmGFW** [uxbox/uxbox#5362]
### Steps To Reproduce

follow the [documents](https://help.penpot.app/technical-guide/getting-started/#install-with-docker)
and create new user in the webpage ,then try login ,
<img width="510" alt="image" src="https://github.com/user-attachments/assets/3e7ba537-7bd2-48a2-bfd2-c76e8dd5b1fe">

### Expected behavior

login success

### Actual behavior

login failed

**Comment by konotorii** [comment]
1. What are your start up flags for frontend and backend?
2. Are you accessing the site through localhost, static IP, or reverse proxy?

**Comment by rmGFW** [comment]
yes through reverse proxy

**Comment by kakalos12** [comment]
I remembered that I had the same issue. It maybe you're not using ssl. Try to use ssl. There must be an option about secure cookie in penpot flags (as far as I can remember), you can disable it.
