### ISSUE TITLE
bug: invited teammate can't join team

### ISSUE THREAD

**Issue by henrychris** [uxbox/uxbox#5375]
### Steps To Reproduce

- create a penpot account
- create a team
- go to team management
- invite a new team member

### Expected behavior

I expected my teammate to receive an email with a link. They would click this link and be prompted to create an account, and afterwards, join the team.

### Actual behavior

Instead, my teammate was prompted to create an account, but afterwards saw the error page saying: "Invite invalid. The invite might be cancelled or expired". 

### Screenshots or video

![image](https://github.com/user-attachments/assets/83013ab4-6912-45a8-8b4c-b85937d14cc5)

### Desktop (please complete the following information)

OS: Linux Mint 22 Cinnamon
Browser: Firefox Developer Edition 133.0b9 (64-bit)

### Environment (please complete the following information)

We are using penpot.app.

### Additional context

I pasted the JWT token from copying the link into jwt.io, and saw this data: "�4����Vq|Y\u0010�*�\u001fwJ�o�\u0015l%*�\u00198�TH�&\u001c\u0019����\u000b=". JWT.io reported that the JSON object within is invalid.

**Comment by madalenapmelo-kp** [comment]
Hi @henrychris,

Thanks for reporting this! Could you go to the team's invitations on Penpot and confirm that the invitation did not expire?

Could you also ask the user to confirm that the email address they are logged into Penpot with is the same as the email address in the invitation?

**Comment by henrychris** [comment]
I created the invite and waited for him to get the email. We were in the same room, so barely a minute passed. The email didn't arrive, so I copied the link and sent it.
Following the link showed the error I mentioned.

There weren't up to two minutes between creating and clicking the link.

As for the email, yes he used the same email address as in his PenPot account

**Comment by madalenapmelo-kp** [comment]
Thanks for confirming! Could you try re-sending the invitation?

**Comment by henrychris** [comment]
I have resent it and it worked this time. My sincere apologies though, my teammate had a brainfart and repeatedly gave the wrong email and confirmed the wrong one was right. it's all good now, thank you!

**Comment by madalenapmelo-kp** [comment]
Hi @henrychris,

Thank you for letting me know :slightly_smiling_face:

**Comment by RunninglVlan** [comment]
> Hi @henrychris,
> 
> Could you also ask the user to confirm that the email address they are logged into Penpot with is the same as the email address in the invitation?

Hi, could you modify the error message, so that users wouldn't have issues with invitations in the future?
My colleague invited me to my official e-mail, I accepted invite, didn't have the account, so created it, used GitLab for that, but there I had different mail. And only through this issue I now understand that the problem is with e-mails not matching

**Comment by madalenapmelo-kp** [comment]
Hi @RunninglVlan,

Thanks for the suggestion! We've added this to our backlog on Taiga so that we can explore this option in the future, you can find the details here: https://tree.taiga.io/project/penpot/issue/9436
